### ISSUE TITLE
[amp-ad] AdSense support for screen orientation and viewport width changes

### ISSUE THREAD

**Issue by SchnWalter** [ampproject/amphtml#10011]
## What's the issue?

The `amp-ad` element for the `AdSense` provider does not properly support device orientation or viewport width changes.

On the [Create an AMP ad unit](https://support.google.com/adsense/answer/7183212) AdSense documentation you are instructed to "Create a responsive ad unit".

And on the [About responsive ad units](https://support.google.com/adsense/answer/3213689) AdSense documentation you see that a key feature is "Support for ad size changes after a screen orientation change"

## How do we reproduce the issue?

If this is a bug please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else.  Then provide step-by-step instructions for reproducing the issue:

1. Generate a responsive Ad slot in AdSense. See: https://support.google.com/adsense/answer/7183212
2. Embed the previously generated slot inside an AMP page using a fixed height or responsive Ad layout.
```
<amp-ad
  type="adsense"
  layout="fixed-height"
  height="250"
  data-ad-client="..."
  data-ad-slot="...">
</amp-ad>
```
3. Check the page on a mobile device and change the device orientation.

## What browsers are affected?

All browsers.

## Which AMP version is affected?
I've tested this on AMP Version: 1497462282545, which is the latest, released 3 days ago.

**Comment by SchnWalter** [comment]
Also, the served ads are (most of the times) responsive, so, a fixed-height layout would cause the width of the Ad to change when the browser width changes (not just the orientation), but the Ad `<iframe>` inside the AMP 3p frame.html doesn't get updated, it remains at the original width.

**Comment by SchnWalter** [comment]
@lannka, in #10136 (Weekly Status) you stated that you work(ed) on "Supporting AdSense responsive ads feature". I could not find any PR (opened or closed) on that subject.

Could this issue be related to your update?

**Comment by jasti** [comment]
@SchnWalter We might need to re-trigger the ad on screen orientation or browser width changes. Adding AdSense folks for comment - @ konakk and @tlong2. Tom, can you please add Charlie to the thread as well? I don't have his handle handy.

**Comment by tlong2** [comment]
@charliereams

**Comment by SchnWalter** [comment]
And we need to make sure that on screen width changes we don't trigger to many requests, maybe we could hide the ad and display the placeholder when the resize event is triggered and set a timeout that is pushed back with each subsequent width change and/or maybe we could also set a minimum refresh interval, just like in the upcoming Ad refresh feature. Otherwise publishers won't be happy, nor will the adveritzers.

**Comment by lannka** [comment]
@SchnWalter that's something @charliereams is actively working on. PR has not been sent out yet.

**Comment by jasti** [comment]
@charliereams Do you have an update?

**Comment by charliereams** [comment]
This is fixed in the responsive implementation, but note that:

1) The new behaviour is to fix the size of the slot to an exact pixel size early in its lifecycle. Therefore if the device is rotated, the slot and the ad will stay the same size, so there's no risk of truncation or distortion. However the ad may not look great in the new orientation (especially landscape to portrait, where there is a risk that the ad is now wider than the viewport.) Actually resizing and requesting a new ad is a nice-to-have but it's quite challenging to implement in a way that doesn't disrupt reporting and viewability. We'll see if it's something people demand urgently.

2) The fix only applies to new tags. We don't plan to change the behaviour of existing fixed-height tags. (Someone else is welcome to tackle that though -- @keithwrightbos may take a view.)
