### ISSUE TITLE
Reliably shutdown server.js when gulp crashes

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#10013]
Lets put in some signal trap or similar to make sure that `build-system/server.js` always shuts down when gulp crashes. It often keeps lingering and then blocks restarting gulp because it hangs on to the port.

**Comment by erwinmombay** [comment]
is there any easy way to replicate the "gulp" crashing and leaving the port in use?

**Comment by cramforce** [comment]
My gulp often crashes with `Abort trap: 6`.

**Comment by rsimha-amp** [comment]
I noticed this too. I made some [initial changes](https://github.com/ampproject/amphtml/blame/2939ecc3c90780e0386f5fc097ba356486f6b4c1/build-system/tasks/serve.js#L52) to the wrapper gulp task in `build-system/tasks/serve.js` that starts and stops the server that cause the server to cleanly exit, but I'm sure there are other flows that keep the zombie process lingering.

Will take a look.

**Comment by rsimha-amp** [comment]
Update: I've poked around the stack of processes created by `gulp serve`, and can see that the `gulp` process is starting a `node` process via third party code in `gulp-webserver', which is then detaching itself from the parent process. I doubt we can do anything in `build-system/tasks/serve.js` or `build-system/server.js` to detect the death of the parent process and pass on a signal to the child process, since the `gulp` process won't be around to run that code when it crashes. (I'm going to try a few more things before definitively saying that the problem lies in third party code.)

One thing we could do in `server.js` is to see if the port is in use, and then provide a yes/no prompt to the user to kill the old orphaned process, or abort the current instance. (I don't think it's good to kill an old process without confirmation, since it may be in use in another console window.)

@cramforce, @choumx, @erwinmombay, @jridgewell, posting this update in case any of you have comments.

**Comment by cramforce** [comment]
+1 adding prompt to kill server binding to port.

**Comment by rsimha-amp** [comment]
@cramforce, instead of killing the server currently using the port, I chose a slightly different solution. See description of #10095.

**Comment by cramforce** [comment]
Saw that before this actually :)

I think they are a bit complementary, but I'm happy with just the other solution.

**Comment by rsimha-amp** [comment]
You're right that they're complementary. I'm happy to add an optional prompt to kill whatever old process is sitting on the port, since it's a reasonable expectation that people would want to do that most of the time.

**Comment by rsimha-amp** [comment]
Hmm... adding a user prompt and blocking while the user says yes/no is non-trivial in nodejs. I'm going to close this issue and reopen it if people continue to complain about zombie processes or ports in use :)
