### ISSUE TITLE
Consider integrating ampproject/amphtml with lgtm analysis

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#10092]
From #10090

ltgm.com provides a mechanism for automatic code reviews for github projects, and has detected a bunch of errors in ampproject/amphtml at https://lgtm.com/projects/g/ampproject/amphtml/alerts/

There is a way to integrate lgtm with amphtml PRs at https://lgtm.com/docs/lgtm/config/pr-integration

Let's do it if we think the alerts generated for the amphtml repo are useful.

**Comment by rsimha-amp** [comment]
@cramforce, most of our alerts seem to be stemming from [ads/ads.extern.js ](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/1061e50dddc381f10ed52b12c25a0675a83db71d/files/ads/ads.extern.js). Are these valid alerts, and if so, is there any reason we're evaluating all those terms without using them?

**Comment by rsimha-amp** [comment]
Per @cramforce, it appears that lgtm needs admin access to ampproject/amphtml for CI integration. 

@xiemaisi, is there a way around this where the integration can be done with just commit read/write access?

**Comment by xiemaisi** [comment]
@cramforce: if you add `@externs` annotations to those files lgtm will stop complaining.

@rsimha-amp: I believe admin access is currently required, @samlanning should be able to provide more details.

**Comment by samlanning** [comment]
Hi @rsimha-amp 

Unfortunately not. The way that GitHub integrations work require us to set up a webhook on a repository on GitHub, that will then send an HTTP request to our servers whenever a pull request is opened or modified. To do this, an admin/owner of the repository (someone who has access to the repository settings) needs to be the person to set this up.

**Comment by rsimha-amp** [comment]
@samlanning, just to be sure that I understood you correctly, can you comment on which of these statements is true?

1. Only the admin / owner of the `ampproject/amphtml` GH repository can set up integration with lgtm
2. The lgtm plugin needs to be granted admin access to ampproject/amphtml for the integration to work, and cannot make do with just committer read/write access

If 1 is true but 2 is false, @cramforce has admin access and can help set things up. However, if 2 is true, I'm afraid that's a deal breaker.

**Comment by samlanning** [comment]
correct, 1 is true, 2 is false.

The only permissions that are requested by lgtm when an admin hits the button that sets up PR integration is:

* Permission to set up webhooks
* Permission to post commit statuses

We don't even need to request read / write access to the repository, since we're not adding commits, and we're only currently integrated with public repositories.

**Comment by cramforce** [comment]
@samlanning Github recently started allowing you to do what you need without admin access. We cannot grant this by policy. We recently installed https://percy.io/ which is very similar to LGTM and doesn't need admin access

**Comment by samlanning** [comment]
@cramforce 

To clarify, lgtm does **not** need request admin access to the whole repository, just for the ability to add and remove repository hooks. The permissions we ask for are `admin:repo_hook` and `repo:status`.

`admin:repo_hook` is considered an "admin" permission because it allows for us to delete webhooks too. The reason we ask for this is so that if you choose to uninstall PR integration via our website, we can uninstall the webhook from your repository.

I understand that *this* may be against your policy, and unfortunately, for now this is the only way in which you can set up lgtm integration.

We are very excited about the new GitHub Apps API, which as you said would solve this problem for us entirely. It's something we'd love to start using, but sadly for the time being it's not on our development schedule.

**Comment by cramforce** [comment]
Could we just manually set up the webhooks?

**Comment by samlanning** [comment]
Unfortunately this isn't quite as trivial as it may sound, and there are a number of problems with this:

* Firstly, we loose the HMAC functionality that we use to authenticate notifications are genuinely from github (we send a Pre-Shared key for use in the HMAC from lgtm.com to GitHub when setting up the webhooks). Sending the PSK over email, etc... does not seem like a good idea.
* We still need to be granted oauth tokens that are authorised to post commit statuses, and manually put this into lgtm's database.

We're having some internal discussions about some short/medium term improvements to this (i.e. until we start using the Apps API). We'll post here if anything changes.

**Comment by cramforce** [comment]
Thanks. For what its worth, we have no problem granting access to commit statuses at all!

**Comment by xiemaisi** [comment]
@cramforce, @rsimha-amp: I understand we no longer require admin permissions for setting up PR integration; would you like to give it another go?

**Comment by cramforce** [comment]
Thanks. Done.

**Comment by rsimha-amp** [comment]
@xiemaisi, @samlanning, thanks for the help!

**Comment by rsimha-amp** [comment]
@xiemaisi, @samlanning, I have a follow up question.

How does a member of `ampproject/amphtml` see lgtm results from past PRs? When I go to https://lgtm.com/projects/g/ampproject/amphtml/ci/, I see a warning about not having admin access even though I'm signed in to lgtm with my github account. I know there's at least one successful [run](https://lgtm.com/projects/g/ampproject/amphtml/rev/pr-6888df723bfe5b8c5d7be93daf23d2751fca8b86) that I'd expect to have shown up on that list.

I'm looking for something similar to the [list](https://travis-ci.org/ampproject/amphtml/pull_requests) Travis shows. Does an admin need to explicitly invite members to view past lgtm results?

**Comment by samlanning** [comment]
Hi @rsimha-amp 

Currently there is no view on lgtm.com that lets you see all PR analyses that have been run, like the list travis shows. The only way to currently see results is via the status links on github.

**Comment by rsimha-amp** [comment]
@cramforce FYI, I'm fixing all the LGTM errors in #12597.

@samlanning I've noticed that over the past few months, errors have snuck in to our code because the `lgtm` check either takes a really long time (therefore, we can't make it a required check) , or because it remains stuck in the `Running analyses for revisions` state.

For example, see #12544, which introduced [these](https://lgtm.com/projects/g/ampproject/amphtml/rev/a31fac1dacb64e0805dbafc8d46185586bea4892) errors, but remained stuck in the `Running analyses...` state.

<img width="724" alt="" src="https://user-images.githubusercontent.com/26553114/34796913-2ca1f654-f625-11e7-9edf-aa59d710dba0.png">

Or see #11830, which introduced [these](https://lgtm.com/projects/g/ampproject/amphtml/rev/pr-410ae91da1428c3c7ea6a8635fb5a1ceff0521f9) errors, but showed a green check mark even though there were new errors.

<img width="729" alt="" src="https://user-images.githubusercontent.com/26553114/34797492-856062de-f626-11e7-9ae4-d972e4b1ac21.png">

I think it would be useful if the `lgtm` check were to show a red `X` mark in cases where a PR introduces new errors. WDYT?

**Comment by rsimha-amp** [comment]
@cramforce I think we can avoid future errors by allowing LGTM to post comments on pull requests when an error is found. 

This can be done via the lgtm integration settings for `ampproject/amphtml`, by unchecking the `Deactivate comments` checkbox. See https://lgtm.com/docs/lgtm/using-lgtm-analysis-continuous-integration

**Comment by cramforce** [comment]
I activated comments.

**Comment by samlanning** [comment]
Hi @rsimha, this is likely due to our caching mechanisms... did you originally log in and view this page from this account before you gave it admin access?

(this particular cache has an abnormally long expiry of 24hrs, we should change this). In any case i've cleared the cache now, can you see if this fixes it? You may need to refresh a couple of times.

**Comment by rsimha** [comment]
@samlanning That worked. Thanks!

Follow up question: Clearly, the `amphtml-lgtm-bot` account needed to have admin access to our GitHub repository in order to initially set up LGTM.com integration. However, does it need admin access after the integration is set up? Can I downgrade the account from admin access to write access, and have the GitHub integration continue to work?

**Comment by samlanning** [comment]
@rsimha Awesome!

And no I don't think you can downgrade, it needs admin access to be able to set the commit statuses I believe?

**Comment by rsimha** [comment]
@samlanning Sounds good. I'll leave the account with admin access. Thanks for the help!

For posterity, here's an example of what incoming LGTM.com comments to `ampproject/amphtml` will look like: https://github.com/ampproject/amphtml/pull/14339#issuecomment-377666805

/cc @cramforce
