### ISSUE TITLE
Testing: Easier stubbing of services

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#10128]
Since this has come up a few times now. Context: https://github.com/ampproject/amphtml/pull/9866#discussion_r123108935

We could do this pretty simply by changing `services.js` to export an object/class instead of `serviceForDoc` functions. Could be nice for classes that need a lot of services stubbed.

### Before
```js
// services.js
actionServiceForDoc(nodeOrDoc) { ... }

// my-class.js
import {actionServiceForDoc} from '../src/services';
class MyClass {
  foo() {
    this.actionService().doSomething();
  }
  actionService() { // This is annoying to do for every service.
    return actionForDoc(this.ampdoc);
  }
}

// my-test.js
import {MyClass} from '../src/my-class.js';
sandbox.stub(MyClass, 'actionService').returns(mockActionService);
```

### After
```js
// services.js
export class Services {
  static actionForDoc(nodeOrDoc) { ... }
}

// my-class.js
import {Services} from '../src/services';
class MyClass {
  foo() {
    Services.actionForDoc(this.ampdoc).doSomething();
  }
}

// my-test.js
import {Services} from '../src/services';
sandbox.stub(Services, 'actionForDoc').returns(mockActionService);
```
It'd be a straightforward (if slightly annoying) refactor. I also checked that this would work with Babel's transpile. 

/cc @lannka @alanorozco @keithwrightbos @taymonbeal @jridgewell

**Comment by taymonbeal** [comment]
One request I'd like to make: Provide an API for swapping out test doubles of specific services at the window level, instead of requiring the test author to call `sandbox.stub` on a global function. I fear that the latter is likely to cause unintended state leaks.

`describes.js` might be the right place for such an API to live. Perhaps an additional field, `serviceStubs: (!Object<string, function(): *>|undefined)`, could be added to `AmpTestSpec`. Or perhaps a `registerServiceStub` function could be added to `env`.

**Comment by lannka** [comment]
This is a good start. Can we go deeper, I would love to stub a service method with one line:
stubService(win, 'action', 'get').returns('abc');

@taymonbeal we clear sandbox on teardown, is that what you meant by "unintended state leaks". I'm not sure if it's wise to stub every services. Sometime, for some services, we do want to include the real impl, like `timer`, `resource`.

**Comment by lannka** [comment]
Actually I introduced such [a helper method](https://github.com/ampproject/amphtml/blob/master/testing/test-helper.js#L26) a while ago.

**Comment by alanorozco** [comment]
@lannka That's pretty cool, I hadn't seen that. This stubs at a slightly different level, though, since it requires service id.

**Comment by taymonbeal** [comment]
That's part of it, yeah. There've definitely been cases where things that were supposed to be cleared on teardown weren't, and I think an approach of "at the end of each test destroy this entire window and everything in it" helps with this, somewhat.

Speaking from my own experience dealing specifically with the `Xhr` service, if a service needs to support test doubles, then its API becomes "two-sided". If I'm writing a unit test for a component that depends on `Xhr`, then I don't want to care whether that component is internally calling `fetch` or `fetchJson` or `fetchDocument` or what; I only want to concern myself with what actual requests it makes, so that I can intercept these, verify that they're as expected, and send test-double responses. On the flip side, I also don't want to stub `fetch` and `fetchJson` and `fetchDocument` separately in every test; I want to specify the test double's behavior just once, and have the class that implements it take care of implementing the entire `Xhr` public API based on that specification. So one side of `Xhr`'s API is for consumers (code that needs to actually fetch things over the network), and the other side is for providers of test doubles. Currently, the latter is not available.

While I haven't personally tried to deal with `Timer` in tests, I would expect that if you wanted to test code that depended on it without actually waiting for the passage of time, similar considerations would apply, since the code under test might be using `delay` or `promise` or something else entirely, and the test ought not to break if those implementation details change.

My preferred approach, therefore, would be:
1. Implement the aforementioned API for substituting an entire service object at the window level. (This would not necessarily have to be to the exclusion of stubbing individual methods! But the option to do this should be there.)
2. For each service like `Xhr` or `Timer` that exposes a multi-method public API over a core of common functionality, define a separate interface for just that core. (This wouldn't have to be done for every such service right away, only as the need comes up among test authors. I personally need it for `Xhr` though.) Then, through an optional constructor parameter or some equivalent, allow the service class to accept an alternate implementation of that interface. (PR #9338 _almost_ does this for `Xhr`, but it mutates `fetchImpl` on existing `Xhr` instances instead of making a fresh one in each fixture; I now think the latter approach is better.)

With this, test authors would have all the tools they need to write stable and hermetic tests of code units that depend on services. (Including to wrap these tools with higher-level APIs, as I did in #9338.)

**Comment by choumx** [comment]
1. Using `sinon.sandbox` is definitely better than mutating `window` since a sandbox is scoped to a single file, so even failing to restore a sandbox can't affect tests in other files.

2. Test doubles would definitely work in the general case, but might be overkill for `Xhr` and `Timer` since the core functionality of those classes have well-defined interfaces. I.e. why doesn't stubbing `Window.fetch` or sinon's [Fake Xhr](http://sinonjs.org/releases/v1.17.7/fake-xhr-and-server/) and [Fake Timer](http://sinonjs.org/releases/v1.17.7/fake-timers/) satisfy your use cases?

**Comment by lannka** [comment]
@taymonbeal it's really mocking at browser API level (in your word the "core"), or at AMP service level. From unit test's point of view, I'm fine with both approaches, as long as it's easy to write and read.

Your other PR is kind of a mixture. 
- You mocked at browser API level (MockXhr), passed into the service by mutating a private member. I see your point of not changing window object as being afraid of "state leakage". But here I agree with @choumx we can trust sinon sandbox is doing the right teardown work. 
- The `XhrMock` is a bit weird class to me. I would think it's a service level mock, but it's really just some helper functions.

BTW, `timer` was a bad example, allow me to replace it with `platform`.

**Comment by jridgewell** [comment]
My only two cents: I agree with mocking `fetch`, not our XHR implementation. Mainly so we can do it when testing our XHR implementation. 😉
