### ISSUE TITLE
amp-bind: Easier toggling of classes 

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1032]
I believe we discussed this before, but I think it might the time to do this.

``` html
<button on="tap:element.toggleClass(someClass)">
```

or similar.

I'd like to avoid this being used to toggle ads, so I was thinking to limit it on elements that do not contain ads. One could still e.g. change zIndexes to put ads behind content. Anyone have an idea how to make it more foolproof?

CC @dvoytenko @rudygalfi

**Comment by rudygalfi** [comment]
@cramforce Do you think this is the same as #1017?

**Comment by AliberGzz** [comment]
This will be possible ?

**Comment by sebastianbenz** [comment]
Have we got a timeline for this? Would love to have a show/hide boilerplate button for http://amp-by-example.appspot.com.

**Comment by dvoytenko** [comment]
We got according now that could be used for this, I think. /cc @sriramkrish85

**Comment by sriramkrish85** [comment]
@sebastianbenz `<amp-accordion>` should let you do that.
`amp-accordion` is now experimental - we will need to add validator support for this.

**Comment by sebastianbenz** [comment]
@sriramkrish85  @dvoytenko Works splendid! When is it going to be released?

**Comment by sebastianbenz** [comment]
@sriramkrish85 @dvoytenko FYI https://amp-by-example.appspot.com/amp-accordion.html

**Comment by dvoytenko** [comment]
@sebastianbenz I'll leave it to @rudygalfi to state the dates.

**Comment by rudygalfi** [comment]
We need to get the validation in. @ericlindley-g is going to track that down with @Gregable.

**Comment by rudygalfi** [comment]
@ericlindley-g @choumx To resolve if this is covered by bind, could be folded into bind, or should be closed.

**Comment by ericlindley-g** [comment]
Yep—covered by bind. Closing for now, but folks should feel free to re-open if there's a need for a simpler syntax, as proposed above.

**Comment by westonruter** [comment]
@ericlindley-g I think more is needed here. In particular, what if there are multiple variable classes on an element already (such as those added to `body` by WordPress), and we need to toggle just one of them? Currently this can't be done with bind because isn't able to mutate the existing classes.

If bind were able to reference the existing state that could be a solution. So maybe something like this, with WP template code to show intended usage:

```
<body <?php body_class(); ?> [class]="ampConf.mobileMenu ? add( 'no-scroll' ) : remove( 'no-scroll' )'" >
```

It would be important for `amp-bind` to compare the `class` attribute in a way that ordering of the class names doesn't matter, or else we'd get:

> amp-bind: Default value for [class] does not match first expression result (). This can result in unexpected behavior after the next state change.

So perhaps it is better to go the action route as initially proposed.

```php
<body id="body" <?php body_class(); ?>>
<button on="tap:body.toggleClass('no-scroll')">Toggle menu</button>
```

There should probably be `addClass` and `removeClass` as well.

**Comment by ericlindley-g** [comment]
Good point, @westonruter — reopening and /cc @choumx for visibility

**Comment by choumx** [comment]
A bit clunky, but you could store the default classes in an `<amp-state>` component:

```html
<body [class]="toggleVariable 
    ? defaultBodyClasses.concat('no-scroll') 
    : defaultBodyClasses">
```

But yea, this sounds a lot like #10622. And @sebastianbenz's suggestion in particular: https://github.com/ampproject/amphtml/issues/10622#issuecomment-317829677

`toggleClass()` action makes sense for simple cases, but won't interoperate with `amp-bind` so we could build both options. We do have `show()` and `hide()` actions which also overlap with `amp-bind`'s functionality. This might make a decent GFI actually.

**Comment by westonruter** [comment]
Here's how I ended up implementing a state-based toggle on the `body` element in WordPress:

```php
<body <?php body_class(); ?> [class]="navMenu.expanded ? <?php echo esc_attr( wp_json_encode( get_body_class( 'sidebar-open' ) ) ) ?> : <?php echo esc_attr( wp_json_encode( get_body_class() ) ); ?>">
```

Importantly, this only would allow for toggling a single class. It's also not very pretty.

**Comment by westonruter** [comment]
In the WordPress theme there is a button that invokes jQuery to `toggleClass`:

```php
<button class="menu-toggle" aria-controls="primary-menu" aria-expanded="false"><?php esc_html_e( 'Primary Menu', '_s' ); ?></button>
```
Here's how I worked out to accomplish (mostly) the same with AMP, with hacking a `label` to work like a button that toggles a hidden checkbox:

```php
<amp-state id="siteNavigationMenu">
	<script type="application/json">
		{
			"expanded": false
		}
	</script>
</amp-state>
<input
	id="site-navigation-expanded"
	type="checkbox"
	hidden
	on="change:AMP.setState( { siteNavigationMenu: { expanded: event.checked } } )"
>
<label
	class="menu-toggle"
	for="site-navigation-expanded"
	tabindex="0"
	role="button"
	aria-controls="primary-menu"
	aria-expanded="false"
	[aria-expanded]="siteNavigationMenu.expanded ? 'true' : 'false'"
>
	<?php esc_html_e( 'Primary Menu', '_s' ); ?>
</label>
```
Notice importantly that the “button” isn't only needing to cause the `body` class to toggle. It also needs to cause the  `aria-expanded` attribute to toggle. This would be well served by an **AMP action which toggles some state**. With such a state toggle, the above `checkbox`+`label` could be restored as a `button`, something like this:

```php
<button
	class="menu-toggle"
	aria-controls="primary-menu"
	aria-expanded="false"
	[aria-expanded]="siteNavigationMenu.expanded ? 'true' : 'false'"
	on="change:AMP.toggleState( 'siteNavigationMenu', 'expanded' )"
>
	<?php esc_html_e( 'Primary Menu', '_s' ); ?>
</button>
```

Where `toggleState` takes a list of args that corresponds to the state tree branch to toggle.

**Comment by sebastianbenz** [comment]
Interesting problem. Here is another approach that supports toggling multiple `body` classes: 

```
<body class="a b c" [class]="globalState.join(' ')">
  
  <amp-state id="globalState"><script type="application/json">["a", "b", "c"]</script></amp-state>
  
  <amp-bind-macro id="toggle" 
                arguments="value" 
                expression="globalState.includes(value) ? globalState.filter(x => x != value) : globalState.concat(value)" />
  
  <button on="tap:AMP.setState({ globalState: toggle('a') })" aria-expanded="true" [aria-expanded]="[globalState.includes('a')]">toggle 'a'</button>
  <button on="tap:AMP.setState({ globalState: toggle('b') })" aria-expanded="true" [aria-expanded]="[globalState.includes('b')]">toggle 'b'</button>
  <button on="tap:AMP.setState({ globalState: toggle('c') })" aria-expanded="true" [aria-expanded]="[globalState.includes('c')]">toggle 'c'</button>

</body>
```

Full example: https://jsbin.com/qilalovife/edit?html,output. 

It's still not very nice, but solves the problem. It'd be nicer if amp-bind-macro would support actions (or a new extension `amp-bind-action`.

**Comment by westonruter** [comment]
@sebastianbenz Good idea to use concat. That made me realize I could actually avoid manipulating the body class state entirely, in favor of dynamically concatenating a class name based on whether or not some other state value changes:

```php
<body <?php body_class(); ?> [class]="minnow.bodyClasses.concat( minnow.navMenuExpanded ? 'sidebar-open' : '' ).filter( className =&gt; '' != className )">
<amp-state id="minnow">
	<?php
	$state = array(
		'bodyClasses'     => get_body_class(),
		'navMenuExpanded' => false,
	)
	?>
	<script type="application/json"><?php echo wp_json_encode( $state ); ?></script>
</amp-state>
```

Given this value of the `[class]` attribute, the `.concat( minnow.navMenuExpanded ? 'sidebar-open' : '' )` part could be repeated any number of times according to the class names that should toggle based on changes to state props. Maybe it's simpler than your example, but maybe it's not as great either.

Note: The `=&gt;` here is due to a limitation in the AMP for WordPress plugin, noted in https://github.com/Automattic/amp-wp/pull/1111/commits/52b3616e03bd9e129eb87dfe8d9d0c0662029117

Aside: I found that if you return an array as the value of `[class]` it automatically gets concatenated with a space.

**Comment by westonruter** [comment]
What I wrote in https://github.com/ampproject/amphtml/issues/1032#issuecomment-386191349 was wrong. It is trivial to toggle state already using straight `AMP.setState()`.  All that is needed is to add an `on` attribute like so:

```html
<button
	class="menu-toggle"
	aria-controls="primary-menu"
	aria-expanded="false"
	on="tap:AMP.setState( { siteNavigationMenu: { expanded: ! siteNavigationMenu.expanded } } )"
	[aria-expanded]="siteNavigationMenu.expanded ? 'true' : 'false'"
>...
```

**Comment by sebastianbenz** [comment]
:-) even better. I thought being able to toggle multiple classes on the same element was your problem, which can result in awkward nested if statements.

**Comment by Hoodlum-Z** [comment]
I've solved how to toggle the hamburger menu in AMP, but now I don't know how to change the symbol that I'm using  ☰ to the ✕ when the menu is active/open.

The example on WP-AMP website uses php to display the button, but apparently I can't alter that function because it runs on the server rather than on button click. Therefore, how am I supposed to change the content of my button?

I know how to implement the actual AMP navbar, but want to do it this way so I can learn more. Thanks.
