### ISSUE TITLE
Validator support for `amp-font`

### ISSUE THREAD

**Issue by NataliaLKB** [ampproject/amphtml#1037]
![image](https://cloud.githubusercontent.com/assets/8774970/11509443/04947526-9856-11e5-85e4-bab6bcb99199.png)

We have started experimenting with `amp-font` on our pages. When will the validator be updated to support the `amp-font` tag?

Thank you!

**Comment by powdercloud** [comment]
We have not updated the released Javascript yet because we're trying to keep it roughly in sync with the web indexing support at Google, to reduce confusion. However, it's implemented, so it should happen soon (days, possibly weeks due to the Thanksgiving break here in the US). https://github.com/ampproject/amphtml/blob/master/validator/validator.protoascii (do a CTRL+F for amp-font).
Why is it useful to keep stuff in sync? We're trying to limit a situation wherein someone's webpage would be considered invalid by our indexer (it doesn't know amp-font yet) even though the Javascript tool reports it being valid. This would be confusing because you wouldn't get the error message you're getting now, but the page may not get retrieved in a search or surfaced in some UI element, etc. So, depending on what your needs are, you may wish to wait with using the amp-font tag - e.g., specifically don't use it yet on pages which you want surfaced as amphtml in Google search. Of course you're welcome to try the tag in your internal experiments.
Why does it take so long? Search engines deal with a fair amount of state (all those processed / indexed pages), so the usual speed of putting code live is not as swift as with typical Javascript projects. Sorry bout that and thanks for the patience.
Also: We have open-sourced the validator so if you're feeling adventurous feel free to run build.py in the validator directory, after that you can use codegen/validate (a NodeJS script) on your file and see what the bleeding edge, unreleased version thinks about your file. This is still a bit rough, in fact not sure someone has tried it. :-)
/cc: @Gregable in case I got something wrong here.

**Comment by NataliaLKB** [comment]
@powdercloud thanks for your answer. It does make sense to keep things in sync with the indexer. As much as possible, I certainly support synchronising your releases.

Given that `amp-font` is a component listed in the [spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-components.md) that we have been encouraged to test, is it possible to give a clearer idea of when this will be valid both by the indexer and the runtime validator? It is a feature we are eager to release.

**Comment by powdercloud** [comment]
@NataliaLKB We can't promise (too many moving parts) but we're hoping amp-font should arrive next week. Will post an update here.
As for the spec, I think the problem is that thus far it doesn't have a release process so we may have some version skew there as well. Sorry there isn't a good answer yet.

**Comment by erwinmombay** [comment]
@dvoytenko brought up the idea of having a place to see the status for anything new we've announced/built to help in the future.

**Comment by NataliaLKB** [comment]
> brought up the idea of having a place to see the status for anything new we've announced/built to help convey information in the future.

@erwinmombay @dvoytenko that sounds like a good idea. Keep us updated! :smile:

**Comment by Gregable** [comment]
The validator now supports amp-font.

**Comment by NataliaLKB** [comment]
Thanks, that is great :smile: !
