### ISSUE TITLE
IAB ads.txt specification appears to be incompatible with AMP

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#10388]
The IAB has released the final ads.txt specificatrion https://iabtechlab.com/wp-content/uploads/2016/07/IABOpenRTBAds.txtSpecification_Version1_Final.pdf

The relevant parts are [emphasis added]

> 3.1 ACCESS METHOD
> ...
> If the server response indicates the resource does not exist (HTTP Status Code 404), the advertising system can assume no declarations exist and that **_no advertising system is unauthorized to buy and sell ads on the website_**.

and

> 5.5 SUBDOMAINS
> Subdomains are currently not supported. This is an open item that will be discussed in future iterations of the spec. _**When writing spiders, implementers should request the /ads.txt from the domains that are driving significant requests for advertising**._ Publishers should post the /ads.txt file on their root domain and not on subdomains. The crawler should strip the subdomains when creating the crawler’s URL list. The public suffix list [12] should be utilized in implementing subdomain stripping.

This implies that a page served from `example-com.cdn.ampproject.org` will use the `ads.txt` file for the`ampproject.org`root domain.

As written there is no way for a publisher to control who can sell ads on their amp pages when served on a CDN.

**Comment by jasti** [comment]
@jpettitt All ad requests in AMP to DoubleClick and AdSense send the context.canonical URL as the src URL. Do you understand how the buyside determines the host URL and if it's different than the ad request? 
I've also scheduled time with the spec authors to understand proposals for subdomains. 

CC @ampproject/a4a

**Comment by jpettitt** [comment]
It's not clear how they are determining things but since the objective is to prevent fraud you can't trust anything that can be controlled by the page author.

**Comment by jasti** [comment]
For this specific case, the page author can't though? The AMP DoubleClick and AdSense tags are the ones passing the page URL. 
Anyway, will update after I've synched with the authors. Lot is up in the air.

**Comment by michaelkleber** [comment]
There is no problem at all with ads.txt and AMP and the CDN.

When an AMP page issues an ad request, the auction that results is selling space on some _publisher-domain_ URL.  (In the adsense and doubleclick case we use the canonicalURL; some other ad companies might use the sourceURL.)

Advertisers looking to buy in that auction will therefore compare the ads.txt file from the publisher domain with the ad network claiming to offer the space for sale, exactly as if the page had been served directly by the publisher.  The CDN never gets mentioned.

**Comment by jpettitt** [comment]
Ok so no matter what domain the page is served from if it's claiming to be from `some-quality-pub.com` based on the canonical you're going to look there to see if some-quality-pub has authorized this ad network and account to resell.  Essentially real time NPM.   

I can see how that would work on an AMP page, you'd use the canonical for that but on a regular page the canonical has a different meaning and may point off domain to a syndication source.  

That was my confusion.  In the non AMP world the canonical is not a reliable indicator of whose page it is, it says who originated the content. We see a lot of pages from our publishers where the canonical points to a completely different site becasue of syndication agreements.

In the AMP world it means the non-amp source page of this AMP doc except when you have an AMP page which is also canonical when it's meaning us utterly unclear because of the contradictory overloaded use of the term canonical.

Given that it's the buy side that's supposed to crawl the ads.txt it might be a good idea to document, exactly, where to look for the right ads.txt file becasue it's not at all clear from the spec.

**Comment by michaelkleber** [comment]
@jpettitt This seems like something for web page authors to discuss with their ad networks.  The only position I could see AMP taking was a recommendation to ad networks that when they integrate with AMP, they _not_ use the CDN domain as their page targeting URL, because the CDN does not offer a way for publishers to set ads.txt.

How the IAB spec interacts with the meaning of "canonical" as used on non-AMP pages is, of course, not in scope.

**Comment by jpettitt** [comment]
@michaelkleber that would require definitive list of CDN's.  However Cloudflare offers a white label CDN aliased on top of their AMP cdn (example cdn.relayamp.com).  This means that really isn't such a list.  

You need to know whose page it is but you can't trust anything on the page to tell you. I'm not sure there is a really easy way around this.

**Comment by michaelkleber** [comment]
@jpettitt I think you're misunderstanding the type of fraud that ads.txt is meant to address.

Check out an example file like http://www.businessinsider.com/ads.txt.  It contains lines like
`taboola.com, 688168, DIRECT`
When a bidder who buys on Taboola sees a bid request for a businessinsider.com URL, they can check that the seller account ID in the request really is 688168.  If it's not, then the bidder will know that this isn't actually Business Insider selling their space, but someone else masquerading as them.  If a bidder sees Outbrain selling Business Insider inventory, they will likewise know it's fake because outbrain is not listed in the ads.txt at all.

This doesn't do anything to address the possibility that evil.com could try to make its visitors send Taboola ad requests that pretend to be businessinsider.com instead of evil.com.  Probably Taboola would try to somehow reject those as fraudulent.  But even if they didn't, evil.com couldn't make any money out of this charade, because Taboola would send all the resulting money to account 688168.

So again, I don't think what you're worried about has anything to do with AMP or with CDNs (either ampproject.org or white-label).

**Comment by jasti** [comment]
Also checked in with the ads.txt authors. Non-issue. Please reopen if you think it needs more analysis.

**Comment by nickdima** [comment]
The fact is that DFP reports ampproject.org as not covered by adx.txt
Should we just ignore this?

<img width="718" alt="screen shot 2017-11-02 at 12 28 10" src="https://user-images.githubusercontent.com/614468/32323797-7e1dc324-bfc9-11e7-8642-0056d4968cef.png">

**Comment by jasti** [comment]
I wonder if there is a flow where DFP ad requests are getting the cache URL domain instead of publisher canonical domain. @ampproject/a4a @keithwrightbos WDYT?

**Comment by MKDan** [comment]
I had a doubt, I've converted two of my blogger blogs template as AMP. I guess there is no canonical URL since the primary blogs itself in AMP. Also, I don't know how is it possible to add ads.tx file to blogger.

My blogger sites are very small in terms of pages and traffic. So, I don't care it much anyway. But there are many people out there who use blogger.

**Comment by jasti** [comment]
@MKDan adding ads.txt file to blogger would be an independent question from AMP, correct?

**Comment by janwinkler** [comment]
@jasti @jpettitt 
I can see that this older post was closed in 2017, anyhow we believe the issue still exists:
Depending on the DSP, the check of the ads.txt file will depend on the (sub-)domain that is transmitted from SSP to DSP. In most cases a SSP will read something like www-mydomain-com.cdn.ampproject.org and send it to the DSP. The DSP will then try to fetch www-mydomain-com.cdn.ampproject.org/ads.txt and will fail. As basically all major DSP now require an ads.txt file to be present and correct, this current behavior of the CDN leads to issues when selling the traffic.

Therefore we recommend, that the CDN should also fetch www.mydomain.com/ads.txt and save it under www-mydomain-com.cdn.ampproject.org/ads.txt.
