### ISSUE TITLE
Support #development=experimental so validation doesn't complain about in-development features

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1064]
"#development=experimental" would runs the JS validator at the same version as the rest of AMP (as opposed to the prod version).

cc @cramforce

**Comment by Gregable** [comment]
Since the runtime and validator have different release cycles due to the environments they run in, this wouldn't really work the way you'd like it to. We could have a version that is at github head, but it wouldn't match up to the runtime features and would probably cause more confusion than it's worth.

Thoughts? OK to close as not feasible?

**Comment by rudygalfi** [comment]
Yeah, OK to close. It's been awhile since I've heard any feedback related to this.
