### ISSUE TITLE
Canary regression: Fixed header moves with scrolling

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#10695]
This repros when opting into dev-channel:

- Search for `amp` in Google
- Click on ampproject.org homepage link
- Initial position is sometimes wrong
- Scroll up and down.
- Observe that fixed header moves down

<img width="314" alt="screen shot 2017-07-28 at 8 09 17 am" src="https://user-images.githubusercontent.com/89679/28723688-6451257a-736c-11e7-90c5-5b69c461028a.png">

**Comment by jridgewell** [comment]
Are you able to reliably reproduce? I can't seem to do it.

**Comment by cramforce** [comment]
Repros both on my desktop with emulation and on my phone. Tested both stable and canary on my phone.

**Comment by jridgewell** [comment]
Tracked it down to the transition style applied to the header (hopefully that's rare). Our detection of the "css defined top style" (not JS defined through `element.style`) involves unsetting the `top` value we previously assigned and then detecting the computed top style again. Because of transition, it's still at the same 54px that we'd set it to (not the 0px css defined). Fix incoming.
