### ISSUE TITLE
`gulp test` is also running integration tests

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#10767]
See the config [here](https://github.com/ampproject/amphtml/blob/master/build-system/config.js#L54). Shall we make `gulp test` only run unit/functional tests, because that's how we [split the shards](https://github.com/ampproject/amphtml/blob/master/build-system/pr-check.js#L312).

**Comment by rsimha-amp** [comment]
I'm surprised to hear that integration tests are being run by `gulp test`. I was under the impression they needed sauce labs to run. Am I wrong about that?

Currently for unit tests, we do `gulp build` and `gulp test`. For integration tests, we do `gulp dist` and `gulp test --saucelabs --integration` (there are some additional args).

Either way, you're right. We should only run functional tests with `gulp test`. Let's make it so.

/cc @erwinmombay @choumx for comment.

**Comment by lannka** [comment]
same surprise here. probably it was me who mis-led you at the very beginning though :-)

**Comment by aghassemi** [comment]
as discussed on hangout, running integration tests on Travis is very useful because 1- it runs on latest Chrome (SauceLabs is always behind on latest versions of things) 2- it runs on every PR (integration doesn't run on every PR).

whatever we endup doing here, let's still run integration tests on Travis (Chrome) on every PR.

(I still prefer if `gulp test` run all tests, we can add gulp test --functional to allow dev runs particular type)

**Comment by lannka** [comment]
I thought we already run integration tests on saucelabs for every PR

**Comment by rsimha-amp** [comment]
> I thought we already run integration tests on saucelabs for every PR

No, we only run them for PRs that edit the integration tests.

**Comment by lannka** [comment]
OK, shall we turn on saucelabs integration test for every PR and remove the integration test from the unit test shard? It might increase some travis load, but the benefit is we can catch any breakage of integration tests much earlier.

**Comment by rsimha-amp** [comment]
@lannka, this is something I've wanted to do for a while, but hesitated because the Travis load will nearly double. That's because the integration tests need `gulp dist --fortesting` to be run, which is a step that takes ~13 minutes on Travis. Running `gulp build` OTOH, takes ~2 minutes on Travis.

I'm fine with doing this on an experimental basis and reverting if the tests aren't stable enough, or if the Travis wait becomes too long.

WDYT?

**Comment by rsimha-amp** [comment]
Chatted offline with @lannka, and here is the plan:

1. For `gulp test`, only run the tests under `test/functional/`
2. For all PRs, run `gulp build` and run integration tests without `--compiled`
3. On master, continue to run `gulp dist` and run integration tests with `--compiled`

This will save time for PRs (`gulp build` is much faster than `gulp dist` on travis), and still give us the test coverage we need for PRs.
