### ISSUE TITLE
Validator rules for amp-brightcove

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#1079]
Support `amp-brightcove` in the validator. See https://github.com/ampproject/amphtml/blob/master/extensions/amp-brightcove/amp-brightcove.md for more info.

**Comment by sriramkrish85** [comment]
@mister-ben, I am trying to implement a validator for `amp-brightcove`. I was going through the [spec](https://github.com/ampproject/amphtml/blob/master/extensions/amp-brightcove/amp-brightcove.md).

I was not able to follow which attributes are optional and which ones are mandatory. 


I think 

data-account - mandatory 
data-player - optional
data-embed - optional 
data-video-id - optional
data-playlist-id - optional 

Not sure about the last 2 (do you need at-least one of those or are they both optional?)

**Comment by dvoytenko** [comment]
@sriramkrish85 we are not validating `data-` attributes.

**Comment by mister-ben** [comment]
Only `data-account` is mandatory to create a player. Publishers will almost always need `data-player` and `data-video-id` to have a useful player, but I didn't want to exclude edge cases where the account's default player configuration really is what they want.

**Comment by powdercloud** [comment]
I'd like to point out that to support the potential edge case of the default player configuration, as proposed we're not checking against the common error of mistyping attribute names. Say I type data-videoid, I'll get the edge case by accident.
These unchecked data attributes may feel lightweight, but they require users loading the pages in a browser and inspecting whether it works, rather than catching common problems with the offline checking that we've built. One way to implement a check that supports the default configuration is allowed is like so: data-video-id, data-playlist-id, data-default-player-config are configured so that exactly one of the three must be specified. We use this mechanism for amp-youtube, for instance (https://github.com/ampproject/amphtml/blob/master/validator/validator.protoascii, look for amp-youtube-nonlayout-attrs, the gist is that you can specify mandatory_oneof). I'd argue this is easier to understand when looking at a document using such tags as well, because the reader won't need to know which attribute takes preference or what the default beavior is when attributes are mistyped or missing, it's immediately obvious for a valid document whether it's a video or a playlist or the default config.
Just my 2 cents. Obviously what you have here works (and I won't stand in the way), it is just less amazing than we could have it, for relatively cheap imho. :-)

**Comment by sriramkrish85** [comment]
@mister-ben i like what @powdercloud is suggesting - could you state the right combination of rules so that we can have the right validation rules. do you think that we could use `mandatory_oneof` for some of the attrs?

**Comment by mister-ben** [comment]
Good points, but I'd like to leave it less strict. There are two types of publisher using Brightcove players: those using Video Cloud (Brightcove's OVP) who need either `data-video-id` nor `video-playlist-id`, and those using Perform (Brightcove's standalone player service) who will not. The alternative is maintaining two components.

**Comment by sriramkrish85** [comment]
Cool - Validator should be available with the next release!.

**Comment by Gregable** [comment]
These validation changes are now live.
