### ISSUE TITLE
Read only field can't do the custom validation

### ISSUE THREAD

**Issue by bluell** [ampproject/amphtml#10845]
## What's the issue?

Read only field can't do the custom validation

## How do we reproduce the issue?

I don't know it's a issue or not, may be you think the read only field don't need validate in the form, since user can't change this field.

But I have below situation:
1. User login our site and go to amp campaign form page.
2. User base information will automaticlly filled in campaign form, like name, birthday, and these fields will be readonly.
3. We need block the user less than 18 years old, **but the birthday field is read only, I can't do any validation**.

## What browsers are affected?

All

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1502226476760

**Comment by jridgewell** [comment]
How are you marking up this form?

**Comment by cvializ** [comment]
The standard behavior does not validate readonly attributes either. Run [this jsfiddle demo](https://jsfiddle.net/ww8jo34x/) in Chrome and verify that the form with the readonly field does not show error validation, but the form with a mutable field does show the validation.

It sounds like since you're pre-populating the field, you might be rendering your AMP page instead of serving it statically. Consider rendering an error on this page, or use the amp-form template feature to render an error template using the form's `submit-error` state. Docs for that are here: https://www.ampproject.org/docs/reference/components/amp-form#success/error-response-rendering

Thanks for reporting! Do let us know if you still expect different behavior, but for now I will close this issue
