### ISSUE TITLE
Improve UX transitioning from placeholder to iframe

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#10903]
There are several things that can be improved with pages like this one that load an iframe (video player) in the first viewport: https://amp.cnn.com/cnn/2017/08/14/politics/trump-charlottesville-north-korea/index.html

- We seem to load the placeholder image even though we immediately load the iframe. Should we not do that and instead load the iframe immediately?
- Should we wait until `iframe.onload` until swapping from fallback (e.g. if we rendered the placeholder during pre-render)? This might be too conservative in some cases and delay time-to-interactive for the iframe, but would likely look nicer.
- Should we fade between placeholder and iframe instead of a hard swap?

**Comment by ericlindley-g** [comment]
+1 These all sound promising — slotting this with default priority (P3), but let me know if you have a particular priority in mind

**Comment by jasti** [comment]
When we figure out the last item from a UX standpoint, can we apply it to https://github.com/ampproject/amphtml/issues/8649 as well please?

**Comment by jwold** [comment]
> Should we fade between placeholder and iframe instead of a hard swap?

If we went with a hard swap option, what would that look like? Below are two screenshots of the current experience showing placeholder image first, then if the iframe were shown first. 

<img width="1302" alt="screen shot 2018-10-10 at 9 00 31 am" src="https://user-images.githubusercontent.com/3411173/46749659-0f983380-cc6b-11e8-87ea-6a8b932efce7.png">

**Comment by aghassemi** [comment]
@jwold In this particular case, when iframe is loaded, the view is the one on the left and not the one with the video player. I actually think current behaviour, which is hard swap of AMP placeholder -> iframe's initial render, is pretty nice since iframe's initial render has the exact same image as AMP placeholder and only the big Play button gets added. Doing a fade can improve this a bit.

![1](https://user-images.githubusercontent.com/2099009/46813202-256d2d80-cd2b-11e8-8d32-3b5cbbe8c1b2.png)
![2](https://user-images.githubusercontent.com/2099009/46813203-2736f100-cd2b-11e8-8f85-0ea674536fc5.png)

(currently we do wait until iframe's `onload` before swapping)
