### ISSUE TITLE
amp-bind ordering

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amphtml#10914]
We've just ran into an interesting scenario where we can't get amp-bind to update the bindings in the order we want.

We are trying to achieve the following use case:

1. Render a list of comments returned by an endpoint, and render an input field and "Reply" button beside each comment in the list.
2. When hitting one of the reply buttons, send an XHR to an endpoint, passing an ID for the corresponding comment along with the value of the input field as query parameters.

We have the following sample AMP HTML:

```html
    <div>
      Comment #1
      <input type="text" on="change:AMP.setState({comment: {0: event.value}})">
      <button on="tap:AMP.setState({index: 0}),foobar.submit">Reply</button>
    </div>
    <div>
      Comment #2
      <input type="text" on="change:AMP.setState({comment: {1: event.value}})">
      <button on="tap:AMP.setState({index: 1}),foobar.submit">Reply</button>
    </div>
    <div>
      Hidden Form
      <form id="foobar" action-xhr="https://example.com">
        <input type="text" name="comment" [value]="comment[index]">
      </form>
    </div>
```

Whenever the input fields beside each comment changes, the new value is also reflected in the foobar form input outside of the list. Whenever the reply button beside each comment is clicked, the index is changed to that corresponds to the comment.

The problem is that the foobar form input doesn't seem to pick up the latest index.

To reproduce:

1. Enter `1` in the input field beside comment 1
2. Hit `Reply` beside comment 1
3. Inspect the sent XHR 
4. Observe that the `comment` parameter is empty
5. Enter `2` in the input field beside comment 2
6. Hit `Reply` beside comment 2
7. Inspect the new sent XHR 
8. Observe that the `comment` parameter is `1`

It looks like the value of the foobar form input does get updated after the input fields beside each comment changes and before the form is submitted. However, the `tap:AMP.setState({index: 1})` part didn't get to update the bound value of the foobar form input before the form submits. The form is submitted with the foobar form input value bound to the comment corresponding to the old index.

Is this by design? If so, what are the alternatives for the use case?

@choumx

**Comment by choumx** [comment]
Ah, yes. 😄  

The issue is that multiple actions are currently executed in parallel rather than chained like promises. A less than ideal workaround for this is avoiding `amp-bind` and duplicating the form for each comment with static, templated input values. 

This is similar to https://github.com/ampproject/amphtml/issues/8648#issuecomment-293077744. I experimented with a possible fix in #8678. The problem with this solution is it allows circumvention of expression complexity limits, so we'd first need to consider the performance of chained actions. 

I think it's a common use case though so I'll re-prioritize this issue for a second pass soon. Thanks for filing this.
