### ISSUE TITLE
Integration tests that do `skipSauceLabs()` used to run on Travis but no longer run at all

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#10970]
integration tests used to run as part of `gulp test` which means the unit_test shard used to run them on Travis. Some of them had `skipSauceLabs()` which means they used to only run on Travis with latest Chrome.

With the new `--unit` change and from what I see in the logs, now the `unit_test` shard only runs unit tests and the `integration_test` shard only runs with `--saucelabs` which means all the integration tests with `skipSauceLabs()` no longer run at all.

**Comment by choumx** [comment]
Let's prioritize the agreed upon follow-up to #10825.

**Comment by rsimha-amp** [comment]
I dealt with this in #10825, by re-enabling as many of the tests as possible, that would run and pass on Sauce Labs' version of chrome. Unfortunately, some tests continue to fail there too, and they had to be disabled via `skipSauceLabs`.

The agreed follow up was to remove `skipSauceLabs` entirely, but I'm afraid that will leave a lot of tests un-runnable. We need to come up with a solution for those tests, that doesn't involve regressing back to a world where integration tests and unit tests are mixed, and we again need to build the runtime in order to run `gulp test --unit`.

**Comment by aghassemi** [comment]
If they used to pass on Travis but now fail on SauceLabs (and hence skipped), we need to do something quickly otherwise we are reducing coverage.

IMO, integration doesn't mean saucelabs-only. Can we have another shard that runs them on Travis with latest Chrome? (not sure why latest Chrome on Saucelabs would behave different than latest Chrome on Travis but looks like it does based on what you are seeing)

**Comment by rsimha-amp** [comment]
@aghassemi, I've created #10972, which entirely deprecates `skipSauceLabs`. If this goes through, the new guiding principle will be that we should write integration tests that run and pass on at least one sauce labs platform, and if not, rethink the existence of the test.
