### ISSUE TITLE
Nodemon fail to restart server

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#11029]
The feature that nodemon will restart server and app is broken due to https://github.com/ampproject/amphtml/blob/master/build-system/tasks/serve.js#L59. This makes changing `server.js` or `app.js` inconvenient as one has to restart server manually. 

Can we not call `process.exit()` on `exit` but on `quit` only? 

@rsimha-amp ?

**Comment by rsimha-amp** [comment]
@zhouyx, the reason we act separately on `exit` and `quit` is because we need to print a message during quit, and kill the process during exit. This is to control the lifetime of our servers, and not have zombie servers lying around. See #10013

Can you describe the situation in which you would want the server to restart on its own? As far as I know, the `process.exit` happens only in case of an explicit intent to kill the server.

**Comment by zhouyx** [comment]
we use 
```
nodemon ({
  script: ...
  watch: [app.js, server.js]
}) ....
```
so whenever a change is made to app.js or server.js, nodemon will automatically restart the server. This makes changing these two files much easier. 
As far as I found, during restart like this `exit` will be triggered and nodemon process will be killed as well. 

I agree that killing the process during exit is important but I assume `quit` itself should be enough. If not maybe we can introduce an argv, `gulp serve --enable-restart` for example ?

**Comment by rsimha-amp** [comment]
I see. I didn't realize that `exit` is triggered when a file is changed. I was under the impression that it's called only when the user hits Ctrl + C, or when the underlying process crashes.

One possible solution to this is what you suggest with `--enable-restart`, where we don't call `process.exit`. The other alternative of reverting that change will potentially cause zombie processes and spurious output due to unflushed output buffers, so I'd like to avoid that.

If you're working on a PR, feel free to add me as a reviewer. If not, I'll look at this tomorrow.

**Comment by rsimha-amp** [comment]
For context, the reason we don't kill the process during `quit` is because if we print a message *and* kill the process during `quit`, the output buffer remains unflushed and spills into the next task's output in the test logs. This is a well known limitation of nodejs. However, if we print a message during `quit`, and kill the process during `exit` (as we do now), the output buffer is properly flushed.

**Comment by zhouyx** [comment]
I see. I have a workaround that:

-  Keep current behavior without ``--enable-restart`:

- Ignore the test logs issue and only kill process during `quit()` with `--enable-restart` We 

Sounds good?

**Comment by rsimha-amp** [comment]
@zhouyx, we don't need the `--enable-restart` flag. All I had to do was remove the `on exit` handler and have the process cleanly exit when it sees `SIGINT`. I've sent you #11069 for review.
