### ISSUE TITLE
Input type number badInput validation will show valueMissing error message

### ISSUE THREAD

**Issue by bluell** [ampproject/amphtml#11049]
## What's the issue?

Input type number badInput validation will show valueMissing error message in Firefix and Chrome.
Opera mobile is OK.

## How do we reproduce the issue?

Type "+" in number type input field, please refer below screeshot:
![badinput-issue](https://user-images.githubusercontent.com/4859578/29608068-b5b5efae-8825-11e7-8858-554a455cab7b.jpg)

## What browsers are affected?

Chrome, Firefox.

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1503095301111

**Comment by cvializ** [comment]
Hmm that's not supposed to happen. I was able to reproduce. As a workaround, if you haven't already, try setting the css rule for the badInput message should have greater specificity than the valueMissing message.

**Comment by cvializ** [comment]
### First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects or have any experience with git & GitHub, please leave this issue for someone else.)

This issue fixes documentation and is intended to help people who have never used git or GitHub get familiar with them.

### What you will need to know

JavaScript, HTML, CSS

### Motivation

Web pages that receive user input securely and accurately are critical to e-commerce. If a user encounters a confusing error while completing a web form, he or she may feel that the business's site is less secure or trustworthy. AMP strives to create the best experience for e-commerce consumers and publishers.

### The bug

A number input field with invalid characters shows the same error message as it would show if the field was empty. It should show a distinct message. This bug occurs because of behavior in `extensions/amp-form/0.1/form-validators.js#getInvalidType`. When `validity.badInput` is `true` and `validity.valueMissing` is also true, the for-in loop encounters the key `valueMissing` first and the function immediately returns. Make a change that prefers `badInput` over `valueMissing` when both values are `true`.

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this issue if you plan on starting work in the next day or so.  (If you [join the AMP Project](https://goo.gl/forms/T65peVtfQfEoDWeD3) we'll be able to assign this issue to you after you've claimed it.)
- [ ] See the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.  For this bug it is not necessary to [build AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server) (but you may want to do that anyway just to see what it's like).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] Using the [instructions in the Getting Started guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them), edit `extensions/amp-form/0.1/form-validators.js#getInvalidType`. 

    *Note that it is possible to make changes to these files using the GitHub UI, but for this issue please go through the exercise of getting and editing the code via git.*
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Sign the Contributor License Agreement](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributor-license-agreement) before creating a Pull Request.  (If you are contributing code on behalf of a corporation start this process as early as possible.)
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review) and mention @mrjoro in a comment.  Mention `closes Issue 12977 ` in the description.
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged and it will be immediately live for all AMP contributors to benefit from.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by kopollo** [comment]
**my amphtml form element   <input type="number"   ... >  

but i can getting error with decimal numbers    10.55  or 22,55   

Do you have a solution?**

**Comment by cvializ** [comment]
Hi @kopollo it looks like your question isn't relevant to the above issue. In the future please open a new issue when you have a new question. This helps us track discussions more easily.

It looks like the standard allows each user agent to define what a valid number in a `number` input should be, and for some reason Chrome at least does not allow decimals in the `number` input, so this is not a problem with AMP. Demo: https://jsfiddle.net/qa5q57cx/

**Comment by yomeshgupta** [comment]
@cvializ Hello, I would like to solve/claim this issue.

**Comment by jpettitt** [comment]
Hmm, @yomeshgupta I can't formally assign it since you're not in the project members group but if you want to take the issue please go for it.

cc @cvializ @aghassemi do either of you know the process/criteria for adding somebody to the project as a member?

**Comment by aghassemi** [comment]
@yomeshgupta, Please fill out https://docs.google.com/forms/d/e/1FAIpQLSeF1PN4Ee7Ke5Hvn4uN_oznV3isr-tfFg7cFRLX2F2OJGhXpw/viewform?c=0&w=1 to join. Thank you for working on this!

**Comment by yomeshgupta** [comment]
@aghassemi I have already filled this form. Should I do it again? 

I will start working on the issue in the mean time.

**Comment by aghassemi** [comment]
Sorry previous comment was meant for a different issue.

It is a manual process, you should get added soon.

**Comment by yomeshgupta** [comment]
@aghassemi Okay. I have opened a PR ( #18060 ) against this issue.
