### ISSUE TITLE
Relax constraints in triple mustache

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#11094]
`amp-mustache` supports unescaped HTML with [triple mustache](https://mustache.github.io/mustache.5.html), which currently sanitizes everything except formatting tags like `<b>` and `<i>`.

```html
<template type="amp-mustache">
  {{{foo}}}
</template>
```

- Can we extend this to allow `class` attributes?
- We support `<code>` and `<mark>`. What about elements like `<p>` and `<h1>`?
- Can we render `<a>` links or the link text (#7502)?

/cc @dvoytenko

**Comment by dvoytenko** [comment]
Tripple mustache was initially planned for inline/formatting content only. But I don't see why we can't extend further. Generally, we wanted more of an actual rendering template rather than for an endpoint to shoot back the whole HTML that's rendered. 

If we expand, we need to re-review things a bit. E.g. `class` attribute cannot contain `i-amphtml-` classes and such.

**Comment by joshcp** [comment]
As noted in #7502 it would be great to have support for `<a>` and `<p>` elements, etc. One use case for this is populating a template with blog post content from WordPress. Thanks!

**Comment by choumx** [comment]
Forwarding a request for `<table>` and related elements `<tr>`, `<td>`, etc.
