### ISSUE TITLE
I2I: TIMER function for analytics URL substitution

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#11194]
Sample config to time the video play duration. (to quickly illustrate the idea, the video trigger spec is made up).
```js
trigger: {
  videoStarted: {
    on: "video-started",
    selector: "#video-id";
    request: "https://example.com/collect?video-started=TIMER(timer-id)"
  }
  videoEnded: {
    on: "video-ended",
    selector: "#video-id";
    request: "https://example.com/collect?video-ended=TIMER(timer-id)"
  }
}
```

In the above example, an in-memory timer with ID `counter-id` is started on the videoPlayed trigger.

The request URLs will be resolved to
```
https://example.com/collect?video-started=0  // start trigger
https://example.com/collect?video-ended=1025 // end trigger
```

If needed, the function can have one extra optional param to pause/resume/reset the timer.
```
TIMER(id)            // to read the timer. 
TIMER(id,pause) // to pause the timer.
TIMER(id,resume) // to resume the timer.
TIMER(id,reset)    // to reset the timer.
```

**Comment by aghassemi** [comment]
One comment: Let's use something other than video for code sample in this case (given video events already support this use-case by providing`playedTotal` values as event data)

**Comment by lannka** [comment]
@cramforce to defend against the argument of "avoid changing state via URL" in the design review, we already have such var function `COUNTER`.

**Comment by lannka** [comment]
@aghassemi good point. 

@pomeroyr is video `playedTotal` the only thing RichMedia is measuring? Can you give another example? If possible, I'd like to remove the support for the 2nd param in TIMER function to start/pause/reset the timer. I do agree "changing state via URL" in such way is odd.

**Comment by pomeroyr** [comment]
We need duration since last batch flush, so interval since last ping. So pings would look like with an constant interval of 5s:

http://mypingurl.com?timer=currentTimestamp
http://mypingurl.com?timer=5
http://mypingurl.com?timer=10
http://mypingurl.com?timer=12 // timer stopped before batching interval ended.

**Comment by cramforce** [comment]
This works for me.

**Comment by lannka** [comment]
@pomeroyr are you saying the `timer` param can be either an absolute timestamp or an interval?

Regardlessly, to meet your requirements, I propose the following special vars to the newly proposed batching API:
- `${batchOrdinal}`: indicates the ordinal of the current batch, starting from 1.
- `${batchInterval}`: indicates the interval between current batch and previous one. Use '' (empty string) if it is the 1st batch.

These meta info seems quite nature to be provided by a batching API, do they meet all your requirements here? Also be aware that you can still use `${timestamp}` to get the current timestamp.

**Comment by pomeroyr** [comment]
@lannka Yes, we need client-side clock, and then only durations after that. What is the usecase for these variables you are proposing? Are we talking about writing pings like:

<pre>
'requests': {
  'timerStart': 'https://mypingurl.com?timer=${timestamp}',
  'timerContinue': 'https://mypingurl.com?timer=${batchInterval}',
  'timerStop': 'https://mypingurl.com...' // how do we get intervals of timers which start and stop between the start and stop of the current batchInterval? Also, how do we know when to use which request?
}
</pre>

Something still needs to hold the state of the timer since batchInterval represents the state of the batch, not the timer. We A) need something that can change the ping parameters on timer state and B) need to do a tiny bit of math that would translate into (currentTime - lastBatchFlushTime) every batch flush.

Perhaps doing this inside the URL is not the best place, but I don't think the batchSpec is the best place either. I would put this ability to query timer intervals in amp-analytics itself and the concept of timers, or simply its own component instead.

Mind you, a timer that can be turned on and off isn't necessarily dependent on a batching config. Some use cases may be happy with a constant interval and no batching.

**Comment by rudygalfi** [comment]
Can anyone say the status of this?

**Comment by pomeroyr** [comment]
This has been abandoned in favor of changes to timer vars in #11290. This can be closed.

**Comment by rudygalfi** [comment]
@pomeroyr - thanks.
