### ISSUE TITLE
amp-iframe works in Mozilla but fails in Chrome

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#11298]
for Mozilla/Firefox and MS Edge, here is an `<amp-iframe>` that successfully displays a PDF.

https://ontomatica.io/amp/10000008/index.html

but in Chrome and Chrome Canary the PDF is not displayed and neither browser throws an error message.

are we doing something wrong?

/jay gray

**Comment by aghassemi** [comment]
Hi @jaygray0919 , 

Chrome currently doesn't allow plugins (e.g. native PDF viewers) to run in sandboxed iframes (even if all sandbox attributes are set).
See https://bugs.chromium.org/p/chromium/issues/detail?id=413851 for details of their reasoning behind this. In AMP, we always sandbox iframes.

I recommend using Google's PDF viewer or other HTML-based third-party PDF renderers. For instance instead of directly linking to your PDF, you can just change iframe src:
from `https://afdsi.org/pdf/1.pdf` to
`https://docs.google.com/gview?url=https%3A%2F%2Fafdsi.org%2Fpdf%2F1.pdf&embedded=true` to use Google's PDF viewer. 

sample: https://jsbin.com/yayowexovo

/cc @sebastianbenz for PDF sample on ABE.

Closing the issue, please feel free to reopen if you have further questions.

**Comment by jaygray0919** [comment]
thank you @aghassemi - we did not know this and now will change the way we display a PDF.
your solution also works in Mozillla and Edge.
/jay gray
