### ISSUE TITLE
amp-img does not load image outside viewable screen inside horizontal column

### ISSUE THREAD

**Issue by softtama** [ampproject/amphtml#11297]
## What's the issue?

`amp-img` does not load image outside viewable screen in horizontal column. Only one or two images outside viewable screen that are loaded.

## How do we reproduce the issue?

You can see my issue in this public URL: http://8d3fa43d.ngrok.io/amp-project/amp/.
I will update the URL if it got changed.

This is the GIF screenshot of the issue in Chrome 60.0 (look under "Produk Custom Populer" heading):

![GIF screenshot of the issue](https://user-images.githubusercontent.com/7237624/30465136-78b5abe4-99ff-11e7-849d-93d1e768734d.gif)

## What browsers are affected?

I test in on Chrome 60.0, Opera 47.0, Firefox 54.0.1, Microsoft Edge 40.15063.0.0

## Which AMP version is affected?

Version 1505341213754.

**Comment by aghassemi** [comment]
@softtama You would need to use [amp-carousel](https://ampbyexample.com/components/amp-carousel/) to create a horizontally scrollable container instead of a normal `div` with overflow.

We are working on relaxing this requirement, but for the moment `amp-carousel` must be used.

Closing the issue, please feel free to reopen if you have further issues with this solution.

**Comment by masihjahangiri** [comment]
amp-carousel is't a solution for this problem. We shouldn't add amp-carousel for simple horizontal scroll.
