### ISSUE TITLE
amp-animatation: width() and height() functions only return size in pixels

### ISSUE THREAD

**Issue by mitjak** [ampproject/amphtml#11351]
## What's the issue?

CSS extension functions `width()` and `height()` in `amp-animation` only return size in pixels. This is limiting to a point that you can only use these values for other properties that accept pixel values as well. You cannot use it for properties that accept numeric values or other value types.

These two functions should (also?) return a numeric value. Alternatively, we could use an additional function that would enable conversion between different value types.

## How do we reproduce the issue?

We would like to animate an element across a container with constant speed regardless of the container size. Animation duration should adapt to the container size. But we are not able to set it based on the output of these two functions as `duration` property accepts numeric values.

**Comment by dvoytenko** [comment]
@mitjak This is a very interesting idea. Here's my proposal: we resolve `px` values from `width()/height()` in the context of dimensional properties and just numerics otherwise. We already do something similar in other cases.

In other words:
 - `transform: translateX(width())` will yield `transform: translateX(531px)`
 - `duration: calc(width()/100)` will yield `duration: 5.31`

If no one can see any issues with this approach, I will go ahead and implement.

**Comment by mitjak** [comment]
@dvoytenko This sounds like a possible solution. But what will happen in case `width()` or `height()` is applied to a CSS variable?

Example:
`"--element-width" : "width()"`
`transform: translateX(var(--element-width))`
`duration: calc(var(--element-width)/100)`

If `calc()` could adapt in the same way, that would be best. It would also be great for doing it the other way around - converting from numerical to pixel values. We use a hack to achieve that at the moment:

`transform: translateX(calc(var(--numerical-property) * 1px))`

**Comment by dvoytenko** [comment]
Good question on variables. Let me ponder it for a bit. RE: numerical -> pixel "hack" - that's a totally valid and documented thing.

**Comment by dvoytenko** [comment]
In the end, I decided to introduce `num()` extension. See #11838.
