### ISSUE TITLE
amp-access return url fail

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#11369]
To whom it may concern:

I use tag - "amp-access" to do the login stuff.
It works well as usual, but failed since 2017-09-21

The login page will stop at  "amp-login-done" page (check the following link) and do nothing such as close the login window and rerender the source page.

stop page link:
https://cdn.ampproject.org/v0/amp-login-done-0.1.html?url=https%3A%2F%2Fblog.lalacube.com%2Fmei%2Fyahoo_auction_amp.html#success=true

I also check the amp by example demo page and has same experience.
https://ampbyexample.com/components/amp-access/

I wonder it is an issue or do I need to do any extra setting ?

Paul

**Comment by dvoytenko** [comment]
@meistudioli Thanks for the report. Issue identified. Fixing ASAP.

**Comment by meistudioli** [comment]
thanks a lot.

**Comment by fdosruiz** [comment]
Hi,

We have eventually received the same error since last month. We could only get this error on IOS mobile devices, and we don't know how to reproduce it again, because it happens so rarely. We had never detected this error until last month. The URL is the same.

https://cdn.ampproject.org/v0/amp-login-done-0.1.html?url=https://elpais.com/politica/2020/02/19/actualidad/1582108005_625437.amp.html#success=1

Francisco,
Thanks

![login-done-error](https://user-images.githubusercontent.com/4465438/76234078-8010fe80-6229-11ea-8412-5e2ce59cb4df.png)

**Comment by dvoytenko** [comment]
@jpettitt and @erwinmombay could you PTAL? @erwinmombay, I'm now by default suspecting single-path compilation for all these errors. Could it be the case?

**Comment by erwinmombay** [comment]
@dvoytenko how is single path affecting this? (since single pass isn't used anywhere yet)

**Comment by dvoytenko** [comment]
@erwinmombay just based on the conversation we had recently on login-done page.

**Comment by erwinmombay** [comment]
i could see it being module build (mjs) but not single pass. if i understand correctly this is a redirect?

**Comment by dvoytenko** [comment]
It's more complicated than just a redirect. It also can message with the opener in case of a popup. So, the JS binary should be fully executable w/o v0.js on that page. Generally, it seems to work ok to me at this time. So I don't think it's a compiler issue. Over to @jpettitt to confirm.

**Comment by jpettitt** [comment]
@ChrisAntaki please work with Dima to help diagnose.

**Comment by jpettitt** [comment]
Cound #27021  be related?

**Comment by ChrisAntaki** [comment]
Good catch, they certainly could be related. I wasn't able to repro today, but tomorrow I'll try more with a real iOS device & MacBook

**Comment by ChrisAntaki** [comment]
I was able to reproduce the issue on Scenic using a real iPhone with iOS 13. It appears the issue only impedes the SwG login flow, and doesn't actually break it, thankfully!

The issue is that when iOS shows a prompt to save a username/password, that pauses execution on the "AMP Login Done" page and basically stops the redirect flow ([video](https://drive.google.com/a/google.com/file/d/1kN0q0IlIhi5ooWX8wOwCKBRleeFgcr92/view?usp=sharing)). The Scenic page that spawned the login window gets updated correctly though. If the user enters credentials iOS remembers then the redirect flow works as expected ([video](https://drive.google.com/a/google.com/file/d/1Z1UaYJzTjUrcbK6SId6ZtJ33QxS5ud7N/view?usp=sharing)).

**Comment by ChrisAntaki** [comment]
Hey @fdosruiz, I just wanted to check with you. Are you seeing iOS users getting stuck on that redirect page, but after clicking "Continue" everything works as normal for them?

**Comment by ChrisAntaki** [comment]
I just created a WebKit bug to track `window.close()` being ignored when save/update password prompts are shown in iOS: https://bugs.webkit.org/show_bug.cgi?id=209074

**Comment by fdosruiz** [comment]
Hi @ChrisAntaki, exactly, we have been verifying it and iOS users getting stuck on that page and just after clicking "Continue" redirects them to the article, with login user ok, being the behavior as you describe.

Thanks a lot,
Francisco

**Comment by ChrisAntaki** [comment]
Thanks for clarifying, @fdosruiz ! We should have a fix for iOS users in the coming weeks
