### ISSUE TITLE
Design Review 2017-10-04 (amp-date-picker, position:sticky)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#11361]
The AMP Project holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

Time: Wednesdays @ [1pm Pacific](https://www.google.com/search?q=1pm+pacific+in+local+time)
Location: [Video conference via Google Hangouts](https://hangouts.google.com/hangouts/_/google.com/amp-eng-desrev)

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

If you are unable to make the 1pm Pacific time due to time zone issues but you have a design you would like to present please make a note of that and we will try to find a time that works.

**Comment by cvializ** [comment]
I'll present the `amp-date-picker` API design for review

**Comment by dvoytenko** [comment]
I'd like to cover ads and `position:sticky`. Related to #4574.

**Comment by aghassemi** [comment]
# amp-date-picker
- Browser default not feature full.
- We are integrating a third-party (AirBnB date picker) which is feature-full and accessible 
- Are the attributes like `keep-open-on-date` same names as the JSX (React API)? Yes
- How does it work with preact? How do we inject out template into the component? Let's discuss offline
- How do we deploy preact? it's just 2.3K, we don't need to do much
- Does it go through out closure compiler? yes it has to but CC may not do much with it.
- Are `mix` `max` absolute or relative? Absolute
- Is `src` JSON thing something we came up with or part of AirBnB picker? It is ours.
- What variables are available? date parts, isHighlighted, etc..
- Is fullscreen their implementation? yes, we may need to adjust that for the header.
- Can viewer override the date picker UI? this is custom enough that may not make sense to viewers to try to replace it.
- Maybe we should remove `min` and `max` and move it to the `input type=date` since it is an HTML5 attributes already.
- Explore ability to set 1 or 2 calendars via media queries.
- Can we use react template rendering rather thin out template rendering? to be explored
- How big are the dependencies? to be determined
- What are the names for the range input? not autogenerated, can be specified with the input placeholders.

# position:sticky
Pursue with the proposal
