### ISSUE TITLE
Explore the best approach for inputting distant dates (e.g. Birthday)

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#11536]
Using `<input type=date>` for picking distant dates such as Birthday has issues of various platfroms as the UI for `type=date` is not standardized. Specifically in Chrome/Android user is presented with a mini-calendar where _ability to change year_ is very _undiscoverable_.

We should research the best UX for picking distant dates:
[Existing research ](https://www.nngroup.com/articles/date-input/) seems to indicate manual input is the best UX for inputting distant dates,  however there are multiple ways of Typing a date.
 
1- A pure textbox without any built-in "intelligence" (e.g. puts the "/" automatically, stops accepting input after date is completed, etc..) won't be good IMO. 
2- three input boxes where the "next" one gets autofocused when user is finishing typing in the first one. 
3- dropdown for month and text box for year and day. 
4- etc..

We should:
- [ ] Come up with a recommendation based on real data
- [ ] Implement the recommendation either in AMP (e.g. `input custom-type="date-distant"`) or in AMPStart/ABE

/to @spacedino 
/cc @ericlindley-g @cvializ

**Comment by rudygalfi** [comment]
@aghassemi It sounds like you're dismissing option 1, but that's only if there isn't any intelligence/auto-insertion of characters, right? The one case we saw of distant dates being worse on AMP and better on non-AMP put a slash automatically with a hint to fill in "MM/DD/YYYY". This seems like a reasonable path. The main question is how to make it generic. I think an important consideration is keeping the input format consistent between AMP and non-AMP, so it may not be possible for someone to migrate to a more structured fill experience (e.g. split month, day, year across three fields).

Option 3 seems weird.

**Comment by aghassemi** [comment]
#12079 for #1

**Comment by jwold** [comment]
Just wanting to validate, before giving any feedback on the specific UI example. Is this the datepicker we're talking about?

![screen shot 2018-10-10 at 08 21 45](https://user-images.githubusercontent.com/3411173/46747282-b4b00d80-cc65-11e8-8265-05533ca33ded.png)

I pulled it from the AMP by Example [playground](https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-date-picker%2Fsource%2F&mode=iPhone+7).

**Comment by aghassemi** [comment]
@nainar @andrewwatterson I still believe this is an idea that can use UX/R. Particularly important for landing pages.

**Comment by andrewwatterson** [comment]
What are all the landing page use cases? The one I can think of the most is making sure someone is 18+ (for liquor brands, for example).

For that use case, I've most often seen three dropdowns. There are at least two theoretical advantages:
1) Dropdowns make it easier to deduce the date format (particularly when month names are used, and especially if the month name is put first, although that's weird for most of the world)
2) Dropdowns are self-validating (it's impossible to put an invalid date into three dropdowns if the month dropdown programatically filters the date dropdown)

`amp-datepicker` is particularly inappropriate here because its two strengths are putting upcoming dates nearby and providing visual context about day of the week for date selection, neither of which is relevant for birthdays (assumption that sounds reasonable: very few people have a strong association with the day of the week of their birth).

An input mask-based solution is interesting - we could do UXR on how quickly and accurately people complete that vs. a dropdown-based approach in a mechanical turk-style study.

Also worth noting that there may be laws that are applicable to the design here (for example, under COPA or COPPA or whatever you're not allowed to stop an "are you 18+ birthday picker" at 2001, because that makes it too obvious how to trick it to get a valid outcome), but that'll vary by jurisdiction/type of site, so not sure how/if we'd want to bake that into the design.

**Comment by aghassemi** [comment]
mostly conversion forms for advertisers like life insurance companies
