### ISSUE TITLE
Request cid failed: document is not visible errors

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#11628]
`Request cid failed: document is not visible` have become common since September 18th. 

Possible culprit: https://github.com/ampproject/amphtml/pull/11046/files#diff-cd24a4710c7e4e23016d10a126055108L180

**Comment by aghassemi** [comment]
reopening, still happens despite the change.

**Comment by zhouyx** [comment]
hmmmmm, do we at least see error number drop?

**Comment by aghassemi** [comment]
@zhouyx yes, they have dropped a lot but still happening.

**Comment by zhouyx** [comment]
Yes I do see a drop there. I am assuming the issue here is still the same, that doc become invisible before we send out the message. The fix reduced the risk but didn't fix the race. 
We wait for `viewer.nextVisible()` promise to ask viewer for cid. But there are few promises to be resolved before actually sending out the message to viewer, where the doc can become invisible.

**Comment by aghassemi** [comment]
Closing in favor of new https://github.com/ampproject/amphtml/issues/11888
