### ISSUE TITLE
lightbox attribute for amp-carousel

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#11660]
```
<amp-carousel auto-lightbox>
```

- All images become clickable and take you to lightbox 2.0 (which is essentially a full-screen carousel)
- All videos and images get a thumbnail by default
- All other elements (ads, quotes) are included in the lightbox but do not get a thumbnail (unless specified explicitly)

**Comment by aghassemi** [comment]
maybe `auto-lightbox`

**Comment by camelburrito** [comment]
This is very useful, couple of thoughts

- do we see this being included in in amp-img/amp-video (instead of higher level components) (auto-lightbox)
- may be think about `on:tap:openInLightbox` - would that be useful

I like the idea - but in general i would like to see some features move to core components to make these features accessible in composite components

**Comment by aghassemi** [comment]
yes, initial MVP is for carousel but any element will support it later.

**Comment by cathyxz** [comment]
Addressed by https://github.com/ampproject/amphtml/pull/12771
