### ISSUE TITLE
amp-story: Videos continue loading when the user moved on

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#11661]
It seems to me that videos still continue to buffer when the user proceeds to the next slide.

Is there a way to stop them from loading any more data (cancel the stream).

@aghassemi

**Comment by aghassemi** [comment]
I am not hopeful there is a "good" solution for this. One way would be unloading the video by setting `src=''` and remembering the current position and seeking to that on the next play().

We probably wanna do this regardless since iOS will do it anyway when it runs out of hardware for decoding (exact # is device specific) (iOS won't restore the previous position, it will just unload an existing paused video when it needs to decode another one)

**Comment by aghassemi** [comment]
@mounirlamouri are they any discussions at the platform level for supporting a "hard-pause" for `video`? i.e. Stop buffering, release all decoding resources occupied by the video but `resume` from the same place on the next `play` (with the understanding that this `play` call will take a bit longer to get to playing state)

**Comment by mounirlamouri** [comment]
I think setting `src=''` would be my recommended solution. If there was a method to do this, what would be different from calling `src=''` and saving the `currentTime`?

**Comment by newmuis** [comment]
We actually don't want to remember `currentTime` anyway; we currently always rewind to `0`.

I can play around with dropping the `src`

**Comment by cramforce** [comment]
Please be careful that src='' doesn't trigger a download

**Comment by aghassemi** [comment]
@mounirlamouri resetting src means user will see the poster image again instead of the current 'paused' frame. Also replaying would re-trigger events like `loadstart` again. A platform supported `hard-pause` can support better UX by showing the paused frame. I think it would be nice if `pause` could take in an options object that supports things like `stop-buffering`, `deallocate`, etc...

**Comment by newmuis** [comment]
#12604 puts us in a good position to fix this.  The remaining work is tracked in #12865, so I am closing this issue.
