### ISSUE TITLE
[FR] amp-form: Support `pattern` or custom validation on &lt;select>

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/amphtml#11674]
`<select>` could become a first-class amp-form citizen by getting the pattern attribute for form validation:
```
<select pattern='^\S+$'>
<option>select a state</option>
<option value='al>Alabama</option>
<option value='c'>California</option>
```
...

**Comment by aghassemi** [comment]
@AndrewKGuan for the cases there user must select one option `required` should work fine. 
If the given example, if user leaves it as "select a state" if you use `required` they will get a validation error since `value=""` for that option.

What is the use-case other than that? Just thinking why include options that don't match the pattern in mind at all in the select?

Closing the issue, feel free to reopen if answer is not satisfying.

**Comment by AndrewKGuan** [comment]
Thanks Ali.
