### ISSUE TITLE
amp-live-list: Use WebSockets

### ISSUE THREAD

**Issue by KiaraGrouwstra** [ampproject/amphtml#11686]
WebSockets were previously discussed as an alternative to long-polling for the live blog use-case at #909. The added value here would seem it's inherently more efficient, allowing the server to push new info real-time without reiterating old data or superfluous polling requests.

Back then, in 2015, one concerned raised was the need for fallback protocols in the case of WebSockets. Today, this situation is looking [somewhat better](https://caniuse.com/#search=websocket), with support missing only from the likes of Opera Mini (2.81% usage), IE<=9 (fixed September 2012), and Android browser <=4.3 (fixed December 2013).

One obvious question here would be what the appropriate API would look like: finding a universal higher-level abstraction was considered challenging in that #909, with @matcarey noting they'd be "harder to specify to everyone's needs".

I'll concede I don't have a silver bullet to offer there. Perhaps starting with a lower-level API might help kick things off already, as not having one precludes people from being able to experiment there, considering the `WebSocket` JS interface is not exposed.

The first thing that'd come to mind for me there would be a thin [wrapper](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) among the lines of `<amp-socket url="..." onmessage="..." />`, to be used with the likes of `AMP.setState(...)`. I imagine others might have more ideas there though.

**Comment by QES** [comment]
I think having a way to minimse the collected / pushed data is very useful, however one of the cool things I like about amp-live-list is its minimal changes required at the server end, a possibly easier way to do what you are suggesting is to allow the amp-live-list to have some kind of optional update URL that is a little more optimized than the current HTML that contains the current time / last poll time.

For example a set of simple JSON elements that define update time and content that could limit the amount of data sent / requested to a much smaller subset than the current system, although the current system can be faked to do this as basic HTML switching the response for updates to JSON objects of the relevant additions could make it easier for a server to just send back the new objects since a set time.

**Comment by tycho01** [comment]
@QES: admittedly so, `amp-live-list` just hooking into REST JSON endpoints makes it quite elegant.

If the main concern is speed and cutting down on polling requests, then as mentioned, that makes for a straight-forward path: let `amp-live-list` support that, so as to allow servers to re-push updated content over websocket.

The reason my initial intuition was to expose websockets in a more general sense was because there's another benefit there: not having to resend all old content each time an update happens.
[CRUD](https://github.com/swagger-api/swagger-socket) [over](https://docs.feathersjs.com/api/primus.html) [websockets](https://www.lagomframework.com/documentation/1.3.x/java/ServiceDescriptors.html) [has](https://github.com/milliondreams/socket.io.play) [been](https://hexdocs.pm/phoenix/Phoenix.Socket.Transport.html) [done](https://github.com/urish/firebase-server) [in](https://www.meteor.com/) [many](http://sailsjs.com/documentation/concepts/realtime) [different](https://djangopackages.org/grids/g/real-time/) [ways](https://github.com/rails/rails/tree/master/actioncable), and a lower-level API would empower devs to hook into the functionality they already have there.

But yeah, prioritizing the 20/80 there sounds quite fair.
