### ISSUE TITLE
running gulp test causes prod-config file to change locally

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#11763]
Whenever I run `gulp test` it changes my `prod-config.json` file locally.

**Comment by rsimha-amp** [comment]
@aghassemi We now write the prod (or canary) config to the AMP runtime after building. I don't believe that the json files themselves are changed in any way. The only files that should change are `dist/amp.js` and / or `dist/v0.js`. Can you confirm that this is what you're seeing? I can take a look too.

**Comment by rsimha-amp** [comment]
@aghassemi see #11588

**Comment by rsimha-amp** [comment]
Oh, I think this might be `gulp prepend-global` in action. I believe it first checks out the latest stable prod or canary config before applying it, thereby squashing any local changes. I can send out a PR to make sure we don't do this. @erwinmombay, do you know why this is done in the first place?

**Comment by erwinmombay** [comment]
prepend-global does this since it is part of the commands ran to produce production binaries. It always uses master HEAD to pull in any changes ASAP since these flags can be used to shut off or turn on features immediately (which is important since that is faster than producing new builds to fix bugs etc)

**Comment by rsimha-amp** [comment]
Makes sense. Will send out a fix ASAP.
