### ISSUE TITLE
livereload validation whitelist

### ISSUE THREAD

**Issue by fsencinas** [ampproject/amphtml#1181]
As many of us that often we use tools such Grunt, Gulp, etc. it will be great a validation blind for stuff like livereload, in order to get rid of validation noise using this kind of features.
Maybe a whitelist lookup for those tools?

**Comment by Gregable** [comment]
I don't think we can change the public validator to allow additional markup for these specific tools because we don't want someone to be confused and publish a page containing this markup, thinking it is valid.

One thing you could do is to check out the validator from the github repository and build it as an nodejs command line interface, modifying the output as you see fit. To do so, from the `amphtml/validator/` directory:

* Run `build.py` which will generate a binary at `amphtml/validator/dist/validate`
* Run that binary against any HTML file you want to use, for example `dist/validate testdata/feature_tests/empty.html`

Some more documentation [here](https://github.com/ampproject/amphtml/blob/master/validator/README.md)

If you want to, you can either modify the validator rules to add whitelists for yourself, or just filter out the errors that you don't want to see.

**Comment by fsencinas** [comment]
OK, what you say makes sense, and I'm in the same way (the spec is the spec).

**Comment by Gregable** [comment]
Closing. If you have any suggestions on things we could do to make this easier for development though, please do let us know!

**Comment by cramforce** [comment]
Just wanted to say: Totally see that this is annoying during dev. We have the same problem. But potentially hiding errors can be really bad.

I will definitely think about how we can improve this.
