### ISSUE TITLE
Allow autofocus on input in amp-form

### ISSUE THREAD

**Issue by devvercer** [ampproject/amphtml#11892]
In an amp-form, an input element with the autofocus attribute does not gain focus.

See an example here:

https://codepen.io/vercer/pen/MOwdVB

I expect the first input to be focused when the page loads but it is not.  Here is an example of the expected behaviour:

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_autofocus

**Comment by cvializ** [comment]
It looks like the `amp-boilerplate` css is the culprit here. The browser doesn't want to autofocus the input when it is not visible on page load. The amp-boilerplate makes the body of the document invisible on page load using the CSS `visibility` property, which prevents the `autofocus` attribute from assigning focus.

We could probably fix this with JavaScript, or by changing the boilerplate. If I use `opacity: 0` instead of `visibility: hidden` in the boilerplate the input is correctly focused.

@dvoytenko @aghassemi what are your thoughts?

**Comment by aghassemi** [comment]
@cvializ I think we should handle it ourselves in `amp-form.js` something along the lines of 

```
viewer.whenNextVisible( () => {
   tryFocus(querySelector('[autofocus]'))
})
```
should do.

**Comment by cvializ** [comment]
That seems like a good approach to me
