### ISSUE TITLE
amphtml-validator cannot validate URLs

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#11941]
Feature request: support validation of URLs via the NodeJS API.

The included command-line script [can validate URLs](https://github.com/ampproject/amphtml/blob/371a072ed4986410b3671469f603e88721890bad/validator/nodejs/index.js#L447), but the API will only validate strings. (The only method exposed is [`validateString()`](https://github.com/ampproject/amphtml/blob/371a072ed4986410b3671469f603e88721890bad/validator/nodejs/index.js#L263).)

**Comment by dvoytenko** [comment]
@Gregable pls triage

**Comment by Gregable** [comment]
Johannes mentioned that this may already be present. @powdercloud for details.

**Comment by powdercloud** [comment]
@Gregable @ithinkihaveacat I think I was wrong there, I thought the API supports passing URLs for identifying AMP documents to be validated but it's true - it does not.
I also think perhaps it should not, reason being, fetching content based on a url isn't something that's specific to AMP, and getting it right is slightly complex due to redirects, concurrency in Javascript, etc, and once we start going down the rabbit hole we'll have to decide on whether or not to interpret the rel=amphtml links, etc. I don't want to burden the API with that, if possible ... for fear of wandering into a bottomless pit.
If you have a particular need and are stuck, copy/pasting the readFromUrl method and modifying it for your needs should get you most of the way there, and then the good thing is that you can tailor it to your specific problem as opposed to having to understand an elaborate API with lots of configuration switches that is bound to be less easy to use than the http / https Node.js module itself (for which there's great documentation and of course, stack overflow snippets / questions answered for inspiration).
Hmm, is this an acceptable resolution? Please let me know if not ... I'll probably close this in a day or two if we don't hear, but happy to discuss more. Thanks!
