### ISSUE TITLE
amp-mustache removes `application/json` script tags 

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#12023]
Template sanitizer currently removes `<script type="application/json">` which means that components that rely on JSON configurations (`amp-animation`, `amp-ima-video`) can not be be used inside `amp-list`

/cc @dvoytenko  @choumx

**Comment by jc275** [comment]
Same applies to <script type="application/ld+json"> tags, which would presumably be useful for marking up amp-list items.

**Comment by zhouyx** [comment]
Same with <amp-analytics>

**Comment by lannka** [comment]
@Gregable and I are working on a new template language designed with AMP validator in consideration. Details are coming soon.

We might deprioritize this work and recommend users to move towards the new templating language once built.

**Comment by src-code** [comment]
Adding my voice of support for prioritizing a fix for this, or that new templating language, sooner rather than later.  We (Oath/Yahoo) have a use case where we need to beacon viewability on elements rendered by an `amp-list`, including beacon data returned in the `amp-list` response, and it seems to be impossible to do currently without either a) `amp-analytics` processing async content for trigger elements, allowing them to be tracked directly and thus use of data attributes for analytics vars, or b) `amp-list` allowing us to embed additional `amp-analytics` config/vars in the response.  Using external config for `amp-analytics` to work around this issue is not realistic for us since the data we need for the beacons is dynamic and unique to each `amp-list` response.

**Comment by aghassemi** [comment]
assigning to @choumx for prioritization in runtime.
