### ISSUE TITLE
DoubleClick iframes raise error: `script tag for amp-analytics is likely included twice in the page`

### ISSUE THREAD

**Issue by AndrewGibson27** [ampproject/amphtml#12039]
## What's the issue?
The error... `amp-analytics is already registered. The script tag for amp-analytics is likely included twice in the page` ... is shown in the browser console of AMP page that includes DoubleClick ad units. If you look at the ad iframe page source, you can see that it also includes the `amp-analytics` script, thus causing this error if the AMP page itself also includes that script. While this isn't causing AMP pages to invalidate, I worry it could in the future.

## How do we reproduce the issue?
1. With the browser console open, visit: https://www.texastribune.org/2017/11/13/texas-gov-greg-abbott-endorses-primary-challenger-state-rep-sarah-davi/amp/#development=1
2. Wait for the error to appear.
3. Here's an [example](https://securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&glade_req=1&glv=26&dt=1510600247993&output=html&iu=%2F5805113%2Fpremium_0&sz=300x250&sfv=1-0-10&correlator=278784009750&adk=3714898680&biw=375&bih=667&adx=38&ady=1500&oid=3&u_sd=2&ifi=1&ga_cid=GA1.2.1974834948.1500401391&ga_hid=9750&is_amp=1&amp_v=1509747505247&scp=guten%3Dperson-greg-abbott%2Csubject-2018-elections%2Csubject-politics%2Cperson-sarah-davis%26pageURL%3D%252F2017%252F11%252F13%252Ftexas-gov-greg-abbott-endorses-primary-challenger-state-rep-sarah-davi%252F&nhd=1&url=https%3A%2F%2Fwww.texastribune.org%2F2017%2F11%2F13%2Ftexas-gov-greg-abbott-endorses-primary-challenger-state-rep-sarah-davi%2F&top=www.texastribune.org&loc=https%3A%2F%2Fd-16285276382271199363.ampproject.net%2F1509747505247%2Fframe.html) of an ad iframe that includes the analytics script.

## What browsers are affected?
Browser-independent issue. I got it in desktop Safari 11, latest Firefox and latest Chrome.

## Which AMP version is affected?
Version 1509747505247

**Comment by keithwrightbos** [comment]
Hello, this is due to an AMP creative being returned by Doubleclick which does have the amp-analytics script included twice.  This will be addressed in two ways going forward:

1.  We are launching Fast Fetch canonical AMP within in the next couple of weeks and your page is eligible (no usage of remote HTML or useSameDomainUntilDeprecated).  This should result in a revenue and viewability increase as fast fetch separates request from render allowing it to occur immediately despite the location of the slot relative to viewport and also allows for AMP creatives to get preferential render (meaning they load without 1 second penalty and within friendly iframe re-using parent page AMP runtime).  The relevant benefit of AMP creative preferential render for this issue, is that it will cause any duplicate script issues to go away.

2.  We are also separately correcting the duplicate script issue within the creative within the next 2-4 weeks.

Thanks and apologies for the confusion.  For now, the duplicate script presence should have no effect on performance.
