### ISSUE TITLE
Add lint check for unused imports

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1212]
Imports should be used or not done.

CC @erwinmombay

**Comment by erwinmombay** [comment]
So we can't really check for `unused imports` since imports can have side effects but per the conversation in https://github.com/ampproject/amphtml/pull/1211/files, we can turn on `unused reference` lint checks but it currently errors out cause it also checks for unused properties and we have the following scattered all over our code base.

```js
class SomeClass {
  constructor() {
    /** @private */
    this.someProp_;
  }
}
```

I'll have to do a cleanup of that first, but i 100% agree this should be on.

**Comment by cramforce** [comment]
Yeah, we should really change those by adding ` = undefined`.

I think that check would really give us robustness!

**Comment by erwinmombay** [comment]
i stand corrected, the one i stated was for `unused expression`. but where it actually errors out are on our typedefs, like so:

```js
/**
 * @typedef {{
 *   newStackIndex: number
 * }}
 */
let ViewerHistoryPoppedEvent;
```

now we need to add either a `Def` suffix or a `Interface` suffix so that they are ignored by the linter. (for typdefs, templates and class interfaces)
