### ISSUE TITLE
failed to call initLogConstructor problem in testing

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#12135]
If you run
```
gulp test --a4a
```
you will see a bunch of test failures that say "failed to call initLogConstructor".

`gulp test --a4a` runs all A4A related tests in a randomized ordering. When the tests are run with the entire suite via `gulp test`, everything passes. This is because initLogConstructor is getting called early and causes the log constructor to exist for future calls to user() or dev(). However, in random order, the "early" code does not execute early, and so future calls to user() or dev() fail.

I've tried adding calls to initLogConstructor within the test code itself, and that does not fix anything. It seems that the way that extensions get loaded causes that not to be a viable solution. I did some digging, and Erwin did even more digging, and no solution has been found.

This is a very high priority issue for our team. We are unable to debug other issues, because the initLogConstructor failures cause unit test debugging to be impossible.

**Comment by rsimha-amp** [comment]
I see a few potential root causes:

1. In the `--randomize` code in `runtime-test.js`, it appears you're adding `test/_init_tests.js` to the list of test files twice: once directly, and once via `commonTestPaths`. I think you can delete [this](https://github.com/ampproject/amphtml/blob/master/build-system/tasks/runtime-test.js#L265) line. 
2. Unit tests only need `gulp css` to be run as a prerequisite. You seem to be automatically running `gulp build` before `gulp test --a4a`. This is unnecessary, and can be fixed with a change to [this](https://github.com/ampproject/amphtml/blob/master/build-system/tasks/runtime-test.js#L39) line. (Change `argv.unit` to `argv.unit || argv.a4a`). This might result in your tests passing from a clean state, but may not be sufficient.
3. Running `gulp build` before `gulp test --a4a` is causing the tests to fail, while `gulp css` lets them pass. This makes me believe that one of the a4a extensions is neglecting to initialize logging during load time. See [this](https://github.com/ampproject/amphtml/blob/master/src/log.js#L537) comment in `src/log.js`. See how other extensions / modules are [initializing logging](https://github.com/ampproject/amphtml/search?utf8=%E2%9C%93&q=%22initLogConstructor()%3B%22) at load time before the runtime calls a log statement.

**Comment by rsimha-amp** [comment]
To add to the above comment, the following works for me, and does not result in the error:
```
gulp clean
gulp css
gulp test --nobuild --a4a
```
It's not a good sign that `gulp test --nobuild --a4a` fails after `gulp build`, but passes after `gulp css`.

**Comment by rsimha-amp** [comment]
And finally, I'm not convinced that enforcing test randomization for a4a tests is a good idea. I recognize that it might have been necessary in the past due to flaky unit tests, but in the past couple of months, things have greatly improved with the adoption of chai v4 and several other bug fixes. In particular, chai v4 now throws errors when any test fails to clean up the global sandbox (IIRC, this was the main justification for randomizing the order of tests.)

I'd encourage you to get rid of test randomization altogether, and open separate bugs for any tests that exhibit flaky behavior.

**Comment by bradfrizzell** [comment]
This is still a problem.

Running `gulp test --a4a` (with randomization shut off) still throws the initLogConstructor issues. 
Running `gulp clean && gulp css && gulp test --a4a --nobuild` works, but we shouldn't have to do that every single time.

**Comment by rsimha-amp** [comment]
It's likely that the error lies in how you are picking the files to build via the `--a4a` flag. See the items in https://github.com/ampproject/amphtml/issues/12135#issuecomment-345856757

There's no reason to have to clean and rebuild each time. Particularly when this works fine with non-a4a testing, like `gulp build --unit`.

**Comment by rsimha-amp** [comment]
@bradfrizzell It appears that you're calling `user()` or `dev()` from `src/log.js` in a bunch of places in the A4A code, but logger hasn't yet been initialized via `initLogConstructor`. This is likely the root cause of the errors you're seeing when only the a4a tests are run without loading any other AMP components. See this comment at https://github.com/ampproject/amphtml/blob/master/src/log.js#L549:

```
export function initLogConstructor() {
  logConstructor = Log;
  // Initialize instances for use. If a binary (an extension for example) that
  // does not call `initLogConstructor` invokes `dev()` or `user()` earlier
  // than the binary that does call `initLogConstructor` (amp.js), the extension
  // will throw an error as that extension will never be able to initialize
  // the log instances and we also don't want it to call `initLogConstructor`
  // either (since that will cause the Log implementation to be bundled into that
  // binary). So we must initialize the instances eagerly so that they are
  // ready for use (stored globally) after the main binary calls
  // `initLogConstructor`.
  dev();
  user();
}
```

When you run all the AMP tests, it so happens that some other component is initializing the logger first, so the a4a components are able to use the logger without an error. However, when you do a full `gulp build` and run the a4a tests, something changes in the way the A4A components load, and there's no other component around to initialize the logger.

I don't think it's the right solution to simply call `initLogConstructor` from all the a4a components, as that will unnecessarily bundle the logger implementation into those components.

I'm sending you #13292 which removes the `--randomize` code from `runtime-test.js` and fixes `gulp test --a4a` from a clean branch. We can follow it up with a PR that either adds a module to `a4aTestPaths` in `build-system/config.js` that first initializes the logger, or explicitly initializes the logger in an A4A test file.

**Comment by bradfrizzell** [comment]
For what it's worth, in the past I'd tried loading a testing-only file that initialized the logConstructor before anything else, but it never worked. The problem from what I could see was that the way that extensions are loaded means that the scope that the logs class lives in was not something I could readily modify with a testing file, but it's entirely possible I missed something really obvious down that path before giving up :)

**Comment by rsimha-amp** [comment]
@bradfrizzell I tried adding `test/functional/**/*.js` to `a4aTestPaths` in `build-system/config.js` and all tests passed when I ran `gulp build` followed by `gulp test --a4a`. Obviously, something is missing when just the A4A tests are run.

Adding @erwinmombay who first added `initLogConstructor` in #5161 to see if he knows what's wrong. To recap...

**This works:**
```
gulp clean
gulp test --a4a
```
**This fails:**
```
gulp build
gulp test --a4a
```
@erwinmombay, when just the A4A tests are run, they fail with `Error: failed to call initLogConstructor`. Can you think of why this is the case? Do you know where in the unit tests the `initLogConstructor` is first called? Here are the files included when `gulp test --a4a` is called: https://github.com/ampproject/amphtml/blob/master/build-system/config.js#L71

**Comment by rsimha-amp** [comment]
It turns out that when the runtime is built via `gulp build`, the following directories are generated and included with the A4A test files via `build-system/config.commonTestPaths`:
```
'test/fixtures/*.html',
'test/fixtures/served/*.html',
'dist/**/*.js',
'dist.tools/**/*.js',
'examples/**/*',
'dist.3p/**/*',
'test/coverage/**/*',
```
I don't think any of these files are actually needed to run the A4A unit tests, and they should be removed from the list of test files.

The good news is that doing so fixes `gulp test --a4a` irrespective of whether it's run on a clean client or on a client with a built runtime :)

At long last, PR coming up!
