### ISSUE TITLE
Feature requests: Search, Themes, Guides for image optimizations

### ISSUE THREAD

**Issue by simonferndriger** [ampproject/amphtml#1221]
I would love to use AMP HTML for our mobile website. However, it would need two things to be available in order to switch:

1. Search functionality must be available. We have local content, so users often search either for nearby content or for location specific content.

2. We currently use jQuery mobile. With that we automatically have some themes to choose from. Since Google is so proud of its new Material Design, why not provide it as a (default) theme?

3. Provide some guidance/standard about how images should be optimized throughout the whole range of possibilities (see also screenshot below).

And finally: Not really a reason, but an AMP HTML page should score 100% on the Google PageSpeed Insights test which [it currently doesn't](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Famp.gstatic.com%2Fv%2Fmobile.nytimes.com%2F2015%2F10%2F07%2Fus%2Fpolitics%2Fhillary-clintons-proposed-changes-to-health-law-zero-in-on-affordability.amp.html%3Famp_js_v%3D0). So either change/correct the test or improve performance ;)

![image](https://cloud.githubusercontent.com/assets/1435963/11956288/651f7972-a8b9-11e5-9bcf-9dd59ad11617.png)

**Comment by cramforce** [comment]
1. We'll work on form functionality. @rudygalfi Are we tracking this anywhere?
2. This isn't a Google project as in we would have an opinion about Material Design. Having said that. http://www.getmdl.io/ should just work. Would you mind giving it a try and report back?
3. Working on it.

In general PageSpeed can only provide heuristics. Not everything is recommends is always correct, nor applicable. We are working with that team to improve their recommendations and we are addressing some of the points. But not because some tool says so, but because we have data that says it would be faster.

**Comment by cramforce** [comment]
Edited the title to reflect the content of the request.

**Comment by simonferndriger** [comment]
Thank you very much so far, cramforce. I'll check it out as soon as my calendar allows me to.

**Comment by rudygalfi** [comment]
We can track form support at #1286, which is mostly a stub for right now but can be expanded in the future.

**Comment by rudygalfi** [comment]
Also, following up within Google on the Material template and Page Speed, so closing this out.
