### ISSUE TITLE
<amp-bodymovin> to play JSON animation files generated by bodymovin for After Effects

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#12309]
https://aescripts.com/bodymovin/
https://airbnb.design/lottie/

AirBnB has a web player we can use. Light version might be a good version: https://github.com/airbnb/lottie-web

/cc @ericlindley-g @dvoytenko @spacedino

**Comment by nainar** [comment]
Hi folks, I would like to claim this issue. This comment covers the proposed design for this Intent to Implement:

# Background

[Bodymovin](https://aescripts.com/bodymovin/) is an After Effects extension to export animations designed in Adobe After Effects for playing on the web/other platforms. Animations are exported as .json files that use a player to then render the animation on the web. 

# Proposal
For the purposes of this element we will be using the AirBnB provided web player - [Lottie](https://airbnb.design/lottie/). It is an open source Bodymovin web player with the advantage of being in close coordination with the Bodymovin team (article [here](https://airbnb.design/introducing-lottie/)) which will hopefully ensure parity for all new Bodymovin features. 

## Simple Examples

`<amp-bodymovin loop="true" path="loading.json"></amp-bodymovin>`

The above example plays the animation in `loading.json` on an infinite loop.

`<amp-bodymovin loop=2 autoplay="false" path="loading.json"></amp-bodymovin>`

The above example plays the animation in `loading.json` twice only when the user triggers the `play` action.

## Demos

Demo here: https://nainar.github.io/example.html
Bodymovin .json file taken from here: https://www.lottiefiles.com/1531-loader

## Design Considerations

[lottie.js](https://github.com/airbnb/lottie-web/blob/master/build/player/lottie.js) supports all forms of rendering - SVG, Canvas and HTML. [lottie-light.js](https://github.com/airbnb/lottie-web/blob/master/build/player/lottie-light.js) restricts animations to the SVG format only. The decision re: which player to use is determined by what rendering we intend to support. 

* HTML5 Canvas is simply a drawing surface for a bit-map - this means the Canvas has no knowledge of the object it has painted, it's just pixels. This makes interactability is hard to code in Canvas - you will have to redraw the image from scratch eac time.
* SVG/HTML on the other hand maintains references to each object that it renders - this allows you to keep much better track of the elements you create and makes dealing with things like mouse events easier by default, but it slows down significantly when there are a large number of objects.
* Canvas would be better for faster things and heavy bitmap manipulation (like animation), but will take more code if you want lots of interactivity.
* SVG animation also has the potential downside of being deprecated in Chrome (and on the path to removal) as can be seen [here](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/5o0yiO440LM/59rZqirUQNwJ).

Given that most animations aren't looking for a large amount of interactivity, and the fact that SVG animations are deprecated, I vote for going with Canvas rendering and hence using [lottie.js](https://github.com/airbnb/lottie-web/blob/master/build/player/lottie.js). This means that the renderer argument passed to each call of `loadAnimation()` will be set to 'canvas'.

## Suggested Design

Since the Bodymovin animation needs an element to target the `<amp-bodymovin>` element will create a `<div>` to target when it is built. The `<div>` element will inherit the `width` and `height` attributes of the `<amp-bodymovin>` element. Then `<amp-bodymovin>` element will propagate the attributes set on the element itself as the `animationData` needed by the Lottie player's `lottie.loadAnimation(animationData)` call. 

Additional actions such as `lottie.play()` will be exposed as `amp-actions`

# Detailed API

## Attributes

The attributes for the `<amp-bodymovin>` element will reflect the configuration needed by the Lottie player. 

| Attribute 	| Mandatory? | Description | Accepted values
| --- | --- | --- | ---
| `path` 		| Yes | The relative path to the bodymovin `.json` file. | Strings
| `loop` 		| No | Determines whether the animation should loop or not. `true` is infinte loop, and `<number>` is a finite loop | Boolean, Number
| `autoplay` | No | Dictates whether the animation will start playing as soon as it is ready | boolean
|`name` | No | animation name for future reference | String

## Actions

`play()` - Plays the loaded animation.
`stop()` - Stops the currently playing animation that it is targetting.
`pause()` - Pauses the currently playing animation that it is targetting.
`destroy()` - Removes the objects associated with the animation being targetted. 


## Task breakdown

In the MVP we will only ship the ability to perform the following actions on a single animation (based on actions Lottie supports): 
* play() 
* stop() 
* pause() 
* destroy()

I would suggest that further actions on animations be added as Good First Issues - or I can take them on a rolling basis?
* setLocationHref(locationHref) 
* setSpeed(speed)
* goToAndStop(value, isFrame)
* goToAndPlay(value, isFrame)
* setDirection(direction)
* playSegments(segments, forceFlag)
* setSubframe(flag)

Lottie also provides more actions that are performed on all animations (hence all `<amp-bodymovin>` elements) that aren't immediately needed. See [Lottie Getting Started](http://airbnb.io/lottie/web/getting-started.html) documentation.

**Comment by aghassemi** [comment]
Thanks for the detailed write up! Comments below in bullet form:

### Name and Attributes
- The name `amp-bodymovin` vs `amp-lottie` may need some vetting. I feel like `amp-lottie` is more accurate but `amp-bodymovin` would let us change the player to something elsein the future. Good to discuss in the review meeting.
- `src` instead of `path` for consistency (and enforce HTTPS as we do with majority of external resources). 
- Do you know if `lottie` fetches the file itself or we can fetch it and pass it to them? I would prefer if we fetch so we can enforce [AMP CORS requirements](https://www.ampproject.org/docs/guides/amp-cors-requests). If that's not an option, do you know what their CORS requirements are?
- Just presence of `loop` should be enough. So `loop` and `loop=<iterations>` ?
- I wonder if `autoplay` should be default and we should add `noautoplay` (similar to `amp-gyfycat`). Sort of depends on what the common use of `amp-bodymovin` is: GIF like animations or animations that trigger to tap. I lean toward `autoplay` being default, good one to discuss in review meeting as well.

### Actions
- We can keep them `LOW-TRUST` actions similar to `amp-video-*` and `amp-animation` actions so they can be triggered via `amp-position-observer` and other LOW-TRUST events. (Given these actions are not disruptive and don't cause relayout, LOW-TRUST is fine). 
- We may also want to add `seekTo` which either takes `percent` and possibly `time` (similar to `amp-animation`). This would enable scrollbound bodymovin animations. (essentially your `goToAndStop` suggestion)
- I am not sure we need `destroy`. In `unlayoutCallback` of the component we certainly want to destruct it to free up resources but normally we manage the life-cycle of the components without authors needing to worry about it.

### Future Actions
- For `setLocationHref`, `setSpeed`, `setDirection`. We should just make those `attributes` and allow `amp-bind` to change them. (e.g. instead of `setLocationHref` one can just do `<amp-bodymovin src=initialSrc [src]="myAmpBindState.newSrc">`)
- `goToAndStop` discussed above as `seekTo`, `goToAndPlay` may not be needed since it will be `seekTo();play()`
- `playSegments` , `setSubframe`: not sure what they are supposed to do. May make sense as attributes + `amp-bind` as well.

:+1: for restricting to canvas.

**Comment by nainar** [comment]
Replying to Ali's comments: 

# Name and Attributes

1. `<amp-bodymovin>` vs `<amp-lottie>` your point of changing the player in the future + the fact that Lottie calls the player hosted on the webcdn bodymovin makes me lean towards `<amp-bodymovin>`. Maybe `<amp-bodymovin-player>` to make sure people understand that this is the player and not the After Effects plugin?
2. `src` instead of `path` (and enforce HTTPS) - Ack.
3. TODO
4. `loop` - Happy to accept your suggestion
5.  Lottie has `autoplay` set to 'true by default' so I am happy to take your suggestion of having the attribute be `noautoplay`

# Actions
1. LOW-TRUST actions  - Ack.
2. `goToAndStop` -> `seekTo`- Ack
3. `destroy()` being superflous - Ack

# Future Actions
1. `setLocationHref`, `setSpeed`, `setDirection` -> attributes. TIL. Ack.
2. `goToAndStop` `goToAndPlay` not needed - Ack
3. `playSegments()` -> lottie allows you to play segments of an animation by passing in a single array or multiple arrays of two values each(fromFrame,toFrame) to play.

**Comment by bodymovin** [comment]
Hi, I'm part of the Lottie team and I wanted to make a clarification regarding the SVG renderer.
Since it doesn't rely on SMIL for animations, an eventual deprecation of the SMIL support on browsers shouldn't affect the player.
My advise would be to go with the svg renderer which supports more features, allows manipulation of properties via css, and is supported by the light version of the player.
It's true that the canvas player might be more performant in some cases but svg rendering is becoming much better with time.
If the full player can be used, it would allow users to select any renderer they feel is convenient for their specific animation. Also, the full player supports After Effects expressions which the light version doesn't.

**Comment by aghassemi** [comment]
Hi @bodymovin! Thanks for the clarification and really appreciate reaching out to us! 

Regarding SVG/Canvas/HTML, what we really hope is removing the need for developers to "worry about" what to pick so even if we make it configurable, it is important for us to pick the best default. With your insights, svg + light player looks pretty promising as the right defaults. I will defer the final decision to @nainar here.

**Comment by nainar** [comment]
Yup, thank you for sure for reaching out! :) 

Light + SVG sounds good. We can always expand and give people the option to pick the renderer they have if needed. But giving developers a well lit performant path is the way to go for AMP. :)

**Comment by bodymovin** [comment]
Hi, makes sense. If I can help in anything, please let me know.

**Comment by aghassemi** [comment]
suggestion by @cramforce to drop `player` from the name as not to confuse with video players.

**Comment by nainar** [comment]
Just some updates since the last design discussion:
* Potential name: `<amp-animation-bodymovin>`
* We fetch JSON object and pass it to the Bodymovin player

Implementation plan:
* V0: Basic load and play animation (without being able to trigger autoplay off)
* V1: More actions and attribute to control autoplay

**Comment by nainar** [comment]
Name we are going with: `<amp-bodymovin-animation>` as the prefix implies that this is a feature of `amp-animation` n-> which is incorrect. `<amp-bodymovin-animation>` also implies that this is a bodymovin produced animation. 

Shipping this! :)

**Comment by nainar** [comment]
The basic MVP has been shipped. Please file new issues for implementation issues.

**Comment by aalinoosh** [comment]
amp-bodymovin-animation does not show lottie.json
