### ISSUE TITLE
amp-list: Remove src attribute requirement?

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#12372]
Context: #12367

For some use cases of amp-list (i.e. with amp-bind), having `src` attribute is not strictly necessary. To workaround, pubs can just set a garbage value but amp-list still attempts an XHR.

Should we (1) remove that requirement outright or (2) only allow omission when `[src]` is present or (3) require existence of placeholder element?

/cc @4-1-1 @ericlindley-g

**Comment by 4-1-1** [comment]
@choumx @ericlindley-g 
I want to make  a menu with sub menus, I don't know how to do it with amp-bind and amp-list, can you make a demo for us?  Thank you very much.

**Comment by ericlindley-g** [comment]
Hi @4-1-1  — you can find a demo of a responsive menu with submenus [here at AMP Start](https://ampstart.com/components#navigation) (just change the size of the viewport to see the responsive behaviors at different sizes). If that doesn't fit your needs, I recommend opening up a different issue in the [AMP by Example repository](https://github.com/ampproject/amp-by-example), which is where examples for developers are requested and discussed. Thanks!

**Comment by ericlindley-g** [comment]
+1 to this feature request — I don't have a strong opinion about (1) or (2), though (3) would be good to have

Two additional thoughts to consider going forward:

A) Were we thinking of extending amp-list to be able to reference JSON already included on the client? In that case, I could see the following logic for requiring a placeholder:

Require a placeholder if:no src specified AND no JSON in doc specified
Else, do not require a placeholder


B) It looks like we don't resize amp-list if its height=0 at load. Is that still necessary, if we fix the resizing logic as we're already planning to do?

If it's not necessary, we could lift the restriction on height=0, and the logic for requiring a placeholder could then be:

Require a placeholder if: amp-list height>0 AND no src specified AND no JSON in doc specified
Else, do not require a placeholder

**Comment by 4-1-1** [comment]
@ericlindley-g  Thank you, I checked the demo in ampstart, maybe it could fit me nowadays, but I prefer to expand the amp-list attributes, add a child or items.child or something you like, enable it to render unlimited menus,  Three-level menu, Five-level menu , etc

**Comment by ericlindley-g** [comment]
Thanks @4-1-1 — feel free to drop a feature request in AMP by Example. For what it's worth, a menu with more than 2-3 levels might start to get hard for users to navigate well. If you do file a feature request, it would help to post a non-AMP example URL of the behavior you're looking to support or get an example for in AMP.

**Comment by 4-1-1** [comment]
@ericlindley-g  I just wanna to make our first amp page exactly same as before,  we are commerce website, the menu is the catalog of our product,  it's three-level menus. 
  I have another question,  if I use myself amp.js files,  after we online the page,  can it be faster and  get the special AMP icon when it opened in google or facefook?

**Comment by ericlindley-g** [comment]
@4-1-1  Valid AMP pages need to use the AMP .js files hosted at cdn.ampproject.org, so what you shared wouldn't validate, and so wouldn't be served from an AMP cache

**Comment by cpapazian** [comment]
>A) Were we thinking of extending amp-list to be able to reference JSON already included on the client? In that case, I could see the following logic for requiring a placeholder:

This functionality already exists in the `mutatedAttributesCallback` method of amp-list. 
```
      } else if (typeOfSrc === 'object') {
        const items = isArray(src) ? src : [src];
        this.renderItems_(items);
      }
```
You can trigger amp-bind to point to an object or list in amp-state instead of a URL, in which case `renderItems_` is called immediately, rather than after the fetch resolves. 

Are you suggesting this capability be added to the initial state of the amp-list? That would be great, and is something I've been thinking about for a while. I didn't see a separate ticket for this. I can create one and take a crack at an implementation if that would be helpful.

**Comment by choumx** [comment]
That could work but I think we might want to discourage unnecessary client-side rendering in principle. I.e. publishers should just use `placeholder` to display zero-state content.

**Comment by AndrewKGuan** [comment]
Hi,
is it possible to use an amp-state (json), rendered directly on the AMP's html, to be the initial src of amp-lists?  Here are a several use cases, I'm sure there'll be more that I can't think of at the moment:

- as the initial values to supply the amp-lists' rendering instead of waiting for a server fetch (xhr).  Think about eCommerce's product listing/filtering, if nothing applied to the filter, the first page of the products could be directly coding into the AMP for faster completion of the page.  Any user actions to apply the filter which changes the list of products, or tapping 'next 20' on the pagination,  will then trigger the xhr.  So instead of `<amp-list src=xhr_url, [scr]=amp_state_json>`, `it becomes <amp-list src=amp_state_json [src]=optional_xhr_url>`.

- one single amp-state json to render multiple amp-lists that are responsible for rendering a portion of the json.   Think of a multilevel parent-child linked <select> drop-downs, something like "select state -> select city -> select office location".  One could easily construct a simple json that represents such a tree and have it right there on the AMP itself instead of fetching on each level of the select.  Also if the person tries to do that using amp-bound <select> tags using show/hide, it would be prohibitively complicated.

The general idea is to allow higher level of programmability to AMP (closer to what developers enjoy with the plain old non-amp fashion) and to allow decoupling between data & rendering.

**Comment by choumx** [comment]
@AndrewKGuan Thanks for explaining your use case. Sounds like you want #12002.

**Comment by josh313** [comment]
+1 to this feature. Was a final agreement about how to relax this requirement ever reached? I'm in favor of options (1) or (2). I think a placeholder element seems unnecessary because the main use case I see for this is when the amp-list is hidden (so the placeholder wouldn't show up anyway).

**Comment by choumx** [comment]
(2) is not possible with current validator's features. [`mandatory_oneof`](https://github.com/ampproject/amphtml/blob/1002eaf6735cfc37588f16361c6e6ca5e1223c57/validator/validator-main.protoascii#L4887) is close but is exclusive, we need something like `mandatory_atleastoneof`.

I think (1) is fine. We can add a runtime user error if neither `src` or `[src]` are present.

**Comment by josh313** [comment]
Sounds good. I can make this change this week if you'd like. Or do we need to discuss/get approval from anyone else first?

**Comment by choumx** [comment]
Actually we could do this in the validator by duplicating the tag and make the new one have a mandatory `[src]` and optional `src`. 

Validator tests can be tricky though so I think it'll be faster if I do it quickly now. Thanks for volunteering!
