### ISSUE TITLE
Feature: trigger tracking events from amp-iframe content via postMessage

### ISSUE THREAD

**Issue by p2er** [ampproject/amphtml#12607]
## What's the issue?

If AMP is used for tracking and it is legally required to have opted in to tracking or for the user to at have least seen the cookie dialog the iframe can not contain custom tracking, unless a custom dialog is shown, since the iframe is unaware of the tracking state of the AMP document. 

The iframe also has to load additional tracking scripts which might impact the page/iframe performance. The duplicate implementation of tracking and unnecessary load of additional scripts might easily be avoided if the iframe could postMessage to the AMP page, where AMP-analytics could then execute a predefined trigger to handle the calls.    

## How do we reproduce the issue?

1. build simple amp page with amp-analytics trigger predefined
2. include amp-iframe in page
3. build simple iframe content page with post message implementation to trigger tracking event on link/button click
4. click button/link inside iframe
5. fire tracking request on AMP page prior to link navigation

## What browsers are affected?

All browsers for new feature.

## Which AMP version is affected?

Upcoming if implemented.

**Comment by rudygalfi** [comment]
If I'm understanding the requirements correctly, I think there's two separate ideas combined here.
* The first relates to enabling iframes to send their events so that they can be tracked as part of an amp-analytics configuration. As far as I know, this isn't supported today. It's somewhat related to the idea of the [video interface](https://github.com/ampproject/amphtml/blob/master/src/video-interface.js) supporting analytics, but asked for in a much more generic way. Would be interesting to get @choumx's feedback relating to 2-way messaging here.
* The second idea is related to disallowing tracking when the user has not yet consented to it. It is not reasonable to expect the iframed page to present the consent UI. Therefore, the AMP page needs to handle this by either blocking the iframe or informing it that it cannot perform its own tracking within.

Does this sound like an accurate summary?

**Comment by p2er** [comment]
Yes, that is correct and sums up the idea very well.

**Comment by rudygalfi** [comment]
Thanks for the feedback. Closing this in favor of tracking #13196 and #13197 separately.
