### ISSUE TITLE
Increase Priority of Ads when AMP pages are hosted on publishers domain.

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#12656]
This is a follow up to issue #12232. This has been pulled out as a separate issue for clarity, and to continue the discussion.

The proposed question is this:
For sites like https://m.mynet.com/ should we relax ad loading constraints because it is being served from the publisher origin? 

We have now agreed to do this if publishers are using the suggested PWA + AMP structure, but there still is some discussion around if self-hosted AMP pages should get the same treatment. It should be a fairly simple thing to implement, once we reach a consensus.

**Comment by jasti** [comment]
My preference would be to do this for all documents that serve from origin given that publishers today can schedule ads however they want on non-AMP pages. @dvoytenko do you have strong objections to this? If not, is it possible to make this configurable when not on origin?

**Comment by lannka** [comment]
AMP advocate many good practices. Yielding ads load to content load is one of them. I think we should keep a good user experience on AMP no matter where the page is served.

We made change for PWA because we believe PWA has other performance benefit in place.

**Comment by jasti** [comment]
AMP is a sliver of the traffic when served from cache whereas it's 100% of their monetization when served from origin. Any drop in revenue due to the slowness of ads (and we know ad slowness causes drop in revenue and viewability) will immediately cause roll back of AMP. I have very little hopes AMP canonical becoming a thing unless all ads on page are in AMPHTML - but we are quite far away from that. 
Therefore, it's a decision between having any AMP pages at all with relaxed ad constraints vs no AMP pages at all.
We could always roll this back to the original state when we have good number of AMPHTML ads in the ecosystem.

**Comment by jasti** [comment]
@cramforce thoughts on above please? The request is mainly coming from one publisher who is already live on canonical AMP.

**Comment by cramforce** [comment]
I don't want any more differences between AMP Cache and origin. The AMP Cache is going away as a separate thing anyway with https://amphtml.wordpress.com/2018/01/09/improving-urls-for-amp-pages/

**Comment by jasti** [comment]
Thanks, closing then.
