### ISSUE TITLE
"!important" in comments breaks AMP validation

### ISSUE THREAD

**Issue by leik0401** [ampproject/amphtml#12651]
## What's the issue?
It seems like a bug to not allow "!important" even in comments for AMP ads.

## How do we reproduce the issue?
For example:
https://screenshot.googleplex.com/q1tHVDpHCrg

**Comment by cramforce** [comment]
CC @Gregable

**Comment by powdercloud** [comment]
Yeah it's a slight bit annoying. So, allowing it means we have to treat comments differently than the rest, as we currently do the !important scan with a regex, as specified in here (https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii, look for !important); this regex applies to the entire text. We'd need to strip comments before applying regexes for example, but then we'd need to make sure that this doesn't introduce some security hole (what if <!-- appears within a /* ... */), and/or we could also strip the CSS comments in the cache - which seems like a good thing to do in general but I don't think we do it right now. We'd need to do the comment stripping properly of course, this isn't too hard as we have a parser.
So I don't think it's unreasonable, but still, it adds some complexity to what we're doing at the moment and there are easy workarounds, e.g. putting a space between ! and important, which doesn't subtract much from the usefulness of such a comment. So I'm kind of inclined to let this go just to keep things simple - notwithstanding that comment stripping etc. may be good in their own right, but it would be better to drive the stuff that makes things more complex with strong motivations rather than cosmetics. :-)

**Comment by Gregable** [comment]
Will leave the issue open for tracking, it's a legitimate issue, but it's probably going to sit around for a while, so if you need a fix I'd work around by adding a space like @powdercloud mentioned..

**Comment by Gregable** [comment]
Fixed. Not in production yet, but closing.
