### ISSUE TITLE
amp-image-lightbox thumbnail with extra zoom image

### ISSUE THREAD

**Issue by mazuk6** [ampproject/amphtml#12724]
My understanding of a lightbox component is: you have a thumbnail Image and get a bigger image opened in a bigger view once you click the thumbnail. I am missing this logic completely.  When making an AMP-Only Website I have to load all the big images as thumbnails in the desktop view in order to not getting blurry zoom images.

It would be nice to have a possibility to define an extra zoom image.

Thank you,
Markus

**Comment by aghassemi** [comment]
@mazuk6 Absolutely. We are working on a new image gallery component and will keep this in mind.

**Comment by cathyxz** [comment]
@mazuk6 I think what will actually solve this issue is solving https://github.com/ampproject/amphtml/issues/11575. For both the current `<amp-image-lightbox>` and as designed for `<amp-lightbox-gallery>`, we will use `srcset` to upgrade the image to its desired resolution in lightbox mode depending on the zoom scale. Basically what you should do is just provide a `srcset` that includes a low-res image for your default thumbnail, a medium-res image for the lightbox mode, and a high-res image for lightbox zoom mode. Note that this isn't an appropriate use for cropping / different dimensions, only for different resolutions of the same image. The problem isn't that lightbox doesn't upgrade, it's rather that we don't have the option to provide a lower resolution thumbnail default. This problem can be solved with `sizes` and `srcset` once we resolve https://github.com/ampproject/amphtml/issues/11575. 

I believe that `<amp-image-lightbox>` already handles upgrading resolution. This parity feature is tracked for `<amp-lightbox-gallery>` in https://github.com/ampproject/amphtml/issues/12929.
