### ISSUE TITLE
amp-img srcset behavior

### ISSUE THREAD

**Issue by Nemo64** [ampproject/amphtml#1280]
I noticed some things about the `<amp-img>` `srcset`:

The [amp documentation](https://www.ampproject.org/docs/reference/amp-img.html#attributes) currently states that the `srcset` attribute is the same as on an `<img>` and that "The behavior will be polyfilled where not natively supported".

However: the native `srcset` is never used and the behavior differs in that the `sizes` attribute is not responsible for the image lookup (`getLayoutRect` is used if i read the code correctly). This is a mayor advantage over the native implementation in my opinion since this doesn't force me to hardcode my styles in the markup.

The documentation should mention the different implementation or the implementation should enforce the `sizes` attribute and use it to decide which image to use.

Personally: i think the current implementation is more advanced than the native one and since an amp document has a more stable layout than vanilla html there won't be any problems with it except that browser zooming doesn't change the used image.

**Comment by cramforce** [comment]
Over to @dvoytenko

**Comment by dvoytenko** [comment]
Yeah. Good point. `sizes` attribute is not necessary in our cases for `srcset` with width selector. I will update the documentation. We'd also normally be able to select `srcset` correctly based on the touch zoom, but we ran into an issue that, while we can tell the zoom reliably, there are no reliable events that tell us that it changed...

**Comment by dvoytenko** [comment]
Also, an important note - we extended `sizes` attribute to all other AMP elements. It's convenient and, in our case, there's no reason why it should be restricted only to images.

**Comment by Nemo64** [comment]
Even though i haven't mentioned using the sizes attribute on other elements: I don't really know how the `sizes` attribute has any advantage. It can be completely implemented using css and `layout="responsive"`. Also: the sizes attribute does not allow for values like `100%` which limits it even further.

**Comment by dvoytenko** [comment]
@Nemo64 I don't believe `sizes` allows percent values. I don't have a handy written proof, but a quick test shows this to be the case. Generally %'s go somewhat against the idea of `sizes`. Do you have any indication otherwise? Otherwise, yes, you are right. Advantages are very limited over CSS - it's mostly stylistic thing and we anticipate with some CMS's `sizes` would come more naturally. One notable benefit is that `sizes` does allow a much earlier and precise estimate of what the width of the element will eventually be, even before layout is complete.

**Comment by mjangda** [comment]
`sizes` has come in handy for the WordPress plugin. We're using it to provide better responsive behaviour for images.

Our page container has a max-width that defaults to 600px. Let's say we have an image with only one size at `350x100`. If we just specify width+height and `layout=responsive` on the `amp-img`, on viewports `> 300` it will grow to fill the page container which is not desirable (images get pixelated).

We want the image to not grow beyond its width (350) but shrink to fill the screen on viewports smaller than its width. We were able to leverage `sizes` for this:

```
<amp-img src="http://placehold.it/350x100" width="350" height="100" layout="responsive" sizes="(min-width: 350px) 350px, 100vw"></amp-img>
```

When the viewport grows beyond 350px, the image width is forced to 350px. When the viewport is less than 350px, it uses the full-width of the viewport (or the image's container).

The main benefit to this approach has been that we can just specify the `sizes` inline rather than having to generate CSS rules for each image.

Here's a pen demonstrating this: http://codepen.io/mjangda/pen/zrdadp/

**Comment by Nemo64** [comment]
@dvoytenko yes, sizes doesn't allow percent values. What the native version does allow however is the css `calc()` method to describe layouts like `calc(100vw - 30px)` which the amp `sizes` attribute does not allow. The workaround is to not define `sizes` and simply use `max-width`. Only downside is that it might be required to generate css dynamically based on the content which might be difficult in some systems. Basically the same as what @mjangda said but with the addition that not every percentage layout has `100vw` so the sizes attribute can't be used for that reliably either.

However: The sizes attribute itself is probably stuff for another issue though.

**Comment by dvoytenko** [comment]
Thanks @Nemo64 . I filed a separate bug #1428 to support calc expressions in sizes.

**Comment by ericlindley-g** [comment]
@dvoytenko is this M1 or M2?

**Comment by rudygalfi** [comment]
Putting in M1 just in case, but please advise.

**Comment by dvoytenko** [comment]
I think this is a M2.

**Comment by winstonma** [comment]
I am not sure if it is related but I have similar issues. When I use the put the following image in a `div` then the image stays within the `div`.

> `<amp-img src=big.png srcset="small.png 120w, mid.png 240w, large.png 375w" width="375" height="201" layout="responsive">`

But then the sizes element is added, then the whole picture is not bounded by the `div`

> `<amp-img src=big.png srcset="small.png 120w, mid.png 240w, large.png 375w" width="375" height="201" layout="responsive" sizes="100vw">`

Since I am showing 3 pictures on one row (for large screen) and 2 pictures on one row (for smaller screen), I want to make sure that the right picture will be downloaded. In my old implementation when I use a cellphone the mid.png will be downloaded. Now they will download the large.png until I shrink the browser width.

Thank you very much

**Comment by dvoytenko** [comment]
@winstonma 

Hmm. That sounds expected if you request the width to be `100vw`. 

It sounds to be that you want to be using flexbox layout to do what you want.

**Comment by winstonma** [comment]
@dvoytenko Thanks

I used Bootstrap and the responsive image will only use 100% of the `div`. I am still using Bootstrap grid to organize the layout so I expected that the grid width will bound the image within.

The reason I want to set sizes is because the I have responsive layout. In mobile screens it shows 2 images / row while it shows three images / row on desktop. So I need to set the size for the web to download the smallest possible image.

**Comment by dvoytenko** [comment]
@winstonma You can use `layout=responsive` which will give you 100% of container. You don't  need `sizes=100vw` on top of that.

**Comment by winstonma** [comment]
@dvoytenko Thanks a lot

According to [Web Fundamentals - Images](https://developers.google.com/web/fundamentals/design-and-ui/media/images), it states that if I use `sizes="50vw"`, and when the browser width is 400px and the pixel ratio is 1, the 200px image will be used. Without setting the sizes attribute now it will always download the best image (since my best image is 400px, and mobile width is almost > 400px). I know it is working but it is not bandwidth-friendly.

**Comment by dvoytenko** [comment]
@winstonma In AMP this is automatically handled. The image is selected based on `sizes`, but also based on the real-environment image width.

**Comment by winstonma** [comment]
@dvoytenko Thanks for the response

**Comment by adelinamart** [comment]
Are there any open questions here, or we can close this? Thanks

**Comment by winstonma** [comment]
@adelinamart Now I understand that `amp-img` chooses image based on the screen width, but not screen width **and** view width. I now understands more on the `amp-img` but still supporting view width would be very useful. Could I request view width support on `amp-img`?

**Comment by adelinamart** [comment]
@ericlindley-g is this something we can support?

**Comment by dvoytenko** [comment]
@winstonma 

> Now I understand that amp-img chooses image based on the screen width, but not screen width and view width

What are "screen" and "view" widths? `srcset` selection is done based on the image's width, `sizes` selection is done based on media queries, which are mostly viewport-based (or window-based).

I'm going to close this issue for now, but feel free to re-open as needed.

**Comment by winstonma** [comment]
Sorry @dvoytenko I think I said it wrongly. What I look for is `sizes` support.

For example. If I am showing a static album, 2 pictures per row on a phone that its width is 480px. In HTML I could add `sizes="50vw"` so it would collect 240px picture and show it on the screen. As `amp-img` doesn't support sizes yet so it would measure the width of the screen and get 480px picture. I added some comment because I feel supporting `sizes` would be mobile-network friendly.

**Comment by dvoytenko** [comment]
@winstonma  `sizes` is [supported](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-layout.md#sizes). You might have missed because we extended this feature to all AMP elements, so it's documented in the common docs.

**Comment by winstonma** [comment]
Thanks @dvoytenko for clarification. But I still can't get my HTML works.

I got the following code that would put pictures on the same row:

> <amp-img
>    src=image.png
>    srcset="image-120.png 120w, image-240.png 240w, image-320.png 320w"
>    width="375"
>    height="201"
>    layout="responsive"
>    sizes="(min-width: 768px) 33vw, 50vw"
>    alt=""

I got 2 of the above elements.

I tested the code on Chrome with Nexus 5X framework (width 412px, DPR: 2.6). I would like the image `image-240.png` would be used but it grabs image.png. How should I structure my HTML code so that the smaller image will be grabbed?

Thanks

**Comment by dvoytenko** [comment]
@winstonma do you think you could package the example in a jsbin? I'll be able to do a direct debug on that.

**Comment by winstonma** [comment]
@dvoytenko 

Here is the [JS Bin](https://jsbin.com/quriboq/1/edit?html,output). For example when the width of the output window is set to 750px. I would the 480w image would be used.

Thank you very much

**Comment by jridgewell** [comment]
So we have two issues here:

1. Selection of closest image
2. Selection with DPR

> 50%vw would be 375px

Working from this, we can either choose 320px or 480px. We select the nearest, with a 10% bias towards larger images. So distance to 320px is 60 (66 with the negative bias) and distance to 480 is 105. So, 66 wins, and we select 320px.

Second issue is the DPR, which you've listed as 2.6. That means we're not trying to fit a 375px slot, we're trying to fit a 975px one. So a much larger image will be selected. So now we want 975px, and the largest possible selection is only 720px. So it wins (because there's not a larger to compare against).

**Comment by winstonma** [comment]
Thank @jridgewell 

Yeah I know DPR plays some role here. But honestly I don't know how to transform DPR to px. But I played around the [JS Bin](https://jsbin.com/quriboq/13/edit?html,output) on my PC (not on mobile layout). Please set the output screen (on the right hand side) to 768px screen width. My questions are:

1. The output shows 3 pictures at the same row (which is correct). But with the second picture and third picture set the `sizes` attribute is being set. There is a gap between 2 pictures. Also it seems to me that the first picture is larger than the second and the third picture. Lastly when `sizes` is not set, the gap between picture disappear.
2. Under the same configuration, why picture width of 480px is being selected. With 768px width, for each picture the screen width is 256px. I am not sure if DPR plays a role in PC monitor.
3. Under the same configuration, `amp-img` selected width the 480px for all three pictures. With the first picture `sizes` attribute is not being set and the second and third picture `sizes` is set to `33vw`, why all three shows the same picture? I would expect adding the `sizes` attribute would eventually causes `amp-img` to select a smaller picture.

Thanks for clarification.

**Comment by dvoytenko** [comment]
@winstonma 

The gap is probably due to some unrelated CSS. I scanned through your CSS and in particular, I think this might have to do with 33.3333% vs 33vw. But it could also have to do with floats used, etc. The size of images itself cannot affect the gaps. That being said, generally, I'd recommend using flex-box as a more universal tool for something like this.

RE: `480px` - correct, most likely it's due to DPR. In Chrome DevTools you can select DPR = 1.0 and refresh to see how this changes. The images will like go to 240px versions.

RE: the same image size. In the end of the day, the final selected images depend on the layout. From what I can see: all images are nearly the same size. Thus I'd expect the same quality image to be  used for all of them. I.e. whether it's due to 33vw or by other layout rules, the images end up around 253px wide on the 768px monitor. Thus the resulting image is selected accordingly.

Finally, the first image ends being slightly bigger in layout. This is because the other two images have width mandated as 33vw (768px * .33 = 253px). However, the first image is requested to take the rest of the available width, or roughly `768px - 253px - 253px = 262px`. Minus some the gap you mention above, it looks like this ends up being around 259px.

**Comment by winstonma** [comment]
@dvoytenko Thanks for the help

Really appreciate your effort and detailed explanation. I think using example would be a better than just giving my vague misunderstanding.

Thanks

**Comment by dvoytenko** [comment]
Sure. Examples are always the best!

**Comment by acusti** [comment]
@jridgewell Is there a way to customize or overwrite the “selection of closest image” algorithm? It seems like there’s a proportionality to that choice that the current logic doesn’t account for.

If you have a 400px wide and 800px wide version of an image in the srcset, and the current `<amp-img>` element width is 550px, amp selects the 400px version and you wind up getting a highly distorted image rendering. In that case. However, if you had 1400px and 1800px wide versions of an image, and the current element width is 1550px, choosing the 1400px version is a good call. It seems like there should be a maximum ratio for the distance of the actual element size to the smaller size as compared to the size of the smaller image, maybe around 0.2. In specific terms, my first example: `(550px - 400px) / (400px)`, 0.375, which would be above the max ratio, so `<amp-img>` chooses the larger image. The 2nd example: `(1550px - 1400px) / 1400px`, 0.107, so `<amp-img>` goes with the smaller image.

This should also scale down to smaller image sizes. I recently had an instance where we had a `30px` and `120px` wide image version in the `srcset`. The element was being rendered at 70px, and `<amp-img>` was choosing the 30px version, which of course looks unacceptable. The ratio makes it obvious: `(70px - 30px) / 30px`, or 1.33.

If you would prefer me to make a new issue about this, I would be more than happy to do so. Thanks for your consideration and very impressive work on :zap:!

**Comment by jridgewell** [comment]
I think that's a pretty good idea. Please submit a PR!

**Comment by acusti** [comment]
Right on! PR: https://github.com/ampproject/amphtml/pull/8055
