### ISSUE TITLE
amp-bind does not work on LocalDev anymore

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#12860]
It ries to load the `worker` (`ww.js`) from CDN instead of localhost.

Might be related to recent isLocalDev changes. 

/to @rsimha-amp @choumx

**Comment by aghassemi** [comment]
it does work after a `guld build` and restart of `gulp serve`. But not with `gulp watch`

**Comment by aghassemi** [comment]
actually probably same as https://github.com/ampproject/amphtml/issues/12852 ?

**Comment by rsimha-amp** [comment]
Yes, this looks like it is #12852. Will confirm tomorrow.

**Comment by rsimha-amp** [comment]
You're probably not waiting for the full build when you run `gulp`. Note that due to how `gulp` works, the server starts way before the build is complete.

**Comment by aghassemi** [comment]
My work flows is that I run `gulp serve` and `gulp watch` in separate windows and keeps them always running. As I switch branches and do my coding, it used to just work. (I have had serve and watch running for months). Would be nice to have that flow work again.

**Comment by rsimha-amp** [comment]
`gulp` does exactly what you're doing: it runs `gulp watch` and `gulp serve`. However, `serve` starts early, even before `watch` is done with the full build. That's being fixed in #12852. 

Meanwhile, a workaround you can use in your separate-window setup is to make sure you fetch the runtime from the server after the first full build is complete.

**Comment by rsimha-amp** [comment]
I just discovered that `gulp` does not build `ww.js` as part of `gulp watch`. This is a bug!

Fixing via #12895
