### ISSUE TITLE
amp-carousel does not seem to work fine with amp-video

### ISSUE THREAD

**Issue by pmlopes** [ampproject/amphtml#1293]
I was trying to make a carousel with a mix of photos and videos (like a photo gallery) and i noticed the following:

Once me as a user starts playing the video the carousel navigation buttons dissapear and i can't navigate out of it (either left or right).

If i do not enable the responsive layout of the video and it fits in the carousel (because the video is smaller than my screen) then i can use the carousel buttons to navigate left/right BUT the video keeps playing in the background.

Is this possible? have a carousel with video (mp4) not 3rd party providers like youtube/vine/etc...?

**Comment by dvoytenko** [comment]
@pmlopes you are using `type=slides` carousel, right?

@erwinmombay Seems very strange, why would arrows disappear? And we should definitely stop video from playing as soon as it's out of the view.

**Comment by pmlopes** [comment]
This was my experiment: https://gist.github.com/pmlopes/59540785ac82410c80d6

Basically i started stripping the full example to just have a carousel with both pictures and videos

**Comment by pmlopes** [comment]
to see the arrows dissapear you need to use amp-video with layout responsive `layout="responsive"`

**Comment by erwinmombay** [comment]
thanks @pmlopes ! looking into this

**Comment by erwinmombay** [comment]
"If i do not enable the responsive layout of the video and it fits in the carousel (because the video is smaller than my screen) then i can use the carousel buttons to navigate left/right BUT the video keeps playing in the background." -- this is definitely a bug.

@pmlopes can you clarify this a bit more "Once me as a user starts playing the video the carousel navigation buttons dissapear and i can't navigate out of it (either left or right)." 
- can you provide a screenshot of this scenario (if possible)
- does it look like this? (below)

<img width="371" alt="screen shot 2016-01-07 at 3 37 12 pm" src="https://cloud.githubusercontent.com/assets/354746/12186116/9643e252-b554-11e5-8810-3ccfb67c5eea.png">

wherein you click play, the controls fade away and the "next" button appears. The next button appearing is a bug, but the controls fading away is intentional (shows again on tap, or hover on desktop)
