### ISSUE TITLE
Blessing videos silently fail on iOS

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#12976]

**Comment by newmuis** [comment]
Was able to reproduce this starting from a blank JsFiddle and working towards our implementation.  [Here's the repro case](https://jsfiddle.net/ub0dvg96/6/) I came up with.

I'm currently trying to test whether the bug is related to the iOS device-specific limitation of how many videos can be in memory at once (16 on everything I've tried; #11856 has some details around this with respect to our implementation).  I am able to trigger the bug with fewer than 16 videos in memory, but it does also appear as if fewer videos does correlate with the bug being less likely to occur.

**Comment by newmuis** [comment]
This appears to be working on both fronts 😄   I've currently got this deployed; you can try it on any story by using https://ampnewmuis.herokuapp.com/proxy/$YOUR_AMP_STORY_URL.

I'll clean up my PR and send it for review tonight or tomorrow.
