### ISSUE TITLE
Design Review 2018-03-14 20:00 UTC (AMP content rendering, amp-story metadata)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#13089]
**Note the new start time to accommodate Daylight Saving in some parts of the world.**

Time: [2018-03-14 20:00 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2018&month=3&day=14&iv=0)
Location: [Video conference via Google Hangouts](https://hangouts.google.com/hangouts/_/google.com/amp-eng-desrev)

The AMP Project holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by alanorozco** [comment]
- Proposals for component rendering solutions #13906

**Comment by lannka** [comment]
@Gregable shall we also talk about the cashapona thing?
/cc @zhouyx

**Comment by choumx** [comment]
- Quick followup to `amp-story` metadata: #11989

**Comment by aghassemi** [comment]
## Notes

### AMP Content Rendering by @alanorozco 
#### Problem:
- manually creating DOM in Stories is complex and non performant

#### Goals:
- reduce overhead in Stories
- define how templating can be used internally

#### Non-Goals
- don't need a whole new component workflow like react+flux
- not for user-authored templates.

@jridgewell `handlebar` is not statically analyzable, `mustache` is.
Q: @jridgewell Is the goal rerenderable or jsut render once and then I manually render?
A: @alanorozco just initial rendering for now.
Q: @aghassemi How does SSR work for cases where there is dynamic data involved?
A: @alanorozco Templates is still rendered to HTML SSR and then reference to nodes are given back to runtime to fill with dynamic data. (using the `ref` attribute).
@kristoferbaxter The nice thing about this is that it is template-language agnostic, it can be mustache, casophena, etc..
@jridgewell so we can do all of this we a simple innerHTML and a regex to make sure there is no mustache thing in it. innerHTML + audit would be faster than bunch of DOM manipulations.
@alanorozco we can decide to do innerHTML during render step, it is an implementation details.
@alanorozco will create a sample PR to show the benefits of this.

### Quick followup to amp-story metadata
- Recap of previous discussion on #11989 but there is a twist
- The proposal is to use attributes for config but only a handful and not extensible. 
- This is nice because they may become useful in the actual story itself in the future.
- @kristoferbaxter  Why not json-ld again? 
- @choumx big reason is it is optional and if author does not put it there we can use them in the stamp itself. 
- @jpettitt Why not enforce json-ld?
- @choumx Enforcement is tricky, it is meta-data it is not format. 
- @jpettitt  But we can enforce it. There is infrastructure there.
- @jpettitt @aghassemi force in both places?
