### ISSUE TITLE
[Layers] amp-lightbox scrollable makes amp-list not trigger

### ISSUE THREAD

**Issue by nha** [ampproject/amphtml#13102]
## What's the issue?

Bug:

amp-lightbox "scrollable" attribute makes the `amp-list` component inside it not trigger a view

context: https://groups.google.com/forum/#!topic/amphtml-discuss/TEbNkNQGDEc

## How do we reproduce the issue?

Steps to reproduce:
- open https://gist.github.com/nha/07f38a4dfa0da3e9648272fadcd8862f
- copy/paste in the amp-playground https://ampbyexample.com/playground/
- see that when clicking on the tabs the content does not load (that's the bug)
- see that by removing the "scrollable" attribute they load (in my case I need the scrolling though)

## What browsers are affected?

All browsers/devices as far as I know.

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1516833286380

EDIT: could be related to https://github.com/ampproject/amphtml/issues/10609 (?)

**Comment by aghassemi** [comment]
@jridgewell Good test case for layers.

**Comment by juliavallina** [comment]
Here is another example of the same bug

## How to reproduce the issue?

1. open https://gist.github.com/juliavallina/a11a960ed123cdb6b8949cddc384d3ba
2. copy/paste in the amp-playground https://ampbyexample.com/playground/
3. click on "Inicia tu busqueda" button
4. focus on "Escribe un destino o un hotel" input. A dropdown will appear but the content is never loaded
5. see that by removing the `scrollable` attribute in the lightbox the content is loaded

A need the `scrollable` attribute in my case, because I need to make some inside elements scrollables

**Comment by dbarcosb** [comment]
Any update on this? Will [amp-list v2](https://github.com/ampproject/amphtml/issues/16507) tackle this issue? Thanks

**Comment by aghassemi** [comment]
Issue is unrelated to `amp-list` and more about scrollable lightbox, any fix needs @jridgewell's layers or something similar.
