### ISSUE TITLE
classes not removed by amp-font

### ISSUE THREAD

**Issue by ericfs** [ampproject/amphtml#13140]
## What's the issue?

All document text remain hidden because classes that should be removed by amp-font are not removed.

It's possible this is a misconfiguration on the publisher's part, but my naive inspection didn't find a problem.

## How do we reproduce the issue?

Go to: https://newatlas.com/radio-waves-vaporize-electronics/53134/?amp=true
None of the text in `<p>` tags is visible, but ads and images are visible.

## What browsers are affected?

Chrome 64.0.3282.119

## Which AMP version is affected?

1516833286380

**Comment by camelburrito** [comment]
cc @cvializ @aghassemi

**Comment by cvializ** [comment]
Hey thanks for reporting this! However I think it is a configuration error and not a bug.

I notice the font classes are on the `<body>` tag. [According to the docs ](https://www.ampproject.org/docs/reference/components/amp-font)

> These classes are toggled on the documentElement for standalone documents, and on body for documents without a documentElement i.e. inside a ShadowRoot

Since this document is standalone, the classes need to be on the html tag.

**Comment by ericfs** [comment]
Thanks for looking!
