### ISSUE TITLE
allow @supports and @-vendor-prefixes

### ISSUE THREAD

**Issue by Nemo64** [ampproject/amphtml#1315]
The [@supports](https://developer.mozilla.org/en/docs/Web/CSS/@supports) query should be added to the allowed @-rules for some nice progressive enhancement tricks.

**Comment by cramforce** [comment]
Definitely!
CC @Gregable, @powdercloud

**Comment by Gregable** [comment]
Will do. We should update the spec as well. It currently lists only `@media`, `@keyframes`, and `@font-face`.

**Comment by cramforce** [comment]
Changed the spec.

**Comment by cramforce** [comment]
@erwinmombay noticed we are lacking supports for a few vendor prefixes on the @-rules. E.g. `@-webkit-keyframes`. @erwinmombay Could you update the spec for that as well?

**Comment by Gregable** [comment]
For the @-webkit- stuff, please be specific here or in the spec and enumerate the @ rules you would like whitelisted in the validator. We don't have a mechanism to whitelist prefixes or anything like that for @ rules. It would be tricky to do since the css parser needs to know how to parse the inside of each rule (e.g. keyframes insides are parsed as more css rules whereas font-face insides are parsed as css declarations).

**Comment by Gregable** [comment]
@erwinmombay 's change is now live and we now validate `@-webkit-keyframes`, `@-moz-keyframes`, `@-o-keyframes`, `@supports` and the `<amp-user-notification>` tag.
