### ISSUE TITLE
FR: amp-bind style syntax for amp-access fields

### ISSUE THREAD

**Issue by cpapazian** [ampproject/amphtml#13341]
We are using amp-access templates pretty extensively to add secondary components or make minor, invisible changes to the page based on the user. For some of these types of changes, we're just changing a single attribute in the template based on the `amp-access` response, and the mustache templates seem like overkill. Would it be possible to use `amp-bind` or similar syntax for making updates based on `amp-access`? or perhaps merging (a subset of) the `amp-access` response into `amp-state`?

**Comment by choumx** [comment]
Thanks for filing this. We generally require user gestures to trigger amp-bind because the mutations can affect the entire page (rather than constrained to a single component like amp-list). I sympathize since using amp-mustache does seem rather heavyweight for a single attribute change. 

Let us know if this becomes functionality blocking for your use case.

**Comment by cpapazian** [comment]
Not a blocker, per se, but we've had some bugs related to these templates recently. 

We're tracking a bug right now with links ... we added some whitespace to the template for readability, but it seems like AMP is interpreting links with leading whitespace as relative links (the links in question should be absolute links)

We are fixing this on our side by stripping the whitespace in our markup, but having a better way to specify this logic (nested if's, not templated markup) would have avoided this issue.
