### ISSUE TITLE
Gulp: create a target to precompile all ".jison" files

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#1347]
This would remove the need for `compile-access-expr` target and will remove the artifact .js files from git history.

**Comment by adelinamart** [comment]
@dvoytenko is it still an issue? Thanks

**Comment by dvoytenko** [comment]
Yes

**Comment by aghassemi** [comment]
to @choumx for routing to infra

**Comment by choumx** [comment]
So far there are three such grammar files for amp-access, amp-animation and amp-bind.

**Comment by rsimha** [comment]
@dvoytenko @aghassemi @choumx To confirm what's involved here:

- Remove these files:
```
extensions/amp-animation/0.1/css-expr-impl.js
extensions/amp-access/0.1/access-expr-impl.js
extensions/amp-bind/0.1/bind-expr-impl.js
```
- Refactor `build-system/tasks/compile-expr.js` to process all extensions that have the need for `.jison` precompilation, instead of hard-coding the list of extensions that need it

Anything else?

@estherkim, is this something you'd have the time to work on?

**Comment by choumx** [comment]
Was just re-triaging old runtime issues and noticed this should be "tooling". Note that this is "only" a P3.
