### ISSUE TITLE
AMP image is not loading in firefox:54.0b9 (64-bit)

### ISSUE THREAD

**Issue by bizimunda** [ampproject/amphtml#13482]
**Please only file bugs/feature requests for AMP here.**

- If you have questions about how to use AMP or other general questions about AMP please ask them on Stack Overflow under the AMP HTML tag instead of filing an issue here: http://stackoverflow.com/questions/tagged/amp-html
- If you have questions/issues related to Google Search please ask them in Google's AMP forum instead of filing an issue here: https://goo.gl/utQ1KZ

## What's the issue?

Bug: image is not loading in firefox

## How do we reproduce the issue?

Here is the link: http://hochzeitsfotografffm.de/

## What browsers are affected?

Firefox: 54.0b9 (64-bit)

## Which AMP version is affected?

https://cdn.ampproject.org/v0.js

**Comment by aghassemi** [comment]
Hi @bizimunda 

The issue is that you are using `webp` images which Firefox does not support. Using `webp` is great but you would need a `fallback` for Firefox and other browsers that don't support `webp`.

Here is example of how to use `webp` with a `fallback`: https://www.ampproject.org/docs/reference/components/amp-img#example:-specifying-a-fallback-image 

Hope this resolves your issue.
