### ISSUE TITLE
as-you-go amp-form doesn't move to the next input when hitting 'enter' key

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/amphtml#13491]
The custom validation 'as-you-go' strategy is not moving the cursor to the next input even when validation passes.
Verifiable in this example (the 5th form from the top):
https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-form%2Fsource%2F

Expected behavior:
the cursor should be brought to the next input for uninterrupted data entry, should have the same behavior exhibited when other validation strategies are in use.

**Comment by cvializ** [comment]
I was able to reproduce. I'll investigate soon

**Comment by AndrewKGuan** [comment]
Thanks!  Just wondering if it is going to be ready soon?

**Comment by nainar** [comment]
Hi, 

Thank you for filing this issue! Unfortunately, the `as-you-go` strategy is meant only to aid in validation. 

Here is a quote from the component documentation:
The `as-you-go` reporting option allows your user to see validation messages as they're interacting with the input. For example, if the user types an invalid email address, the user will see the error right away.  Once they correct the value, the error goes away. - [Source](https://www.ampproject.org/docs/reference/components/amp-form)

This says nothing about cursor movement. This is working as intended. I would be hesitant about this as a feature due to accessibility considerations.

**Comment by AndrewKGuan** [comment]
Hi Nainar,
should I file an FR/bug for cursor movement?
