### ISSUE TITLE
Images embedded with amp-img are not shown in Safari on iOS

### ISSUE THREAD

**Issue by bizimunda** [ampproject/amphtml#13502]
## What's the issue?
Images are not shown

## How do we reproduce the issue?
http://www.hochzeitsfotografffm.de/ visit this website

## What browsers are affected?
Safari

## Which AMP version is affected?
latest version CDN

**Comment by cathyxz** [comment]
Hi @bizimunda, thanks for getting touch. Would you mind being a bit more specific as to what the issue is? I checked out your page, and it seems like all of your `<amp-img>` tags on the page are commented out. Also, I don't think the page you've included is valid amp. You need to include amp runtime script (` <script async src="https://cdn.ampproject.org/v0.js"></script>`), the amp boilerplate styles, and cannot have other javascript running. Please see the documentation on this [page](https://www.ampproject.org/docs/tutorials/create/basic_markup) for reference. You can also use the [amp validator](https://validator.ampproject.org/) to verify that your markup is valid amp.
