### ISSUE TITLE
Remove CDATA references from error messages

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#13572]
We have error messages like `The text (CDATA) inside tag 'style amp-custom' contains 'CSS !important', which is disallowed. (see https://www.ampproject.org/docs/reference/spec#stylesheets)`. 

Outside of HTML parser community and people who have spend too much time with XML nobody knowns what CDATA is. I think it'd be better if we simply removed the mentions of CDATA from the error messages.

**Comment by powdercloud** [comment]
There are three choices.
(1) Just edit the English text in validator-main.protoascii. This will change it for the Javascript validator, e.g. in the console and in validator.ampproject.org.
(2) Introduce new error codes and switch to them. This will trigger new translations, so it'll also be fixed for French / German / ... in the Search Console. But we use the error codes in a fair number of places and there are aggregations of errors. There are also records of previously processed documents with the old error codes since Search Console keeps history. So this touches more code than I like and creates a little churn. But it's the principled fix.
(3) Do nothing.
I started with (2) for about 20 minutes. But maybe (3) is the better choice. Or (1). What do you think, @cramforce ?

**Comment by cramforce** [comment]
I think (1) is the way to go for now.

**Comment by powdercloud** [comment]
This is done (and released). And btw I was wrong about (2), just fixing the English text triggers retranslations. Apparently our system improved since I last touched it consciously. :-)
