### ISSUE TITLE
Page-level background-audio only playing on desktop

### ISSUE THREAD

**Issue by matthewgcallahan** [ampproject/amphtml#13635]
## What's the issue?

Inserting background-audio on the `amp-story` tag of an amp story will play on desktop, but does not play on iOS mobile web.

## How do we reproduce the issue?

Visit [this story](https://www.washingtonpost.com/graphics/2018/national/amp-stories/fentanyl-the-deadly-drug-haunting-america/) on desktop. Audio plays automatically.

Visit [this story](https://www.washingtonpost.com/graphics/2018/national/amp-stories/fentanyl-the-deadly-drug-haunting-america/) on desktop. Click the unmute button. No audio plays. 

## What browsers are affected?

Noticed on iOS 

## Which AMP version is affected?

Amp stories extension

**Comment by gmajoulet** [comment]
Thanks for filing this!

It is not possible to autoplay audio or unmuted videos on mobile as it is blocked by most browsers. To provide a consistent experience across the platforms, all the media elements should be muted by default.

The bug here is that the story wide ``background-audio`` should not be playing unless you click the "unmute" sound icon in the top right corner.

**Comment by jshmllr** [comment]
It is possible to play background-audio if you map the transition event action intent of the user to the playback listener. Not sure how to accomplish this on the initial load <cover> of the experience but subsequent pages it can be accomplished.

**Comment by gmajoulet** [comment]
That would work for transitions initiated by a user action, but unfortunately would not work for auto-advance transitions, or first page load. To be consistent, we decided to always mute the story by default.
