### ISSUE TITLE
Traffic Source issue in GA

### ISSUE THREAD

**Issue by avinash-collegedekho** [ampproject/amphtml#13656]
Hi AMP Team, recently i started using amp cache url to In-link my amp content.. now i have two concern for this, which are:
1. Is it a legitimate thing in terms of  SEO?
2. when users click on those cached and visit those pages, GA put that traffic into referral instead organic traffic which increases bounce rate of that page and cut down Pages per session of my organic traffic.

you can check it here:
https://www.collegedekho.com/amp/colleges/iit-delhi
the tabs link i.e courses,placement, news etc are amp cached urls..

**Comment by davisshaver** [comment]
@aghassemi @avinash-collegedekho This is expected behavior. If for instance a user shares the cached AMP URL on social, we would expect a desktop user clicking the link to be forwarded to the desktop site.

One option might be setting up CloudFlare's Accelerated Mobile Links feature to enable this functionality at the edge. https://www.cloudflare.com/website-optimization/accelerated-mobile-links/

This behavior should also be anticipated to change in the behavior, [noting the announcement for URL change here](https://amphtml.wordpress.com/2018/01/09/improving-urls-for-amp-pages/amp/).

**Comment by rudygalfi** [comment]
@avinash-collegedekho While you are welcome to do this, I'd recommend linking to pages on your own site (either the AMP or the non-AMP) rather than the AMP Cache pages. (AMP caches are mainly designed for use by platforms linking to AMP contesting using an AMP viewer, rather than by the original publisher.).
