### ISSUE TITLE
Ability to hide unmute/mute button on Amp Story if video has no audio

### ISSUE THREAD

**Issue by matthewgcallahan** [ampproject/amphtml#13652]
## What's the issue?

Amp stories with videos that have no sound display an unmute icon which can be misleading to readers and make something appear broken, when in fact that's the preferred/default experience.

## How do we reproduce the issue?

Vist [this page](https://www.washingtonpost.com/graphics/2018/food/amp-stories/how-to-make-cold-brew-coffee/). Notice that the unmute button appears and you can try to unmute, but never hear any sound. 

## What browsers are affected?

All browsers

## Which AMP version is affected?

Amp stories

## Current workaround

We've discovered a workaround in the meantime for others who face this issue. 
```
div[class*="story-unmute"]{
	visibility: hidden;
	opacity: 0;
}
```

**Comment by calebcordry** [comment]
@newmuis I will need this functionality too for ads and could work on it. 
 
Do we want to expose a public API for showing/hiding this element? (similar Q for progress bar)  Or is using the existing CSS the preferred method?

**Comment by newmuis** [comment]
@matthewgcallahan There is a plan for this; we'll show an equalizer icon on videos containing sound, and only show the mute/unmute icon for stories where at least one page has sound.  We will also show hints that pop up informing the user of whether or not the page has sound.  This underwent user research studies and performed better than the idea of having the mute/unmute icon disappear and re-appear on a per-page basis.

The work for this is tracked in #11857, but depends on #11940, which may actually be relatively difficult to implement cross-browser.

@calebcordry The ads use case is different; since this is all internal to the runtime, the ads extension can message the story and have it update its system layer accordingly.

**Comment by calebcordry** [comment]
Got it thanks for the clarification!

**Comment by aghassemi** [comment]
@newmuis `noaudio` is now supported on `amp-video`, I assume there is work to be done on the Stories side to take advantage of this? (Someone on Slack was curious about this)

**Comment by newmuis** [comment]
We just need to update the [`updateAudioIcon`](https://github.com/ampproject/amphtml/blob/22a42fef96531292d126f07b058d024558b59435/extensions/amp-story/0.1/amp-story.js#L1540-1549) function to check the `noaudio` attribute.

There's no harm in starting to mark up videos with `noaudio` now.
