### ISSUE TITLE
amp-ima-video don't work when adblock is active

### ISSUE THREAD

**Issue by seomaz** [ampproject/amphtml#13660]
You can see this example: https://ampbyexample.com/components/amp-ima-video/ using chrome with adblock.

the video does not play, the normal situation would be to play the video without ads.

**Comment by shawnbuso** [comment]
Hey all, I may need a hand with this one - I'm having trouble replicating exactly in a debug environment because my plugin is being loaded from ads.localhost, so instead of the IMA library being blocked like in prod, the whole plugin gets blocked in dev. Is there a modification I can make to avoid loading the plugin from ads.localhost?

**Comment by shawnbuso** [comment]
Scratch that - uBlock Origin will let me configure it to allow localhost connections through but block other connections. Taking a look at this now.

**Comment by shawnbuso** [comment]
FYI I sent #13713 for review, which will fallback gracefully to content when adblock is being used.
