### ISSUE TITLE
amp-list should show loading indicator and placeholder during refetch

### ISSUE THREAD

**Issue by josh313** [ampproject/amphtml#13718]
When an amp-list refetches its data due to the src changing via amp-bind or the soon-to-be-implemented refresh action being triggered (#13717), the amp-list just shows the previous data until the new data is returned by the server. This can create a weird user experience in lots of cases, because the user taps some button which should change the data but the page seems to not react at all until the refetch is complete. I think it would be better to instead hide the previous data during the refetch and show the loading indicator and placeholder while it is loading to make it clear that the data is being refreshed. 

cc @choumx @aghassemi

**Comment by aghassemi** [comment]
Also needed for infinite scroll case: https://github.com/ampproject/amphtml/issues/13718 
/cc @cpapazian

**Comment by seomaz** [comment]
See my example https://www.cibercuba.com/actualidad clic on see more button

**Comment by josh313** [comment]
@aghassemi Are you saying that this change to show the loading indicator on refresh should be opt-in, or just that the other feature you mentioned to should be opt-in?

**Comment by aghassemi** [comment]
for design review, discuss:
1- attribute to turn loading+placeholder behaviour on (what should the default be).
2- do we need two attributes so loading and placeholder can be separated.

**Comment by aghassemi** [comment]
@josh313 Suggestion is to add a `reset-on-refresh` attribute and unless that attribute is set, this behaviour will not kick in.

**Comment by choumx** [comment]
Related: #12212 proposes a general approach with CSS.

**Comment by aghassemi** [comment]
@choumx This came up as an additional feature we can add in case someone does not want both `placeholder` and `loading` feature this feature provides.

CSS-only approach can mostly work to mimic the initial loading stage (e.g. placeholder + our default loading icon) which this feature provides with two caveats:
1- CSS would need to account for  showing and hiding of `placeholder` and content.
2- It can't do our loading icon since default loader is removed from the DOM after initial load, so a custom loading UI must be provided in this case.

@josh313 What is the UX for your immediate use-case? Does it need AMP's default loading UI?

**Comment by kul3r4** [comment]
@aghassemi ignore the previous comment, I understood that I need to use `reset-on-refresh`. I will also add it to the ABE sample
