### ISSUE TITLE
Disallow nested scrolling elements

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1377]
Enforced through validation. Seems like it would be a nice user experience guarantee.

**Comment by Gregable** [comment]
Can you provide a list of the scrolling elements you are aware of, or at least a couple examples.

**Comment by cramforce** [comment]
This is mostly CSS. `overflow:auto` and `overflow:scroll`.

This would be for #1356

**Comment by Nemo64** [comment]
Also `overflow-x: scroll` and `overflow-y: scroll`.

**Comment by dvoytenko** [comment]
Search for `overflow` in this spec file: https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md

**Comment by cramforce** [comment]
Ha, I missed it the other day :)

Did we implement it, though? It would be interesting to see if we can still make the change without breaking many docs.
CC @Gregable

**Comment by Gregable** [comment]
Those aren't implemented. We haven't had time to finish up the css work, so what's actually active are essentially a few blacklist regexps at the moment. `overflow` is not one of them.

**Comment by aghassemi** [comment]
Currently having author defined scrollable subviews (using overflow) results in buggy behaviour as this is not something the runtime code handles properly but that does not stop page authors to do it ( for example see https://github.com/ampproject/amphtml/pull/4081#issuecomment-234655415 ). IMO, we should get this in the validator soon to avoid setting the wrong expectations.

**Comment by shimonenator** [comment]
I've pointed it out in the aforementioned comments on #4081, but would like to elaborate that unlike a nested vertical scrolling container, horizontal scrolling is not a bad user experience. This is to contrast to the original scope of this issue as @rudygalfi has defined it.

Buggy layout for custom elements on horizontal scrolling can be fixed with minimal effort and without performance tolls.

**Comment by aghassemi** [comment]
Good point @shimonenator. If we decide to only disable vertical scrollables and allow horizontal (which seems reasonable) we have some work to do to bring layout scheduling to arbitrary sub-layers (such as finding all scrollable areas and attaching scroll handlers to detect user actions, etc..) or introduce wrappers such as `<amp-scrollable>`. https://github.com/ampproject/amphtml/issues/3434 would be a good start.

**Comment by shimonenator** [comment]
@aghassemi, that sounds reasonable. But may be then entirely disabling horizontal axis in $4081 should not be rushed out the door?

**Comment by aghassemi** [comment]
@shimonenator #4081 makes the lack of support for nested scrollables more obvious but the behaviour without it is also bad and against AMP principles. Without #4081, **all** resources inside a horizontally scrollable area will start loading after page load **regardless** of whether these resources are in the view or about to come to the view. There was no resource scheduling or pre-loading happening before #4081, it simply loaded everything, which isn't good (*see example below)

If this is not causing big production issues for you, I rather keep #4081 to prevent similar usages until we have a proper solution.

*To see the issue in action, disable [Dev Channel](https://cdn.ampproject.org/experiments.html) and visit https://amphtml-ae5fc.firebaseapp.com/examples.build/empty.amp.html, but do not scroll and keep your Network tab open. You will notice that after a while (about 8-9 seconds) all 10 image resources are loaded despite most of them not even being close to come to view port.

cc @dvoytenko

**Comment by shimonenator** [comment]
@aghassemi, I've actually thought that it was normal that after a delay (to allow clear path for highest priority content), 6-10 would load. The only part of it that I considered as a bug in my work was the fact that when you start scrolling, 6 and 7 don't preload in time before they get in the view.

You guys obviously have a better view into the usage of AMP across different publishers, whereas I can only assume that horizontal scrolling is not the most common issue at the moment. 

No, it certainly does not cause big production issues, but prevents a feature deployment. What worries me is if the only place where horizontal scrolling is allowed will be `<amp-carousel>`, the possibilities for horizontal scrolling will stay limited due to declarative nature of the tag. For example, one of the uses that we would like to employ is being able to switch from carousel view (where a little more than one element is visible, like in your example), to the full screen view, where only one element is in the view). When you switch between the views, the currently visible item in the carousel stays visible. This is possible with minimal CSS, however is not possible with `<amp-carousel>` + CSS or with `<amp-rousel>` + `<amp-lightbox>`. Since the only performance toll is coming from the layout and preloading, I've been hoping it would be possible to stall a blanket moratorium, and instead couple it together with the release of `<amp-scrollable>` instead, which would give a meaningful alternative within AMP principles.

**Comment by shimonenator** [comment]
In addition, I see that disabling horizontal scrolling was originally slated for v1, as per #1356

**Comment by adelinamart** [comment]
Is this still relevant?

**Comment by Gregable** [comment]
@rudygalfi @dvoytenko @cramforce 
I did a quick check and it looks like this would invalidate about 20% of docs. I presume this is not something that we want to do?

**Comment by Gregable** [comment]
I'm going to close this. Feel free to reopen if this is the incorrect conclusion.
