### ISSUE TITLE
Range-date-picker: "cannot read property 0 of 0; returning null. " warning

### ISSUE THREAD

**Issue by Jade05** [ampproject/amphtml#13919]
Description:

As shown below, there are several warnings when choosing the first date on range-date-picker.
![555](https://user-images.githubusercontent.com/5029635/37262409-f70663fc-25dd-11e8-98a4-3bebab548f6e.png)

In fact, they are caused by the below code snippet. We cann't get the date value when we choose the first date on range-date-picker(bacause date picker doesn't return this value).  
![666](https://user-images.githubusercontent.com/5029635/37262534-94304d82-25de-11e8-9a3e-b5509b7a0dab.png)

how can we get the first clicking value? would you have a good solution？Thank you.

**Comment by cvializ** [comment]
This happens when bind encounters undefined values in expressions, and it isn't an issue with the date picker. It's only a warning so it is not a problem. I'll close this unless it is causing issues.

Now there are explicit `event.start.date` and `event.end.date` properties so you don't have to use the list notation.
