### ISSUE TITLE
Need to Whitelist in Validator

### ISSUE THREAD

**Issue by ayumihamsaki** [ampproject/amphtml#13928]
Hi,

Should this meta-tag should be whitelisted in the Validator Tool:

```
<meta http-equiv="x-dns-prefetch-control" content="on">
and
<meta http-equiv="x-dns-prefetch-control" content="off">
```

If we can use the rel-dns-prefetch link tags now, we should be add to use the above as well.

I attach a screenshot to show more of what I mean:

![untitled](https://user-images.githubusercontent.com/17784082/37298930-bb529286-2619-11e8-875b-72607bec5d3d.png)

**Comment by honeybadgerdontcare** [comment]
@aghassemi thoughts?

**Comment by aghassemi** [comment]
@honeybadgerdontcare after some research and chat with @cramforce, I believe we can not allow this (privacy preserving nature of prerendering) until we make sure cache actually removes it (same way it does with `<link rel="preconnect">` by changing it to `<link disabled-rel="preconnect">`). After that change is in, it should be alright to allow it.

(Currently I can not test to see what cache does with it since it is not valid)

**Comment by honeybadgerdontcare** [comment]
Currently the cache would [allow this link](https://github.com/ampproject/amphtml/blob/master/spec/amp-cache-modifications.md#remove-non-whitelisted-meta-tags) and not remove it. I have created issue #13980 to track changing the cache behavior.

**Comment by ayumihamsaki** [comment]
Sorry can I ask an extra thing, related to this issue. I was reading the comments and following the links and saw that all resource hints are removed - see link below:

[Remove <link> resource hints](https://github.com/ampproject/amphtml/blob/master/spec/amp-cache-modifications.md#remove-link-resource-hints)

I thought support for pre-connect has been added to amp-html now see old issue: [Issue: 12483](https://github.com/ampproject/amphtml/issues/12483)

**Comment by honeybadgerdontcare** [comment]
This is coming to production in one to two weeks.
