### ISSUE TITLE
amp-analytics: Difficult to have timer trigger fire once reliably

### ISSUE THREAD

**Issue by dougscher** [ampproject/amphtml#14234]
The following will sometimes send 2 events after a page refresh

```javascript
triggers: {
    performanceTimer: {
        on: 'timer',
        timerSpec: { interval: 10, maxTimerLength: 10, immediate: false },
        request: 'performanceEvent'
    }
}
```
Setting maxTimerLength: 9.9999999 seems to correct the problem.
A better usage may be to set maxTimerLength: 0 to indicate a one shot timer, or something like this.

**Comment by zhouyx** [comment]
@dougscher Thanks for filing the issue.
I've tested and was able to reproduce every time. 
This is kind of expected, because amp-analytics is trying to send one last request when `maxTimerLength` has been reached. So if you think about a config like this
```
triggers: {
    performanceTimer: {
        on: 'timer',
        timerSpec: { interval: 10, maxTimerLength: 15, immediate: false },
        request: 'performanceEvent'
    }
}
```
that kind of makes sense. 

However in your case, since `interval` and `maxTimerLength` is the same value, 2 requests will be sent out. One due to the 10sec `interval`, and other other inform you that the `maxTimerLength` has been reached. 

As you mentioned `maxTimerLength=9.99` would fix the issue. That's because only one single request when `maxTimerLength` has been reached is sent out in that case. 

I'll update our documentation to indicate that one additional request will be sent at `maxTimerLength` time.

**Comment by zhouyx** [comment]
Regarding your request to add support to send timer event at specified time once. I've created #16910

**Comment by dougscher** [comment]
A better fix may be to add an attribute like  once: true.

Thanks,
Doug


Doug Scher | Lead Developer
p: 561-361-8486 | c: 561-445-9659
doug@mathereconomics.com

mather : 
1215 Hightower Trail | Building A, Suite 100 | Atlanta, GA  30350
770-993-4111 | www.mathereconomics.com 
Named for the third consecutive year to the Inc. 500/5000 list of the fastest growing private companies in the U.S.

**Comment by dougscher** [comment]
Maybe a new timer invocation in the same context should cancel the previous on.

Thanks,
Doug


Doug Scher | Lead Developer
p: 561-361-8486 | c: 561-445-9659
doug@mathereconomics.com

mather : 
1215 Hightower Trail | Building A, Suite 100 | Atlanta, GA  30350
770-993-4111 | www.mathereconomics.com 
Named for the third consecutive year to the Inc. 500/5000 list of the fastest growing private companies in the U.S.
