### ISSUE TITLE
Leaner AMP: Stop the bleeding (feeding?)

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#14394]
Part of #14392.

- Provide feedback of binary size increase to engineers as part of workflow
- Cap the size of v0.js to prevent continued growth

**Comment by choumx** [comment]
Proposal: Integrate [bundlesize](https://github.com/siddharthkp/bundlesize) into our CI with limits on `amp.js` for PR builds and `v0.js` for push builds.

/cc @rsimha @cramforce

**Comment by rsimha** [comment]
The fact that this shows up as a new check makes me happy!

<img width="785" alt="" src="https://user-images.githubusercontent.com/26553114/38274937-4dfe80f4-375e-11e8-8145-f71e4e91692f.png">

**Comment by cramforce** [comment]
@choumx We should do this. However, death by a thousand cuts problems aren't fixed by this. It can only catch major shifts. We will need to approve every small increase.

**Comment by choumx** [comment]
The `bundlesize` tool actually only supports checking against an absolute max size, not incremental changes.

**Comment by cramforce** [comment]
The problem with "death of a thousand cuts" is, that such checks fail the 1000th cut, while each single one was an equal problem. Or do they have a clever way around that?

**Comment by choumx** [comment]
Ah, I interpreted that differently. No, we'd need to increase the `maxSize` in that case. 

I'd first set `maxSize` to the current size of `v0.js` and see how painful it is. I suspect that most PRs that do trigger this limit are able to workaround, and we can encourage finding offsets for those that can't.

Hopefully this will eventually resemble "cap-and-trade" and not "debt ceilings and government shutdown". 😄

**Comment by cramforce** [comment]
I've worked on a program with such a limit and it was definitely "debt
ceilings and government shutdown". The only way out is if we literally say:
0 tolerance policy. But then we must be willing to block launches on it.

**Comment by choumx** [comment]
Fair enough. I do think that (1) we need to be aggressive to have a hope of completing the KR, and (2) most AMP engs outside of the runtime team should only have incidental impact on code in `v0.js`.

I say let's try it and we can relax or remove the limit if it becomes a serious problem.

**Comment by rsimha** [comment]
Reopening this because we've seen a lot of noise on `master` due to the fact that we run `bundlesize` on unminified code during PR checks, and on minified code during push builds.

<details><summary>Commits that have bumped up the size cap</summary>
6827fac5d ✅ Bump up bundle size again (#14984)

diff --git a/gulpfile.js b/gulpfile.js
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -826,1 +826,1 @@
-  const size = compiled ? '77.02KB' : '336.66KB';
+  const size = compiled ? '77.05KB' : '336.66KB';
3fd30b062 ✅ Increase expected minified bundle size (#14976)

diff --git a/gulpfile.js b/gulpfile.js
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -826,1 +826,1 @@
-  const size = compiled ? '76.96KB' : '336.66KB';
+  const size = compiled ? '77.02KB' : '336.66KB';
19187a747 🏗 Bump the compiled bundle size by 0.01KB to fix build (#14907)

diff --git a/gulpfile.js b/gulpfile.js
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -826,1 +826,1 @@
-  const size = compiled ? '76.95KB' : '336.66KB';
+  const size = compiled ? '76.96KB' : '336.66KB';
6ea8ef7c4 Refactor action whitelisting and apply to amp-story (#14628)

diff --git a/gulpfile.js b/gulpfile.js
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -825,1 +825,1 @@
-  const size = compiled ? '76.85KB' : '336.10KB';
+  const size = compiled ? '76.95KB' : '336.66KB';
43243f932 Allow tap targets to trigger inside accordion header (#14717)

diff --git a/gulpfile.js b/gulpfile.js
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -825,1 +825,1 @@
-  const size = compiled ? '76.85KB' : '336.00KB';
+  const size = compiled ? '76.85KB' : '336.10KB';
333a47cb3 Static HTML Template helper (#14623)

diff --git a/gulpfile.js b/gulpfile.js
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -823,1 +823,1 @@
-  const size = compiled ? '76.79KB' : '334.55KB';
+  const size = compiled ? '76.85KB' : '336.00KB';
7461ac7c4 Copy amp-story 1.0 back to 0.1 (#14626)

diff --git a/gulpfile.js b/gulpfile.js
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -823,1 +823,1 @@
-  const size = compiled ? '76.79KB' : '334.46KB';
+  const size = compiled ? '76.79KB' : '334.55KB';
e4350f9ab Fix amp-bind tests and elementByTag() (#14603)

diff --git a/gulpfile.js b/gulpfile.js
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -811,1 +811,1 @@
-  const size = compiled ? '76.81KB' : '334.41KB';
+  const size = compiled ? '76.79KB' : '334.46KB';
f88bf6cd6 Consent API introduce UNKNOWN & IGNORED state (#14508)

diff --git a/gulpfile.js b/gulpfile.js
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -811,1 +811,1 @@
-  const size = compiled ? '76.81KB' : '334.39KB';
+  const size = compiled ? '76.81KB' : '334.41KB';
82fd3a165 Add support for cache:getClientId (#14450)

diff --git a/gulpfile.js b/gulpfile.js
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -811,1 +811,1 @@
-  const size = compiled ? '76.5KB' : '333.28KB';
+  const size = compiled ? '76.81KB' : '334.39KB';
828392660 Add 0.01KB buffer to current size cap. (#14511)

diff --git a/gulpfile.js b/gulpfile.js
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -811,1 +811,1 @@
-  const size = compiled ? '76.49KB' : '333.27KB';
+  const size = compiled ? '76.5KB' : '333.28KB';
87cbad7d1 ✨ Add support for custom tabs. (#14224)

diff --git a/gulpfile.js b/gulpfile.js
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -811,1 +811,1 @@
-  const size = compiled ? '76.2kB' : '332.6kB';
+  const size = compiled ? '76.49KB' : '333.27KB';
c2d580f0c ✨ amp-geo pre-release integration (#14464)

diff --git a/gulpfile.js b/gulpfile.js
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -810,1 +811,1 @@
-  const size = compiled ? '76.1kB' : '332.3kB';
+  const size = compiled ? '76.2kB' : '332.6kB';
75cdb4a7a Bundlesize follow-up (#14459)

diff --git a/gulpfile.js b/gulpfile.js
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -809,1 +809,1 @@
-  const size = compiled ? '75.1kB' : '332.3kB';
+  const size = compiled ? '76.1kB' : '332.3kB';
3abc40172 Integrate `bundlesize` and cap main binary size (#14405)

diff --git a/gulpfile.js b/gulpfile.js
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -804,0 +809,1 @@
+  const size = compiled ? '75.1kB' : '332.3kB';
</p>
</details>
