### ISSUE TITLE
AMP Experiment Takes a While to "Switch On"

### ISSUE THREAD

**Issue by akabiru** [ampproject/amphtml#14487]
## What's the issue?
Heya AMP team,

We've noticed that amp x intermittently fails to "switch on" -  it takes a couple of refreshes to get it working.

I've been able to verify the above from the following:

- "amp-x-experiment-name='the-variant'" is **not always** set in the body tag 
- ~AMP.isExperimentOn() returns false~

Feedback on this highly appreciated. 🙂

## How do we reproduce the issue?

N/A (In development, requires authorisation), sorry.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

AMP - https://cdn.ampproject.org/v0.js
AMP Experiment - https://cdn.ampproject.org/v0/amp-experiment-0.1.js

### Knowledge share on SO
https://stackoverflow.com/questions/49672039/amp-experiment-fails-to-switch-on

**Comment by choumx** [comment]
Ah, I think there's some confusion due to a naming collision. `AMP.isExperimentOn` is for internal features listed [here](https://cdn.ampproject.org/experiments.html) and is unrelated to the `amp-experiment` extension.

**Comment by akabiru** [comment]
@choumx thanks for the response. `AMP.isExperimentOn()` was as an example; my bad. Are you able to comment on why AMP X does not always switch on on first load?

**Comment by choumx** [comment]
There might be a small latency after page load for the `amp-experiment` extension to load etc. 

Do you have a sample page that is exhibiting this behavior?

**Comment by akabiru** [comment]
Thanks for reopening the issue @choumx. I'm afraid I unable to share the asset here as it's still in development/requires authorisation.

I've made a quick pen here https://output.jsbin.com/kivuxid for what we're looking at.

So far I'm ruling out the following:
- does the number of amp components being loaded affect this in some way (we have 6 amp scripts)
- Toggling to a slow 3G connection makes amp-x to fail - guess due to the latency issue

**Comment by choumx** [comment]
Thanks for the jsbin. I can't reproduce `amp-x-foo-bar-experiment` not being set on the `<body>` even with network throttling, and look at the source code I don't see a timeout. As long as the fetch of the `amp-experiment` extension itself completes, this should work.

**Comment by akabiru** [comment]
hmm, no worries. I'll see if there's any other way I can reproduce the issue. Cheers! 👍

**Comment by choumx** [comment]
Thanks and good luck!

**Comment by alex-magana** [comment]
_Cross-sharing this from slack._

Hello
I’m reaching out to provide another sample amp document for use in resolving this issue,as raised by Austin.

Since the actual sample amp document requires credentials, that we aren’t able to share, to access, I have copied the raw html on the amp document, returned by accessing the link in the steps below.

The validator shall report errors for this webpage because of the inline `style`
clauses found in the raw html.

Please use the steps below to view the reported issue and advise on how we should proceed to have the issue resolved.

Steps to reproduce
1.On a new tab, on chrome, open developer tools and toggle device toolbar.
2.Select Mobile L - 425px
2.Go to https://a-referrer.000webhostapp.com/amp-experiment/indonesia.html

The steps outlined above, return a page with a working amp experiment, when carried out in an incognito window.

Below are screen grabs for the page above as seen on a normal window, incognito window and iPhone 6s safari respectively.

`normal window - chrome`
![normal_window](https://user-images.githubusercontent.com/20963836/39199421-18145cf8-47f2-11e8-906f-3c84c7e38950.png)

`incognito window - chrome`
<img width="1677" alt="incognito_window" src="https://user-images.githubusercontent.com/20963836/39199476-340fdfe0-47f2-11e8-95c4-384f411fcf8c.png">

`iPhone 6 - safari`
<img width="375" alt="iphone 6s safari 1" src="https://user-images.githubusercontent.com/20963836/39199520-56c99d96-47f2-11e8-8206-2cfe70033f76.png">

Thank you.

**Comment by cramforce** [comment]
@lannka Did you port the fixes for the service registration race that @jpettitt debugged?

**Comment by lannka** [comment]
#16531 address that

**Comment by briankabiro** [comment]
Thanks all for the help! Happy to report back that the experiment is working correctly on our sites. 🎉
