### ISSUE TITLE
AMP Story: progress bar "skips" two pages at the same time

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#14635]
## How do we reproduce the issue?

- https://www.washingtonpost.com/graphics/2018/national/amp-stories/the-5-biggest-political-headlines-facebook-and-paul-ryan/ (on mobile device or mobile emulator)
- tap through a few pages, until a video of a woman in a red jacket appears
- tap on the right hand side of the screen

Actual:

- the progress bar shows two pages being "advanced" simultaneously (also see [video](https://photos.app.goo.gl/fQViSkCGPlYJenuP2))

![screen shot 2018-04-16 at 2 12 43 pm](https://user-images.githubusercontent.com/51244/38811013-49d12b72-4180-11e8-9b4a-1c0bcf7e5084.png)

Expected:

- the progress bar shows one page being skipped

## What browsers are affected?

Reproduces on Chrome Desktop 65.0.3325.181 (using mobile emulation) and Chrome Mobile.

## Which AMP version is affected?

AMP version: 1523662348051
dev-channel: either on or off

/cc @newmuis

**Comment by newmuis** [comment]
This is technically not a bug in the code.  The issue is that when transitioning from auto-advance pages to manual-advance pages (or vice versa), this appears because the auto-advance page appears to have 0% progress in its initial state, whereas the manual-advance page appears to have 100% progress in its initial state.  As a result, when going back from a manual-advance page to an auto-advance page, the manual-advance page and the auto-advance page reset to 0%.

/cc @spacedino @hongwei1990

**Comment by spacedino** [comment]
Did we figure this out? 

(Is there a way to have an override / reset / rule when switching in and out? Ex: If auto > user clicks > reset to 100% / 50% / wait 1 extra second...?)

**Comment by newmuis** [comment]
We can do any arbitrary ux here, we just need to spec out what we want 🙂

**Comment by hongwei1990** [comment]
Based on what we discussed in the meeting this morning. Let's try to cut the width animation for the "previous" page progress bar. Making it instantly fill to 100% white, or 0% white (by changing the opacity).

**Comment by newmuis** [comment]
Thanks @hongwei1990!

We should apply an `active` CSS class to the progress bar segment for the currently-active page (which should get updated to the new page upon navigation), and only apply the `transition` CSS property to the `active` segment.
