### ISSUE TITLE
Getting lots of travis errors due to changes to the test runner, unclear how to proceed

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#14636]
I am getting a lot of [travis errors](https://travis-ci.org/ampproject/amphtml/jobs/366290414) on my [PR](https://github.com/ampproject/amphtml/pull/14563)

These errors appear to maybe be related to: https://github.com/ampproject/amphtml/issues/14406

I have tried rerunning a couple times now, and see the same thing. Unsure how I should proceed with these errors.

**Comment by rsimha** [comment]
@bradfrizzell Your build didn't fail due to the console errors (they're printed so test owners can clean them up, and don't fail tests). The build failed due to some tests timing out on Safari: https://travis-ci.org/ampproject/amphtml/jobs/366290414#L698-L699 Unfortunately, short of rewriting all the integration tests, the only way past this is to re-run your tests.

If you sync to `master` and run your tests, you'll notice that the console errors are now collapsed by default.
