### ISSUE TITLE
Add support for Vimeo

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#1471]
Currently it's only possible show Vimeo video using amp-iframe tag. 
Would be better to have a proper Vimeo tag.

**Comment by adewale** [comment]
This would be the equivalent of amp-youtube: https://github.com/ampproject/amphtml/blob/master/extensions/amp-youtube/amp-youtube.md

The syntax should be something like `<amp-vimeo data-videoid="140261017"
    layout="responsive"
    width="500" height="281"></amp-vimeo>`

We should also support all the options listed here: https://developer.vimeo.com/player/embedding since it only involves changing the parameters to the src URL. We don't currently do the same thing for YouTube so this will require some investigation.

**Comment by johnnyshankman** [comment]
Just popping in to let you know you can use an amp-iframe to successfully embed Vimeo videos.

**Comment by mkhatib** [comment]
I sent out a PR to add `amp-vimeo`. However I haven't addressed passing all the options listed in the documentation. Mainly because I have an open PR to pass `data-param-*` to the `amp-iframe.src`. I am wondering if we should be implementing `amp-vimeo` extra options similarly.

What do you folks think?

**Comment by cramforce** [comment]
@mkhatib For the 1st class components we use `data-`. `data-param-` is a thing for generic iframes.

**Comment by mkhatib** [comment]
Sounds good. Let me know if I should update the pull request with that.
