### ISSUE TITLE
amp-facebook element disappears when clicking on the post author avatar

### ISSUE THREAD

**Issue by htrex** [ampproject/amphtml#14722]
## What's the issue?
amp-facebook element disappears when clicking on the post author avatar

## How do we reproduce the issue?
1. Go to https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-facebook%2Fsource%2F
2. Click on the Mark Zuckenberg face

## What browsers are affected?
All

## Which AMP version is affected?
Version 1524089272632

**Comment by cathyxz** [comment]
Unfortunately I think this is a function of how Facebook's embeds work, not unique to the `<amp-facebook>` component, so there isn't anything we can do about this here, since `<amp-facebook>` is essentially a wrapper around the facebook embed iframe. 

You can see the same behavior on Facebook's developer documentation example here: https://developers.facebook.com/docs/plugins/embedded-posts/
