### ISSUE TITLE
FAN on AMP

### ISSUE THREAD

**Issue by jehan96** [ampproject/amphtml#14769]
hi there
quick question

i am searching on how to monetize my blog with FAN..
i know that normal blog can use FAN, but does AMP support it?
while searchin
this link brought me here
https://developers.facebook.com/docs/instant-articles/other-formats#instant-articles-to-amp

but i don't found FAN supported in here
https://www.ampproject.org/docs/reference/components/amp-ad#supported-ad-networks

can someone clarify?

**Comment by lannka** [comment]
@jehan96 FAN is not supported in AMP at the moment. What you probably can do is to seek help from FAN team, raise the issue that the instant article to AMP conversion tool is incomplete because FAN is not available in AMP.

AMP is an open source project that any 3rd party vendors are welcome to integrate.
