### ISSUE TITLE
FR: Math.floor() for amp-analytics number values.

### ISSUE THREAD

**Issue by johnteee** [ampproject/amphtml#14821]
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-video-analytics.md

It's wonderful to use amp-analytics on amp-video
However the `currentTime`variable seems not a rounded value...
Is it possible to add something like `floor()` in `amp-bind`?

for example:

Current:
```javascript
"requests": {
  "event": "https://pub.com/tracking?progress=${currentTime}"
}
```

Expected:
```javascript
"requests": {
  "event": "https://pub.com/tracking?progress=${floor(currentTime)}"
}
```

Thanks a lot :D

**Comment by abazeed** [comment]
Values of `currentTime`, `playedTotal`, and `duration` should be rounded if passed as an `eventValue`.
Since `eventValue` accepts only integer values, you have to:
- round any passed values to it by default.
- or make it accepts non-integer values.
- or support Math functions in `amp-analytics` as @johnteee suggested.

**Comment by ericlindley-g** [comment]
/to @aghassemi for feedback and /cc @choumx w/r/t amp-bind
