### ISSUE TITLE
Intent-To-Implement : Analytics support for configuration rewriter

### ISSUE THREAD

**Issue by zikas** [ampproject/amphtml#14822]
##  Objective

We'd like to be able to dynamically rewrite provided configuration. This is very similar to remote-config feature but additionally includes user-provided configuration in the request. 

For example:
1. Configuration in vendors.js specifies **configRewriter** property with a server url.
1. Configuration on page gets posted to the specified url.
1. Response contains a configuration that must be used. Configuration on a page is distracted.

## Overview
**vendors.js**
```javascript
export const ANALYTICS_CONFIG = {
  'vendor': {
    'configRewriter': {
      'url': 'https://www.vendor-host.com/amp-config-rewriter',
      'defaults': {
        'requests': {
          'host': 'https://www.vendor-host.com'
        }
      }
    }
  }
}
```
**my-page.html**
```javascript
<amp-analytics type="vendor" id="vendor">
    <script type="application/json">
    {
      "vars": {
        "config": "CONFIG_1"
      },
      "triggers": {
        "on": "visibility"
      }
    }
  </script>
</amp-analytics>
```

On start AMP will send inlined configuration  
```
{"vars": {"config": "CONFIG_1"}, "triggers": {"on": "visibility"}}
``` 
to `https://www.vendor-host.com/amp-config-rewriter` endpoint.

**Config Rewriter response**
```javascript
 {
  'requests': {
    'pageview': '${host}/pageview?cid=${clientId}',
  },
  'triggers': {
    'on': 'visible',
    'request': 'pageview',
    'vars': {
       'clientId': '${clientId(config-1-cookie-name)}',
    }
  }
}
```
The response will be used as the final AMP configuration.

## Optimization
To optimize amount of data we include in the response, **configRewriter** has **defaults** section. 
Definition from this section will be merged with final AMP configuration retrieved from the rewriter. In the example *host* is defined in vendors.js but could be referred by the generated confg.

The merging strategy will looks like this:
```
finalConfig = 
  Merge(
    Rewrite(
      Merge(vendorConfig - vendorConfig.configRewriter.defaults, remoteConfig, inlineConfig)), 
    vendorConfig.configRewriter.defaults);
```

**Comment by lannka** [comment]
As talked offline, this is a good enhancement to the existing remote config feature, which can only include simple data in the request.

One question, how is the 'requests' config in the vendors.js used?
```
    'requests': {
      'host': 'https://www.vendor-host.com'
    }
```

**Comment by lannka** [comment]
> Having request in the vendors.js would help saving a bandwidth.

I thought vendor config is also going to be sent to server?
```
merged config = vendor config + inlined config + remote config
```
In this case, the config rewrite will be the final step, which takes the merged config as input. Or you are thinking other way?

/cc @btownsend

**Comment by zikas** [comment]
From the efficiency standpoint there' not a lot of value in sending vendor config (as it's static and doesn't change). I was thinking that
```
final config = vendor config + rewrite_config (inlined config + remote config)
```

**Comment by lannka** [comment]
split off inline config with vendor config will break the current paradigm. it also might bring in some more complexity to the feature itself (you need to explain what will be rewritten and what will not). just want to see how much bandwidth we are going to save, is it worth it? 

/cc @rudygalfi

**Comment by zikas** [comment]
After offline discussion I have updated the original proposal with "defaults" section in configRewriter definition. 
Could you please take another look.

**Comment by lannka** [comment]
I'm also thinking if we should deprecate the remote config, given
1. config-rewriter provides a superset of feature. only feature wise difference is the HTTP request is a POST not a GET, but we might also work around this if we want. 
2. having 2 ways to get config remotely is a bit confusing from product's stand of point.
3. we can migrate major vendors using remote config to config-rewriter, so that we can give them type names in vendors.js. Then users get the benefit of put "type=googletagmanager" instead of "config=https://googletagmanager.com/balablala?cid=12345".

Mostly it should not affect the feature here, except that if we prefer config-rewriter to remote config, then we should dis-allow using both.

**Comment by zikas** [comment]
I'm not sure that config-rewriter will provide a superset of features.

For example the following use cases will be affected by the deprecation.
* Customer already has both, GTM AMP configuration and inlined configuration with extra triggers.
Unless GTM starts merging inlined config with generated config on server, page tagging will change (user expects union of GTM tags and inlined tags, only GTM tags will be available)

* If customer provides a remote configuration (fetched from a Customer server) that needs to be post-processed by a vendor (Vendor server).

**Comment by zikas** [comment]
* Another complication is we'll need to stick with remote-config attribute for configRewriter as customer migration would mean retagging.

**Comment by lannka** [comment]
> Customer already has both, GTM AMP configuration and inlined configuration with extra triggers.
Unless GTM starts merging inlined config with generated config on server, page tagging will change (user expects union of GTM tags and inlined tags, only GTM tags will be available)

Yep, work for vendor server. 

> If customer provides a remote configuration (fetched from a Customer server) that needs to be post-processed by a vendor (Vendor server).

They cannot do it with GTM or other tag manager now in anyway, since we only allow them get remote config from one place. Do you see this can be a feature for your case?

> Another complication is we'll need to stick with remote-config attribute for configRewriter as customer migration would mean retagging.

Not necessary. For config-rewriter, we will go with what you proposed. We will still support remote-config before all people moving away from it into config-rewriter. It certainly can take indefinite time, but we will remove the documentation of remote-config once config-rewriter is out.

**Comment by rudygalfi** [comment]
I think this will work and it seems like a pretty good way to address a complicated set of requirements. Just to confirm: `configRewriter` is something you can include both in vendors.js but also in the direct markup for amp-analytics? That is, a publisher could use the same pattern for their own proprietary, non-vendor analytics?

My feedback is to really ensure the merging logic can be communicated clearly. Consider dropping merge sources like the vendor.js static config if it'll just complicate things. 

Also, on the topic of deprecating remote config, is there something that stops this from being patterned off of remote config. IIRC, I think remote config gets highest precedence, so I assume it's that we want the precedence to flow in a different direction. I'm just wondering if this could be achieved by having a toggle on the precedence direction rather than introducing new concepts.

**Comment by lannka** [comment]
This is done.
