### ISSUE TITLE
amp-carousel with src=myJson

### ISSUE THREAD

**Issue by nikoviedo** [ampproject/amphtml#14832]
We need a dynamic carousel. Amp-list into amp-carousel doesn't work :/

**Comment by danielrozenberg** [comment]
Hi @nikoviedo, can you please elaborate on what you mean? Can you provide a simple example of source code that doesn't work as you expect and explain what you want this code to do?

**Comment by danielrozenberg** [comment]
The way these two components work is by design, so GitHub is not the best forum to ask this type of questions. It might be worth seeking help either on [StackOverflow](http://stackoverflow.com/questions/tagged/amp-html) with the tag #amp-html, or try our [Slack channel](https://docs.google.com/a/google.com/forms/d/e/1FAIpQLSd83J2IZA6cdR6jPwABGsJE8YL4pkypAbKMGgUZZriU7Qu6Tg/viewform)
