### ISSUE TITLE
amp-social-share[type="line"] occurs error

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#15082]
To whom it may concern:

I try to implement amp-social-share[type="line"]  to my AMP page and it occurs error whatever I set **data-param-url** / **data-param-url** or not.

Sample code:
```
<amp-social-share 
    type="line"
    class="social-share-line"
    width="24"
    height="24"
    data-vars-event-label="social-share-line">
</amp-social-share>
```

- [Document which I referenced](https://github.com/ampproject/amphtml/blob/master/extensions/amp-social-share/amp-social-share.md#pre-configured-providers)
- [Demo page](https://blog.lalacube.com/mei/yahoo_auction_item_amp.php?merchandiseId=100398791795)

Do I need to provide attribute  **data-share-endpoint** ?

Thanks for replying.

Paul

**Comment by cathyxz** [comment]
You should not need to since it has already been configured in https://github.com/ampproject/amphtml/pull/14687. It seems to be fine in this minimal example: https://codepen.io/cathyxz/pen/BxdgpE as I can't reproduce any error. 

Since #14687 was a relatively recent change, this code is in canary but not in production. You will be able to use it if you're opted in to the dev channel only. It should release to production in approximately a week.

**Comment by meistudioli** [comment]
Hi, @cathyxz:

You can try it on [playground](https://ampbyexample.com/playground/), and still occurs error in devTool.

**Comment by cathyxz** [comment]
I know. What I mean is to say that this feature isn't launched yet. =) It's in canary, which you can opt in via the Dev Channel (you can turn on dev channel [here](https://cdn.ampproject.org/experiments.html) ), but it won't arrive in production until a week later.

**Comment by meistudioli** [comment]
Got it. Thanks a lot.
