### ISSUE TITLE
[Master Feature] Ability to implement "flying carpet" from within AMPHTML ads

### ISSUE THREAD

**Issue by lexandera** [ampproject/amphtml#15216]
We get quite a few requests for "flying carpet effect" ads from our publisher clients. We suggested implementing the amp-fx-flying-carpet around the ad slot, but this has two major downsides:
* It requires involvement from another team which does web site development and is separate from the client's ads team. Times quoted for the requested changes can be several months.
* All ads served into such slots must then be close to full screen size since if a 300x250 ad is served into a flying carpet, it will only be visible for a short time when the "window" reaches the center of the page, but otherwise it will just show empty space around the ad.

Because of this we would like to be able to achieve the same effect from within the ad itself.

We see two possible approaches:
* A pre-packaged solution which automatically creates the background layer, aligns it with the ad viewport, and keeps it in place during scrolling.
* A DIY approach using the combination of amp-position-observer for keeping the background layer in place, and a sizing solution that would allow us to create a background layer of exactly the same height as the device viewport. Currently the sizing part is what's missing since using "height: 100vh" for the background layer matches the height of the ad's iframe viewport instead of the device viewport height, and matching the height is important in order to be able to keep the background stationary across different device sizes and also to avoid bands of empty space at the top and bottom (the second point applies to both approaches).

Here's an example of the format that we're trying to replicate in AMP (scroll the page inside the device):
http://sandbox.celtra.com/preview/89bde6a9#deviceType=Phone

**Comment by lannka** [comment]
Thanks @lexandera for bringing this up. The current flying carpet was implemented for publisher, and we do need a solution for ad networks.

To make the problem clear: how do you plan to use one background image for all different viewport sizes?

**Comment by lexandera** [comment]
@lannka The example uses just a single image as the back layer, but in reality it can be any kind of responsive html (as can the front layer).

Typically the background would be a div set to 100%x100% with a bg image and "background-size: cover" set in css. Above that (but still in the fixed background layer) other elements are added that shouldn't be cropped together with the background image, and they're anchored to top/bottom and sized in % to take up less/more space, depending on the size of the device. As long as the size of the device viewport can be matched, this usually nicely fills the background top to bottom.

**Comment by lannka** [comment]
The screen width/height is currently available via `window.context.initialIntersection.rootBounds` .

To do scroll bound animation in iframe, you will need our position change API, which is right now behind a feature flag. /cc @zhouyx

**Comment by lexandera** [comment]
@lannka The `window.context` is for JS based/legacy ads, right? Making our existing ads of this type work with AMP pages would also be great; but the main point of the original request was to bring the same kind of functionality to AMPHTML ads.

Regarding  the feature flag you mentioned - what is the process for enabling it? Is it something that can be set at the amp-ad tag level if we wanted to test it?

**Comment by lannka** [comment]
@lexandera sorry for the misunderstanding. We can try to make `amp-flying-carpet` work in AMPHTML ads.

The flag I mentioned for non-AMP ads is `inabox-position-api`. You can turn on by visiting [here](https://cdn.ampproject.org/experiments.html).

**Comment by jasti** [comment]
This feature has been accepted to be implemented in Q3.

**Comment by zhouyx** [comment]
Hi @lexandera Thank you for the two approaches you provide. I investigated into the implementation. 

1. the flying carpet works in AMP because we fix the background with `position: fixed`. This is impossible to do with an iframe because `position:fixed` only fixed background element to the iframe itself. 
2. I used `<amp-position-observer>` and `<amp-animation>` to created a similar flying carpet effect. Here's the example page 
https://zhouyx-flying-carpet.firebaseapp.com/manual/amp-animation/scrollbound-embeds.amp.html
As you can find the performance is not great, and that's after all the optimization we had. It's in general to have the animation compete with native scroll and there will be latency. 

Can I ask how you achieve the flying carpet effect in non AMP page? I am curious how you handle the iframe restriction while also ensure good performance. 

cc @jasti

**Comment by lexandera** [comment]
@zhouyx The formats we built using this effect are almost exclusively used by publishers for serving on their own properties, so we have the benefit of not being sandboxed inside an iframe, which allows us to use various techniques for keeping the position since we can interact with the host page directly. I'm not sure what we use currently - this has varied in the past - but I do recall polling of scroll position from requestAnimationFrame being used at one point.

Your example doesn't load for me because of a JSBin restriction; but I have one example built in AMPHTML using a scroll bound animation that probably looks similar: http://sandbox.celtra.com/preview/4920f5b4

It looks pretty good, but the background drifts slowly because it's not possible to match the height of that image with the height of the browser viewport.

Also, I can't claim this for sure, but it seems to me like previewing this example on mobile is now more jittery than it was ~2 months ago when I built it. The drifting masks it somewhat, but it would probably be a lot more obvious if the image was still.

**Comment by zhouyx** [comment]
Thank you @lexandera 

Sounds like we need to make a decision here:

1. Attempting to use the `position:fixed` by asking the host window to apply the background image. 
2. Applying background image inside the iframe. But calculate it's translateY offset in real time. 

@lexandera Thanks for the example. Yes it looks similar to what I have, except that in mine I eliminate the background drift by applying image height to 100vh. As you also mentioned  performance wise it visually feels much worse because you are actually comparing the native scroll to the image animation without the background drift. How do you want to handle it? 

>  I can't claim this for sure, but it seems to me like previewing this example on mobile is now more jittery than it was ~2 months ago when I built it
Could you provide with more information. We should probably investigate into this more if there's visibible performance downgrade. 

Thank you.

**Comment by zhouyx** [comment]
@lexandera Please let us know if the example works for you, and if the requestAnimation approach is acceptable in terms of performance. 
In the meanwhile we are exploring using the ScrollTimeline and AnimationWorklet to provider smoother scroll bound animation. #13714

**Comment by zhouyx** [comment]
@lexandera We can have some workaround to get the parent doc viewportHeight within the iframe. However there is another issue that is difficult to deal with. 

The background viewport height can be changing because the top header display/hide itself when the user scrolls. Without compensating the height change there, it is difficult to provide a relatively smooth visual effect.

I am going to explore some workaround. Will keep you updated. Thanks.

**Comment by coreybyrnes** [comment]
@lexandera Not sure if this helps, but I figured out how to horizontally and vertically center an image that is larger than the browser in an amp-ad running inside the flying-carpet component. We also wanted to be able to run an ad in this component that did not have any whitespace around it and had a full-bleed image. Again, not sure if this exactly relates to your request but thought I'd mention it since it might be close to what you're looking for. Here's a demo:
https://rev.cbsi.com/corey/test/amp/amp_demo_flying-carpet_736x736.html
And here's the background image I'm running in that demo so you get a sense of what what's visible in the flying-carpet "window":
https://tpc.googlesyndication.com/pagead/imgad?id=CICAgKCL37e7XhABGAEyCGY5yV7ZEQa4

**Comment by damjan25** [comment]
@zhouyx  Is there a plan to implement this any time soon? Or did you maybe find any decent workaround ? :P

**Comment by lannka** [comment]
@damjan25 thank for your comments. the ads working group recently is considering investing more in different ad formats support, flying carpet is one of them.
do you mind leave your specific requirement maybe in a separate issue so we can talk about details?
