### ISSUE TITLE
Introduce `consentHandlingOverride` for amp-ad

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#15269]
For a page that has amp-consent configured to block an amp-ad: 

Current behavior:
- amp-ad is not scheduled until user interacted (accept/reject/dismiss) with the consent prompt.
- the amp-ad 3p iframe is then built and the consent state is made available to the 3p js
- it's 3p ad networks' responsibility to respect the consent state and do the right thing (NPA or no ads)

New behavior
- introduce a new field in ad config "consentHandlingOverride: true/false". it is false by default
- any ad network integrated with amp-consent can flip the bit, and then they will have the "current behavior"
- any ad network has "consentHandlingOverride: false" will be blocked completely unless user accepts consent.

**Comment by jpettitt** [comment]
Related to #15264, #15235

**Comment by zhouyx** [comment]
Related to https://github.com/ampproject/amphtml/pull/14938#discussion_r187726114

**Comment by jpettitt** [comment]
Do we need something similar for `amp-iframe` (maybe an attribute that flags a consent aware iframe)?

**Comment by lannka** [comment]
@jpettitt but who will be flagging the amp-iframe?

**Comment by jpettitt** [comment]
@lannka the publisher.  Example: publisher has their own video player or data journalism iframe that is consent aware.  We'd want that to run and get consent state from the environment or as a url param.  In another case a writer includes a random iframe to embed some shiny object, we'd want that to block because there is no way of knowing if it's consent aware.  Default would be to block if `data-block-on-consent` is set and `data-consent-aware-iframe` isn't set.

**Comment by zhouyx** [comment]
@jpettitt We filed #15290 to track the iframe case separately.  The idea is `data-block-on-consent` is an attribute to specify consent blocking behavior from design, and we want to reuse that.
