### ISSUE TITLE
Would a changes.md be helpful for extensions?

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#15275]
Does it make sense for us to have a `changes.md` in each extension directory that is auto generated and lists in flight PR's for that extension by category (not-merged, merged, merged and in canary).  I noticed a couple of cases where people have tried to use features that are not yet live.

It would be handy to know what is in flight. This is particularly true once a PR is merged but not yet deployed because most searches have the `is:open` filter.  

I have no idea how easy/hard this would be to do :-)

I'm imagining something like this, the change file is triggered by changes to any of the files under `./extensions/amp-bar/`

### Not yet Merged
#123456 add foo to amp-bar
#123457 make amp-bar `<blink>`

### Merged, Not Yet Deployed
#123301 added baz feature

### Merged, Deployed to Dev Channel (Canary)
#123300 fix #123298

## Pull Requests In production
#123200 some old pr
and so on

**Comment by jpettitt** [comment]
cc @rsimha

**Comment by rsimha** [comment]
Let me take a stab at this :)

I believe the only way we can edit an `.md` file under `ampproject/amphtml` is via a PR. (Unless there's another way?)

In order to maintain an always-refreshed `changes.md` file under each extensions directory, I'd imagine we'll have to create a webhook(?) that gets triggered for all incoming PRs, and does the following:
- Checks for which extension(s) the PR touches
- Send out a new (separate) PR that:
  - Adds those changes to all applicable `changes.md` files
  - Removes all stale PRs from all the lists
  - Updates the merged / deployed state of items on the lists
- Have someone review and merge it

I suppose this will result in heavy use of our Github API, and am concerned that this will result in a lot of PR noise, given the number of extensions we have.

I now invite others to correct me on any of what I've just written :)

**Comment by jpettitt** [comment]
Another way to do it would be as an app-engine app and just link it from the top of all extension.md files. That would avoid having to generate and merge a pr every time there was a pr :-)
