### ISSUE TITLE
Linter complaining about @override lacking params

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#15297]
After #15294, `@override` statements should not contain @param declarations.

`src/service/video-manager-impl.js`
![image](https://user-images.githubusercontent.com/254946/40033045-862259fc-57ab-11e8-88a2-c4e0b305e658.png)

**Comment by rsimha** [comment]
This error goes away when you use...
```
/** @inheritdoc */
```
... in place of ...
```
/** @override */
```

However, we have numerous uses of `@override` in our code, so I'll look for a better way to fix this.

**Comment by rsimha** [comment]
I tried fixing this error by adding the missing `@param` annotation for the `@override` like so:
```
  /**
   * @override
   * @param {!../video-interface.VideoInterface} video
   */
   register(video) {
```

After this, running `gulp validator` did not result in any errors.

@alanorozco Is there any reason `@param` annotations shouldn't be used with `@override`?

**Comment by rsimha** [comment]
The answer to my question above lies in the Google JS style guide:

https://google.github.io/styleguide/jsguide.html#features-functions-parameters
https://google.github.io/styleguide/jsguide.html#appendices-notes-about-standard-closure-compiler-annotations

I'll continue to look for a way to not require `@param`s for `@override`. In the absence of this, I might have to silence the `jsdoc/require-param` rule, which would be unfortunate, since it's catching numerous legitimate cases.

**Comment by choumx** [comment]
I also ran into this with TypeScript's JSDoc support.

**Comment by rsimha** [comment]
@choumx Did you find a workaround for TypeScript?

**Comment by rsimha** [comment]
@alanorozco The Google style guide recommends `@override` over `@inheritdoc`. I'll try pursuing a fix in the lint extension.

**Comment by rsimha** [comment]
I've raised this with the developer of the JSDoc lint plugin: https://github.com/gajus/eslint-plugin-jsdoc/issues/73

**Comment by rsimha** [comment]
Good news: I've sent out a PR (https://github.com/gajus/eslint-plugin-jsdoc/pull/74) to fix the JSDoc linter, and will update our version once the PR is approved, merged, and released.

As of now, `jsdoc/require-param` is flagging 508 issues in our code. Once https://github.com/gajus/eslint-plugin-jsdoc/pull/74 is merged, the number will reduce to 166.
