### ISSUE TITLE
Define and provide a "read" event

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1540]
Some way to determine when a pageview is considered a "read" and either provide to downstream clients like access or analytics.

**Comment by rudygalfi** [comment]
@ashwinlimaye Do you think this is needed for any Access scenarios?

I think it's possible to achieve this in a publisher-defined fashion by using a timer trigger.

**Comment by georgecrawford** [comment]
Hey @rudygalfi. I was going to get in touch to ask for this, but since there's a ticket already, I'll just add my thoughts here.

I discussed the analytics/access combo with colleagues at the FT yesterday, and they're very keen to have a 'read' event which we can use for our main analytics reporting. It would need to fire after the access callback (so that we can report whether or not access has been granted), and also perhaps only when the user has been seen to 'engage' with the page in some way (scroll/click, as per #1296).

Since the primary platform for AMP at the moment seems to be the search carousel, we're very keen to avoid collecting page view stats when the user is swiping past our articles without reading them.

**Comment by amphtml-team** [comment]
+Dima
Amp-access has the pingback call which is the access spec's default version
of a read event. If there were a publisher-defined read event for analytics
purposes, I propose that we make the pingback call as the _later_ of
(access-spec default, publisher-defined)

**Comment by dvoytenko** [comment]
@georgecrawford Pingback as defined today should be what you are looking for, I believe. It's a meaningful "view" not a transitive one. We also provide `access-viewed` analytics event that is triggered at the same time as pingback. The #2417 currently in review will also repeat both pingback and `access-viewed` after successful login as well.

**Comment by georgecrawford** [comment]
OK, thanks. `access-viewed` looks right in that case.

**Comment by rudygalfi** [comment]
Haven't done much with this in awhile. If anyone is interested to work on this now, please re-open.
