### ISSUE TITLE
amp-fit-text needs a fit | truncate property

### ISSUE THREAD

**Issue by 88kbbq** [ampproject/amphtml#15448]
When a min-font is defined, there should be a property that either allows auto-expansion to include all text at that min-font size or truncate the text with ellipses. 
```
<div class="fixedblock">
  <amp-fit-text width="200"
    height="200"
    layout="responsive"
    min-font-size="40"
    expand="fit | truncate">
    Lorem ipsum dolor sit amet, has nisl nihil convenire et, vim at aeque inermis reprehendunt.
  </amp-fit-text>
</div>
```

Playing with CSS sucks
```
.title{font-size:calc( 46px + (60 - 46) * ( (100vw - 400px) / ( 1200 - 400) ));font-weight:800}
.title2{font-size:calc( 32px + (50 - 46) * ( (100vw - 400px) / ( 1200 - 400) ));font-weight:800}
```

**Comment by jpettitt** [comment]
This would be useful for variable length image captions in `amp-carousel`

**Comment by sparhami** [comment]
Rather than expanding in place, it seems more useful to expand to a scrollable fullscreen modal. For example, if you have an image with a caption, you might want to limit the caption to 1 or 2 lines, so that it does not take up a ton of space. But if users are interested, you could allow them to expand it out and read more. In that case, depending on the length of the full text, going below the min font size would not be a good experience, as the text would be very small and hard to read.

I think we should also add an affordance that lets users know they can expand out the text, though the whole area could also pop out the expanded text. Maybe something that looks like https://output.jsbin.com/rikocex.

**Comment by jpettitt** [comment]
I think both expand in place and modal would be good.   In the image caption case typical usage would be a caption clamped to 2 or 3 lines with an ellipsis.  On click the caption would expand over the parent image (up or down depending op caption position) to reveal the full text.

**Comment by cpapazian** [comment]
@jpettitt were you thinking of an overflow element similar to `amp-list`? This is something that we would like to see, as well, and I'm happy to work on this. Click-to-expand seems simple enough. How were you envisioning the modal working? This could also be bound to an action, and trigger amp-lightbox, amp-animation, etc. 

Ideally, the overflow element could be styled to float right, rather than just use absolute position, so https://github.com/ampproject/amphtml/issues/20122 would be related.

**Comment by aghassemi** [comment]
Implemented under `<amp-truncate-text>` with https://github.com/ampproject/amphtml/pull/22302
