### ISSUE TITLE
Validator tests fail on OS X with `.DS_Store` message

### ISSUE THREAD

**Issue by twifkak** [ampproject/amphtml#15557]
## What's the issue?

Validator tests fail on OS X with `.DS_Store` message. See:

![screenshot of error](https://user-images.githubusercontent.com/4065175/40468845-2940de58-5f61-11e8-8be8-d5c197176a85.png)

From comments in PR #15453.

## How do we reproduce the issue?

Run `gulp validator` and/or `gulp validator --update_tests` on OS X.

**Comment by Gregable** [comment]
It looks like something is creating these extraneous files in the github path. 

The test expects a certain directory structure and that testdata/ only has directories in it, not files. To fix, we could skip calling readdirsync on items starting with `.`, or items which are files. I'm nervous about the latter, because it could result in someone adding a test file to `testdir/` itself and not noticing that the test isn't actually being executed.

**Comment by Gregable** [comment]
> I'm nervous about the latter, because it could result in someone adding a test file to testdir/ itself and not noticing that the test isn't actually being executed.

I'll take that back. It looks like the code already inspects for file-ness in the extension testdata directories, but doesn't in the feature tests directories. I'll check in both.
