### ISSUE TITLE
bug: amp-user-notification blocks amp-consent when they are applied to different countries

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#15598]
## Use case:

Site has `amp-consent` configured for GDPR countries and `amp-user-notification` configured for another country.  `amp--geo` is used to set the contents of `amp-user-notification` to `display: none` outside its intended target country.

## Expected behavior

In GDPR location the consent dialog is displayed.  In the country targeted for notification the notification is displayed and in other locations the site just works.

## Actual behavior

In GDPR countries the user notification doesn't display (this is correct) but the GDPR consent dialog never appears and elements with `data-block-on-consent` are blocked.

In the notification country it works as expected (notification shown, GDPR dialog not show, ads and analytics fire)

In the countries outside both notification and consent it works as expected, both notification and GDPR dialog hidden, ads and analytics fire.

**Comment by zhouyx** [comment]
I can see this happening. In order to make `<amp-user-notification>` and `<amp-consent>` work together, only single notification/consent UI can be displayed. Which means in this case `<amp-consent>` will always wait for the `<amp-user-notification>` UI to be dismissed.

The issue is `<amp-geo>` only block `<amp-user-notification>` with `display:none`. That doesn't prevent it `#buildCallback` from being called. In which case `<amp-user-notification>` has decided to show the notification although it has `display:none`.

I think a possible solution is to have `<amp-user-notification>` to support `<amp-geo>` as `<amp-consent>` does. Would that work?

**Comment by jpettitt** [comment]
Yes I think that would work - I can definitely see a need for multiple different consent/notifications that are geo controlled  so making `amp-user-notification` geo aware and documenting how `amp-consent` and `amp-user-notification` interact would be very helpful.
