### ISSUE TITLE
Amp-List component cannot resize when using flex-item layout.

### ISSUE THREAD

**Issue by zmarquez** [ampproject/amphtml#15662]
## What's the issue?

The amp-list component does not calculate height correctly when using flex-item layout.

## How do we reproduce the issue?

1. Go to the following URL: https://www.emagister.com/amp/landing/test
2. Scroll down to the bottom of the page while the amp-list component is still loading the content.
3. When the content is loaded, only some items are visible. 

NOTE: It is important to scroll down before the content has finished loading.

Another way to reproduce the issue:
1. Go to the second page using the pagination button ("Siguiente") on the bottom.
2. Go back using the back button on the browser.

## What browsers are affected?

Reproduced in Chrome Version 66.0.3359.181 (Build oficial) (64 bits), FireFox Quantum 60.0.1 (64-bit) and Safari Version 11.1 (11605.1.33.1.4)

## Which AMP version is affected?

AMP ⚡ HTML – Version 1527021682973

**Comment by Jade05** [comment]
mark

**Comment by aghassemi** [comment]
@zmarquez `amp-list` is not guaranteed to `resize`. 

One of AMP's UX principles is not allowing page content to shift while user is looking at them. To do this, we have a complex set of heuristics which determine whether resizing `amp-list` (or other similar components) would cause content shifting. In its simplest form, if the bottom of your `amp-list` is in the viewport ( which happens if you scroll fast enough ) then resize will be denied.

AMP has the concept of `overflow` button that should be specified in case resize fails. AMP will automatically show the `overflow` section and when user taps it, it will do the resizing.

Please see https://www.ampproject.org/docs/reference/components/amp-list#specifying-an-overflow for details and implement it for our case.

**Comment by aghassemi** [comment]
Closing the issue per above.
