### ISSUE TITLE
Request cherrypick to #15671

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#15672]
#15671 Fixes #15636 

It is bug that affects the usage of `<amp-consent>` component in Safari version < 10.3. That's around 15% of Safari users. With the Safari bug, user won't be able to close the consent UI and proceed with content.

I believe #15636 is qualified as a P0 for the large number of users that are affected and it should be patched to PROD. 

cc @choumx @lannka @jasti @dparikh

**Comment by mrjoro** [comment]
We haven't started the [new process for cherry picks yet](https://github.com/ampproject/amphtml/issues/15666), so we don't technically need this issue yet.

That is, because this affects a large number of users of amp-consent which is important for regulatory reasons I'd be supportive of making it a P0 and cherry picking it.
