### ISSUE TITLE
FR: Change AMP form search action

### ISSUE THREAD

**Issue by ssingar** [ampproject/amphtml#15708]
I need to dynamically append the User entered search value(name=globalSearchText) to the below form action and then display the users the search results page. The final relative URL format should be /en/mystore/searchterm/globalSearchText/true/globalSearchText/, ie. like /en/mystore/searchterm/pen/true/pen/.
Here is the sample code I am trying to implement. Please help me with your inputs.

Approach 1 : 
```
<form method="GET" class="desktop-header-search" action="/en/mystore/searchterm/"
     	name="CatalogSearchForm" id="CatalogSearchForm" target="_top" data-amp-replace="globalSearchText">	        
	        <div class="desktop-search-wrap" id="header-search" role="search">
		        <input id="site-search__input" type="search" placeholder="Search mysite.com"  value="" accesskey="0" name="globalSearchText" autocomplete="off"/>
		        <button title="Search" type="submit" id="searchButton"><i class="icon-search-1"></i></button>					
	      	</div>
		</form>
```
I tried to append the globalSearchText/true/globalSearchText to the action , but was unsuccessful.

Approach 2 : 
```<form method="GET" class="desktop-header-search" action="/en/mystore/searchterm/globalSearchText/true/globalSearchText/"
     	name="CatalogSearchForm" id="CatalogSearchForm" target="_top" data-amp-replace="globalSearchText">	        
	        <div class="desktop-search-wrap" id="header-search" role="search">
		        <input id="site-search__input" type="search" placeholder="Search mysite.com" on="tap:AMP.setState({CatalogSearchForm: 'globalSearchText'})" value="" accesskey="0" name="globalSearchText" autocomplete="off"/>
		        <button title="Search" type="submit" id="searchButton"><i class="icon-search-1"></i></button>					
	      	</div>
		</form>
```
Here I tried to update the globalSearchText in the form action using data-amp-replace but failed to get the result.

**Comment by cvializ** [comment]
`data-amp-replace` and [AMP Variable Substitution values do not work on the form element](https://github.com/ampproject/amphtml/blob/master/extensions/amp-form/amp-form.md#variable-substitutions), only the inputs within it.

I would say the standard way to handle GET requests is to use the data in the querystring `?globalSearchText=myquery` but if you need to use the path to leverage existing endpoints, I think your best bet will be to use a redirect on the GET response. Write your AMP form as normal and use the HTTP response from the server to handle changing the URL. It incurs a round trip cost since you can't rewrite the action on the client, but it solves your issue.

The example uses expressjs but you can use your library or language of choice.

Example code: https://glitch.com/edit/#!/amphtml-15708-form-redirect
Example demo: https://amphtml-15708-form-redirect.glitch.me/

```js
app.get('/en/mystore/searchterm', (req, res) => {
  res.redirect(`/en/mystore/${req.query.globalSearchText}/true/${req.query.globalSearchText}`);
});

app.get('/en/mystore/:term/true/:termagain', (req, res) => {
  res.end(`Thanks for looking at ${req.params.term}`);
});
```

```html
  <form method="GET" class="desktop-header-search" action="/en/mystore/searchterm/" name="CatalogSearchForm" id="CatalogSearchForm" target="_top">	        
    <div class="desktop-search-wrap" id="header-search" role="search">
      <input id="site-search__input" type="search" placeholder="Search mysite.com"  value="" accesskey="0" name="globalSearchText" autocomplete="off"/>
      <button title="Search" type="submit" id="searchButton"><i class="icon-search-1">Search</i></button>		
    </div>
  </form>
```

I'll change this to a feature request for client-side action URL rewriting, but we will need to investigate feasibility and security considerations.

**Comment by ssingar** [comment]
@cvializ ,
      Thanks for the reply. It provides an option for me to implement this. Also, I would like to check if we have any simple way like using an anchor tag (<a>) instead to form submission and appending the user searchterm to it dynamically and do a location.href ? If yes, can you please provide an example.

**Comment by cvializ** [comment]
Yes if you don't need to submit more data using the form, you can use `amp-bind` with an `<a>` tag.

```html
  <div class="desktop-search-wrap" id="header-search" role="search">
    <input on="change:AMP.setState({query: event.value})" id="site-search__input" type="search" placeholder="Search mysite.com"  value="" accesskey="0" name="globalSearchText" autocomplete="off"/>
    <a href="/en/mystore/searchterm/" [href]="'/en/mystore/' + query + '/true/' + query" title="Search" type="submit" id="searchButton"><i class="icon-search-1">Search</i></a>		
  </div>
```
