### ISSUE TITLE
Change css attribute by system time

### ISSUE THREAD

**Issue by 88kbbq** [ampproject/amphtml#15787]
Trying to show an "Open" or "Closed" on the homepage based on the current local time. Easy with JS but can't seem to find the right amp component to do this. 

Would we need an **amp-time** component or is this possible with some combination of current components?

**Comment by jpettitt** [comment]
You can do this with `amp-list` and an external endpoint.  That may be a better way to go in general as it will allow you to change the rules server side instead of burning them into the page code which may be cached for some time.   

If you were going to build an `amp-time` how would you like to see it work?

**Comment by 88kbbq** [comment]
Well it'd make sense to just add new [event and actions](https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md) maybe called dateTime for all relevant components. This way dateTime syntax could look something like

`<div on="dateTime:AMP.cron(0 13 * * 1).hide,AMP.cron(0 14 * * 1).show">hides content at 1:00 p.m. UTC every Monday and show content 2:00 p.m.</div>` 

or

`<div id="message" on="dateTime:AMP.iso(20180915T000000-0800).message.someattribute">Adds some attribute to the message ID on midnight Sept, 15 2018 PST.</div>` 

Just thought about it for a few minutes, so I maybe be off on syntax. I'm confident you got the jist of it. Developers could add time control to ads and other AMP components for holiday sales, breakfast/lunch/dinner specials, flash sales, etc. Or you could work it like amp-bind in a way. Whatever you think is most versatile.

**Comment by 88kbbq** [comment]
https://github.com/ampproject/amphtml/issues/15780

**Comment by sparhami** [comment]
Kind of reminds me of a Polymer component I made a while ago: https://github.com/sparhami/time-selector

I think having something update a value based on the time, then using that with `<amp-selector>` would be nice. Also being able to specify various time ranges for the selection would be nice.

Having this purely client-side would be good for something like a small business that might want to have their open/close times drive the presentation of an AMP page, but aren't too worried about it being incorrect due to caching and don't want to host an endpoint.

**Comment by aghassemi** [comment]
@sparhami That's a cool component! 

The biggest problem we need to solve with dynamic content request such as this one is AMP's UX promise that content will not shift after render. This essentially means if anything can change CSS, it either has to block rendering until it has done its thing or wait until user interacts. With SSR we have almost remove all cases where an extension needs to block rendering. `https://ampbyexample.com/components/amp-dynamic-css-classes/` is still blocking, so we may need to put this feature there.

We are getting more and more requests for dynamic content, so we need to reevaluate other possible approaches at some point as well.
