### ISSUE TITLE
position-fixed element bounces when scrolling on iOS

### ISSUE THREAD

**Issue by aboekhoff** [ampproject/amphtml#15809]
## What's the issue?

The position fixed elements bounce when scrolling on iOS.

## How do we reproduce the issue?

[Visit a reddit AMP page in Safari or Chrome on an actual iOS device](https://www.google.com/amp/s/amp.reddit.com/r/NorthKoreaNews/comments/8f6mky/2018_interkorean_summit_%EB%82%A8%EB%B6%81%EC%A0%95%EC%83%81%ED%9A%8C%EB%8B%B4_megathread_rkorea/)
Note the jittering position of the CTA at the bottom of the page.

## What browsers are affected?
Chrome and Safari in iOS

## Which AMP version is affected?
1527809694656

**Comment by aghassemi** [comment]
/to @jridgewell 
/cc @dvoytenko 
happens in viewer case only.

**Comment by jridgewell** [comment]
This is because you have `bottom: 1%` on the fixed position element. Right now, the fixed-layer transfer hack (it helps with iOS's jittering) only transitions elements that are `top: 0` or `bottom: 0` and it's total height is less than 300px. We can probably loosen these restrictions, though.

Related: https://github.com/ampproject/amphtml/issues/14788

**Comment by aboekhoff** [comment]
Ok we're changing it to `bottom: 0` for the time being.
Relatedly, is there a way to test this in the AMP viewer in development?

**Comment by jridgewell** [comment]
Unfortunately not. 😅
