### ISSUE TITLE
amp-sidebar with toolbar will open then immediately close

### ISSUE THREAD

**Issue by bmadzar** [ampproject/amphtml#15907]
## What's the issue?

`amp-sidebar` with toolbar will open then immediately close (on both 'toggle' and  'open' actions) as of 1528247370025.

## How do we reproduce the issue?

It can be reproduced on ampbyexample.com:

https://ampbyexample.com/components/amp-sidebar/preview/

Clicking on either of the two bottom "Toggle Sidebar" buttons will cause the sidebar to open then immediately close.

## What browsers are affected?

Tested in Chrome 67, Firefox 52 and Microsoft Edge.

## Which AMP version is affected?

This is a new issue, first observed today. Latest prod AMP version 1528247370025.

**Comment by aghassemi** [comment]
/to @cathyxz I think it is just a confusing ABE sample. Issue seems to be related to "Toolbar" part and opening/toggling when sidebar is displayed as toolbar doesn't make sense. (still shouldn't flicker anyway).

**Comment by ericcecchi** [comment]
We also noticed this bug was introduced into production in the latest AMP sidebar release. The bug is only present when the toolbar is visible; the sidebar opens as expected when the toolbar is hidden by the toolbar media query.

**Comment by cathyxz** [comment]
Ack. 

Technically speaking, the sidebar isn't supposed ever to open when the toolbar is visible, but the implementation of this logic is leaky. We currently have a callback that closes the sidebar whenever the toolbar becomes visible. We should add logic that avoids opening the sidebar in first place if toolbars are visible. 

Technically speaking, the intended use case is that your media query should not display the toggle sidebar button if the toolbar is visible. But nonetheless, the component itself should have some inbuilt restrictions so that we don't try to flash the sidebar.

**Comment by cathyxz** [comment]
This is a bit more subtle than I thought it was. I think AMPStart where our current example is from uses a pattern where we have a minimal toolbar that only displays a hamburger that's supposed to open the sidebar itself. Hence, the coarse-grained check for *do-we-have-a-toolbar* visible to determine whether sidebar can be opened is not correct... I think the best way currently to implement sidebar is just to use vanilla CSS media queries on your sidebar toggle button so it only shows up when the toolbar is not visible (e.g. PR to AMP By Example referenced above).

**Comment by htrex** [comment]
Our website https://amp.openpolis.it/ is affected by this bug too.
It seems a regression introduced around 7 or 8 June as it worked perfectly before.

> We should add logic that avoids opening the sidebar in first place if toolbars are visible.

On the AMP documentation I couldn't find any reference for this statement.
Please restore the previous behavior as soon as possible and leave the toolbar hiding as an option.

As a design decision we have some "hot" links on the toolbar, which are repeated on the top of the sidebar. When there's enough display space the links are repeated on purpose and the toolbar is not supposed to disappear when the sidebar is opened.


Something like:
```
<button id="menu-toggle" on="tap:toolbar.toggle,sidebar.toggle" aria-label="open menu">menu</button>
```
should be good.

**Comment by htrex** [comment]
This change broke backward compatibility and I'm desperately looking for a temporary fix to revert to the previous AMP behaviour but couldn't find any way to use a previous AMP version.
Any suggestion is welcome!

**Comment by bmadzar** [comment]
Our setup is similar to what @htrex described; it's not an 'either-or' -- our design relies on the toolbar to remain visible when the sidebar opens. I can achieve the same end result by different means, but once again this is a breaking change with no warning. I could also find nowhere in the docs saying that this was not an acceptable use case. The fact that it is on ampbyexample.com seems to imply the opposite.

**Comment by aghassemi** [comment]
Since this is a regression, I will set to P0.

**Comment by aghassemi** [comment]
/cc @adelinamart @cathyxz 
lets patch along with https://github.com/ampproject/amphtml/issues/15980

**Comment by ericcecchi** [comment]
Thanks for prioritizing @aghassemi! I agree with @bmadzar and @htrex that since this broke what appeared to be an acceptable use of the toolbar w/ sidebar toggle, the patch should restore the previous functionality and not implement the undocumented "intended" behavior. We should at least be given notice of deprecation if the behavior is going to change in a future release.

**Comment by cathyxz** [comment]
Okay, it seems like this behavior changed between 1527816702194 and 1527021682973 (regression test [here](https://codepen.io/cathyxz/pen/OEmoWr) ) caused by the refactor in https://github.com/ampproject/amphtml/pull/15641. I didn't realize that the old behavior was to allow them to show up at the same time since there's [code that explicitly tries to prevent that](https://github.com/ampproject/amphtml/blob/f20f2fe956f7dace7952755a1eeb67f0a5c92e66/extensions/amp-sidebar/0.1/amp-sidebar.js#L195-L210) from https://github.com/ampproject/amphtml/pull/10796. I think that's how it was originally designed, but it previously just didn't work. Anyway, it seems like the expected behavior now is that sidebar should still be open-able while toolbar is active.

**Comment by conwaydev** [comment]
Howdy @cathyxz ! I work with @ericcecchi and we're actually seeing this behavior happening again. We're seeing the sidebar appear/ disappear on anything that has an amp-bind attribute. You can see it happen at https://sproutsocial.com/small-business/ (or any sproutsocial.com page for that matter) where you navigate to the "Seamlessly plan and publish content across networks" section and click any of those carousel items. You'll get an immediate flash of the sidebar then it disappears. @johnritterbush noticed that there was a recent change with amp-sidebar to utilize CSS animation, but we also think this may be a regression brought on by changes to amp-bind. Please let us know!

**Comment by aghassemi** [comment]
It is related to some recent changes, @sparhami could you take a look? I think `animation-name: i-amphtml-sidebar-slide-out-left;` that's defined on `amp-sidebar[side="left"]` runs when `class` is mutated. I guess setting `animation-name` may need to move to JS? I wish keyframe animations supported "no keyframe 0" and calculated it at start like transitions do.

**Comment by sparhami** [comment]
It actually looks like the animation is triggered because the `hidden` attribute is being removed when bindings are evaluated for the first time. This causes the sidebar to layout (and thus animate) at a time it does not expect. The typical flow internally for sidebar is to remove the `hidden` attribute at the right time when opening/closing.

Binding `hidden` for opening/closing the sidebar is definitely not a good approach for showing/hiding. For example, when we show the side bar, we want to trap focus within the sidebar. This may entail something like the `inert` attribute, or setting `aria-hidden` on everything else on the body. If you try to close the sidebar by toggling the `hidden` attribute, screenreader users would end up with a completely inaccessible page.

We also do things like disabling body scrolling when we open the sidebar. If you hide the sidebar using `hidden`, scrolling will stay broken.

We can probably allow binding an attribute for controlling open/close state in the future, though we can't name that attribute `open` due to the existing usage.

In the mean time, you can open/close/toggle the sidebar using actions, as described in the documentation: https://amp.dev/documentation/components/amp-sidebar#opening-and-closing-the-sidebar

If you then need to sync some state based on whether or not the sidebar is open, you can do something like:

```html
  <amp-sidebar
    id="sidebar1"
    layout="nodisplay"
    on="sidebarOpen:AMP.setState({...});sidebarClose:AMP.setState({...})"
    side="right">
</amp-sidebar>
```

**Comment by conwaydev** [comment]
Howdy @sparhami ! I appreciate you getting back so quickly. Got it! We use `hidden` to hide the `amp-sidebar` until theres a "state" so we can be sure non-JS enabled users aren't seeing it/ allowing them to interact with it. That said this was working great up up until ~6 days ago when @jritterbush created a bug for us. Let us know if theres a better way to accommodate our AMP components for non-JS (thus non-AMP) users!

**Comment by conwaydev** [comment]
For reference, we had several bug reports of people either not having JS enabled _or_ people who weren't able to load AMP scripts "in time" and our website ended up looking like:

![50522469-b7feac80-0a90-11e9-97b5-7694ce296c3a](https://user-images.githubusercontent.com/1868805/58926994-9b873000-8712-11e9-9c53-b345ef77a6cd.png)

**Comment by conwaydev** [comment]
@aghassemi and @sparhami again please let me know if theres a different way we should be handling this, but my gut feeling that this is a regression of a change in `amp-sidebar` and I'd appreciate at least re-opening this bug until its ruled out that it isn't.

**Comment by conwaydev** [comment]
also we're updating our `amp-sidebar` to be hidden via CSS and removing the `hidden` attribute, confirmed that that works

**Comment by sparhami** [comment]
> Howdy @sparhami ! I appreciate you getting back so quickly. Got it! We use `hidden` to hide the `amp-sidebar` until theres a "state" so we can be sure non-JS enabled users aren't seeing it/ allowing them to interact with it. That said this was working great up up until ~6 days ago when @jritterbush created a bug for us. Let us know if theres a better way to accommodate our AMP components for non-JS (thus non-AMP) users!

Having the hidden attribute is fine, it is just that you should not bind it. The `<amp-sidebar>` will remove `hidden` at the right time.

It seems that anything that can only have a `layout="nodisplay"` should require you add the `hidden` attribute (and not bind it) to avoid the problem you mentioned above (in case JS is disabled or the AMP JS fails to load). I suppose it is too late to add this to validation at this point, but there may be something we can do to help other developers avoid this in the future.

//cc @honeybadgerdontcare
