### ISSUE TITLE
Flaky test:  amp-nexxtv-player 

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#15972]
Error: The test "amp-nexxtv-player   fails without mediaid" called "expectAsyncConsoleError", but there were no call(s) to console.error with these message(s): "/data-mediaid attribute is required/"

**Comment by cathyxz** [comment]
Sadly I couldn't get this test to locally fail after some 10-ish tries. 

```
  it('fails without mediaid', () => {
    expectAsyncConsoleError(/data-mediaid attribute is required/);
    return getNexxtv(null, '761').should.eventually.be.rejected;
  });
```
My best guess is that it's timing out under certain conditions on Travis. 

The purpose of this code is to verify that the mandatory attributes `mediaid` and `data-client` exist on the element. 

@alanorozco (as this is a video component) since we already validate for them anyway, do we still need the user errors? If not, we might as well just get rid of both the user error logs and the tests.

**Comment by alanorozco** [comment]
This test is trivial and can be skipped. Not sure why it's failing on Travis, I couldn't get it to reproduce locally either. #15981
