### ISSUE TITLE
Error handling for <amp-state>

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#16011]
`amp-state` allows to initialize an object by calling an URL specified in the `src` attribute.
In case the call to the endpoint fails, there is no way of providing a fallback behaviour (similar to what `amp-list` provides).

A scenario is the case where amp-state is called to initialize a variable and the value of the variable is used to decide whether or not showing a spinner. In case the call fails, the spinner will never disappear.

A solution could be adding a new action to `amp-state` like:
`on=error:AMP.setState()`

**Comment by choumx** [comment]
Continuing discussion here since an error event won't work.

This might be a good candidate for "amp-fresh" -- a UI component that (1) waits for dependent fetches to finish (#11998) and (2) then evaluates bindings in its children. /cc @ericlindley-g 

(2) currently exists in amp-list but we've talked about extracting it from the next version of amp-list (along with rename etc.). /cc @aghassemi 

```html
<amp-state id="foo" src="http://example.com/foo.json"></amp-state>
<amp-state id="bar" src="http://example.com/bar.json"><amp-state>

<amp-fresh await="foo bar">
  <template type="amp-mustache>
    <amp-img src="http://example.com/spinner.gif" [class]="foo.loaded ? 'hide' : ''"></amp-img>
    <p [text]="bar.content">Fresh content from bar.json</p>
  </template>
</amp-fresh>
```

I thought about just adding this to `amp-state` in a new version -- i.e. allow it to be a UI component OR a pure data component based on `layout` attribute -- but we probably want to support a "many-to-many" relationship between data and UI components. E.g. multiple spinners that depend on a single `<amp-state>`, or a single spinner that waits for multiple `<amp-state>` to load.

**Comment by kul3r4** [comment]
Thanks Will for summarizing this!
How does this differ with components that have an error handling, for example amp-form? Could it be counter intuitive that for some we provide the error handling inside the component and for others you have to use a different one?

**Comment by choumx** [comment]
Fair point. We could add success/failure templates to `amp-state` like I said, but then we're basically recreating `amp-list`. Instead, maybe we can allow `amp-list` to also act as `amp-state` and seed the global bindable state.

```html
<amp-list src="http://example.com/foo.json" set-state>
</amp-list>
```

**Comment by choumx** [comment]
Another possibility:

```html
<amp-state id=foo src="https://remote.example/data.json">...</amp-state>

<!-- Error UI for fetching remote amp-state. -->
<amp-list src="#foo.bar" await="foo">
  <div fetch-error>...</div>
</amp-list>
```

This does allow a workaround for "fetch only happens when amp-list is in viewport" though. I'm currently leaning towards adding optional UI to `amp-state`.
