### ISSUE TITLE
Support for referrerpolicy in amp-analytics

### ISSUE THREAD

**Issue by uniquelygeneric** [ampproject/amphtml#16060]
Currently the ability to remove referer URLs from HTTP headers are possible in [amp-pixel](https://www.ampproject.org/docs/reference/components/amp-pixel#referrerpolicy-(optional)) tags.

This functionality does not currently exist in amp-analytics, but this proposed feature would leverage the same ```referrerpolicy``` parameter as with amp-pixel.

Ideally, this would be represented in an analytics spec as such:
```
'vendor':{
    'vars': {
      'foo': 'bar'
    },
    'requests': {
      'pageview': 'https://example.com/analytics?id=${foo}'
    },
    'triggers': {
      'trackPageview': {
        'on': 'visible',
        'request': 'pageview',
        'referrerpolicy': 'no-referrer'
    },
    'transport': {
      'beacon': false,
      'xhrpost': false,
      'image': true
    }
  }
```
This is an example JSON, but would hopefully allow for backwards compatibility without disruption to existing vendor specs.

If ```referrerpolicy``` is not specified, the default behavior would pass the originating URL in the referer HTTP header (as it does today).

**Comment by jeffjose** [comment]
Quick update - Scheduled to work on this for the July 9 sprint.

**Comment by uniquelygeneric** [comment]
@jeffjose Did work on this FR happen this sprint? Are there any questions regarding it?

**Comment by lannka** [comment]
Yes, it's in this sprint. just about to work on it.

**Comment by lannka** [comment]
@uniquelygeneric I'm wondering on which level the `referrerpolicy` should be defined.
3 options I can see:
- request level (specified along with the `request` URL)
- trigger level (as in your example)
- transport level (defined in transport: {} and applies to all triggers/requests)

As you know AMP supports 3 ways (transport) to send pings.
- image
- xhr
- beacon

My research tells me that both `XMLHttpRequest` and `sendBeacon` APIs do not support `referrerPolicy`. So at this moment we would only be able to support `no-referrer` pings for `image` transport.

To make it clear to the users, I suggest we do the `referrerPolicy` at transport level:

```
transport: {
  image: true,
  xhr: false,
  beacon: false,
  referrerPolicy: "no-referrer"
}
```

We will enforce `xhr` & `beacon` to be false when `referrerPolicy` is specified, so that we don't end up with mixed pings.

Does that sound good to you?

**Comment by uniquelygeneric** [comment]
@lannka Yes, defining referrerPolicy in the transport level sounds good. Support for image tags is all that's needed to parallel amp-pixel behavior. Thanks.

**Comment by lannka** [comment]
@uniquelygeneric thanks for the quick response. Working on an implementation.

**Comment by lannka** [comment]
Done. Will be in canary for testing next week.
