### ISSUE TITLE
Console Warning amp-sidebar.js:303 [Violation] 

### ISSUE THREAD

**Issue by IamAlta** [ampproject/amphtml#16079]
## What's the issue?
Any chance of fixing this Console Warning?
amp-sidebar.js:303 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
Q @ amp-sidebar.js:303
(anonymous) @ amp-sidebar.js:249
mutate @ focus-history.js:100
vl @ viewport-impl.js:486
f.gh @ viewport-impl.js:444

## How do we reproduce the issue?
Applied your arrow that shows up to move to the top of the page.

## What browsers are affected?
Chrome and Firefox

## Which AMP version is affected?
1528841168349

**Comment by aghassemi** [comment]
@IamAlta Among other priorities we have, this falls on the lower end. Would you be interested in contributing a PR for it? Our contribution process is well documented and used by over 500 developers already. See https://bit.ly/helpamp if interested.

**Comment by IamAlta** [comment]
Hi @aghassemi,
I'd love to contribute when this horrendous project is done.

**Comment by vishaldodiya** [comment]
Hey @aghassemi,

I would like to work on this issue, but need help to understand the code.
https://github.com/ampproject/amphtml/blob/master/extensions/amp-sidebar/0.1/amp-sidebar.js#L556

is there reason to prevent touchmove event from executing? Because adding passive to the event listener will execute touchmove event disregarding event preventDefault and throwing an error in console.

**Comment by msyber** [comment]
Any update?
