### ISSUE TITLE
Allow amp-iframe resizing when using srcdoc

### ISSUE THREAD

**Issue by samjacoby** [ampproject/amphtml#16098]
## What's the issue?
Allow for resizing an `amp-iframe` when using the `srcdoc` attribute. 

Currently, that's not possible, because of restrictions placed on `srcdoc` and `allow-same-origin`. I understand there are substantial security concerns, but perhaps there is some workaround? 

## How do we reproduce the issue?
Per the [docs](https://www.ampproject.org/docs/reference/components/amp-iframe#iframe-resizing), to allow the appropriate `window.postMessage`, `allow-same-origin` must be enabled. `allow-same-origin` is specifically disallowed when using `srcdoc`, so it's not possible to resize the iframe.  I'd be happy to investigate possible solutions to this, if there are any viable pathways forward. 

Looks like this an issue downstream of https://github.com/ampproject/amphtml/issues/8545. Our use case is somewhat simpler (basic user interaction), so we could get away with something more limited, but this would resolve the issue, of course.

**Comment by aghassemi** [comment]
Thanks for the issue and detailed write up. We won't allow `allow-same-origin` with `srcdoc` for security reasons ( otherwise it would be a friendly iframe with access to parent ) but I don't see an issue with allowing `resize` request. The `source` of the event would be `null` in this case and that's where some of our checks fail, may require a bit of thinking to ensure this does not open any security issues, but seems reasonable to allow it.

/cc @sparhami

**Comment by samjacoby** [comment]
Great. Thank you. If this is the kind of thing that could be shaped-up for a first-time contributor, I'd be happy to take some time to see what could be done.

**Comment by aghassemi** [comment]
@samjacoby Thanks for the offer. That would be great! The change itself I believe is as simple as changing this: https://github.com/ampproject/amphtml/blob/8e04b57d2d23f431025115443aa95fcd706ee278/src/iframe-helper.js#L136 but the important part is the discussion among other experts in the team to see if there is any security downfall from that change. 

If you could kick of a PR with the change after testing to make sure if handles the bug properly, then we can start the discussion on the PR. https://bit.ly/helpamp for getting started guide.

**Comment by aghassemi** [comment]
@samjacoby We had to revert the PR due to some security concerns with redirects. After more discussions, we don't have a good solution at the moment. Unfortunately unless we can distinguish between `srcdoc` and `src with no allow-same-origin flag of sandbox`  there is a security risk in implementing this.

**Comment by samjacoby** [comment]
OK. That's too bad. 😞 

Is there no path forward, then, on resizing iframes populated w/ `srcdoc`? 

We're looking to use `srcdoc` so that we can publish better stories _to_ amp. At the moment, we sometimes disable amp publishing entirely for our more interactive pieces,
but we're hoping to have better feature parity between amp and the rest of our platform. Here's an example of a story with fairly minimal interactivity, that we still can't do, if that's at all helpful: https://www.nytimes.com/2018/07/25/crosswords/daily-puzzle-2018-07-26.html

Appreciate any thoughts or guidance on this...

**Comment by samjacoby** [comment]
Just following up here — assuming that `srcdoc` and `allow-same-origin` aren't compatible — is there any way to resize an iframe that's populated via the `srcdoc` attribute? It seems like the `postMessage` API was established for exactly this use case, so perhaps there's another (safer) way of hooking into it, or doing something similar?

**Comment by aghassemi** [comment]
@samjacoby The problem - which I verified with Web Platform engineers - is that we can not distinguish between a postMessage from `<iframe srcdoc="something">` and `<iframe  srcdoc="some-origin-that-redirects-to-another-origin">` if the second one does no have `allow-same-origin` since in both cases `origin` will be `null`. One possible approach is using some sort of `token` between communication instead of checking `origin`.

So answer you question, it is possible but more work than we can prioritize at this point. Moving your `srcdoc` to an actual Url may not be a bad idea anyway, smaller initial page size is always good.

**Comment by samjacoby** [comment]
OK, I appreciate the additional detail. I'll see if we can work around that
for now.

**Comment by ericlindley-g** [comment]
Hi @samjacoby  — circling back to the use-case: I'm assuming that it wouldn't help for us to share ways to implement the hide/show behavior in AMP (most likely with the [toggleVisibility action](https://www.ampproject.org/docs/interaction_dynamic/amp-actions-and-events) or with [amp-accordion](https://ampbyexample.com/components/amp-accordion/)), because each interactive piece you'd like to publish has a somewhat different interaction, so you need a way to embed arbitrary HTML in your AMP docs in a way that scales to different CMS users in your organization. Is that correct?

If that is the case, using an actual URL instead of srcdoc is one way to do it. Another would be to make sure that all necessary space is reserved up front for the interaction so there's no need to resize (though I imagine that's not always possible).

It may be useful to know that we're working on a what may work as a [third option](https://github.com/ampproject/amphtml/issues/14095), where developers are expected to be able to use non-AMP javascript in sections of a given page. However, there is still some uncertainty around our ability to release this feature, because we may find that it doesn't guarantee the user experience standards of AMP. As a result the timeline is a bit uncertain as well. However, this is one of the primary ways we expect to support highly interactive content.

**Comment by samjacoby** [comment]
Thanks for the assist, @ericlindley-g! Definitely, the AMP-specific options are certainly appropriate for the specific example cases we've got at hand, but yes, we're looking for a more general solution.

> If that is the case, using an actual URL instead of srcdoc is one way to do it

Yes, this seems like the most promising direction at the moment. We've got a few things we can do on our end to make this happen. 

#13471 seems like it'd be a perfect fit for our use-case. I'll keep an eye on it. Thank you!
