### ISSUE TITLE
The url requested to the amp cache by the amp-live-list component returns a broken page

### ISSUE THREAD

**Issue by franciscoUE** [ampproject/amphtml#16212]
## What's the issue?

The url requested to the amp cache by the amp-live-list component returns a broken page.

## How do we reproduce the issue?

Load a page using the amp cache and wait until the amp-live-list component sends the request

amp page in cache: https://www.google.es/amp/s/amp.marca.com/en-directo/2018/06/21/dinamarca-australia/01_0117_20180621_369_575.html

update request: https://amp-marca-com.cdn.ampproject.org/v/s/amp.marca.com/en-directo/2018/06/21/dinamarca-australia/01_0117_20180621_369_575.html?usqp=mq331AQGCAEoATgB&amp_js_v=0.1&amp_latest_update_time=20180621141038&__amp_source_origin=https%3A%2F%2Famp.marca.com
![imagen](https://user-images.githubusercontent.com/40464923/41721789-2a142a12-7567-11e8-9c11-7188116b681f.png)

I have observed that removing the amp_latest_update_time parameter from the url gives a correct response:

https://amp-marca-com.cdn.ampproject.org/v/s/amp.marca.com/en-directo/2018/06/21/dinamarca-australia/01_0117_20180621_369_575.html?usqp=mq331AQGCAEoATgB&amp_js_v=0.1&__amp_source_origin=https%3A%2F%2Famp.marca.com

![imagen](https://user-images.githubusercontent.com/40464923/41721804-331db402-7567-11e8-843f-d93b6a56e1cf.png)

## What browsers are affected?

All browsers and devices

## Which AMP version is affected?

Amp Version 1529449959701

**Comment by aghassemi** [comment]
/to @erwinmombay could you please triage ?

**Comment by ericlindley-g** [comment]
@franciscoUE The links you provided that are "broken" seem to be working as intended: I believe they are special requests that amp-list sends to the host to get a smaller response that just contains updates since the last time the page was loaded.

Are you seeing the pages break in the context of a platform that uses the Google AMP Cache? If so, please reopen this issue (I'll close for the time being, since I think this is currently working as intended)

**Comment by franciscoUE** [comment]
Thanks for your answer @ericlindley-g 

Regarding this:

> Are you seeing the pages break in the context of a platform that uses the Google AMP Cache?

I observed this while investigating why the update button does not appear after new items are added to the amp-live-list component.

While testing this I kept another tab with the cached page, this tab was refreshed regularly to make sure that the cache was updated with new items to be sure it was not a cache issue, and I confirmed that after the cache had the new items, the old tab that had not been refreshed did not detect them using the amp-live-list requests.

However, making the same test accessing the amp page directly through our domain resulted in the correct behaviour, the amp-live-list component did detect the new items making the update button visible. The only difference I was able to find is that in our domain, our server does return a full page in response to the amp-live-list request, whereas the request through the cache does not and I thought that was the problem, I should have mention from the beginning that the real issue was about detecting new items.

Unfortunately the example for this issue is for an already finished event that does not have new messages, we only have pages with actual new items added while covering relevant sport events so I can't provide you with an example that is being updated right now.

**Comment by ericlindley-g** [comment]
Got it — thanks for elaborating.
I was able to test just now with [another live blog in the wild](https://www.google.com/amp/s/amp.theguardian.com/politics/blog/live/2018/jul/17/brexit-trade-bill-vote-referendum-result-branded-dodgier-than-ever-after-vote-leave-found-to-have-broken-election-spending-law-politics-live) and didn't see the issue (update button appears as expected). 

The issue with your page might be hard to debug since there might not be an AMP developer available to check when you have something live to check out, but you can let us know if you're still seeing the issue again. In the meantime, @erwinmombay , do you have any thoughts about whether this might be an issue w/ AMP itself or a specific implementation?
