### ISSUE TITLE
gulpAmpValidator: To exclude validate HTML if no AMP defined

### ISSUE THREAD

**Issue by claudchan** [ampproject/amphtml#16241]
Hi,
Could you add this feature on validating HTML files, if there is not AMP defined, maybe show as warning that this is not AMP page / AMP not defined will be skip/ label as warning
In my case some scenario, I have some pages that not using pure AMP in the projects, but the validation keep failing from my gulp tasks.

**Comment by Gregable** [comment]
This is risky. 

For someone else's use case, they may want it to be an error if the page isn't AMP, for example because it indicates that they forgot to include the `amp` attribute on the `html` tag.

I think your best bet is to add this in as a pre-condition to running your gulp test. The easiest check is probably to look for something like the regex `<html[^>]* amp[^>]+>`. Not perfect, but should work fine for testing.
