### ISSUE TITLE
[Intent to implement] Form with CRSF token

### ISSUE THREAD

**Issue by jean-felipe** [ampproject/amphtml#16309]
### Proposal

Create an `amp-form-auth` tag, that will work like the `form_for` helper from rails, this form will get the value from `<meta token='lakshfsodiugfskdfhslkjd'>` and insert it in a hidden input to send it to backend when submitted.

``` 
<form-auth, authenticityToken="true">
  <input normalField />
  <input name="utf8" type="hidden" value="✓" class="some-class"> 
  <input type="hidden" name="authenticity_token" value="ToKeN==" class="some-class">
</form>
```
The input `authenticity_token` and `utf8` will be generated by the new component for this issue.
This will solve the problem for #9471

**Comment by aghassemi** [comment]
@jean-felipe Thanks for the proposal, unfortunately this won't work because AMP pages are cached and hence the token would be the same for all users and all page loads, defeating the purpose.

https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md#processing-state-changing-requests highlights checks you need to do server-side to ensure integrity of data. 

If you are worried about origin mocking and really need to use a CSRF token, one work-around for now until first-class support is added, is loading the token via `amp-list` (e.g. have `amp-list` talk to your server to get a token and render it in a hidden `input`).

/cc @cvializ any other work-around ideas?

**Comment by jean-felipe** [comment]
Ok @aghassemi , thanks for your reply, i already have an implementation as that link you sent, so this issue can be close right?

**Comment by cvializ** [comment]
@aghassemi your suggestion would be what I would recommend for a workaround. @jean-felipe I'm glad you have an implementation that works for you!
