### ISSUE TITLE
Check / uncheck radio input field not updated properly

### ISSUE THREAD

**Issue by sayalok** [ampproject/amphtml#16409]
## What's the issue?
I have developed an AMP site where I have three radio buttons.
1. show all
2. show only favourite
3. clear all

when i will click on clear all button it will show a lightbox. On that lightbox I have two buttons.
1. ok
2. Cancel

when user click on cancel from the lightbox the show all radio input will be checked. I have  implemented it with amp-state variable change. For the very first time when i click on cancel it checked properly in show all radio input but after that if I have click on clear radio input and then cancel button again it does not checked again show all radio input. 

Here i have added a sample code in codepen

Sample Code link: https://codepen.io/sayalok/pen/VdEagq

any suggestion please?

## What browsers are affected?
All browsers

## Which AMP version is affected?
1530043289240

**Comment by aghassemi** [comment]
@sayalok You need to also set the `partnerLogo.chkRadio` to something else when lightbox opens. Otherwise your state would be out of sync with selected radio. (issue is state stays at `show-all` value but checked button is not, so next time `AMP.setState` is called with `show-all` it gets ignored since value did not change so it is considered noop.

`change:favorite-lightbox, AMP.setState({partnerLogo:{chkRadio : ''}})` would do it.

For future, Stackoverflow or Slack channel would be better for these questions, we hope to reserve github for real bugs. Please see https://www.ampproject.org/support/developer/get_support for different developer support channels AMP has.

Thanks.

**Comment by sayalok** [comment]
thanks for your feedback. And i posted on stackoverflow with amp tag but i don't get any response there.
