### ISSUE TITLE
AMP page rending slowly and have white screen 

### ISSUE THREAD

**Issue by lealff** [ampproject/amphtml#16499]
click and switch to a new page will wait 2-5 seconds and have white screen until the page is presented。
according the network request records and find belows:
failed to access the request:https://www.google.com/ads/ga-audiences
also sometimes the https://www.google-analytics.com/r/collect will auto request twice. the first is 200 but reponse a black page . the second request is normal and statu code is 302.
i dont know if you are understand my words. if you have any ideas about this issue. plesase help to share your exprience. thank you!

**Comment by jpettitt** [comment]
`/r/collect` firing twice is normal if you have analytics integration enabled for ads. It fires once to the analytics endpoint and then redirects to the ad server.

Can you post a link to a page that's failing to render?  AMP has a couple of timeouts in the design to catch errors that would otherwise leave a blank screen (one for extension that fail to load and another in the CSS catches the case where the runtime throws an error).  Without seeing the console log or the page in question it's not possible to diagnose this further.

**Comment by jpettitt** [comment]
I'm going to close this, if you still have the issue please post a link and re-open it.
