### ISSUE TITLE
[Master feature] Improve basic amp-carousel UX

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#16508]
Fix some low-hanging fruit for amp-carousel UX, including better visual and interaction design for the slide-advance affordances.

- Better advance affordance visual design (improved arrow icon)
- better "hint" affordance (currently appears and disappears without optimal timing—there could be a better pattern)

**Comment by jpettitt** [comment]
I'd love to see caption handling built in.  The issue is that one slide may have a caption that's three words eg  "Photo: John Pettitt" and the next will have a 25 word description. With the single height for all slides requirement on `amp-carousel` this becomes problematic to implement well.  Typically a caption is partially shown if it overflows and `amp-bind` or `selected` used to expand it over the slide content on user action.  A built in caption handler that expands on user action would greatly simplify implementation.

**Comment by ericlindley-g** [comment]
@jpettitt Good call — likely won't be completed in this activity, but adding that to the list of needs for amp-carousel

**Comment by ericlindley-g** [comment]
Closing this master feature to de-dupe with https://github.com/ampproject/amphtml/issues/16509
