### ISSUE TITLE
amp-pan-zoom does not scroll when using buttons

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#16575]
Go to [https://codepen.io/kul3r4/pen/QxRBjr](https://codepen.io/kul3r4/pen/QxRBjr). Run AMP.toggleExperiment('amp-pan-zoom') in the console to enable the component.

- Click on the PLUS button on the right side: the area is zoomed but you cannot scroll
- If you double tap instead, scrolling is available

@cathyxz FYI

**Comment by cathyxz** [comment]
This should already be fixed. By "scrolling", do you mean panning the zoomed in content or something else?

**Comment by cathyxz** [comment]
![panning](https://user-images.githubusercontent.com/1528181/42476561-3735c424-8383-11e8-9d25-50f81b89bbf1.gif)

**Comment by kul3r4** [comment]
Hi, can you try https://codepen.io/kul3r4/pen/QxRBjr?
Please do not double tap at first, just push the + button and try to swipe. It doesn't swipe for me

**Comment by cathyxz** [comment]
Did something change in your codepen between yesterday and today? There are a lot of XHR errors and amp-state errors that prevent it from working, so I'm having a bit of trouble reproing. 

What I ran above was a direct fork of yours because your version can't be viewed in full page mode. Perhaps the real underlying issue here is that swiping only works on mobile? Desktop panning I realize isn't implemented yet because the gesture recognizer tap events don't map to desktop mouse events. Codepen's edit mode is in desktop mode.

**Comment by kul3r4** [comment]
Yes, so I opened https://codepen.io/cathyxz/full/rKQBjL/ as you suggested, (gone to full mode as you can see from the link containing /full) and opened the Chrome console to mobile mode. If I click on the + button and try to swipe, then it doesn't swipe.
How are you testing exactly? Are those the same steps? I am sure I am not doing this properly but can't understand how you are testing it on codepen.

**Comment by kul3r4** [comment]
Closing this as I cannot reproduce it anymore
