### ISSUE TITLE
amp-img fallback breaks on resize if srcset is present

### ISSUE THREAD

**Issue by antejan** [ampproject/amphtml#16588]
## What's the issue?

I'm trying to use several webp image sizes through srcset of amp-img and adding fallback amp-img inside with png. 

```
<amp-img src="s.webp" srcset="s.webp 100w, m.webp 200w" width="100" height="100">
    <amp-img fallback src="s.png" srcset="s.png 100w, m.png 200w" width="100" height="100"></amp-img>
</amp-img>
```

1. Most of the non-webp-supportive browsers (Edge 17, IE 11, Safari 11, iOS 11 Safari) do show fallback on load, but then if user resize browser and (as it seems) triggers srcset transition, browsers show broken image, and after it resize doesn't change things anymore. 
2. Firefox 67 doesn't even show fallback if outer amp-img have srcset.

## How do we reproduce the issue?

Here's minimal demo on codepen: https://codepen.io/antejan/full/rKEPNm/

* Open in non-webp-supportive browser, resize window to narrow and back, observe issue
* Open on iPhone, rotate to landscape view and back, observe fallback image disappear
* Open in Firefox, observe fallback not present if outer amp-img have srcset

## What browsers are affected?

Tried Firefox 67 on Ubuntu 18.04, Mobile Safari on iOS 11.4.
And through Browserstack: Edge 17 and IE 11 on Win 10, Safari 11 on 

## Which AMP version is affected?

Included as `<script async src="https://cdn.ampproject.org/v0.js">`.
In console I see `Powered by AMP ⚡ HTML – Version 1530567757224`.

**Comment by jridgewell** [comment]
@cathyxz: P1

**Comment by aghassemi** [comment]
Existing PR https://github.com/ampproject/amphtml/pull/16404 should fix this. Good test case in codependent, thanks @antejan.

**Comment by cathyxz** [comment]
>Most of the non-webp-supportive browsers (Edge 17, IE 11, Safari 11, iOS 11 Safari) do show fallback on load, but then if user resize browser and (as it seems) triggers srcset transition, browsers show broken image, and after it resize doesn't change things anymore.
Firefox 67 doesn't even show fallback if outer amp-img have srcset.

#16404 should solve most of this. 

There is one slight caveat though. We explicitly only toggle the fallback once. So basically if you have a `srcset`, and it falls back once, you resize once to trigger srcset upgrade and resize back to trigger a srcset downgrade, it will not re-trigger the fallback image. This only applies to Firefox though, since Safari doesn't even trigger srcset, and Chrome always keeps the upgraded image. I intend to revisit this behavior though, since from a UI perspective it doesn't make a lot of sense and I'm wondering if the performance concerns that resulted in this decision are still applicable after we switch to native srcset.

**Comment by cathyxz** [comment]
I forked this to https://codepen.io/cathyxz/pen/ajNpaZ, using latest canary which includes changes from #16404 by including https://cdn.ampproject.org/rtv/001531357871900/v0.js. 

I tested this on Safari and Firefox on MacOS, and the fallback images show correctly.

**Comment by cathyxz** [comment]
Chatted about the double-rotation fallback-only-gets-toggled-once case with @aghassemi, and we decided not to change the current behavior because it's a super edge case: 
1. It only applies to Firefox. 
2. It only applies if you have a `srcset` with mixed `webp` and valid image formats. 
3. It only applies if you rotate the phone and back again. 

Having a mixed `srcset` that has both `webp` and other valid image formats is a pretty strange hyper edge case, so we're not going to address that for now. Other than that, this issue should be wholly addressed by #16404.

**Comment by antejan** [comment]
Sounds great, thank you! Also checked your fork in my devices/browsers and it works perfectly for me as well. When do you think we can expect it to be released to `https://cdn.ampproject.org/v0.js`?

**Comment by cathyxz** [comment]
@antejan the current canary should be released to production the following Tuesday on 7/24/2018. I think the release tracking issue is: https://github.com/ampproject/amphtml/issues/16669.
