### ISSUE TITLE
Support "twitter lists" embed.

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#16684]
Twitter has a "twitter lists" product (basically a string of tweets from a curated list of accounts).  We should consider adding it to amp-twitter or create a separate amp-twitter-lists component.

See https://help.twitter.com/en/using-twitter/twitter-lists

**Comment by sparhami** [comment]
The twitter API docs are here:

https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview

Lists are a type of timeline. There appear to be different types of timelines, so we may want to make sure we can handle the various types. The "Guides" tab has more information on each of them.

This issue is basically the same as #300, so we should consider merging the two.

**Comment by juanlizarazo** [comment]
I can work on this one.
