### ISSUE TITLE
amp-access AUTHDATA analytics fails when response is `false`

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#16720]
in [`amp-access-analytics.js`](https://github.com/ampproject/amphtml/blob/d39efc401241421fe0830e4a710b342c44b1f7b5/extensions/amp-access/0.1/amp-access-source.js#L341)  We need to test for `!== undefined` so that `false` is correctly retuurned if the `authResponse_` is `false`.

Open question is `undefined` the right default return value?

**Comment by jpettitt** [comment]
cc @dvoytenko

**Comment by dvoytenko** [comment]
No, I don't think `!== undefined`. The `authResponse` field can never be `false`. So I don't see how truthiness could cause issues here. Still not clear what's going on.

**Comment by dvoytenko** [comment]
Which analytics field is this referring to?

**Comment by remybach** [comment]
The specific field in question is the `access` field, which comes back as `false`.

**Comment by dvoytenko** [comment]
The amp-subscriptions, on the top level, does not have `access` field - the similar-in-notion field is called `granted`. The `data` substructure allows any custom fields, but top level is protected to ensure forward extensibility. It's possible to instead put the `access` field inside `data` and do `AUTHDATA(data.access)`. But I'd instead recommend `AUTHDATA(granted)` since it covers any type of entitlements source the same way, including `amp-subscriptions-google`

**Comment by jpettitt** [comment]
Closing as invalid
