### ISSUE TITLE
How to enable scrolling while sidebar is opened

### ISSUE THREAD

**Issue by zaxoavoki** [ampproject/amphtml#16844]
I have a sidebar:
```
<script custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js" async></script>
<amp-sidebar id="header-sidebar" layout="nodisplay" side="right">
    ....
</amp-sidebar>
```
But when sidebar is opened I can't scroll the page. I see that `<html>` tag has this class `i-amphtml-scroll-disabled`.

**So, how can I enable scrolling on the page when menu is opened?**

**Comment by aghassemi** [comment]
@zaxoavoki `amp-sidebar` is a `modal` which makes the page behind not interactive when opened ( it shims the background and any click on the page will close the sidebar). That is by design.

Curious to hear what your use-case is and whether we have existing ways to achieve what you like to do. A Url or screenshot would be great.

/cc @ericlindley-g

**Comment by zaxoavoki** [comment]
For example you can check [this page](http://inbusiness.zzz.com.ua/amp/post.amp.html). When user open the sidebar it's disable scroll on th hole page. Probably, I don't sure that I could open the page with AMP in desktop, right? I mean that Google won't show it in the search websites list..?

**Comment by aghassemi** [comment]
this is as designed. amp-sidebar should not be used for context menus (amp-selector, amp-bind and normal CSS should be used instead) https://github.com/ampproject/amphtml/issues/21888 will also help with the use-case.
