### ISSUE TITLE
Uncaught exception when using scrollTo after setState and open link

### ISSUE THREAD

**Issue by trvanhai4** [ampproject/amphtml#16901]
## What's the issue?

I got an uncaught exception when using scrollTo after setState and open link. 

## How do we reproduce the issue?

I want to fetch remote state, open a new tab with an anchor and scroll to a specific element on the page.

There are 2 cases: https://gist.github.com/trvanhai4/11e6237177603b33aece631c3ce04b98
- scroll_before.html
- scroll_after.html

Please try running those cases on AMP playground: https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-bind%2Fsource%2F&mode=iPhone+7.

## What browsers are affected?

I checked Chrome Version 66.0.3359.181 (Official Build) (64-bit), Safari Version 11.1 (13605.1.33.1.4) and Firefox 59.0.3 (64-bit).

I got the uncaught exception on Chrome/Safari. But the scroll only happen when I'm using scrollTo before setState (the page are not scroll if I'm using scrollTo after setState).

## Which AMP version is affected?
Powered by AMP ⚡ HTML – Version 1531347091169

**Comment by sparhami** [comment]
It looks like actions wait for a previous one to finish here:

https://github.com/ampproject/amphtml/blob/ec8e69114664da1de8b5fe3103039a6804227c99/src/service/action-impl.js#L497-L500

It looks like the first setState action is fairly async (needs to get the bind service), so the scrollTo does not happen for a while. This appears to happen after the anchor has opened the link in the new tab. Finally, the mutation is blocked because it happens when the viewer is not visible.

A couple of notes:

1. The second time you click the link, things work (presumably because the bind service is already set up, so the async work for the `setState` action happens prior to the browser switching to the new tab)
2. If you try this locally (e.g. outside of a viewer), things work correctly
