### ISSUE TITLE
Analytics: Timer event to trigger once at certain time

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#16910]
Request from #14234

`<amp-analytics>` timer trigger doesn't provide way to trigger a request once at certain time. It would be easier to config if we can provide something like `sendAt: 10` to send and only send one request at 10sec. 

 As @dougscher pointed out in https://github.com/ampproject/amphtml/issues/14234#issuecomment-406394867, it's also possible to add `once: true` config.

**Comment by dougscher** [comment]
BTW

The use case was to send page load and other statistics after 10 seconds. This also acts as a user bounce/flyby indicator if it is not sent.


Thanks, 
Doug

**Comment by ASochat** [comment]
Is the feature available now? Would love to use it as well

**Comment by dougscher** [comment]
Any update on this?

**Comment by micajuine-ho** [comment]
From my understanding, this should be possible by using a config setup like this:
```
      "triggers": {
          "timer": {
            "on": "timer",
            "timerSpec": {
              "interval": 3,
              "maxTimerLength": 2,
              "immediate": false
            },
            "request": "endpoint"
          }
        },
```

This will send a request once the `maxTimerLength` is reached (no request will be sent out since the interval is never hit). Additionally, this behavior will occur regardless of the existence of `startSpec` or `endSpec`.
