### ISSUE TITLE
Set cookieDomain in amp-analytics

### ISSUE THREAD

**Issue by 88kbbq** [ampproject/amphtml#1693]
Possible?

**Comment by 88kbbq** [comment]
Ah, found another issue #1449

**Comment by cramforce** [comment]
We implement the ability to set on the highest available domain. Let me know whether you were looking for anything else.

**Comment by 88kbbq** [comment]
I searched for documentation about this but couldn't find anything. How do we set cookie domain for amp google analytics

**Comment by cramforce** [comment]
There is currently no way to do it. What would you like to set it to?

**Comment by 88kbbq** [comment]
I'm looking to set the www as the cookie domain and have cookie-free domain for static content. Does the AMP cache add cookies to static resources? If so, I suppose this is a moot point.

**Comment by cramforce** [comment]
Separate domains for resources are somewhat of a mixed bag in the times of HTTP 2 and SPDY.

AMP, when loaded from your own domain, can add cookies if requested by amp-analytics. By default it will set it on `example.com` instead of `www.example.com`.

For a cookie-free domain it is is better to use a different 1st or 2nd level domain like `example-static.com`

**Comment by 88kbbq** [comment]
In my case, I already have EV SSL certificates for my domain and subdomains. Buying another domain and cert is uneconomical.
