### ISSUE TITLE
Lighthouse reports inefficient cache policy on AMP's js scripts

### ISSUE THREAD

**Issue by ro2ni3** [ampproject/amphtml#17079]
## What's the issue?
When running Lighthouse tests against our AMP pages, one of the diagnostics warnings that comes up is the use of inefficient caching policy. 
The caching policy on all amp js scripts seem to be too low for lighthouse. All of them are 7 days except for the v0.js which is 1 day.
Is this something that Lighthouse is too picky about and should be ignored? or is it something that needs to be fixed on the where the scripts are being served from?

Screenshot of lighthouse caching policy diagnostic attached:
![screen shot 2018-07-25 at 12 05 15](https://user-images.githubusercontent.com/32260852/43203013-f093c8a6-9014-11e8-8978-d0cf2fd2d47d.png)

**Comment by jpettitt** [comment]
AMP is on a once a week release cycle so a 7 days cache time is appropriate.  When you load an amp document via the amp cache we substitute a versioned url with a longer cache time.  There are two exceptions `v0.js` which is deliberately shorter to allow for high priority fixes and `amp-geo.js` which has a 30 minute lifetime because it is patched with the users current country when served.

So yes this is lighthouse being picky.

**Comment by ro2ni3** [comment]
So there is no versioning of amp scripts then, which means that everyone using 0.1 may get broken.
