### ISSUE TITLE
getMode().test should be true for visual tests

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#17108]
/cc @rsimha

**Comment by danielrozenberg** [comment]
@rsimha what are the differences when it comes to test mode? What should we take into account here

**Comment by rsimha** [comment]
@newmuis Nice catch.

@danielrozenberg I don't believe the visual tests themselves need to do anything different, but yeah, the runtime does behave slightly differently in some cases when `getMode().test` is true, so we need to trigger that behavior during the visual tests.

I think this issue can be fixed by adding a case here for the visual tests:

https://github.com/ampproject/amphtml/blob/28ac444cc29c92daaee0fd08665c69f673b29e4c/src/mode.js#L71

**Comment by rsimha** [comment]
To plumb the test mode during the visual diff tests, you can first add an `opt_test` flag to `applyConfig`

https://github.com/ampproject/amphtml/blob/dec2fc23fe1ddcae1abb2022bc8630d18d4998cf/build-system/tasks/prepend-global/index.js#L114-L156

Then, you can make `visual-diff.js` directly call `applyConfig` instead of invoking the wrapper `gulp` task via `exec` as is done right now

https://github.com/ampproject/amphtml/blob/8e9d57d806f05756219d466ea77ce0e8e2125ec0/build-system/tasks/visual-diff.js#L354-L366

**Comment by Enriqe** [comment]
running `gulp visual-diff` doesn't set AMP_TEST to true by default. Is this expected?  (see https://github.com/ampproject/amphtml/pull/19250/files#r233264120)

**Comment by danielrozenberg** [comment]
The fix for this issue was accidentally reverted in #18158. I'll take a look at fixing it again asap
