### ISSUE TITLE
amp-iframe allow-same-origin and subdomain restriction

### ISSUE THREAD

**Issue by sryze** [ampproject/amphtml#17212]
Why is it not allowed to have iframes loaded from the same domain even if `allow-same-origin` is specified, while it is allowed to use a subdomain? 

I don't understand this requirement. Is this due to technical reasons or due to "we don't want you to do dumb things because we care about you" reasons?

For example, I need to include a chat box on a page. It used to work perfectly on the non-AMP page, but now that I'm converting it to AMP I need to use a workaround. OK. I put it into an `amp-iframe` as suggested in documentation in other places. But it doesn't work, says something about null origin. Ah, here is the error message:

```
Sandbox access violation: Blocked a frame at "https://localhost:8080" from accessing a frame at "null".  Both frames are sandboxed and lack the "allow-same-origin" flag.
```

No idea what it is trying to say because the iframe is obviously from the same origin (and also where this `null` comes from), but OK, after some googling I figured I need to add `allow-same-origin, added that. But the iframe still won't load, this time with a different error:

```
Origin of <amp-iframe> must not be equal to container  ... if allow-same-origin is set. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.
```

If same origin it must not be same origin? Doesn't `same-origin` in the name of the property contradict this?

I'm sorry for this dumb question, I have read the explanation at https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md but I still don't understand this. Can you please improve the documentation and the error messages, or make it possible to turn off this restriction? 

**Update:**

I'm not sure what "both iframes" means as I have only one iframe, but the chat library itself creates another iframe inside that iframe. Could this be the reason I'm having this issue?

**Update 2:**

If you add something that says "allow" it usually implies that some additional things become allowed, and AMP makes it the other way around. I think this is confusing.

> There is one exception to this. amp-iframe uses a restrictive iframe-sandbox by default. If one does not opt into allow-same-origin, then every origin is allowed for the iframe. As soon as you add allow-same-origin to the sandbox the origin rules apply.

**Comment by jpettitt** [comment]
It's designed to stop pages breaking on the AMP caches.  If you rely on an `iframe` having the same origin as the parent page then it will break when the parent page is served from an unexpected origin, for example an AMP cache.

`allow-same-origin` allows the `iframe` document to make credentialed requests to its own origin.  Without this a sandboxed `iframes` cannot access cookies from it's real origin.  

So if `allow-same-origin` is not specified the origin of the sandboxed iframe is irrelevant because it's unique and thus isolated.  However if `allow-same-origin` is specified the sandboxed frame could make credentialed requests and access cookies. Allowing this would make it easy to create a page the works locally but fails when the origin changes to one of the AMP caches.  While this restriction can be circumvented with redirects developers who do this assume the responsibility to make sure their pages still work on the AMP cache.

Secondarily developers using `iframes` should be aware of the restrictions imposed by the upcoming [Apple ITP2](https://webkit.org/blog/8311/intelligent-tracking-prevention-2-0/). (note: this is out of scope for discussion here and we can't offer any advice on ITP2)

**Comment by AndrewKGuan** [comment]
So what is the recommended setup for a page with the following constrains: 

- must have an iframe, for example, js widgets that are hard/impossible to replicate using AMP

- a separate domain cannot be afforded due various reasons

- the AMP page could be served directly from the origin, for example, amp-as-canonical and other pages on the site points to the hosted amp.
