### ISSUE TITLE
amp-list to use/consume Link Header's?

### ISSUE THREAD

**Issue by AcidRaZor** [ampproject/amphtml#17274]
Hi,

With the implementation of a "Show More" button on amp-list, I had to make a few changes to the output of my JSON to include "hasMorePages" including keeping count of page number I'm on/requesting etc.

I was wondering if it would be possible/considered (I'm not 100% sure security-wise), that instead of having to make changes to my JSON output, if the header of the response could contain that information instead?

I'm specifically referring to (https://www.w3.org/wiki/LinkHeader):

    Pagination-Count: 100
    Pagination-Page: 5
    Pagination-Limit: 20

When AMP consumes this, it can then add it's own paging elements to the output that could be accessed in the template of amp-list.

This should give developers the flexibility to implement paging (not just "Show More") and if they already follow that standard, pretty much out of the box.

What do you guys think? Crap idea?

Cheers

**Comment by jpettitt** [comment]
So are you thinking of `Link: <https://www.example.com/...>; rel=next`(or prev, first, last)  headers on the json data response in the same way as [github does it](https://developer.github.com/v3/#pagination) ?

**Comment by aghassemi** [comment]
@AcidRaZor That's a great idea and we have started woking on a feature that has a fairly similar API to your suggestion. We are combining the concepts of "show more" and "infinite scroll" together (infinite scroll essentially being a auto trigger of show more). The API allows for specifying next page in the JSON response ( instead of HTTP response headers).

Please see https://github.com/ampproject/amphtml/issues/13575 for the design draft and follow https://github.com/ampproject/amphtml/issues/14060 for updates regarding the feature.

**Comment by AcidRaZor** [comment]
Apologies, @jpettitt , you are correct. Just read the RFC for Link Headers

**Comment by AcidRaZor** [comment]
This is what my API checks for/accepts to page:

`X-Pagination: {"totalItems":100,"pageNumber":1,"pageSize":10,"totalPages":10} `

I'm adding the Link Header responses as well, but this is the main driver
