### ISSUE TITLE
Percy still flakes with iframe-based components

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#17321]
For instance: https://percy.io/ampproject/amphtml/builds/913922?utm_campaign=ampproject&utm_content=amphtml&utm_source=github_status

`video-player` and other `iframe` based components have dynamic data inside their iframes and depending on when screenshot is take, video may be at a different frame or content inside iframe may be half-loaded etc..

I don't think there is a great technical solution for this other than telling that Percy that the area inside iframe is not to be used for comparison.

**Comment by danielrozenberg** [comment]
This specific case is something I'm actively working with Percy on. If you look at the source diff, these two files are exactly the same (except for the RTV version and the order of the CSS styles loaded from the extensions, due to unsynchronicity,) this specifically is an issue with their renderers that we're trying to figure out.

As for the iframes, right now I tried to disable all the explicitly flaky tests, if you find tests that have different content within the iframe (as opposed to cases like these, where things just don't load in time before the screenshot happens,) let me know and I'll disable them individually

**Comment by aghassemi** [comment]
@danielrozenberg https://percy.io/ampproject/amphtml/builds/913922?utm_campaign=ampproject&utm_content=amphtml&utm_source=github_status was just a flake and passed on the second run.

**Comment by danielrozenberg** [comment]
We no longer have tests for iframe based components. Closing this for now
