### ISSUE TITLE
error "No ampdoc found" reading amp from pwa in shadow dom

### ISSUE THREAD

**Issue by iwoak** [ampproject/amphtml#17328]
We load an amp-page in shadow dom from pwa by an amp-reader component, but we receive an error as soon as you open the page:

`Template failed:  [object HTMLDivElement] [object HTMLDivElement]: No ampdoc found for [object HTMLTemplateElement]`

amp page is visible and some things works fine, but we have errors after some other actions like click/tap on element with event listener like this:

`tap:audio-target.scrollTo()`

audio-target is an ours element target selector, but we have

`Uncaught (in promise) Error: No ampdoc found for [object HTMLHtmlElement]`

this is a production affected url (pwa): https://rep.repubblica.it/pwa/generale/2018/08/06/news/gas_esplosivi_benzina_e_vernici_ogni_giorno_10_mila_bombe_vaganti-203552010/

this is the relative original amp page: https://rep.repubblica.it/ws/detail/generale/2018/08/06/news/gas_esplosivi_benzina_e_vernici_ogni_giorno_10_mila_bombe_vaganti-203552010/

In the original amp page all works fine, we have noted this issue since last 3-4 days.

**Comment by gilbertococchi** [comment]
Additional Context is that it happens when the users is clicking on a#detail-audio_trigger

![screen shot 2018-08-07 at 11 11 09](https://user-images.githubusercontent.com/329023/43766474-ca2c00a2-9a32-11e8-84a7-315c155f5c47.png)

**Comment by gilbertococchi** [comment]
To emulate it's possible to force the showing of a#detail-audio_trigger by changing the visibility from Dev Tools of its ancestors and then click into the icon to reproduce.
No changes were made on the site recently so we suspect some changes in the Shadow DOM interactions here.

**Comment by gilbertococchi** [comment]
@danielrozenberg would you be able to triage and investigate?

**Comment by sparhami** [comment]
Did some debugging and found what appears to be a problem with `<amp-access>` when used in a shadow doc with this function:

https://github.com/ampproject/amphtml/blob/a5b415d3c39839c8cd3a8660a3214322d37eed22/extensions/amp-access/0.1/amp-access.js#L219-L230

The main problem appears to be that `event.target` is null when read in the `.then()`. It is not null when initially read at the start of `onDomUpdate_`. I'm not sure why that might be the case.

This works for non-shadow-v0.js since the single doc will be returned. Note that this will also have problems with `<amp-next-page>` when we fix `getAmpDoc` to return the correct `AmpDoc`.

**Comment by iwoak** [comment]
Thanks for your reply @sparhami. I removed amp-access on section tag as you suggested and however it is a good change, but I have jet the same errors in console. 

![image](https://user-images.githubusercontent.com/10278898/44844754-12efd680-ac4c-11e8-8e81-87dc50180663.png)

**Comment by sparhami** [comment]
Thanks for removing the extra amp-access. I can now see that the source of the problem lies here:

https://github.com/ampproject/amphtml/blob/4c6faff8b33a417d3e9273c7b9193351341b9888/extensions/amp-access/0.1/amp-access.js#L508-L519

When the template has been rendered for the first time, it stores the template onto the rendered element for future reference. The second time it comes through to update, it takes the stored template and calls `renderTemplate` again. However, since this is a shadow document and the `template` no longer has a parent element, trying to find the `AmpDoc` fails when it checks if it is okay to render here:

https://github.com/ampproject/amphtml/blob/4c6faff8b33a417d3e9273c7b9193351341b9888/src/service/template-impl.js#L116-L119

I'll take a look to see how this can be addressed.

**Comment by iwoak** [comment]
Thanks a lot for your explanation and for your time over this @sparhami!

**Comment by sparhami** [comment]
The "No ampdoc found for" error should no longer appear. I am unsure if all the issues are ironed out however (e.g. audio icon) since the test account I have does not appear to have an active subscription. Are there still issues that you see?

**Comment by iwoak** [comment]
Thanks a lot! We no longer have the error "No ampdoc found for" and so we can close this issue.

PS yes in this moment there are some error on audio, but they are ours and we just fixed :)
