### ISSUE TITLE
Dynamic appending HTML to DOM

### ISSUE THREAD

**Issue by trvanhai4** [ampproject/amphtml#17352]
Hi,

Currently, we're using amp-list with amp-mustache to load dynamic contents from the server side. From our experience, there are some limitations as below:
1/ The binding time is quite long, especially on the pages with multi lists
2/ To much boilerplate code => increase HTML size
3/ The APIs must be designed to conform with amp-mustache syntax

It'd be better if we have a mechanism to dynamically insert HTML from the server side. Any thoughts?

**Comment by vamshi5889** [comment]
Hi @trvanhai4 , the beauty of AMP is consuming the WEB API responses as is and decouple the client from server. 
Example, i can hit the mobile API's (android/ios) and build a same kind of client (mobile page) using AMP.
And binding time completely depends on your response payload. So, i don't think it's a good idea to insert HTML from server side.

**Comment by aghassemi** [comment]
Hi @trvanhai4 

1) If you don't need amp-bind expressions to be evaluated at load time, please set `binding=no` attribute. See https://github.com/ampproject/amphtml/blob/master/extensions/amp-list/amp-list.md#binding-optional for details.

for the rest of your points, the template definitions may increase the initial HTML load size but keep in mind that initial page is cached by AMP Caches and will be much faster than responses from you end point which would be slower if instead of simple data, you return HTML. We also need to validate the the template to make sure it is valid AMP which would be much slower to do at runtime if you return HTML (since we still need to validate your HTML) this will also stop use from server-side rendering temples (#15643).

We currently are not planning to allow insertion of arbitrary HTML from amp-list's response. We however are planning to support more flexible templating languages to allow for features such as conditional checks, index access, etc...

**Comment by aghassemi** [comment]
closing as "Intended"
