### ISSUE TITLE
amp-stick-ad 0.1 (old version) doesn't have a sourcemap

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#17518]
We build `amp-sticky-ad-0.1.js` with every release, but it's missing it's corresponding source map file. Likely something to do with the versioning?

**Comment by rsimha** [comment]
What needs to be done here? Is it a special case flow for this component? Or a more general tooling fix?

**Comment by rsimha** [comment]
This is happening because `amp-sticky-ad-0.1` is declared under `aliasBundles`, and isn't being compiled like the rest of the components.

https://github.com/ampproject/amphtml/blame/2f4630b2e9f5d27bdef0393173b8978b4be0de01/bundles.config.js#L937-L945

@erwinmombay Why was `aliasBundles` added, and do we still need it after #21190?

**Comment by rsimha** [comment]
> @erwinmombay Why was `aliasBundles` added, and do we still need it after #21190?

Found the answer. We just need to copy the `.map` file here:

https://github.com/ampproject/amphtml/blob/c4a663d0ba13d0488c6fe73c55dc8c971ac6ec0d/build-system/tasks/extension-helpers.js#L122-L136

**Comment by rsimha** [comment]
Fix ready at #22605
