### ISSUE TITLE
Google Search Console not rendering AMP

### ISSUE THREAD

**Issue by alexpetkov** [ampproject/amphtml#17516]
Google Fetch and Render (Chrome 41 engine) is not rendering AMP components correct.

**Comment by aghassemi** [comment]
@alexpetkov Thanks for the report. It is caused by the same issue as https://github.com/ampproject/amphtml/issues/17505 which we have fixed and will be releasing as a [patch](https://github.com/ampproject/amphtml/issues/17515) on production over the next few hours. 

/fyi @jridgewell Tested in Chrome 41 and error is the same, `fonts['values']` is undefined.

**Comment by aghassemi** [comment]
Closing per comment above as dup of #17505
