### ISSUE TITLE
Resizable <amp-iframe> is not resized in some cases (reproducible)

### ISSUE THREAD

**Issue by artemf** [ampproject/amphtml#17750]
## What's the issue?

I have an issue where resizable `amp-iframe` would not resize (sometimes) when the iframe is loaded.

That happens, when:
1) You scroll to the widget, it takes time to load the widget, then widget height is not updated (**reproduced after this post, see the first comment**).
2) You scroll to the widget, it gets resized correctly. Then you click "Reload" in browser with the widget in viewport. The page would reload and the widget wouldn't resize. (**reproducible**)

## How do we reproduce the issue?

Here's the host AMP page with `amp-iframe`: https://amp-iframe-bug-host.netlify.com/ (validates)
The widget which is the source of iframe: https://amp-iframe-bug-widget.netlify.com/

I use browser in "mobile" sizes, so it fits closer to the page's intended look and feel.

Note that the widget would hook on DOM ready and send size events to the host AMP page. Also it would send size events on other DOM events. For transparency, I added logging to see incoming and outgoing (size) events for the widget.

### Steps to reproduce

1. Open https://amp-iframe-bug-host.netlify.com/ in Chrome **in "iPhone 7" (or other mobile) view** (otherwise it would complain that iframe is too high on the page), scroll down to grey widget. It would be of correct 500px height. That's expected behaviour. 

Here's how this step looks, note that the iframe (grey) gets resized correctly when scrolling page from the top:

![screen recording 2018-08-28 at 06 41](https://user-images.githubusercontent.com/5671349/44734437-98f80a00-aaf2-11e8-9ce5-088f482fae10.gif)

2. Click reload. The page would reload and the widget would not be resized to 500px height, even though you can see in a console it sends the correct 500px height to the parent AMP page.

_Note: You can see in the second case the iframe is not getting some "resize" event which it gets in the first step. After the page is loaded in step 2, you can scroll up and down - the iframe wouldn't resize unless you click the iframe itself, for example._

Here's how this step looks:

![screen recording 2018-08-28 at 06 42](https://user-images.githubusercontent.com/5671349/44734467-aad9ad00-aaf2-11e8-9ff2-1bc229a9f155.gif)

## What browsers are affected?

Affected:
- Chrome on Mac
- Firefox on Mac
- Safari on Mac

Could not reproduce (not affected?):
- iPhone iOS 11

## Which AMP version is affected?

Version 1535038987988

**Comment by artemf** [comment]
Was able to reproduce case N.1 in the issue above. I added artificial delay into the iframe page, to imitate slow network / heavier page. 

How to reproduce:

1. Open https://amp-iframe-bug-host2.netlify.com/
2. Scroll through the page to `amp-iframe` loading the iframe page (https://amp-iframe-bug-widget2.netlify.com)

Expected behaviour:
3. Once the iframe page is loaded, it should resize to 500px

Actual behaviour:
3. Once the iframe page is loaded, it wouldn't resize and stay at 200px 

Demo:

![screen recording 2018-08-28 at 08 07](https://user-images.githubusercontent.com/5671349/44738721-7a980b80-aafe-11e8-9481-5d3232b8b075.gif)

**Comment by aghassemi** [comment]
Hi @artemf. This is working as intended. `resize` from an iframe is a `request` that may not be honored if it adversely impact UX by causing content shifting on the page.

Per: https://www.ampproject.org/docs/reference/components/amp-iframe#iframe-resizing

Once this message is received, the AMP runtime tries to accommodate the request as soon as possible, but it takes into account where the reader is currently reading, whether the scrolling is ongoing and any other UX or performance factors. If the runtime cannot satisfy the resize request,
the `amp-iframe` will show an `overflow` element. Clicking on the `overflow` element will immediately resize the `amp-iframe` since it's triggered by a user action.

Here are some factors that affect how fast the resize will be executed:

- Whether the resize is triggered by the user action.
- Whether the resize is requested for a currently active iframe.
- Whether the resize is requested for an iframe below the viewport or above the viewport.

So in you example, if the bottom iframe is not in the viewport, it will resize, it not, it will fail. It is important to specify a `<div overflow>` button inside your `amp-iframe` to allow the user to manually expand it in the failure case.
