### ISSUE TITLE
amp-story: INI_LOAD appears to fire after 5s timeout

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#17757]
While working on #17756 we discovered that sometimes we were getting several clicks through a story before the `INI_LOAD` signal has fired. Need to investigate further.

**Comment by calebcordry** [comment]
cc/ @lannka @newmuis

**Comment by lannka** [comment]
This bug can be reproduced in Search Viewer (searching for "CNN" for instance) clicking on the 1st story result.

The symptom is that ad gets scheduled very late because INI_LOAD on the story didn't fire until timed out [after 5s](https://github.com/ampproject/amphtml/blob/4b868aa9bd2d2aa6b922b785c4ca4f71ab31c15a/extensions/amp-story/1.0/amp-story.js#L719).

The root cause can be this [line of code](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/amp-story-page.js#L336):
```
          case 'amp-img':
          case 'amp-anim':
            mediaEl.addEventListener('load', resolve, true /* useCapture */);
            break;
``` 

We're waiting for the 'load' events from `amp-img` which can happen before `amp-story` extension gets loaded, hence missed them.

Not sure for what reason the bug happens more often in pre-render mode. 

For the fix, we might want to introduce a 'load' signal to `amp-img` and all those [media tags](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/amp-story-page.js#L70).

**Comment by lannka** [comment]
Marking it as P1 as it's blocking the AMP ads launch. 
@jasti FYI

**Comment by lannka** [comment]
Actually, it's debatable if this is launch blocking after #17756 is fixed. The impact of the bug is a 5s delay  of the 1st ad load.

**Comment by gmajoulet** [comment]
Does #17756 fix the navigation issue? Right now, a user is stuck as they tap through a story when the bug mentioned on this ticket happens.

**Comment by lannka** [comment]
Yep, it should fix the navigation.

**Comment by lannka** [comment]
Discussed offline. The INI_LOAD signal of story is only used by ads. Deprioritize it to P2, given the current impact is a 5s delay of ads load for pre-rendered stories.

**Comment by gmajoulet** [comment]
@lannka Do you have a way to reproduce it locally? We have a couple ideas of how to fix it but aren't sure how to test it

**Comment by jasti** [comment]
@lannka to clarify, in the best case scenario, ads will trigger 5 seconds after the user starts to consume the story? In which, I'd still mark this as P1.

**Comment by newmuis** [comment]
@jasti It's the worst case scenario, not best.

We'll be taking this work on in the upcoming sprint, so I'm not certain the priority matters much beyond "not P0" 😃

**Comment by lannka** [comment]
@gmajoulet I have an idea to reproduce the issue locally:

- add some latency (e.g. 2s) to `amp-story.js` on your local server, to make sure `v0.js` is running before `amp-story.js`. 
- print console log with timestamp in `amp-img` layoutCallback
- print console log with timestamp when story INI_LOAD is fired

We should see INI_LOAD firing right after `amp-story.js` load.
But because of the bug, we will see it firing about 5s after `amp-story.js` load.
