### ISSUE TITLE
[gestures] gestures break if interrupted mid-gesture

### ISSUE THREAD

**Issue by kevinkassimo** [ampproject/amphtml#17796]
## What's the issue?

For components relying on `Gesture` library and uses `Swipe[XY]Recognizer/PinchRecognizer`, on operations such as lock screen, (or switching desktops for simulation), the handler no longer triggers.

For example, in `amp-image-slider`, while still holding down finger to move the slider, if you turn off the screen using side button (or switch desktop using keyboard during simulation) and lift your finger, when you come back to the page, the slider could no longer be moved by moving the touch position.

![gesture-bug-1](https://user-images.githubusercontent.com/15007517/44870649-a245bb80-ac45-11e8-822a-38ae1c4b4961.gif)

Another example, in `amp-image-lightbox`, normally you could swipe up/down to close the lightbox. However, during things similar to above, the swipe could no longer be triggered.

![gesture-bug-2](https://user-images.githubusercontent.com/15007517/44870720-ca351f00-ac45-11e8-93a0-1074f34c69f2.gif)

Currently, the bug is confirmed to impact components including `amp-image-slider`, `amp-image-lightbox`, `amp-pan-zoom`, `amp-story` (for showing touch hints). It would also probably (not yet tested) impact `amp-lightbox-gallery` and `amp-lightbox`.

## How do we reproduce the issue?

Follow the steps mentioned above.

## What browsers are affected?

All.

## Which AMP version is affected?

Should have been a long existing issue.

**Comment by cathyxz** [comment]
This problem applies more generally to the case where a gesture is interrupted by a touch or unlayout mid-gesture.

**Comment by ericlindley-g** [comment]
Thanks for digging into this, @kevinkassimo 

 /cc @aghassemi 

In testing folks seemed to observe that attempting 3-finger pinch-zoom would also trigger this (i.e. two fingers initiate pinch gesture, third finger falls and interrupts the gesture). Since the use-case for amp-pan-zoom is directly tied to similar gestures, it stands to reason that folks could run into this issue more often for amp-pan-zoom than for other components (even though amp-lightbox-gallery supports zoom, it does so as a secondary feature). This is why, even though we haven't seen this bug reported for other components, it might be worth taking time to fix for amp-pan-zoom.

How much work would we expect it would take to address the issue?

**Comment by andrewwatterson** [comment]
This is one of those things that you can't really reason about until you can feel it, but my instinct is that @cathyxz's proposal is the right way to go.
