### ISSUE TITLE
(element).scrollTo button causes "No ampdoc found" error in AMP Shadow

### ISSUE THREAD

**Issue by mattwomple** [ampproject/amphtml#17792]
## What's the issue?

When an element is used for `.scrollTo` (e.g. `tap:top-scroll.scrollTo()`) in an AMP page, tapping that element results in `Uncaught (in promise) Error: No ampdoc found for [object HTMLHtmlElement]` when the AMP page is viewed in an AMP Shadow.

## How do we reproduce the issue?

I've created a minimal example with a scroll to top button. Scroll down the page to reveal the scroll-to-top button on the right side of the screen (you may need to decrease the height of your browser window, sorry). Tapping that button works fine for the bare AMP page, but results in an error (and no scroll action) when that AMP page is viewed in an AMP Shadow.

- AMP Page: https://cmphys.com/amp-svg-scrolltop.html
- AMP Page viewed in Shadow AMP: https://cmphys.com/amp-svg-scrolltop-shadow.html

## What browsers are affected?

I've reproduced this issue in the following browsers:

- Mozilla/5.0 (Linux; Android 7.0; Moto G (5) Plus Build/NPNS25.137-93-14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36
- Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

## Which AMP version is affected?

1535566825959

**Comment by mattwomple** [comment]
I believe I misidentified this bug as being related to SVG. Any character (e.g. `X`) in the `#scrollToTopButton` element will cause this issue to appear. I will update the original report.

**Comment by sparhami** [comment]
The problem is here:

https://github.com/ampproject/amphtml/blob/5f75efe35b734a4fcf0884d373315de60cd42df9/src/animation.js#L200

https://github.com/ampproject/amphtml/blob/5f75efe35b734a4fcf0884d373315de60cd42df9/src/service/vsync-impl.js#L283-L286

Before animating the scroll on the scrolling element (the `<html>` element), it tries to get the `AmpDoc` to check if it is visible. This throws an error since there is no `AmpDoc` for `<html>`, since the element lives outside of any AMP document.

**Comment by mattwomple** [comment]
`.scrollTo` has been broken in PWAs for between 2-3 months now. I'd like to bump this issue because there has been a patch waiting for review since the first day this issue was reported. Would someone mind giving pull request #17804 some attention -- even if it is just to say "not ready"?
