### ISSUE TITLE
AMP shadow not loading AMP components correctly in angular 6 app on 2nd AMP page

### ISSUE THREAD

**Issue by mathisobadia** [ampproject/amphtml#17833]
**Please only file bugs/feature requests for AMP here.**

- If you have questions about how to use AMP or other general questions about AMP please ask them on Stack Overflow under the AMP HTML tag instead of filing an issue here: http://stackoverflow.com/questions/tagged/amp-html
- If you have questions/issues related to Google Search please ask them in Google's AMP forum instead of filing an issue here: https://goo.gl/utQ1KZ

If you have a bug or feature request for AMP please fill in the following template.  Delete everything except the headers (including this text).

## What's the issue?

Using the AMP shadow API in an angular app, the AMP document is loaded correctly the first time with all AMP components functional, but AMP components (e.g. amp sidebar) are not working anymore when loading a 2nd AMP document. 

## How do we reproduce the issue?

this reduced [test case](https://stackblitz.com/edit/angular-ztgihj) shows the issue: [https://stackblitz.com/edit/angular-ztgihj](https://stackblitz.com/edit/angular-ztgihj)

Step 1: The first document is loaded on Angular component initialization (onInit function) See that sidebar is functioning properly.
Step 2: Click on the reload button at the bottom of the page. The amp Document is closed then loaded a 2nd time.
Step 3: See that the amp sidebar is not functioning properly anymore.

This is probably an angular issue as the same code produces no error when using vanilla js ([see this example](https://stackblitz.com/edit/js-hxajh5)) and only happens when loading a new AMP document inside the same angular component (routing to a new angular component then using the same function in the new component produces no error). So if this repository is not the right place to discuss this issue I am sorry

## What browsers are affected?
Latest versions of Chrome and Firefox. The angular version is angular 6.0.0

## Which AMP version is affected?

HTML shadows – Version 1535566825959

**Comment by kevinkassimo** [comment]
Looks like it was caused by the following assumption:
https://github.com/ampproject/amphtml/blob/e5a2b981af4bc74b4946783d1c916d1f7ee1a5e3/src/style-installer.js#L143-L152
Essentially, the original `styleMap` is preserved across shadowRoot replacement, while the style map is not cleared. Therefore, after refresh and during reinstalling the elements, AMP would found that cached style and falsely believe that we have already inserted the style tags - the one we inserted are actually gone at that time.

Will discuss with team members to see if could make a fix for this
