### ISSUE TITLE
amp-bind escapes new lines in strings

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#17863]
Inconsistent string escaping behavior with amp-bind. This will escape the new line char:
```
<button type="button"
  on="tap:AMP.setState({formState: {message: formState.message + '\nSome another text' } })">
  Button
</button>
```
but this wont:

```
<amp-state id="formState">
  <script type="application/json">
  {
    "message": "Some text",
    "newLine": "\n"
  }
  </script>
</amp-state>

 on="tap:AMP.setState({formState: {message: formState.message + formState.newLine + 
```
see also: https://stackoverflow.com/questions/52136567/how-to-dynamically-add-a-new-line-to-the-string-stored-in-the-amp-state

//cc @choumx

**Comment by choumx** [comment]
Thanks for the report.

**Comment by westonruter** [comment]
Possibly related: #22265.

**Comment by choumx** [comment]
This is because the expression parser builds string tokens one character at a time, and won't generate special string chars like line breaks etc. 

This is not an issue for amp-state which processes special chars since it just does `JSON.parse(element.textContent)`.

We can replicate this behavior for amp-bind expressions.
