### ISSUE TITLE
amp-analytics scroll - provide a sampled series of scroll positions over time (batched)

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1797]
cc @cramforce

**Comment by dpup** [comment]
Per email conversation there are two parts of this request.

1. Scroll position sampled based on distance moved and/or time since last sample (i.e. debounce).
2. Reporting rate, which would often mean multiple samples get reported in a single batch.

Sampling would allow for detection of moving up and down through the document, so not threshold based.

**Comment by rudygalfi** [comment]
cc @michaelkleber on the issue we were discussing earlier

**Comment by julien51** [comment]
I'd love to see this happening. I understand that getting all "scrolls" posted is not trivial and may likely create a lot of events. in the same vein as the %age based scrolls inside the doc, do you think we could have something like every X pixels? 

The main problem with %ages for is that this may create overlong period without events during which we would consider the user as inactive while she is, in fact, active.

**Comment by rudygalfi** [comment]
Would pixel-specified boundaries on the existing `scroll` feature be sufficient (i.e. batched scrolling data proposed in this issue wouldn't be necessary)?

I'd be fine with augmenting the amp-analytics spec to enable a pixel-based definition instead of %-based. We would need to establish a minimum interval between the boundaries.

@cramforce @avimehta Do you think there's a way to make this work and still have good performance? And what would that minimum interval be?

**Comment by avimehta** [comment]
@julien51 I am not sure I understand the disadvantage of % based scroll events. If the approximation to nearest 5% the cause of missed data? or is it something else? 

As for the sampled scroll data, I think it is probably useful to provide this. What format and what kind of configuration to support is an open question. Can you give examples of how the data would look on a page for https://github.com/ampproject/amphtml/issues/1797#issuecomment-180105366?

**Comment by julien51** [comment]
Sorry for the delay,
The problem with scroll based events is that they become "too rare" when the document is large enough and we will "miss data".

We need to have a TTR event pushed to us every 30 seconds if there has been any scroll in that time frame, otherwise we consider the user inactive. If reading the document takes more than 10 minutes, at least one 5% increment will be triggered more than 30 seconds after the previous one... generating a timeout on our end.

By order of preference:
* Batch events for all scroll events would be the best.
* distance/pixel based events would come second (like every X pixels)

Thanks!

**Comment by rudygalfi** [comment]
Closing this out. Ideally we'll have a partner who's interested in this to help us drive the spec and test it. Until then, we'll defer doing this.
