### ISSUE TITLE
check package manager should have --cli mode

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#17984]
when we're building the amp runtime through a script or automated process it hangs on the check-package-manager checks if it fails globalGulp and yarn version checks. if --cli is passed in it should just fail with the commands to fix instead of haulting and waiting or at least there should be a reasonable timeout.

cc @cathyxz

**Comment by rsimha** [comment]
Some context: This used to be just a warning, but it turned out that people would ignore it because the associated gulp task would immediately begin, and scroll way past the warning message. Currently, you can just hit enter and continue running the gulp task, or hit ctrl + C and cancel, in order to fix.

For automated processes, I agree this is a bad experience. Continuing after a timeout is a great idea. Will do!
