### ISSUE TITLE
Separate analytics vendor config to different files

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#18034]
cc @lannka @torch2424

**Comment by harshvcs** [comment]
@zhouyx 
Considering that each amp-analytics vendor has a corresponding \<vendor>.js file, is it possible to add JavaScript to the configuration file to allow mapping the AMP [variable](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#variables) value to a custom value?

In short, is something like below possible/allowed and will it work?

```js
let mapVar = ${variable};
if (mapVar === 'something') {
    mapVar = 'else';
} 

export const VENDOR_CONFIG = /** @type {!JsonObject} */ ({
  'vars': {
    'var': mapVar,
  },
  'requests': {
  },
  'triggers': {
  },
  'transport': {
  },
});
```

Alternatively, is it possible to to allow 1-1 vendor-specific mapping of output generated from AMP variable(s)? This will simplify vendor downstream processes that expect a specific value.

**Comment by zhouyx** [comment]
Hello @harshvcs 

So I understand you want to perform the mapping after the variables are resolved.We already have some macros support that may help you solve the problem. Apology for not having documentation yet. Here's the list of macros, let me know if they work for you. Thank you

https://github.com/ampproject/amphtml/blob/99d8eac351a94119233295dfda497b0b31b3967f/extensions/amp-analytics/0.1/variables.js#L153-L164

**Comment by harshvcs** [comment]
Thanks @zhouyx 

That's right. The information is helpful though I am not able to use the available macros to map cases where there are two or more possible output string values. The `$IF` macro is a good start, but its first argument has to be a boolean, so that isn't very useful for cases where a comparison of `${variable}` string is required. The `$REPLACE` macro will only apply if a single output string has to be mapped. To resolve multiple output string mapping, most of the vendors I believe will require something that checks for equality - say a new `EQUALS` macro (that returns a===b) along with the existing `$IF` macro. Assuming `$EQUALS` is added, then a required mapping like "A" -> 1, "B" -> 2, "C" -> 3 can be solved using: 

```js
$IF($EQUALS({variable}, A), 1, $IF($EQUALS({variable}, B), 2, 3));
```

Could you please add an `EQUALS` macro or suggest an alternative if something already exists to resolve the multiple output string mapping?

**Comment by zhouyx** [comment]
Thank you @harshvcs for the suggestion. Yes I can see the `EQUALS` macro to be very helpful. We can definitely add it.

Add @calebcordry to provide more context on if this type of nested macros is supported. 

As a workaround, you can still use $REPLACE

```
$IF($REPLACE(${variable}, A, ''), $IF($REPLACE(${variable}, B, ''), 3, 2), 1)
```

I know this is not straightforward. We're definitely planning to add `EQUALS` support.

**Comment by harshvcs** [comment]
@zhouyx: Is there an open ticket that I can follow to check when the EQUALS macro will be available? Thanks!

**Comment by zhouyx** [comment]
@harshvcs Thank you for following up. The entire team is traveling for the AMP Conf this week. 

I don't think there's one, feel free to create one and reference it here. Thank you very much.
