### ISSUE TITLE
FR: Allow Url hash to be changed via amp-position-observer events.

### ISSUE THREAD

**Issue by TWsky** [ampproject/amphtml#18049]
## What's the issue?

A behavior I would like to achieve is as [this page](https://campaign.simpleskincare.tw/Kind-to-Skin/#product_1), after this page reload, let the viewport scroll back to the anchor(#) point (for browser default behavior, it will remember the last position user scrolled & stopped at there after page reload, rather than the url anchor(#) id element).

I try to use <amp-position-observer on="enter:top1.scrollTo(duration=200) /> to scroll to the top of the page, and discovered that the enter event doesn't support scrollTo action.
<img width="879" alt="screen shot 2018-09-13 at 3 05 40 pm" src="https://user-images.githubusercontent.com/4546841/45528798-8ed54b80-b814-11e8-8952-07e611c00604.png">

Two questions here:
- Is there a reason why we don't support _scrollTo_ with _enter_? If no, then it would made this issue a feature request.
- Is there a way for implementing the expected AMP behavior as I described above? Saying it broadly, is there any method of reading the page url and using it's anchor or query string to animate the page (without a manual user interaction i.e. tap). Since it will be more flexible for developers to do some UI flow behavior which they can not use Javascript here.

## How do we reproduce the issue?

Go to [here](https://amp-spa.firebaseapp.com/ampPositionObs/)
1. Scroll down to the paragraph "When Sees me, scroll back to Top1"
2. Expecting it to scroll back to top, but nothing happens

## What browsers are affected?

tested on Chrome 69.0.3497.81

## Which AMP version is affected?

Used AMP Version 1809122303360

**Comment by aghassemi** [comment]
Thanks for the report @TWsky.

AMP has the concept of high-trust and low-trust events and actions. Events that do not carry strong user-intent (e.g. position-observer events) are considered low-trust and can only run actions that are not considered disruptive. In this case `enter` is low-trust (as intended) and `scrollTo` is high-trust (arguable but it is a fairly disruptive action).

That being said, we should do something to support your use-case as there is precedence for it in browsers using `hash`.

Ideally you change the `url hash` as user scrolls to different areas of the page so that Url is more accurate and you won't need to call `scrollTo` anymore as browser will handle it for you on reload.

I have updated the title of the issue to request adding a new `low-trust` action to allow for Url `hash` change.
