### ISSUE TITLE
Too many errors 404 related to ads and 2 more about amp-list included js and mustache

### ISSUE THREAD

**Issue by theroot79** [ampproject/amphtml#1825]
Test area: [http://mob.frognews.bg/#development=1](http://mob.frognews.bg/#development=1)

`<amp-ad type="adsense" ... ` causes a lot of 

> The response had HTTP status code 404

 errors , 
and also:
> The attribute 'src' in tag 'amphtml engine v0.js script' is set to the invalid value... 

which is absolutely strange.

**Comment by cramforce** [comment]
Switch
`<script src="https://cdn.ampproject.org/v0/amp-list-latest.js" custom-template="amp-list" async></script>`
to
`<script src="https://cdn.ampproject.org/v0/amp-list-latest.js" custom-element="amp-list" async></script>`

and it validates.

I'm assuming you are seeing the errors in Safari? Those are due to a polyfill for `<link rel=preconnect>` that we developed. It greatly improves load time for the ads.

**Comment by theroot79** [comment]
Yes, thank you all , all AMP-LIST errors are gone now.
I see all 404 errors on Chrome browser / Windows 10 x64

**Comment by cramforce** [comment]
Please attach a screenshot.

**Comment by theroot79** [comment]
[http://imgur.com/EGaI6tr](http://imgur.com/EGaI6tr)

**Comment by cramforce** [comment]
Ah, that is because you set the user agent to an iPhone. We sadly cannot detect whether this is needed by anything else but looking at the user agent.

Someone else was suggesting to change the URL to something like `/preconnect_polyfill_dont_worry_about_404.html` :)
Maybe we should do that. Would that have helped you?

**Comment by theroot79** [comment]
Yes, once I switched the browser back to Desktop mode all errors are gone, thank you for the fast response.
