### ISSUE TITLE
amp-3d-gltf: Expose seekToX/Y/Z(percent) method

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#18276]
@mixtur would it be possible for `amp-3d-gltf` to expose a `seekTo(percent)` for each axis? 
This would allow integration with `amp-position-oberserver` and `amp-orientation-observer` for some cool scrollbound and tilt-based experiences.

For instance see how `amp-position-observer` can be used with animations (or anything that exposes `seekTo(percent`): 

https://ampbyexample.com/visual_effects/basics_of_scrollbound_effects/ 
https://codepen.io/aghassemi/pen/jxvzzq

I think `amp-3d-gltf` is a great candidate for this sort of effect.

amp-orientation-observer is similar but based on title instead of scroll: https://codepen.io/nainar92/project/full/XwzYOd/

**Comment by aghassemi** [comment]
@mixtur sorry for the delay. Exactly!!! All we need is 3 actions. `seekXTo(percent)`, `seekYTo(percent)`, `seekZTo(percent)` then `amp-position-observer` can move the items as user scroll.

We are also considering adding `<scroll-freeze>` (#18706) component in AMP soon which similar to `amp-position-observer` can trigger scroll-based behaviour. 

Would be super cool to have this for `amp-3d-gltf`! `amp-animation`, `amp-bodymovin-animation` both have this.

**Comment by mixtur** [comment]
btw none of the demos here https://codepen.io/nainar92/project/full/XwzYOd/ worked for me.

- I am not a native English speaker, but `seekTo` sound to me like there is some kind of time based animation in play. Which is the case for both `amp-bodymovin-animation` and `amp-animation`.
And something like that is actually supported by gltf format. But not by amp-3d-gltf. Yet. So when it will be naming may become confusing.
- Another issue is that angle range better be adjustable. I hoped I could achieve that with amp-state + some math in binding, but it seems you can't change state on scroll.
- Every call will send separate message so if someone will want to change rotation on multiple axises at the same time, 3p side may handle it on different animation frames (unless messages are batched). I am not sure if that will look ok or not, but it doesn't sound right to me.

With everything above considered I suggest this API instead:

`setModelRotation(x, y, z, xMin, xMax, yMin, yMax, zMin, zMax)` with default values for every argument.
x y z - are 0..1 floats. defaults to 0
min/max - are radians. defaults to 0 and pi * 2
So real world usages would likely be something like
`setModelRotation(y=event.scroll)` or
`setModelRotation(y=event.scroll, z=event.scroll, zMin=6.59, zMax=5.96)`
 

a few additional notes
- y axis is what you expect it to be but x/z are not. It may be confusing. That is because camera positioned the way it is. It can be helped if we'll also expose initial camera position via some attribute(s)
- negative numbers are not supported in action arguments. So right now you can't say `setModelRotation(y=event.scroll, yMin=-0.1, yMax=0.1)` you can work around that by adding 2 * pi to both numbers but still it is weird.

**Comment by aghassemi** [comment]
@mixtur Good point about naming, it actually doesn't need to be called `seekTo`. `rotate`  or `setModelRotation` is fine ( personally I like `rotate(x, y, z, xMin, xMax, yMin, yMax, zMin, zMax)` )

We can expose `rotate` action a `LOW_TRUST` so it can be called by scroll.

So we don't give absolute values for `onscroll` event of `amp-position-observer`. We give a `percentage` which essentially says how far an element is between the start and end of the viewport (so when it comes to the viewport, we fire `0%` all the way to `100%` when it exits). 

Looks like your API expects values between 0 and 1 anyway, so it is just a matter dividing the values given by `onscroll` by 100.

(https://codepen.io/nainar92/project/full/XwzYOd/ only works on mobile phones is it relies on Browser's orientation observer)

**Comment by mixtur** [comment]
`rotate` sounds to me like "add rotation to existing rotation".
Also there are many things that could be rotated. Namely model, scene and camera. Therefore `setModelRotation`. Though I agree that `rotate` is more consice.

> Looks like your API expects values between 0 and 1 anyway, so it is just a matter dividing the values given by onscroll by 100.

Umm... maybe I am doing something wrong, but this
```html
<amp-position-observer on="scroll:bottle.setModelRotation(z=event.percent, zMin=6.59, zMax=5.96)"
                       intersection-ratios="0.6"
                       layout="nodisplay">
```
already gives me values between 0 and 1 in `z`. So I didn't had to divide anything.

> (https://codepen.io/nainar92/project/full/XwzYOd/ only works on mobile phones is it relies on Browser's orientation observer)

I tried Chrome/Xiaomi Redmi 2 and Safari/Iphone 6. both didn't worked for me. It seems images are missing in project. Maybe that is the reason.

**Comment by mixtur** [comment]
`rotate` sounds to me like "add rotation to existing rotation".
Also there are many things that could be rotated. Namely model, scene and camera. Therefore `setModelRotation`. Though I agree that `rotate` is more consice.

> Looks like your API expects values between 0 and 1 anyway, so it is just a matter dividing the values given by onscroll by 100.

Umm... maybe I am doing something wrong, but this
```html
<amp-position-observer on="scroll:bottle.setModelRotation(z=event.percent, zMin=6.59, zMax=5.96)"
                       intersection-ratios="0.6"
                       layout="nodisplay">
```
already gives me values between 0 and 1 in `z`. So I didn't had to divide anything.

> (https://codepen.io/nainar92/project/full/XwzYOd/ only works on mobile phones is it relies on Browser's orientation observer)

I tried Chrome/Xiaomi Redmi 2 and Safari/Iphone 6. both didn't worked for me. It seems images are missing in project. Maybe that is the reason.

**Comment by aghassemi** [comment]
You are right it does return 0..1. also correct, images are missing from https://codepen.io/nainar92/project/full/XwzYOd/

**Comment by aghassemi** [comment]
This has been launched and can be used to created scrollbound 3D models like: https://codepen.io/aghassemi/pen/GwWKoB
