### ISSUE TITLE
amp-video: auto advance after a video has ended (feature request)

### ISSUE THREAD

**Issue by nhunsaker** [ampproject/amphtml#18291]
I'm working on a project where we want to advance from one video to the next similar to this example:
https://www.buzzfeed.com/videos

<img width="1133" alt="banners_and_alerts_and_buzzfeed_videos" src="https://user-images.githubusercontent.com/3289500/45970129-b8a42480-c003-11e8-9982-c2feb976d8ea.png">

Unfortunately I don't see way to auto-advance from one video selection to another in amp without using a story. Do you have any recommendations?

Ideally I'd like to do something like this:
```
<amp-video-playlist width="450" height="300" auto-advance="true">
  <amp-video src="videos/video1.mp4" width="450" height="300"></amp-video>
  <amp-video src="videos/video2.mp4" width="450" height="300"></amp-video>
  <amp-video src="videos/video3.mp4" width="450" height="300"></amp-video>
</amp-video-playlist>
```

Or:
```
<amp-carousel width="450" height="300">
  <amp-video id="one" src="videos/video1.mp4" width="450" height="300" auto-advance-after="one"></amp-video>
  <amp-video id="two" src="videos/video2.mp4" width="450" height="300" auto-advance-after="two"></amp-video>
  <amp-video id="three" src="videos/video3.mp4" width="450" height="300" auto-advance-after="three"></amp-video>
</amp-carousel>
```

Or:
```
<amp-carousel id="my-carousel" width="450" height="300">
  <amp-video src="videos/video1.mp4" width="450" height="300" on="ended:my-carousel.goToSlide(index=1)"></amp-video>
  <amp-video src="videos/video2.mp4" width="450" height="300" on="ended:my-carousel.goToSlide(index=2)"></amp-video>
  <amp-video src="videos/video3.mp4" width="450" height="300" on="ended:my-carousel.goToSlide(index=0)"></amp-video>
</amp-carousel>
````

For reference, I read through this issue which explains why some video events are not exposed for 
https://github.com/ampproject/amphtml/issues/8971

**Comment by ericlindley-g** [comment]
Relates to some discussions @aghassemi and I were chatting about with a developer yesterday, as well as a project that @alanorozco has been thinking about.

At the moment, this functionality isn't directly supported outside of amp-iframe, in part because we can't trust that a user reaching the end of a video is a high enough trust event to hook into amp-bind. 

However, I believe one option for making this possible would be to put a custom video player inside of amp-video-iframe (when that component is launched) — another could be a new custom component or enhancement to amp-carousel as you note here, @nhunsaker.

**Comment by jerryluk** [comment]
Wondering if there is any solution to this. Is there an example how to use amp-video-iframe to do this or is there a new custom component which can handle this? (Or how to develop such component)
