### ISSUE TITLE
Perform Visual Diff Tests on CDN and Origin pages

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#18446]
Context: https://github.com/ampproject/amphtml/pull/18419

The `display: none` bug wasn't caught during review because I forgot to test AMP docs that have Server Side Rendering through the AMP Cache CDN. Having the visual diff tests run on both the origin pages (eg, https://www.ampproject.org/) and the CDN pages (eg, https://www-ampproject-org.cdn.ampproject.org/c/s/www.ampproject.org) might have caught it before we shipped it to 1% canary.

**Comment by rsimha** [comment]
@jridgewell does the `localhost:8000` dev server support CDN pages?

/cc @alanorozco @torch2424

**Comment by rsimha** [comment]
To answer my own question, it appears this can be done by passing `--cdn` to `gulp serve`, or by switching the mode at runtime by navigating to `http://localhost:8000/serve_mode=cdn`. (The latter way may work best, since the server is already running during visual tests.)

https://github.com/ampproject/amphtml/blob/master/contributing/TESTING.md#serve-mode

@danielrozenberg Maybe we can try this for one or two relevant tests? 
@jridgewell Which tests do you think would've caught #18419?

**Comment by torch2424** [comment]
@rsimha I think the dev server does support them, but I'll let Alan give the final 👍

**Comment by rsimha** [comment]
@jridgewell Is this issue still relevant?

- Do the real-world visual tests alleviate this problem?
- Does the ability to manually run `gulp visual-diff --config canary` help?

**Comment by rsimha** [comment]
_[Infra triage]_ Closing this issue as stale. Please reopen if required.
