### ISSUE TITLE
Scroll event flicker on position:sticky element in Safari iOS

### ISSUE THREAD

**Issue by addy5** [ampproject/amphtml#18469]
Similar to issue: https://github.com/ampproject/amphtml/issues/10343

When there is an element with `position: sticky`, and user scrolls down on the page, the sticky element is a few pixels behind -being partially scrolled out of view, and eventually flickers back to the correct position when the scrolling is halted.

The same conditions as the linked issue above (Safari iOS only), but `position: sticky`.

## How do we reproduce the issue?

- Visit this page on Safari iOS: https://www.google.com/amp/s/weecare.co/amp/daycare/happy-saplings-treehouse 
- scroll below the fold + watching the nav that will "sticky".
- observe the flicker issues
- scrolling back up (to bring the amp sticky nav), makes the issue a little more apparent

**Comment by jridgewell** [comment]
Hi @addy5,

So this is a core issue with trying to scroll an iframe in iOS. We actually have several technical articles about approaches to solve this ([1](https://medium.com/@dvoytenko/amp-ios-scrolling-and-position-fixed-b854a5a0d451), [2](https://hackernoon.com/amp-ios-scrolling-and-position-fixed-redo-the-wrapper-approach-8874f0ee7876), [3](https://medium.com/@dvoytenko/amp-ios-scrolling-redo-2-the-shadow-wrapper-approach-experimental-3362ed3c2fa2)).

Unfortunately, there's no way to easy fix this for `position: sticky` elements ☹️.  Because sticky-positioned elements depend on the surrounding content to give them their initial position (until they hit the sticky condition), we cannot do the "transition element to fixed-layer" hack we do with `position: fixed` elements. Further, we're actually looking to reduce the number of elements that can be transferred, because it's so fraught with other bugs.

I think the best we can do at this point is to get Apple to prioritize iframe scrolling in Safari. We have a long standing but at https://bugs.webkit.org/show_bug.cgi?id=149264.

**Comment by addy5** [comment]
thank you for the response and thorough breakdown @jridgewell
