### ISSUE TITLE
What is the issue when open amp stories in mobile version and desktop version

### ISSUE THREAD

**Issue by siddiqrahman** [ampproject/amphtml#18499]
![af50eeec-61dd-4184-9ec4-5ad5107b70b1](https://user-images.githubusercontent.com/43777424/46341651-5fb53b80-c656-11e8-88d0-edecb05b6b32.jpg)
![070fb472-2505-48f9-94db-6b7c504c6e64](https://user-images.githubusercontent.com/43777424/46341652-5fb53b80-c656-11e8-9ba0-c3d015fec3a7.jpg)

**Comment by newmuis** [comment]
Thanks for the report @siddiqrahman.  It's definitely intended for Chrome mobile to work.  It's would be very helpful if you could share the following:

- Your Chrome version
- Your device
- What version of `amp-story` you are using

**Comment by siddiqrahman** [comment]
it's not for only chrome, it's not working in firefox also, 
 

- chrome Version 69.0.3497.100 (Official Build) (64-bit)

- device, all device, like Samsung , appo, xiaomi

- amp_story version 1809142227020

**Comment by newmuis** [comment]
Is this amp-story-0.1.js or amp-story-1.0.js?

**Comment by siddiqrahman** [comment]
0.1.js

**Comment by newmuis** [comment]
The first screenshot is not expected.  Chrome should be supported, so I'm not sure why you are getting this screen.

However, it's strongly encouraged that you use version 1.0 of amp-story.  The second screen is due to the fact that using version 0.1 requires whitelisting your domain.  However, the whitelist has been closed (since July), as version 1.0 does not require whitelisting.

**Comment by newmuis** [comment]
Closing this issue since it's based on the deprecated v0.1; feel free to reopen if necessary.
