### ISSUE TITLE
[amp-pan-zoom] reset-on-resize miscalculates dimensions with padding

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#18501]
`amp-pan-zoom` supports `reset-on-resize` attribute that should help resizing when rotating with different landscapes.
Try to open this [page](https://amp-demos.glitch.me/seatmap2.html ) in portrait mode, then rotate to landscape and the corners are cut. Attached screenshot made on iPhone 7.
![seatmap-landscape](https://user-images.githubusercontent.com/820891/46348543-33de8980-c647-11e8-842e-fab8b99097e6.jpg)

@cathyxz FYI

**Comment by cathyxz** [comment]
The issue here is with the `padding-top: 30px`. After you shift from portrait to landscape mode, it fits if you adjust `padding-top` to something like `38px`. If you remove `padding-top: 30px`, it doesn't have the same problem either. Or if you straight up add `padding: 30px`. 

The`<amp-pan-zoom>` element works with aspect ratios. Adding padding forces the `<svg>` element to shrink within the defined width and height, so static padding might not play nice when the aspect ratio changes from being confined by width to confined by height or vice versa.

**Comment by kul3r4** [comment]
Thanks for explaining! What is the alternative when a space around is
needed?

**Comment by cathyxz** [comment]
Can you pad both width and height? You can probably play with the values to find some that work with your content aspect ration + amp-layout dimensions combination

**Comment by cathyxz** [comment]
Alternatively, try changing your svg `preserveAspectRatio` value to "meet" instead of "slice". https://codepen.io/jonitrythall/post/preserveaspectratio-in-svg

**Comment by cathyxz** [comment]
Here's a static repro: https://codepen.io/cathyxz/full/aRNdbO/ that shows the SVG shrinking if you toggle between portrait and landscape mode a few times. Details added to comment above.

**Comment by kul3r4** [comment]
Thanks for the detailed explanation.
I am not sure what is the best way of documenting this, I have made an attempt in #18560 .

**Comment by cathyxz** [comment]
There are two separate things here. 1 is the usage of the `SVG` `preserveAspectRatio` property, and 2 is a bug in `<amp-pan-zoom>` that I isolated here https://codepen.io/cathyxz/full/aRNdbO/ and am fixing in https://github.com/ampproject/amphtml/pull/18557. It's not necessarily the case that all SVG users inside `<amp-pan-zoom>` will want to use meet instead of slice (even though meet is usually the default property and has slightly more intuitive behaviour). 

After investigating and updating https://github.com/ampproject/amphtml/issues/18501#issuecomment-426433986, I looked into the interactions between CSS transforms and padding here: https://codepen.io/cathyxz/pen/jeqOEL. It appears that the padding will also be transformed by `scale. I think https://github.com/ampproject/amphtml/pull/18557 will fix the behaviour you reported here regardless of `slice` or `meet`. 

The thing that we should document for `<amp-pan-zoom>` is that it assumes a constant aspect ratio for the content inside of it. Therefore when anything tries to manipulate the dimensions or aspect ratio of the content inside of it, it will result in clipping or unwanted space. This becomes particularly relevant as we start allowing things like `<amp-selector>` which can show/hide elements per https://github.com/ampproject/amphtml/pull/18545. I previously wanted to disallow elements that do this, but since CSS classes toggled via `<amp-bind>` can already achieve the same effect, we will probably just have to carefully document this assumption as a caveat instead.

**Comment by kul3r4** [comment]
Thanks for explaining. 
What is "anything" when you say "Therefore when anything tries to manipulate the dimensions or aspect ratio of the content inside of it, it will result in clipping or unwanted space", can we complete a list?
