### ISSUE TITLE
AMP Validator adds an extra rel="nofollow" to some links

### ISSUE THREAD

**Issue by lsarni** [ampproject/amphtml#18519]
## What's the issue?

I'm getting this warning for many of my amp pages:

> The tag 'a' contains the attribute 'rel' repeated multiple times.

But what I see on the AMP Validator doesn't match the HTML on my page.
In all the pages the issue is the same.

## How do we reproduce the issue?

1. Go to [https://www.chefsfeed.com/amp/experts/1735](https://www.chefsfeed.com/amp/experts/1735)
2. Inspect the HTML for the link in blue
![screen shot 2018-10-02 at 19 46 43](https://user-images.githubusercontent.com/15196342/46381268-ec262500-c67b-11e8-9032-3db88d7a5206.png)
It says:
`<a target="_blank" rel="noopener" href="https://www.cheflorenagarcia.com">https://www.cheflorenagarcia.com</a>`
3. Run the validator for this page [https://validator.ampproject.org/#url=https%3A%2F%2Fwww.chefsfeed.com%2Famp%2Fexperts%2F1735](https://validator.ampproject.org/#url=https%3A%2F%2Fwww.chefsfeed.com%2Famp%2Fexperts%2F1735
)
This should show a warning: 
![screen shot 2018-10-02 at 19 49 08](https://user-images.githubusercontent.com/15196342/46381347-40c9a000-c67c-11e8-924e-5638bd6c5db0.png)
4. Go to the part of the HTML that causes the warning. The HTML code is:
`<a target="_blank" rel="noopener" href="https://www.cheflorenagarcia.com" rel="nofollow">https://www.cheflorenagarcia.com</a>`
It has an extra `rel="nofollow"` which triggers the warning, even though I can't see it on the website HTML.

Could this be a problem on the validator side? I'm getting a list of this warnings in the Google Search Console.

**Comment by honeybadgerdontcare** [comment]
If one does a view source on the page it'll show that there are two `rel` attributes. The first is `noopener` and the second is `nofollow`. Perhaps Chrome is only showing the first when inspecting as it's selecting the first attribute as being the one intended and ignoring the second (this is speculation). The validator message is correct since the webpage does have two `rel` attributes.

```
<a target="_blank" rel="noopener" href="https://www.cheflorenagarcia.com" rel="nofollow">https://www.cheflorenagarcia.com</a>
```

You may want to use `view-source` in addition to `inspect` for debugging this.
