### ISSUE TITLE
amp-ima-video: Controls Hidden when Ad is Playing

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#18533]
relates to #8841
relates to #18531

# Issue Context

* Issue is visible on the [`amp-ima-video` AMP By Example](https://ampbyexample.com/components/amp-ima-video/).

* Source code for the video player of `<amp-ima-video>` can be found in [ads/google/imaVideo.js](https://github.com/ampproject/amphtml/blob/master/ads/google/imaVideo.js).

* Currently, we are designing/considering a rebuild of video within AMP to use Video.js, so smaller issues will be considered as we don't want to dedicate too much time on the older component version.

# Issue Description

When an ad is playing there is no way to exit full screen, or mute the ad, due to a lack of controls when an ad is playing.

**Comment by torch2424** [comment]
So this may be a bit tricky. Discussed this a little bit with @aghassemi and they may a good point there is a conflict of intent when an ad is playing.

If you click the video, it should take you to the ad page. However, currently, the controls are shown by clicking the video. Also, if the controls are shown, what is the radius for when we should take them to the ad vs. when they actually meant to click the button?

May need some UX / Add standards advice on this before implementation.

**Comment by curseagain** [comment]
Here are my thoughts:
- **always**: have a sound toggle button to toggle sound on/off
- **full screen only**: have an 'x' icon to close the ad (with the effect of exiting full screen and pausing ad/video)

Adding these controls should be a priority because:
- right now a user has to mute their device and/or close a browser window in order to exit/silence an ad that has started playing noise unexpectedly
- sometimes ads don't give you the option to skip so you are forced to watch a 30 second video before you can control your window again
- on desktop, if you are watching a video in full screen and an ad begins to play you are forced to click on the ad in order to be given the option to exit.  There is no way to even close your browser.  The same is true on mobile on my particular device.
