### ISSUE TITLE
amp-user-notification notification fails to display in PWA

### ISSUE THREAD

**Issue by mattwomple** [ampproject/amphtml#18762]
## What's the issue?

If an `amp-user-notification` is set to display based on an `amp-geo` condition, it does not show when the AMP page is viewed in an AMP Shadow.

## How do we reproduce the issue?

I've created a minimal example of an `amp-user-notification` that displays "You are in the US." if the AMP page is loaded in ISOCountryGroup `us`. The AMP page displays the notification correctly, but the PWA fails to show the notification with the following errors reported in the console:

    requires <amp-geo> to use promptIfUnknownForGeoGroup | shadow-v0.js:102
    Notification service failed amp-user-notification homeNotification: No ampdoc found for undefined | shadow-v0.js:102
    Uncaught Error: Notification service failed amp-user-notification homeNotification: No ampdoc found for undefined _reported_ | amp-user-notification-0.1.js:2

Note, this issue smells very race-y. When you visit the AMP Shadow page, you may need to refresh a few times to reproduce the problem. If you keep refreshing, you'll see that sometimes the notification succeeds and other times it fails (with the above console errors).

- AMP Page viewed in Shadow AMP: https://cmphys.com/amp-geo-shadow.html
- AMP Page: https://cmphys.com/amp-geo.html

## What browsers are affected?

I've reproduced this issue in the following browsers:

- Mozilla/5.0 (Linux; Android 8.0; Pixel 2 Build/OPD3.170816.012) AppleWebKit/537.36 (KHTML, like 
Gecko) Chrome/69.0.3497.100 Mobile Safari/537.36
- Mozilla/5.0 (Linux; Android 7.0; Moto G (5) Plus Build/NPNS25.137-93-14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Mobile Safari/537.36

## Which AMP version is affected?

1810052256480

**Comment by jpettitt** [comment]
This is really weird.  Looking into it.

**Comment by jpettitt** [comment]
Detailed analysis:

It is a race condition.   `amp-geo` is particularly susceptible to race conditions because it has a shorter cache lifetime.

In the normal, non shadow case, when `amp-user-notification` calls the `geo` service the runtime looks for a service promise, if one has not been created because  `amp-geo` hasn't run yet then it looks in `head` to see if the `amp-geo` script is present (`waitForExtensaion()`) and if it's there it then creates a placeholder that is replaced when the real service is instantiated.

In the shadow case the same flow happens except that when it tries to find the `amp-geo` script it fails because `extensionScriptsInNode()` is being passed the `head` returned by `AmpDoc.getHeadNode()` which isn't really the `head` it's the shadow root.  It then fails to find the `amp-geo` script and you get an error that it's missing.

Looking at the code `AmpDoc.getHeadNode()` was put in to enable CSS to be attached in the right place, in that use case the shadow root is the right return value.  

If (to be confirmed) extensions scripts never live inside the shadow root then we can just switch to using the real `win.document.head` in `extensionScriptsInNode()` which should fix this.
