### ISSUE TITLE
Validator complaining about invalid viewport when <meta name="somthingelse" is present

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#1876]
If I have a page with 

```
<meta name="viewport" content="width=device-width,minimum-scale=1">
<meta name="anything" value="this,that,theother">
```

The validator throws

`validator.js:274 http://localhost:8000/templates/amptemplate.html:11:4 The attribute 'name' in tag 'meta name=viewport' is set to the invalid value 'anything'. (see https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#vprt)`

` <meta name="twitter:card" content="summary">` is however accepted.

Bug or are you blocking some meta tags intentionally? If so where can I find the list of approved meta tags?

**Comment by Gregable** [comment]
I think the validator is doing the right thing here, but the error messages being produced aren't that great.

The validator allows meta tags of the form:
```
<meta name="anything" content="this,that,theother">
```
But not:
```
<meta name="anything" value="this,that,theother">
```
which, I don't _think_ is very standard, though please correct me if I'm mistaken. Note the difference in the 2nd attribute `content` vs. `value`.

There is a caveat here that there are a few `name` attribute values the validator does not allow in this generic tag, specifically `viewport`, `content-disposition`, and `revisit-after`. All other `name` attribute values we allow.

The poor error message is because the validator gets confused about which matching rule it should try to generate an error for when none of them match perfectly. This is a area I'm planning to improve on in the future.

**Comment by Gregable** [comment]
> where can I find the list of approved meta tags? 

If you would like to take a look at these, you can see the[ spec the validator is using](https://github.com/ampproject/amphtml/blob/master/validator/validator.protoascii) for this tag. Search for the string "meta name= and content=" to find the relevant spec. Currently line 432, but it could move around.

**Comment by jpettitt** [comment]
Yep that's it - I'll have to go find where they got the value= in the original page source I'm converting - we were just preserving all meta tags apart from the blacklisted ones but I guess I'll have to be more aggressive.
