### ISSUE TITLE
amp-3d-gltf fails to load model asset due to CORS issue

### ISSUE THREAD

**Issue by aknoerig** [ampproject/amphtml#18810]
## What's the issue?

The plugin for loading GLTF 3D models fails due to a CORS issue.
The error message reads

`Failed to load https://ampbyexample.com/glTF/DamagedHelmet.glb: The 'Access-Control-Allow-Origin' header has a value 'https://d-2216337535257116248.ampproject.net' that is not equal to the supplied origin. Origin 'https://d-10884114631319091289.ampproject.net' is therefore not allowed access.`

## How do we reproduce the issue?

The bug shows in the playground example for this plugin: https://ampbyexample.com/playground/#url=https://ampbyexample.com/components/amp-3d-gltf/source/

Curiously, for some reason it usually works here when loading the page for the first time. Try refreshing it a couple of times to see varying results.

When I host this example on my own server (with https and local asset hosting), it fails consistently.

## What browsers are affected?

All browsers? Some specific browser? What device type?

Tested with Chrome 69 and Safari 12.0 on macOS 10.14

## Which AMP version is affected?

1810152207300 - tried it for the first time. I assume this is caused by browser updates that have more strict security rules.

**Comment by aghassemi** [comment]
All the `fetch` requests from `amp-3d-gltf` are triggered from `three.js` with the origin `https://<random>..ampproject.net` and require CORS.

@aknoerig on your server, you want to send `access-control-allow-origin: *.ampproject.net` to enable CORS. If you want to `echo` request header's `Origin` instead of the wildcard `*.ampproject.net`, that's possible too but then cache policy should be set to no-cache since the origin changes on every reload. @sebastianbenz Same is true for AMPByExample and that's why this fails on reloads.

@mixtur FYI and I will update the documentation for this.

**Comment by aghassemi** [comment]
@mixtur It would be nice to fetch the data in the component and then pass it to the iframe so normal AMP CORS policies would apply. Created https://github.com/ampproject/amphtml/issues/18822 to track that if you find time.

**Comment by aghassemi** [comment]
Closing per comments above.
