### ISSUE TITLE
hidden placeholder in `layout=container` takes unnecessary space.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#18817]
This bugs happens when a component with `layout=container` has a `placeholder`.
For instance `amp-mathml` or when `amp-list` resizes to container via `auto-resize` attribute.

Sample repro with `amp-list auto-resize`:  https://codepen.io/aghassemi/pen/ePrYwW?editors=1000
Sample repro `with amp-mathml`: https://codepen.io/aghassemi/pen/bmMGzG 

Issue is:
- `placeholder` is only make position absolute when `i-amphtml-layout-size-defined`. This makes sense initially since `placeholder` needs to expand the `container` when `layout=container`
- we hide placeholders using `visibility:hidden`, this only makes sense if `i-amphtml-layout-size-defined`. For `layout=container`, hiding the placeholder with `visibility` will keep the space there causing this bug.

**Comment by jaygray0919** [comment]
There is a similar problem with `amp-list`.

When using `amp-mustache` with `amp-list`, a `{{term}}` in `<span>` forces a line-break. Have tried various CSS methods to `keep-together` but all fail. The consequence is that we cannot create a `<p>` using multiple `<span>` for different URLs loaded from `amp-list`.

Have shared examples with @choumx.

Our request is that `amp-list` generate an inline `span block` rather than a `div block` which forces the new-line-break.

**Comment by aghassemi** [comment]
@jaygray0919 I believe that is a separate issue and likely for `amp-mustache` to fix. Do you mind creating a separate issue for it? It will get lost here as a comment.

**Comment by jaygray0919** [comment]
@aghassemi will do.
