### ISSUE TITLE
amp-3d-gltf: Fetch data in 1P instead of 3P

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#18822]
Currently all the `fetch` requests from `amp-3d-gltf` are triggered from `three.js` with the origin `https://<random>.ampproject.net`.

This creates non-standard CORS requirements for this component.

It would be nice if data is fetched in the 1P `amp-3d-gltf` JS and then passed to the 3P iframe instead. This way normal [AMP CORS ](https://github.com/ampproject/amphtml/blob/8a33484f56829a9ad13f5b98e864f4795161d9ad/spec/amp-cors-requests.md) requirements would apply instead. 

Not sure how feasible it is given there are multiple layers of SJ libraries here from gltf to three.js. IF all of this API surfaces allow JSON data to be passed instead of a Url, then this should be feasible.

/to @mixtur

**Comment by mixtur** [comment]
It technically possible but I am not sure if it is a good idea.
- gltf is mostly binary so it will need to be serialized/deserialized
- gltf is not necessarily single file it may require to download other files via relative paths.
- also need to cross process boundaries with that much data doesn't sound good to me.

So I believe there are at least two solutions to that
- clean but halfway solution. Fetch src in 1p and then transfer whatever it is to 3p. Then parse it in 3p. It will eliminate need for CORS on server providing gltf but it will only work when gltf is a single file. CORS requirement will still stand for multiple files case.
- dirty but complete solution. Monkeypatch three.js in such way that when it need to download file it goes through 1p. It is also a bit slower because there are two messages involved for every request.

For both solutions we'll still have to cross process boundaries with lots of data. Not cool.

**Comment by aghassemi** [comment]
@mixtur Got it. Not a big deal and given the technical limitations, looks like it is not worth it. I documented CORR requirements for the component here: https://github.com/ampproject/amphtml/pull/18821

**Comment by aghassemi** [comment]
Closing per discussion above.

**Comment by donmccurdy** [comment]
Quick thoughts on technical options:

> gltf is not necessarily single file it may require to download other files via relative paths.

Some viewers, like Facebook, only allow the binary GLB (`.glb`) variant of glTF, which is expected to be a single file with no external assets. Packing a multi-file `.gltf` into a `.glb` is a very easy process, see https://glb-packer.glitch.me and https://github.com/AnalyticalGraphicsInc/gltf-pipeline. If restricting `amp-3d-gltf` to not allow multi-file assets would improve CORS requirements, that doesn't sound too crazy.

> gltf is mostly binary so it will need to be serialized/deserialized

Strictly speaking, if you need to pre-load external assets from a `.gltf` file, you only need to do `JSON.parse()` and then fetch the `.buffers` and `.images` entries. The binary `.bin` and textures contain most of the data. `.glb` is the binary packed form, but shouldn't reference external files.
