### ISSUE TITLE
Measure impact of visibility change on startup

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1884]
With the new boilerplate we are animating and then setting visibility.

According to @esprehn this may be expensive

@sriramkrish85 Did we evaluate the performance of this? I'd like to minimize performance impact including and up to rolling back the change.

**Comment by cramforce** [comment]
CC @dvoytenko

**Comment by esprehn** [comment]
Changing the visibility on the body causes us to recalc the style of the entire page since visibility is "internally inherited" even though the CSS property itself is not. Looking at an example page like https://www.ampproject.org/docs/get_started/about-amp.html this takes about 2ms.

I do see a 2ms style recalc during page load for that page, but I can't get the source map to tell me what line in styles.js caused it.

**Comment by dvoytenko** [comment]
We definitely looked into performance of visibility vs opacity. @sriramkrish85 do you still have your docs on this?

**Comment by sriramkrish85** [comment]
@esprehn , @cramforce , @dvoytenko 
I just ran some tests on our 

/examples.build/article.amp.html (and created another duplicate file on my localhost /examples.build/article-old.amp.html)

and made the files larger (by copy-pasting the <article> 14 times) and compared the `Recalculate Style` timings

Looks the the one animating visibilitiy  (NEW) is better than the OLD boilerplate( <style>body {opacity: 0}</style><noscript><style>body {opacity: 1}</style></noscript>)

You can view the data here- 
https://docs.google.com/spreadsheets/d/1rLB5vNlVROErK5dqCJwIMFQPrymoROxEysKiFB49Nug/edit?usp=sharing

**Comment by sriramkrish85** [comment]
Ping @esprehn
