### ISSUE TITLE
Add story-level mediasession metadata

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#18937]
Currently, we provide [mediasession](https://developers.google.com/web/updates/2017/02/media-session) metadata from the videos and/or audio elements within the story.  Instead, it would be cool to provide a story-level metadata, and hook up the media buttons accordingly:

* **play/pause** plays/pauses story
* **seek forwards** next page
* **seek backwards** previous page
* **next track** next story
* **previous track** previous story

We'll also need to somehow suppress the mediasession data that comes from videos and audio within the story, so that they don't override what's provided at the story level. /cc @aghassemi @alanorozco

**Comment by alanorozco** [comment]
I wonder what the right approach for this would be. I'm thinking of a couple possible options:

1. Special-case `amp-story` with different compositions of `VideoManager` subsets. This has the nice benefit of being transparently polymorphic (e.g. not littered by diversion conditions) but there's some performance regressions with the immediate check of `amp-story` inheritance. The composition binding for the story case could be "barebones" as well, since some of the things that are turned off/changed for `amp-story` are reimplemented at the story level anyway. (Sorry for the word salad).

2. Push `amp-story`-specific configuration through some sort of transport (e.g. signals, events). The issue here is querying for video elements in the reverse as above (i.e. querying for `amp-video` instead of checking if `amp-video` belongs to an `amp-story`). Though this is option is nice because nothing about `VideoManager` is special-cased, it only receives optional "parent configuration" that will change state at any time. The biggest downfalls of this option are UX (e.g. if the video registers earlier than the story element there could be FOUC-like media session changes) and managing how the state of the video service changes/resets.

I don't like either of these options. I'm sure there are more elegant ways to divert the implementation but I haven't been able to think of one that maps to our component/service model well.

**Comment by aghassemi** [comment]
Given there is no build order guarantee due to async scripts, the only source of truth is the DOM, so I don't think we can avoid checking ancestors.

**Comment by newmuis** [comment]
We now actively do not want this; MediaSession API will open some browser behaviors we don't want, like Chrome's [global media controls](https://www.theverge.com/2019/7/6/20684353/google-chrome-global-media-controls-play-button-pause-experimental-test-canary)
