### ISSUE TITLE
Set cookie duration with clientId

### ISSUE THREAD

**Issue by StephanGuenther** [ampproject/amphtml#1899]
After our data privacy we can only set cookies with a maximum duration of 6 months, but amp sets currently 1 year.

**Comment by rudygalfi** [comment]
Quick question regarding your requirement: The AMP cookie renews the 1-year expiry each time it's accessed. Would you need 6 months without renewal or is renewal OK but in 6 month intervals?

**Comment by StephanGuenther** [comment]
Renewal is ok.

**Comment by rudygalfi** [comment]
@cramforce @avimehta Just thinking about how we expose this. We could do:

clientId takes an argument:
```
${clientId(scope-id, duration)}
```

Unfortunately the above conflicts with the user notification stuff.

We could just have a config k-v pair:
```
"cidSpec": {
  "ttl": "180"
}
```
This is a bit strange, though, because I don't see any reason why this configuration is at the amp-analytics level while user notification is inlined with the use of the client ID.

Any thoughts on this?

**Comment by zhouyx** [comment]
cc @jeffjose
