### ISSUE TITLE
The close action of the amp-sidebar determine the scroll at the previous manual scrolled position

### ISSUE THREAD

**Issue by morenz** [ampproject/amphtml#19021]
## What's the issue?

The close action of the amp-sidebar determine the scroll at the previous manual scrolled position.
In the reference:
https://nuovoduster.dacia.it/amp/index.php
we have an amp-sidebar that has scrollTo links and "sidebar-left.close" action on menu items.
When clicked on amp-sidebar menu item, it will scrollTo and, closing the amp-sidebar, it will scroll immediately to the previous manual-scrolled position

## How do we reproduce the issue?

Here:
https://nuovoduster.dacia.it/amp/index.php

## What browsers are affected?

All

## Which AMP version is affected?

amp-sidebar-0.1.js
amp-accordion-0.1.js

**Comment by aghassemi** [comment]
@morenz `amp-sidebar` automatically `focused` the element that opened it for better accessibility for screen readers.

You can accomplish what you want by using the `sidebarClosed` event. 

So instead of
`on=tap: scroll; close`
do
`<amp-sidebar  on="sidebarClose:scroll ...`

that being said, for accessibility reasons I suggest you also focus on an element that makes sense after on instead of doing `scrollTo`.

**Comment by aghassemi** [comment]
Closing per answer above.

**Comment by morenz** [comment]
<amp-sidebar on="sidebarClose:scroll
do not know where to scroll... but there's a simple solution:
on=tap: close; scroll
in practice, just invert will solve, calling close after calling scroll.
