### ISSUE TITLE
"The document is too complex" issue can not be fixed

### ISSUE THREAD

**Issue by NNSTH** [ampproject/amphtml#19052]
## What's the issue?

on AMP section in search console I get this error related some pages in my site. when trying to run these pages on AMP validator, or using the AMP extension for chrome - validation passes OK (green).
This  issue can't be fixed if I don't know what causes it- too much DOM elements? TOO deep? rich style?
Can you help us fix those problems please?

## How do we reproduce the issue?

I can't tell you how to reproduce it- since I can't do it myself, but I can give you a problematic URL, appears on the issue's details section:
https://www.homeworkmarket.com/amp/files/gmepowerpointslidestopic4-ppt

## What browsers are affected?

All browsers

## Which AMP version is affected?

V0

**Comment by torch2424** [comment]
cc @Gregable @honeybadgerdontcare 

Could you help out with this? 😄

**Comment by Gregable** [comment]
This error isn't specific because we don't typically know what's going on in this case. It implies that the parse tree for the document has exploded in some fashion. These cases are rather rare. @jpettitt probably has it right. If the nesting gets too deep, most parsers will probably blow up / give up, including some browsers.
