### ISSUE TITLE
Error handling on the authorization request

### ISSUE THREAD

**Issue by jugglingcats** [ampproject/amphtml#1906]
My understanding is that if the authorization request results in an error response (4xx or 5xx), the page will render without any AMP Access expression processing.

First it would be good to state this in the documentation, and make it clear that expressions will simply not be evaluated (assuming that is the behaviour), so in the example below the section would be hidden on error.

```
<section amp-access="NOT forbidden" amp-access-hide>
  THIS IS PREMIUM CONTENT
</section>
```

Second, it would be good to provide some way for developers to detect when an error occurs, because they might want to make a decision whether to fail open or fail closed, or provide some message to the user. I can think of a couple of ways to achieve this:

- Provide a 'fallback' response JSON which will be used if the authorization request fails. This has the advantage that developers can vary this JSON based on business rules, such as whether the content is premium or not, without changing the rest of the page logic
- Provide a new attribute like amp-access-error which will only show the content when an error occurs

**Comment by dvoytenko** [comment]
@jugglingcats couple things that we can do.

1. We currently set `amp-access-error` top-level CSS class when authorization endpoint fails. It can already be used for something like you are requesting. (E.g. `.amp-access-error #important-id {display: anyway}`
2. We can definitely evaluate authorization, but instead with a predefined `{error: true}` data so that expression can include things like `amp-access="datax OR error"`.
3. I do like the idea of the fallback JSON response. However, it'd seem to be a concern that your format will be "freely open" in the config. There are obviously no security concerns in this, but would you feel comfortable putting it there?

WDYT?

**Comment by jugglingcats** [comment]
Didn't notice amp-access-error CSS class. That's definitely useful.

I'm not worried about the fallback JSON being exposed. It is simple enough for a tech user to sniff the real response to see what's in it, and there are many other ways to hack the content in client mode.

For developers who are worried, they could just bake in {error: true} and revert to solution 2. So for me it gives people options without encouraging them to introduce a big security hole that wouldn't otherwise be there.

**Comment by dvoytenko** [comment]
Thanks, @jugglingcats. A very good point that fallback of `{error: true}` essentially covers both solutions.
