### ISSUE TITLE
[amp-pan-zoom] support more customization for zoom level

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#19117]
For instance: could allow developers to set various levels of zoom (ex. the number of steps corresponding to different % values, as well as which level of zoom is the default value for the first tap)

**Comment by jaygray0919** [comment]
We could use this for large SVGs
examples:
  https://afdsi.org/test/amp_pan_zoom_0/
  https://afdsi.org/test/amp_pan_zoom_1/

**Comment by cathyxz** [comment]
So we currently have 2 levels of zoom only: min and max, where MIN_SCALE is 1, and MAX_SCALE is a variable that defaults to 3. 

Technically, you can already kind of do this with the `transform` action and `bind`, since the `transform` action takes a `scale` variable, so you can arbitrarily set the `scale` to anything you want. You can keep track of the current scale using `amp-state`, and increment / decrement it on tap using `amp-bind` and `transform`. So the question here is more like, how do I make this easier and part of default behavior. 

Here are a few possibilities: 

### Steps
We could introduce an attribute called steps (feel free to bikeshed on naming), requiring an integer larger than or equal to 1, that specifies how many zoom steps to take to reach MAX_SCALE. 

So basically, say steps = n. There for each zoom in / out should increment / decrement the zoom scale by `(MAX_SCALE - MIN_SCALE) / n`. 
Tapping the zoom button once will result in 
`scale = scale +/- (MAX_SCALE - MIN_SCALE) / n`
Subject to bounding  by `MAX_SCALE`, since the `transform` action could interfere with this. 

A few caveats / open questions:  
1. This doesn't play nice with the existing UI, which is a single button matching the behavior of double tap zoom. You'll need two buttons instead of one since you can theoretically be in between `MIN_SCALE` and `MAX_SCALE` and can now go either way. This will either need a change in the default UI, or we'll need to special case and have a new UI when `steps` are included. 
2. It's not clear to me what double tap zoom should do in this case. If increment by `(MAX_SCALE - MIN_SCALE) / n`, then doesn't that mean it needs to increment all the way to `MAX_SCALE` before decrementing all the way back to `MIN_SCALE`? The easiest consistent behavior is double tap zoom should keep the current behavior, and zoom to `MAX_SCALE` if it is currently at `MIN_SCALE`, and then zoom out to `MIN_SCALE` if it is at any other scale. But I'm open to alternative suggestions.
