### ISSUE TITLE
Provide a button to enable all tooltips on an AMP Story Page

### ISSUE THREAD

**Issue by ghelapratik** [ampproject/amphtml#19134]
AMP Story Tooltips are really great. But, chances are that people may not be aware about one. A good use case will be to offer a CTA button at the bottom clicking which makes all the available tooltips active. Also, apart from just allowing text in tooltips, it will be awesome to allow images inside tooltip content. An example of this can be as follows. 

![story-final](https://user-images.githubusercontent.com/22929187/47968360-fd759f00-e036-11e8-9e35-8b5d5ebf59df.png)

**Comment by newmuis** [comment]
*Re: showing all available tooltips*
The publisher of the story should make it clear that an element is interactive with publisher-defined styles.  Think of this as being analogous to creating links on a standard web page; links are generally given some type of visual treatment (blue text, underlines, etc) to indicate that they are indeed links.

*Re: images in tooltips*
The tooltips are not generally meant to hold content, but just to act as a confirmation for the story's navigation model, to ensure the user intended to act upon an interactive element rather than to navigate.

/cc @hongwei1990 @Enriqe

**Comment by dcombe** [comment]
Any update on this ?

**Comment by newmuis** [comment]
This is not being actively implemented at the moment. I don't think we'll have an update here for a few months, but it's something we're still exploring on the UX side.
