### ISSUE TITLE
launch amp-lightbox for AMPHTML ads

### ISSUE THREAD

**Issue by kuldeep** [ampproject/amphtml#19138]
Is there any timeline to take it live? @zhouyx

**Comment by aghassemi** [comment]
@alanorozco any remaining items before launching this? /cc @lannka

**Comment by zhouyx** [comment]
@alanorozco Is there any remaining blockers to launch 'amp-lightbox-a4a-proto'? If so can we document the blockers? I'm happy to work on it. Thank you.

**Comment by alanorozco** [comment]
@zhouyx Let's sync offline. I need to yet again wrap my head around these, but as far as I remember we're pretty close to launch.

**Comment by kuldeep** [comment]
@alanorozco   When can we expect this to go live?

**Comment by antony-cm** [comment]
question on the amp-lightbox tag status ? Whether it's live or not, as the main docs - https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/amp-a4a-format.md mentioned it's supported now. But having contradicted example highlight amp-lightbox is not supported. 

"Example: <amp-lightbox> is not yet included because even some AMPHTML ads creatives may be rendered in an iframe and there is currently no mechanism for an ad to expand beyond an iframe. Support may be added for this in the future, if there is demonstrated desire for it." 

If it's not go live , can I suggest we remove the amp-lightbox from the support list ?

**Comment by zhouyx** [comment]
to @lannka

**Comment by lannka** [comment]
From a previous discussion, there are 2 remaining issues need to be addressed before we can make it fully available:
- give publisher the control to disallow expansion 
- introduce a fallback UI if the expansion is denied

We should prioritize it and launch it before 3/20. /cc @jasti

**Comment by calebcordry** [comment]
@lannka Is this prioritized?

**Comment by lannka** [comment]
we might get back to this shortly as to support more direct sold ad formats
