### ISSUE TITLE
Proxy-based paywalls

### ISSUE THREAD

**Issue by carlosabalde** [ampproject/amphtml#1917]
I think AMP Access is focused on scenarios where the access control logic is embedded in the CMS of the publisher. However, there is another popular scenario where the **paywalling logic is embedded in a proxy (e.g. Varnish Cache, Nginx+LUA, etc.) deployed in front of the CMS of the publisher. In this case the CMS does not known anything about paywalling. It simple delivers contents and delegates on the proxy the access control decisions**. This has a lot of nice properties, specially when the proxy is able to cache contents (e.g. high performance, paywalling complexity not included in the CMS, etc.), but it also has some limitations (more about this in the example below). These limitations can be easily workarounded when there is not JavaScript restrictions in the client side. However, when dealing with AMP contents, the usual JavaScript-based hacks are not an option.

Below I include a simple example that illustrates the differences between both scenarios. **Let's assume a paywalled site serving only AMP contents (i.e. canonical URLs of AMP contents are AMP contents) using a simple metered model**. 

In a **traditional paywalling scenario** (i.e. access control logic embedded in the CMS) when processing an incoming request for a paywalled content:

* **If the request matches Google Bot or some IP in the AMP Cache range**, the paywalling logic is skipped and the full content, including the AMP Access stuff, is delivered by the CMS. The access control logic will be executed somewhere else (the AMP Runtime or the AMP Cache) using the AMP Access endpoints.

* **Otherwise (i.e. neither Google Bot nor AMP Cache request)**, the paywalling logic is executed by the CMS. If access is granted, the CMS will render and deliver the full version of the AMP document. If access is denied, the CMS will render and deliver a teaser of the AMP document. In both cases, the generated AMP document will not contain the AMP Access stuff and **it may embed some data such as the current value of the meter and the remaining quota**.

However, in a **proxy-based paywalling scenario**, when processing an incoming request for a paywalled content:

* **If the request matches Google Bot or some IP in the AMP Cache range**, the proxy will request to the CMS the full version of the content, including the AMP Access stuff, an it will deliver it. No problems here.

* **Otherwise (i.e. neither Google Bot nor AMP Cache request)**, the paywalling logic is executed by the proxy. Depending on the authorization result, it will request to the CMS the full version or the teaser of the AMP document. **And here comes the problem: how to transport to the client side the current value of the meter and the remaining quota? In a non-AMP case, the proxy could keep that state readable in the client side generating a cookie consumed in the client side using some JavaScript, but that's not an option with AMP**.

I can think about **two possible solutions**:

1. Deliver the full version of the content including the AMP Access stuff even when it has not been requested by Google Bot or the AMP Cache. In other words, always rely on the AMP Access endpoints to execute the access control logic. I think this could be acceptable in the 'client' mode, but not in the 'server' mode.

2. Paywalling proxies have strong limitations to modify delivered contents, but some simple substitutions may be possible. When completing the execution of the access control logic, the proxy could modify the AMP document and inject some AMP tag embedding a JSON object similar to the one returned by the AMP authorizations endpoint. This object could contain information like the current value of the meter, the remaining quota, etc. These properties should be usable when rendering the AMP document in the client side. I think this kind of feature does not exist at the moment in AMP and perhaps it could be useful.

Any feedback about this is highly appreciated. And please, sorry for the huge post. I tried to keep it short and simple but I failed miserably.

**Comment by jugglingcats** [comment]
@carlosabalde I think you raise some good points. From my reading of the spec, in client mode the flow is quite clear. The CMS delivers the teaser AND the full content in all cases but the full content is in amp-access-hide section. This response is fully cacheable. The AMP client then hits the authorization end point to get a decision. The JSON response from this endpoint can contain data which is rendered by the client, such as the current and max meter limit.

This is analogous to the current approach with sophisticated CDNs like Akamai with strong ESI support - the CMS delivers all the content to the CDN and the decision is made at the edge, with any content that shouldn't be shown being removed dynamically.

Obviously some publishers will be concerned about delivering the full content all the way to the client. It is not clear to me how server mode will work when it comes - there is very little detail on it that I can find. But perhaps the flow will be similar to that described above. Cookie handling is a concern in this case though...

**Comment by dvoytenko** [comment]
@carlosabalde, @jugglingcats

I can see a few options here:
 1. Auth proxy implements AMP Access spec itself and sends the document back with `type = other`.
 2. Auth proxy does its own access logic to create the target document content and AMP runtime is not aware of any of it.
 3. The differences between 1 and 2 are rather trivial and one could have a compromise between them.
 4. We extend AMP Access spec to accept authorization response JSON inside the document itself. In this case AMP Runtime will do exactly what it does today except it will forgo calling the authorization endpoint and use the provided object instead. This is kind of similar to authorization fallback we are considering in #1957.

A bit more detail on 1-3.

#### Auth proxy implements AMP Access spec

AMP Access is a fully public spec and thus, I don't see this being a huge problem to "filter" the document on the serving proxy side. In that case the auth proxy has to have authorization response (which sounds like it would since it's the core purpose for it in this case). The amp-access grammar is public and has the BNF which should make it possible to convert to any language that proxy uses. Thus, filtering the document by expression is possible and should be a fairly straightforward process. That means an auth proxy could use the same AMP spec for most of its needs.

Access already supports `type = other` in the configuration. This type disables most of access functions in AMP Runtime except pingback - it it's configured, it will be called, which should be a nice signal if desired.

What this option gives you also is the flexibility of launching login dialog on every platform, given that this is often difficult to achieve fully by simply using links. So this would be nice to keep.

#### Auth proxy does its own filtering

This is very similar to the first option, except client doesn't even need to know that there's any access work done. The complication is that "login" is lost and there's no pingback. But it's certainly possible.

In this case auth proxy will have its own access definition and it will generate response for AMP Cache and direct response to the user from this definition.

#### Compromise

Since the 1 and 2 are so similar - there could be a compromise. Auth proxy includes amp-access configuration but does all the filtering itself. In this case, configuration will have `type = other` and none of the elements will have `amp-access` expressions. However, AMP Runtime can still send pingback and will still provide handling for login.

**Comment by jugglingcats** [comment]
@dvoytenko your option 1 is how I vaguely imagined type="server" would be handled. Are you in a position to comment on this?

All your options essentially break caching. The AMP Cache would need to hit the publisher CMS (or CDN) for each request. It wouldn't be possible for the AMP Cache to pre-populate any content because it would need to pass the user context (cookies) in all requests. If the AMP Cache implemented option 1, it could pre-cache the content, and dynamically execute the access endpoints.

I think that @carlosabalde scenario is quite Varnish specific (serving teaser OR full content from the CMS) because Varnish has very limited support for choose/when logic within a single backend CMS response. 

> Depending on the authorization result, it will request to the CMS the full version or the teaser of the AMP document 

Akamai and Nginx have better support for this, making it possible for the CMS to deliver teaser AND full content in a single response, and have the filtering done at the edge. This latter approach is a more natural fit when switching to AMP Access, because the CMS dev just has to replace ESI/SSI tags with AMP Access tags, and not change the way pages are composed.

@carlosabalde as an aside, your original post mentions indexing by robots, but am not sure search engines are intended to index the AMP version of documents. See issue #1936

**Comment by davidfb** [comment]
Hi, a @carlosabalde colleague, here.

@jugglingcats Totally agree with you. Although @dvoytenko suggestions on doing all filtering on the proxy seem theoretically possible, there are implications on caching that should better be avoided and the strengths of Varnish don't cover well this scenario, so that's a path that can't be followed. It would be very helpful indeed understanding if AMP Cache in server mode will behave as option 1. Hope @dvoytenko can clarify that a bit.

About the original question, main issue in this context is to already supply the authorization result information when delivering the requested content directly to the client. For this, @dvoytenko your suggestion on using an authorization fallback seems to fairly fit. Having a way to avoid doing the authorization request and directly using the authorization fallback info would be certainly great. Do you think it would be possible to give it a thought on getting something like that into the specification?

Thank you very much.

**Comment by dvoytenko** [comment]
One thing I should have mentioned and what should have been the option 0 in my list above: auth proxy can simply add `amp-access` config with `type=client` and markup to a document and serve it directly (as well as via AMP Cache). Basically the same version for everything. This allows complete caching. AMP Access would work the same way either the document is accessed directly or through Cache. This is definitely the simplest path and the best performance.

> your option 1 is how I vaguely imagined type="server" would be handled. Are you in a position to comment on this?

Indeed it's similar to `type=server`, but there are some key differences. I'm not yet clear on the timeline, but you will certainly start seeing some PRs arriving in our repo soon. We are intending the future `type=server` to work using exactly the same protocol, markup, etc as `type=client` with a single exception: the content hidden by default is not initially delivered to the user and is only sent after the authorization endpoint is complete. In fact both types are fully compatible and `type=client` can be used to develop and test `type=server` initially. Thus the only difference really is that not all of the content is delivered initially. The tradeoff is that delivering the rest of the content is going to be slower.

It'd work about like this:
 1. The initial content is delivered from AMP Cache but some sections are omitted
 2. Client initiates request to get rest of the content via AMP Cache.
 3. AMP Cache calls authorization endpoint on behalf of the client
 4. Authorization response is used to create delta on the AMP Cache's side (server side). I.e. the delta of what's been sent initially vs what authorization endpoint allows
 5. AMP Cache sends back the delta to the client which merges it in

So performance is one tradeoff, obviously. Another notably complication in this approach is that `type=client` works exactly the same regardless whether the document is accessed directly or via AMP Cache. While `type=server` will need a compatible backend to work.

**Comment by carlosabalde** [comment]
Thanks for the feedback. Let me **try to summarize in order to check that we're all in the same page**:

1. Several options are possible when using **client mode**, but the simplest and most performant one is **delivering identical AMP documents (i.e. ``type=client``, ``amp-access`` stuff & authorization, pingback and login URLs)** to the AMP Cache, to Google Bot and to any client accessing directly to the publisher's site. Obviously there are not problems with this approach when using an auth proxy.

2. When using **server mode** this gets more complicated. Ideally the auth proxy running in the publisher's site should **behave as the AMP Cache** (i.e. deliver contents with some sections omitted, send deltas when required, etc.). However, that may not be possible, at least when the auth proxy has limited capabilities to modify/process CMS responses (e.g. Varnish Cache). As an alternative the auth proxy could **deliver different responses to AMP Cache (i.e. ``type=server``, ``amp-access`` stuff & authorization, pingback and login URLs) and to other clients (i.e.``type=other``, no ``amp-access`` stuff & only the pingback and login URLs)**. 
This should be ok for most auth proxies (they simply need to request to the CMS side the right version of the AMP document), but the original problem that motivated this issue is still present: **how to transport the authorization response from the auth proxy to the client side?** The suggestion of using something similar to the authorization fallback seems to fairly fit here. The auth proxy could embed the the authorization result in the AMP document doing a simple substitution and the AMP Runtime could use it without executing a request to the authorization endpoint.

**Comment by dvoytenko** [comment]
@carlosabalde First 1st point about `type=client` is correct. However, other options, as you note, are indeed progressively more complicated. My question is, before digging deeper into possible additions to the protocol, could you please explain the following? If you would still want to support `type=client` for AMP Cache, why would you want to do it any differently for direct access? Or did I misunderstand and you are saying that you'd prefer `type=server` instead? Both of them require more-or-less the same things: same content markup, same endpoints, etc...

**Comment by carlosabalde** [comment]
@dvoytenko,  we're interested both in ``type=client`` and ``type=server``. At the moment we're working on a integration with AMP Access using ``type=client``, which I think it's the only realistic option at the moment. However, we're also interested in ``type=server`` because we're specialized in paywalling proxies based on Varnish Cache. We would like to be ready if some of our customers is interested in the ``type=server`` flavor in the near future.

This discussion helped us to understand that handling direct accesses in a different way is not useful when ``type=client``. That's only useful when ``type=server``, and, as I said, even we're not working on supporting AMP Access in server mode at the moment, we would to extend our auth proxy to support it as soon as is available. That's the main reason for this issue and all this discussion. Sorry for the confusion! :)

**Comment by dvoytenko** [comment]
Thanks, @carlosabalde! And one more question. I'm not sure if I understood yet fully, but you are considering, at least in some cases, to directly request documents from CMS for different versions of the document? E.g. full document vs restricted document? The reason I'm asking is that in my research most of paywall systems do use some form of content markup where all sections are included in the complete document and they are hidden/shown or server-side filtered at the serving time. The solutions here range from something very basic like a boolean attribute to a SSI-style instructions. My point here is that if you have this kind of markup - you can essentially support the compromise version I described above with some ease. AMP content markup is fairly open-ended, but it's your output markup - it doesn't mean that you need to support it yourself. E.g. if you get a document arriving from CMS marked up in any basic way you can always filter it yourself or replace this markup with AMP markup when serving to AMP Cache. These are all valid options, I think.

**Comment by carlosabalde** [comment]
I know some paywalling products out there work that way, but that's not how paywalls build on top of Varnish Cache (VC) usually work. Main reason for that is that VC is not really a paywalling product per se. VC is a high performance caching proxy with a flexible configuration language (VCL) and extensible using modules (VMODs). 

VCL and VMODs provide a lot of flexibility to implement the access control logic in the caching edge of the publisher and run that logic at maximum speed (VCL is translated to C and compiled as a shared library on load time; VMODs are already shared libraries). However, mainly because of that high performance, when using VC for paywalling you also have some restrictions: limited support for ESI and strong limitations to alter bodies of delivered HTTP objects.

The way paywalls build on top of VC work is internally rewriting the requested URL and fetch from the CMS (or from the internal VC storage) the right version depending on the authorization result (e.g. full article vs. teaser).

Therefore, back in AMP: when ``type=server``, if a content is requested by the AMP Cache, VC will simply skip the paywalling logic and it will deliver the content (``type=server``, ``amp-access`` stuff & authorization, pingback and login URLs). Otherwise, when handling a direct access, VC will execute the paywalling logic and based on the result the full or teaser version will be delivered (in both cases with ``type=other``, no ``amp-access`` stuff & only the pingback and login URLs). So, yes, the CMS needs to be able to build three different versions of the same AMP document when using the server mode, but that's the price you need to pay to avoid bottlenecks in you caching layer. The only problem here is how to transport the result of the authorization to the client side when ``type=other``. A modification to the HTTP body is possible in VC to embed the JSON, but how to use it in the AMP Runtime?

Hope this helps to understand the scenario and limitations for VC-based paywalls (and probably also for other similar auth proxies) running AMP in server mode.

**Comment by dvoytenko** [comment]
Thanks, @carlosabalde . I think I got a pretty good grasp on it now. Let me check with our privacy/security to see if anyone has any problems with allowing authorization response to be transferred in the content. We do already provide `authorizationFallbackResponse` so we can, in theory, just build on this.

**Comment by dvoytenko** [comment]
@carlosabalde, sorry for delay. I reviewed this idea and I think we are ok extending `type=other` and `authorizationFallbackResponse` the way we discussed, provided the following conditions are met:

1. This is exclusively done for direct (non-cdn.ampproject.org) document requests.
2. Documents are served with cache-control private

We, of course, have only very minimal options for enforcing this. But provided these constraints we part of the spec - what do you think?

**Comment by carlosabalde** [comment]
We've discussed this and we think it's a good solution for proxy-based paywalls. A simple ESI substitution could be executed in the caching edge of the publisher to inject the ``authorizationFallbackResponse`` value when handling non-CDN accesses to AMP documents using the ``server`` option. We'll try to implement a PoC during the next weeks.
