### ISSUE TITLE
STAMP: Always set theme color to background color

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#19203]
For STAMP documents that do not have a theme color, STAMP should set it to the same color as the background color.
https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android

We should consider making theme color meta tag mandatory for standalone STAMP

**Comment by newmuis** [comment]
We have a primary accent color (generally a brand color, not a per-story color), that is optional.  Most publishers do not set background colors on a per-story or per-page basis.

We can set it to the accent color, but we'll need a fallback.  Making this mandatory is definitely an option, but it would be a breaking change, and I'm not sure how much we stand to gain from it?

**Comment by newmuis** [comment]
@bramanudom The accent color comes from a CSS variable called `--primary-color`.  We can [read the CSS variable](https://stackoverflow.com/questions/41725725/access-css-variable-from-javascript) and use it to output the theme color meta tag described in the [document Malte linked above](https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android).

**Comment by cramforce** [comment]
@bramanudom I was looking at a few stories where this wasn't really working (e.g. https://www.cnn.com/ampstories/us/lets-celebrate-national-mutt-day but WaPo has a similar issue). They don't seem to use the primary-color but instead just use `amp-story,amp-story-page{background-color:#000}`.

Would it make sense to add support for that? Since we already call `getComputedStyle` we could just check if instead the actual background color is different.

**Comment by bramanudom** [comment]
I will investigate the story where this isn't working, though just to be clear because these sites don't use primary-color, not working means that the toolbar doesn't have the light-gray default color, correct?

In terms of adding support for setting the theme-color to match the background color, that does make a lot of sense to me. However, in the first go-around I did consult Hong who suggested the light-gray default color, and I'm wondering if defaulting to a publisher's background-color could pose potentially bad UI.  

For example if a publisher's background-color is set to be white, since we know that either the publisher logo or the Google logo would also show up on the toolbar, Hong did mention a potential white publisher logo edge case.

**Comment by cramforce** [comment]
In any case the body-background case should be equal to the `theme-color`. That is because in notch phones you'd sometimes see either of them. Right now it looks really ugly with a bright color notch.

**Comment by newmuis** [comment]
In practice, many publishers set neither the body nor `amp-story` nor `amp-story-page` background color.  We could use the `amp-story-page` background color, then think about adding an image processing transform in the AMP cache that finds the dominant color of the background image and uses that on the page, although there are some complications there.

How about we start by just using the `amp-story-page` background color for now, falling back to the accent color, falling back to our default gray?  This would decouple the frontend work from any such support from the cache.

The downside here is that, again, in practice, this largely won't change anything, since many publishers do not specify background colors.

**Comment by cramforce** [comment]
SG. One more thing though: How about defaulting to black?

**Comment by bramanudom** [comment]
Defaulting to black sounds good to me, but I'm looping in @hongwei1990 since I had originally talked to her when selecting the default light-gray color.
