### ISSUE TITLE
FR: amp-form conditional variable substitution

### ISSUE THREAD

**Issue by caiotomazelli** [ampproject/amphtml#19298]
Today we have something like "conditional var substitution" with the [data-amp-addparams](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#appending-parameters-to-the-href) attribute for links.

I'd like to achieve a similar conditional behavior with form inputs.

My use case is the following: I'd like to check if a query param is present at the URL. If so, i'd like to add a query string parameter to the form request. It would work very similarly to how data-amp-addparams work for links. Something like the following:

#### Proposition 1
`<form method="GET" action="/get" data-amp-replace="QUERY_PARAM" data-amp-addparams="QUERY_PARAMS(gclid)" target="_top">`

Right now I can implement this behavior with a hacky way of checking if the query parameter is present in the URL or if it is empty. You can read the [source code](https://gist.github.com/caiotomazelli/ad8a554e76c43f3327e09d74e5552a06) and test the two demo variations: [with gclid in the url](https://output.jsbin.com/kaxotal?gclid=asdasd) and [without gclid in the url](https://output.jsbin.com/kaxotal)

To test it, it suffices to write something the input to trigger state binding and click in the "OK" button.
Only the variation with a gclid on the query parameter will pass the parameter forwards in the form request.

This method would be ok if there was a better way to inspect the QUERY_PARAM with an action. Something like:

#### Proposition 2
`<input on="input-debounced:AMP.setState({gclid: QUERY_PARAM(gclid)})">`

-------
Any thoughts? Is there any specific known blocker for proposition 1 and/or 2? If not, I could start working on a PR for 1, which should be simple.

**Comment by torch2424** [comment]
Triaging to @cvializ 😄 Feel free to move anywhere else.

**Comment by cvializ** [comment]
Hey @caiotomazelli thanks for opening this feature request! 

If I understand correctly, the server that receives the form request will trigger different behavior if the `gclid` queryparam is empty vs if the `gclid` queryparam is absent, is that correct?

The `data-amp-addparams` still adds the empty queryparam if the value is not present in the original URL so I believe that it is not conditional like you describe. Do you have a link to a document where `data-amp-addparams` behaves like you want?

Since there is a workaround I will prioritize this as "when possible" but if you would like, you can propose this in the AMP design review. @choumx might have opinions about the feasibility / security considerations for the second proposal.

**Comment by caiotomazelli** [comment]
Hey @cvializ, thanks for your reply!

I was under the impression that the "dynamic" part of `data-amp-addparams` was about checking for non-existence, but you're right, proposition 1 does not work as I thought. Actually, what I need ("test for null or empty string") is covered by amp-bind expressions, so something like proposition 2.

I will wait for any considerations that @choumx might have before going ahead and proposing something in the AMP design review.

Thanks again!
