### ISSUE TITLE
Allow publishers to set Google Analytics cid for the AMP GA tag

### ISSUE THREAD

**Issue by R-O-P** [ampproject/amphtml#1940]
This will allow publishers to track known visitors (Once we have IDs for) with the same ID as we do on our site.
@rudygalfi

**Comment by avimehta** [comment]
@rudygalfi please assign this to me.

@cramforce I am planning to move the client id into its own var for GA so that publishers can set it to whatever they want. One wrinkle in this solution is that the client id that is shared with doubleclick and adsense is hardcoded to use a cookie name. Can you think of any way to solve that? 

One solution I can think of is to add an API to amp-analytics that returns value of vars based on the config. For this case, the var will be client id and the ads tags can request for the var from analytics tag. One wrinkle here is that there can be multiple amp-analytics tags. How do the ads tags know which amp-analytics tag to request the value from?

Any other suggestions?

**Comment by cramforce** [comment]
We could map ad tags to vendor configs.

**Comment by avimehta** [comment]
but in this case, the publisher config will define the client id. Are you suggesting that we look at the first amp-analytics tag of a given type and use vars defined in that? 

@R-O-P is from nyt btw. I asked him to open the issue so that we can track it on github.
