### ISSUE TITLE
amp-experiment doesn't work in PWA mode

### ISSUE THREAD

**Issue by egianco73** [ampproject/amphtml#19434]
Hi we have an issue with 
```
<amp-experiment>
```
when an AMP document is injected via 
```
<amp-viewer> 
```
in a Progressive Web App.

Within AMP document we have configured:
**1)** the library:
```
<script async custom-element="amp-experiment" src="https://cdn.ampproject.org/v0/amp-experiment-0.1.js"></script>
```
**2)** the json configuration, like this:
```
<amp-experiment>
  <script type="application/json">
    {
      "button-experiment": {
        "variants": {
          "pw-with-button": 70,
          "pw-local": 30
        }
      }
    }
  </script>
</amp-experiment>
```

**3)** we are using the runtime variable VARIANTS

**The problem we noticed:**

once an amp page using amp-experiment is injected in the shadow dom
the variable VARIANTS isn't resolved and the following error appears in console:

**To use variable  VARIANTS , amp-experiment should be configured**

while in the amp-page everything is working properly.

The error is thrown by shadow-v0.js

Could you please check?
Best Regards

**Comment by torch2424** [comment]
Assigning to @lannka since you are listed as a code owner of the `amp-experiment` extension 😄

**Comment by enzo-giancola** [comment]
Hi,

related to the same problem with

```
<amp-experiment>
```

when an AMP document is injected via

```
<amp-viewer> 
```

in a Progressive Web App

we can see that CSS conditions in order to hide/show variant elements aren't working.

For examples, using Override variant allocation within AMP VIEWER:

https://example.com/progressive-web-app-sample-path/amparticle#amp-x-experiment=none

components related to a variant are still visible.

Instead, with the related AMP version: 

https://example.com/amp-sample-path/amparticle#amp-x-experiment=none

components related to a variant are not visible (AMP behaviour is working fine).

As from the documentation (https://www.ampproject.org/docs/reference/components/amp-experiment):

"Experiments with no variant allocated are ignored."


Could you confirm that the fix will solve also this issue?

Best Regards

**Comment by prateekbh** [comment]
I am not completely aware of what amp-viewer does but since it again deals with [iFrames](https://github.com/ampproject/amp-viewer/blob/master/mobile-web/src/viewer.js#L83) which means the document is not attached on the actual body, I guess this should fix it. I'll try to verify this tomorrow.

@choumx can you confirm my assumption  about the working of amp-viewer?

**Comment by choumx** [comment]
@enzo-giancola Can you share a page that has this bug so we can verify?
