### ISSUE TITLE
Edit amp-sidebar to default to side="right" for stories

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#19471]
If the `side` attribute is unspecified, `<amp-sidebar>` defaults to the "start" side for regular AMP documents (`left` for left-to-right languages, and `right` for right-to-left languages):

https://github.com/ampproject/amphtml/blob/37d3aed564ea0875fd08e4f629d8401668500dd1/extensions/amp-sidebar/0.1/amp-sidebar.js#L118-L121

For stories, we would like it to default to the "end" side  (`right` for left-to-right languages, and `left` for right-to-left languages).  It would be great if it were possible to override this.

/cc @alanorozco @bramanudom 
Part of #16532

**Comment by alanorozco** [comment]
@cathyxz 

For consistency with `amp-video`, `amp-sidebar` should configure itself when it finds an amp-story parent by `closest`.

Better configuration scanning could be done in the future but I would appreciate if we follow this pattern for now to be able to refactor later.

**Comment by newmuis** [comment]
@alanorozco does it make sense to factor out the `closest` check either to a util or a `BaseElement` call?  Then we can change the definition in one place

**Comment by alanorozco** [comment]
Sure, a utility makes sense. Filed #19475 to get started.

**Comment by newmuis** [comment]
We should be able to just add an `if` to the `amp-sidebar.js` snippet above using the util that @alanorozco added in #19475.

@bramanudom, would you mind taking a look?

**Comment by bramanudom** [comment]
Thank you @alanorozco for doing the work to create a util for use in both amp-video and amp-sidebar!

I do have one thing I wanted to point out though. From the mocks [here](https://github.com/ampproject/amphtml/issues/16532#issuecomment-427419206), it seems like the amp-sidebar is actually placed not within an amp-story-page but as a sibling, within the overall amp-story tag. 

Because of the util checks for the [amp-story-page tag specifically](https://github.com/alanorozco/amphtml/blob/903e7ff928eb4b58f52244f446afcfbab47858d4/src/utils/story.js#L28), it's expectedly not doing the right checks when used in amp-sidebar. 

@newmuis Is my assumption about the sidebar tag placement correct?

**Comment by newmuis** [comment]
Yep, that sounds correct.

@alanorozco, can we change the [`descendsFromStory`](https://github.com/alanorozco/amphtml/blob/903e7ff928eb4b58f52244f446afcfbab47858d4/src/utils/story.js#L28) implementation to check for `amp-story` rather than `amp-story-page` to account for this?  (despite the small performance hit)
