### ISSUE TITLE
Custom JS on form submit failure

### ISSUE THREAD

**Issue by srehanuddin** [ampproject/amphtml#19575]
I have to run some javascript code if i got some specific type of error on form submit.

JS code will check response status and message, and then check web page open in android or ios webview and some js function exists or not which inserted by parent app (android or ios), if this function exists call that function with response text.

Are you planing to introduce this type of feature?

**Comment by torch2424** [comment]
Triaging to @cvializ Since it involves amp form 😄 Feel free to reassign.

Though, currently AMP does not support custom / external JS. We suggest using out components to accomplish your tasks and build your UI. If you could provide some sample code of what you are trying to do that would definitely help us steer you in the right direction.

Thanks! 😄

**Comment by cvializ** [comment]
hi @srehanuddin! I believe WebViews can intercept responses and evaluate their own JS in the context of the document, so it sounds like you can do this just like you would with any other document. WebViews are able to inspect the content of responses, so the WebView could inject the function call with the response text after it receives the response.

I don't believe AMP is planning any features to integrate with scripts injected by WebViews. To me this seems like it's outside the scope of AMP in general so I don't expect it to be worked on soon, but I'll leave this open to track the conversation if this becomes a priority later.

**Comment by srehanuddin** [comment]
Hello @torch2424 please check sample code which i am using in my non amp app.

`$.ajax({
                    method : "POST",
                    url : "",
                    dataType: "json",
                    contentType: "application/json",
                    headers : headers,
                    data : data
                }).done(function(res) {

                    if(res){
                        
                    }

                }).fail(function(res) {
                    if(res.status == 409){
        
                        //some code 

                    } 
                    else if(res.status == 400 && res.responseJSON && res.responseJSON.errors && res.responseJSON.errors.length){
                        for(var i = 0; i < res.responseJSON.errors.length; i++){
                            if(res.responseJSON.errors[i].source.parameter == "some str"){
                                
                                if (window.myMethod && window.myMethod.closeView){
                                    window.myMethod.closeView(res.responseJSON.errors[i].title);
                                }

                            }
                        }
                    }
                }).always(function() {
                    
                });`

**Comment by torch2424** [comment]
@srehanuddin Thank you for that!

In this case, I think what @cvializ said definitely applies to your use case. And I think it may be best for you to go down that route.

Thanks! 😄

**Comment by cvializ** [comment]
@srehanuddin if you only need the page to react to the response of the form submit, you can use the [`amp-form` `submit-error` action](https://www.ampproject.org/docs/reference/components/amp-form#to-render-a-successful-response-with-data-binding) and [`amp-bind`](https://www.ampproject.org/docs/reference/components/amp-bind#initializing-state-with-amp-state) and the [`amp-list` [src] binding](https://www.ampproject.org/docs/reference/components/amp-list#src-(required))

```html
<!-- amp-state stores the response data -->
<amp-state id="response"><script type="application/json">{}</script></amp-state>

<!-- the button opens the lightbox view -->
<button on="tap: lightbox-view.open">Show lightbox</button>

<!-- the lightbox displays the form and closes when the form experiences an error -->
<amp-lightbox id="lightbox-view" layout="nodisplay">

  <!-- the form passes the error response to the amp-state variable -->
  <form 
    method="POST"
    action-xhr="/my/form/action"
    on="submit-error: AMP.setState({response: event.response}), lightbox-view.close;">
    <!-- add your form elements -->
  </form>
</amp-lightbox>

<!-- the amp-list renders the data that the form stores in the response variable --> 
<amp-list [src]="response" layout="fixed-height" height="100" hidden [hidden]="!response.errors.length">
  <template type="amp-mustache">
  {{#errors}}<p>{{title}}</p>{{/errors}}
  </template>
</amp-list>
```

You will have to make this work on your own with your exact server response. I'll close this since now it appears that your goal is already possible within AMP.
