### ISSUE TITLE
Allow relative URLs for amp-bodymovin-animation

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#19672]
Any particular reason why `amp-bodymovin-animation` must take absolute URLs?

This was also noticed [at launch](https://twitter.com/DigitalPrasar/status/982488497876537345) and I have a partner hosting an animation who ran into this issue.

**Comment by nainar** [comment]
Closing due to lack of feedback in >1 month

**Comment by bogdangoie** [comment]
Hello,

I'm working on a project using AMP and noticed that AMP Validation fails if a relative URL is used with `amp-bodymovin-animation`. 

Why is it required for an absolute path to exist? Seems to work fine with relative paths but I am concerned  that because the validation fails, we'll have issues with the CDN not accepting the website if the url to the JSON file is relative.
