### ISSUE TITLE
amp-sidebar animations don't respect the CSS transition properties.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#19777]
## What's the issue?

`amp-sidebar` animations doesn't seem respect the CSS transition properties, except for the first time you open it.
It will animate correctly the first time you open the sidebar, but then animate very fast and ignore any specified CSS, for both the open/close animations.
Also, it looks like it changes the width of the document/body (probably because the scrollbar disappears?).

## How do we reproduce the issue?

The example at `/examples/sidebar.amp.html` reproduces the issue.

**Comment by newmuis** [comment]
I think the new timings are general and could be used anywhere, but @gmajoulet would probably have more insight.

/cc @bramanudom

**Comment by andrewwatterson** [comment]
As far as the bug goes, this appears to be happening due to the order that the `amp-sidebar` mask element is being hidden/shown. If you move the calls to `open/closeMask_` from `updateForOpening/Closing` to `updateForOpened/Closed`, this issue fixes itself. That said, I can't tell from the actual `open/closeMask_` logic why this would be happening, and I've exhausted my pretending-to-be-an-engineer time budget on this. :)

As far as the actual animation curves we use - a helpful comment in the CSS points to https://goo.gl/AGFioO - we're using the same sidebar timing/curve as the Google PWA App Shell. The curve (`233ms cubic-bezier(0,0,0.21,1)`) is similar to (if faster than) your ease-in curve, and it doesn't look like we have a different curve for the closing.

My instinct is that having two different curves would be more elegant, but I'd want to understand our relationship to PWA App Shell (which, if it's trying to be all app-like probably does it the way Android does sidebar animations, which also seems desirable).

But the curves aren't `important`'d, so I suspect fixing the bug will also give you the ability to override them.

**Comment by signalcat** [comment]
Hi, I made an attempt to fix the transition interrupt bug with https://github.com/ampproject/amphtml/pull/19811. @cathyxz  @aghassemi please feel free to take a look. Deferring the animation discussion to those more knowledgeable on the thread.
