### ISSUE TITLE
Timing and invalidation of authorization requests

### ISSUE THREAD

**Issue by jugglingcats** [ampproject/amphtml#2004]
Apologies if this is already covered in the documentation. I couldn't find it.

It would be useful to know if the authorization endpoint is intended to be called prior to the user following an AMP document link. For example, will the client request authorization for some/all links in a search results page? If so this has a few implications:

- Potentially significant increased load placed on the authorization endpoint. This may have a commercial impact for some publishers using a vendor with tiered pricing based on number of API requests

- After viewing a document and calling the pingback url, it will be important to invalidate any previously fetched authorizations, because in a metering scenario any previous decision might be incorrect after one of the documents is viewed. There might be a scope issue here: would the client invalidate ALL authorization decisions, including those potentially from other sites which are completely unrelated?

- There are times when invalidation is not strictly necessary, for example if the user is a subscriber. Unfortunately using cache directives in this case would be problematic because the response is personalised to each user, unless AMP Cache could use the reader id as a cache key. This would be possible using a Vary header in the authorization response, but only if the reader id was passed as a header as well as a parameter, and if AMP Cache supports Vary of course

If the authorization endpoint is always called as part of the actual rendering process, most of these considerations don't apply.

**Comment by rudygalfi** [comment]
cc @dvoytenko

**Comment by dvoytenko** [comment]
@jugglingcats Thanks for the questions. Here are my responses:

> Potentially significant increased load placed on the authorization endpoint

The authorization endpoint is called as soon as possible, but it's called by runtime and thus never by any other system itself. I.e. it'd not be automatically called for search result links - only when the document is either navigated or prerendered. This is no different from, say, what sometime ago was envisioned by the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) in browsers. So, we definitely expect a slight increase in traffic to this service due to prerenders, but not a huge one. But on the plus side:
 1. Users will see the content sooner without visibly flickering.
 2. When publishers combine auth calls and page re-filtering: auth calls by themselves should be notably  cheaper.
 3. Auth calls are expected to be only read calls, since pingback is used for writes. Reads are typically cheaper than writes.
 4. Caching can be used. More on this later.

> After viewing a document and calling the pingback url, it will be important to invalidate any previously fetched authorizations

Correct. AMP Runtime currently performs invalidates. Invalidates are only done per source origin (e.g. publisher1.com). How much this would affect traffic to the auth service depends on the app. E.g. in case of Google Search, where a lot of different sources are combined and ranked independently, the likelihood that there are two articles currently in memory (e.g. prerendered) from the same publisher is somewhat small and it progressively smaller for 3, 4, 5, etc articles.

> There are times when invalidation is not strictly necessary, for example if the user is a subscriber. Unfortunately using cache directives in this case would be problematic because the response is personalised to each user, unless AMP Cache could use the reader id as a cache key.

The caching can certainly be used for auth responses. Currently, with `type=client` access setup, only AMP Runtime ever queries and sees authorization response (not AMP Cache), and if it has cache headers, they will be respected. 

In the future `type=server` access setup where the auth response will travel via AMP Cache, I can't yet say if we'd respect cache headers or not. But if AMP Cache does cache them - it'd only cache them by the complete URL including READER_ID. That, of course, assumes that READER_ID will be in the URL. If we do elect to do so - my guess is that we will require authorization URL to include READER_ID for `type=server`.

**Comment by jugglingcats** [comment]
Thanks @dvoytenko I appreciate your taking the time to respond - everything makes sense. We will wait and see what happens to the authorization endpoint load ;-)

**Comment by dvoytenko** [comment]
Thanks @jugglingcats! I'll close this bug for now, but please re-open with any other questions.
