### ISSUE TITLE
Should we Preload the cdn.ampproject.org Javascript Modules?

### ISSUE THREAD

**Issue by ayumihamsaki** [ampproject/amphtml#20150]
I would like to find out if it's a good idea or not to preload all the cdn.ampproject.org Javascript Modules. 

When I ran some tests I got the following results, repeated the test on several web pages and got the same results, these are as follows:

## Without Preload

![not-preload](https://user-images.githubusercontent.com/17784082/50697749-084eaf00-103b-11e9-87f6-8f20ec62f505.png)

Results: The On load and Document Complete times were 1 second slower than preloading results. Also the more cdn.ampproject.org Javascript Modules you use the bigger the waiting delay - see the last three assets.

## With Preload

![preload](https://user-images.githubusercontent.com/17784082/50697826-3e8c2e80-103b-11e9-8a33-ae2258e9e98e.png)

Results: The On load and Document Complete times were **1 second Quicker** than the non-preloaded results. Also the more cdn.ampproject.org Javascript Modules you use it didn't matter because they all started loading at the same time.

## Notes

These test results were done using webpagetest.org and direct from the server via cloudflare. Using the '**simple test**' and set to a mobile setting of '**3G Regular**', which many Googler's recommend as a good mobile speed test.

I did not test the AMP web pages through Google's CDN and I don't know if Google has setup preloading the cdn.ampproject.org Javascript Modules? Therefore I wonder if it is worth preloading the JS assets or not? Another factor that should be considered is that the AMP web pages are getting upgraded this year with Signed HTTP Exchanges (Web Packaging) and Portals which both may affect preloading features?

I look forward to any insights from the smart people at AMP Project into this.

**Comment by aghassemi** [comment]
Hi @ayumihamsaki 

Yes, it is recommended to preload at least `v0.js` (along with other things such as hero images, etc..)
Please see some details and tips here: https://www.ampproject.org/docs/fundamentals/optimize_amp 

AMP cache does a lot of transformations on AMP documents to optimize them further, including adding preloads for the main `v0.js`. For AMP pages served from origin, of course these optimizations are not applied automatically, so some of the tips in https://www.ampproject.org/docs/fundamentals/optimize_amp would be good to do manually.

Additionally we have also published a tool called `amp-toolbox-optimizer` (https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer) which you can use to apply most of optimizations AMP cache does to your documents when serving from origin. There is also an `express` plugin for it ( https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer-express )

Note that applying the transformations via `amp-toolbox-optimizer` will make the page invalid AMP (since it does server-side rendering as part of the optimizations), so you would need to serve both pre and post transformed pages and pair them together same way you would pair a non-AMP and AMP page.

Hope this helps.

**Comment by ayumihamsaki** [comment]
@aghassemi Thank you for all the information it helps a lot.
