### ISSUE TITLE
Use native overflow-x:scroll for carousel

### ISSUE THREAD

**Issue by markfinst** [ampproject/amphtml#2019]
Native scroller created with `overflow-x:scroll` for horizontal carousel feels much more natural and fast, than trying to imitate all the physics via js and touch events api. 

Also, currently carousel doesn't work in IE, as it supports only Pointer events, not Touch events, this change would fix that.

**Comment by dvoytenko** [comment]
@markfinst Overall I'd like to do this. We'd have to retest this. From what I understand Edge fully supports WebKit's touch event model, even if IE might not. It'd probably be relatively easy to enable IE today. The last time we did a round of tests we determined that the `overflow-x:scroll` had a number issues on different devices including timeliness of events and being able to cancel event propagation when scroll is detected. Please advise if you have some recent tests in these areas.

**Comment by mkhatib** [comment]
@dvoytenko what "timeliness of events" refers to? And what is the use case for canceling the event propagation when scroll is detected in the context of amp?

**Comment by dvoytenko** [comment]
Timeliness: e.g. in iOS it'd be common for scroll events to arrive significantly later after scroll position has changed. E.g. when the touch has been released.

Even cancelation: if we don't call `preventDefault` on touch events - they will propagate all the way to the document's root where they could be used by the viewer, e.g. to swipe to the next document. This part is critical - otherwise, you'd basically be unable to swipe carousel at all.

**Comment by oliverfernandez** [comment]
About timeliness, from iOS 8 Safari scroll events behave very similar to Chrome: they arrive almost instantly while doing scroll

About Event cancellation, one solution could be that the Swipe Gesture that the carousel component creates to work like this:

1. On a swipe gesture do nothing, since we rely on the overflow: scroll. Instead of manipulating the container via CSS transforms, we let the native scroll to kick in.

2. The swipe gesture should only call stopPropagation() for touch events, but not preventDefault(). This way, if the Viewer has also a swipe gesture it won't kick in, but we let the browser to do the native scrolling.

Does this work?

**Comment by cramforce** [comment]
This would also fix the non-ability to scroll on top of youtube, instagram, etc. elements, right?

**Comment by dvoytenko** [comment]
It would, but, as it stands, in a rather narrow case - only for scrolling carousel. Depending on desired transition, slideshow may be impossible to implement via scrolling. And I'd assume that youtube case is more likely to be used with a slideshow. Thus the options are:

1. Redo slideshow using scrolling transition and implemented via overflow-x.
2. Possibly also keep overlay/fade

Generally I think it's definitely worth trying - the benefits are obvious.

P.S. we also need to retest scrolling on iOS. The latest I checked on earlier iOS9 the timeliness of events was very unsatisfactory. Perhaps it's been addressed on iOS9.3 or such.

**Comment by oliverfernandez** [comment]
Yeah, it would only work in case of scrolling, not for a slideshow.

In the slideshow case, we would be talking about CSS Scroll Snap Points, which is a proposed standard: https://drafts.csswg.org/css-snappoints/

Slideshows in amp-carousel is what is being discussed in #2355 right?

**Comment by dvoytenko** [comment]
@oliverfernandez #2355 relates to both scrolling and slideshow carousels.

**Comment by ericlindley-g** [comment]
@camelburrito  — is this issue obsolete after your carousel native scrolling work?

**Comment by camelburrito** [comment]
Yes
