### ISSUE TITLE
amp-bind: textarea's [text] binding loses focus on input

### ISSUE THREAD

**Issue by Bill-SnowWolf** [ampproject/amphtml#20220]
## What's the issue?

I'm trying to use amp-state to cache text values for textarea (textarea is inside a form, then inside a amp-list). When amp-list is refreshed by some other reasons, I would like to set textarea text to cached value.

Example: https://jsbin.com/xaxiwod/edit?html,output

I've tried to bind [text] and "on:input-throttled" event to same amp-state, but this will only allow me to type only one character then textarea lost focus.

Is this working as intended so I need to find other solutions, or this is a bug?

## What browsers are affected?

Only tested on Chrome

## Which AMP version is affected?

1901021931380

**Comment by choumx** [comment]
I think the issue is with the `[text]` binding in your `textarea` element:

1. Input character `x` into the textarea
2. `input-throttled` triggers `AMP.setState({state: {word: 'x'}})`
3. textarea's [text] binding triggers and sets `el.textContent = 'x'`, which causes loss of focus

We can probably fix this. Do you need to have that `[text]` binding on the textarea though?

**Comment by choumx** [comment]
Oh I think I understand your use case. Should be a quick patch.

**Comment by Bill-SnowWolf** [comment]
awesome thanks.
