### ISSUE TITLE
amp-img doesn't suppot unknown sizes

### ISSUE THREAD

**Issue by nahuelange** [ampproject/amphtml#2039]
Hello,

We are implementing amp view for a national daily newspaper. We have a lot of articles, so many images.
In some cases, we don't have all the sizes (width or height), even the aspect ratio. We can't prefetch content before rendenring amphtml, because of too many needed http requests all the time.
Does it exist a lazy layout for amp-img tags? Do you plan to provide one?
Even if the newest articles have image sizes, old ones don't have, so we're not able to have a correct aspect ratio with a valid amphtml markup…
Thanks for all,

**Comment by cramforce** [comment]
We absolutely do not intend to allow not specifying sizes. This just pushes the work you'd need to do, to the client – on every single page view.

You'd need to fetch the images in your CMS and get the sizes from them, just like the client would.

**Comment by mjangda** [comment]
@cramforce In the worst case scenario where we can't determine the size for a hotlinked image (let's say the request to fetch the image failed for some reason), would it be better to a) omit the size, b) force a specific size, or c) just omit the image completely?

**Comment by dvoytenko** [comment]
@mjangda the choice of (b) or (c) one of those options is up to you - depending on your need either could be valid. (a) is not supported at all. One interesting option is to do option (b) and then style image via CSS with `object-fit` property (https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit). Usually this is not recommended since it can display image in a imperfect layout. But in your case this could actually be a good compromise. E.g.
```
<amp-img class="unknown-size" width=300 height=200 src="..."></amp-img>
```

And CSS would be:
```
.unknown-size img {
  object-fit: contain; /* or 'fill', or 'cover', etc */
}
```

**Comment by mjangda** [comment]
Thanks, that's a good idea.
