### ISSUE TITLE
Amp-accordion doesn't navigate to the correct position

### ISSUE THREAD

**Issue by lucky42890** [ampproject/amphtml#20401]
## What's the issue?

I am using amp-accordion component but I found a bug on its navigation.
Please take a look at this. https://jsfiddle.net/oakbthm5/1/

## How do we reproduce the issue?

As you can see in jsfiddle, there are 3 sections. First section's height is very big. In order to reproduce the issue

- Click first section.
- Scroll down to second section
- Click second section

Then it should display second section, where first section is collapsed.
But it is not navigating to the correct position,

## What browsers are affected?

All browsers

## Which AMP version is affected?

1901081935550

**Comment by aghassemi** [comment]
@lucky42890 Thanks for the report. This looks that way because the height of section 1 is much larger than section two and the overall height of the container is fixed. When section 2 is clicked, section 1 is collapsed and section 2 is expanded correctly however we do no change the scroll position on the user. Because the overall container div has a fixed height, the scroll position is still valid.

I am not sure if we want accordion to automatically scroll, changing user's scroll position is normally not a good UX but may be necessary in certain situations. If that's the UX you are okay with, you can implement it yourself using the `expand` event and `scrollTo` action. 

Something like:
```
      <section on="expand:s1Top.scrollTo(duration=1)">
        <h4 id=s1Top >Section 1</h4>
...
```

See an example here:
https://codepen.io/aghassemi/pen/gZJzgz


hope this helps.

**Comment by aghassemi** [comment]
closing per comment above
