### ISSUE TITLE
Elements get built in pre-render mode

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#20580]
An element with `prerenderAllowed = false` should not be built in pre-render mode to preserve privacy, instead it will go to the build queue .
We need to ensure this because some component can make xhr request in `buildCallback()`. 

There maybe a bug: if the document is parsed in prerender mode, the runtime attempts to run the build queue `this.pendingBuildResources_`. 
https://github.com/ampproject/amphtml/blob/7b541fac90d8757d5776293d84bdcc98d465f96f/src/service/resources-impl.js#L276-L281 

https://github.com/ampproject/amphtml/blob/7b541fac90d8757d5776293d84bdcc98d465f96f/src/service/resources-impl.js#L608-L616

@ampproject/wg-runtime @dvoytenko

**Comment by choumx** [comment]
I think the premise is incorrect. 

Historically, we did build elements in prerender mode and it was the callers' responsibility to make sure XHRs waited for viewer to be visible. E.g. in amp-state.js: https://github.com/ampproject/amphtml/blob/39464270aa888000b7692e36f5b8eac302eab516/extensions/amp-bind/0.1/amp-state.js#L49-L56

This has since changed for unrelated reasons:
1. In prerender mode, we no longer build elements that are not allowed to be prerendered. This was to improve utility of our "prerender build quota".
2. We have a check in XHR service that waits for viewer-visible. This was added to make XHR have a safe default after a few privacy bugs. 

Also, is there an actual bug here? Or is this just a question?

[1] https://github.com/ampproject/amphtml/blob/39464270aa888000b7692e36f5b8eac302eab516/src/service/resources-impl.js#L560-L565

[2] https://github.com/ampproject/amphtml/blob/39464270aa888000b7692e36f5b8eac302eab516/src/utils/xhr-utils.js#L204-L207

/cc @jridgewell

**Comment by jridgewell** [comment]
I may have been confused with nesting... It looks like the element is not pushed into the build queue if it's not pre-renderable.

**Comment by choumx** [comment]
Closing, please reopen if you notice a bug.

**Comment by zhouyx** [comment]
Thank you @choumx and @jridgewell for the explaination. @jridgewell is correct that element is pushed to the build queue only if prerender is allowed. 

https://github.com/ampproject/amphtml/blob/62d3b0bcdf568f2d39fe4f71d7023dcf05b7ff9d/src/service/resources-impl.js#L567-L576

I believe, given this it is fine for non pre-renderable element to make xhr request in their `buildCallback`. We no longer need to protect with `Viewer.whenFirstVisible()` manually.

**Comment by jridgewell** [comment]
> We no longer need to protect with Viewer.whenFirstVisible() manually.

Defensive behavior is still good! Please make it explicit that this must wait for viewer visible!

**Comment by zhouyx** [comment]
: ) Sounds good. Thank you for clarifying.
