### ISSUE TITLE
Sidebar in stories animation/design 

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#20625]
I just tried copy/pasting the [example from the `amp-sidebar.md`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-sidebar/amp-sidebar.md#sidebar-for-stories) documentation into a story, and noticed a few non critical design issues:

- There's no animation at all. It seems that the CSS selector relies on a `[side]` attribute that is actually optional
- The width of the mobile sidebar is not set and just adapts to the content size. Should we have a set width?
- The background color of the sidebar is forced to white and not overridable because of the `!important` statement. Given how it would be for publishers to bypass this, we should consider making this CSS rule overridable
- On desktop, the pagination buttons are above the background opacity mask

**Comment by bramanudom** [comment]
Thank you for catching all of this Gabriel! 

I'm about to submit a PR with these changes. Though, for your second point 
> The width of the mobile sidebar is not set and just adapts to the content size. Should we have a set width?

I think that it makes sense that the sidebar width should adjust to its content, especially since we have a set max-width to prevent the sidebar from obscuring the story. Also to my knowledge, there is [set min width via the sidebar component](https://github.com/ampproject/amphtml/blob/master/extensions/amp-sidebar/0.1/amp-sidebar.css#L24), at 45px. 

Do you think that this should be different?

**Comment by gmajoulet** [comment]
Hmm sorry, I just checked the material guidelines and you're right, there's not really any minimum width recommended. We don't have to, but if you think it might look great, we could always set it to 280px on mobile, like we set it to 320px on desktop. Your call!
