### ISSUE TITLE
Improve documentation for specific vendor analytics configurations

### ISSUE THREAD

**Issue by ctbarna** [ampproject/amphtml#2072]
In implementing Chartbeat and Omniture, I found it impossible to find docs from the individual vendors on the provided support links ([Chartbeat's link](http://support.chartbeat.com/docs/), [Adobe's link](https://helpx.adobe.com/marketing-cloud/analytics.html)). The docs might be on the support sites but I couldn't find them.

However, looking at [vendor.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors.js) in `amp-analytics` answered all my questions about implementation. I'm wondering if there is a better way to document individual vendors even when the vendors themselves don't have public documentation.

This could be something like:

- Documenting specific and finite custom variables in the vendors section of the `amp-analytics` docs.
- Linking the vendors section of the docs to individual sections in `vendors.js`.

**Comment by rudygalfi** [comment]
This is great feedback, thanks.

I opened #2430 and #2431 to address the two examples you cited. I also have #2432 to make vendors.js a little more visible in the documentation.

I don't think it will be feasible to keep line links up to date well enough to directly link into vendors.js. In addition, it's a goal to have documentation maintained more on the vendor side rather than here in the project where it's liable to grow out of date. I hope the steps above can improve things, though.
