### ISSUE TITLE
amp-carousel : Load News article with URL Just like amp-next-page

### ISSUE THREAD

**Issue by manjunathkundar** [ampproject/amphtml#20739]
## amp-carousel on change load News article

I am new to AMP and I was exploring an option to load news article in amp-carousel. I found this feature in **amp-next-page** but user has to scroll till the end of page for this. 

Instead, if the same feature introduced in amp-carousel where on slide-next/previous, next/previous news article get loads with URL change without refreshing the page.

Please refer below example 
![carousel](https://user-images.githubusercontent.com/8400700/52480958-2f1c7a00-2bd3-11e9-8dac-fe9a603641e0.gif)

Thanks in Advance!

**Comment by aghassemi** [comment]
Hi @manjunathkundar,

AMPs current recommendation for what you are trying to do is PWA + AMP. https://github.com/ampproject/amphtml/issues/20368#issuecomment-454904925

@nainar relevant for AMP first.

**Comment by manjunathkundar** [comment]
Hi @aghassemi 

Thanks for your reply. Is there any way where I can build this without PWA? by using **onchange** event of AMP slider?

**Comment by aghassemi** [comment]
@manjunathkundar There are lots of nuances when swapping whole documents instead of just some sub-content. Url needs to be updated, analytics events needs to work properly, new scripts may need to get loaded, previous documents needs to be properly dismissed... This is not something I recommend building with amp-carousel.

**Comment by manjunathkundar** [comment]
Thank you @aghassemi!
