### ISSUE TITLE
cannot mark class constructor as private

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#20798]
Bug in `amphtml-internal/enforce-private-props` prevents you from annotating a constructor as `@private`. It wants a trailing underscore, but you cannot change `constructor` to `constructor_`.

```js
class X() {
  /** @private */
  constructor() {
  }
//^ Method marked as private but has no trailing underscore.
}
```

/to @erwinmombay 
/cc @ampproject/wg-infra

**Comment by erwinmombay** [comment]
@cvializ can you explain to me what the scenario is? seems a little odd

**Comment by rsimha** [comment]
I believe the problem stems from here: https://github.com/ampproject/amphtml/blob/c9aa5f4eef0b7a2acf3b199ee824e8fabcb4220d/build-system/eslint-rules/enforce-private-props.js#L57-L66
The rule treats `constructor` like a method and expects a trailing underscore, and `constructor_` is an invalid name.

@cvializ What if you use the `@constructor` annotation instead of `@private`?
https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#constructor

**Comment by jridgewell** [comment]
Constructor's can't be private.

**Comment by cvializ** [comment]
Isn't setting a constructor as private part of the factory pattern?

**Comment by jridgewell** [comment]
`@private` applies to properties of an object, not to the object itself. If you want a private class, don't export the class.

**Comment by cvializ** [comment]
Sounds good
