### ISSUE TITLE
allow-same-origin iframe potential issue with signed exchange

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#20848]
Based on the [paragraph](https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md#security-impact) that @cramforce wrote, redirection within `allow-same-origin` iframe can easily create make the iframe a friendly iframe. 

This won't happen for cached AMP pages because the iframe origin can never be the same as the cache origin. However what about the case with signed exchange?

cc @cramforce @Gregable @aghassemi @lannka @torch2424

**Comment by aghassemi** [comment]
@zhouyx yes, it is a problem. We are tracking a new feature request for Chrome where we "Ensure AMP frames can never mess with their parent (whether or not actually hosted on the same origin)." Some early discussions here: https://github.com/whatwg/html/issues/2757 

Essentially unless we can detect a redirect origin change before the page has a chance to interact with parent ( I haven't tried to find a solution but looks unlikely ), this becomes a blocker for web packaging.

To build on @zhouyx's point, allowing same-origin `amp-iframe` in the current state is technically equivalent to allowing `<script async src=whatever>` in AMP.

**Comment by twifkak** [comment]
cc @ampproject/wg-caching

**Comment by twifkak** [comment]
see also: https://github.com/dtapuska/documentaccess

**Comment by twifkak** [comment]
Quick note that "iframe origin can never be the same as the cache origin" is not true; redirect can evade that too. But cache prevents that resource from being too much of a problem for the unsigned case.

**Comment by dfabulich** [comment]
I was thinking about this bug today, and I think a workaround might be possible without adding a new feature to the web platform.

What if the AMP SXG validator required the SXG to have a `Content-Security-Policy` `frame-src` explicitly allowing all and only the origins of its `<amp-iframe>` elements?

That way, an `example.com` SXG could have an `<amp-iframe>` pointing to `iframe.example.com`, but that iframe would be forbidden to navigate back to `example.com` and thereby become friendly, because CSP would prevent iframes from `example.com`; it would only allow unfriendly iframes from `iframe.example.com`.

Would that work?

**Comment by cramforce** [comment]
I think a problem with such an approach is that it can be extremely difficult to enumerate iframe origins.

In general, AMP would really like to allow same-origin iframes. It also wants to avoid them scripting the parent. Not for security or compliance reasons, but because it would break on the cache in unexpected ways, and AMP aims to avoid documents breaking on the cache in unexpected ways.

That is also why we've so far ignored the "redirect hack" that was always possible for on-origin AMP docs since it wasn't about security, but rather the hosting invariant.
