### ISSUE TITLE
Follow up work from PR #20811 comments - New Travis Build Matrix

### ISSUE THREAD

**Issue by estherkim** [ampproject/amphtml#20887]
Follow up work to PR https://github.com/ampproject/amphtml/pull/20811 - New Travis Build Matrix

- [x] Clean up `build-system/pr-check.js` https://github.com/ampproject/amphtml/pull/20811#discussion_r256934626
- [x] Use `requests` module instead of `curl` https://github.com/ampproject/amphtml/pull/20811#discussion_r256934925
- [x] Fix `stopTimer` logic https://github.com/ampproject/amphtml/pull/20811#discussion_r256935544
- [x] ~~Don't start Travis VMs if job doesn't need to be run~~ https://github.com/ampproject/amphtml/pull/20811#discussion_r257013943 Determined not supported by Travis
- [x] Create dummy PR to test error handling when uploading and download build artifacts https://github.com/ampproject/amphtml/pull/20811#discussion_r257305172
- [x] Create dummy PR to test error handling when checking yarn state https://github.com/ampproject/amphtml/pull/20811#discussion_r257308693
- [x] Restrict read/write permissions at storage location to Travis 
- [x] Investigate using Xenial instead of Trusty VMs
/cc @ampproject/wg-infra

**Comment by rsimha** [comment]
A few more I can think of:

- [ ] Make `gulp dist --fortesting` optionally run in a new `build` stage job during push builds
- [ ] Upload / download `dist` output during push builds so that tests are run in `--compiled` mode
- [ ] Use a Windows Travis VM for one or more or the test jobs, to get coverage on local Chrome / IE on Windows

**Comment by estherkim** [comment]
Closing now that all tasks are complete.
