### ISSUE TITLE
Demo viewer.html does not put documents in visible state after sending visible message

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#20892]
Steps to repro:
1. Change one of the documents in `examples/viewer.html` to be `../test/manual/amp-carousel-0-2/vertical.amp.html`
2. Also change the initial page to be the new page.
3. Navigate to `localhost:8000/examples/viewer.html`

Expected behavior:
4. The carousel page transitions through the prerender and visible states correctly and the components get built.

Observed behavior:
5. The carousel page gets stuck in the prerender state and the components do not get built.

Toggling the visible/prerender button causes the document to transition to the visible state and the component to build.

I believe this is due to the demo viewer sending the visible message before the document is able to receive messages. Adding a `setTimeout(() => showContainer('9'), 4000)` allows the elements to build, but I have not found the correct specific event to wait for.

/cc @choumx @aghassemi

**Comment by alabiaga** [comment]
Carlos, I got this to work with no issues. Though I didn't realize at first that I had to enable the experiment 'amp-carousel-v2' as well. Let me know if this is still an issue. I tested it on chrome and safari. I remember you not being able to get this to work when you showed me and then getting it to work via some interaction but perhaps you've made some things changed since then?

**Comment by cvializ** [comment]
Thanks for taking a look : ) I was able to make a change to work how I expect it. I'll mention you in the PR and you can lmk if it looks right
