### ISSUE TITLE
Consider making amp-list fallback mandatory in future version

### ISSUE THREAD

**Issue by fstanis** [ampproject/amphtml#20960]
## Describe the new feature or change to an existing feature you'd like to see

I've come across a lot of cases where an `amp-list` that fails to load has no suitable fallback, resulting in just an empty white box when the server returns an error. This creates a confusing user experience, since it's often unclear if the list returned no items or an error occurred.

I think the fallback should become mandatory in the future. The developer can still choose not to have a fallback by using an empty one (`<div fallback></div>`), but this forces them to make it a conscious choice rather than a hindsight.

## Describe alternatives you've considered

- Having a built-in fallback (like the web browser's "broken image") if none is specified. This is probably viable, but would perhaps confuse users since there's no well-established convention (unlike for images).

- Having this as part of some future linter / warning system that doesn't make it invalid AMP. This requires changes to how validation works, so may not be viable.

## Additional context

Since this change would make existing AMP pages invalid, it can't be added without a version bump. I propose it be considered for a (tentative) amp-list 0.2.

**Comment by cathyxz** [comment]
I think this is a good idea. Especially since we are actually in the process of designing amp-list v2 right now. I wonder if we could go one step further and actually provide a default fallback for amp-list, since practically speaking, if we allow an empty `<div fallback></div>`, it's very likely that a lot of people will just put that or copy our default example. @andrewwatterson what are your thoughts on a default fallback? Does that work or not really?

**Comment by andrewwatterson** [comment]
I'm into it! Does this need to be on my radar in the short term, or is this an amp-list v2 thing that will happen someday?

**Comment by cathyxz** [comment]
We need to know go / no go within a sprint or two and if go, final designs by end of next quarter (July) should be fine.
