### ISSUE TITLE
Unmute some performance tests

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#21062]
Muted by #21061

@ericandrewlewis could you pls take a look?

**Comment by ericandrewlewis** [comment]
I can't reproduce the error myself (here's [notes on that](https://gist.github.com/ericandrewlewis/ff5462e9e5b40d2f0817c6fabf990915)), but I understand the problem.

Webkit validates the entryTypes passed to a call to `PerformanceObserver.observe()` like this:

```js
perfObserver.observe({entryTypes: ['some', 'entry', 'types']});
```

If it sees all entryTypes are invalid, it throws a TypeError.

This is the case in our tests, where we stub properties on the window object to pretend that APIs like Event Timing exist in order to test the implementation of our metrics collection. Since these APIs don't actually exist and fail this validation, we see the TypeError in Safari.
