### ISSUE TITLE
[FEATURE REQUEST] <amp-date-picker> Takes on the full screen on mobile viewports

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#21203]
Taking a look at Priceline:

https://www.priceline.com
Versus on their AMP page here
https://www.priceline.com/hotel-deals/amp/c3000016152/US/New-York/New-York-Hotels.html

Their canonical date picker 

1. Opens as a full screen on mobile whereas the desktop experience shows inline. 
2. Shows a vertically scrollable calendar

**Comment by cvializ** [comment]
Right now the amp-date-picker component supports both of these modes of interaction, but not in the same date-picker element. This is a technically difficult challenge since the AMP element `layout` is and even tree structure is fundamentally different, e.g. `<amp-date-picker fullscreen>` needs `layout="fill"` and to be inside of an `<amp-lightbox>`. `<amp-date-picker number-of-months="2">` does not display well on mobile. Additionally, we would need to spec the transition from one state to the next if the user changed the screen width from a desktop to a mobile resolution.

Currently how we'd implement this is that the form would contain two amp-date-picker elements that show for a given media query. I can give markup examples if needed.

**Comment by nainar** [comment]
Let me reach out to stakeholders and see how that goes?
