### ISSUE TITLE
Add support for itms-services protocol 

### ISSUE THREAD

**Issue by MohammedKaludi** [ampproject/amphtml#21225]
Need to allow support for itms-services protocol for anchor links, so users can serve iOS apps.

https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2922

**Comment by torch2424** [comment]
Did some research into this, most of the context is in the original link (thank you @MohammedKaludi ), and the idea here is that we are blocking the `itms-services` protocol (itms-services://) in our links. However, this protocol is used to link to iOS apps. Thus, it probably has something to do with out allow list. 

Triaging to @choumx since they have the most context on our allow list for things like this, feel free to re-assign. 😄

**Comment by torch2424** [comment]
Also adding @aghassemi to see if we can get their input as well 😄

**Comment by choumx** [comment]
This is a validation error:

> Invalid URL protocol 'itms-services:' for attribute 'href' in tag 'a'.

**Comment by Gregable** [comment]
Do you have any documentation on what this protocol is about that you can point us to? I can only find some stackoverflow discussions and so forth that don't fully explain it. It sounds like it installs and executes an app on device from my read, which I'm not sure we would want, in the same way as we don't want javascript execution. Some documentation would help immensely to understand this.

**Comment by torch2424** [comment]
cc @iamafu @MohammedKaludi @MARQAS 

See @Gregable 's comment above. As well as your use case / user flow would be really handy in understanding how this would work in AMP pages 😄

**Comment by ahmedkaludi** [comment]
@Gregable Here's a good one for you: https://github.com/nifcblm/AHPP-iOS-App/wiki/How-to-distribute-enterprise-iOS-App

I think it helps us understand it

**Comment by honeybadgerdontcare** [comment]
This was add in June 2019 via cl/252863575 and sync'd to GitHub in pr #22925
