### ISSUE TITLE
autodeploy PRs to firebase or glitch

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#21258]
There are a lot of cases where automatic deployment of PRs to a publicly accessible URL would be nice. E.g. when working with other people across timezones who need to try it out, mobile testing, etc. We currently have a firebase deployment in gulp. We could relatively easily do a `git diff master`, build only extensions edited, and then deploy to `firebase`, `glitch`, or `app engine` for each PR.

**Comment by aghassemi** [comment]
if cost is an issue, having a link in the PR CI report to manually create it would be nice as well.

**Comment by rsimha** [comment]
Today, we zip and upload the output of `gulp dist --fortesting` between build stages of every CI build. There's a link in the logs that can be used to download the binaries. For example, here: https://travis-ci.org/ampproject/amphtml/jobs/539431246#L1086

@aghassemi @cathyxz Will this serve the purpose here? Or is this irrelevant now that `gulp dist` is significantly faster, and can be done in 2-3 minutes locally?

**Comment by aghassemi** [comment]
awesome, then we just need a CI step to upload those somewhere and put a link to it in the PR. @alanorozco suggested Netlify

**Comment by rsimha** [comment]
Before adopting a new tool, I think it's worth discussing whether this ought to be done once per commit to `master`, or whether the upcoming nightly builds are sufficient to serve the original purpose.

For example, if you'd like to get someone external to try out a new feature, simply ask them to opt in to nightly builds, and they'll automatically receive that day's build.

/cc @danielrozenberg who is working on nightly builds, and @estherkim who wrote the code to zip and upload the build to GCE during CI

**Comment by aghassemi** [comment]
This feature is more about ability to demo and test a PR that's in review. (e.g. reviewer can play around with the code is doing on a hosted site).

We don't really need to (actually shouldn't) create a site for every PR, if there is `on-demand` button, it would be more than enough.

**Comment by rsimha** [comment]
Gotcha. In that case, I agree that on-demand deployment is the way to go. I don't think this should even be a part of normal CI.

Here's my proposal:

- [ ] Create a new task `gulp deploy-travis-pr-build` (pick a sensible name :smiley:)
- [ ] Take an argument `--build` for the build number
- [ ] Download `amp_dist_<build_number>.zip` from `gs://amp-travis-builds` (does this need authentication with GCE?)
- [ ] Unzip to a local directory and deploy to the service we decide to use (probably needs authentication with the service)

Would this work?

@estherkim assigning this to you since you're most familiar with the code for authentication / upload / download.

**Comment by estherkim** [comment]
Happy to take a look. Might deviate from your proposal to keep everything hosted remotely but I agree this could be super useful for any contributor/reviewer.

**Comment by estherkim** [comment]
This was fixed with multiple PRs, the last ones being https://github.com/ampproject/amp-github-apps/pull/317 and https://github.com/ampproject/amphtml/pull/23513

And here's a working demo, https://github.com/ampproject/amphtml/pull/24274
