### ISSUE TITLE
Stories analytics variable "storyProgress" never reaches 1

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#21325]
## What's the issue?

In AMP Stories Analytics, the `storyProgress` substitution variable never reaches 1, even when viewing the last page of a story.

`storyProgress` seems to be calculated as `storyPageIndex/storyPageCount`, instead of `(storyPageIndex + 1)/storyPageCount`.

Let's take the extreme example of a single page story. `storyPageIndex = 0` and `storyPageCount = 1`, so currently `storyProgress = 0`. It would make way more sense to have the progress being 1 as the entire Story has been viewed.

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Build an AMP story with a single page
2. Setup amp-analytics
3. Create a trigger with `"on": "story-page-visible"` and sending the `${storyProgress}` substitution variable.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

I think this has always been broken.

**Comment by newmuis** [comment]
Thanks for the report!  This is true, but I am not sure whether the alternate definition you have provided is optimal (e.g. with your definition, it would be equally valid to file an issue "Stories analytics variable `storyProgress` is never 0").

Instead, I propose that when the user navigates on the last page of the story (triggering the bookend, and the `story-bookend-enter` event), we also update the `storyProgress` to 1.  This seems more accurate since, for example, if there is a video on the last page of the story, a `storyProgress` of 1 would indicate that the user has completed viewing the story, despite not having had the chance to view that video.

@cpauwels does this work for your purposes?

**Comment by cpauwels** [comment]
The main question of this issue is if a story progress can ever be `0`. When a Story is showed, is it not by definition already started?

As for the bookend, I'm not considering it part of the Story, as it is used for recommendations, for credits, etc, but has no true semantic value to the Story.

Comparing Stories to a webpage: is a fictive `articleProgress` equal to the `viewportHeight / pageHeight` (e.g. 720px/2000px), or `distanceScrolled / pageHeight` (0px/2000px). And if that page height is equal to the viewport height, does `articleProgress` make sense with 0 as a value?

And here are a few edge cases I'm thinking about that could maybe help in making a decision:
* With a single page story (which I guess will be quite common with AMP Story Ads within AMP Stories), `storyProgress` will always be 0 as no bookend will be shown.
* With stories of any length, where the viewer clicked on a CTA on the last page, `storyProgress` will never reach 1 even if the viewer did in fact watch the entire story and even acted on it.
* With story analytics and metrics. It's impossible to set KPIs as a percentage of completion (say, how many people viewed at least 80% of a story) as no viewer in stories with 5 pages or less will match that query.

All these issues could be solved if `storyProgress` is `]0, 1]` instead of `[0, 1[`.

What do you think?

**Comment by newmuis** [comment]
We've taken the approach of adding a new trigger (`story-last-page-visible`) that is triggered when the user has arrived on the last page, which you can use for completion rates.  In the future, we may also provide ranges (e.g. 0%, 25%, 50%, 75%, 100%), since those can be provided accurately.

We don't want to unnecessarily inflate completion rates, so we don't want to change `storyProgress` from starting at 0.  Please feel free to reopen if you feel this does not adequately address this issue
