### ISSUE TITLE
Add "fetch-error" event to amp-list / remote state

### ISSUE THREAD

**Issue by ianba** [ampproject/amphtml#21322]
## Describe the new feature or change to an existing feature you'd like to see
We'd like be able to send an amp-viewer-assistance.updateActionState (FAILED_ACTION_STATUS) in response to certain critical failed amp-list / amp-state XHRs; however, we need an event to trigger after such a failure to be able to run that action.

## Describe alternatives you've considered
None that I'm aware of

/cc @choumx

**Comment by nainar** [comment]
Hi @ianba what use case are you trying to solve for here? 

Do some of the suggestions here cover those use cases? https://github.com/ampproject/amphtml/issues/15478#issuecomment-465750927

**Comment by ianba** [comment]
We are trying to report the failure back to our extension (which then reports back to our viewer), not update the UI, so I don't think the features listed in that comment will work for us.

**Comment by choumx** [comment]
#21512 adds the `fetch-error` event to amp-state and amp-list extensions.

However, some minor changes are needed in amp-viewer-assistance to support sending `FAILED_ACTION_STATUS` as a result of `fetch-error`. This is because `updateActionState`'s data format expectation is such that it can can only be called with the `event.response` of an amp-form submission. 

One option is to extend the action handler to conditionally accept a "status" param instead of an "update" param:
```html
<amp-list src="..." 
    on="fetch-error:amp-viewer-assistance.updateActionState(status=FAILED_ACTION_STATUS)">
```

Either way, should be a straightforward change. 

/to @hellokoji
