### ISSUE TITLE
Allow preserving markup in captions when going to lightbox

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#21337]
When opening a lightbox, we currently only use the text content of a caption and not any markup within the caption. There may be some styling or links in the caption (e.g. for photo credits) that would be nice to preserve. One example of a page with such a caption:
https://www.google.com/amp/s/www.nytimes.com/2019/03/08/us/san-francisco-tech-wealth.amp.html

The code that extracts the text is here: https://github.com/ampproject/amphtml/blob/50a9eed6ea15306d027a29232c8e62eed093c212/extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js#L308-L326

**Comment by cwlovell13** [comment]
Would love to see this, or a similar feature, for amp-lightbox-gallery. We currently have to use amp-image-lightbox so that we can apply custom styles to the caption, which means we can't lightbox any galleries, just individual images. This leads to a poor user experience, as the have to open, then close, each lightbox image. Even just a locator we can use for styling the caption similar to how amp-image-lightbox uses amp-image-lightbox-caption it would be amazing!
