### ISSUE TITLE
Add `ChromeBeta` to test suite

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#21339]
We currently test with Chrome Canary which is great, however Chrome Beta is a closer representation of what will ship in next version of Chrome. Beta has the same flags enabled that are expected to launch in next version whereas Canary has features that may never launch and certain flags that may never get enabled.

If too much to run both Canary and Beta, I think we should just replace Canary with Beta.

/to @rsimha to prioritze
/cc @choumx

**Comment by choumx** [comment]
I think we actually run [Chrome Beta on SauceLabs](https://github.com/ampproject/amphtml/blob/f56a3d48a002c354a1d2d26c2bd6f1d7630e4d74/build-system/tasks/runtime-test/index.js#L110), but we have a local option to run on Chrome Canary with [`--chrome_canary`](https://github.com/ampproject/amphtml/blob/f56a3d48a002c354a1d2d26c2bd6f1d7630e4d74/build-system/tasks/runtime-test/index.js#L64-L66).

For context, Ali and I were curious why [this bug](https://github.com/ampproject/amphtml/pull/21060#issuecomment-470652789) wasn't caught in automated testing. This is the closest green build following that PR, which appears to run Beta (73).

> [17:07:35] Chrome 73.0.3683 (Windows 10.0.0): Executed 267 of 527 (Skipped 260) SUCCESS

https://travis-ci.org/ampproject/amphtml/jobs/502113797#L1411

**Comment by choumx** [comment]
Hmm, seems like that new `PerformanceLayoutJank` API is only enabled when run with `--enable-blink-features=LayoutJankAPI`. Just tested both Canary (74) and Beta (73).

Let me follow up with @ericandrewlewis.

**Comment by choumx** [comment]
Apparently it's still in origin trial for 73 without a definitive ship date.

So in terms of coverage, we might be good. However, IIRC we don't fail the Travis build if the SL task fails (due to flakiness). So it's possible that we'd miss the breakage -- we had a similar problem in last major Chrome release. @rsimha Is that still accurate?

**Comment by aghassemi** [comment]
Good to know we are using Beta, this request was a bit unrelated to https://github.com/ampproject/amphtml/pull/21060 just makes sense to use Beta instead of Canary for our automated testing.

**Comment by aghassemi** [comment]
I think it is fair to make `Beta` break PRs as essentially there is only a few weeks to get any fixes related to `Beta` out so they should be high priority.

**Comment by rsimha** [comment]
Just caught up with this. @choumx is correct in pointing out that we currently don't fail sauce labs jobs due to test flakiness. However, we're close to the point where failures will surface as a PR status instead of a Travis failure. This will make failures more visible, more likely to be fixed, and less annoying to overcome.

At that point, we can block PRs that legitimately break on beta Chrome / FF. Stay tuned!

**Comment by aghassemi** [comment]
Sounds good. Closing this issue since everything mentioned here is either planned or already implemented.
