### ISSUE TITLE
Use webp for amp-youtube placeholder image

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#21357]
from @yazdotdev: the placeholder image for amp youtube is jpg and not webp. any chance of changing this? it might be more a youtube team rather than amp team issue though.

This was brought up from a conversation related to `amp-youtube`: #21340
@aghassemi to triage.

**Comment by yazdotdev** [comment]
thanks @lannka for bringing it up as a separate issue

**Comment by aghassemi** [comment]
@yazdotdev Good idea! YT does provide WebP thumbnails already.

**Comment by cramforce** [comment]
It would be possible to load by toggling format on the client side with a picture element. However, youtube doesn't appear to use webp for their player right now and it is more important to match their URL, since otherwise the sum of bytes will be bigger.

For reference, here is the URL pattern for webp thumbs https://gist.github.com/bojanvidanovic/0b31443827c2c424469da754376180d4
