### ISSUE TITLE
[amp-list-load-more] Maximum number of bindings reached (%s).

### ISSUE THREAD

**Issue by xiaotong-kk9** [ampproject/amphtml#21429]
## What's the issue?

Maximum number of bindings reached (%s). Additional elements with bindings will be ignored. 1000

## How do we reproduce the issue?

Keep scrolling [this page](https://m.rotita.com/whats_new-amp.html).
After loading about 10 pages * 30 items, got this error multiple times 'Maximum number of bindings reached (%s). Additional elements with bindings will be ignored. 1000'.

## What browsers are affected?

Chrome Version 72.0.3626.121

## Which AMP version is affected?

Version 1903141753530 with amp-experiment-token.

**Comment by aghassemi** [comment]
@choumx @cathyxz We need to `virtualize` `amp-bind` mutations to be able to handle cases like this. This is not unique to infinite scroll however infinite scroll/load more does make hitting limit more common.

If we allow `amp-bind` to be virtualized (i.e. only apply mutations for elements in viewport +/- some margin), then we can not count a majority of expressions as part of the total limit. There are definitely some nuances ( like forms input expressions probably should not be virtualized).

We should also consider virtualizing list element, but that's sort of separate than virtualizing amp-bind. Given Chrome is launching Display Locking (https://github.com/WICG/display-locking) soon, it is better for us to use Display Locking instead of full virtualization of list items so A11Y and Find in Page do not suffer.

**Comment by choumx** [comment]
Related: #15519

**Comment by aghassemi** [comment]
dedup with https://github.com/ampproject/amphtml/issues/15519
