### ISSUE TITLE
Configure lazy loading strategy for AMP pages

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#21497]
This issue was raised by Ali Express, where in they want to be able to specify the loading strategy for pages. E.g. on mobile most users will not go past their product image carousel and size selector, however images in a later viewport are still loaded. 

We should allow for sites to customize the loading strategy for a page as well as for individual components. 

cc @leonalicious @cramforce @aghassemi

**Comment by choumx** [comment]
> We would like to have this feature, so we can improve the performance of the page.

@andreyMakahov Is the goal to improve user-perceived performance or reduce server traffic? 

If performance, can you explain how AMP's current lazy loading heuristic affects performance?

**Comment by andreyMakahov** [comment]
@choumx The most important is to improve user-perceived performance and speed up [load event](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event), when all resources in the document are loaded. This event will be fired faster because AMP will not request resources witch position is far away from viewport, if I understand correct how AMP lazy loading algorithm works.

Let me show you the example, where I set slow internet connection. 
![image](https://user-images.githubusercontent.com/5758614/54731206-e8557300-4bc7-11e9-9b1b-f0529d610b8c.png)

Actually, user-perceived performance is not so bad. With such slow internet I already could interact with the page after 8 seconds, but as you can see from screenshot, load event was fired after 49 second. If we request less resources initially the event will be fired faster.

But it would be great to reduce server traffic as well.

**Comment by cramforce** [comment]
Let's ignore the load event. It doesn't mean anything. If we wanted it to
be earlier, we'd just wait for it to fire first and then do the work.

There is definitely a bandwidth use argument (e.g. if you know users rarely
scroll you'd want to be more conservative about resources below the fold)
and a bandwidth congestion argument (non-critical images may drown out more
important requests like item availability).

**Comment by choumx** [comment]
Another consideration is the tradeoff for "how likely will users see not-yet-loaded content when scrolling". I think we can fine-tune current viewport distance values with some metrics, e.g. minimize "loaded but never viewed" and, importantly, "viewed but not yet loaded".

Also, IMO we should only allow configuration if there is meaningfully different user patterns across sites WRT below-the-fold scrolling. 

/cc @andrewwatterson

**Comment by cramforce** [comment]
I do think these differences exists. We probably don't want to allow
micro-management.

amp-ad already supports this via the `prefer-viewability-over-views`
option. Generalizing that seems useful.

**Comment by leonalicious** [comment]
sorry guys, I am kind of lost, please correct me if I am wrong, it means you guys are going to fine-tune the current viewport distance values with some metrics and we do not need to worry about anything or provide any properties in, am I right?

**Comment by eliashuamanmeza** [comment]
ghghghgh

**Comment by ZdejPoham** [comment]
I need a way to force AMP not to set 'loading="lazy"' attribute on hero image. At the moment, AMP wrongly calculates the images' position and loads it lazily, which causes lower pagespeed score for the page.
