### ISSUE TITLE
ilmeteo.it:  Old amp cache for not cached pages

### ISSUE THREAD

**Issue by thinkdifferent** [ampproject/amphtml#21515]
## What's the issue?

There are old amp cache for pages that should not be cached.

Search Query: https://www.google.com/search?q=ilmeteo+genova&oq=ilmeteo+genova

AMP Cache URL: https://www.google.com/amp/s/www.ilmeteo.it/meteo/Genova

But our amp page is https://www.ilmeteo.it/meteo/Genova/amp and there is no amphtml in the canonical.

So why the cache?

**Comment by torch2424** [comment]
Triaging to @Gregable , Feel free to re-assign 😄

**Comment by Gregable** [comment]
When did you remove the `<link rel=amphtml>` on the AMP page? The search result page shows me a "Mar 4, 2019" date when I look at it. It could just need to get recrawled, so I think this is working as intended.

The AMP Cache will keep showing the page regardless of the `<link rel=amphtml>` on the canonical, as long as the AMP page exists. Otherwise, users to your site would get a broken experience when clicking the link.

Beyond that, this is more of a Google Search product question, and I'm not sure we can help you further here.

**Comment by thinkdifferent** [comment]
We removed the rel=amphtml some months ago. The amp page exists, but we want google to show the current page, not a very old one.

**Comment by Gregable** [comment]
The search results on mobile do not show an AMP link for me. Is there something more you are still trying to resolve?
