### ISSUE TITLE
Limit story sidebar open action to story sidebar icon

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#21588]
The `amp-sidebar` action `open` is used by `amp-story` to open its sidebar.  However, we want it to be opened by the system affordance, rather than any arbitrary publisher-specified UI.

I propose that we introduce a synonym of `open` called `i-amphtml-open` that uses the same handler that `open` does, but is internal-only.  We can then refactor amp-story code to use this action, and only add the internal variant to the action whitelist.

/cc @cathyxz @bramanudom @gmajoulet

**Comment by aghassemi** [comment]
@newmuis How are you planning to prevent publishers from calling `open` ?

**Comment by newmuis** [comment]
There's a [whitelist](https://github.com/ampproject/amphtml/pull/14628) of AMP actions that can be allowed in a document.

Currently we whitelist `open`.  If we instead whitelist `i-amphtml-open`, then publishers will not be able to use it, due to `i-amphtml` being invalid AMP.  They will be able to publish their document using `open`, but it will not function, as it will no longer be whitelisted.

**Comment by aghassemi** [comment]
I assume (or suggest) you will be calling `open` from `amp-story` JS code (using `ActionService`'s `trigger` method (https://github.com/ampproject/amphtml/blob/master/src/service/action-impl.js#L375) rather than through `on=...` string.

My recommendation is adding a `ignoreWhitelist` to the existing `options` param of trigger, this way your code can call `open` just fine without a need to alias it (Unless we build something to validator, I don't think renaming to `i-amphtml-open` prevents anything other than hiding it. My understand is that validator looks for `i-amphtml-*` only in certain places not sure if attribute values is one of those places but I might be wrong)

**Comment by honeybadgerdontcare** [comment]
We do not allow `i-amphtml-` in `<style amp-custom>` nor as the value for attributes `class` or `id`. IOW, it is not generally excluded as a value for any attribute.
