### ISSUE TITLE
I2I: Premium content encryption protocol

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#21658]
Implement protocol described in the [explainer.md](https://github.com/ampproject/wg-access-subscriptions/blob/master/content-encryption/explainer.md).

**Comment by sjparkinson** [comment]
Hi @dvdyakonov, I'd be interested to know what other solutions have been explored, I find it hard to evaluate the proposed solution in the explainer in isolation.

On the document key that is used to decrypt the content that requires authorisation, it's not clear to me in the explainer if that key is unique to the document, the user, the authorizer, or the document and user. It sounds like it'd be per document regardless of the user or authorizer, but good to be clear about that.

I have a concern that if it is per document, it may be trivial to distribute a link to premium content, and a snippet of javascript containing the key to run in your console in order to read the content. People are already doing so in suggesting disabling javascript to get access with the current design.

> https://amp.ft.com/content/1091cf20-5209-11e9-b401-8d9ef1626...
> 
> Make sure you have javascript disabled or use "reader mode"
> 
> Or delete the AMP CSS in developer tools or use a browser that does not support CSS

From https://news.ycombinator.com/item?id=19541276.

People are much less inclined to share their own logins publically, but there is nothing to stop someone sharing a per document key anonymously without any repercussion.

> otherwise the "premium content" is hidden and only a "preview" of the document is shown.

In our case we'd ideally not deliver any content, instead displaying our barrier/login page.

Regarding the first click free system, I assume it'd be the authorisation service's responsibility to grant access if the request meets the criteria for free access?

**Comment by jpettitt** [comment]
@sjparkinson We really appreciate the questions. It's a complex thing to explain (although fairly simple to implement). 

We agree the current "hide the content with CSS", client side paywall models are easy to defeat for a technical user.  This is less of a problem for publications that allow metered access since the meter is inherently dependent client side storage. For higher value / non-metered access content something stronger is appropriate, hence this protocol.

Some high level context on the threat model here should help.

The first thing I should note is that we're not trying to create DRM.  In traditional music / video DRM system individual content items are high value and sharing even once is not desirable.  However in a news publication the content goes stale rapidly, the value is usually not in a single article instead it's in the ability to consistently access content.  This is reflected in how the current server side model operates, delivering unprotected content to authorized users.

The goal is the same level of protection as you would get by authenticating a user on the server side before serving them the content.  We're specifically not trying to protect content delivered to authorized users, just as with server side paywalls today once the user has the premium content they can abuse it in many ways , eg  save it, copy paste, or print it to a PDF and share that.

Keys are per document intentionally, this replicates the above behavior in that unauthorised users can't get access but authorised ones can still print etc.   It's true that an authorized user will have the key for a given document, however they will also have the actual content.  The net result is if they want to share the content they can go the copy/paste route with less work than sharing the key.

It is possible the make a key sharing app. An attacker would need to maintain a database of keys and documents.  When implementing the protocol is makes sense to generate a new random key for each document whenever it is regenerated by the CMS.  Since the key is in the document this doesn't present a key management problem, and there is no need for the server to remember or track keys used.

If random keys are used every time the document is regenerated an attacker would then need to maintain a key database and a content database of the document version encrypted with those keys.  At that point they may as well just maintain a decrypted document store.  The net of all this is the threat model is functionally identical to serving plain text only to authorized users.

Regarding access by search engines the idea is that there are multiple copies of the key in the document, each encrypted with the public key of entities the publisher wants to grant access to.  For example keys for Bing, Google Search, Yahoo, Subscribe with Google, archive.org etc.  The choice of who is allowed to decode a document is entirely in the hands of the publisher based on whose keys they choose to use.

Lastly this system doesn't have to do the decryption in the browser. One obvious optimization is to have an edge cache that is aware of the users authentication status decode the content before it sends the page.  A number of edge cache providers are adding functionality to run applets at serving time.  This, from a user standpoint, would behave identically to the current server side paywall model, authenticated users get clear text, non authenticated ones get the the paywall and no premium content delivered.

Does that help?

cc @dvoytenko @chenshay

**Comment by mpaw** [comment]
Thanks @dvoytenko and @jpettitt. For the most part I think this would work for us and solves the main problem.

Regarding the way that the "paid" content is inserted after it is decrypted. Would it be possible to still have it replace the "free" content like we can do now with `amp-access="NOT access"` and `amp-access="access"`? I can think of a couple examples where we might want to do more than just append past the free content. For example if we have content that looks like this to users that are not subscribers:

```
Headline
Sub-headline

Image

First paragraph preview
```

But looks like this to subscribers:

```
Headline
Sub-headline

Video

First paragraph
```

Just appending past the first paragraph doesn't allow us to do this.

> A Cache that requires full validation will have to publish its public key and request the publisher to include it in the "encrypted keys" section.

Will there be a centralized location where AMP CDNs will publish their public keys? If not, will the document fail AMP validation if the cache can't decode the encrypted content?

> One negative: if a new crawling partner is added, the previously created content has to be re-generated with the new encrypted key.

I'm assuming this means that the publisher needs to serve the AMP articles with the additional encrypted document key using the crawler's public key. This does not mean that all CDNs need to update all cached data, correct?

**Comment by jpettitt** [comment]
We don't plan to change the page rendering, once a document is decrypted the premium plain text text will replace the encrypted blobs.  How it gets displayed will still be gated by CSS as now.  This will allow the paragraph / paragraph preview as now.

We haven't worked out the exact detail of how public keys will be published.  Probably not in a central location as that would make key rotation hard todo.  We will probably end up with a list of key url's on cdn.ampproject.org/some/well/known/path/tbd.  Keys for other entities (search engines, archives etc) would be handled by those entities.  

There is no need for a crawler that whose key was included in earlier to re-crawl when a new key is added.

**Comment by mpaw** [comment]
@jpettitt Thanks for the clarifications

> How it gets displayed will still be gated by CSS as now. This will allow the paragraph / paragraph preview as now.

Can you clarify how that is going to work? From the document it seems like the response from our server will be in this format:
```
{
  "key": "DECRYPTION_KEY"
}
```
Are you saying we will be able to send back other flags that can be used to hide/show elements like is done right now with CSS? Or is there going to be some binary flag set (like `access`/`NOT access`), depending on if a decryption key was sent back, that we will be able to use?

@sjparkinson
> Regarding the first click free system, I assume it'd be the authorisation service's responsibility to grant access if the request meets the criteria for free access?

That's what I'm assuming too. In this implementation the publisher is responsible for metering.

**Comment by jpettitt** [comment]
The initial implementation will be on `amp-subscriptions` and the `key` object would live within the larger `amp-subscriptions` authorization response which contains the access grant etc.

**Comment by mpaw** [comment]
Where does this currently stand? Last update was in May

**Comment by jpettitt** [comment]
We're in the final process of integrating it with the amp cache.  We've published a sample encryption engine in golang at https://github.com/subscriptions-project/encryption
