### ISSUE TITLE
AMP HTML UX Framework Master

### ISSUE THREAD

**Issue by spacedino2** [ampproject/amphtml#21684]
It's great that we have incorporated UX best practices into our work, via - examples, documentation, and templates, but it would be nice to have them documented in one place for a few reasons:

- to help developers who might want to understand why certain things are best practices, and how to extend these patterns to new components
- to help other designers working on AMP
- to highlight opportunities to codify more attributes as well as fix potential inconsistencies across components

As an MVP I have put together some current examples and ways we might start to think about our system holistically. One thing that came up through this process was a suggestion to think about our animations as a library. Another was an opportunity to think about our different offerings for defaults, such as a way to quickly enable "dark mode". What might that look like as part of this framework?

[AMP HTML UX Framework - master_v1.pdf](https://github.com/ampproject/amphtml/files/3035650/AMP.HTML.UX.Framework.-.master_v1.pdf)

**Comment by spacedino2** [comment]
[AMP HTML UX Framework - master_v1_1.pdf](https://github.com/ampproject/amphtml/files/3035665/AMP.HTML.UX.Framework.-.master_v1_1.pdf)

**Comment by spacedino2** [comment]
Intro
![AMP HTML UX Framework - master_v1_1](https://user-images.githubusercontent.com/47966956/55431981-9bb65400-5546-11e9-8055-309add14c8e1.jpg)

Why
![AMP HTML UX Framework - master_v1_2](https://user-images.githubusercontent.com/47966956/55432002-a7a21600-5546-11e9-9cfd-7dcaa5528be2.jpg)

Why AMP
![AMP HTML UX Framework - master_v1_3](https://user-images.githubusercontent.com/47966956/55432018-b5579b80-5546-11e9-8226-5b7e776c4b3f.jpg)

UX Principles
Links from the page:
[ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)
[WCAG guidelines](https://www.w3.org/WAI/standards-guidelines/wcag/)
[W3C guidelines](https://www.w3.org/WAI/standards-guidelines/wcag/)
[MDN guides + tutorials](https://developer.mozilla.org/en-US/docs/Web/Accessibility) 
[https://a11yproject.com/](https://a11yproject.com/)
![AMP HTML UX Framework - master_v1_4](https://user-images.githubusercontent.com/47966956/55432036-c0123080-5546-11e9-83c9-5df447d6df5f.jpg)

Error / Success states
Links from the page:
[WCAG 2.0 Contrast ](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html)
[Colour Blind Awareness](http://www.colourblindawareness.org/)
![AMP HTML UX Framework - master_v1_5](https://user-images.githubusercontent.com/47966956/55432249-3dd63c00-5547-11e9-84a5-0eaca9b4b1ae.jpg)

Buttons
Links from page:
[ARIA tags](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)
[WCAG Color Contrast 2.0](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html)
![AMP HTML UX Framework - master_v1_6](https://user-images.githubusercontent.com/47966956/55432264-4af32b00-5547-11e9-8272-c67de3a25d5f.jpg)

Styling
![AMP HTML UX Framework - master_v1_7](https://user-images.githubusercontent.com/47966956/55432632-3a8f8000-5548-11e9-9539-a5d2fbcf690d.jpg)

Styling / Our approach 
![AMP HTML UX Framework - master_v1_8](https://user-images.githubusercontent.com/47966956/55432663-5004aa00-5548-11e9-882d-9b8172af914f.jpg)

Styling / Range x customization
![AMP HTML UX Framework - master_v1_9](https://user-images.githubusercontent.com/47966956/55432687-690d5b00-5548-11e9-8d59-3c007c3496a4.jpg)

Devices + breakpoints
![AMP HTML UX Framework - master_v1_10](https://user-images.githubusercontent.com/47966956/55432706-74608680-5548-11e9-9da7-6c44d8ab44a6.jpg)

Animation library
Links from page:
[Can I use](https://caniuse.com/)
![AMP HTML UX Framework - master_v1_11](https://user-images.githubusercontent.com/47966956/55432729-82aea280-5548-11e9-9a37-e0affe13d323.jpg)

Components with some built-in UI
![AMP HTML UX Framework - master_v1_12](https://user-images.githubusercontent.com/47966956/55432775-9eb24400-5548-11e9-8048-5583bb47f8df.jpg)

amp-date-picker
![AMP HTML UX Framework - master_v1_13](https://user-images.githubusercontent.com/47966956/55432788-aa9e0600-5548-11e9-8a05-8e5e7c301b8a.jpg)

amp-lightbox-gallery
![AMP HTML UX Framework - master_v1_14](https://user-images.githubusercontent.com/47966956/55432811-b8538b80-5548-11e9-8b09-f577b0b3d92a.jpg)

amp-ad-banner / amp-app-banner
![AMP HTML UX Framework - master_v1_15](https://user-images.githubusercontent.com/47966956/55432824-c4d7e400-5548-11e9-9649-237bb0156d1c.jpg)

Do / Don't
![AMP HTML UX Framework - master_v1_16](https://user-images.githubusercontent.com/47966956/55432856-d6b98700-5548-11e9-819d-632067f11c3b.jpg)

Useful articles
Links from the page:
[Tap to Dismiss article](https://medium.com/tap-to-dismiss/tap-to-dismiss-fbc66bdf500a)
[Tips for form fields](https://www.smashingmagazine.com/2018/08/best-practices-for-mobile-form-design/)
![AMP HTML UX Framework - master_v1_17](https://user-images.githubusercontent.com/47966956/55432999-34e66a00-5549-11e9-829a-06714d95521b.jpg)

**Comment by aghassemi** [comment]
Thanks @spacedino2 

to @andrewwatterson @nainar & @CrystalOnScript to find the best place to have this documented

**Comment by andrewwatterson** [comment]
Heyy - my understanding was that @spacedino2 originally created this as a guide for non-Google contributors to use when designing the UX for their components (and as a reference point for internal folks).

Separately, I've been doing some work to unify the visual style of several of our more UI-forward components (the ones mentioned in this preso + autocomplete + carousel + the payments project next quarter). It's on my schedule to present some of that to the team ("are these visual guidelines we're comfortable with? is this the visual customization story we're comfortable telling AMP developers given what we know about how many people customize our components?") and also use the payments project as a crucible to test out how well those guidelines work in practice.

So from @CrystalOnScript 's perspective: I'm super stoked to document this stuff publicly, but I'd bias slightly toward waiting at least a few months until we have some more data (since this is actively being explored right now).

**Comment by nainar** [comment]
@spacedino2 thank you for sharing this! I think this is incredibly useful information for us to disseminate to developers working on the AMP Project to make sure all contributions have the same foundation resources to creating great AMP components.

I am excited to see how @andrewwatterson's work to create a Default UI guideline from AMP link up with @spacedino2's work here. Let's wait till that work is done? Specially since some of the default recommendations might change as we explore more components like `<amp-pay>`.
