### ISSUE TITLE
`getNameArgs ` in variables.js doesn't understand nested macros

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#21751]
We have a function export function `getNameArgs` that extracts the name from the arguments in our macros. `encodeVars` relies on this function to not encode the arguments to a macro which will later be resolved by UrlReplacementService. This does not work for nested macros and thus the arguments get encoded and everything breaks.

example: 
`encodeVars(SOME_MACRO(abc,123))  == SOME_MACRO(abc,123)`
`encodeVars(SOME_MACRO(abc, OTHER_MACRO(foo)))  == SOME_MACRO(abc%2C%20OTHER_MACRO(foo))`

This could be fixed by altering the regex here to be smart about nested macros.
https://github.com/ampproject/amphtml/blob/bbabe0a9d266a9421a1b527f37fcbd3e06482e72/extensions/amp-analytics/0.1/variables.js#L31

cc/ @ampproject/wg-analytics

**Comment by calebcordry** [comment]
Actually this bug in `getNameArgs` affects more than `encodeVars` we are also using it in cookie-writer.js to validate the allowed macros. This is bad because if we wish to allow something like `$IF(QUERY_PARAM(foo), QUERY_PARAM(foo), LINKER_PARAM(foo)` it also is broken due to not recognizing the right names :(

**Comment by calebcordry** [comment]
cc/ @lannka

**Comment by zhouyx** [comment]
Any update on the issue @calebcordry We get few request for the fix. And it's blocking us from documenting the nested macros.

**Comment by calebcordry** [comment]
I am not sure where we landed after our previous discussion. I had #22379 but there were some tradeoffs with that approach.

**Comment by zhouyx** [comment]
Here's what I recall from the last discussion. 
We are thinking about two ways to solve this issue. 
1. Expand variables before appending them to url, so we won't be having the encoding issue. 
2. Expand the `#getNameArgs` function to support all the cases. This will be similar to what we have in expander. 

We went with Approach#1 in #22379 because we believe that implementation is cleaner. However the approach has an issue which we can't fix. By expanding variables ahead of time, it leads causes delay to variables that got resolved asynchronously. For example
```
'request': 'https://fake.com/t1=${timestamp}&t2=${var_time}&c=${c}
'vars': {
  'c': 'CLIENT_ID(test)',
  't2': TIMESTAMP,
}
```
Let's assume that it takes 2 seconds for `CLIENT_ID` to resolve. `t2` will be resolved right at trigger time, but `t1=${timestamp}` will only be resolved after `c=CLIENT_ID(test)` has resolved. Which leads to a delay to all the time sensitive macros. 

Because of this, I think we can only go with option #2. But please let me know if you have other ideas.

**Comment by calebcordry** [comment]
Right, thanks for the recap. #2 SGTM. I tried this originally but it was a while ago and I don't think I saved the code (it was incomplete anyway). Let me know if you want me to work on this and I can start on it next week.

**Comment by zhouyx** [comment]
I'd like to prioritize the work here, it's blocking @zikas's work. Do you have an estimate to the workload? Thanks

**Comment by lannka** [comment]
Discussed with @zhouyx offline, let's go with #22379 and admitting the caveats in documentation. The benefit is obvious as it avoids this error-prone getNameArg code.

@calebcordry let's prioritize this next week, as it's the last item for launching #13371

**Comment by calebcordry** [comment]
SGTM, thanks all!

**Comment by micajuine-ho** [comment]
Tracked in #26271
