### ISSUE TITLE
No vendors in amp-pixel?

### ISSUE THREAD

**Issue by Meggin** [ampproject/amphtml#2176]
There's currently no mention of vendors in amp-pixel, but believe at least one is using it?

We should document any vendors who've integrated with pixel and link off to their docs. Eventually, we may want to centralize vendors into one doc for both amp-pixel and amp-analytics, if there's cross-over?

**Comment by cramforce** [comment]
I think it is a good idea. One big difference is that `amp-analytics` actually supports vendor config, while `amp-pixel` does not.

**Comment by ryanlombardo** [comment]
comScore suggested we (BuzzFeed) use `amp-pixel`, however, I have seen that they support for `amp-analytics` also. We plan to switch to the `amp-analytics` component to maintain consistency with our other vendor implementations.

**Comment by bpaduch** [comment]
@cramforce  - How can I determine what vendors are supporting amp-pixel?  We currently list all supported analytics vendors [here](https://www.ampproject.org/learn/who/#analytics).

**Comment by rudygalfi** [comment]
After ~1 year since this was filed, I don't think tracking pixel implementations on ampproject.org is needed. The typical path for a vendor will be to use amp-analytics. Those vendors who have an amp-pixel only implementation for analytics can provide visibility and make it clear in their own documentation.
