### ISSUE TITLE
<amp-lightbox> in <amp-carousel> working differently on iOS vs. Android

### ISSUE THREAD

**Issue by Svenmay** [ampproject/amphtml#21777]
## What's the issue?

<amp-lightbox> is rendering differently on iOS compared to Android when triggered within <amp-carousel>. 
On Android everything works as expected, i.e. the navigation arrows (left + right) disappear when lightbox is opened. On iOS the navigation arrows are still visible when lightbox opened and the content of the underlying page is also still visible.

## How do we reproduce the issue?

1. Open https://tolwin.spdns.org/amp/fdaf_light.html
2. Click on "open lightbox".
3. Compare visual output on Android vs. iOS:

## What browsers are affected?

Tested with Chrome on Android + iPhone 8 (and Iphone simulator in Xcode). Note: The error does not appear when using Safari and emulate an iPhone there.

## Which AMP version is affected?
Current version.

Some screenshots attached.

This is how it looks like on an real IPhone after clicking on "open lightbox"
![IMG_20190409_162934](https://user-images.githubusercontent.com/39521568/55809291-f2430580-5ae5-11e9-93e6-fb9cbfa261af.jpg)

This is how it should look like (and how it looks like on Android)
![Screenshot 2019-04-09 at 16 39 13](https://user-images.githubusercontent.com/39521568/55809353-0ab32000-5ae6-11e9-9916-4ee8c0756fa3.png)

**Comment by aghassemi** [comment]
Thanks @Svenmay. We are currently working on version 2 of `amp-carousel`. We will verify this is fixed in the new version but unlikely to backport the fix at the moment.

**Comment by Svenmay** [comment]
Thanks @aghassemi for looking into this.

Do you have a timeline when to expect the new version of amp-carousel being available? Are we talking about days, weeks(, months)?

This bug was notices by some of our iOS users on our production website, so do we have some urge for a fix/workaround.

**Comment by aghassemi** [comment]
Will take a look today, setting as high priority

**Comment by aghassemi** [comment]
Hi @Svenmay There is an easy work-around for this that publisher can do to get around the problem:
* Make sure `amp-lightbox` is outside of `amp-carousel` in DOM order, ideally make it direct child `body`.

The problem here is `stacking context`, since `amp-lightbox` is a position fixed element, various CSS rules at any of its ancestors can create a new stacking context and mess up the z-index. In this particular case `-webkit-overflow-scrolling` in `.i-amphtml-slides-container` is creating a new stacking context.

User-defined CSS can also mess up stacking context, this is one of the reasons we enforced `amp-sidebar` to be a direct child of `body` but we missed doing the same for `amp-lightbox`.

I will keep this issue open since there are possibilities of fix in core as well (or at least showing warnings) but the workaround should work fine for now.

**Comment by aghassemi** [comment]
Created https://github.com/ampproject/amphtml/issues/21959 to track a long-term fix.

Closing this based on the workaround mentioned above.
