### ISSUE TITLE
amp-story: animations not working in amp-video

### ISSUE THREAD

**Issue by Serhio77777** [ampproject/amphtml#21794]
Hi, I have a problem with APM story video (amp-video). I create a simple story with 4 pages. Pages have video inside amp-video tag, it works fine, but when I add amp-animations they often do not start, although the amp-video contains animate-in attribute.

example story - https://test-cutnut-tv.cdn.ampproject.org/c/s/test.cutnut.tv/amp/66c1cd03-2fab-4a0b-9c8e-dcfa79f20bef

Can you help me, please? what I do wrong?

![image](https://user-images.githubusercontent.com/20393340/55875045-bae36000-5b9c-11e9-99e1-abcbb1b0788d.png)

**Comment by aghassemi** [comment]
/to @newmuis, let me know if amp-video needs to do anything for this.

**Comment by StebneRuslan** [comment]
Are there any updates here?

**Comment by newmuis** [comment]
@gmajoulet can you take a look when you get back?

**Comment by gmajoulet** [comment]
I found the bug but I'm not sure about the best way to fix it yet.

There's a lot of context here, but here's a short summary:
Somewhere in the animation code, it waits for the animated element `layoutCallback` to complete. When it's an amp-video, the code ends up in [this method](https://github.com/ampproject/amphtml/blob/master/src/event-helper.js#L148) that, in the context of a story, sometimes never resolves because of a race condition with the internal media pool. The media pool starts loading the video earlier, and the `loadstart` event already fired when we start listening for it. 

An easy fix would be to simply look at the `videoEl.readyState` to know if the video is already preloaded, but that doesn't work reliably enough.

I believe the right fix would be to improve this `loadPromise` helper to better support `HTMLMediaElement`.

**Comment by aghassemi** [comment]
I think `isLoaded` in `event-helper.js` should be fixed to handle media elements properly same way `loadPromise` is special casing media elements.

**Comment by newmuis** [comment]
Wow, thanks for finding that @gmajoulet!

**Comment by StebneRuslan** [comment]
@gmajoulet, You will plan to fix this bug? or we should try to fix and create a pull request?

**Comment by gmajoulet** [comment]
Thanks for offering to help!
I already wrote a fix, that can hopefully be merged today: https://github.com/ampproject/amphtml/pull/21972
