### ISSUE TITLE
AMP consent not working as expected when moving from cache to non cache pages

### ISSUE THREAD

**Issue by chcohen** [ampproject/amphtml#21803]
Hey,
I think there might be an issue with passing the user's consent from amp cached-pages to amp non-cached pages.
If the user accepts the consent in a non-cached amp page,
than rejects it in a cached amp page,
than navigates again to a non-cached amp page - 
the consent will be "accepted" although he rejected it

I tested it with your example page, but now there is a problem there and it can't be uploaded to cache.

The links I used in my test:
A non cached page: https://ampbyexample.com/user_consent/external_user_consent_flow/
A cached page:  https://ampbyexample-com.cdn.ampproject.org/c/s/ampbyexample.com/user_consent/external_user_consent_flow/

thanks
Chedva

**Comment by calebcordry** [comment]
@torch2424 I think you have more context here. Let me know if not, I can look but I thought you might be faster.

**Comment by torch2424** [comment]
@calebcordry Thanks for cc'ing me!

Also adding @zhouyx on this, as they will have the most context.

@chcohen 

Thank you for the issue! 👍 

So I did confirm this with the following URLs:

Non-cache page (canonical): https://amp.dev/documentation/examples/user-consent/external_user_consent_flow/

Cache page (view in mobile dev tools inspector): https://www.google.com/amp/s/amp.dev/documentation/examples/user-consent/basic_user_consent_flow/index.amp.html

The reason why you experienced an issue, is we recently moved `ampbyexample` to `amp.dev`, thus there were probably some redirecting going on causing a problem.

I think this happens because the consent is stored per the origin, and thus since the origin is different causes an issue. @zhouyx will have the most context on this. But unfortunately, we are all currently travelling soon for the upcoming AMP Conf next week. So We will probably start a fix for this issue when we get back from that 👍 

Thank you!

EDIT: After some investigating, seems like this issue would lie within our [Storage Service](https://github.com/ampproject/amphtml/blob/master/src/service/storage-impl.js).

**Comment by chcohen** [comment]
Thanks  @torch2424 !
Can you please update when you start working on it?

**Comment by torch2424** [comment]
@chcohen Definitely can :) Thank you for your patience!

**Comment by zhouyx** [comment]
@chcohen Thank you for bringing this up. Unfortunately syncing consent information between cache and non cache pages is not something we are able to support because the two pages are served from different domain and they don't share the same set of localStorage. 

The best we can do is to append the consent information in the outgoing link if user navigate from cached page to non cached page. However that doesn't solve the issue completely. 
Another possible approach would be to make use of the remote server and to use cookies. But still that doesn't work well for browsers that restrict 3p cookies. 

Unfortunately Both approaches couldn't solve the issue. Currently we don't have plan on supporting consent syncing. 

I'm going to close the issue. But please let us know if you have any idea. Thank you.
