### ISSUE TITLE
AMP4EMAIL: "Advanced Server Request" example does not work from Gmail

### ISSUE THREAD

**Issue by alexandr-kazakov** [ampproject/amphtml#21826]
## What's the issue?

Code from this example: https://amp.dev/documentation/examples/interactivity-dynamic-content/advanced_server_request/?format=email does not work if I send it to my gmail using this service: https://amp.gmail.dev/playground/

In gmail when you switch select error: http://bit.ly/2KuTdyL

## How do we reproduce the issue?

1. Go to this page: https://amp.dev/documentation/examples/interactivity-dynamic-content/advanced_server_request/?format=email
2. Switch to the Playground with the code: http://bit.ly/2KtfeOA
3. Copy the code and use this service: https://amp.gmail.dev/playground/ send yourself an email.
4. Go to your gmail and try switching select in the email. You will see an error in the console.

## What browsers are affected?

Google Chrome, Safari.

## Which AMP version is affected?

Version 1903141753530

**Comment by fstanis** [comment]
Thanks for reporting. There's currently an issue with forms with `method="get"` in Gmail that we're working on.

As a temporary solution, you can replace `<form id="animal-form" method="get" action-xhr="https://ampbyexample.com/echo">` with `<form id="animal-form" method="post" action-xhr="https://ampbyexample.com/echo">` and the email should work in Gmail.

Closing this since we can't fix it from within AMP / sample itself unfortunately, but I expect Gmail to roll out a fix shortly.
