### ISSUE TITLE
`amp-list` integration tests are flaky

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#21821]
Failures from the past few hours:

https://travis-ci.org/ampproject/amphtml/jobs/518540806#L1531-L1537
https://travis-ci.org/ampproject/amphtml/jobs/518493595#L1539-L1545
https://travis-ci.org/ampproject/amphtml/jobs/518425950#L1539-L1545
https://travis-ci.org/ampproject/amphtml/jobs/518388001#L1531-L1537
https://travis-ci.org/ampproject/amphtml/jobs/518429018#L1557-L1564

**Comment by cathyxz** [comment]
So the specific test that is flaky in question is: 
```
    it('should change to layout container as on bind', function*() {
```
It consistently passes on my computer locally (mac, Chrome/Chrome headless within 500ms, FF within 3000ms), but times out on Linux / headless Chrome on Travis. It's a bit confusing why this would time out on Travis at 15000 ms. 

I'll modify this test slightly so that it becomes obvious which poll is failing to further troubleshoot.

**Comment by cathyxz** [comment]
Let's monitor for a bit and see how these do.
