### ISSUE TITLE
Yahoo! Japan Template Ads integration

### ISSUE THREAD

**Issue by mwakkiy** [ampproject/amphtml#21835]
## What's the issue?

Hi, I'm Yahoo!JAPAN Ad engineer. I need to test "Template Ads" before adopting it in our product. However, I can't upload to ".cdn.ampproject.org/ad/s/". Can you whitelist "mwakkiy.github.io" with AMP Cache?

## How do we reproduce the issue?

I created this amp4ads file.
https://mwakkiy.github.io/amp_template_ads/amp_template/ad_test002.html

I want to cache in the next path "/ad/s/".
https://mwakkiy-github-io.cdn.ampproject.org/ad/s/mwakkiy.github.io/amp_template_ads/amp_template/ad_test002.html

Thank you

**Comment by mwakkiy** [comment]
cc/ @calebcordry

**Comment by lannka** [comment]
@mwakkiy thanks for reaching out. 

Instead of whitelisting your github testing domain, as a faster option, I've uploaded your test creative to my test Github domain. Hope that can work for you. Let me know if you have more templates to upload, happy to do so.

```
https://lannka-github-io.cdn.ampproject.org/ad/s/lannka.github.io/amp-ad-template/mwakkiy_1.html
```

Whitelisting takes about a week. Once you are ready, you can come up with your preferred production domain to get whitelisted.

-------
In case you missed some of the background of template ads:

The concept of template ads is simple:
1. the ad template needs to be served from AMP cache
2. the ad response will contain the template URL and the data to populate the template.
3. the ad is fully client side rendered

That said, it will require some work at your side to get integrated. Check [here](https://docs.google.com/document/d/1nF1L_1rAn7I5culLX0_6HqQaCWTfmu0nHaYqwMbfnGI/edit#heading=h.ha73jvcfte12) and [here](https://github.com/ampproject/amphtml/issues/13688) for some more details.

**Comment by mwakkiy** [comment]
@lannka
Thank you for uploading and whitelisting. I am waiting for registration to be completed.
When the in-house testing is complete, I will post a request for registration of the production domain here.

**Comment by lannka** [comment]
@mwakkiy sorry if it wasn't clear. I'm not going to whitelist your GH testing domain, as I think you can use mine instead. 

```
https://lannka-github-io.cdn.ampproject.org/ad/s/lannka.github.io/amp-ad-template/mwakkiy_1.html
```

**Comment by mwakkiy** [comment]
@lannka
OK. Please add "s.yimg.jp" domain to the whitelist.
This is Yahoo! JAPAN's production domain.

Sample file:
https://s.yimg.jp/bdv/yahoo/tmp/ad_test002.html

**Comment by lannka** [comment]
@mwakkiy FYI, this is live: 

https://s-yimg-jp.cdn.ampproject.org/ad/s/s.yimg.jp/bdv/yahoo/tmp/ad_test002.html

let me know if you have other questions.

**Comment by mwakkiy** [comment]
@lannka
Thank you very much.
