### ISSUE TITLE
Scrolling seems "locked" - and only scrolls on the second scroll gesture. 

### ISSUE THREAD

**Issue by nitzanvolman** [ampproject/amphtml#2186]
sorry for taking my time with reporting this, was trying to find the smoking gun...

This problem happens more often on this [page](https://www.taboola.com/amp/announcement) (more often iphone 6)

after loading the page, immediately try to scroll -> the first scroll gesture will not work (will feel stuck) the second gesture will continue to work normally. 
this also happens after pausing the scroll, and then trying to scroll back up again.  

we were also able to catch this on a laptop, see this  ([video](https://www.dropbox.com/s/ncns4a02qg4y99v/AMP%20laptop%20behavior.mov?dl=0))

**Comment by dvoytenko** [comment]
@nitzanvolman Took me a while - it's a pretty bizarre effect. The problem is here:
```
footer {
  ...
  height: 226px;
  ...
}
```

The footer section actually needs slightly more space. As the result, it looks like both Safari and Chrome get confused, perhaps because it's the last section at the bottom of the document.

Anyhow, I changed `height` above to `min-height` and it started working fine. As I said, pretty strange.

**Comment by nitzanvolman** [comment]
Thanks @davidkeyes ! strange one indeed. 
btw, I am not able to recreate on a non amp page. (same contents, just removing all amp references)

**Comment by dvoytenko** [comment]
The reason for this is that there's a conflict between that "insufficient height" situation and `overflow-x: hidden` that AMP sets. The reason it sets `overflow-x: hidden` is to enable swiping applications.

**Comment by rudygalfi** [comment]
@dvoytenko Does this any follow-up or can it be closed?

**Comment by dvoytenko** [comment]
Yep. Resolved.
