### ISSUE TITLE
Links in Stories page content don't always work in Safari

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#21925]
## What's the issue

The `a` links in the story page don't reliably work on Safari. Some links work, others don't.

## How to reproduce

I can't figure out why some links work and others don't, so I can't provide steps to reproduce. But a live example can be found here: [https://tappable.co/s/tokyo](https://tappable.co/s/tokyo).

On the story cover, the Tappable logo is clickable and works.

On the "Made with Tappable" page, the Tappable text has an `a` tag, but isn't clickable in Safari. It does work in Chrome though.

<img width="358" alt="Screenshot_2019-04-21_at_16_38_36" src="https://user-images.githubusercontent.com/4594196/56471560-45a54400-6454-11e9-9eb4-eb7c6c3ac242.png">

## Which browsers are affected?

Safari on iOS and MacOS.

## Which AMP version is affected?

As the support for `a` links in the page content is recent, I'm guessing all versions since release.

**Comment by torch2424** [comment]
Triaging to @newmuis , feel free to re-assign 😄

**Comment by newmuis** [comment]
@Enriqe can you take a look?

**Comment by Enriqe** [comment]
Sorry for the delay, I was out last week...

From taking a quick look, it seems that the issue rises from the fact that the story is embedded in an iframe, since I could not reproduce it in other stories that weren't inside an iframe.

Safari could be doing something weird with links... Taking a look to see what we can do about it.
