### ISSUE TITLE
Invalid public key due to ingestion error

### ISSUE THREAD

**Issue by cr-solutions** [ampproject/amphtml#22010]
Pub-Key and Code we use to generate URL worked till last year ....
Whats wrong now?

https://bildagentur-panthermedia-net.cdn.ampproject.org/update-cache/c/s/bildagentur.panthermedia.net/landingpage/nl-archiv-20190326-360-grad-bilder-reminder/%61%6D%70/?%61%6D%70_action=flush&%61%6D%70_ts=1556284754&%61%6D%70_url_signature=FtzBfR96FVnbabFjrcUi3JBDhO3ohHDQ8VnQKBSmQEj7zKLQXowP5o_zHCuqgy8lY_RXdU0FTtC0aIisswDe9_sjYNK1W1VpqkC-voKZlHqAC4heGJsMpFgLwIz6dl7_6ZuAgLwNr-BIR42Fq5zIua55n7LnCDGMO6oqOIdsr9yW1JxUTZjID9aJqS31_xRQkujcd-UALJhZowHTWJGbNKR8ES1bod2N_v5ACFsqyb_dW4pn9hbYCtVEQ8wW8LeTjKGXhRZb3knN9v3L8naXIa4W754gaWZcTry9neJ5MQTXc7PF0hRBYsH6We6FTrCJiLqM9JPQPuM0P2pWYSf9_Q

**Comment by torch2424** [comment]
Triaging to @Gregable , feel free to re-assign 😄

**Comment by Gregable** [comment]
Tracked as a Google product issue in b/132270710. I don't have any updates for you, but will update this thread if there are any.

**Comment by jgluk** [comment]
Do you get any errors or HTTP response codes as a result of trying this link? Can you describe more what is not working?

Also, putting the exact link is not as helpful because it contains a signature that expires quickly. Clicking on it now, the link no longer works. It's more helpful to copy any of the errors you encounter.

**Comment by cr-solutions** [comment]
Since Yesterday it works again without changes on our side!
