### ISSUE TITLE
I2I: amp-insticator

### ISSUE THREAD

**Issue by triso07** [ampproject/amphtml#22027]
### **………. What we want to achieve ……….**
We’d like to add a new tag to the components catalogue list called `<amp-insticator>`. 

### **………. Expected Behavior ……….**
When implemented in AMP articles or sidebars this `<amp-insticator>` tag would embed our content enhancement unit. The unit is white labeled and serves quizzes and polls to better engage a publishers audience. In the future more content types will be added.

### **………. Technical Description ……….**
Via JavaScript we will create an iframe that will serve our Insticator unit. We’ll ingest a configuration option named "**_data-embed-id_**" which we’ll use to serve the appropriate unique content unit. 

### **………. Monetization ……….**
Our non-AMP unit utilizes advertisements above and below our content to monetize. We’d like to use an `<amp-ad>` tag in this implementation in order to accomplish this.

### **………. Desired Tag ……….**
```
<amp-insticator
	data-embed-id=“7atc7d4c-e5e2-4b1e-bfc7-4775790decb7”>
</amp-insticator>

```

### **………. Visual Output ……….**
![insticator-unit-sample](https://user-images.githubusercontent.com/235373/56835048-1ec68380-6841-11e9-848f-99887724cb6b.png)

@aghassemi

**Comment by aghassemi** [comment]
adding @lannka since there is a monetization piece to this. This may make more sense as an Ad type in `amp-ad` rather than a separate embed component.

**Comment by aghassemi** [comment]
@triso07 Could you explain how the monetization piece is configured? Is the Ad configuration tied to the `embed-id` and controlled by the publisher through a separate configurator tool?

**Comment by aghassemi** [comment]
Is there a particular reason for wanting to use `amp-ad` within the component? (instead of the units being inside your own `iframe`?).

**Comment by lannka** [comment]
> Do we have examples of mixed Ad/Interactive Content embeds? Did they go separate component route or integration with amp-ad?

@aghassemi I don't think we have anything like this in AMP yet. I did get some similar inquiries before. In addition to @aghassemi 's questions, @triso07 could you share more details about how the content is loaded and how the ad is loaded.

**Comment by triso07** [comment]
@aghassemi The content is tied to an embed-id which is controlled via a separate configuration tool. Each embed has two advertisements "attached". Essentially two DIVs that sit above and below our content in the DOM.

@lannka 
Our code works by a publisher placing two pieces of code in their page. 

`<head>`
The first is a script placed in the head of the document. It will load our advertising code as well as some setup functions to be used later. 

`<body>`
The second is code in the body of the document, specifically where the embed should appear. This code contains DOM elements that will be used as containers. We insert our content and ads into those containers via an inline script which triggers their creation.

**Comment by triso07** [comment]
A single `<amp-insticator>` code affords us the ability to control the advertisements around our content for a given publisher. We can fully service their needs without effort being required on their end.

**Comment by triso07** [comment]
@aghassemi We wouldn't want to be a "type" of ad because technically we're not an ad. We're content enhancement with the ability to monetize via ads. We have other monetization methods through the content itself currently and in the future.

**Comment by triso07** [comment]
Let me know if that helps give a better picture. Thanks.

**Comment by aghassemi** [comment]
Thanks for the explanation, I am leaning toward `<amp-insticator>` as well instead of an `<amp-ad type=insticator>`. 

Let's discuss the ad placement part a bit more, I see two options:
1- The `iframe` handles both Ads and Content. In this case `<amp-insticator>` is a fairly straitforward  iframe-backed 3P embed similar to `amp-playbuzz`, `amp-instagram`, etc..
2- The `iframe` handles the content and `<amp-insticator>` itself creates and places `amp-ad` above and below the iframe ( all still contained within `<amp-insticator>`)

For 2 to happen, you need to make an XHR to your servers (Adhering to [AMP CORS](https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md) requirements) and get some info about what ads to place (I assume `type`, `size`, `slot` etc..). Would all the types of ads you want to place be supported by `amp-ad`? 

I think 2 is a better option than 1 as you get all the perf and UX benefits of `amp-ad`. @lannka thoughts?

**Comment by lannka** [comment]
we have a couple of "content enhancement" [vendors](https://github.com/ampproject/amphtml/blob/master/3p/integration.js#L275) integrated with AMP using the `amp-embed` tag. It's basically identical to `amp-ad` with a different name. 

In general, that [type of integration](https://github.com/ampproject/amphtml/blob/master/ads/README.md) is much simpler because it's just a 3rd party iframe. Let us know if that fits your needs. Introducing a new extension will much more involved and require some [baseline criteria](https://github.com/ampproject/amphtml/blob/master/3p/README.md).

**Comment by aghassemi** [comment]
@triso07 I will be out for 2 weeks on paternity leave, @lannka can help you get the ITI and PR reviewed and implemented.

**Comment by triso07** [comment]
@aghassemi Congratulations!

@lannka We're most likely going to use `<amp-insticator>`. We've tested an implementation that seems to work well. We'll create a draft pull request soon and CC you.

**Comment by lannka** [comment]
@triso07 could you further explain how the ad insertion will work? Especially, is the ad delivered from your server, or you just plan to put an `<amp-ad>` tag that will fetch an ad from an ad network that supports AMP? be aware that if your widget is already scrolled into viewport but you haven't get your ad back, you might have problem to insert the ad because AMP does not allow content reflow.

**Comment by triso07** [comment]
@lannka @aghassemi 

We've opened a draft pull request here:
https://github.com/ampproject/amphtml/pull/22295

**Comment by vladdeev** [comment]
As suggested by @lannka we’ll continue with <amp-embed type=“insticator”>.
New i2i opened: #23257
