### ISSUE TITLE
Remove app_id required for Facebook sharing

### ISSUE THREAD

**Issue by CairnsPaul** [ampproject/amphtml#22041]
Currently to use the social sharing component for Facebook requires an app_id using the share dialog with a link url formatted as below:

https://www.facebook.com/dialog/share?href= { CANONICAL_URL }&app_id={ APP_ID }

Facebook does provide a share endpoint that does **not** require an app_id:

https://www.facebook.com/sharer.php?u= { CANONICAL_URL } 

My feature request would be if an app_id is present the social share component uses the share dialog url otherwise use the share endpoint url.

This would eliminate the need to then have an app_id for providing shares to Facebook.

The only alternative is to use Facebook sharing without an app_id is with non-configured provider settings. However this is also not currently possible with Amp Stories #19284

**Comment by cathyxz** [comment]
Since it's two different share endpoints, I think the easy way to achieve this would be to add an additional config item in `amp-social-share-config.js`. I don't think the current social-share code is structured to be smart enough to make that exception. We could call it something like `facebook-url` and perhaps use it like so? 

```
      <amp-social-share type="facebook-url"
                        data-param-u="https://www.google.com"
                        aria-label="Share to Facebook">
      </amp-social-share>
```

**Comment by cathyxz** [comment]
On second thought, although I've tested and verified that this works, I'm not able to find official documentation on Facebook for this endpoint. @CairnsPaul would you mind pointing me to it (before I merge this PR)? Just so I'm not accidentally reverse engineering a deprecated endpoint xD. In the meantime, if this is urgent, you can also make this happen yourself with something like the following: 

```
<amp-social-share type="facebook-url"
    data-share-endpoint="https://www.facebook.com/sharer.php"
    data-param-u="https://www.example.com/endpoint">
</amp-social-share>
```

We do have support for non-configured providers. You just have to style it with a background color and an SVG using CSS. Further documentation can be found at: https://amp.dev/documentation/components/amp-social-share?format=websites#non-configured-providers

**Comment by cathyxz** [comment]
Hi @CairnsPaul! Since there isn't clear documentation for this endpoint, and we do have a documented way for developers to configure `<amp-social-share>` with non-configured providers per my comment above, I'm going to close this issue for now. Feel free to reopen this issue or to resubmit #23160 if you need help or find the relevant Facebook developer documentation for that endpoint.
