### ISSUE TITLE
amp-dynamic-css-classes: Allow for Targeting platforms using extension

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#22060]
Was brought up during AMP Conf, and from our CAMP AMP document. 👍 

Met a partner that was interested in using [<amp-dynamic-css-classes>](https://amp.dev/documentation/components/amp-dynamic-css-classes) to target Android vs. iOS. They figured this extension would offer this functionality, and it does not. Neither do any other AMP Extensions.

Their use case was to show different App install banners depending on the device that visited their website. 😄

**Comment by torch2424** [comment]
Assigned to the owners in Owners.yaml. Feel free to re-assign 😄

**Comment by dvoytenko** [comment]
This was debated, but we decided to move away from this to avoid significantly different document variations between platforms. Many extensions (such as app banner) take the platform into account when making their decision and I think this is a better approach because it can get to the source of the solution better that just CSS classes.

**Comment by dvoytenko** [comment]
I'll close this for now, but please feel free to refile an issue with a more specific use case.
