### ISSUE TITLE
amp-list with placeholder load very slow

### ISSUE THREAD

**Issue by seomaz** [ampproject/amphtml#22087]
You can see on the example of amp-list: [https://playground.amp.dev/?url=https://preview.amp.dev/documentation/examples/components/amp-list](https://playground.amp.dev/?url=https://preview.amp.dev/documentation/examples/components/amp-list)

the 2nd list use the placeholder feature, but you can check the load time is high.

You can see the same problem here: [https://www.cibercuba.com/noticias](https://www.cibercuba.com/noticias)

**Comment by mattwomple** [comment]
In the example `https://playground.amp.dev/?url=https://preview.amp.dev/documentation/examples/components/amp-list`, there is a comment just above `<amp-list id="amp-list-placeholder"` that explains why its load time is high: "We are using an endpoint which intentionally delays the response by 10 seconds." This is done so that users can see the placeholder before the `amp-list` loads.

On `https://www.cibercuba.com/noticias`, have you tested different [`binding`](https://amp.dev/documentation/components/amp-list?referrer=ampproject.org#binding-(optional)) attribute values? You might see a performance increase with `binding="refresh"` or `binding="no"`.
