### ISSUE TITLE
`amp-skimlinks` tests are flaky

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#22154]
```
DESCRIBE => amp-skimlinks
  DESCRIBE => Basic features
    DESCRIBE =>  
      IT => Should send the page impression tracking request
        ✗ Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

DESCRIBE => amp-skimlinks
  DESCRIBE => Basic features
    DESCRIBE =>  
      IT => should send NA-tracking on non-merchant link click 
        ✗ Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
Failures from the past few hours:

https://travis-ci.org/ampproject/amphtml/jobs/528860786#L1940-L1944
https://travis-ci.org/ampproject/amphtml/jobs/527886895#L1533-L1539
https://travis-ci.org/ampproject/amphtml/jobs/527096273#L1909-L1914
https://travis-ci.org/ampproject/amphtml/jobs/528755387#L377-L381

/to @sparhami, who is build cop this week

**Comment by sparhami** [comment]
It looks like these tests make a request to an external URL (https://t.skimresources.com/api/...), which seems like it times out or fails quite often. Three of the tests timeout 100% of the time for me locally:

        ● Should send the page impression tracking request
        ● Should send the links impression tracking request
        ● should send NA-tracking on non-merchant link click 

These match the tests that are timing out above. Additionally, the above links has

        ● Should send merchant links to to waypoint on click

as failing due to an assert, but I don't see that locally. It could be the endpoint for that test returned some bad data.

I will skip these tests for now, since there seems to be no problem with AMP itself, but there could be an issue with the API endpoints this extension is using.

@slocka

**Comment by rsimha** [comment]
I'm seeing more `skimlinks` tests failing on `master` today.

```
DESCRIBE => amp-skimlinks
  DESCRIBE => Affiliate unknown links
    DESCRIBE =>  
      IT => Should send unknown links to waypoint
        ✗ AssertionError: Target cannot be null or undefined.
            at http://localhost:9876/home/travis/build/ampproject/amphtml/test/integration/test-amp-skimlinks.js:248:29
```
https://travis-ci.org/ampproject/amphtml/jobs/529288928#L1940-L1945
https://travis-ci.org/ampproject/amphtml/jobs/529101437#L1940-L1945

Seems like there's a more widespread problem with this suite?

**Comment by sparhami** [comment]
Hmm, maybe we should disable the tests entirely. It seems like the endpoint might not be reliable enough to use it in the tests. Not sure if there is a longer term plan here (have some sort of golden files for network requests? how would they be updated?).

**Comment by rsimha** [comment]
I agree with not having tests that rely on an external end point. Would it be possible to use a local endpoint from `examples/` in the tests?

For the time being, skipping the flaky suite SGTM.

**Comment by slocka** [comment]
Thanks for flagging. We are having stability issues with one of our core API and I believe this is the reason why the tests started failing. I am happy to change the tests to not rely on any external endpoint but I am not sure how to do it. Is there a way to mock the response of a request?

**Comment by sparhami** [comment]
I'm not sure we have an established pattern or a useful wrapper, but you could do something like `amp-live-list` does:

https://github.com/ampproject/amphtml/blob/df6bc8998892d9b8bf97b56cdf897b99d587975a/extensions/amp-live-list/0.1/test/test-live-list-manager.js#L50-L62

https://github.com/ampproject/amphtml/blob/df6bc8998892d9b8bf97b56cdf897b99d587975a/extensions/amp-live-list/0.1/test/test-live-list-manager.js#L334-L339

which uses [Sinon's XHR stubbing](https://sinonjs.org/releases/latest/fake-xhr-and-server/). Not sure how useful that XHR buffer thing is, I think ideally, we would have something that matches the XHRs with the request URL and responds with a payload rather than operating on an index.

We might have something better that I am not aware of though.

/cc @cvializ Are you aware of any integration test XHR stubbing that we might already have?

**Comment by cvializ** [comment]
I am not aware of anything better, but stubbing the request somehow, including using the Sinon XHR stubbing with indices would be preferred over making the real request.
