### ISSUE TITLE
Wildcard domains in origin experiments

### ISSUE THREAD

**Issue by patrickkettner** [ampproject/amphtml#22169]
Origin Trials [have the ability to be wildcard](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md#13-i-have-multiple-testingstaging-domains-or-subdomains-that-are-programmatically-generated-do-i-need-to-request-a-token-for-every-subdomain) domains (i.e. *.foo.com), however the current implementation [only allows for FQDNs](https://github.com/ampproject/amphtml/blob/ca63c9982871efaee01b792f79ee06957de30d7c/src/service/origin-experiments-impl.js#L206-L212)

**Comment by jeffjose** [comment]
We just ran into this during the testing of amp-experiment with a vendor. Will it be possible to prioritize this higher?

**Comment by nainar** [comment]
Couple of things need to be done before we can support this:
- We want to make sure that an Origin Trial token is not issued for more than 6 months. 
- We should be able to validate components if the origin trial token is correct on the page (This isn't currently done)
- We also want to make sure we can cap the population of the web that is exposed to an Origin Trial since we don't want folks depending upon this. 
- We also want to make sure that partners understand that something launched in Origin Trial is not expected to upgrade to full launch and that we can turn of an Origin Trial at any time. (For e.g too large of the web depends on it, we discovered a security flaw, etc.)

@kristoferbaxter

**Comment by jeffjose** [comment]
From a vendor's perspective, when they productize features, they create automated integration tests to cover future regression testing that run under several subdomains. Usually, these integration tests are executed on different browsers with support of Selenium.
