### ISSUE TITLE
Validator : bug with dailymotion

### ISSUE THREAD

**Issue by okeul** [ampproject/amphtml#2222]
This component works well but there are several errors in the console.

**1) Case 1 :**
After playing the video :
![capture d ecran 2016-02-23 a 3 21 52 pm](https://cloud.githubusercontent.com/assets/6248074/13254340/383aa666-da41-11e5-8c14-b28ae9f3b128.png)

**2) Case 2 :**
Validator doesn't support long ID :
![capture d ecran 2016-02-23 a 3 20 16 pm](https://cloud.githubusercontent.com/assets/6248074/13254293/05ba5d80-da41-11e5-98e9-98bbb0f3ff19.png)

http://output.jsbin.com/dokosa/#development=1

**Comment by erwinmombay** [comment]
that latter one definitely looks like a bug https://github.com/ampproject/amphtml/blob/master/validator/validator.protoascii#L3057 (only allows lowercase?)

**Comment by erwinmombay** [comment]
actually i stand corrected, please use `data-video-id` instead of `data-videoid` for amp brightcove https://github.com/ampproject/amphtml/blob/master/extensions/amp-brightcove/amp-brightcove.md. `data-videoid` is probably deprecated.

**Comment by cramforce** [comment]
@powdercloud Lets remove those validations for extensions data values.

**Comment by okeul** [comment]
Thanks guys for your quick answer. About case 1, do you need a specific issue ?

**Comment by cramforce** [comment]
@okeul For case 1 paging @zeno. This is a bug on the dailymotion side.

**Comment by powdercloud** [comment]
Btw, video ids starting with k are private.
See here: https://developer.dailymotion.com/player#player-api

**Comment by zeno** [comment]
Regarding Case 1)
It's a known issue we discussed with Google: we are in the process of making all of our ad partners switch to HTTPS. In the meantime you might still see (like in this case) a non-https request attempt from a 3rd party ad provider down in the ad chain, those calls are gonna get blocked. So that error notifies about a failed ad request attempt, it’s not an error about the video. Everything on our side is HTTPS (every resource loaded as well as the video streams). Hopefully you should see those errors disappear soon. 

Regarding Case 2)
@powdercloud is right: 'k' video ids are for private videos and they are valid. So you might want to update your `value_regex` to support uppercase chars too (`"[a-z0-9]+"` => `"[a-zA-Z0-9]+”`), or remove that validation…

**Comment by Gregable** [comment]
We'll definitely fix the case-sensitivity issue. A fix is already prepared, but I'm not sure we can make changes until Monday with the launch. My apologies that this didn't get caught in time.

We could presumably disallow video ids beginning with "k", if that is something you would like us to do. On the pro side, it might help a publisher spot and debug the issue earlier. On the con side, presumably you could use amp html on a private page not intended for inclusion in the cache.

**Comment by Gregable** [comment]
Unless you find a new issue, this has been fixed in github and in the cache. I won't be releasing the fix to the javascript validator (`#development=1`) immediately, but that'll come very soon. In the meantime, just ignore these errors.

**Comment by Gregable** [comment]
This fix should be live everywhere. Let me know if you see further errors.
