### ISSUE TITLE
amp-script: Add a way to preventDefault for events

### ISSUE THREAD

**Issue by fstanis** [ampproject/amphtml#22253]
## Describe the new feature or change to an existing feature you'd like to see

It would be good to have a way to prevent the default behavior when using events such as `tap` (for example, link opens). This would be equivalent to `event.preventDefault()` in JavaScript.

I propose having a `preventDefault` action that can be added, separated with a comma, like any other action, e.g. `<a href="/" on="tap:AMP.setState({}), preventDefault">Click here</a>`.

## Additional context

Example use:

    <form method="get" action-xhr="/endpoint" id="myForm"></form>
    <a href="/endpoint" on="tap:myForm.submit, preventDefault">Test</a>

The user can copy the link or open it in a new tab, but if they simply tap, the form is submitted instead and they don't navigate to a new page.

**Comment by choumx** [comment]
This is also useful for `amp-script` since there's no way to call `preventDefault` from the web worker.

**Comment by doradsoft** [comment]
@choumx Any workaround?

**Comment by schlessera** [comment]
If `event.preventDefault()` is not properly supported right now, I think the [compatibility table](https://github.com/ampproject/worker-dom/blob/0c9eeb362201b9401f8d4c1959205801358dc345/web_compat_table.md) should be adapted.

It currently states that `event.preventDefault()` is supported, and even though that might be technically true as it doesn't throw errors, it also doesn't do what it is supposed to do, so that is highly misleading. For all practical purposes, it's not supported right now and all use cases requiring it are not directly implementable with `<amp-script>`, AFAICT.

**Comment by choumx** [comment]
Thanks for flagging the documentation bug!
