### ISSUE TITLE
AMP4Email: amp-lightbox positioning issue

### ISSUE THREAD

**Issue by brettdavis13** [ampproject/amphtml#22297]
## What's the issue?

In Gmail, amp-lightbox uses `position: fixed!important;` and ` top: 0!important` which attaches it to the top of `<iframe id="amp-iframe">`. If the user scrolls down on the email and then triggers the light-box, the light-box will display above the viewport.

## How do we reproduce the issue?

1. Send yourself an AMP email where you have to scroll down to trigger an amp-lightbox.
2. Once triggered, scroll up to see that the lightbox is fixed to the top of the amp-iframe.

## Which AMP version is affected?

AMP4Email

**Comment by torch2424** [comment]
Triaging to @choumx , Feel free to re-assign 😄

**Comment by fstanis** [comment]
Hi @brettdavis13, could you tell us more on how you're trying to use amp-lightbox in an email? This problem turned out to be difficult to tackle, so seeing some use-cases would help us better understand which approach to take.

**Comment by brettdavis13** [comment]
Hi @fstanis, please see my [JS Bin example](https://jsbin.com/fiyuqor/edit?html,output). The button at the bottom of the HTML should trigger an amp-lightbox. While this functionality works in JS Bin, it doesn't behave the same way when sent as a dynamic email. Here is a [screen capture of the bug](https://gfycat.com/JovialHarmlessAmericanbulldog).

**Comment by fstanis** [comment]
Understood on the technical side, I was just curious if you could share more about the use-case, i.e. what the lightbox would do in a real-world scenario?

Again, this is to better understand us how the component would be used in emails, since we haven't seen any use-cases for it yet.

**Comment by brettdavis13** [comment]
Ah sorry, I misunderstood.
We populate an email with a list of job openings. This list is usually long enough to cause scrolling.  Currently, users click on a job and land on a landing page with more information about the job. We would like to pass the job information to a lightbox with all of the job information, including a CTA button to "Apply" (which would send you to our web app).

**Comment by modernwarfareuplink** [comment]
@brettdavis13  Can you try this one out? https://github.com/ampproject/amp.dev/pull/2105#issuecomment-594354441

**Comment by sharkcrayon** [comment]
I'm coming across the same issue when trying to use `position: fixed` within an AMP email for a different purpose (a sticky header, and always-visible-within-the-email success and error messaging).

I think this comes down to what "fixed" means conceptually within an email, as well as what the "viewport" conceptually means in this context.

On a webpage, the viewport is the inside of the browser window. As a result, `position: fixed` anchors an element to the specified position inside that window, regardless of the position of the page contained inside.

The current use of `position: fixed` within email differs from this, in that it's relative to the "page" (i.e. email) rather than the viewport. This causes an element that is `position: fixed; top: 0` to show up at the top of the email itself, even though that might be scrolled out of view.

I don't like this behavior, and I'd rather it mimic how `position: fixed` works on the web.

To mimic it though, I think we need a different version of what a "viewport" is when it comes to email.

Within email, I view the conceptual equivalent to the browser viewport to be the boundaries that the email is viewed within, bounded by the browser viewport. In other words, if the email extends below my browser viewport (so is not entirely visible), I would expect something that is `position: fixed; bottom: 0` to be visible at the very bottom of my browser viewport. If the email was scrolled down all the way and there was non-email content visible below the email, then I would expect the `position: fixed; bottom: 0` element to be displayed at the very bottom of the email that it belonged to.

It's hard to explain without pictures or video, but does that make sense?

**Comment by sharkcrayon** [comment]
This is also how I'd expect `amp-sidebar` to behave: That it would always be visible, with its top anchored to either the top of the email or the top of the viewport (if the top of the email was scrolled out of visibility), and its bottom anchored to the bottom of the email or the bottom of the viewport (if the bottom of the email was scrolled out of visibility). Within that area, it would be internally scrollable.
