### ISSUE TITLE
Update / delete `build-system/SERVING.md`

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#22384]
The [How AMP HTML is deployed](https://github.com/ampproject/amphtml/blob/master/build-system/SERVING.md) article was written 3 years ago, and is outdated.

Once the new release workflow is in place, this file should either be updated or deleted.

**Comment by erwinmombay** [comment]
We probably need a follow up task for this where `dist` just does the right thing without the other instructions.

other caches still need to know and understand how to deploy AMP since we have multiple directories under root that are part of the AMP "library". (i wish it was just 1 directory, ideally dist but i think its a little too late)
