### ISSUE TITLE
Inconsistency between GSC and AMP Validator

### ISSUE THREAD

**Issue by anuragphadke** [ampproject/amphtml#22517]
## What's the issue?

AMP Validator and Google Search Console for AMP returning different results.

## How do we reproduce the issue?

1. Enter the URL below in GSC and AMP Validator
https://amp.stewartmovingandstorage.com/amp/pensacola-moving-hacks-you-should-know-when-moving-to-from-pensacola-florida.html 
2. AMP Validator gives a thumbs-up.
3. GSC fails with specific errors.

Details:
AMP validator is marking the above page as valid (https://validator.ampproject.org/#url=https%3A%2F%2Famp.stewartmovingandstorage.com%2Famp%2Fpensacola-moving-hacks-you-should-know-when-moving-to-from-pensacola-florida.html), however, GSC returns it as invalid.
https://search.google.com/test/amp?utm_source=gws&utm_medium=onebox&utm_campaign=suit&id=ixTwAgujfsRiTX4eLTjEDw

**Comment by torch2424** [comment]
cc @sebastianbenz as I remember you helped solve a search console issue in the past 😂

**Comment by Gregable** [comment]
It appears that the web server in question is returning different pages to the AMP Validator vs. GSC. 

For example, GSC is describing issues with a `<path>` tag. The AMP Validator code view does not show a `<path>` tag anywhere in the document.

It is unclear what set of conditions is resulting in the different responses from the server, but the issue is server-side.
