### ISSUE TITLE
amp-list resizing broken 

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#22552]
The release yesterday broke https://amp.dev/boilerplate/.

Steps to reproduce:

* go to https://amp.dev/boilerplate/
* select on of the checkboxes on the left
=> no code snippet visible (the initial snippet is server-side-rendered and gets replaced with an amp-list when the config changes).

This is what the implementation looks like (simplified from amp.dev/boilerplate):

```
      <amp-list id="codeSnippet"
                width="auto"
                layout="fixed-height"
                [src]="config"
                single-item
                binding="always"
                [is-layout-container]="config.changed"
                hidden [hidden]="!config.changed">
   ....
</amp-list
```
Adding a dummy height binding `[height]="1"` fixes the problem.

**Comment by choumx** [comment]
Thanks for the report. 

This is due to a change in #22227 that postpones rendering of amp-list triggered by `[src]` binding with local data from "immediate" to "layout". The problem is that "layout" won't happen if the element has a zero size. 

In the boilerplate case, looks like `amp-list#codeSnippet` has a static height of 0.

**Comment by choumx** [comment]
As you mention, giving the `amp-list` a defined height fixes this issue but we should probably revert this behavior change since it may break other pages.

Related external reports: `b/133433229`, `b/133355484`
