### ISSUE TITLE
Carousel & landscape bug on iPad

### ISSUE THREAD

**Issue by okeul** [ampproject/amphtml#2256]
Hi !

There is a bug with the carousel and the landscape mode on iPad.

1) In portrait mode it works well.
![portrait](https://cloud.githubusercontent.com/assets/6248074/13281834/4889725e-dae6-11e5-9263-bc01c5689382.png)

2) Bug appears after a switch in landscape mode.
![landscape](https://cloud.githubusercontent.com/assets/6248074/13281854/673b2aee-dae6-11e5-84b4-ff51882a29b4.png)

3) After a refresh, the article displays well but we can't slide between other website and bullets point in the header are gone.
![landscape_refresh](https://cloud.githubusercontent.com/assets/6248074/13281875/85061a02-dae6-11e5-83de-7fc53c8aa386.png)

Tested on :

iPad Air 
Model : md788nf/a
iOS : 9.2

iPad 4
Model : md523nf/a
iOS : 9.0.1

Let me know if you need more information.

**Comment by ericfs** [comment]
Thanks for the report. As this seems specific to Google search. I'll file an internal issue for it.

**Comment by sketchytech** [comment]
I wanted to add some points about this because the behaviour is different between Chrome and Safari on an iPad

1. Both browsers currently display AMP articles misaligned when opened in landscape
2. If opened in portrait or turned from landscape to portrait they then display correctly
3. In Safari once you've been in portrait and returned to landscape the articles continue to display correctly
4. In Chrome turning back to landscape the layout returns to a misaligned state

**Comment by dvoytenko** [comment]
Thanks @sketchytech . We found a problem and the workaround and will fix it soon.

**Comment by dvoytenko** [comment]
Internal tracking: b/27333870
