### ISSUE TITLE
Handle meta tags from AMP to the PWA when used as data source

### ISSUE THREAD

**Issue by Joelsz** [ampproject/amphtml#22587]
## What's the issue?
We have an existing AMP environment and a separate SPA with PWA environment, now we're working on combining them with the "Use AMP as a data source for your PWA" initiative with AMP Shadow. Everything seems to be well documented and pretty straight forward, except the meta tags.

Currently, the PWA gets its meta tags from the JSON data source and injects it to the head tag, vs the AMP page has its meta tags hard in the html. Now, we need to figure out how to get the meta tags from the AMP document and inject it to the PWA head tag.

I found the easiest way to work around this by querying the Shadow DOM for all meta tags `doc.querySelectorAll("meta")` and inject it to the head after `AMP.attachShadowDoc()`, but obviously, this is not the preferred method.

## Proposed resolution
I suggesting exposing all the meta tags on the Shadow AMP instance (value returned from `AMP.attachShadowDoc()`), just like it has the `title` and `canonicalUrl` properties it should have another property, for example `meta`, with an array of nodes or attribute and value pairs.

Or maybe AMP should be the one taking care of the meta tags and transfer it to the PWA head tag, so no manual injections would be needed from us developers, after all AMP is in control now.

I'll leave the final resolution for the AMP engineers to decide.

**Comment by prateekbh** [comment]
@dvoytenko any views on this?
I dont mind adding the meta tags but i also saw that `this.amp_.ampdoc.getHeadNode()` gives access to Head Node but its children does not have Meta Tags.

Can we expose them there? So the publisher could just run a filter on `this.amp_.ampdoc.getHeadNode().children`

**Comment by dvoytenko** [comment]
Preliminary, I like the proposed solution by @Joelsz or some variation of it. The reason is that inserting `<meta>` tags inside the shadow root might have some odd consequences that are not expected. Right now, I don't believe we insert any meta tags into shadow root's head. We could always consider returning the parsed detached `head` object as part of the `AMP.attachShadowDoc()` response. That way one could still use familiar DOM APIs to query meta, link, and other tags.

WDYT?
