### ISSUE TITLE
Request: New Validator Rule for Mandatory Parent Attribute

### ISSUE THREAD

**Issue by chenshay** [ampproject/amphtml#22595]
@wg-caching

In the AMP Validator:
We'd like a new validator rule that's similar to mandatory_parent, just a bit different.
We'd like for it to be something like mandatory_parent_attribute where a child can require its parent to have a specific attribute, and the parent can be any html tag.

Example:

<whatever_tag mandatory-attribute="mandatory-value">
    <child_tag></child_tag>
</whatever_tag>

Proposed Validator rule format:

tags: {  # child_tag
  html_format: AMP
  tag_name: "CHILD_TAG"
  mandatory_parent_attribute: {
    name: "mandatory-attribute"
    value: "mandatory-value"
  }
}

**Comment by jpettitt** [comment]
We may not need this after all :-)

The use case was 

```
<sometag subscription-section="content">
   base 64 script tag with encrypted content
</sometag>
```

Where we want to enforce that the encrypted content has the `subscription-section` attribute on the parent.

However, the validator won't see the page until after the base64 block has been decrypted and replaced with the `amphtml` plaintext which should be valid, and critically, at that point there will be no base64 script to care what it's parent was.

I think what we need to do is fail the decrypt (throw a user error) is the parent is incorrect and then the validator will fail the page because the encrypted block is not valid amp.

**Comment by Gregable** [comment]
Closing this issue as per @jpettitt 's comment. Feel free to reopen.
