### ISSUE TITLE
CDN not caching images

### ISSUE THREAD

**Issue by dmquadrat** [ampproject/amphtml#2276]
The images in my articles come from absolute URLs on a different server than the AMP Site. More than half the time, images will not display if you reach them through the search carousel. If you enter the URL manually, everything works fine. Here's an example:

This one works: https://cdn.ampproject.org/i/www.abendzeitung-muenchen.de/media.imagefile.8fe7b8ae-1c0a-4bfa-be7d-acfda9e2a240.normalized.jpeg

This one doesn't: https://cdn.ampproject.org/i/www.abendzeitung-muenchen.de/media.imagefile.c23901ae-61f0-4b8d-87d6-d490f0185190.normalized.jpeg
If you remove the CDN-URL you can see that the image does exist on my server.

The articles are identical in structure and all validate. This error seems completely random. It even happens on the same page when I'm using multiple images in a gallery. 

I tried recrawling the page through webmaster console, but that doesn't help.

**Comment by cramforce** [comment]
@dmquadrat The reason is that the image is served without a content-type header. We only allow images images that have a mime type starting with "image/" to avoid security issues with browser sniffing.

We will have better docs about this out shortly and are also looking into making the error message actually say what the problem is. We understand it is way too hard to debug right now!
