### ISSUE TITLE
amp-consent CMP: AMP CDN url bar overlays fullscreen Prompt UI iframe

### ISSUE THREAD

**Issue by hrkhal** [ampproject/amphtml#22994]
When viewing content on the Google CDN the AMP url menu overlays the amp-consent prompt iframe when in fullscreen mode.

To reproduce:
1. Visit https://www.google.com/amp/s/metro.co.uk/2019/06/25/cat-charity-boss-forced-pensioner-sleep-outside-eat-pet-food-10055967/amp/ on a device with EU Geo.
2. On the CMP prompt hit the `Privacy Settings and policy` link and note that the once fullscreen opens the AMP CDN url bar overlays the content.

I've tested on Samsung 9+ Chrome and Samsung Browser and on an iPhone XR Safari and the issue exists in all of them.

This issue does not happen when `amp-lightbox` is in fullscreen mode, the url bar correctly retracts / is hidden. 

Relates to #22943

cc @zhouyx / @torch2424

![IMG-20190625-WA0000](https://user-images.githubusercontent.com/7547332/60087202-747db600-9734-11e9-968f-1f9add7e8ed2.jpg)

**Comment by torch2424** [comment]
@hrkhal Thank you very much for finding this!

cc @zhouyx 😄

**Comment by torch2424** [comment]
Hello! So I figured out why this does not mimick Lightbox's behavior. The reason is, it seems that Lightbox calls `enterLightboxMode` on the viewport service, which in turn [sends a message to the viewer to hide itself](https://github.com/ampproject/amphtml/blob/master/src/service/viewport/viewport-impl.js#L772). Thus we need to mimick this behavior. From what I can tell, all we should need to do is send the message, as the Lightbox mode is doing a lot of things we don't need.

cc @jridgewell do you have any advice on this? Especially how we can test the viewport hiding itself to see the example working. 

I have a branch here if anyone is interested: https://github.com/torch2424/amphtml/tree/consent-viewer-overlay

FYI @zhouyx

**Comment by jridgewell** [comment]
> as the Lightbox mode is doing a lot of things we don't need.

What's unneeded?

>  I currently am sending the message, but my "hacked together" example isn't working.

Just sending the message like https://github.com/ampproject/amphtml/blob/50102ccd813e6f8ecfbc34cbeb6a7f28db313964/src/service/viewport/viewport-impl.js#L772-L776 should work fine.

**Comment by torch2424** [comment]
@jridgewell 

> What's unneeded?

So from the code, it seems like enterLightBox mode does a lot of overlaying handling that is specific to the lightbox extension, as well as implementing thins like a friendly iframe. All we want to do in our case is hide the viewer, that way our animation can slide up our consent UI. We don't need any special overlay or friendly iframe from what I can tell 😄 

> Just sending the message like ... should work fine.

Yep, had to do a lot of digging around testing with the viewer, and it worked! 😄 🎉
