### ISSUE TITLE
amp facebook comment is not working on dynamic page.

### ISSUE THREAD

**Issue by akash4223** [ampproject/amphtml#23125]
In amp facebook comment component we have a field called data-href. This is where the absolute url of page where comments go has to be entered. But when a page is dynamic and the url is dynamic its becomes very difficult to do so. 

If one is not using AMP framework it is actually very easy to do. Just leave the data-href field empty and it will automatically take the current url of the page, but with amp we can not leave the data-href field empty because it is a required field.

We can not even use external javascript to solve the issue.

**Comment by cathyxz** [comment]
I think maybe there is a bit of confusion here. The `data-href` field is supposed to take in the `url` of the facebook comment that you are trying to display, not the url of your own page. In order to embed a facebook comment, you have to know the url of that comment. Are you by chance looking for a sharing component instead, that will, for example, automatically share the current page you are on? Maybe `<amp-social-share>`? 

Sample code below: 
```
<amp-facebook width="552" height="500"
    layout="responsive"
    data-embed-type="comment"
    data-href="https://www.facebook.com/zuck/posts/10102735452532991?comment_id=1070233703036185">
</amp-facebook>
```
(Source: https://amp.dev/documentation/components/amp-facebook)

**Comment by cathyxz** [comment]
Closing for now, since we haven't heard a response. Feel free to re-open this issue and follow up if needed.

**Comment by mateusnds** [comment]
Qual a solução? Estou com o mesmo problema
