### ISSUE TITLE
I2I: remove amp-embed allowed list 

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#23172]
`<amp-embed>` is a custom-element alias for `<amp-ad>` to support 3rd party content embed that are not ads. In reality most of the usages are so called "Content Recommendation" services. Those serves either provide cross-site link exchange or in-site article recommendation. Sometimes those content are mixed with ads.

We right now maintain a whitelist of vendors that are allowed to use this `<amp-embed>` syntax sugar. However, we don't really have an actionable criteria for the whitelisting. So it's mainly operated as "add while asked". 

I want to revisit the value of such a whitelisting. I suggest we remove it and just let vendors decide what syntax should be apply to publisher tagging. Overall, vendor is in the best position to decide what product are they offering to their customers. 

@ampproject/wg-ads

**Comment by zhouyx** [comment]
Sounds good, I agree that we don't have an actionable criterial for whitelisting. 

One comment. From all the vendor integration I reviewed previously, most vendor only support one syntax. And because of that I never ask them to implement the `renderStart` API when they add themselves to the amp-embed whitelist. We may need to ask them what syntax they want to support in the future, and document that the renderStart API is designed for amp-ad only. Thanks.

**Comment by lannka** [comment]
@zhouyx do you see reasons why we not recommend renderStart API for embed? I think the vendors will get the same benefit of an improved loading experience.

**Comment by zhouyx** [comment]
It's not that we don't recommend. The API is mostly used to toggle placeholder and show ads at the proper time. But we don't apply any placeholder for amp-embed, so the API is not very useful.

**Comment by lannka** [comment]
That makes sense.
