### ISSUE TITLE
Swipe gestures

### ISSUE THREAD

**Issue by demil** [ampproject/amphtml#23252]
Is there possibility to detect swipe event in amp on body or any other element and set desired event callback, just like on intersection observer for example?

**Comment by choumx** [comment]
What's your intended use case?

**Comment by TheRook** [comment]
@dreamofabear  If the `amp-story-grid-layer` was a 2d array, instead of just a list - then you could use a "swipe up" to move up or down, as well as swipe left and right.

Now, this simple change would allow you to display a very large infographic - that is maybe a large PNG that is broken up into 9 cells three rows each - and you start in the center and you can swipe to go to the different sections of the infographic. 

Another use-case is... gaming. Think of a 2d `amp-story-grid-layer` as being a map, and each page is a "room" of the game. You can use the tap operation to collect items or interact with the world, and swipe to "move" the map between rooms.  

I hope that we can do a "choose your own adventure" style amp-story using `amp-script` to catch touch events.  But it would be nice if there was a first party solution to support these kinds of advanced stories.
