### ISSUE TITLE
Moving elements for fixed layer can prevent CSS selectors from working

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#23340]
https://www.hiscox.com/amp/small-business-insurance/

See the following screenshot, which shows the phone number of a popup getting cut off, along with text above the button. It appears 5 seconds after page load using amp-animation.
![image](https://user-images.githubusercontent.com/7919520/61255144-3b75a780-a71c-11e9-877c-19d43defd7ff.png)

The expected behavior is visible on their hosted AMP page. iPhone and Nexus emulation both display correctly. Visiting the hosted AMP page on my iPhone also displays it correctly.

iPhone
![iphone](https://user-images.githubusercontent.com/7919520/61255201-5f38ed80-a71c-11e9-967f-99bcddd3e14e.png)

Nexus
![nexus](https://user-images.githubusercontent.com/7919520/61255206-619b4780-a71c-11e9-8b7b-156a1e5ea6ab.png)

The cache URL doesn't exhibit this issue in iOS or Android, so it appears to be a viewer issue.

Filed by Philip Kriegel at Google.

**Comment by sparhami** [comment]
The animations themselves are working just fine.

The positioning is due to the fixed layer handling moving elements. More specifically, the header bar is moved from the current location into the duplicated body. This prevents the following CSS rule from working correctly:

```css
.ampstart-headerbar+:not(amp-sidebar),.ampstart-headerbar+amp-sidebar+* {
  margin-top: 2.8rem
}
```

The sibling selector no longer works since the `.ampstart-headerbar` has been moved to a different DOM subtree. I'm not aware of all the issues with fixed layer and why it is needed, but this is a known (though perhaps not communicated in documentation) consequence of AMP moving DOM elements for iOS iframes.

This can be worked around by changing the CSS to no longer rely on a sibling selector. That is, give the appropriate styling to the elements using a different selector by giving things a class to target.

**Comment by sparhami** [comment]
@nainar We can't actually fix this issue, but we can perhaps document it. There is also no way for us to validate which sibling selectors `+` or `~` will be impacted by this issue.

**Comment by choumx** [comment]
Looks like this CSS originates from ampstart, so this probably affects a bunch of other sites: https://github.com/ampproject/ampstart/blob/9acc6ca2e48f984f4749748cc53ab6405d47d4d4/components/navbar/navbar.css#L24-L27

Chatted with @jridgewell and there doesn't seem to be a good way to track and restore lost styles due to reparenting. 🤞 for scrolling iframes in iOS 13.

**Comment by philkrie** [comment]
What's the best way to deal with this on the client side? Are there any workarounds? It's a key component of their site.

+1 to documentation on this... easy to miss. In fact, would be great to have a tool that generates a group of screenshots that confirm everything looks consistent across AMP Viewer, Cache, and Hosted AMP across a range of devices.

**Comment by jridgewell** [comment]
Can you avoid any sibling selectors on fixed position elements?

**Comment by choumx** [comment]
Things to do here:
1. Add documentation for fixed position elements on iOS in iframes.
2. Refactor the amp-start template to avoid this edge case.

@jridgewell Let's schedule (1) for the fix-it.

**Comment by philkrie** [comment]
@jridgewell perfect, makes sense, I see @sparhami originally suggested that. Thanks!

**Comment by jridgewell** [comment]
Initial tests for iOS 13 look very good. It's possible we'll be able to disable our hack entirely and still get perfect fixed-position scrolling.

**Comment by choumx** [comment]
Can you share how we'd ship this (disabling the hack) to users?

**Comment by jridgewell** [comment]
It's controlled by the viewer: https://github.com/ampproject/amphtml/blob/e01933c4758e7441f38662ac7082ed44d48db5e1/src/service/viewport/viewport-impl.js#L1405-L1439
