### ISSUE TITLE
Feature Request: Pull to Refresh

### ISSUE THREAD

**Issue by L42y** [ampproject/amphtml#23371]
## Describe the new feature or change to an existing feature you'd like to see
[Pull to Refresh](https://en.wikipedia.org/wiki/Pull-to-refresh) is a popular UI pattern

### A clear and concise description of what you want to happen.
I would like to see an implementation letting me refreshing page's data such as those in `amp-list`

## Describe alternatives you've considered
I've googled to see if there is pure CSS implementation of pull to refresh, sadly it's still too complex for CSS, it would have to involve JS for an implementation, then we have to use `amp-script`, I would argue with such a popular UI pattern, it's best to have a built-in implementation

**Comment by cathyxz** [comment]
I think there are a few ambiguities here that makes awkward to have as a feature of just `<amp-list>`.  E.g. Does it refresh when I pull the entire page or just the amp-list that it's supposed to be refreshing? Do I refresh all the amp-lists on the page or just one? Which ones do I refresh? 

I think maybe one thing to do here could be a general swipe down action, that has a UI element (e.g. loader, maybe also customizable), that triggers actions on release, and then activates `<amp-list>`'s `refresh` method. 

It could be part of a gestures library upgrade: 
- an exposed swipe down action (since right / left are overridden by viewer) 
- an element (maybe a container div) has an `on="swipeDown.refresh"`
- downsides here are swipe down might not offer enough nuance (since technically you want to trigger this on release

You could have a `<amp-pull-to-refresh>` element that listens to pull down and release, but also has its in-built default loader UI: 
```
<amp-pull-to-refresh actions="listid.refresh"/ > 
<amp-refreshable lists="listid1,listid2" /> 
```
You could have a `pull-to-refresh` attribute 
```
<div pull-to-refresh="list1, list2"> .... </div>  // defaults to refreshing all children
```
If enough people want something like this, maybe @nainar can help with scoping. =)
