### ISSUE TITLE
amp-carousel animation duration attribute

### ISSUE THREAD

**Issue by doppl3r** [ampproject/amphtml#23494]
Developers should be able to alter the duration of the carousel animations.

For example, adding `duration="2000"` should animate the current slide to the next/previous slide for 2 seconds. Currently, it feels like 1 millisecond between each transition.

The only time attribute we have is `delay="4000"`, which only controls the pause time on each slide.

**Comment by sparhami** [comment]
We are moving to use the browser's native smooth scrolling timing for carousel in 0.2, which is not configurable. We currently have no plans to implement our own transitions.

@nainar Is this something we are interested in asking the browsers for?

**Comment by doppl3r** [comment]
@sparhami, what the intent of using the browser's native scrolling behavior? Currently, the default scroll speed is so fast, you can hardly see it animate from either direction.

**Comment by sparhami** [comment]
> @sparhami, what the intent of using the browser's native scrolling behavior? Currently, the default scroll speed is so fast, you can hardly see it animate from either direction.

To match what the platform thinks is the correct speed as well as moving the scrolling animation off the main thread. The speed can depend on distance scrolled (e.g. if you have a button to move multiple slides away) and might differ based on viewport size. Since the platform can probably make a better determination and using the platform's behavior makes it consistent with how other things work on the platform, this will result in a better overall user experience. It will also be smoother as we no longer need to animate the scroll using JS.

While it would be possible to animate a transform instead of scroll (to avoid the javascript animation problems), then fix positioning afterwards, it would be more complex to implement and not something we are looking at right now.

**Comment by doppl3r** [comment]
That makes sense, thanks @sparhami!

**Comment by austintude** [comment]
> Since the platform can probably make a better determination and using the platform's behavior makes it consistent with how other things work on the platform, this will result in a better overall user experience.

Wait. What?
What is the definition of "better determination"? Is this a browser definable item or a viewer/visitor/site-owner determinable item?
If, indeed, we are attempting to attain a "better overall user experience", then who or what defines 'better'? Is this not a decision for the site owner to make?
When aesthetics are 'determined' by computers/algorithms and not humans, have we not lost the scope of design theory?
Should this not be reconsidered and added as a developer modifiable feature as per all other design choices which are client-side rather than computer/developer side?

**Comment by sparhami** [comment]
> > Since the platform can probably make a better determination and using the platform's behavior makes it consistent with how other things work on the platform, this will result in a better overall user experience.
> 
> Wait. What?
> What is the definition of "better determination"? Is this a browser definable item or a viewer/visitor/site-owner determinable item?
> If, indeed, we are attempting to attain a "better overall user experience", then who or what defines 'better'? Is this not a decision for the site owner to make?
> When aesthetics are 'determined' by computers/algorithms and not humans, have we not lost the scope of design theory?
> Should this not be reconsidered and added as a developer modifiable feature as per all other design choices which are client-side rather than computer/developer side?

Think about how users scroll pages. Scrolling mechanics on all pages are the same and they all rely on the browser (or OS), and behave the way the user expects. When someone implements custom scrolling behavior, it is very disruptive and disorienting to users. I don't think that site owners should implement their own scrolling, even though they are free to do so.

As I mentioned before, we may consider this in the future, but we currently are not looking at doing this at this time.

**Comment by austintude** [comment]
Perhaps I'm misunderstanding something here, but I am not taking about
scrolling down a page. Rather, I am wanting to control the speed at which
images swap out in the likes of an amp-carousel. While I can control the
duration that each image stays on the screen before being replaced, I have
no easy way to define the speed at which they swap from one to the other.
In my opinion, the current default is uncomfortably fast!
