### ISSUE TITLE
[MASTER FEATURE] Stateful AMP

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#23527]
- [x] Research browser back/forward cache support level in AMP
- [x] Support bfcache and create test documents #23634  #23528
- [ ] Polyfill-like feature for preserving scroll position on browsers that do not support bfcache (priority?)
- [ ] Additional layers of state preservation on top of bfcache
- [ ] Page transitions between preserved states

Related issues: #22527 #12360 #23634 

/cc @nainar

**Comment by matthiasrohmer** [comment]
Will this also enable updating the URL with `AMP.pushState`? Otherwise sharing a state that could then be server-side rendered for a first-time visitor would still be impossible.

Specifically thinking of the category filtering on [amp.dev](https://amp.dev/documentation/components/?format=websites). 😉

**Comment by ikriser** [comment]
This would be great for amp for ecommerce as I am trying to get product variations to work. I can change the variation with `AMP.pushState`, but then I am not able to update to the url, so refreshing the page goes back to the initial state, not the most recent state. So I would also request that either the url be able to update with `AMP.pushState` for server-side rendering on refresh, or a type of behavior where `AMP.setState` saves on refresh.
