### ISSUE TITLE
String template evaluation capability in amp-mustache 

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/amphtml#23530]
Very often client-side text templating is very useful.  It is consisted of a string template and key-value map fetched in the form of json objects.
Example:
{"template" : { "message" : "Hello [name], today's weather is [weather]!"}}

{"values" : {"name" : "Mickey", "weather" : "sunny"}}

The outcome: "Hello Mickey, today's weather is sunny!"

Currently this is not doable using amp-list and amp-mustache because values inside a json response is not evaluated, also amp-list cannot be nested.

**Comment by choumx** [comment]
If I understand correctly, the FR is for "client-side templating inside client-side templating"? :)

Can you provide more context on why it's hard to do this server-side?

**Comment by AndrewKGuan** [comment]
In many cases things are doable on server side, but we also need to understand publishers would have business requirements which are hard to work around because reasons like "APIs are shared between AMP and non-AMP",  "endpoints are controlled by a different team/org/company", "it is just much more flexible to have client-side template evaluation capabilities for some situations".

Please consider the follow example for someone selling TVs:
entities:  
TV {brand, screen size, price, shipping cost...}
Return Policy: [p1, p2, p3....]
Shipping Disclaimer: [disclaimer1, disclaimer2, disclaimer3....]
More dimensions...

Actual JSON responses on a TV listing page:
{items: [{tv1},{tv2},{tv3}......]}
{"Return Policy": [p1, p2, p3....]}
 {"Shipping Disclaimer": [disclaimer1, disclaimer2, disclaimer3...]}
More JSON objects...

If one has to provide a tooltip that describe the TV which the user is looking to buy and all those dimensions to produce the final messages are all server-side concatenated, the JSON would be very bloated with repeated texts.  And if someone is doing the same with non-AMP, most likely those pieces of info are served from different json endpoints as templates.  Sometimes these API endpoints are even managed by different CMSs or even sources/domains/businesses.

Hope this would make sense.

**Comment by morsssss** [comment]
Yes, sadly, at larger organizations, people who work on the front end sometimes have no control over the back end. Either the back-end people say it will take months to change a data format, or sometimes data comes from a third party over which they have no control.

Personally, I'd like it if it was possible to introduce a bit of logic into templates. Either via lambda functions in mustache, or by allowing a more powerful templating system like handlebars.

+@alankent

**Comment by alankent** [comment]
Thanks for the mention Ben!

It is a very common problem. A/B testing platforms are frequently selected on the basis of zero developer effort required to make a test (so it injects JavaScript onto the page) solely because any developer effort is almost impossible to get access to. It is very common for it to be much easier to change the frontend HTML than backend services.

Also, headless backends are a lot more common these days (my favorites being e-commerce platforms). If you want to build an AMP theme for Shopify for example, there is no way to change the backend - it is owned by Shopify. You have to adapt to it (it will not adapt to you). Or you have to create and manage a new proxy service (which makes latency worse plus a new service you have to manage when all you wanted to do was create a theme). This is true for all e-commerce platforms that expose APIs.

I personally quite like the idea of a "protocol adapter" which I have mentioned a few times in different places. A JavaScript function that intercepts the outbound amp-list request to set any additional headers etc required by the backend (or even make multiple API calls if needed), then can adjust the response into the JSON that best meets the need of the template. Kind of like a service worker, but guaranteed to always run (it can be run in a worker thread).

**Comment by AndrewKGuan** [comment]
Hi everyone,
are we able to conclude whether this FR is something worth implementing?  Thanks!
