### ISSUE TITLE
Consider opening custom protocols links in _top

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#2357]
We opted into opening custom protocol links in `_blank` for now, this is a tracker bug to consider using `_top` instead for a potential UX improvement - No new tab page opening and closing very quickly after the browser figures out what app to open.

**Comment by mkhatib** [comment]
@dvoytenko I found one case where `window.open(_blank)` breaks the link. Handling `mailto:`.  (top seems to work fine)

For now I'll be adding `mailto:` to the normal URLs in that iOS Safari logic block to unbreak this.

Any top of mind protocols like `mailto:` we need to worry about?

**Comment by dvoytenko** [comment]
I LGTM'd the PR. Can't think of any other like this. Possible also `tel:` - but that has to be tested.

**Comment by mkhatib** [comment]
@dvoytenko I've tested out using `_top` instead of `_blank` to open custom protocols in iOS Safari (incl. whatsapp:, tel:, sms:, mailto:) this works well haven't seen any issues. 

One question remains with ftp: which works with top but this would change the address to the top document, do we want to add a special case for `ftp:` and possibly `http:` to open in `_blank` instead?

Actually for `http:` do we want to always handle this to open in `_blank` when the embedding document is `https:` to avoid the document not doing anything? I know the Google Carousel Viewer handle this well because we're serving from the AMP Cache which adds `_blank` to all links, but this might not be obvious for other implementations of the viewer?

**Comment by dvoytenko** [comment]
@mkhatib We generally should adhere to what CDN says about links, but exceptions are totally fine. I agree with your `ftp:` and `http:` suggestions going to `_blank` always.

Few comments:

> this works well haven't seen any issues

Did this testing include iframe case? One important thing to test is whether or not such links push into history stack, which could be very disruptive for iframes. The easiest way to test this would be probably in devtools console checking on `history.length`.

> AMP Cache which adds _blank to all links, but this might not be obvious for other implementations of the viewer?

One important aspect - I don't believe we are intercepting links at all in the non-iframed case. The only reason we needed to intercept links initially is because fragment navigation pushed into history stack which caused significant problems for iframes - essentially breaking the parent's history stack.
