### ISSUE TITLE
Solid testing infra amp-ad to ad and amp-iframe to iframe

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2358]
Create helper in `testing/iframe.js` to create an iframe that both records the `postMessage` message it receives and that can be instructed to send messages to its parent.

Ideally this mock iframe can be loaded from a data-uri or srcset and is same origin with the container, because that would make tests much less flaky. We need to fool `targetOrigins` and source `origin` verification to accept that without compromising security.

**Comment by mkhatib** [comment]
I am starting to think more about this and putting some thoughts here, feel free to comment if I am missing a point.

As we chatted, one of the usecases for this is to streamline testing ad-resizing cases, [for example this](https://github.com/ampproject/amphtml/blob/master/test/functional/test-amp-ad.js#L134) which actually uses the fixture iframe.

So in testing, instead of loading the bootstrap iframe, we want to use a new bootstrap iframe specifically for testing purposes that loads the iframe from the same domain that the test is running in? That iframe need to be prepped to your specs - keep track of the messages and be instructed to send messages.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
