### ISSUE TITLE
Css psuedo selectors issue in Gmail amp 

### ISSUE THREAD

**Issue by sonia75birdeye** [ampproject/amphtml#23616]
Css Pseudo selectors like :after, :before are not working in gmail amp but its working in gmail playground.

**Comment by fstanis** [comment]
Pseudo-elements like `::before` and `::after` are not supported in AMP for Email (the [list of supported CSS is available here](https://amp.dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-css/?format=email)). The AMP validator doesn't currently validate CSS, so the Gmail playground renders unsupported CSS.

Since these are not supported in HTML in many email clients, it's unlikely support will be added in AMP either.
