### ISSUE TITLE
Add documentation and code sample for posters 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amphtml#23645]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated**
We explain what a poster is and what its used for, but we do not include a code sample or instructions on how to use it. 

**Which part of the site would that content live at?**
https://amp.dev/documentation/components/amp-story/?format=websites#posters

**Comment by newmuis** [comment]
@CrystalOnScript I think we should just remove this, since we talk about them extensively in the [metadata](https://amp.dev/documentation/components/amp-story/?format=websites#new-metadata-requirements) section.  WDYT?

@sebastianbenz it would be hard to preview because it's not actually a feature of the format; it's metadata provided for other platforms to take advantage of (which, I don't believe any are actually currently using)

**Comment by sebastianbenz** [comment]
@newmuis got it, yeah - you're right.
