### ISSUE TITLE
Can't Swipe over amp-youtube in amp-carousel to navigate slides

### ISSUE THREAD

**Issue by paul-matthews** [ampproject/amphtml#2366]
The amp-video tag captures the drag input and doesn't allow the pane to change.

Visible at: http://amp-partners.appspot.com/carousel-video

Reproducible by:
- Embed amp-carousel
- Insert amp-video item
- Insert amp-youtube item
- Insert another amp-video item

Expected:
- Cycle through all videos and watch the correct one

Actual:
- Cycle through first item fine
- Attempt to cycle through amp-youtube and doesn't change item
  - Can't get out of the youtube item

**Comment by paul-matthews** [comment]
Could be related to #2200

**Comment by dvoytenko** [comment]
/cc @erwinmombay @mkhatib 

I think I understand the problem now. Basically, we can't swipe on YouTube since it's an iframe. Hmm... I think our only recourse is to either:
 1. Advise authors to always include `controls` when iframe-based components are present
 2. Automatically show controls ourselves when the frame contains iframe-based components, but only when the component is paused. One way this could be arranged is via an event that a component in slide sends such as "navigational controls should be shown or such".

**Comment by ericlindley-g** [comment]
Rolling into the next milestone

**Comment by mkhatib** [comment]
> 2. Automatically show controls ourselves when the frame contains iframe-based components, but only when the component is paused. One way this could be arranged is via an event that a component in slide sends such as "navigational controls should be shown or such".

I like this, however this brings the question of how do they navigate while the video is playing? One would have to figure out that they need to pause in order to navigate to the next slide which isn't intuitive. I say we keep the navigation controls even when the video is playing the user can always go to full screen mode if they want to watch the video with no obstruction. We can introduce a lite version of the navigation buttons to make it less obstructive and only use these when we automatically show the navigation buttons (when the slide is amp-youtube, iframe...etc).

**Comment by ericlindley-g** [comment]
Agreed that the UX gets tricky if navigation affordances conditioned on video state

/cc @edlea-g for UX thoughts

**Comment by ericlindley-g** [comment]
Rolling into the next milestone

**Comment by cramforce** [comment]
@sriramkrish85's work should fix this.

**Comment by ericlindley-g** [comment]
Heads up to everyone waiting on a fix that this is ready to be dogfooded via an experiment!

If you want to see a new carousel ("slides" version) implementation that supports swiping over iframes (including videos, social embeds, and other iframed content), you can opt into the experiment, and immediately see the updated version for any `amp-carousel` of `type="slides"`

Two ways to try it out:

• Opt into the experiment for "amp-slidescroll" for all pages served via cdn.ampproject.org [here](https://cdn.ampproject.org/experiments.html)

• To test in your development environment, in your javascript console, toggle the experiment on and off by entering:

`AMP.toggleExperiment('amp-slidescroll')`

You can learn more about experiments [here](https://www.ampproject.org/docs/reference/experimental.html).

Note that you shouldn't need to change anything about your <amp-carousel> implementation to use the new version, so please let us know if anything is different or breaks.

And after taking a look, please give us feedback! We're curious to hear how it works for you, and what we can do to make it better (Of course, there are a few other open issues that we're already aware of and would like to address, like pagination options, better swipe affordances, and an improved lightbox. Feel free to give a thumbs up or comment on issue threads that have already identified improvements you'd like to see)

**Comment by sriramkrish85** [comment]
The experiment is 100% now  and hence you should not see this issue any longer.
