### ISSUE TITLE
amp-lightbox animation customization

### ISSUE THREAD

**Issue by oliverfernandez** [ampproject/amphtml#2374]
Currently an amp-lightbox appear animation is fixed to an opacity transition that lasts 0.1s We'd like to be able to customize this behaviour (for example, a slide in).

When looking at the amp-lightbox source code, there's a comment from @dvoytenko that says "use new animations support instead", but I haven't been able to find any documentation about this new animation system in the AMP source code. 

Where could I find more information about this?

**Comment by jridgewell** [comment]
We're tracking this in https://github.com/ampproject/amphtml/issues/2355.

**Comment by oliverfernandez** [comment]
Ops, sorry about that, but  that issue is  related to amp-carousel instead of amp-lightbox, isn't it? Or are we talking about the same animation system?

**Comment by jridgewell** [comment]
Whoops, I read this as `amp-carousel`.

**Comment by nainar** [comment]
@cathyxz raised a great point offline that once we fully launch `<amp-fx="fade-in">` this can be done using that? AMP components eating their own dogfood!

**Comment by alanorozco** [comment]
@nainar Probably can be accomplished in a simpler way :) But keeping the same API (i.e. animation names) should be ideal.

**Comment by nainar** [comment]
Sounds good! :)

**Comment by oliverfernandez** [comment]
Thanks for taking care of this! :)

As per I see in #16813 there will be a new attribute in `amp-lightbox` to select different opening animations.

The limitation I see is that it's constrained to a fixed set of animations.

Could also be possible to use an `amp-animation` component together with `amp-lightbox`? Something like

````javascript
<amp-animation id="myAnimation" layout="nodisplay">
  ... /* Custom lightbox animation*/
</amp-animation>
<amp-lightbox on="open:myAnimation.start">...</amp-lightbox>
````

**Comment by alanorozco** [comment]
Hi @oliverfernandez 

That would require a larger effort, partially to design an API around it. There's more to lightbox that goes on whilst animating (e.g. resource scheduling, focusing, etc.), so that would require some sort of coordination between `amp-animation` and `amp-lightbox`.

There's also technical and UX questions:

- How does one ensure that the opening and closing keyframes are exactly inverse of each other? We could certainly assert that on runtime, but that impacts complexity and performance.

- This is subjective, but how does one ensure that the animation looks and feels good? This is certainly a UX question, but let's not forget that AMP is more than just about performance! :)

If you could describe the style of animation you could accomplish, given feasibility, we can provide the preset for you.
