### ISSUE TITLE
[amp-list] loading-indicators shown not long enough

### ISSUE THREAD

**Issue by dritter** [ampproject/amphtml#23815]
If the List is changed to a layout container and the request takes quite long, the loading indicators disappear too early. The request is still running, but the indicators fade away.

In the below example, clicking on the "Show List (broken)"-Button demonstrates the problem.

This is loosely related to #23769

```html
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <title>amp-list</title>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <!-- ## Setup -->
  <!-- Import the `amp-list` component ... -->
  <script async custom-element="amp-list" src="https://cdn.ampproject.org/v0/amp-list-0.1.js"></script>
  <!-- ... and the `amp-mustache` component in the header. -->
  <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
  <!-- Import the `amp-bind` component for dynamically changing the content of an `amp-list`. -->
  <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
  <link rel="canonical" href="https://amp.dev/documentation/examples/components/amp-list/index.html">
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <style amp-custom>
    .hide-me {
    max-height: 0;
    opacity: 0;
    overflow: hidden;
    transition: max-height .15s ease,opacity .15s ease;
    visibility: hidden;
    width: 100%;
}
  </style>
</head>
<body>
  <amp-state id="mystate">
    <script type="application/json">
      {
      	"hidden": true
      }
    </script>
  </amp-state>
  
  <button on="tap:test-list.changeToLayoutContainer(), AMP.setState({mystate: {hidden: false}})">
    Show List (broken)
  </button>
  
  <button on="tap:test-list.refresh">
    Refresh List
  </button>
  
  <button on="tap:AMP.setState({mystate: {hidden: false}})">
    Reveal withouth layout change (works)
  </button>
  
  <div class="hide-me"
       [class]="mystate.hidden ? 'hide-me' : ''">
    <amp-list id="test-list"
              layout="responsive"
              height="100"
              width="100"
              src="/documentation/examples/api/slow-json-with-items/?delay=10000&x=RANDOM"
              binding="no"
              reset-on-refresh
              >
      <template type="amp-mustache">
        <div class="product">
      <amp-img width="150"
        height="100"
        alt="{{name}}"
        src="{{img}}"></amp-img>
      <div>
        <div>{{name}}</div>
        <div>{{{stars}}}</div>
        <div>${{price}}</div>
      </div>
    </div>
      </template>
    </amp-list>
  </div>

</body>
</html>
```

**Comment by nainar** [comment]
@andrewwatterson do you think the new loaders will also have this problem?

**Comment by nainar** [comment]
Hi @cathyxz this seems to be an issue with the loading logic in `changeToLayoutContainer()` could you take a look when you get the chance? 

The normal loading logic should cause this to keep looping.

**Comment by mdmower** [comment]
This issue occurs because the mutation of an element without width or height results in `this.toggleLoading(false)` due to the element being classified as `!inViewport`. Here's the chain:

The width and height of the `amp-list` are removed in `undoLayout_()`:

https://github.com/ampproject/amphtml/blob/201289bfb7f9354626163a6b2b2d9b8126629f74/extensions/amp-list/0.1/amp-list.js#L1332

When a subsequent mutation is requested and a resources pass is scheduled:

https://github.com/ampproject/amphtml/blob/201289bfb7f9354626163a6b2b2d9b8126629f74/src/service/mutator-impl.js#L250

then `viewportCallback(inViewport)` is called with `inViewport = false` due to:

https://github.com/ampproject/amphtml/blob/201289bfb7f9354626163a6b2b2d9b8126629f74/src/service/resource.js#L672-L679

in

https://github.com/ampproject/amphtml/blob/201289bfb7f9354626163a6b2b2d9b8126629f74/src/service/resources-impl.js#L1303-L1305

This ultimately runs `this.toggleLoading(false)`:

https://github.com/ampproject/amphtml/blob/201289bfb7f9354626163a6b2b2d9b8126629f74/src/custom-element.js#L1228-L1229

**Comment by caroqliu** [comment]
Thanks for the thorough investigation @mdmower. It seems the call to `isDisplayed` resolves to zero dimensions due to the initial `setStyles`. Is there a `premeasuredRect` available such that `isDisplayed` does not resort to measuring the updated dimensions? 

It looks like this series of call causes `!inViewport` every time. We should start by addressing that.
