### ISSUE TITLE
Amp Animation on AMP-Brightcove shows still processing

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#23862]
##What's the issue?
Amp Animation on AMP-Brightcove shows still processing

Briefly describe the bug.
The loading animation is continuously going while video is playing.

## How do we reproduce the issue?
1. Opt into Canary/RC
2. Open JavaScript Console
3. Open https://www.google.com/amp/s/amp.si.com/nfl/2019/08/09/nfl-preseason-2019-week-1-highlights-takeaways

## What browsers are affected?

macOSX Chrome Version 76.0.3809.87

## Which AMP version is affected?
Canary/RC Version: 1908061758110

@kristoferbaxter is this specifically a UI issue or is it more how the video is being played?

## Gif 1
![amp_animation](https://user-images.githubusercontent.com/48487406/62797377-73100f00-ba90-11e9-973f-42583b36e78c.gif)

## Gif 2
![amp_animation_1](https://user-images.githubusercontent.com/48487406/62797675-1d883200-ba91-11e9-9a5b-cc679ae3554f.gif)

**Comment by kristoferbaxter** [comment]
@sparhami – Is this a regression with the recent loaders changes?

**Comment by sparhami** [comment]
The gif appears to show a loader rendered by `<amp-brightcove>` itself and not our new loader. I wasn't able to reproduce on canary/rc, so I'm not sure if there is anything about the new release that would cause a difference in behavior. Since the extension is basically just an iframe, the issue is likely on their end.
