### ISSUE TITLE
amp-facebook-comments do not warn on invalid `data-href`

### ISSUE THREAD

**Issue by jonasmarco** [ampproject/amphtml#23903]
## What's the issue?

I implemented amp-facebook-comments on a page of my site, but it's not loading. 

https://i.imgur.com/DveB8Zb.jpg

## What browsers are affected?

Google Chrome

## Which AMP version is affected?

1907301630320

A page example where it is implemented
https://blog.appegada.com/blog/149/a-causa-do-refluxo-em-pets-pode-ser-a-altura-do-comedouro/amp

**Comment by sparhami** [comment]
The problem seems to be with the `data-href`, it is `data-href="https://http://blog.appegada.com.br/blog/149/a-causa-do-refluxo-em-pets-pode-ser-a-altura-do-comedouro"`. The extra `https://` (or `http://`) seems to confuse the Facebook comments code.

It looks like the validation for the extension currently does not validate that this is a validly formed URL. I'm not sure if that is a change we can make, but that is one way to avoid such problems. Another option would be to add a user assert if the URL does not look well formed.

The message about CORB is the preload for the iframe that renders the content being blocked, but that should not cause problems for rendering. I'm not sure if that is expected, preloading may still work.

**Comment by jonasmarco** [comment]
Hi @sparhami, I removed 'https: //' from the url and resolved, thank you very much.

The CORB message continues, but does not affect rendering.

But once thanks :)
