### ISSUE TITLE
Not all assert calls are being removed from v0.js by babel transforms

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#23960]
#23377 updated the babel transforms to remove `assert` calls. This should have paved the way for the removal of `AmpPass.java` from the custom closure compiler runner. However, removing `AmpPass.java` increases the number of instances of `assert` in `v0.js` from 20 to 80.

Before removing `AmpPass.java`: [20 instances](https://gist.github.com/rsimha/058ebb2bc6c189dff109ead7caa54de5#file-v0-master-js)
After removing `AmpPass.java`: [80 instances](https://gist.github.com/rsimha/058ebb2bc6c189dff109ead7caa54de5#file-v0-amp-pass-js)

See discussion at https://github.com/ampproject/amphtml/pull/23377#issuecomment-521441454

**Comment by rsimha** [comment]
This is still an issue. Reopening based on the discussion at https://github.com/ampproject/amphtml/pull/24047#issuecomment-524038214

**Comment by kevinkimball** [comment]
@erwinmombay is this issue still relevant?

**Comment by rsimha** [comment]
> @erwinmombay is this issue still relevant?

Yes, this is still relevant, and is the only thing that's blocking #24047. Start reading from https://github.com/ampproject/amphtml/pull/24047#issuecomment-577359402 for the latest status.

**Comment by rsimha** [comment]
@jridgewell @erwinmombay Can we prioritize this fix and unblock #24047? Our inability to remove `AmpPass.java` is resulting in cascading build problems, because (as discovered by @kristoferbaxter), `runner.jar` does not reliably run in a concurrent fashion due to the code in `AmpPass.java`.

**Comment by kristoferbaxter** [comment]
I’m out on paternity leave, but started work on a refactor of the Babel transforms necessary to complete this transition.

Note, once complete you can use the async pool implementation (used internally in filesize and open sourced separately) and remove nailgun. Those combined improve compilation times for everyone significantly.

All together on a sample machine it was a 12x reduction in build time.

An additional optimization to finish later would be to request the compilation of all resources together as a complete array instead of extensions separately from runtime.

**Comment by rsimha** [comment]
Reopening due to non-trivial diffs in extension code, leading to test failures: https://github.com/ampproject/amphtml/pull/24047#issuecomment-621643069
