### ISSUE TITLE
Design Review 2019-09-19 00:00 UTC (amp-sidebar)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#23991]
Time: [2019-09-19 00:00 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2019&month=09&day=19&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20190919T000000Z/20190919T010000Z&details=https%3A%2F%2Fbit.ly%2Famp-dr))
Location: [Video conference via Google Meet](https://bit.ly/amp-dr)

The AMP community holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc or issue by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by mrjoro** [comment]
The Runtime Working Group will be presenting their [periodic update](https://github.com/ampproject/meta/wiki/Working-Group-Updates) at this Design Review (10-15 minutes).

/cc @ampproject/wg-runtime @choumx

**Comment by sparhami** [comment]
If we did not have time for https://github.com/ampproject/amphtml/issues/23990#issuecomment-529587077 in the previous design review, I'd like to talk about it (5-10 minutes).

**Comment by cathyxz** [comment]
@leafsy and I would like to present a new design for [<amp-sidebar>](https://docs.google.com/document/d/1FNduZqgOU8yl3j6_b-VpTvp9cmtbCfNQ25Vm8w-BXQc/edit#).

**Comment by nainar** [comment]
@ampproject/wg-stories @newmuis someone from the Stories WG should be present at this Design Review to make sure that the new sidebar experience is in line with the requirements of the Stories.

**Comment by newmuis** [comment]
I will hopefully be able to attend!  My guess is that many of the details we care about may be fine-grained enough that they should be addressed in code review rather than design review, but will attend just in case and make sure that we communicate our needs.

**Comment by mrjoro** [comment]
@sparhami did we fully address your issue last week?

**Comment by cathyxz** [comment]
@sparhami is out today. The last time we discussed https://github.com/ampproject/amphtml/issues/23990#issuecomment-529587077, we concluded that there was a larger discussion to be had on the deprecation path for `<amp-img>` in favor of regular `<img>` instead. This is a longer conversation that maybe we can revisit in next week's design review.

**Comment by cathyxz** [comment]
# Notes
## amp-sidebar review
### Feature set
- Swipe to dismiss: [demo](https://amp-sidebar-swipe.firebaseapp.com/examples/playground.amp.html)
- Nested menus: [demo](https://amp-sidebar-nested.firebaseapp.com/)
- Animations: [demo](https://amp-sidebar-push.firebaseapp.com/)

### Discussion
@zhouyx: 
- If you open a submenu and close the sidebar, what happens when you open it again? 
- If you close and reopen, it goes back to the main menu and does not maintain state. 
- Why don't we make maintaining state configurable? 

@leafsy: 
- supports browser back button

@dvoytenko: 
- Structure is similar to html5 `<menu>` tag (and ul/li inside of it). 
- To see if we can use its (`<menu>` tag) structure to enforce the DOM structure to use the semantics. 
- Which part of navigation should be currently selected. 
- Suggestion: make sidebar's job simpler and focus on just sliding / presenting content, and maybe shift the nested menu / transition feature into a component that can be a child of sidebar. 
- Curious as we add more functionality to sidebar, how much we're trying to clone, beyond elements and even behavior. 

@zhouyx: 
- It's probably hard to check the visibility of an element if it's cloned. 

@dvoytenko: 
- In theory, you can say the page has navigation, and I decide to sidebar or lightbox it, wondering if we could consider reversing it. 
- A nav shown on a big screen, hidden in small screen, and if we open it in sidebar, we just open a sidebar and point to this nav. 
- We can consider reversing how we currently do it: we take elements and clone it into a sidebar. Maybe we should have them in sidebar and clone it outside. 

@leafsy: 
- Animations: push animation, do we anticipate issues with `amp-story` for new animation customizations. 

@newmuis :
- story makes a lot of assumptions on the Dom structure. Wouldn't be surprised if there were certain styles that `amp-story` can't allow overrides. 
- let's use validation spec to not allow new custom animations in `amp-story` until we verify that they work with `amp-story. 

@dvoytenko : 
- We can't assume that there is one root for all amp pages. 
- What will we do for position fixed elements? They will ignore all transforms. 

@leafsy : 
- For body animations specifically, we'll assume that there is a single root in a `<main>` tag. 

@wassgha : 
- This will also be a problem with video docking

@dvoytenko : 
- Technically if it only uses `transform` and `visibility` it will be okay. Otherwise we may have issues. 
- Definitely don't try to do an animation on the `<body>` tag, iOS will be a mess. 

@newmuis : 
- Let's figure out with UX and publishers to see if customizing animations is something we want for stories. 

### Accessibility
- Ensure that all submenus have a "return to parent menu" button for screenreaders. 

@dvoytenko: 
- What happens on double tap and triple tap? Desktop we have four keys. 
- On a mobile device, you only have two gestures, so it's important to validate that we can navigate through the whole thing via screen reader on a mobile device. 

@wassgha : 
- What if amp-accordion was the component that encapsulated the submenu feature? 

@leafsy : 
- This involves shifting and hiding parent menus, would need the containing div of the parent. 

@nainar : 
- This experience doesn't make sense outside of sidebar. 

### Nested Menu APIs
- Other approaches considered include having a separate component for `amp-submenu`. 
- One option used slots. 
- The issue with shadow dom / slots. 
- A different option used submenu. 

@dvoytenko : 
- If we have a component, we should not nest them. 

@leafsy : 
- If we wanted to separate this component, should we keep the current API, but just put the DOM structure in a new component, which would be a only child of `amp-sidebar`? 

@dvoytenko : 
- Are the "close" / "open" components actually buttons? 

@leafsy : 
- Currently no restrictions, but we could. 

@dvoytenko : 
- We could put this in a separate component that makes assumptions on DOM structure and remove the need for attributes. 
- Connect it to the history API. 

@newmuis: 
- Launch timeline: tentatively end of October
- Original sidebar has a thing where the mask is always made to be a child of the body. Is that still the case? This is a problem for stories because amp-story requires amp-story to be the only only child of body. 
- Basically, swipe to dismiss currently doesn't work very well with `amp-story` because `amp-story` has its own mask and swipe actions on the amp-story mask might not dismiss. 
- How to prevent propagation of touch events to the viewer. 

@leafsy : 
- Right now our swipe to dismiss feature doesn't propagate to viewer. 

@newmuis 
- The nested menu thing, we've had issues with sidebar and history state in the past. We were trying to modify history state but also closing the sidebar. Sidebar is writing to history state because it wants to close itself, but story wants to change history because it's navigating somewhere else. Sometimes this results in a race condition. 
- For history state, we'd like to make sure that further changes that impact history don't regress this race condition. 
- Runtime has a wrapper around history, maybe we can have a task queue? 

@wassgha 
- History might not make sense on mobile, because swiping triggers the browser "back" action. 


Investigate: 
- Menu tag API, what we can use from it for assuming Dom structure. 
- Investigate impact of mask, body animations, and history on `amp-story`. 
- Explore assumptions on dom structure. See if it makes more sense to have a child component of sidebar that directly requires a dom structure and registers actions to it.

**Comment by dvoytenko** [comment]
> @dvoytenko :
> If we have a component, we should not nest them.

After some reflection, I think this is not necessarily true. We could have a nice nesting concept here where a menu could nest into another menu or into an accordion or into a plain div element.
