### ISSUE TITLE
Design Review 2019-09-11 20:00 UTC (wg-performance, reviewer bot selection, email viewer, amp-img source)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#23990]
Time: [2019-09-11 20:00 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2019&month=09&day=11&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20190911T200000Z/20190911T210000Z&details=https%3A%2F%2Fbit.ly%2Famp-dr))
Location: [Video conference via Google Meet](https://bit.ly/amp-dr)

The AMP community holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc or issue by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by mrjoro** [comment]
The Performance Working Group will be presenting their [periodic update](https://github.com/ampproject/meta/wiki/Working-Group-Updates) at this Design Review (10-15 minutes).

/cc @ampproject/wg-performance @kristoferbaxter

**Comment by rcebulko** [comment]
We'll be presenting a new OWNERS-bot reviewer selection algorithm #24338 (15-20 minutes)

/cc @rsimha

**Comment by fstanis** [comment]
I'll be presenting the design for a reference implementation of the AMP email viewer (design doc to be added by Monday).

**Comment by sparhami** [comment]
If there is any time left, I'd like to talk about #24223, giving developers more control over which source to pick from a `srcset`, without affecting the layout dimensions of the `amp-img`.

**Comment by rsimha** [comment]
### Discussion on owners bot, led by @rcebulko.

@mrjoro
An important reason for the existence of the owners bot is so we can open up merge permissions to the reviewers and collaborators teams on ampproject

@rcebulko
- Right now: Owners status is green if PR has full coverage, grey if not. Will be changed to a blocking check
- Right now: PR reviewers are suggested. Will be changed to auto-assign reviewers
- Github status has a link that shows OWNERS.yaml parsing results as a tree and errors if any

Design tenets:
- Don't want to spam high level owners like Malte
- Don't want to add too many reviewers to each PR

Basic design:

- For each file:
    - Take "deepest" owners rules (root owners file has depth of 0, subdir owners files have depth 1, etc.)
    - Find a reviewer in that set who covers most files
    - Add them as a reviewer
- If a PR has many files in separate ownership zones (without common reviewers), the worst case number of reviewers for a PR is the number of zones it touches
- Did analysis of last 1000 PRs. At most 6 or 7 reviewers in the worst case.
- Only 14 out of 2600 PRs needed more than 3 or 4 reviewers
- Showed Beautiful images of analysis in I2I issue :)

Alternative designs considered:
- Add lots of reviewers first, and back off (bad because we'll spam high level reviewers)
- Incrementally add reviewers (bad because we're likely to add too many reviewers)
- Give up if a PR needs too many reviewers (leave it to the author)

Current plan:
- When we roll out reviewer assignment, manually exclude top-level reviewers to save them the spam
- Add support to owners.yaml for a preceding ? or ! in front of owner names
    - ? prefix owners can be suggested, but should not be auto-added as reviewers
    - ! prefix owners must be auto-added as reviewers (or notified about PRs)
- This will come into play for PRs that update files with lots of potential owners (for example, renovate PRs that update package.json) 

@alanorozco
- When the owners check blocks merge, if a reviewer doesn't have ownership privileges to approve an entire PR, we'd still have to add more reviewers, right? (Answer: Yes. However, if we notie this happening often, we can add appropriate reviewers to the owners yaml files.)
- Can we set up glob patterns? Do they apply to existing folders? Or new folders too? (Answer: Yes, we can. Format lets you specify both same dir file globs and arbitrary subdirectories like `**/`)

@honeybadgerdontcare
- We'll need glob support for validator as well, so this is good 

@choumx
- In practice, is it common to not know which reviewer to ask for a review? (Answer: Hard to answer right now, because we haven't enforced the check thus far. We'll know more once the check is enforced.)
- Github already suggests reviewers based on activity. How does that play in to the owners algo? Does it cover most cases? Some cases?
- Piper has a built-in algo called find-owners.

**Comment by rsimha** [comment]
### wg-performance Quarterly Status Update 2019-09

See https://github.com/ampproject/wg-performance/issues/18

**Comment by rsimha** [comment]
### Discussion on AMP email viewer led by @fstanis

Design doc link: https://docs.google.com/document/d/1ULfDlmJDK30ABgA-QWXQvxvjlGCigA13Rl-qxhAFOR8/edit

**Highlights:**
- Viewer is aimed at email clients
- Two parts to the library
    - Documentation and specs
    - Open source implementation
- Also consists of a demo

**General workflow:**
- Input is email
- Check if there's an AMP part to the email
- Check if sender is registered
- Rejected: do nothing
- Accepted: display inside an iframe
- Most email servers already proxy images

**Processing:
CSS workflow:
Rendering emails:
Webkit solution:**
- See design doc for details on all these sections

@choumx
- We've already reviewed this as part of the AMP4email design

@wassimgharbi
- Have we communicated with other email providers? (Answer: Want to get feedback, started doing so (?))

@mrjoro
- What about features that need to be implemented by clients? (Answer: We put placeholders there)

@alanorozco
- Are there any worthwhile alternatives to the domain / iframe logic? (Answer: This is the only approach that seemed to work)

@dvoytenko
- There's a bug (?) (Answer: It's been around for 2 years)

@choumx
- This is a good recipe for new providers. Which providers do we want to pitch this to? (Answer: Microsoft is in dev preview. Yahoo is in an early stage. Maybe we target web testing tools or email playgrounds)

@mrjoro
- What about gmail? Can they do this? (Answer: Probably not, their infrastructure is pretty complex)

**Comment by rsimha** [comment]
### Discussion on `img-sizes` attribute for `amp-img` by @sparhami 

**Original context:** https://github.com/ampproject/amphtml/pull/24223

**Two options to solve problem:**
- `img-sizes` sizes attribute
- `cancel-layout` boolean attribute

@dvoytenko
- Ideally, it makes sense to change `amp-img` to standard behavior, so we can eventually eliminate `amp-img` in favor of `img` (Answer: Can disable auto-sizes generation, and anything else that's non-standard)
- We can then disable `amp-img` at the validator level, and get to the point of replacing it with `img`

@kristoferbaxter
- Why not auto-convert images to `amp-img` and introduce a polyfill for the remaining functionality? (Answer: No good way to enforce the rules (?))
