### ISSUE TITLE
<amp-subcriptions> let `subscriptions-display` cascade to child elements of `subscriptions-dialog`

### ISSUE THREAD

**Issue by ed-bird** [ampproject/amphtml#24067]
## Describe the new feature or change to an existing feature you'd like to see
When a `subscriptions-display` expression is added to a `subscriptions-dialog` element, the decision to show/hide elements should cascade down to child elements of the `subscriptions-dialog`.

**Desired:**
```
<div subscriptions-dialog subscriptions-display="EXPR" >
  <button
    subscriptions-action="subscribe"
    subscriptions-service="local">
      Subscribe!
  </button>
  <button
    subscriptions-action="subscribe"
    subscriptions-service="subscribe.google.com"
    subscriptions-decorate>
      Subscribe with Google
  </button>
</div>
```

## Describe alternatives you've considered

At the moment, the same `subscriptions-display` expression has to be added to every child element.

Example:
```
<div subscriptions-dialog subscriptions-display="EXPR" >
  <button
    subscriptions-action="subscribe"
    subscriptions-service="local"
    subscriptions-display="EXPR">
      Subscribe!
  </button>
  <button
    subscriptions-action="subscribe"
    subscriptions-service="subscribe.google.com"
    subscriptions-decorate
    subscriptions-display="EXPR">
      Subscribe with Google
  </button>
</div>
```

**Comment by jpettitt** [comment]
I think the best way to do this is to set the default visibility for swg elements to that of their closest swg ancestor or false is no swg ancestor.  

This will be a breaking change if for some reason somebody has a swg element without `subscriptions-display` inside one that does have `subscriptions-display` as it will start tracking the parent rather than remaining hidden.

Choices:
1. Do we accept the breaking change on the basis that they shouldn't have been doing that in the first place
1. Do we add `subscriptions-display="inherit"` to explicitly tell swg to inherit from a parent?

cc @dvoytenko @kestrad

**Comment by jpettitt** [comment]
I'm doing some research on usage to see if anybody is using `subscriptions-display` with no value.  If I find there is no usage I'll make the breaking change.

Until then `subscriptions-display="true"` will work and the `<button>` will inherit the display of it's dom parent as expected.

```
  <button
    subscriptions-action="subscribe"
    subscriptions-service="subscribe.google.com"
    subscriptions-decorate
    subscriptions-display="true">
      Subscribe with Google
  </button>
```

**Comment by jpettitt** [comment]
Demoting to P3 since there is a workaround.  Good fixit week issue.
