### ISSUE TITLE
Improve viewability % metrics for AMP ads

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#2407]
AMP pages have consistently lower viewability % metric compared to publisher's lazy loaded ads pages. Provide the publisher an option in amp-ad to prefer higher viewability over higher views.

Reasons why viewability % metric is important -
1. Agencies will only buy from publishers that have high viewability % (~70%).
2. Some publisher-agency contracts expect a minimum of 70% viewable impression delivery, else the publisher has to continue delivering impressions until the 70% viewable metric is achieved at the campaign or page level.

**Comment by rudygalfi** [comment]
With #2425 being merged, can this be closed?

**Comment by whatisjasongoldstein** [comment]
What I'd really like to see is the ability to control the lazy load range.

The way we cleared the viewability hurdle on our site was by AB testing the distance from the screen each ad starts loading, and setting different positions to the value that works best.

There isn't one definitive answer for all placements, in part because there's a tradeoff between viewability and impressions. For example: sometimes we see a position that could have a 5% improvement in viewability by tightening the lazy value (load at 1 screen away instead of 1.5), but doing that would disproportionately reduce the number of impressions, so it's not worth the boost.

Does that make sense?

On our own ads, we control this by setting a `lazy=` attribute on the ad element. Something similar would be a huge help.

Thanks.

**Comment by jasti** [comment]
@dvoytenko - I just tested this feature by loading two pages with 2 slots each (one at the top and one below 1.25 viewports below). The left page uses the default viewability strategy and the right page uses the 'prefer viewability' strategy. The problem is I see that all 4 ad slots are still being loaded as soon as the initial page loads. With the 'prefer viewability' flag on amp-ad, I would expect the bottom right ad slot to load only when the user scrolls down to within 1.25 viewports. (basically lazy load).
Here is the test page : http://dfp-amp-testing-1185.appspot.com/amp_tests/viewability/viewability_test.html

I believe #2425 - which this issue's implementation will hit GA tomorrow. 

CC @kashyapnitin

**Comment by jasti** [comment]
actually, please wait one sec before debugging. I'm checking if I'm in the experiment.

**Comment by jasti** [comment]
Please ignore. WAI. I was not on dev experiments.

**Comment by erwinmombay** [comment]
@jasti thanks for rechecking!
