### ISSUE TITLE
amp-sidebar: [aria-hidden] removed on open

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#24120]
This appears to be a recent-ish regression. On open, `[aria-hidden]` is set to "false" but the attribute is quickly removed afterwards.

Looks like this is due to `setModalAsOpen()`, which is invoked async after `setAttribute('aria-hidden', 'false')` is called: https://github.com/ampproject/amphtml/blob/98bdfca3602731473248126b6903801fa54d9569/extensions/amp-sidebar/0.1/amp-sidebar.js#L331-L347

Poking into `setModalAsOpen()`, I wonder if the issue is that the return value of `getAncestors(el)` includes `el` itself. That may not be expected.

First reported in `b/139279314`.

/to @sparhami

**Comment by sparhami** [comment]
I'll clean this up, but adding a note that this isn't actually a bug. When the sidebar is open, it is fine to not have `aria-hidden` (behaves the same as `aria-hidden="false"`, except on things like `<script>` tags). When the sidebar is closed, it is fine to have `aria-hidden="false"`, since the element is `display: none`.

**Comment by choumx** [comment]
Makes sense, thanks.

**Comment by choumx** [comment]
Reread the original bug and an additional issue is that `[aria-hidden=false]` is present after closing the sidebar. Possibly related to the same root cause?

**Comment by sparhami** [comment]
I think the reason for that the modal closing logic tries to restore the previous value of `aria-hidden`, which it thinks is `false` rather than not present due to the async behavior you mentioned above. With #24123, we won't set `aria-hidden` on the sidebar element at any point, instead relying on the `display: none;`, which will remove the content from the accessibility tree. The `aria-hidden="false"` is not an issue as the `display: none` is picked up by screen readers.
