### ISSUE TITLE
AliExpress: Toggle slider displays white square

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#24175]
## What's the issue?
Toggle slider displays white square

Briefly describe the bug.
White square is displayed on toggle button.

## How do we reproduce the issue?
1. Opt into Canary/RC
2. Open JavaScript Console
3. Go to [link](https://m.aliexpress.com/wholesale/door%20lock.html?channel=direct&gclid=null)

## What browsers are affected?
macOSX Chrome Version: 76.0.3809.100

## Which AMP version is affected?

Canary/RC: 1908212120530

![Screen Shot 2019-08-23 at 9 39 05 AM](https://user-images.githubusercontent.com/48487406/63612286-c440f800-c592-11e9-947b-f8958bfd2ff2.png)

**Comment by sparhami** [comment]
One weird thing about this is that the white square is not present on the initial page load, but seems to occur sometime after (perhaps when the list content loads). This is suspicious since there shouldn't be a way for that change to happen without a user action.

One possibility is that the toggle is actually after the list in the DOM, and relies on the list loading state for some CSS. Some more investigation is needed here.

Just as a note, I was not able to reproduce this on my machine, so there could be some experiment that causes this behavior.

**Comment by wassgha** [comment]
Same as @sparhami , could not reproduce on Chrome for OS X, could you please confirm that this is still broken on the latest canary/rc?
