### ISSUE TITLE
Load higher resolution image on amp-pan-zoom

### ISSUE THREAD

**Issue by VMBindraban** [ampproject/amphtml#24259]
## Describe the new feature or change to an existing feature you'd like to see

Currently the `amp-pan-zoom` scales the given child.
If a normal image is used it becomes pixelated.

Is it an idea to add an optional attribute to `amp-pan-zoom` so it loads a higher resolution image instead?

**Comment by cathyxz** [comment]
We have a large refactor backlog on amp-pan-zoom. We were originally planning to fix it to work with the internal amp-image-viewer component, but haven't really prioritised this due to the extremely low usage of `<amp-pan-zoom>` as a component. 

Generally people who need zoom operations for images have just used `<amp-lightbox-gallery>`. Most of the usages of `<amp-pan-zoom>` we've seen so far are for PDFs and SVGs. Curious what your use case is, and if `amp-lightbox-gallery` works for it. 

Ideally the way this would work is you would just give your amp-img a `srcset` and `<amp-pan-zoom>` would automatically upgrade to a higher resolution src when necessary. This is how `amp-image-viewer` (an internal component to `<amp-lightbox-gallery>`) works.

**Comment by VMBindraban** [comment]
I am currently using list of resolutions for `amp-img` with `srcset` (between 1440w and 480w) but it doesn't seem to use the higher resolution when using `amp-pan-zoom`.

For now it's scaling 2 times which makes it less.. horrible.

My client is using 1 site for mobile, desktop and AMP. (which has his own challenges to begin with)
Within `amp-carousel` and by using `amp-pan-zoom` when you click on an image it zooms in.

**Comment by cathyxz** [comment]
I see. Just to clarify, the `srcset` approach is not how it currently works (it's a missing feature request), it's how I would propose implementing it, and is how `amp-lightbox-gallery` currently works. 

Due to low usage, I don't think we're going to get to this anytime soon, but you are more than welcome to contribute a fix if interested.
