### ISSUE TITLE
<amp-script> must not be empty

### ISSUE THREAD

**Issue by fstanis** [ampproject/amphtml#24265]
## What's the issue?

If `<amp-script>` is empty (doesn't contain any initial content), then no attempt is made to load it and no error is throws.

## How do we reproduce the issue?

```html
<amp-script layout="container" src="/anything.js"></amp-script>
```

This should either:

*   Make an attempt to fetch `/anything.js`
*   Result in runtime error
*   Result in validator error

## Which AMP version is affected?

1908222134250

**Comment by nainar** [comment]
This is a developer affordance we should definitely have to set them on the correct path. Marking it as a P1 as such.

**Comment by choumx** [comment]
I think this is actually due to the `amp-script` element having a width/height of zero. Such elements are ignored by the resource scheduling system -- `layoutCallback()` won't be called which initializes the element.

Is there a use case you have in mind for a child-less `amp-script`? E.g. I can imagine using `amp-script` as a data layer (using AMP.setState in the JS), though you could just add `width=1 height=1` as a workaround.

**Comment by samouri** [comment]
> I think this is actually due to the amp-script element having a width/height of zero. Such elements are ignored by the resource scheduling system -- layoutCallback() won't be called which initializes the element.

I've actually run into this as well and was confused. I was attempting to populate the `<amp-script>` element completely by the script's js as without having initial contents.

Forcing a nonzero width is fine, but I'd at least expect a dev warning.

**Comment by choumx** [comment]
We could do that by overriding `onLayoutMeasure()` or `onMeasureChanged()` in amp-script.js and warning if the layout box has a zero size and hasn't been laid out.
