### ISSUE TITLE
amp-twitter in amp-story cut tweet's height

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#24298]
It looks like when embedding several `amp-twitter` components within an `amp-story`, the size of the first `amp-twitter` component is set to all the following ones, cutting their content.

To repro:

https://new-on-the-web.glitch.me/

Here, the first `amp-twitter` has a height of 440px, and all the following `amp-twitter` are cut at 440px.

![image](https://user-images.githubusercontent.com/1492044/63976432-522f4e00-ca7f-11e9-87e2-d45c0ddc2dba.png)
![image](https://user-images.githubusercontent.com/1492044/63976475-6e32ef80-ca7f-11e9-8773-523960cdb981.png)

**Comment by Enriqe** [comment]
I played around with this and I'd like to share some context and options. The problem is that the tweets are changing size even after we think they have done resizing. Causing our code to set an incorrect height that is shorter than the actual height.

For more context, we have a function `debounceEmbedResize()` that listens to the resize events coming from the `amp-twitter` element. Once `RESIZE_TIMEOUT_MS` pass between resize events, it calls `prepareForAnimation()`. This function is used for expanding the tweet's size + applying a scale to make it look like its original size. All of this is done in order to create the "expanded/lightbox mode" animation. 

Since `amp-twitter` is also listening for resize events coming from the iframe, and then changing the element size each time, we have to stop listening to these resize events on the `debounceEmbedResize()` side, otherwise `amp-twitter` will keep resizing the element, and `prepareForAnimation()` will do too, causing an infinite loop.

To solve this, we call `unlisten()` once `prepareForAnimation()` is actually called after `RESIZE_TIMEOUT_MS` pass between resize events. And this is where if a tweet gets resized, we won't handle this event anymore since we already called `unlisten()`.

If the tweet ends up being taller than what it said it was going to be by the time we call `prepareForAnimation()` it will be cut off, since we were using incorrect measurements when preparing it for the animation.

Some options: 
#### A. Increase debounce timeout
If we wait longer on the debounce we could make this issue happen less often, since it's more likely that the tweet will be completely loaded before calling `prepareForAnimation()`. But it's not ideal since the issue could still happen in slow network speeds.

#### B. Use scale in order to expand tweet
If we only change the `scale` instead of the `width/height` of the tweet after `prepareForAnimation()`, we will avoid that infinite loop between `amp-twitter` and `prepareForAnimation` since we aren't actually changing the element's size. The disadvantage here is that the tweet will look blurry when expanding it in the light-box view.

#### C. Don't change the size, only position tweet in the middle
Get rid of the "expand" animation, and just position the tweet in the middle of the screen with the black background behind it. 

My votes go for `C` and then `B`, WDYT?

**Comment by gmajoulet** [comment]
Thanks for investigating!

It is impossible to predict the height of a tweet, but as we allow other embeds with fixed size we will be able to re-use the resizing/scale logic.
 
B is blurry :(
C sounds good to me.

@hongwei1990 what do you think?
