### ISSUE TITLE
New Loaders: spinner circle initially renders larger and misaligned for a split second

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#24393]
![Screenshot_20190906-074522](https://user-images.githubusercontent.com/2099009/64437150-9d96bd00-d07a-11e9-88aa-ed1277faa220.png)

**Comment by alanorozco** [comment]
![ono](https://user-images.githubusercontent.com/254946/64650811-e4ffaf00-d3d4-11e9-964e-ba2fdb247ade.png)

**Comment by sparhami** [comment]
Some different configurations I have tested:

Have Bug:

Chrome 76, Mac
Chrome 77, Mac
Chrome 77, Linux
Chrome 77, Android

Work fine:

Firefox
Safari
Chrome 76, Linux
Chrome 76, Android

This is very likely a layout bug in Chrome's [new rendering engine launching in Chrome 77](https://www.chromium.org/blink/layoutng). Since their launch is soon, we may need to figure a way around it for now.

**Comment by nainar** [comment]
Tested disabling LayoutNG in Chrome and it works to corroborate the hypothesis above.

**Comment by cramforce** [comment]
CC @chrishtr 
Did we file a crbug.com yet?

**Comment by sparhami** [comment]
> Did we file a crbug.com yet?

Yes, it is https://bugs.chromium.org/p/chromium/issues/detail?id=1002748
