### ISSUE TITLE
:target css selector not working

### ISSUE THREAD

**Issue by Nemo64** [ampproject/amphtml#2440]
I noticed that the `:target` css selector is not working on [amp-page](http://jsbin.com/gizususetu/1/edit?html,output). 
I honestly don't know why since the url is updated correctly like [on a none-amp page](http://jsbin.com/beluzehahi/edit?html,output).

It can be used for some css tricks like described in https://github.com/ampproject/amphtml/issues/827

**Comment by dvoytenko** [comment]
I'm not entirely sure why the `:target` selector is not working - from what I understand it should work, but most probably it's because with `preventDefault` on the click event. This, in turn, is necessary because iframe navigation breaks the parent page's history state, hence we were forced to implement it ourselves directly.

**Comment by Nemo64** [comment]
Possible. Accessing the page with `#headline` already in the url does work fine.

**Comment by dvoytenko** [comment]
The fix has been merged. It should be in canary tomorrow (Thur).
