### ISSUE TITLE
amp4ads-host-v0.js should not write AMP_CONFIG 

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#24449]
This might cause issues when inabox ads are served to dirty AMP. because inabox & AMP release can be out of sync, both v0.js and amp4ads-host-v0.js will race for writing the global AMP_CONFIG and causing mixed versions loaded on the page.

`amp4ads-host-v0.js` should be treated as an extension that should not write AMP_CONFIG.

**Comment by lannka** [comment]
@rsimha is this not the right list to look at?
https://github.com/ampproject/amphtml/blob/971a10c1530fbb62997f7d41fc90190d95c115ac/build-system/tasks/helpers.js#L81-L90

**Comment by lannka** [comment]
or is it out of sync with our release script?

**Comment by rsimha** [comment]
That is the correct list for local development. We use a completely different piece of code during releases because the release infrastructure makes multiple copies of the rtv directory before inserting different versions of `AMP_CONFIG` into each of them. 

The lists could very well be out of sync. If the problem you're seeing is only during local development, feel free to delete the minified and unminified targets that shouldn't have a config from these two lists:

https://github.com/ampproject/amphtml/blob/b11fe0ea5b5bcbae124df0f43ac8b74f0c6ad531/build-system/tasks/helpers.js#L69-L79

https://github.com/ampproject/amphtml/blob/b11fe0ea5b5bcbae124df0f43ac8b74f0c6ad531/build-system/tasks/helpers.js#L81-L90

**Comment by lannka** [comment]
yes, the problem is in release scripts. tracked here: b/140877200
will let you decide how we can keep the 2 in sync.

**Comment by lannka** [comment]
Done.
