### ISSUE TITLE
Blocking 3rd party cookies breaks www.google.com/amp/s/ but works on cdn.ampproject.org/c/s

### ISSUE THREAD

**Issue by archon810** [ampproject/amphtml#24499]
Hi all, I don't understand why 3rd-party cookie blocking
![image](https://user-images.githubusercontent.com/469543/64817009-b4974c80-d55d-11e9-820b-e1d443231ca7.png)

affects

https://www.google.com/amp/s/www.androidpolice.com/2019/09/10/opinion-the-apple-watch-series-5-embarrasses-wear-os-yet-again-its-time-for-changes/%3famp

but doesn't affect

https://www-androidpolice-com.cdn.ampproject.org/c/s/www.androidpolice.com/2019/09/10/opinion-the-apple-watch-series-5-embarrasses-wear-os-yet-again-its-time-for-changes/?amp

If you block 3rd party cookies, the ampproject link loads fine, but google.com/amp fails to load everything (and eventually triggers our custom overlay to alert the user stuff's broken):

![image](https://user-images.githubusercontent.com/469543/64816963-9d585f00-d55d-11e9-804a-6d827fe7033d.png)

Behind the banner, the page looks like this:

![image](https://user-images.githubusercontent.com/469543/64816967-9fbab900-d55d-11e9-9b4d-5980c7c26bf6.png)

Why can't google.com/amp use the same tech as ampproject.org? Or is there a way to fix it for us by changing some settings?

Thank you.

**Comment by cramforce** [comment]
CC @lannka For potential inabox impact.

Reopening until fix has landed in prod.

**Comment by archon810** [comment]
Thanks for what seems to be a fix in the works, but can someone knowledgeable please explain the issue and the fix?

Thank you.

**Comment by cramforce** [comment]
It was a relatively complex chain of circumstances:

- an experiment was added to switch to a new custom element polyfill
- it being a polyfill the check whether to use the new or old has to happen
very early in program init
- the experiment code reads from localStorage to see if the experiment is on
- this read fails in 3p context if 3p cookies are disabled
- the failure is caught and an error is logged. The program is supposed to
continue as normal
- unfortunately, the logging system hadn't been initialized yet because
this read happens to early that init depends on code order that the
compiler determined
- fail

There are some obvious systemic failures that enabled this chain of
circumstances to happen and get through testing. Details will be discussed
in a postmortem.

**Comment by cramforce** [comment]
Thanks for the original report. It should now be fixed in production.

**Comment by archon810** [comment]
Awesome, thank you. Please post the post-mortem if you're able to once it happens.
