### ISSUE TITLE
I2I: amp-story-player

### ISSUE THREAD

**Issue by rrjanbiah** [ampproject/amphtml#24539]
## Describe the new feature or change to an existing feature you'd like to see

Currently `amp-story` is standalone and can't use it in place of carousel or so.

**Comment by newmuis** [comment]
I'm working on an iframe-based way of embedding stories into other documents, starting with https://github.com/ampproject/amphtml/pull/23980.  I'm writing up a more fleshed-out proposal in a Google Doc, but can migrate that over to GitHub soon!

**Comment by newmuis** [comment]
## Background

For quite some time, we've been ideating about rich embedding experiences for STAMPs on third-party pages.  This document tries to scope smaller projects that can be composed into the larger initiative outlined at go/stamp-kit.


## Goals



*   Distributing our own embeds means we can ensure quality of embedded experience
*   Get embed JS out in the wild early on
*   Improve upon embedded experience over time (a la AMP as a Service)


## Non-Goals



*   Embedding within native applications
*   Altering the UI of the publisher page (i.e. showing the story in a lightbox, etc)


## Features



*   Prerendering
*   Prefetching and caching resources on O&O
*   Customizable embed UI / chrome
*   Swipe/tap to next/previous on O&O


## High-level API Design

There are three primary high-level goals of the API:



1.  Allow the AMP and non-AMP implementations to have the same API
1.  The AMP API should be idiomatic AMP
1.  The stories themselves should be represented in a way that search engines would consider a link between the embedding document and the embedded document (story)
1.  If the JavaScript fails to load, the experience should degrade gracefully

As such, we have settled on this API:


```html
<amp-story-embed>
  <a href="https://www.example.com/story1.html"></a>
  <a href="https://www.example.com/story2.html"></a>
  <a href="https://www.example.com/story3.html"></a>
  <a href="https://www.example.com/story4.html"></a>
</amp-story-embed>
```


This feels like idiomatic AMP, can be used in both the AMP and non-AMP version, and with each <a> representing a story, would allow search engines to crawl embedded stories.  The <a> tag will also continue to work, even if the JavaScript does not upgrade the <a> to an embed.

Since each <a> represents a story, we can include story-level metadata on the tag, as follows:


```html
<a href="https://www.example.com/story1.html"
    data-poster-portrait-src="https://example.com/story1-portrait.png"
    data-poster-landscape-src="https://example.com/story1-landscape.png"
    data-poster-square-src="https://example.com/story1-square.png"
    data-publisher-logo-src="https://example.com/logo.png"
    data-title="My Awesome Story"
    data-publisher="The AMP Team">
</a>
```



## Milestones


### ~~Milestone 0: Documentation Only~~

~~For publishers interested in simply embedding a STAMP in another page with no rich features, they can simply create an iframe with the STAMP URL as its src.  We should document that this is the case.~~

~~For those looking to build richer features such as the swipe/tap to next story, but unwilling to wait until we deliver an official API for it, they can use the [open source viewer](https://github.com/ampproject/amp-viewer/tree/master/mobile-web) for now, with the documentation [here](https://github.com/ampproject/amphtml/blob/viewer-doc-api-link/extensions/amp-viewer-integration/amp-doc-viewer-api.md) and any additional STAMP functionality through either URL params or feature requests.~~


### Milestone 1: "Simple" iframe embed

Write some simple JS to create a sandboxed iframe and propagate the story's src from the embed API to the iframe.  That iframe should be wrapped in a shadow root, to prevent publisher styles from targeting any DOM output by this script (primarily as a means of future-proofing the script to allow it to output arbitrary UI elements outside of the iframe context).

As an optimization, we should load the cache URL for the story (we can hardcode cdn.ampproject.org at first, and allow publishers to configure their AMP cache of choice if the need arises).

Get this JS compiled and served from from cdn.ampproject.org.  As a precedent, we can look to [video-iframe-integration.js](https://github.com/ampproject/amphtml/blob/master/src/video-iframe-integration.js), which is also a JavaScript API that is served from cdn.ampproject.org, but not "part of AMP" (instead, rather, communicates with AMP over a postMessage-based API).


#### Usage


```html
<script async src="https://cdn.ampproject.org/amp-story-embed-v0.js">
<!-- ... -->
<amp-story-embed>
  <a href="https://www.example.com/story1.html"></a>
</amp-story-embed>
```



### Milestone 2: Add embed modes

Add a parameter that publishers can specify in the DOM/JSON configuration that can be passed through to the embedMode fragment parameter, to allow specifying embed modes.


#### Usage


```html
<script async src="https://cdn.ampproject.org/amp-story-embed-v0.js">
<!-- ... -->
<amp-story-embed embed-mode="no-sharing">
  <a href="https://www.example.com/story1.html"></a>
</amp-story-embed>
```



### Milestone 3: Switch from plain iframe to open source viewer implementation

The [open source viewer implementation](https://github.com/ampproject/amp-viewer/tree/master/mobile-web) handles the messaging API between the viewer and the runtime, including the initial handshake, as well as sending messages.  Using this JS API with the iframe implemented in Milestone 1 above will create a minimal AMP viewer.


#### Usage

From a user's perspective, this should be a no-op from Milestone 2.


### Milestone 4: Ensure the document is a valid STAMP

By virtue of the fact that it is loaded from the cache, we can be sure that the document is valid AMP.  We should also ensure it is valid STAMP (not just a valid AMP), by either:



*   Have amp-story send an "I am STAMP" message to the viewer
*   Parse the DOM and look for `<amp-story standalone>` (which, when combined with the fact that the document is valid AMP, should be sufficient to indicate it is a valid STAMP)
    *   This is tricky, since we potentially want to make the iframe 3p


#### Usage

From a user's perspective, this should be a no-op from Milestone 2 and Milestone 3, as long as the document was a valid STAMP.


### Milestone 5: Allow prerendering

The open source viewer implementation should already support prerendering, with the `visibilityState=prerender` fragment parameter, as well as the `visibilitychange` request.  The bigger question here will be how to best expose prerendering as an API to publishers (i.e. how do we know what to prerender?  how do we keep from prerendering too little?  too much?)


#### Usage

TBD.  This milestone would have to expose some type of hook for publishers to indicate that a given URL should be prerendered.


### Milestone 6: Allow tapping/swiping to next/previous story

Once prerendering is allowed, we should allow tapping/swiping to the next/previous story.

Both require setting up multiple viewer iframes and prerendering the next story.  Swipe events should be handled manually and animate to the next story's iframe, positioned after the current iframe, along the x-axis.  To enable tapping to the next story, the viewer should handle the selectDocument request, and inspect its payload to determine whether it should move the previous or next story's iframe into focus.


#### Usage


```html
<script async src="https://cdn.ampproject.org/amp-story-embed-v0.js">
<!-- ... -->
<amp-story-embed embed-mode="no-sharing">
  <a href="https://www.example.com/story1.html"></a>
  <a href="https://www.example.com/story2.html"></a>
  <a href="https://www.example.com/story3.html"></a>
</amp-story-embed>
```

**Comment by rrjanbiah** [comment]
Bump! @newmuis Any idea when this will be available for all?

**Comment by newmuis** [comment]
@Enriqe has been working on this and has a prototype that we're looking to productionize.  I would expect at least some of the milestones above to be launched in the first quarter of 2020.

**Comment by gmajoulet** [comment]
Tracked in https://github.com/ampproject/amphtml/issues/26308
