### ISSUE TITLE
Design Review 2019-10-02 20:00 UTC (amp-mega-menu)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#24588]
Time: [2019-10-02 20:00 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2019&month=10&day=02&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20191002T200000Z/20191002T210000Z&details=https%3A%2F%2Fbit.ly%2Famp-dr))
Location: [Video conference via Google Meet](https://bit.ly/amp-dr)

The AMP community holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc or issue by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by mrjoro** [comment]
The UI & Accessibility Working Group will be presenting their [periodic updates](https://github.com/ampproject/meta/wiki/Working-Group-Updates) at this Design Review (10-15 minutes).

/cc @ampproject/wg-ui-and-a11y @nainar

**Comment by nainar** [comment]
@Gregable are you still open to swap the @ampproject/wg-caching's update and provide it at this time slot?

**Comment by Gregable** [comment]
I just saw this. I'd prefer to delay to another week if that's possible.

**Comment by mrjoro** [comment]
We can do both of these at the next design review (October 16).

**Comment by nainar** [comment]
Works for me! Thank you!

**Comment by mrjoro** [comment]
We are cancelling this week's design review since there are no topics.

**Comment by leafsy** [comment]
Sorry for the late notice; I'd like to discuss the design for a new `<amp-mega-menu>` component.

**Comment by cathyxz** [comment]
Steven introduces design doc and demo (both linked above: 
@alanorozco : Can it nest up to a third level or more or is it just two levels? 
Whether you can open a second menu from the first menu? Are we considering such a use case? 

@cramforce : Is there any reason why you couldn’t just compose a toggle section component into the mega menu? E.g. you can put an accordion in your mega-menu item. 

@alanorozco : is the action on click settled or would we also have an open on hover? 

@sparhami : we have to support open on click for screen readers, so adding hover on top of click would lead to the two undesirable scenarios for accessibility referenced in the design doc. 

@kristoferbaxter : our current design does not preclude hover, and in the future we could potentially revisit this. 

@alanorozco : does wrapping everything in a nav have any semantic advantages, or is it just a convention kind of thing? 

@leafsy : it communicates that this is a top level navigation for the webpage. It also helps to identify which items should be identified as mega-menu items. An alternative approach would be to attributes to identify them. 

@alanorozco : Why can’t we use the mega-menu itself to indicate this? It seems weird that we need to have an intermediate container? 

@dvoytenko : maybe it should be amp-mega-nav. 

@cramforce : we definitely should have the nav. Two options: either we require it or we put it as runtime. A11y is also helpful for indexing to be explicit. 

@kristoferbaxter : semantic html question: is there any reason why these ordered items are unordered? Since practically speaking, they are ordered. 

@sparhami : ordered list indicates sequencing, but here the ordering does not mattering other than presentation. 

@leafsy : right now we could have an ordered list and it would still work well, using a ol is not precluded. 

@dvoytenko : how do we mask? 

@leafsy : Right now we recommend that the <amp-mega-menu> is put in the header, and the mask is attached to the header. The main consideration is that we want the mask to cover everything below the menu, but not anything above it. 

@dvoytenko : are we also going to support html dialog? 

@sparhami : there are some styling considerations and we would have to remove their mask. We currently have to implement the modality ourselves with keyboard because safari doesn’t support dialog and it is unlikely that they ever will. AFA a11y is concerned, the role dialog suffices for this. You have to stay within the dialog until you close it. 

@dvoytenko : the buttons in this case, 

@sparhami : Buttons with aria-has-popup and aria-expanded=true. 

@dvoytenko : if I wanted to style the button of the opened menu, how would I target it? 

@sparhami : aria-expanded. 

@leafsy : an invisible close button is also appended for screen readers. 

@dvoytenko : how does focus trapping work? 

@sparhami : it should behave like a modal, and it will allow you to navigate focus to the browser. 

@dvoytenko : what if one of these buttons is not actually a submenu and is a button or a heading with an action? 

@sparhami : we disregard all tap actions on accordion headers. 

@kristoferbaxter : this is a valid feature request to have headings in the mega-menu that have a different tap action that does not trigger a submenu open. 

@alanorozco : or we could just ignore buttons that have on actions. In this case don’t register any actions from the mega-menu. 

@dvoytenko : how do we turn this into a sidebar when we don’t have space? 

@leafsy : we currently just use a media query. We have two different amp-lists that are sourced from the same endpoint, and the data is reused because we have batch fetching. 

@sparhami : we did look at ways to combining these two elements, however in the real world, this was not practical because mega menus and sidebars for the same page representing the same categories looked too different in practice. 

@alanorozco : what are the allowed layouts? 

@leafsy : fixed height. 

@kristoferbaxter : what happens if a resize event occurs to hide the menu and show the sidebar while the menu is still open? Let’s descope this functionality for now. 

@sparhami : the one use case I can see for this is on tablet, where rotating the tablet would expose both APIs (sidebar and mega menu), but tablet usage is relatively small and this does not happen as result of normal use case in mobile and desktop. 

@alanorozco : what happens with horizontal overflow? 

@leafsy : great question. We currently do a cut off. 

@alanorozco : authors can be unexpectedly hit by this due to i18n. 

@sparhami : what happens when JS is disabled? For sidebar, we just put hidden attribute so if JS doesn’t load, nothing displays. 

@kristoferbaxter : since hidden is display none, would this strategy result in a content shift? 

@alanorozco : would hiding the submenus result in a content shift? It’s probably a better idea to hide them via CSS by default. 

@kristoferbaxter : do we support multiple breakpoints here? 

@leafsy : if multiple mega menus, how do we deal with the mask? 

@sparhami : Remove mask on unlayout. Or we reuse the same mask to ensure that multiple mega menus only have one mask. 

@alanorozco : should we guarantee that each header only has one mega menu? E.g. via validation. 

@kristoferbaxter : do we want to enforce that there’s a consistent set of options between different breakpoints? 

@sparhami : in the wild, this has not been the case. 

@alanorozco : can you put a flying carpet in a mega menu? What happens if the mega menu header is position fixed or position sticky? 

@kristoferbaxter : let’s add a test for position sticky. Right now we have h1s inside the header. Do we want to explicitly prohibit headings from being in the menu, since h1s should be for actual content? 

@sparhami : we should talk to a11y folks about this. 

@alanorozco : ensure with validation that at least 1 role dialog exists. We should add a css class to ensure the z-index styling, in order to avoid using the header tag as a CSS selector.
