### ISSUE TITLE
AliExpress back button is not functional

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#24696]
## What's the issue?
AliExpress back button is not functional.

Briefly describe the bug.
When clicking on the back button it does not revert back to the previous page.

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Opt-in to Canary/RC
2. Go to [link](https://m.aliexpress.com/wholesale/car%20sleep.html?channel=direct)
3. Open Java Console
4. Select an item
5. In new tab Open Java Console
6. Click on the back button

## What browsers are affected?
Chrome Version: 77.0.3865.90
FireFox: 69.0.1

## Which AMP version is affected?
Canary/RC: 1909181902540
Prod: 1909141409590

**Comment by sparhami** [comment]
Some other things I noticed:

- If you do not open devtools, the back button seems to work correctly for me for Chrome desktop.
- On Safari (and iOS), this does not seem to close the tab as it should (when not a viewer environment)
  * This is due to checking `window.opener` exists before allowing the close. The page does not have an `opener`. This looks to be due to a Safari intervention, treating `target="_blank"` as `target="_blank" rel="noopener"`. The bug specifies that you can opt into using opener using `rel="opener"`. See https://bugs.webkit.org/show_bug.cgi?id=190481
  * It is unclear why we need to check for an opener before allowing the close. The check is here: https://github.com/ampproject/amphtml/blob/1c1e722ad99fc5352e5519b28cdb0db99854e2fd/src/service/standard-actions-impl.js#L242-L247 The comment and the PR, #19962, are explicit about wanting an opener though the context on why is missing.

**Comment by sparhami** [comment]
Another thing I noticed is that if you:

1. Open https://m.aliexpress.com/wholesale/car%20sleep.html?channel=direct in Chrome
1. Open the tab
1. Open dev tools
1. Click the button
1. Try to close dev tools

I noticed that dev tools will not close, both when trying close via the "x" button or via the dev tools keyboard shortcut.

**Comment by sparhami** [comment]
So it looks like there are two separate issues here:

1. the `window.close()` call has strange behavior while the Chrome devtools are open (does not close the tab, but remove all event listeners, perhaps unload all the JS). This seems to be a Chrome devtools bug (filed https://bugs.chromium.org/p/chromium/issues/detail?id=1007407 for the issue).
1. We do not necessarily need to check `window.opener`, and it is `null` in Safari for the above steps since the anchor tag uses `target="_blank"`, which they make imply `rel="noopener"`.

For the second issue, we can change our logic slightly and remove the check for `window.opener`. I am not sure exactly on why `opener` was checked for explicitly, but reading the spec on when you can call `window.close`. From [the spec](https://html.spec.whatwg.org/multipage/window-object.html#script-closable) (though browsers may differ in implementation), it seems like either the window needs to have been opened using `window.open` or it is a top-level browsing context with a single history entry (`window.history.length == 1`).

From some testing on Chrome, I have found that:

If you start on the original page, https://m.aliexpress.com/wholesale/car%20sleep.html?channel=direct, and

a. Click on the first result, call `window.close()` in the new page, then the tab closes.
b. Click on the first result, click on a related result, then call `window.close()`, the call is ignored.
c. Click on the first result, click on a related result, then navigate back (either via browser or UI button), then call `window.close()`, the call is ignored.
  * This is because `window.history.length == 2`.

So the correct logic seems to be to ignore `window.opener` and instead check if `window.history.length > 1` to determine if we can close.

**Comment by sparhami** [comment]
One last complication is that we cannot just check `window.history.length`. If you do the following sequence:

1. Open a tab (e.g. via an anchor tag)
2. Call `history.pushState('blah');`
3. Call `history.back()`

You can call `window.close()`. However, if you do:

1. Open a tab (e.g. via an anchor tag)
2. Open another tab (via an anchor tag)
3. Go back

You cannot call `window.close()`. Note that after step two, you cannot call `window.close()` regardless.

I think the best thing to do might be to just call `window.close()` and let that fail, since we already check `window.closed`.

**Comment by diantekyrie** [comment]
This issue is reappearing on AliExpress [link](https://m.aliexpress.com/item/4000142680772.html?pid=808_0000_0101&spm=a2g0n.search-amp.list.4000142680772&aff_trace_key=&aff_platform=msite&m_page_id=5193amp-s8mh9s4A0FMyTVITQo8ciA1574280461072)

AMP Version: 1911191835190
