### ISSUE TITLE
AMP-List doesn't render in Firefox or Safari

### ISSUE THREAD

**Issue by SimonHogstromRonbol** [ampproject/amphtml#24704]
## What's the issue?

I have this amp-list that works perfectly fine in Edge and Chrome, but throws and "Unknown error" in Firefox and Safari, and doesn't render

## How do we reproduce the issue?

i have made a codepen of the amp-list in question:
https://codepen.io/sunturion/pen/bGbzxwj

you can see an even more minimal version of the amp-list where the error is still present.
https://codepen.io/sunturion/pen/pozGQaV

you will see that when you open these pens in chrome and edge, there is no problem, and the amp-list is rendered as it is supposed to, but if you open the same pen in safari or firefox, you wont get the list rendered.

## What browsers are affected?

I've tested it in Chrome, Edge, Internet Explorer, Firefox and Safari and it doesn't work in the last three, Internet explorer, Firefox and Safari.

## Which AMP version is affected?

i've only tested this in 1909141409590

**Comment by sparhami** [comment]
This appears to be because one of the list items is trying to set `"http://byaagaard.com, http://k-z.dk"` as an `href` in the template. This throws an error in the sanitizer as it is not a valid URL, which prevents the list from rendering properly.

This validation / sanitization of a valid `href` is done using the [`URL` constructor](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL), which is functionality provided by the browser. If I had to guess, Firefox and Safari are actually doing the right thing here and rejecting the URL.

Is your intent to have a comma and space separated list as an `href`?

Perhaps there is some better error handling/messaging we can do here.

/cc @choumx

**Comment by SimonHogstromRonbol** [comment]
@sparhami good catch, however, i corrected the error in the data, and i still cant get the list to render on firefox and safari, i've updatede the data in the pens in my initial comment.

**Comment by choumx** [comment]
Something strange is happening in the codepen sample where extension `<script>` elements are being reparented to the document body. Your updated sample works when testing locally outside of codepen (I see the `<amp-selector>` element being rendered).

**Comment by SimonHogstromRonbol** [comment]
@choumx i have a real word example where the bug is present on Firefox and Safari if that helps: https://www.capidea.dk/virksomheder

**Comment by sparhami** [comment]
> @sparhami good catch, however, i corrected the error in the data, and i still cant get the list to render on firefox and safari, i've updatede the data in the pens in my initial comment.

I still see some data containing `"http://byaagaard.com, http://k-z.dk"`. I think there might have been multiple locations originally, but I still see one location with `"hjemmeside": "http://byaagaard.com, http://k-z.dk",` in the data returned from the server.

**Comment by SimonHogstromRonbol** [comment]
I've implemented a workaround on the live site (https://www.capidea.dk/virksomheder), by removing the protocols from the url, and then doing href="http://{{hjemmeside}}" instead

**Comment by jaygray0919** [comment]
saw something similar in user source that may cause a problem:  `\">her</a>`
