### ISSUE TITLE
[FR] Allow crossorigin="anonymous" on amp scripts in validator

### ISSUE THREAD

**Issue by dritter** [ampproject/amphtml#24731]
Hey all,

currently, we are using a ServiceWorker to cache the amp scripts. We are not using the `amp-sw` script, as we have some complex cache purging strategies (like purging the cache, when the user visit certain URLs, or after a timeout). Instead we use our own ServiceWorker that uses `Workbox`.

Eventually, we found out that due to [opaque](https://developers.google.com/web/tools/chrome-devtools/progressive-web-apps#opaque-responses) responses our cache limit exceeded:

![image](https://user-images.githubusercontent.com/1544760/65610950-66009e00-dfb2-11e9-9c43-5e01053672f6.png)

#### Feature Request

The usual workaround for this is to set `crossorigin="anonymous"`, to make a cors request. But setting this attribute is disallowed by the amp validator. So, here is the feature request: Would it be possible to allow that? IMHO this won't make it worse..
This could be the recommended way of including amp scripts, so that folks that want to implement their own ServiceWorker (like us) wouldn't trip over that error (which is not obvious).

#### Question

We couldn't find out why this does not happen on amp.dev. Could someone enlighten us?

#### Workaround

We've managed to intercept the request, set the appropriate headers and cache that response. That works so far, but the feature request would be the much cleaner solution.

```JavaScript
// Serve the AMP Runtime from cache and check for an updated version in the background
workbox.routing.registerRoute(
  /^https:\/\/cdn\.ampproject\.org\/.*/,
  new workbox.strategies.StaleWhileRevalidate({
    cacheName: ampCache,
    plugins: [
      {
        requestWillFetch: async ({request}) => {
          // Return `request` or a different Request
          return new Request(request.url, {
            method: request.method,
            headers: request.headers,
            mode: 'cors',
            credentials: 'same-origin',
            redirect: 'manual'
          });
        }
      }
    ]
  })
)
```

// cc @uasd7

**Comment by choumx** [comment]
Seems reasonable. You'd only need ~16 cached AMP JS files to exceed quota if each opaque response is 7MB. The one issue I can see is that [dev channel](https://cdn.ampproject.org/experiments.html) won't work since cookies won't be sent in anonymous mode. 

@ampproject/wg-caching thoughts?

**Comment by twifkak** [comment]
I don't know why it doesn't occur for amp.dev; perhaps it's due to a difference in amp.dev's SW? FWIW: `assetCachingOptions: [{regexp: /\.(png|jpg|woff2|woff|css|js)/, cachingStrategy: 'CACHE_FIRST'}]`

I can't think of a reason to disallow this in AMP pages on origin. Before allowing it, we could update the cache transforms to remove the attribute when serving (unsigned) on cache -- would that mitigate the dev channel concern?

**Comment by jridgewell** [comment]
👍.

Turns out, `crossorigin=anonymous` is a **requirement** for us to receive error reports from the runtime. We should begin the process to make this a mandatory part of the boilerplate (giving people enough time to migrate, of course).

**Comment by westonruter** [comment]
> Seems reasonable. You'd only need ~16 cached AMP JS files to exceed quota if each opaque response is 7MB. The one issue I can see is that [dev channel](https://cdn.ampproject.org/experiments.html) won't work since cookies won't be sent in anonymous mode.

@choumx @jridgewell Thinking about this in relation to the [new LTS channel](https://blog.amp.dev/2020/02/05/behind-the-scenes-deploying-the-amp-runtime/) which has a dedicated LTS-specific base URL which is distinct from the stable channel, should there actually be distinct channels for `experimental` and `beta` as well to avoid the required dependency on cookies to opt-in? I can imagine this would be useful for dev environments which publishers may want to _always_ pin to `experimental`, and _always_ pin a QA environment to `beta`, and then leave the prod environment pinned to stable or `lts`?

The context here is the WordPress plugin. I'm working on a PR (https://github.com/ampproject/amp-wp/pull/4390) to update to the latest AMP spec, which includes an LTS opt-in as well as adding `crossdomain=anonymous` to the `script` and `link` tags. Currently the LTS opt-in is a boolean. However, it could be an enum including `stable`, `lts`, `beta`, and `experimental`. This doesn't make sense at the moment because there are only base URLs for stable and `lts`. But if there were base URLs for the other channels, then it would make sense.

**Comment by westonruter** [comment]
Moved my comment to a new issue: https://github.com/ampproject/amphtml/issues/27267
