### ISSUE TITLE
gulp dist doesn't prepend experiments by default

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#24817]
`gulp dist` doesn't call the `prepend-globals` task by default, which means all prod experiments are disabled on local compiled builds. This was surprising to me.

Currently workaround is to run `gulp prepend-global --target=dist/v0.js --prod` manually after dist.

/to @ampproject/wg-infra

**Comment by rsimha** [comment]
This is the intentional for `gulp dist`, since experiments are enabled by the release scripts while copying the minified code across different RTV flavors.

For local development, the preferred invocation is `gulp dist --fortesting`, which does enable all prod experiments in addition to setting `localDev` to `true`.

**Comment by choumx** [comment]
My workflow was using a proxy to run prod pages against a local build. In that case, we don't want "test" or "localDev" modes enabled. Also IMO this is not very intuitive because it's inconsistent with its sister task `gulp build`. 

A simple fix is to add an option that the release scripts can use e.g. `--noexperiments`. In any case, it's not urgent hence P3. :)

**Comment by rsimha** [comment]
Gotcha. Can do!

**Comment by rsimha** [comment]
Will prioritize this along with #25720.
