### ISSUE TITLE
Add `hidden` event to amp-analytics

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#2487]
Would fire when the document becomes invisible (opposite of `visible`).

[This was mentioned in #871.]

**Comment by rudygalfi** [comment]
@avimehta I know you raised some doubts on this in the past (I think relating to whether delivery of the ping could be guaranteed). Can you give a sense on whether you think building something like this makes sense?

**Comment by georgecrawford** [comment]
We're interested in capturing this too, if possible.

**Comment by cramforce** [comment]
`viewer.onVisibilityChanged` should mostly abstract this. The `viewer` also sends us a `we will kill you in 100ms` event that we can use for this. At this event it is very likely that we'll get killed, although it can be interrupted by the user.

**Comment by avimehta** [comment]
@rudygalfi  a few questions:

What exactly does invisible mean? Does user swiping to a different document count? does changing browser tab or minimizing the window count? Or only the page getting unloaded counts?

Also, is this supposed to work for pages that are not inside a viewer? (eg: directly on publisher website or through cache?) If they are supposed to work, viewer.onVisibilityChanged will not work the way it is currently coded.

**Comment by rudygalfi** [comment]
I'd be curious to hear @uniquelygeneric's requirements here.

I think this event is going to be pretty best-effort given we're trying to do work just as the page is going away. I think definitely in a viewer context `viewer.onVisibilityChanged` sounds like the way to go. I assume that will cover swiping to a different document.

Changing browser tab or minimizing window seem like they might be better captured using different events. They aren't destructive actions.

**Comment by uniquelygeneric** [comment]
For minimizing/tab switching, you could also use document-level [focus/blur](https://github.com/ampproject/amphtml/issues/2564) events.

I understand if a hidden event does not fire due to page close. It could still be inferred from the termination of a timer event. However, I had noticed in testing that the heartbeats/timer event could still potentially fire after the browser has been minimized, phone locked, or tab switched (particularly on Android). Ideally, either a blur or hidden event would fire once the page has been removed from focus/view.

There is some degree of semantic flexibility on what exactly is and isn't "visible". I understand why you may want to keep focus/blur to non-destructive actions, as long as an event of some type is fired when a page exits the screen.

**Comment by avimehta** [comment]
Hi,

I'll be starting work on this with hopefully a PR to show before end of the month. Everything will be behind a flag so that we can do tests in production by turning on the flags. I'll be using `viewer.onVisibilityChanged` as discussed previously in this thread. Note that the 'hidden' state means that the viewer hid the page from screen. It could still be in the background and a user can swipe and bring it back up.

### `on = 'hidden'`

```
  "triggers": {
    "hiddenTrigger": {
      "on": "hidden",
      "request": "requestTemplate"
    }
  }
```

This case is opposite of of `on = "visible"` without any `visibilitySpec`. It is a simple way of firing a hit when a page is about to be hidden.

### `on = 'visible'`

```
  "triggers": {
    "continuousVisible": {
      "on": "visible",
      "request": "requestTemplate1",
      "visibilitySpec": {
        "selector": "#adsElementSelector",
        "visiblePercentageMin": 50,
        "visiblePercentageMax": 74,
        "continuousTimeMin": 1000,
        "continuousTimeMax": 2000,
        "unload": true
      },
    },
  }
```

This method allows you to use unload along with other visibility triggers. This is usually used when you want to send out requests only if certain other conditions are met. (eg: ad has been visible for no more than 2 seconds by the time page unloaded)


**Sidenote**: I did think about allowing unload in just `on = 'visible'`. That keeps code a little cleaner as we just have one way of specifying unload requests but it is more difficult to read and understand when you don't need to use the rest of visibility spec. Feedback on this is welcome!

**Comment by rudygalfi** [comment]
Thanks @avimehta!

The Method 2 (`on = 'visible'`) semantics seem a bit weird to me because the trigger is defined as `visible` but in terms of timing for the document it's happening on unload. I wonder if we could introduce `visibilitySpec` to `hidden`?

Also, what's the use case for "ad has been visible for no more than 2 seconds by the time page unloaded". Presumably you could collect this info at the time it happens with a `visible` trigger. Is there value in introducing an unload-timed event?

**Comment by avimehta** [comment]
Talked to @rudygalfi offline. Here is what he proposed and I think it makes sense:

### `on = 'hidden'`

```
  "triggers": {
    "hiddenTrigger": {
      "on": "hidden",
      "request": "requestTemplate"
    }
  }
```

This case is opposite of of `on = "visible"` without any `visibilitySpec`. It is a simple way of firing a hit when a page is about to be hidden.

### `on = 'hidden'`

```
  "triggers": {
    "continuousVisible": {
      "on": "hidden",
      "request": "requestTemplate1",
      "visibilitySpec": {
        "selector": "#adsElementSelector",
        "visiblePercentageMin": 50,
        "continuousTimeMax": 1000,
      },
    },
  }
```

This method allows you to use hidden along with other visibility triggers.


Usecase: Advertisers may want to keep track of unviewed ads. To do this, they specify that if by the time a page is being hidden, if 50% of the ad has not been on screen for at least 1 second, send a hit.

**Comment by uniquelygeneric** [comment]
Thanks, @avimehta and @rudygalfi.

This looks like it should work for our duration analytics. Is there a way I can test out a pre-release implementation to see it's behavior at runtime?

**Comment by rudygalfi** [comment]
@uniquelygeneric Thanks for the feedback! Once @avimehta gets the PR merged, it will be incorporated as part of a canary build during the next Thursday. If you opt into the [dev channel](https://github.com/ampproject/amphtml#amp-dev-channel) you should be able to try it out early.
