### ISSUE TITLE
"selected" and "option" attributes are stripped on amp-selector childs

### ISSUE THREAD

**Issue by amanjaggaPracto** [ampproject/amphtml#24907]
## What's the issue?

AMP_Allowed_Tags_Generated does not allow the "selected" and "option" attribute in divs.
In AMP examples the "selected" attribute is used inside <div> elements and using it is mandatory for it to work.

## How do we reproduce the issue?
1. Code - https://ampbyexample.com/advanced/tab_panels_with_amp-selector/
2. Demo - https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fstyle-layout%2Ftab_panels_with_amp-selector&format=websites

## What browsers are affected?

All browsers

## Which AMP version is affected?
Version 1909181902540

**Comment by sparhami** [comment]
Both https://validator.ampproject.org/ and https://search.google.com/test/amp think the AMP markup in https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fstyle-layout%2Ftab_panels_with_amp-selector&format=websites is valid. The amp-selector validator file seems to specifically allow children to have the `option` and `selected` attributes.

A quick search for AMP_Allowed_Tags_Generated seems to indicate that it may be a part of https://github.com/ampproject/amp-wp. Is the problem you are seeing with the AMP WordPress integration?

**Comment by amanjaggaPracto** [comment]
No I am not using any WordPress integration.I am using amp selector in this Amp page - https://www.practo.com/tests/amp/chloride-24-hour-urine/p

Url,  https://validator.ampproject.org, returns a valid amp page but not https://search.google.com/test/amp

These are the result of the failed case - https://search.google.com/test/amp?id=9qSVs4cPqQpmNcljYWVxVQ . **The attribute 'option' may not appear in tag 'div'.**

**Comment by sparhami** [comment]
It looks like there are four uses of `[option]` on the page, that are a child of `<amp-selector>`, however three are failing.

After stripping down the page, I found I could get the following to fail on the validator:

https://gist.github.com/sparhami/85bab1a608697a6dcd39c3dde8e251c4

I'm not sure exactly what is going on, but changing the nested anchor tag into a non-anchor tag seems to fix the issue. AFAIK, nested anchor tags are not legal HTML, so I'm not sure if it throws off the validator (or its parser). Also, removing the `<div>` that that wraps the `<amp-selector>` also makes it validate.

@Gregable Any thoughts?

**Comment by Gregable** [comment]
There is a difference here, but the AMP test tool is the correct version. Here's the minimal version:

```
<div>
  <amp-selector role="tablist" layout="container">
      <a href="/foo">
        <div>
          <a href="/bar"></a>
        </div>
      </a>
    <div option="">B</div>
  </amp-selector>
</div>
```

However, this has "nested" `<a>` tags, which is not legal in HTML5 and so produces a different parse tree. I've re-indented to demonstrate what the HTML parser sees, replacing tags that are dropped in the parse with `[]` versions

```
<div>
  <amp-selector role="tablist" layout="container">
      <a href="/foo">
        <div></div implied>
      </a>
  </amp-selector implied>
</div>
<div option="">B</div>
```

In other words, `<a href="/bar">` is ignored because we are already within another `<a>` tag. The immediately following `</a>` closes `<a href="/foo">`, but that also implicitly closes the inner `<div>`. Now, when we encounter the first explicit `</div>`, it closes the outer `<div>` which implicitly closes the `<amp-selector>`.

Finally, when we reach the `<div option="">B</div>`, we are no longer a child of `<amp-selector>`.

This is a larger issue with the Javascript HTML parser being unaware of some of the more intricate nuances of HTML5 parsing, but the page is broken.

**Comment by sparhami** [comment]
@Gregable To clarify, is https://validator.ampproject.org incorrect in its handling of nested anchor tag due to the HTML parser it uses? Do we have a plan to fix this / output a more useful error message? Having this silently fail and the surface as another issue is not a great experience and consume quite a bit of developer time trying to understand what is going on.

**Comment by honeybadgerdontcare** [comment]
It is most likely a parsing issue difference between the JavaScript parser and the C++ parser. We have worked extensively to minimize those differences and there's ongoing work there. However, we don't expect the validator to catch every HTML5 error and report it, but instead to report AMPHTML errors.

**Comment by Gregable** [comment]
> @Gregable To clarify, is [validator.ampproject.org](https://validator.ampproject.org) incorrect in its handling of nested anchor tag due to the HTML parser it uses? 

Yes

> Do we have a plan to fix this 

Yes, but it's a long term plan to replace the parser, not an isolated fix for this specific case.

> / output a more useful error message? 

This is more difficult, I'm open to suggestions. We could have the validator emit a warning when a nested `<a>` is encountered, but I suspect that would be very noisy for pages where this doesn't cause issues. Emitting warnings for every HTML parse error, as an example, would cause most warnings to become ignored nuisances.

I was considering something like an internal warning type that is only emitted if the page fails validation. So nested `<a>` would emit a warning if and only if the page fails validation, however it's virtually impossible to associate cause in this case, so this might still be very verbose.

Currently, I think this is probably too rare. Given the complexity of making a useful error that is not more noise than signal, I'm inclined to leave it be.

> Having this silently fail and the surface as another issue is not a great experience and consume quite a bit of developer time trying to understand what is going on.

Fully agreed. The big issue is fixing the Javascript parser, which is tracked elsewhere.
