### ISSUE TITLE
Warning: `<link rel=preload>` must have a valid `as` value

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2492]
This is surprising.

Getting this message when loading
http://localhost:8000/max/s/thawing-ridge-70066.herokuapp.com/examples/index.amp.html

Can we always provide a default or make it mandatory?

Lets fix before next dev channel.

**Comment by mkhatib** [comment]
This doesn't indicate that the `as=` attribute is missing, it seems this is thrown when the value is wrong. In this case it doesn't like `as=document` although [it seems to be a valid value according to the spec](https://w3c.github.io/preload/#link-element-interface-extensions).

`as=document` might not be supported by the browser yet? Will drop it and not specify as in that case.

**Comment by jitendravyas** [comment]
I'm still getting this warning 

`<link rel=preload> must have a valid `as` value`

**Comment by cramforce** [comment]
@jitendravyas This is a bug in Chrome, so we decided to leave it as is.

**Comment by DanielHerr** [comment]
Is there an open Chrome issue for this?

**Comment by josephrocca** [comment]
Chrome issue, for those interested: https://bugs.chromium.org/p/chromium/issues/detail?id=593267

**Comment by pedramvdl31** [comment]
When you use preload as rel you must add style as the value like this:
`<link rel="preload" href="style.css" as="style">`
more info:
[](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content)

**Comment by josephrocca** [comment]
@pedramvdl31 Unless I'm mistaken, this issue is about `as="document"` rather than `as="style"` (I could definitely be mistaken here). Seems that Chrome 80 still gives a warning when trying to reload a document that is going to be used in an iframe:

```
<link rel=preload> must have a valid `as` value
```

`as=document` is definitely valid according to the spec: https://www.w3.org/TR/preload/#as-attribute

Also, a heads up to people hitting this page from Google (unrelated to AMP), if you want to preload a document from a cross-domain source, `prenavigate` might be in the wc3 pipeline for that purpose: https://github.com/w3c/resource-hints/issues/82#issuecomment-532072736

**Comment by cramforce** [comment]
document, while in the spec, is not implemented in Chrome (or any browser).
For navigations prefetch is the right primitive, and in the future
prenavigate (which will do the right thing for cross origin navigations
with double-keyed caches).
