### ISSUE TITLE
amp-carousel: Support custom scrolling indicator

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#25124]
Hi, @choumx & @kristoferbaxter:

I would like to implement custom scroll like the following picture. (It can't just use amp-carousel to complete this feature)

![IMG_2B3F215D7A3E-1](https://user-images.githubusercontent.com/10822546/67068727-7b31ac80-f1ad-11e9-8f14-c775021b46c8.jpeg)

To adopt this feature I need to use element.offsetWidth & element.scrollLeft. So I wondering is it possible to put them in allow list ?

Paul

**Comment by choumx** [comment]
Any APIs that rely on synchronous DOM state like `scrollLeft` will be tough. Does this use case have a public URL that we can look at?

**Comment by meistudioli** [comment]
hi, @choumx 

the inter action will just like the following video.
https://youtu.be/59SVJ_oikCI

How about sign that information into something like `getBoundingClientRectAsync` (promise basrd) ?

**Comment by choumx** [comment]
A Promise-based API would work. :)

Though I think we should also consider supporting touch-and-drag in `amp-carousel` since it would be easier to guarantee lazy-loading etc. /cc @ampproject/wg-ui-and-a11y

**Comment by sparhami** [comment]
I'm not sure I quite understand the custom scrolling going on here, since the video doesn't seem to capture how the user is interacting with it.

If the feature request here is for a custom pagination/progress indicator, that is something we can look into adding for carousel. This otherwise looks like a `<amp-carousel type="carousel">` from what I can tell.

We currently don't have any plans for implementing custom (JavaScript) scrolling (i.e. manually handling `touchmove`, changing the scroll position). Carousel is just a native scrolling container that behaves as scrolling containers naturally do on the platform (that is, iOS has different momentum than Android, and we should stick to the platform behavior). Implementing custom scrolling physics is not something we currently envision doing as it generally leads to an inconsistent UX and performs poorly.

**Comment by choumx** [comment]
> If the feature request here is for a custom pagination/progress indicator, that is something we can look into adding for carousel. This otherwise looks like a <amp-carousel type="carousel"> from what I can tell.

I think that's correct. Custom progress indicator, plus removing the limitation that `amp-carousel[type=carousel]` snaps scrolling to increments of 1vw might do it.

**Comment by meistudioli** [comment]
Cool. `amp-carousel` 0.2 has already move event `slideChange` to high trust. That means  `amp-carousel[autoplay]` can't react with amp-bind in this case and I can't do any indicator either. So if `amp-carousel` could support custom indicator, I'll celebrate for that.
