### ISSUE TITLE
amp-script: amp-list in subtree can't setAttribute or attach to host.

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#25185]
Hi, @choumx and @kristoferbaxter:

I check [WorkerDOM compatibility](https://github.com/ampproject/worker-dom/blob/master/web_compat_table.md) and looks like DOM API is ready for  `createElement` & `setAttribute`. So I like to do some `amp-list` mutation through these Web API. 

- Ex1: dynamic create `amp-list` element
```html
<amp-script width="300" height="100" script="local-script">
  <div class="parasite"></div>
  <template id="template-venom" type="amp-mustache">
    ...
  </template>
</amp-script>

<script type="text/plain" target="amp-script" id="local-script">
  const host = document.querySelector('.parasite');
  const ampList = document.createElement('amp-list');

  ampList.setAttribute('noloading', 'noloading');
  ampList.setAttribute('layout', 'fill');
  ampList.setAttribute('items', '.');
  ampList.setAttribute('single-item', 'single-item');
  ampList.setAttribute('credentials', 'include');
  ampList.setAttribute('src', 'web_service');
  ampList.setAttribute('template', 'template-venom');

  host.appendChild(ampList);
</script>
```

- Ex2: use exist element and change its attribute.
```html
<amp-script width="300" height="100" script="local-script">
  <div class="parasite">
    <amp-list
      noloading
      layout="fill"
      items="."
      single-item
      credentials="include"
      src="web_service"
    >
      <template type="amp-mustache">
        ...
      </template>
    </amp-list>
  </div>
  <template id="template-venom" type="amp-mustache">
    ...
  </template>
</amp-script>

<script type="text/plain" target="amp-script" id="local-script">
  const ampList = document.querySelector('amp-list');
  ampList.setAttribute('src', 'web_service');
</script>
```

Above examples aren't work. Just wondering can these actions be done with `amp-list` in `amp-script` ?

Paul

**Comment by choumx** [comment]
Hey Paul, thanks for trying out `amp-script`. Interaction between AMP elements like `amp-list` and `amp-script` are a known issue right now (we'll update the documentation with this). 

The fundamental problem is that both `amp-list` and `amp-script` assume that they have complete knowledge/control over their DOM subtrees. We need a way for them both to be reactive to changes by the other. The "bento" project is currently our long-term plan for this.

Short-term, you can try using using other (non-AMP) ways to render elements instead of `amp-list`. If you have a specific use case in mind, we'd love to hear it.

**Comment by choumx** [comment]
Merging with #25460.
