### ISSUE TITLE
amp-story: Relative image URLs in the bookend break when served from an AMP cache.

### ISSUE THREAD

**Issue by flaviori** [ampproject/amphtml#25314]
When serving the following URL from the AMP Cache 
https://www-nationalgeographic-com.cdn.ampproject.org/c/s/www.nationalgeographic.com/amp-stories/travel/10-iconic-places-to-photograph/
the thumbnail images in the bookend won't load, but they load as expected when the page is loaded from origin
https://www.nationalgeographic.com/amp-stories/travel/10-iconic-places-to-photograph/
![uUyVVLQoOoA](https://user-images.githubusercontent.com/14192925/67811398-098e1400-fa73-11e9-94ec-54f19eb1e634.png)

I noticed the images URLs are relative, so it might be that these are not properly absolutified by the cache, but I haven't verified. If relative URLs are in fact not supported, then there should be a validation error, but I believe we do want to support them.
<div class="i-amphtml-story-bookend-article-image">
  <img src="assets/01-iconic-american-destinations.jpg">
</div>

**Comment by flaviori** [comment]
The image URL was: assets/01-iconic-american-destinations.jpg

**Comment by gmajoulet** [comment]
Thanks for filing this one!

I think the issue is something different though. During ingestion by the AMP cache, the img `assets/01-iconic-american-destinations.jpg` is not present in the DOM as it will be lazy loaded as users get close to the bookend. So this img will never get fetched and cached.
The URL is fine as it tries to load the image from the AMP cache, which is the expected behavior. But the image didn't get cached.

In an ideal world, we'd want to have these images served from the AMP cache. But since the bookend configuration is dynamic and changes depending on what the publisher's backend returns, this might not be achievable.
Do we want to force the relative URLs to be loaded from the publisher's origin, when served from the cache?

cc @Gregable

**Comment by gmajoulet** [comment]
Greg and I synced offline:

When served from an AMP cache, we compute the absolute URL from the relative URL, using the current cache host.
In this example, the relative URL is
`assets/01-iconic-american-destinations.jpg`
which resolves to
`https://www-nationalgeographic-com.cdn.ampproject.org/c/s/www.nationalgeographic.com/amp-stories/travel/10-iconic-places-to-photograph/assets/01-iconic-american-destinations.jpg`
Here, we replace the `/c/s` into `/i/s`. The cache will either serve the image if already cached, or fetch it.
`https://www-nationalgeographic-com.cdn.ampproject.org/i/www.nationalgeographic.com/amp-stories/travel/10-iconic-places-to-photograph/assets/01-iconic-american-destinations.jpg`

We should also look into using extra parameters to get a resized image and save users bandwidth:
`/ii/w${width}/s`

**Comment by Enriqe** [comment]
Sorry, can you clarify if this is something we need to do on the runtime side?

**Comment by gmajoulet** [comment]
Yes my previous comment describes what our code should do :))
