### ISSUE TITLE
amp-script size limit checks real size instead of download size

### ISSUE THREAD

**Issue by marcmrf** [ampproject/amphtml#25346]
## What's the issue?

amp-scripts is checking the real size of the file instead of the download size, which normally is compressed and much smaller. If the parsing of the file is done in a web worker, the thing that has to be consider for the size limit is the bytes to download, in this case, the compressed size. For instance, react + styled components is 180kb in file system, but compressed is around 67kb.

## How do we reproduce the issue?

1. Create a script for being consumed bigger than 150,000 bytes, uncompressed
2. Consume this file compressed with gzip or brotly, size has to be smaller than 150,000 bytes.
3. Amp triggers the following errors `amp-script] Maximum total script size exceeded (150000)`

**Comment by sparhami** [comment]
I feel it would be weird to use the transferred size, and have it work locally since you are using brotli, then fail for some users in production when they receive an over the limit gzip payload.

Some lower end devices may also run limited numbers of threads, so parsing/compilation time may still be relevant. Compiled code also takes up memory proportional to the uncompressed size. While browsers are getting better at reducing how much code they keep compiled, having more code will cause other things to get evicted and recompiled later, increasing latencies for code a truntime.

Ultimately, 150,000 is the cut-off point, it could be changed to 70KB compressed. I think the discussion would be more productive on whether or not 150,000 bytes uncompressed is a sufficient threshold rather than if we should use something like 70KB compressed as the threshold.

**Comment by kristoferbaxter** [comment]
Agree with Sepand here, we've kept the threshold low to start but would be happy to explore making the value higher.

Are you interested in submitting a design document that explores how we could determine a safe high band? If so, we'd love to work together on it.

**Comment by roopakv** [comment]
@kristoferbaxter has there been any movement on this? would love to figure out 
- how we can get AMP to trust transfer size instead of actual size. We use brotli and our compressed asset is around 88.3 KB, however prior to compression our asset is ~389Kb.
- Happy to work on finding a better limit that works. But personally i think it is safer to to trust transfer size than a higher limit since some CDNs may support brotli, while others may support only gzip etc. So finding a limit would end up penalizing the folks who actually have brought their asset size down using better compression mechanisms.

**Comment by samouri** [comment]
@roopakv, not all browsers support brotli. Relying on transfer size would make validity of the script [browser dependent](https://caniuse.com/#feat=brotli). 

I was also under the impression that uncompressed size has an impact on performance aspects (e.g. parse time).

**Comment by roopakv** [comment]
@samouri that makes sense. But if we considered gzip instead of brotli that is still a huge win and gzip is supported in almost all browsers

![image](https://user-images.githubusercontent.com/678239/82937046-5ae87e00-9f44-11ea-90ef-a5a88d5530f4.png)

And yes uncompressed has performance aspects, but we could account for that and change the limits accordingly. so maybe not 150,000 but 140,000? At that point as long as the overall time remains roughly the same we are good. Further, the decompression time even on the slowest devices is pretty good, and the transfer has always been the long pole

**Comment by kristoferbaxter** [comment]
Apologies, I’m out on paternity leave. But believe this comment still applies:

Are you interested in submitting a design document that explores how we could determine a safe high band? If so, we'd love to work together on it.

Additionally, using compressed size versus uncompressed size doesn’t appear to be a good idea (fails for some browsers, passes in others).

We’ve seen it possible to deliver highly complex segments inside the current size limit, could you elaborate on what’s making this current limit difficult for your use case?

**Comment by roopakv** [comment]
@kristoferbaxter would be happy to work on a design doc. I just want to make sure I am looking in the right direction before I get started.

The thing that is (I believe) making it hard for us is that we use react and on its own that crosses some of the boundaries defined. I would love to see if it possible for us to continue using react and support amp.

**Comment by choumx** [comment]
I believe AMP's CSS limit also looks at uncompressed size. I think the deeper question is why is 150KB uncompressed insufficient for your use case?

**Comment by RobertLowe** [comment]
It would be nice if the limit was higher as then rails `turbolinks` or phoenixs `liveview` could be utilized saving page loads and accelerating the user experience, while enforcing a small payload. Its also a weird restriction considering there's no restrictions on image size for example.
