### ISSUE TITLE
Indentation for </template> is wrong in amp-list amp.dev documentation

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amphtml#25356]
## What's the issue?

Indentation for `</template>` is wrong in amp-list amp.dev documentation
## How do we reproduce the issue?

https://amp.dev/documentation/components/amp-list/

1. Go to the above page
2. Search for `</template>`
3. Most of the occurrences have indentation wrong

## What browsers are affected?

All browsers

**Comment by BrendonCurmi** [comment]
I've just opened 2 pull requests to try fix this issue:
https://github.com/ampproject/amphtml/pull/26640 - To fix the issue for EN translation on amphtml
https://github.com/ampproject/amp.dev/pull/3492 - To fix the issue for other translations on amp.dev

It seems the issue is being caused by Prettier sometimes being weird and formatting the text strangely. In fact on the first pull request, the Travis CI build failed due to Prettier/Preffify not liking it
