### ISSUE TITLE
amp-img default src image in amp-state with amp-bind

### ISSUE THREAD

**Issue by francymin** [ampproject/amphtml#25398]
Hello,
I'm trying to set a default image src. Tried in different ways but without success.

When I print the html code I don't know the default image src, and in some conditions the image should change. So I think amp-bind is the correct component.

This is a sample (not working) code:
`<amp-img 
        width="100"
        height="100"
        layout="responsive"
        alt="Test"
        data-amp-bind-src="colorGallery[150][0]"
    ></amp-img>
    <amp-state id="colorGallery">
        <script type="application/json"> { "150": [ "https://via.placeholder.com/100" ] } </script>
    </amp-state>`

No image appear, loading only...
If I type AMP.printState() in console it is undefined.

Then if I type in console AMP.setState({colorGallery: { "150": [ "https://via.placeholder.com/100" ] }})
I can see the image...

I read that:
> amp-bind expressions are not evaluated on page load, but only after an user interaction has taken place.

How I can set the default value not using the src attribute? Thanks

**Comment by cathyxz** [comment]
The default image src of `<amp-img>` should be set using the `src` attribute of `<amp-img>`. `<amp-bind>` is appropriate if you need to change the `src` attribute after user interaction. If you are waiting for data from a request in order to determine the default src of `<amp-img>`, consider wrapping the `<amp-img>` inside `<amp-list>`, possible with the `single-item` attribute if appropriate for your use case (See https://amp.dev/documentation/components/amp-list/#single-item-(optional) ). 

Issues on this repository should be for bugs and feature requests in amphtml. This would be a better question for Stackoverflow or our Slack channel. Documentation bugs and changes can be made at the amp.dev repo here: https://github.com/ampproject/amp.dev.
