### ISSUE TITLE
amp-anim is not working in inabox-lite

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#25406]
amp-anim relies on viewportCallback to function, which is neutered in inabox-resources service.

one work around is to have all resources as in viewport.
in long term, we should consider deprecate viewportCallback and use InOb. cc @dvoytenko to see if that aligns with Bento's design.

**Comment by dvoytenko** [comment]
InOb use definitely aligns as long as we have the right polyfill strategy. A bigger change - we'll want to clearly indicate which elements want to be notified from InOb to avoid oversubscribing. Calling inViewport on all elements, though, might be not exactly what we want since the Ad itself may or may not be currently in viewport. Whichever way we go, we need to make sure we only call this callback on "displayed" elements. "Displayed" being the AMP's understanding of it.
