### ISSUE TITLE
Design Review 2020-01-08 16:30 UTC (LTS schedule, wg-performance)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#25452]
Time: [2020-01-08 16:30 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2020&month=01&day=08&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20200108T163000Z/20200108T173000Z&details=https%3A%2F%2Fbit.ly%2Famp-dr))
Location: [Video conference via Google Meet](https://bit.ly/amp-dr)

The AMP community holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc or issue by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by mrjoro** [comment]
The Performance Working Group will be presenting their [periodic updates](https://github.com/ampproject/meta/wiki/Working-Group-Updates) at this Design Review (10-15 minutes).

/cc @ampproject/wg-performance @kristoferbaxter

**Comment by rcebulko** [comment]
If there's time, we'd like to get some input on [how to publicize the LTS promote schedule](https://github.com/ampproject/amphtml/issues/26206)

/cc @ampproject/wg-infra

**Comment by rsimha** [comment]
## LTS promote schedule (led by @rcebulko)

Exactly N weeks: Simple to implement, can provide a static calendar
1st Monday of the month: Easier for publishers to know when the next LTS is forthcoming

@mrjoro: Pick second Monday of the month instead of first (doesn't coincide with any common holidays). Picking a schedule exactly 4 weeks apart can coincide with holidays and release freezes. It's unlikely that any major holidays (July 4, Labor day, etc.) will be on the second Monday.

@rsimha: Preference is for Monday over Wednesday because it clears the path for stable promote and canary cuts on Tuesday.

@jridgewell: Promoting LTS on Monday will lower the risk of mistakenly promoting a brand new stable to LTS.

@mrjoro: Customers who are going to use the LTS release will actually care about regularity of release, so second Monday works best.

**Comment by mrjoro** [comment]
@kevinkimball provided a verbal update for the Performance WG during this meeting; do y'all have a written update we can link to here and on the [WG updates page](https://github.com/ampproject/meta/wiki/Working-Group-Updates)?

/cc @ampproject/wg-performance @kristoferbaxter

**Comment by mrjoro** [comment]
Friendly ping to @kristoferbaxter for the wg-performance quarterly update.
