### ISSUE TITLE
Ban dynamic content (amp-list, amp-ad) in element fallback

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#25506]
From discussion #23367, using dynamic content (amp-list, amp-ad) as element `fallback` defeats the original purpose of `fallback`. `fallback` as a UI feature should be a "graceful degradation" that is always statically available. 

That said, we don't want to people to do a `fallback` chain.

The question is do we want to start enforce that in validation? How do we do it in a backward compatible way.

/cc @ampproject/wg-ui-and-a11y

**Comment by caroqliu** [comment]
How often are we seeing dynamically sourced fallbacks in use today? In the amp.dev documentation on [Placeholders and Fallbacks](https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/placeholders/#fallbacks), there is sample markup of an `amp-img` whose provided `fallback` is another `amp-img`.

It should also be noted that an `amp-list` can render non-url expressions from `amp-bind` via the `[src]` attribute, so someone could hypothetically provide a statically analyzable `amp-list` as a `fallback` this way:
```
<amp-state id="data">
    <script type="application/json">
    {
      "items": ["apple", "banana", "orange"]
    }
    </script>
</amp-state>

<amp-list src="/bad/endpoint" ...> 
    ...
    <amp-list fallback [src]="data"  ...></amp-list>
</amp-list>
```

The resource above also says:
>  Some elements will even reward you for doing it by relaxing restrictions – for example, if you provide a `placeholder` for `amp-iframe`, it can be used near the top of the page (which won't work without).

An alternative to enforcing static `fallback` in validation could be to add restrictions on dynamic content in `fallback`. For example, if `fallback` content is statically analyzable (possibly identified as regular HTML markup and not a potentially dynamic AMP component), that could have special privileges rather than the opposite being dinged via the validator.

On a similar note, we should also consider enforcing static `placeholder` content as part of this conversation. Since the purpose of `placeholder` is to be present _while_ content is loading it's perhaps even more crucial that it is reliably renderable from the start.
