### ISSUE TITLE
amp-ima-video tag does not accept track tag in same way as standard video tag

### ISSUE THREAD

**Issue by benwfreed** [ampproject/amphtml#25514]
## What's the issue?

The amp-ima-video documentation (https://amp.dev/documentation/components/amp-ima-video/) says that track tags for subtitles are supported in the same way as the standard video tag. However, this does not seem to be the case. I have three snippets of nearly identical code, except that the first uses a video tag, the second uses an amp-video-tag, and the third uses an amp-ima-video-tag. The video and amp-video tags display subtitles, but the amp-ima-video tag does not.

## How do we reproduce the issue?

Here is a fiddle that reproduces the issue: https://jsfiddle.net/1df6h3oj/

## What browsers are affected?

Chrome. I haven't tried others.

## Which AMP version is affected?

Latest

**Comment by victhevenot** [comment]
+1 this bug, I have run into the same issue!

**Comment by nainar** [comment]
paging @lannka let us know if this is a UI WG issue instead

**Comment by micajuine-ho** [comment]
Hi @benwfreed, thank you for your issue report. 

Looking at your jsfiddle, it seems that you do no have the `data-crossorigin` attribute in your `<amp-ima-video>` tag (instead you have `crossorigin`). 

You will need this attribute since your .vtt [is from a different origin than your video](https://amp.dev/documentation/components/amp-ima-video/#attributes).
