### ISSUE TITLE
[Validator] No closing tag for <amp-audio> tag in test html

### ISSUE THREAD

**Issue by sidkshatriya** [ampproject/amphtml#2551]
There seems to be an issue with the test data at:

https://github.com/ampproject/amphtml/blob/master/validator/testdata/feature_tests/regexps.html

Excerpt from the above document 
```html
[...]
  <amp-audio src="https://exmaple.com/audio" layout="fixed" autoplay="">
  <amp-audio src="https://example.com/audio" layout="fixed" autoplay="desktop">
  <amp-audio src="https://example.com/audio" layout="fixed" autoplay="invalid">
  <amp-audio src="https://example.com/audio" layout="fixed" autoplay="desktopfoo">
  <amp-audio src="https://example.com/audio" layout="fixed" autoplay="foodesktop">
[...]
```

Are these tags not malformed? Should each tag not have `</amp-audio>` to close it? 

I notice that everywhere you are closing each custom tag and here you have not done so. 

This (according to me) should be:
```html
  <amp-audio src="https://exmaple.com/audio" layout="fixed" autoplay=""></amp-audio>
  <amp-audio src="https://example.com/audio" layout="fixed" autoplay="desktop"></amp-audio>
  <amp-audio src="https://example.com/audio" layout="fixed" autoplay="invalid"></amp-audio>
  <amp-audio src="https://example.com/audio" layout="fixed" autoplay="desktopfoo"></amp-audio>
  <amp-audio src="https://example.com/audio" layout="fixed" autoplay="foodesktop"></amp-audio>
```

Not have a closing tag presents a problem, for instance, when processing the HTML with the very commonly used [PHP dom extension](http://php.net/manual/en/book.dom.php). If closing tags are not provided then tags start nesting

```html
<amp-audio abc>
<amp-audio xyz>
``` 

when processed by PHP dom becomes 

```html
<amp-audio abc>
   <amp-audio xyz>
   </amp-audio>
<amp-audio>
```

Clearly this is very undesirable.

So we'd like to understand if not closing the tags here is a bug or the specification allows not closing tags this way. An exact answer is requested -- we've done a [limited port](https://github.com/Lullabot/amp-library) of the node.js/javascript validator to PHP and want to make sure that our validator works properly as per specification. Note: our validator deals with AMP compliance issues and not malformed HTML issues. Let us know if this is correctly formed HTML in the `regexps.html` example.

(BTW PHP dom is based on libxml2 so many other non-PHP projects may face the same isssue)

**Comment by Gregable** [comment]
The files in validator/testdata/ are not necessarily meant to be valid. They test validation features, including error messages. In this example, the emitted error messages golden file is https://github.com/ampproject/amphtml/blob/master/validator/testdata/feature_tests/regexps.out

That said, not closing `<amp-audio>` is not an AMP validation error. It is an HTML5 validation error, but AMP does not require completely valid HTML5. Modern web browsers will close these tags automatically in the appropriate context as part of error handling, so the final DOM will have closing tags in it, even if the HTML source does not. Requiring strict HTML5 validation is not necessary to guarantee performance and security, so in order to make AMP development simpler, we do not require it.
