### ISSUE TITLE
Validation : add amp-springboard-player component

### ISSUE THREAD

**Issue by Em-PredragMilosevic** [ampproject/amphtml#2553]
Per your suggestion in my <a href="https://github.com/ampproject/amphtml/pull/2467">pull request</a>, please add <code>amp-springboard-player</code> component to validation.

**Comment by Gregable** [comment]
It looks like [this](https://github.com/Em-PredragMilosevic/amphtml/blob/master/extensions/amp-springboard-player/amp-springboard-player.md) is the working spec.

Which layouts should this support? Possibly a question for @dvoytenko 

This is pretty straightforward for validation. Let me know if you think it would be helpful to validate any of the attribute values. For instance, it looks like data-more should always be `video` or `playlist`. These kinds of validation make it easier for developers to spot errors. So, for example if we know a field is always numeric or should only contain specific values, we can validate those. Otherwise, we'll just allow any value for these attributes.

**Comment by dvoytenko** [comment]
`layout=fixed|responsive|fill`

**Comment by Gregable** [comment]
@honeybadgerdontcare

**Comment by Em-PredragMilosevic** [comment]
Attribute values:
<code>data-mode=video|playlist</code>
<code>data-site-id=NUMERIC</code>
<code>data-player-id=ALPHANUMERIC</code>

Thanks

**Comment by Gregable** [comment]
From the documentation, it looks like all 6 data- attributes are mandatory, since mandatory errors are listed for them. Is that correct or are any of them optional?

**Comment by Em-PredragMilosevic** [comment]
Yes, they are all mandatory.

**Comment by Gregable** [comment]
Validation added, but it'll take a week or so before this will go live.

**Comment by Em-PredragMilosevic** [comment]
Ok, Thanks.

I'm closing the issue.

**Comment by Gregable** [comment]
<amp-springboard-player> validation is now live everywhere. It'll hit javascript in roughly an hour.
