### ISSUE TITLE
Add `focus' and 'blur' events to amp-analytics

### ISSUE THREAD

**Issue by uniquelygeneric** [ampproject/amphtml#2564]
Would fire when the document is in or out of focus.

Similar to onfocus and onblur events in JavaScript.

**Comment by avimehta** [comment]
@uniquelygeneric would https://github.com/ampproject/amphtml/issues/2487#issuecomment-234050096 solve this, if yes, I'll close this bug.

**Comment by uniquelygeneric** [comment]
@avimehta I would like to test out the implementation before giving a final word, but yes, it looks like #2487 will likely be sufficient.

**Comment by avimehta** [comment]
cool. Let me close this bug and take the discussion to the other bug then. Feel free to comment on the PR. If you would like to test it before it is checked in, you can also patch the PR into a local client and then try it out.

**Comment by rudygalfi** [comment]
@avimehta I don't think I'm following how the `hidden` support in your PR covers `focus` and `blur`. Can you explain?

**Comment by avimehta** [comment]
@rudygalfi I think the motivation for the request was to calculate total time on page. `hidden` lets you calculate the end of time on page thus letting you calculate the duration.

There is also the use case of firing `visible`, and `hidden` triggers every time the page comes and goes out of view. This use case is not supported by my PR. If there is interest in that, please reopen the bug and I'll work on that as well. Adding support for repeated triggers should be easy and can probably be done as a generic solution for `visible`, and `hidden` events with or without `visibilitySpec`.

**Comment by Littlemad** [comment]
I am sorry to comment I am a developer looking for better understanding and use AMP, but the example on https://github.com/ampproject/amphtml/issues/2487#issuecomment-234050096 about using "visibility" instead of "focus" / "blur" as event it is absolutely not clear related to tracking events in amp-analytics. I want to track how many time an user is focusing on an input or checkbox, and his relative blur. I have nothing that I want to track that is visible, I just want to understand when some elements are "in focus" like in JS. At the moment I couldn't find any example on the docs related to tracking such thing. I just want to understand if there is a way to do it and how, and if not, understand why.
