### ISSUE TITLE
Provide a mechanism for a custom video play/pause button

### ISSUE THREAD

**Issue by schlessera** [ampproject/amphtml#25669]
## Describe the new feature or change to an existing feature you'd like to see

Here's the specific use case:

There's that popular WordPress theme that has a looping video header. It has a button in the top right corner for people to pause the video, or resume looping again. It's a toggle button, so if the video is currently looping, it is labeled "Pause", and when you click it, the label changes to "Play" for the resume action.

I would like to be able to replicate this behavior with `<amp-video>`.

The most simple option would be to have an additional action `toggle` next to `play` and `pause`.

Another simple solution would be to be able to use `amp-bind` to bind the "playing" state of the video to a variable I can control. This would then be guaranteed to sync with the label of the button.

## Describe alternatives you've considered

I looked at the https://github.com/ampproject/amphtml/issues/19435#issuecomment-453310850, and I think it would solve the problem as well once it is implemented and deployed. However, it would be hugely complicated for this particular use case, where a simple toggle is needed. If I understand correctly, this would entail adding two conditional macros, just to get this toggle working.

## Additional context

Here's a link to the origin issue: https://github.com/ampproject/amp-wp/pull/2819

**Comment by westonruter** [comment]
Note the popular theme (Twenty Seventeen) is using a WordPress core feature—video headers—so this issue can appear in any theme that is also using video headers. Here is the logic for toggling whether the video is playing:

https://github.com/WordPress/wordpress-develop/blob/944502a09421e1b14f84b5fae4bdcccc495263a8/src/js/_enqueues/wp/custom-header.js#L126-L133

**Comment by wassgha** [comment]
@alanorozco this seems like a valid request, you can reassign it to me if there's too much on your plate

**Comment by alanorozco** [comment]
From an online discussion between @wassgha and me.

> The most simple option would be to have an additional action toggle next to play and pause.

This is not possible since playback events can come from different sources and keeping the button state in sync would be impossible just with the actions mechanism.

> Another simple solution would be to be able to use amp-bind to bind the "playing" state of the video to a variable I can control. This would then be guaranteed to sync with the label of the button.

This seems possible, but `amp-bind` seems like overkill for a play/pause button, since it needs to download about `17kb` and needs to spin up a worker.

Another choice would be to wrap this in a managed component, like `<amp-play-button>` or `<amp-video-controls>` (the latter just supporting play/pause initially but custom controls are the higher-level story here).

For now we're considering both `amp-bind` or a new API that can be coordinated via a new component or selectable video element descendants. Will update here.

**Comment by alanorozco** [comment]
...I'm realizing that I also failed to consider event trust.

Playback state events should not be considered high-trust, so in AMP land they shouldn't be allowed to mutate the DOM generically. So I'm thinking the scope of solutions changes with some caveats:

A. We can use `amp-bind`. However, we can't really `setState` as those operations are always assumed to be high-trust. A mechanism similar to `amp-script` where mutations are allowed under a fixed size container might work, but that requires additional work since not even `amp-script` cascades `amp-state` changes into this scenario.

B. Domain-specific component or video-component internal API is still on the table and unchanged.

C. Not do any additional runtime work and similar to the original solution:

    - post `play/pause` events as `LOW` trust.
    - support `playPause` action
    - require `amp-animation` for visual button toggle (it's the only kind of mutation trigger that can be allowed with low-trust. This has a larger overhead over the wire than `amp-bind`, but doesn't require any new additional mechanisms under the hood.

**Comment by schlessera** [comment]
Gentle ping to enquire about the status of this.
Is there anything I can help with to unblock?
