### ISSUE TITLE
AMP validator detects  more CSS than the actual length.

### ISSUE THREAD

**Issue by VivianWang1993** [ampproject/amphtml#25686]
**Actrually, its length is only 45300, but the AMP validator shows its length is 50647**

- The demo pages are  https://www.magicstarry.com/custom-gift-for-pet-lovers.html?amp=1 and https://www.magicstarry.com/custom-gift-for-pet-lovers/personalized-accessories.html?amp=1
- And its length is changing in other page while they use the same code.

![image](https://user-images.githubusercontent.com/34879854/69216216-9b86c980-0ba6-11ea-9356-11c3906df054.png)

![image](https://user-images.githubusercontent.com/34879854/69216521-5f079d80-0ba7-11ea-8fbb-d32593bbffd9.png)

**Comment by honeybadgerdontcare** [comment]
@VivianWang1993 I'm unable to reproduce the issue. Do you have a page that does reproduce this issue you can share? Please reopen if you do.

**Comment by VivianWang1993** [comment]
- https://www.iartify.com/gifts.html?amp=1&color%5B0%5D=BLACK&color%5B1%5D=Aqua&color%5B2%5D=SkyBlue

- https://www.iartify.com/gifts.html?amp=1&color%5B0%5D=Aqua&color%5B1%5D=DarkBlue

**Comment by honeybadgerdontcare** [comment]
@VivianWang1993 I see what the issue is. The 50k CSS limit counts both `<style amp-custom>` and all inline styles on elements (`style=`). The first page has 256 inline styles and the second page has 260 inline styles. Plus the size of inline styles probably are different for each element. There is also a 1k limit on each inline style.

**Comment by VivianWang1993** [comment]
Thanks @honeybadgerdontcare , Got it
