### ISSUE TITLE
amp-carousel v2 sets the display property of i-amphtml-fill-content to block with important.

### ISSUE THREAD

**Issue by kborisov93** [ampproject/amphtml#25717]
## What's the issue?
I have a carousel with text elements inside. It works like navigation panel for the rest of the page.
It has to take the whole container width and the elements have be equally distributed. 

The new stylesheet of the carousel contains the following code:

`amp-carousel:not([type=slides]) .i-amphtml-carousel-scroll {
    **display: block!important;**
    white-space: nowrap!important;
}`
Setting it to flex used to work with v1, but not anymore.

## How do we reproduce the issue?
[jsbin](
https://jsbin.com/wozipopahe/1/edit?html,output)

Change the carousel version number.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

1911121900560

**Comment by sparhami** [comment]
It looks like you are targeting an internal element of a component, which uses an `i-amphtml` class so that you cannot target it directly, and avoiding that restriction by using a generic tag name selector. Note that there is no API guarantee for such usage and such things may break in the future, even without a version change.

The CSS you have added also makes the arrows position incorrectly, since it targets the arrow container which uses flex internally.

I'm not sure everything will work correctly, in general, if we remove the restriction of the scrolling container not being flex for the carousel (i.e. not slides) case, so this needs a bit more investigation.
