### ISSUE TITLE
Visibility issues with Ads on Internet Explorer 11

### ISSUE THREAD

**Issue by sman68** [ampproject/amphtml#2577]
Cube ads that are being displayed inside an iframe on IE11 are getting a visibility: hidden inline style added to it, which hides the ads. Does anyone know a workaround on this? This is not occurring on other acceptable browsers.

Here are three sites that currently have this problem. Each one shows fine as AMP pages in latest Chrome, Safari, Firefox, & Edge, but if you open these pages in IE11, cube ads are invisible. Our company is having the same problem and we are triaging it now.

1. https://www.washingtonpost.com/amphtml/blogs/plum-line/wp/2016/03/11/get-ready-donald-trump-youre-about-to-run-into-a-buzz-saw/#
2. http://mobile.nytimes.com/2016/03/10/opinion/sanders-surprises.amp.html#
3. http://www.people.com/people/article/amp/0,,20993119,00.html#

Not completely sure if this this a bug or if IE11 was intentionally left out because of other issues?

**Comment by rudygalfi** [comment]
@kashyapnitin for triage

**Comment by mark-leppa** [comment]
Having this same issue getting IE11 to display AdSense ads (Android, Chrome and Firefox are all working good). After troubleshooting, I discovered **two separate issues with displaying on IE 11:**

1. The `visibility: hidden` style is being applied via the `-amp-fill-content` class. Below is a hack which allows the ad to display. This is an invalid style due to -amp prefix and !important usage. Use this for debugging only: 
    ```
.-amp-fill-content {  
      visibility: visible !important;
    }
```
2. When you use amp inline media queries on IE 11, such as: 
```
         <amp-ad 
            **media="(min-width: 768px)"**
            width=728 height=90
            type="adsense"
            data-ad-client="ca-pub-0000000000000000"
            data-ad-slot="0000000000">
        </amp-ad>
```
       The class `-amp-hidden-by-media-query` is preventing the display of a valid inline media query amp-ad with: 
```
.-amp-hidden-by-media-query {
    display: none;
}
```

**Comment by dvoytenko** [comment]
@sman68 To confirm, the problem is specifically due to issues with IE11 interpreting media query? Do you know if this is only when calling `window.matchMedia` API directly? Or when doing this via CSS, e.g. `<style>@media (...) {}</style>`?

**Comment by sman68** [comment]
@dvoytenko and @mark-leppa this involved only the CSS style issue as pointed out from @mark-leppa's first issue (visibility) from our side.

**Comment by dvoytenko** [comment]
@mark-leppa @sman68 `-amp-fill-content` never applies `visibility: hidden` - could you point me to a place where it does so?

**Comment by mark-leppa** [comment]
@dvoytenko if `amp-fill-content` never applies `visibility: hidden` then something else is because that style is applied on the rendered page in IE 11. Pleading ignorance of amp internals, I am not the one to speak to exactly how this might be occurring. In my original post above I describe symptoms from a front-end developer perspective rather than cause. 

A few areas I suspect may be causing this issue: 1. amp media query incompatibilities with IE 11, 2. IE 11 incompatibilities with amp or 3. mis-implementation of amp on my own part although, like @sman68, ads render properly in all other browsers tested.

**Comment by dvoytenko** [comment]
Thanks, @mark-leppa! We'll take a look. If IE11 `window.matchMedia` is broken, we have a recourse to address that.

**Comment by dvoytenko** [comment]
I can confirm the problem on IE with this jsbin: http://jsbin.com/fafeteg/edit?html,js,output

On startup the `window.matchMedia` is regularly wrong. Interestingly, it self corrects after about 1 second. No correlation with `DOMContentLoaded`, `resize` or `window.loaded` events.

The only stable solution I see is to externalize `media` expressions into CSS as described in #1428.

**Comment by cramforce** [comment]
Can we quick fix this with an IE specific hack?

**Comment by dvoytenko** [comment]
The only way to fix it for now I see is to stop using `window.matchMedia` on IE - I tried a number of things to find a better signal and there's simply none. We can implement this feature and deploy to IE first to test out.

**Comment by cramforce** [comment]
SGTM

**Comment by dvoytenko** [comment]
My only hope was `onchange` events on the `MediaQueryList` object, which we previously saw some issues with on other browsers. However these events are not supported on IE at all.

**Comment by dvoytenko** [comment]
Blocked by #3077.

**Comment by ericlindley-g** [comment]
This is blocked by another item in the backlog, so I'm inclined to put it there as well, but @dvoytenko @cramforce feel free to let me know (or re-slot directly) if either this or #3077 have a more specific target (next couple of sprints, or in the short-term after after)
