### ISSUE TITLE
amp-access not sending pingback request

### ISSUE THREAD

**Issue by montmanu** [ampproject/amphtml#2578]
We would expect https://www.google.com/amp/mobile.nytimes.com/2016/03/15/arts/music/radiohead-tour.amp.html to make two requests to https://meter-svc.nytimes.com/meter.js -- one GET (`authorization`) and one POST (`pingback`).

Verified on iPhone 6 / iOS 9.2 (13C75)

AMP HTML Version - 1457721872758

**Comment by dvoytenko** [comment]
@montmanu and I discussed this on Slack. This is due to the "Authorization failed: " Error: Response must contain the AMP-Access-Control-Allow-Source-Origin header" error, which is described in detail here: https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md

Additional recommendation is to use https://github.com/ampproject/amphtml/blob/master/extensions/amp-access/amp-access-analytics.md to report authorization and pingback failure events to stay on top of this kind of issues.

I will close this bug for now, but please reopen as needed.

**Comment by Shobby** [comment]
I have a form on my amp website right now it is not functional, all i want to send emails from that form whenever any user fills that form admin of  the site will receive the email with all the filled information.

How i can achieve this with AMP.

please guide me on this

**Comment by dvoytenko** [comment]
/to @mkhatib @ericlindley-g to respond. Generally, this sounds like a wholly separate issue from the original bug here.

**Comment by mkhatib** [comment]
/to @rudygalfi 

@Shobby Check out the [example we have](https://github.com/ampproject/amphtml/blob/master/examples/forms.amp.html#L238). It's gonna be very similar to that.

What you would need to make sure your backend does is that it sets the [CORS headers correctly](https://github.com/ampproject/amphtml/blob/master/extensions/amp-form/amp-form.md#security-considerations).

Let me know if you have specific questions about the example.
