### ISSUE TITLE
Validator engine files shouldn't run percy

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/amphtml#25831]
Files in /validator/engine do not need to run percy as they have no affect on the UI. Maybe even exempt /validator as a whole, unless there's concern around allowing or disallowing new attributes.

**Comment by rsimha** [comment]
Visual tests are only run against PRs that modify the runtime. For the rest, we generate a dummy Percy build with a single blank snapshot. (This is done because it is a required check on GitHub, and the Percy service does not provide a way to skip a build without uploading a snapshot.)

@honeybadgerdontcare can you point out a case where visual tests were blocking a validator-only PR? (I want to make sure it's generating just a blank build.)

**Comment by honeybadgerdontcare** [comment]
This one was and is causing issues and it's only a comment change within the validator.js file: https://github.com/ampproject/amphtml/pull/25581

**Comment by rsimha** [comment]
From looking at the [Travis logs](https://travis-ci.org/ampproject/amphtml/jobs/619860235#L348) for #25581, a blank build was indeed generated. I think this is a transient bug on Percy's side. We can recover from this by restarting just the Visual Test job. I've done that for you.

Feel free to reach out if the restart doesn't do the trick. Meanwhile, closing this issue.

**Comment by honeybadgerdontcare** [comment]
Thank you @rsimha. Is there a way to restart the test myself? I didn't see any options in the percy UI.

**Comment by honeybadgerdontcare** [comment]
Oh, is it Travis that kicks off the separate Percy instance? So if Percy has issues then just restart Travis?

**Comment by rsimha** [comment]
> Oh, is it Travis that kicks off the separate Percy instance? So if Percy has issues then just restart Travis?

You are correct. See [this section](https://github.com/ampproject/amphtml/blob/master/contributing/TESTING.md#flaky-tests) of `TESTING.md` for more details.
