### ISSUE TITLE
Bot comments for PRs without a linked issue

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#25844]
When a PR is created without any linked issue, a bot should leave a comment indicating that one is usually required and provide a link to the [contribution process](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md). Ideally, this would only happen for medium-to-large PRs, and would not trigger on small/trivial PRs.

This idea is motivated by the increasing number of PRs not following this convention, such as #25703 and #24788 . New contributors are not always familiar with the contribution process, and so this gets raised at PR review time. This has some developer cost, as AMP contributors then end up partially reviewing code and pointing the new contributor(s) to documentation of the process.

So far, the PR template is updated in #25841 with the expectation that an issue is linked, along with a link to the contribution process.

Creating a new bot for this purpose would be helpful. At the same time, it would take development and maintenance, and would only take effect after a PR is already created and, most likely, after reviews are already requested. This reduces the potential usefulness of the bot, especially given that it does not actually block any contributor from submitting or creating PRs without linked issues. It's questionable whether a bot for this is worthwhile.

Care to add any additional context @nainar @alanorozco ?
/cc @ampproject/wg-infra

**Comment by alanorozco** [comment]
During an offline discussion with some members of @ampproject/wg-ui-and-a11y the topic of collaboration blockers in particular cases came up more generally.

Concretely, some aspects of collaboration approval are "more optional" than others. For example, expecting a linked issue is a bit of a NO-OP since that's the case for most PRs (so it'd just be a nag bot).

But security is a whole different case. We don't need security reviews for most changes, but it's important when we do. Some of those can be analyzed statically very simply:

- Cookie access (we can check for use of our internal utilities and the browser APIs)
- Inserting scripts
- Creating frames
- Creating URL strings without encoding

So expecting a review from @ampproject/wg-security-privacy in those cases might be very helpful to reduce friction overall.

I know this diverges the conversation somewhat but in case issue linking is too trivial to consider a collaboration-process-blocking bot, maybe there are some other contexts in which it might be useful.

**Comment by rcebulko** [comment]
It sounds like what @alanorozco suggests is needed is, generally speaking, the ability for teams and working groups to implement some degree of semantic checking, and potentially trigger effects or ownership in some way based on those checks.

The linked issue bit seems to be fairly separate. This case would probably require a good bit of business logic to identify different triggers, and then some way of either interacting with the owners bot or acting as its own bot (or perhaps some form of a Travis check, but I don't know if that would work).

Leaving these thoughts here while we collect more feedback around this issue and get a higher-level view; maybe a solution will clarify itself as a couple more use cases fall into place.

**Comment by choumx** [comment]
FYI we used to have a bot that would comment on missing labels, priority-based update SLOs, etc. and it was widely found to be noisy and eventually discarded.

**Comment by rcebulko** [comment]
> FYI we used to have a bot that would comment on missing labels, priority-based update SLOs, etc. and it was widely found to be noisy and eventually discarded.

I agree with this sentiment generally; I feel like comment-only bots would offer minimal benefit, and any new bots we decide to put in place should have some actionable effect (ie. on ownership, Travis, GitHub status, reviewers/labels, etc.)

**Comment by molnarg** [comment]
Within google, we have "presubmit checks" that can block submitting the change until a member of the security team LGTMd the change. This is triggered for dangerous APIs and turned out to be very useful. Something like that would be useful here too.

**Comment by rcebulko** [comment]
This exists in the form of the [Owners Bot](http://ampproject-owners-bot.appspot.com/example)

**Comment by choumx** [comment]
> This is triggered for dangerous APIs

Does owners bot do this? We do have regex-based presubmit checks for dangerous APIs, though owners bot would need to inspect file contents to subsume it.

**Comment by rcebulko** [comment]
It doesn't for specific APIs (and I'd say that may be out of he scope of the owners bot, given that it's a good bit of code introspection and the like), but there's nothing stopping an owner or WG from making the API files owned by a smaller group with `required: true`. Are there existing use cases or examples where APIs need to be locked down within files that need broader ownership?

**Comment by choumx** [comment]
https://github.com/ampproject/amphtml/blob/master/build-system/tasks/presubmit-checks.js

**Comment by rcebulko** [comment]
So these checks will currently fail on a PR without the proper review? Or are they just warnings?

**Comment by choumx** [comment]
Try it. 😉 

Though this is digressing from the original issue and I think presubmit-checks is probably good enough as is.

**Comment by rsimha** [comment]
This conversation has touched upon a few different things. To summarize:

1. Substantial PRs must be linked to an existing issue
2. Security (or other) reviews should be done for PRs that touch certain parts of code (Owners bot can already do this)
3. The use of dangerous APIs in code should be disallowed and safe alternatives suggested (Regex based `gulp presubmit` already does this)

To accomplish item 1 (the original subject of this issue, as I understand), I think we can reorganize the default [PR template](https://github.com/ampproject/amphtml/blame/master/.github/PULL_REQUEST_TEMPLATE.md) into sections so that authors can fill out mandatory parts and selectively delete optional parts.

**Comment by rcebulko** [comment]
PR template has been updated in #25841; closing.
