### ISSUE TITLE
amp-img loading dots does not go away when error is thrown

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#2585]
## How do we reproduce the issue?

1. create amp-img with bad url link.
2. refresh repeatdly until you get a an amp-img whos "loading dots" don't dissapear.

## Short description of your issue:

amp-img loading dots does not go away when error is thrown

## What browsers are affected?

All browsers

## Which AMP version is affected?

unsure, but currently exists in master as of 1457721872758

**Comment by erwinmombay** [comment]
will look for ux guidance if this is the behavior we want or not

**Comment by dvoytenko** [comment]
I think we should definitely stop spinning. I can't see any way to provide any indication of the error, however. I don't think we will find one. There are couple of options here:
 1. I'm pretty sure we can find and add the appropriate aria attributes to indicate that element has failed.
 2. We can consider adding a class or a attribute to the element and leave the styling to the author. However, I can't quite imagine anyone really styling this.

So, most likely option for us is to stop spinning, possibly set aria, but otherwise noop.

**Comment by dvoytenko** [comment]
@erwinmombay In the meantime, the advise should be for people who experiment with image fallback to include `noloading` attribute.

**Comment by ericlindley-g** [comment]
@erwinmombay You were working on this one, right? Do you have everything you need now, UX-wise?

**Comment by erwinmombay** [comment]
@ericlindley-g yep i was. should be good ux-wise, trying to wrap up some stuff and will try and get to this asap.

**Comment by rudygalfi** [comment]
We should re-slot this: next milestone or pending? @ericlindley-g

**Comment by dvoytenko** [comment]
I think our first action here should be to hide them on error. And move error state processing in a separate bug.

**Comment by erwinmombay** [comment]
starting to work on this

**Comment by rudygalfi** [comment]
Rolling this into next milestone.

**Comment by ericlindley-g** [comment]
@erwinmombay Is this tracking toward the 4/14 milestone?

**Comment by ericlindley-g** [comment]
Rolling into the 4/28 milestone

**Comment by src-code** [comment]
@dvoytenko: 

> I'm pretty sure we can find and add the appropriate aria attributes to indicate that element has failed.
> We can consider adding a class or a attribute to the element and leave the styling to the author. However, I can't quite imagine anyone really styling this.
> So, most likely option for us is to stop spinning, possibly set aria, but otherwise noop.

Hiding the element by default seems like a good start, but if developers could also style against a class or attribute, that'd be nice too.  Perhaps the default for `-amp-error` could be `display:none`, but also add another class that developers can style against?  This is relevant to more than just amp-img, also - eg, if an amp-iframe 404's, it'd be nice to be able to hide it.

**Comment by erwinmombay** [comment]
we could possibly add `amp-error`(no dash meaning public) to be styled

**Comment by dvoytenko** [comment]
The reason we didn't want to hide it by default was because of the same scrolling issues that often plague when images are loaded. The same problem will be with a class. And aria attributes are, of course, also expose us to the same problem. We can do our own hiding via our resizing system that's more respectful of scrolling.

**Comment by ericlindley-g** [comment]
Rolling into the next milestone

**Comment by cramforce** [comment]
Yes, public class please. Then devs can just style it as `display: none` if they want that.

**Comment by dvoytenko** [comment]
Let's not do an error class yet, but instead rely on "fallback". I actually believe we already do that in most (all?) cases, so we can check if we need some consistency, but otherwise fallback system is the way to go.

**Comment by rudygalfi** [comment]
Can this be closed out based on #3153?

**Comment by erwinmombay** [comment]
@rudygalfi nope, we closed that one out. so this is still primary tracking issue for this. will prioritize this after i finish up some amp-live-list work.

**Comment by erwinmombay** [comment]
closing this as new work is being done in #3806 by @zhouyx
