### ISSUE TITLE
[amp-sidebar-0.1.js] Does not use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by eduardogoncalves** [ampproject/amphtml#25865]
Chrome Audits reports for Best Practices

![image](https://user-images.githubusercontent.com/4308648/70156828-ea466000-168a-11ea-93f7-19b0e3c9ced4.png)

**Comment by sparhami** [comment]
The only touch listener is here:

https://github.com/ampproject/amphtml/blob/d9015fe61b6ccecfc6c2d2cfccf33cdfb396cabd/extensions/amp-sidebar/0.1/amp-sidebar.js#L611-L613

Which cannot be passive, since it calls `preventDefault()`.

There is no context on the code, but if I had to guess, it was probably to prevent swiping on the mask scrolling the document, it seems to have been there from the start. Since the page is made `position: fixed` when we open the sidebar, I think it should be safe to just remove this.

**Comment by wassgha** [comment]
Closing in favor of #26203

**Comment by yosuke-furukawa** [comment]
what status is this issue ?
[on the project](https://github.com/ampproject/amphtml/projects/72#card-30151818), the status is "Done".  but i could not find the PR.

**Comment by 7110** [comment]
Build version: `2001281851410` seems to solve this __Best Practices__ issue.
https://cdn.ampproject.org/v0/amp-sidebar-0.2.js
