### ISSUE TITLE
Amp v0.js adds ineligible tags to static html

### ISSUE THREAD

**Issue by rotexhawk** [ampproject/amphtml#25911]
I am using gatsby js to build my static amp page and you can see the final html output in the [search console](https://search.google.com/test/amp?id=khLFg07BIgoKn_XaRuHfIQ). You can see that the generated html is valid. 

These tags are added after the page is loaded. It is added by the v0.js and I don't know why. If I remove the script, the html stays the same. 

```<script async src="https://cdn.ampproject.org/v0.js"></script>```

It's adds things like `amp-version` `i-amphtml-sizer` in the css and changes other things on the page. 

You can see the failing page here. 
https://search.google.com/test/amp?id=aClwacaTtbw5q7-Dm3glPg&skip_amp_follow=true

Noticed this in the code. It is very hard to debug this further in the compressed version of `v0.js`. Where can I see the original `v0.js`?

`self.document.documentElement.setAttribute("amp-version", "1911191835190")`

**Comment by samouri** [comment]
Hi @rotexhawk,

Those tags are supposed to be added by v0 at runtime, but are not meant to be served from your origin server. It looks like your site is serving different HTML based on whether it is being crawled by Google or not (and sending the html with ineligible tags to Googlebot).

A default curl provides valid AMP:
- `curl https://www.michaelharwinlaw.com/what-is-a-career-criminal/amp/`

A curl with the Googlebot UA nets invalid AMP:
- `curl -H "User-Agent:Googlebot" https://www.michaelharwinlaw.com/what-is-a-career-criminal/amp/`

In order to fix this, you'll need to make sure your server emits valid AMP even with a Googlebot UA.

**Comment by samouri** [comment]
I'm going to close this for now, but please leave another comment if you have further trouble and I'll reopen the issue.
