### ISSUE TITLE
"firstchild" is an invalid value for "id" attribute?

### ISSUE THREAD

**Issue by blakebutcher** [ampproject/amphtml#25933]
## What's the issue?

https://amp.abc.net.au/article/10303912 is failing validation due to: 

> The attribute 'id' in tag 'a' is set to the invalid value 'firstchild'.

But the documentation for IDs at https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/#ids seems to indicate it should be OK.

## How do we reproduce the issue?

https://validator.ampproject.org/#url=http%3A%2F%2Famp.abc.net.au%2Farticle%2F10303912

## What browsers are affected?

N/A

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1911191835190 https://amp.abc.net.au/article/10303912

**Comment by sparhami** [comment]
It doesn't like the attribute value itself (`firstchild`). When an element has an id, it gets added to the global window object (in this case, `window.firstchild` will be the anchor tag). In order to prevent accidental renaming of important properties on the `window` object, the validator disallows some values being used as ids.

**Comment by sparhami** [comment]
Perhaps the validator could link to some more description on why the value is not allowed in the error message.

**Comment by honeybadgerdontcare** [comment]
We should probably update the [documentation](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/#ids) to link to the [disallowed list of attributes](https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L5392).

@CrystalOnScript fyi
