### ISSUE TITLE
Amp-ad is already registered. The script tag for amp-ad is likely included twice in the page. Even the script is loading once in the page.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ampproject/amphtml#25960]
1. AMP-Ad:- error.js amp-ad is already registered. The script tag for amp-ad is likely included twice on the page. https://monosnap.com/file/n8lhmTiF9Vt2pDKJ5IPVvKDI0G4EQE
The script is included once in the source code https://monosnap.com/file/VbG66lGA1NTekfqe7y24F7ymzkoL6a

2. Either it is a bug or it is conflicting with the Sticky ads.js

**Comment by zerkshaban** [comment]
Somehow I am facing the same error but for amp-bind, did you got anything on this ?

**Comment by aldeimos** [comment]
> Somehow I am facing the same error but for amp-bind, did you got anything on this ?

Hello there. Did you solved that problem?

**Comment by zerkshaban** [comment]
> > Somehow I am facing the same error but for amp-bind, did you got anything on this ?
> 
> Hello there. Did you solved that problem?

Not exactly, the issue only appeared when I switch between the tab I was using amp-bind in and the non amp-bind tab. So, on first render it was working fine but on switching the tabs in coming back it was showing me this issue "Keeping in mind that this issue inside the storybook of the project which was not using nextJS". So, I shifted my component to main project in which we are using nextjs. The issue disappeared itself, I still don't know why was it not working in the storybook might be because it's not compatible with JS.

**Comment by zerkshaban** [comment]
> > > Somehow I am facing the same error but for amp-bind, did you got anything on this ?
> > 
> > 
> > Hello there. Did you solved that problem?
> 
> Not exactly, the issue only appeared when I switch between the tab I was using amp-bind in and the non amp-bind tab. So, on first render it was working fine but on switching the tabs and coming back it was showing me this issue "Keeping in mind that this issue occured inside the storybook of the project which was not using nextJS". So, I shifted my component to main project in which we are using nextjs. The issue disappeared itself, I still don't know why was it not working in the storybook might be because it's not compatible with JS.
