### ISSUE TITLE
Sidebar opens twice on tap event in Safari

### ISSUE THREAD

**Issue by veronicaweiss** [ampproject/amphtml#25991]
## What's the issue?

Clicking on button that is supposed to open the sidebar (on="tap:sidebar.open") opens the sidebar twice. The first time it quickly opens and closes, the second time it stays open. 

## How do we reproduce the issue?

https://www.powtoon.com/video-templates
Open on mobile in Safari or in responsive design mode on desktop

1. Tap the hamburger menu button

## What browsers are affected?

Safari, on mobile and on desktop

## Which AMP version is affected?

Version 1911191835190

**Comment by samouri** [comment]
Hi @veronicaweiss!

I don't have the full solution but I've done some preliminary research which should give whoever takes this on a headstart.

I think is caused by an interaction between custom css in the `<style amp-custom>` tag.  Specifically the line:
```
    *, *:hover{-webkit-transition:all 0.3s ease-in-out; -moz-transition:all 0.3s ease-in-out; -o-transition:all 0.3s ease-in-out; transition:all 0.3s ease-in-out;}body{margin:0}
```
---

I figured this out by comparing the computed css on the `amp-sidebar` component vs. the css in the examples on the amp playground (which don't have this issue).

Here are a couple things that were able to resolve the issue:
1. Removing that line of the css
2. Adding a `transition-duration: 0;` style rule to the `amp-sidebar[side][i-amphtml-sidebar-opened]` selector.

**Comment by veronicaweiss** [comment]
Thanks a lot @samouri ! It really helped!
