### ISSUE TITLE
amp-iframe won't render if positioned before first visible viewport threshold (72vh/600px)

### ISSUE THREAD

**Issue by suntong** [ampproject/amphtml#26211]
## What's the issue?

Please take a look at
https://output.jsbin.com/guyigetegi

Which contains several `amp-iframe`s. 

The problem is that, there are huge gaps between them, and while looking at the source, https://jsbin.com/guyigetegi/edit?html,js,console, I don't see anything that might have caused the huge gaps.

How to make the `amp-iframe`s next to each other without gaps? Thx.

**Comment by alanorozco** [comment]
@suntong Could you draw on a screenshot which gaps you're referring to?

From my look at it the 2nd of the 3 frames won't load and therefore leave an empty box, but I don't see any margins on the individiual frame components.

**Comment by alanorozco** [comment]
Digging deeper, the second frame is not loaded since you can't have frames before the first visible portion of the document, defined as `75% of viewport height or 600px, whichever is smaller`.

<img width="1096" alt="Screen Shot 2020-01-07 at 9 12 07 AM" src="https://user-images.githubusercontent.com/254946/71914160-e09e9500-312d-11ea-9ae6-35064df4e912.png">

I'm unsure as to why this rejects the second frame rather than the first, but overall the use case of rendering >1 frames taking up a certain amount of the first viewport is **not allowed**.

This is worked around by redesigning your page. Include a container before the first frame that takes up the `75vh/600px` visible portion so the runtime won't prevent the frames from rendering.

So an element with CSS as:

```css
.spacer-before-first-frame {
  height: 75vh;
  max-height: 600px;
}
```

**Comment by suntong** [comment]
Thank you @alanorozco, 

So I put an element of `.spacer-before-first-frame` before the first frame, and it looks good within jsbin editor:

![image](https://user-images.githubusercontent.com/422244/71938865-c4771400-317e-11ea-9b27-97d4fab1e1d5.png)
-- https://jsbin.com/wevelug/edit?html,output

However, when viewing it without editor, I got this:
![image](https://user-images.githubusercontent.com/422244/71938959-115aea80-317f-11ea-9204-d7006a252817.png)
-- https://output.jsbin.com/wevelug

I.e. I still see gaps between the amp-iframes (although they are smaller than I saw before).

I know you might think that this is not an amphtml issue but a jsbin one, but I'm still curious how I can make the jsbin full output look normally. Thanks!
