### ISSUE TITLE
Custom Javascript Not Working

### ISSUE THREAD

**Issue by instanano** [ampproject/amphtml#26353]
I am using AMP on blogger template and custom javascripts are not working properly. I want to create my custom scientific calculator, which should have sin cos value calculations also. Please help me.

**Comment by samouri** [comment]
Hi @instanano, currently AMP has specialized support for JS in the form of [amp-script](https://amp.dev/documentation/components/amp-script/). Beyond that, custom 3p js in the main thread is explicitly not allowed. 

Closing since AMP is functioning as desired/expected, but feel free to leave more comments if you have further questions.
