### ISSUE TITLE
amp-script: Support layout=nodisplay (or zero width/height)

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#26378]
@choumx mentioned that `nodisplay` will cause issues if set as the layout for `<amp-script>` elements. Should this be removed from the validator, or added as a supported layout in the extension?

**Comment by samouri** [comment]
I believe the issue is that components are usually not laid out unless they have a nonzero width/height. Currently, `<amp-script>` has most of its initialization within layoutCallback, so without layout it becomes inert.

I'm investigating how to address this for https://github.com/ampproject/amphtml/pull/29541
