### ISSUE TITLE
FR: allow doc level opt-out of amp-auto-lightbox

### ISSUE THREAD

**Issue by photocoder** [ampproject/amphtml#26452]
## What's the issue?
My website use AMP. And home page doesn't have any "lightbox" pluggins added.
even more, I put "data-amp-auto-lightbox-disable" tag everywhere I can, but, I still see in information, that it's loaded.
"amp-auto-lightbox-0.1.js"
You can see full stat with Waterfall Chart of request-by-request visualization of the page load here: https://gtmetrix.com/reports/dimasfrolov.com/bR3vy8mq

## How do we reproduce the issue?
https://dimasfrolov.com/

## What browsers are affected?
Chrome, Opera, Firefox

## Which AMP version is affected?
Powered by AMP ⚡ HTML – Version 2001071857360

**Comment by caroqliu** [comment]
The `data-amp-auto-lightbox-disable` tag disables behavior of the lightbox but not inclusion of the script in the first place. This seems like a feature request to be able to do the latter. /cc @ampproject/wg-runtime @alanorozco

**Comment by alanorozco** [comment]
@photocoder `amp-auto-lightbox-0.1.js` is tiny and has no effect when disabled. Is there a particular need you're trying to fulfill by not loading it?

**Comment by jitendravyas** [comment]
I have the same question. Why should it load if I don't intend to use.

**Comment by photocoder** [comment]
> @photocoder `amp-auto-lightbox-0.1.js` is tiny and has no effect when disabled. Is there a particular need you're trying to fulfill by not loading it?
It just one more request what I didn't ask.
But anyway, if "disable" option exist, why it doesn't work?

**Comment by alanorozco** [comment]
@photocoder @jitendravyas 

I'd like to understand the practical concerns coming from loading a script that is a) `3.4kb` and b) to an already preconnected domain. Some clarification might be needed:

1. Out of the `3.4kb` size, ~40% is common extension overhead. This is being handled separately for all extensions, but in any case the difference is negligible in all practical purposes.

2. Disabling per the `data-` attribute doesn't promise that the extension won't load. It means the treatment is not applied. Should this be clarified on docs?

3. There's logic inside `auto-lightbox` to determine other criteria for treatment as well.

One important distinction between the core runtime binary (`v0.js`) and extension binaries (`amp-auto-lightbox-*.js`) is that the former **blocks page display**, while extensions don't delay the page from displaying.

For this reason, including `auto-lightbox` in the core runtime would make it ~2% larger. The _page display_ delay is not a great trade-off since it would block every AMP page, while loading a separate binary won't delay visibility.

Otherwise, to introduce some block for the loading of the `auto-lightbox` binary itself we'd need to increase core size to some degree.

To do this properly might need some design work, as the `data-` attribute annotation strategy cannot perform as well from a runtime's pov. I'm also not fully convinced of the need to increase core size in order to prevent this request in general.

**Comment by ithinkihaveacat** [comment]
For me it's not necessarily about the real-world perf implications, it's that loading the script just seems a bit unnecessary, wasteful and surprising. I certainly didn't expect it to be loaded even if the page contains no images (I actually thought this was a bug); in this case I don't think an opt out should be necessary, it should just not load at all.

**Comment by sebastianbenz** [comment]
+1 to @ithinkihaveacat 

I agree that it doesn't make sense from a perf point of view, but it is very surprising for developers and this question will come again and again.

**Comment by westonruter** [comment]
We get support forum topics about this for the WordPress plugin as well.

**Comment by jridgewell** [comment]
ping @nainar

**Comment by jono-alderson** [comment]
Also keen to see this not load, when not needed/used. This waterfall is so very _nearly_ perfect.
![image](https://user-images.githubusercontent.com/11629607/117264148-dcca7200-ae4a-11eb-8f4d-48aecda28502.png)
