### ISSUE TITLE
amp-analytics fires only occasionally in amp-ad-custom

### ISSUE THREAD

**Issue by mwakkiy** [ampproject/amphtml#26643]
## What's the issue?
amp-analytics fires only occasionally in amp-ad-custom

## How do we reproduce the issue?
I've made this sample.
https://test.ms-rd.com/amp/amp-ad-custom/test01.html

1. Reload page several times

2. amp-analytics fires only occasionally
When amp-analytics is successful, there is a request at the following URL.
https://b94.yahoo.co.jp/1/m?
https://b94.yahoo.co.jp/1/v?

## What browsers are affected?
All browsers

## Which AMP version is affected?
Version 2001281851410

**Comment by micajuine-ho** [comment]
@lannka We took a look at this issue, but think that it's probably ads related rather than analytics related. Would you mind taking a look?

**Comment by lannka** [comment]
sure, looking

**Comment by lannka** [comment]
while still looking, some early finding is a race condition between the loading of amp-analytics.js script and the injection of `<amp-analytics>` in FIE.

**Comment by lannka** [comment]
it is because the `factory` method for amp-analytics's services didn't get run in that case
https://github.com/ampproject/amphtml/blob/036ab52732023159f37039da166caef7d68efb3e/src/service/extensions-impl.js#L404-L418

It happens when the amp-analytics.js script gets loaded before the `<amp-analytics>` element gets injected in the FIE iframe. 

because `<amp-analytics>` element is injected dynamically, it missed the opportunity to get stubbed during `stubElementsForDoc` time.

https://github.com/ampproject/amphtml/blob/036ab52732023159f37039da166caef7d68efb3e/src/custom-element.js#L795-L804

 so `<amp-analytics>` is not stubbed, so the `isStub` call returns `false` which prevents `installExtensionForDoc`  from being run.


@dvoytenko @choumx did I miss anything here? is a dynamically injected AMP element supposed to be stubbed if the extension is already fully loaded on the page?

**Comment by choumx** [comment]
Sorry I'm not familiar with amp-analytics injection in FIE. Is the code above the correct, non-racy path? FIE doesn't actually call `installExtensionForDoc` itself and relies on custom-element.js?

**Comment by dvoytenko** [comment]
@lannka I don't think this is the reason here. I'll need to debug this. Do you have a good localdev repro instructions?

**Comment by lannka** [comment]
@dvoytenko I pushed a branch for testing. pls check out https://github.com/ampproject/amphtml/pull/28882

and thanks for helping!

**Comment by lannka** [comment]
Discussed with @dvoytenko offline, we both believe the launch of [ampdoc-fie experiment](https://github.com/ampproject/amphtml/pull/25554) will fix the issue. It's not worth at this time to add additional hacks to fix amp-ad-custom. We will prioritize the launch of ampdoc-fie instead.
