### ISSUE TITLE
Cache transformations modifying website layout

### ISSUE THREAD

**Issue by twifkak** [ampproject/amphtml#26660]
http://hawaii-limo.com is an AMP page that looks correct, but https://hawaii--limo-com.cdn.ampproject.org/c/hawaii-limo.com breaks its layout. My suspicion is a open/close tag imbalance somewhere, as that has been the primary cause in the past.

Original report: https://groups.google.com/a/chromium.org/d/msg/webpackage-dev/UKtfA468F18/oDN752JUAQAJ

cc @ampproject/wg-caching

**Comment by Gregable** [comment]
I'd have to run a document through the AMP cache to be certain, but spending a few minutes looking at the differences in the DOM of these two pages, it appears that the original has an unclosed button tag:

```
 <nav class="navbar navbar-dropdown navbar-expand-lg navbar-fixed-top">
...
<button on="tap:sidebar.toggle" class="ampstart-btn hamburger sticky-but">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </buttom> .</nav>
```

Note the typo of butto**m** in the closing tag instead of butto**n**.

The browser appears to close the button tag when it encounters the closing `</nav>` tag, while the AMP Cache keeps putting later nodes under the `<button>` tag.

There may be other additional issues.
