### ISSUE TITLE
insecure response errors with amp-kaltura-player

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#2669]
We're working on a POC for a TV station that's using Kaltura.  I generate the `<amp-kaltura-player>` tags from their page to match the example.

```
<amp-kaltura-player 
    data-uiconf="14517512" 
    data-partner="557781" 
    data-entryid="1_1znjuxfv" 
    data-param-streamertype="auto" 
    layout="responsive" width="640" height="390">
</amp-kaltura-player>
```

The player loads, I see the poster image but when I click play it fails on this URL returning insecure content.

https://ib203846.ib-prod.com/p/557781/sp/55778100/serveFlavor/entryId/1_1znjuxfv/v/1/flavorId/1_c37b93lk/forceproxy/true/name/a.mp4

What am I missing?

Fails on all browsers.

Tagging @itaykinnrot

**Comment by itaykinnrot** [comment]
In order to override the default and use http please add the following param : data-param--kaltura.-protocol="http" (i can also add it to the uiconf from the server if you want)
In addition i'll suggest to use up to date player version (our latest is 2.41 and you're using 2.36) - you can just go to the studio in KMC and add a new player

**Comment by jridgewell** [comment]
@itaykinnrot: To be clear, do you mean `data-param-kaltura-protocol="https"`?

**Comment by jpettitt** [comment]
Won't switching to http cause an AMP validation fail / mixed content warning?  

Is there any way we can specify an https to http proxy to use for stations that don't have their content on https servers?

**Comment by jpettitt** [comment]
I added `data-param-kaltura-protocol="https"` and now it works.

In addition, and this is probably a chrome thing, if using chrome to emulate an iOS device I get audio and no video.  If I emulate an android device it works fine. A real iPhone also works fine.  

I'm seeing an error in the logs (only on chrome in iOS emulation so may not be a real error)

`'https://cdnapisec.kaltura.com/html5/html5lib/v2.36/mwEmbedFrame.php/p/55778…uxfv&flashvars%5Bstreamertype%5D=auto&flashvars%5BkalturaProtocol%5D=https' was loaded over HTTPS, but requested an insecure image 'http://cfvod.kaltura.com/p/557781/sp/55778100/thumbnail/entry_id/1_1znjuxfv/version/100011/acv/191/width/100/vid_slices/100'. This content should also be served over HTTPS.`

**Comment by dvoytenko** [comment]
If `data-param-kaltura-protocol="https"` is necessary, we should simply force it on all `<amp-kaltura-player>` instances automatically from the AMP extension. @itaykinnrot is there any reason we shouldn't do this?

**Comment by itaykinnrot** [comment]
Hi all,
The amp-kaltura-player use https by default - you dont need to add special param for that, The issue @jpettitt is raising related to wrong CDN configuration or mapping issue since the cdn host is without https certification. I suggested to force it to be loaded with http but if you're saying http is not supported we will resolve it internally, @jpettitt lets take it through the Kaltura support - Thanks,
