### ISSUE TITLE
amp-access: cookie won't pass with SameSite cookie policy 

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#26833]
To whom it may concern:

I use `<amp-access />` to connect member login status through AMP pages. I try to force turn on SameSite cookie policy with browser Chrome (VER. 80) and I found out cookie without `SameSite=None Secure` won't pass to authorization API. That means I can't pass login status cookie to API and I will get non-login all the time.

I check [SameSite Cookie document](https://web.dev/samesite-cookie-recipes/) and figure these out:
![image](https://user-images.githubusercontent.com/10822546/74622275-2877f980-517b-11ea-889f-50c9bfa5c1f1.png)

AMP CDN Cache to my site API is cookies for cross-site usage.

What if I can't modify the cookie to `SameSite=None Secure`, is there any suggestions or method to solve this issue or my `<amp-access />` will be nothing but piece of junk. 

- [Effected Site: TW Yahoo Auction](https://tw.bid.yahoo.com/amp/homepage)
- [AMP CDN Cache page](https://tw-bid-yahoo-com.cdn.ampproject.org/c/s/tw.bid.yahoo.com/amp/homepage)

Paul

**Comment by meistudioli** [comment]
Any update ? Looks like SameSite Cookie Policy has already active and my login process has fail.

**Comment by choumx** [comment]
I think the recommended approach is to use `READER_ID` and then map it to your logged-in user identity ID on your backend. Another (more expensive) solution is to implement [signed exchanges](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/signed-exchange/) to avoid the whole cross-site issue in the first place.

> What if I can't modify the cookie to `SameSite=None; Secure`

Curious why not? 

Side note: I think all browsers are moving away from third-party cookies, so this will be more and more of a problem over time. E.g. was authentication for Safari users also a problem due to ITP?

**Comment by amrithakrishnan** [comment]
@meistudioli Hi Paul, I'm facing the same issue. Did you find a solution that worked for your scenario?
