### ISSUE TITLE
Untangle Sauce Labs integration test logs

### ISSUE THREAD

**Issue by estherkim** [ampproject/amphtml#26852]
On Travis, integration tests run in multiple Sauce Labs browsers at the same time. The test logs are unorganized as a result, and can be misleading.

Example of a tangled Travis job log:
https://travis-ci.org/ampproject/amphtml/jobs/652149872#L2311

The error is reported on Chrome, but the end result says 1 test failed in Safari 12.

**Comment by rsimha** [comment]
I think the current entanglement comes from printing the per-browser start and finish events inline, instead of saving them for the end. (The reason this was done earlier was to help debug stalled builds, since it was otherwise hard to know which browsers were in the process of running tests during a stall.)

With the sleuthing done by @rcebulko in identifying the cause of our stalled Sauce Labs runs, we could consider getting rid of the inline reporting for per-browser [start](https://github.com/ampproject/amphtml/blob/929dfd9e53254a601331ec96869aa4fe0e35f711/build-system/tasks/runtime-test/helpers.js#L187-L194) and [finish](https://github.com/ampproject/amphtml/blob/929dfd9e53254a601331ec96869aa4fe0e35f711/build-system/tasks/runtime-test/helpers.js#L215-L227), and simply rely on the report at the end.

One disadvantage of doing this is that if there is one failure each on two different browsers, it will become even harder to tell which failure occurred on which browser. But I suppose the current situation is not great either, so it might still be worth making the logs more readable.

WDYT?

**Comment by rcebulko** [comment]
I think this would be a good move for the short term, to improve log readability. It looks like it's not just the start and finish bits getting logged and mixed around, but also the progress bubbles. Ex.

![image](https://user-images.githubusercontent.com/6694512/80722666-9de23d80-8acd-11ea-9ef7-be4c29928843.png)

It's not obvious which set of bubbles even corresponds to which set of bubbles. This will only get worse if heartbeat fixes to karma-sauce-launcher eventually allow us to increase the # of concurrent browsers.

Longer-term, perhaps it could be feasible for each browser to log to a temp file/buffer, and dump the full log at the end, grouping any errors with each browser. Instead of setting up a long-term connect tunnel, each browser could run in its own tunnel (see [ephemeral vs long-running tunnels](https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Proxy+Tunnel+Types%3A+Ephemeral%2C+Long-Running%2C+Combination#SauceConnectProxyTunnelTypes:Ephemeral,Long-Running,Combination-CombinationTunnels)). The latency impact of an extra tunnel would have to be investigated, but it may simplify and add structure to logging

**Comment by rsimha** [comment]
Bubbles are for following instantaneous progress, so the only way to have them be useful during concurrent runs is to have them be interspersed. We could stop printing them during sauce runs, but that’ll lead to long periods of radio silence. 

My vote is to compromise and remove the inline total summaries but leave the bubbles alone. SGTY?
