### ISSUE TITLE
Improve amp-nested-menu documentation for usage with amp-list

### ISSUE THREAD

**Issue by philkrie** [ampproject/amphtml#26874]
**Please only file reports about bugs in AMP here.**

## What's the issue?

As noticed in https://github.com/ampproject/amp.dev/pull/3450, when creating dynamic nested menus in AMP using amp-list, amp-nested-menu does not work with dynamic data. 

https://glitch.com/edit/#!/amp-snippets?path=dynamic_menu_sub_menu/index.html shows an example of this being attempted.

When you click into a submenu, the transition occurs but nothing appears, despite the li elements all being populated with the correct info when you look at the DOM. The inspector even highlights the boundaries of these elements when you select them in the elements tab.

## How do we reproduce the issue?
Please refer to https://glitch.com/edit/#!/amp-snippets?path=dynamic_menu_sub_menu/index.html 

## Which AMP version is affected?
2002191442400

**Comment by cathyxz** [comment]
FYI it will work if `<amp-nested-menu>` is a child of `<amp-list>`'s `<template>` tag. See: https://github.com/ampproject/amphtml/blob/master/extensions/amp-nested-menu/amp-nested-menu.md#dynamic-content-rendering

Working amp.dev playground example: 
https://gist.github.com/cathyxz/8cee99f26856f2f7e7b4465378641272

It seems like this file (https://github.com/ampproject/amphtml/blob/master/extensions/amp-nested-menu/amp-nested-menu.md#dynamic-content-rendering) was written in a way to be displayed on amp.dev (e.g. all the playground examples). Is there a reason why this isn't searchable in amp.dev? Since we merged https://github.com/ampproject/amphtml/pull/25517, we should be able to remove the experimental status from that page too. =)

**Comment by philkrie** [comment]
Got it, so and I confirmed it in Glitch. My bad! Thanks for surfacing the solution.

@sebastianbenz looks like we already had an example, so I'll roll back my PR. Why isn't this searchable?

**Comment by sebastianbenz** [comment]
What do you mean by searchable?

>

**Comment by philkrie** [comment]
It doesn't appear in playground.amp.dev search

**Comment by cathyxz** [comment]
It looks like it works now: https://amp.dev/documentation/components/amp-nested-menu/
For whatever reason, that link was 404-ing 11 days ago. I wonder if it now works because the intro table was removed in https://github.com/ampproject/amphtml/pull/26383, or if it's because amp.dev had logic to exclude documentation for components in `experimental` (which has since been removed).

**Comment by cathyxz** [comment]
I played with this a bit more because the documentation here can probably be a bit better. Here's a bit of context on the usage of amp-nested-menu with dynamic rendering. 

1. Generating an entire `<amp-nested-menu>` within an amp-list is supported where the entire `<amp-nested-menu>` is generated as part of the `<amp-list>` template. This covers most use cases where you just want to dynamically generate the entire thing. 
``` 
<amp-sidebar>
  <amp-list ...>
    <template ...><amp-nested-menu/></template>
  </amp-list>
</amp-sidebar>
```
2. Generating an `<amp-list>` as the child of `<amp-nested-menu>` is supported conditionally, when the `amp-list` is not generating submenus. Explicitly, when the contents of the `amp-list` does not contain a div with the amp-nested-submenu attribute. This should cover the use case where most of your menu is static, but a small portion of it needs to be dynamically generated (banners, promotions, etc.). 

3. Generating nested submenus using an `<amp-list>` within `<amp-nested-menu>` is not supported. This is due to layout issues. The submenus in `<amp-nested-menu>` has transition animations and this doesn't work well with the way `<amp-list>` does layout, refresh, refetch, etc. 

 
Here's another example that you can play with in the playground. I basically made your code kind of work by turning `<amp-list>` to use layout FIXED. Observe that the first layer of menus are generated, but when you click on them, the submenus transition off the screen and the layout's quite off. 

```
<amp-sidebar id="sidebar2" layout="nodisplay" style="width:300px">
  <amp-nested-menu layout="fill">
    <h1>
      Test
    </h1>
    <amp-list
      layout="fixed"
      height="300"
      width="300"
      src="/static/inline-examples/data/amp-list-data.json"
      items="."
      single-item
    >
      <template type="amp-mustache">
          <ul>
            {{#items}}
            <li>
              <h3 amp-nested-submenu-open>{{title}}</h3>
              <div amp-nested-submenu>
                <button amp-nested-submenu-close>close</button>
                <amp-img
                  src="{{imageUrl}}"
                  layout="responsive"
                  width="400"
                  height="300"
                ></amp-img>
              </div>
            </li>
            {{/items}}
          </ul>
      </template>
    </amp-list>
  </amp-nested-menu>

</amp-sidebar>
```

Anyway @philkrie, does that help with what you were trying to do in the first place? Would you be up to helping us update the documentation here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-nested-menu/amp-nested-menu.md#dynamic-content-rendering 

So that whoever has similar questions as you did in the process will be able to find what they need easier? You can send a pull request to @wassgha and @CrystalOnScript if you like. =)

**Comment by philkrie** [comment]
Sure thing, I'll add your snippet to that file. I think there are other places I could make updates to mention amp-nested-menu. 

In general, I think amp-nested-menu is a bit confusing: the name doesn't associate it with amp-sidebar, and to be frank, until I tried to solve this problem I was not aware it existed, so it could probably be mentioned in a few more tutorials/documentation. amp-mega-menu is also usable w/ amp-nested-menu, but seems to require amp-sidebar as well. It also isn't clear why it isn't really a standalone element: it must be paired w/ amp-sidebar.
