### ISSUE TITLE
Add visual indicator for active opt-in version

### ISSUE THREAD

**Issue by ChrisAntaki** [ampproject/amphtml#26990]
Recently I experienced some flakiness when using the `experiments.html` page. I was testing iOS 13, 12, and 11 via BrowserStack, which gives you access to the JavaScript console. Based on the console logs, the opt-in wasn't taking effect consistently in iOS 13 and 11. One or two refreshes seemed to fix the issue. For iOS 12 though, no amount of refreshes helped, I wasn't able to get the console logs to say it was loading the version I'd opted in to. https://github.com/ampproject/amphtml/issues/26746#issuecomment-585095522

Would it be possible to add a, possibly optional, visual indicator when an opt-in version was active? I worry that without a visual indicator, it's pretty easy to assume the version is active when it might not be

**Comment by danielrozenberg** [comment]
While this is a valid request, I think it's also much more involved than one would expect. To get this rolling, we would need input from:
* @ampproject/wg-infra: currently there's no binary difference between getting the `experimental` opt-in version v0.js vs. getting it because the CDN randomly chosen to send the `experimental` build via its A/B testing mechanism. We would have to figure out a way to indicate the difference (my first thought: maybe an HTTP response header?)
* @ampproject/wg-ui-and-a11y: how would that look?
* //cc @ampproject/wg-runtime @ampproject/wg-performance @ampproject/wg-security-privacy might want to chime in

**Comment by jridgewell** [comment]
> maybe an HTTP response header

Headers are not inspectable in JS. This would have to be a check for the cookie value, or some global.

**Comment by choumx** [comment]
I assume OP is asking for a visual indicator on actual AMP pages. Experimental channel has `canary: 1` in the runtime experiment (canary-config.json), so we could have some runtime code that renders a little overlay on the page.

**Comment by ChrisAntaki** [comment]
Yep, that would be awesome!

**Comment by choumx** [comment]
FYI opt-in on Safari is finicky due to ITP effect's on cookies. I typically disable "prevent cross-site tracking" in Safari settings to avoid this, though probably not an option in emulation. 

I believe private/incognito mode or clearing cache also resets ITP state.

**Comment by ChrisAntaki** [comment]
Thanks for the tips! BrowserStack won't allow for changing Safari settings sadly

**Comment by rsimha** [comment]
_[Infra triage]_ Is this something we'd like to do? If not, can this be closed?

**Comment by ChrisAntaki** [comment]
Please feel free to close :+1:
