### ISSUE TITLE
Support for non cache served AMP pages

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#27011]
Allow for developers to voluntarily opt out of a valid AMP page being in the cache. This will make personalization and cookie management much easier. 

Proposal in detail here: 
https://docs.google.com/document/d/1uEMpT3r692Sy6qZW7UgYekXaMr7KDTep1D5zMbTAIVI/edit#

cc @sebastianbenz @Gregable @alankent @cramforce

**Comment by morsssss** [comment]
Woo!

/cc @demianrenzulli @antoinebisch

**Comment by alankent** [comment]
Love it!

**Comment by westonruter** [comment]
How does this relate to signed exchanges? I can imaging a case where a site wants to simplify cookie management but _also_ take advantage of signed exchanges. In other words, serve signed exchange from cache if browser supports it, otherwise serve from origin. In other words, never use AMP Cache URLs.

**Comment by alankent** [comment]
Is that covered by the `<html amp="no-caching-non-sxg">` example in the proposal doc? "Don't cache non SXG content."

**Comment by westonruter** [comment]
Right you are! My bad. I did a find for “signed exchange” but not “SxG”.

**Comment by twifkak** [comment]
Dupe of #29296.
