### ISSUE TITLE
Java AMP-Validator not in mvn repository

### ISSUE THREAD

**Issue by patrickmartin0** [ampproject/amphtml#27069]
## What's the issue?

There is no amp.validator:amphtml-validator:1.0 in the maven repository

## How do we reproduce the issue?

Include `implementation group: 'amp.validator', name: 'amphtml-validator', version: '1.0'` in your build.gradle or search for amp.validator on https://mvnrepository.com

**Comment by honeybadgerdontcare** [comment]
FYI @GeorgeLuo @nhant01

**Comment by GeorgeLuo** [comment]
@patrickmartin0 hello, we have just recently revisited the distribution. we were looking to push to central repository, but noticed build issues come up, due to changes in the extensions since the merge. we are resolving those build conflicts right now and will follow with getting this into central. Thanks for the attention.

**Comment by patrickmartin0** [comment]
Hey @GeorgeLuo @nhant01 
any updates here?

**Comment by GeorgeLuo** [comment]
@patrickmartin0 thanks for checking in.  issue #27093 is addressing this right now. My impression is this the work left is not substantial, the question is of process and ownership.

**Comment by honeybadgerdontcare** [comment]
@patrickmartin0 The Java AMP Validator has moved into it's own repository. If this is still an issue for you then please file this request there: https://github.com/ampproject/validator-java
