### ISSUE TITLE
Design Review 2020-04-01 15:30 UTC (amp-social-share layout shift, wg-outreach)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#27073]
Time: [2020-04-01 15:30 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2020&month=04&day=01&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20200401T153000Z/20200401T163000Z&details=https%3A%2F%2Fbit.ly%2Famp-dr))
Location: [Video conference via Google Meet](https://bit.ly/amp-dr)

The AMP community holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc or issue by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by mrjoro** [comment]
The Outreach Working Group will be presenting their [periodic updates](https://github.com/ampproject/meta/wiki/Working-Group-Updates) at this Design Review (10-15 minutes).

/cc @ampproject/wg-outreach @sebastianbenz

**Comment by erwinmombay** [comment]
I'd like to present about changes to allow the module/nomodule pattern in AMP in regards to origin pages (20 mins)

**Comment by caroqliu** [comment]
If there is time left I'd like to discuss several approaches for reducing layout shift on `amp-social-share`.

**Comment by choumx** [comment]
### Layout shift in amp-social-share

#### Approaches

1. SSR in cache based on user agent
2. allowing prerender
3. render blocking
4. render blocking in runtime
5. mitigate with CSS behavior change (depends on usage)
6. ~don't hide~ (worse UX)
7. ~reorder in cache~ (worse UX)

#### Discussion

- MU: Let's make it prerenderable in any case
  - CL: OK :)
- KB: In the vein of "do things at the right layer", this type of work should be delegated to the server (AMP cache)
- MU: Let's not do the render blocking thing
- MU: Change defaults to align with most likely outcome, and add a class on desktop to override default due to lack of Web Share API
- WC: Does it cause layout shift on other content?
  - CL: Depends on usage but it's possible.
- WC: Can we migrate a fixed-size container API that follows AMP's normal resizing rules (and maybe transform existing usages)? 
  - Would allow layout shift within buttons in the component, but won't impact other content on the page.
- KB: Can we use a phased approach for short-term and long-term? I.e. allow prerender, do the UA-based cache SSR, implement a better V2 API for amp-social-share?
