### ISSUE TITLE
Design Review 2020-03-18 20:00 UTC (wg-bento, deprecate old AMP versions, url beta/experimental opt-in)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#27071]
Time: [2020-03-18 20:00 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2020&month=03&day=18&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20200318T200000Z/20200318T210000Z&details=https%3A%2F%2Fbit.ly%2Famp-dr))
Location: [Video conference via Google Meet](https://bit.ly/amp-dr)

The AMP community holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc or issue by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by danielrozenberg** [comment]
I would like to discuss a plan to [deprecate and remove AMP versions older than 6 months](https://github.com/ampproject/amphtml/issues/25468). I expect this to be a short discussion (~10-15 minutes)

**Comment by mrjoro** [comment]
The Bento Working Group will be presenting their [periodic updates](https://github.com/ampproject/meta/wiki/Working-Group-Updates) at this Design Review (10-15 minutes).

/cc @ampproject/wg-bento @dvoytenko

**Comment by danielrozenberg** [comment]
And another quick discussion, @westonruter would like to add an option to [opt-in to beta/experimental channels via the URL](https://github.com/ampproject/amphtml/issues/27267) instead of via a cookie, given increase usage of `crossorigin="anonymous"`

**Comment by dvoytenko** [comment]
Bento update: https://github.com/ampproject/wg-bento/issues/10

**Comment by rsimha** [comment]
### AMP Versions older than 6 months - Led by @danielrozenberg

- Came out of discussion around nightly builds and what to do with older builds
- 6 months seems like a reasonable amount of time because there are ~25 stable builds
- wg-caching helped determine that ~50k webpages are pinned to older RTVs, <10k pages pinned to versions older than 6 mo

**Decision:** Let's do this, with a 6 month period, and a redirect to the latest LTS for all requests for older RTVs

**Comment by rsimha** [comment]
### Adding url-based opt-in for Beta / Experimental - Led by @westonruter and @danielrozenberg 

- Came out of discussion around adding `crossorigin=anonymous` to all CDN scripts
- When this is added, cookies are not respected, so there's the need for dedicated URLs for fetching channels (vs. current cookie-based method)
- Can be useful for pinning certain pages to beta / experimental, instead of relying on developers to do so
- Pages that pin to beta / experimental should NOT be valid AMP
- Cookies may not be usable on all surfaces, for example, mobile browsers without dev tools. URL-based opt-in can help in those situations.
- We should discourage publishers from pinning to beta / experimental. This is why we don't plan on making these pages valid AMP.
- It's unlikely that publishers will organically move all their pages to beta / experimental, because it will need all their pages to be re-ingested.
- Paths vs. query params:
	- Our infrastructure requires path names to be different in order to differentiate between server / security settings. So that's one point in favor of using different path (versus the same path with an additional URL param at the end).
    - Different path isn't a hard requirement like LTS, so it's not the end of the world if we can't control the caching behavior.
    - Internal serving infrastructure currently doesn't have the ability to inspect query params, but it can inspect paths.
    - In terms of HTTP semantics, a query param may be preferable, but no strong objection to a different path.


**Decision:** Let's implement this. Will investigate both options (path vs. query param) and update this issue with the final decision.
