### ISSUE TITLE
Cached video does not fallback to the origin video

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#27109]
The video source in this story 404s, and does not fallback to the origin video:

https://unumbox-com.cdn.ampproject.org/v/s/unumbox.com/website-development-trends-2020-amp-story/?usqp=mq331AQFKAGwASA%3D&amp_js_v=a2&amp_gsa=1#referrer=https%3A%2F%2Fwww.google.com&visibilityState=visible&cap=swipe&ampshare=https%3A%2F%2Funumbox.com%2Fwebsite-development-trends-2020-amp-story%2F

cc @ampproject/wg-stories

**Comment by gmajoulet** [comment]
1. Only on 3 panels desktop
2. Only if the video is in the first 3 story-pages
3. Only when the cached source 404s

**Comment by newmuis** [comment]
There are reports of this happening on mobile as well, also when served from the AMP cache.

**Comment by cramforce** [comment]
One fundamental problem is I think that media-pool works with `amp-video` elements before they ever had a `layoutCallback` resolve. That breaks all kinds of assumptions like #27874 

Is there any reason that the media pool has to ignore the AMP `layoutCallbacks`? If yes, should it turn it off and completely take over the video lifecycle instead of letting both run concurrently?
