### ISSUE TITLE
Refrain from depreciating Bookend & Sidebars

### ISSUE THREAD

**Issue by ghelapratik** [ampproject/amphtml#27149]
**Problem**

As documented a week ago or so at https://github.com/ampproject/amphtml/issues/26957 & https://github.com/ampproject/amphtml/issues/26958, bookend & Sidebars are on their way to be depreciated as new components like amp-tooltips, page-attachments exist and users can be redirected to the new places. Also, a major reason to depreciate bookend is the availability of amp-story-player where bookend can really be a blocker and may obstruct the regular flow of the stories as they happen on other platforms. All of this holds true for the users visiting the publisher websites where the publisher might implement the widget for stories. 

The major question comes when the users visit the story directly from SEO results and need to visit the organization website or look at more articles. Bookend and sidebars are the most ideal solutions in such a scenario. Also, the bookend helps with offering credits for open-source assets like photos from Unsplash, etc. 

**Solution**
Now, both the arguments of depreciating and continuing these features hold true at their places. So, the best way to solve this will be to allow the users to disable/enable these features depending on where they come from. 

If the user is using a story in amp-story-player, give them an option to pass the attributes ?bookend=off&sidebars=off in the URL while embedding. This way, the users can have a seamless option to have bookends for direct/referral traffic to the story & disable the same while using in amp-story-player

**Comment by Beethoven** [comment]
I agree and I think it should be optional. 
Sidebar is essential to navigate on a Story using branching and to put Social links, terms etc.
Amp Story is a web page in essencial and needs a MENU.

**Comment by newmuis** [comment]
Should we move this conversation to the intent to deprecate issues for the respective components?

> If the user is using a story in amp-story-player, give them an option to pass the attributes ?bookend=off&sidebars=off in the URL while embedding

This was an alternative that was considered.  However, the other question becomes whether it is fair to publishers to allow this type of behavior.  They will likely not have tested their story in that configuration, and it can lead to broken experiences (e.g. if they were expecting the user to be able to navigate via the sidebar) or other problems (e.g. some publishers use bookends for credits; being unaware that the bookend surface could be hidden on some platforms could cause works to go uncredited).

Deprecating bookends and sidebars makes it unambiguous which surfaces will be available across platforms.  Also note that the deprecation does not mean it will not be possible to have bookends and sidebars; it means that their implementation will live on publishers' own platforms rather than within the story document itself.

**Comment by newmuis** [comment]
I see that @Beethoven has left his comment already on #26958.

@ghelapratik, would you mind commenting on #26957 and/or #26958 and closing this issue once you feel you've expressed your opinion on those issues?
