### ISSUE TITLE
Consent Timeout ignored when specifying an attribute on data-block-on-consent

### ISSUE THREAD

**Issue by pedrolopezmrf** [ampproject/amphtml#27220]
## What's the issue?

A component with **data-block-on-consent="_till_accepted"** is not loading after the timeout set up on amp-consent expires. We are using it on an amp-ad type doubleclick and it only works when data-block-on-consent doesn't have a value explicitly specified. According to the docs, the default value is _til_accepted, so it should have the same behaviour.

## How do we reproduce the issue?

Set up an AMP page with a third party CMP (Didomi in our case) and an amp-ad type doubleclick with data-block-on-consent with _til_accepted value. Then:

1. Clear cookies and local storage
2. Wait 5 seconds (timeout specified) and see how the components are still blocked
3. The components will only load after the CMP is resolved.

If you try the same but removing the _til_accepted value, you will see that after the timeout expires, doubleclick handles the request.

## What browsers are affected?

Version 80.0.3987.132

## Which AMP version is affected?

Version 2003031842100

**Comment by micajuine-ho** [comment]
Hi @pedrolopezmrf, thank you for your report. 

The issue here is that you are trying to customize the `_til_accepted_` policy. 

[Right now only customizing the default policy instance is supported](https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/amp-consent.md#customize-consent-blocking-behaviors), where the `default` behavior policy applies to every component that is blocked by consent with `data-block-on-consent` attribute (`data-block-on-consent` == `data-block-on-consent="default"` and these are not the same as `data-block-on-consent="_til_accepted_"`.

Essentially, this means that you cannot attach a timeout value to an element that is blocked with anything but `data-block-on-consent` or `data-block-on-consent="default"`.
