### ISSUE TITLE
Pin AMP Version inside Signed Exchange

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/amphtml#27383]
## Describe the new feature or change to an existing feature you'd like to see

Pin the version of the AMP libraries inside Signed Exchanges. This would help move us toward the goal of removing version locking, and ultimately using ESModules without an intermediary loader.

## Describe alternatives you've considered

Continue allowing for network raciness to load different versions of components, and correct loading on the client after retrieving an incompatible version. This tradeoff means we can reliably ship newer versions of AMP and automatically use them within Signed Exchanges.

## Additional context

The largest concern here is if a stored version of a rtv contains an issue causing a rollback. There is now additional complexity to be resolved by the underlying servers hosting AMP JavaScript payloads, they need an eviction policy and the ability to use an updated rtv from an existing path.

**Comment by choumx** [comment]
One alternative that we discussed briefly in person awhile back was to disable version locking for extensions that have significant performance implications. 

E.g. force amp-list to have a backwards-compatible API across N releases (with extension reloading as fallback). One way to do that is add internal versioning for extensions. :) A bit more painful for AMP engs but should avoid reloading extensions in the critical path for most users.

**Comment by Gregable** [comment]
Specifically, the request involves having the AMP Packager rewrite `v0.js` and all extension `.js` files to use versioned resources, such as:

```
<script async custom-element=amp-analytics src=https://cdn.ampproject.org/rtv/012003261442330/v0/amp-analytics-0.1.js></script>
```

The AMP Packager already has access to the latest RTV, since it is being fetched for CSS inlining. The remaining work would be to add a transfomer to the AMP Packager to rewrite `<script>` URLs similarly, and then to add validation logic in the AMP Cache to verify the RTV values.

Open Questions:

1. @twifkak / @alin04 Can you recall the reasons we selected against version locking in the original version? Were there reasons other than quick revocation?
2. @choumx (?) What should be the policy for which RTVs we would allow? Do we need a way to remove cached SXGs that are still within the expiry window for the SXG (~7 days)?

**Comment by choumx** [comment]
> What should be the policy for which RTVs we would allow? Do we need a way to remove cached SXGs that are still within the expiry window for the SXG (~7 days)?

Yea I think quick revocation is the main concern e.g. stop propagation of RTV with a P0 bug.

**Comment by twifkak** [comment]
An alternative to unversioned runtime in SXG is that the cache would maintain a set of valid RTVs and only ingest/serve SXGs with versions in that set. The main downside of that approach is that revoking a specific version becomes a difficult decision (how many SXGs will this invalidate?) as opposed to an easy one, and we don't want extrinsic factors to impede a revocation decision where possible. The good news is they could still be ingested and served unsigned (and therefore re-transformed).
