### ISSUE TITLE
amp-list: layout=nodisplay does not change to container layout

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#27405]
Given the following amp-list implementation:

```
 <amp-list layout="nodisplay"
            [src]="myList" 
            [is-layout-container]="true"
            items="."
            binding="no">
    <template type="amp-mustache">
      <div><a href="{{url}}">{{title}}</a></div>
    </template>
  </amp-list>
<button on="tap:AMP.setState({
                myList: [
              		{url: 'https://amp.dev', title: 'AMP'},
               		{url: 'https://google.com', title: 'Google'}
                ]
              })">Add list content</button>
```
**Steps to reproduce:** 

paste the snippet into playground.amp.dev and click the button

**Expected behavior:** 

 the list content renders (by changing the layout from nodisplay to container). 

**Actual behavior:**  

the list content is not displayed

Sidenote: this works:

```
  <button on="tap:AMP.setState({
                myList: [
              		{url: 'https://amp.dev', title: 'AMP'},
               		{url: 'https://google.com', title: 'Google'}
                ]
              })">Add list content</button>

  <amp-list layout="fixed" height=0 width=0
            [src]="myList" 
            [is-layout-container]="true"
            items="."
            binding="no">
    <template type="amp-mustache">
      <div><a href="{{url}}">{{title}}</a></div>
    </template>
  </amp-list>
```

**Comment by cathyxz** [comment]
Drive by comment: 

I always thought it was intended behavior to prevent content shifting that you couldn't randomly have an amp-list start as layout no-display, set it to container, and then go display it.... 

In the design for layout-container-without-content-shifting, we had so many discussions, hacks, and ugliness on how to restrict the usage of layout container such that it wouldn't cause layout shifting. But I really don't know what AMP's stance is on content shifting these days anymore, so maybe that's changed? 

In any case, if this feature request truly is intended behavior, it's simple to fix. You can just add layout no-display to the list of layouts that are undone here: 

https://github.com/ampproject/amphtml/blob/b0187b7e1cc3008cdd2368350ba194d2db42d1e8/extensions/amp-list/0.1/amp-list.js#L1231

**Comment by sebastianbenz** [comment]
I don't know how this would cause (unintended) content shifting. The container layout would only be applied after user interaction.

**Comment by caroqliu** [comment]
Based on the definition of [nodisplay](https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/control_layout/#supported-values-for-the-layout-attribute), this FR sounds borderline to me:

> It’s assumed that the element can display itself on user action, for example, amp-lightbox.

On one hand, the amp-list should be able to display itself according to this description, but on the other hand `amp-lightbox` is a special case wherein the display doesn't actually cause content shift. 

Based on the recent change that added support to `layout=container` by locking height and only attempting to resize (rather than forcing it), an amp-list going from `layout=nodisplay` to `container` wouldn't even resize if there is content to be shifted below it. So this should be a safe change to make.
