### ISSUE TITLE
I2I: Allow amp-animation in the amp-story format

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#27420]
## Summary

The proposal is to allow amp-animation extension to be used for amp-story-page entry animations.

## Motivation

[Web Animations API](https://drafts.csswg.org/web-animations/#animatable) is a powerful tool. Some use cases can be expressed better using this API and it also allows a more fine-tuned control over the animation lifecycle. In AMP this API is mainly exposed via [amp-animation](https://github.com/ampproject/amphtml/blob/master/extensions/amp-animation/amp-animation.md) extension. This I2I proposes to allow amp-animation use for amp-story "enter" animations.

## Design document

The usage will roughly look like this:
```
<amp-story>
  <amp-story-page>
    <amp-animation trigger="visibility">
       ...
    </amp-animation>
  </amp-story-page>
</amp-story>
```

Constraints:
 1. Only one `amp-animation` with `trigger=visibility` will be allowed initially. We may allow more later. Other `amp-animation` elements (without `trigger=visibility`) are allowed because they can be used for composition.
 2. The `amp-animation` must be a direct child of `amp-story-page`. Either required or recommended placement for `amp-animation` is at the bottom: close to the `</amp-story-page>` given that the animation spec is not render-blocking.
 3. The animation's root will be limited to the parent `<amp-story-page>`. This means that the `amp-animation` will only be able to involve elements that are included on the page: both for transitions and for composition.
 4. The story page will replace `amp-animation`'s controller. More on this below.
 5. Stretch goal/optional/TBD: allow `<style amp-keyframes>` at the bottom of a `<amp-story-page>`.

### amp-animation controller for amp-story-page

The story page has to be have a more fine-level control over amp-animation lifecycle.

Currently amp-animation exports the following relevant actions:
 - start
 - restart
 - pause
 - resume
 - finish
 - cancel

Currently, the `trigger=visibility` animation automatically controls these actions. This proposal requires a new feature to be added to the `amp-animation`. Instead of self-controlling its state via these actions, the `amp-animation` will ask the story page to control.

Exactly what it looks like is TBD. It could look like this:

```
class AmpAnimation {
  ...
  if (trigger === 'visibility')  {
    if (parentController) {
      parentController.controlAnimation(this);
    } else {
      // current behavior
    }
  }
}
```

## Launch tracker

No special launch tracker is required.

/cc @ampproject/wg-approvers
/cc @ampproject/wg-stories

**Comment by newmuis** [comment]
This has been on our backlog forever!  Thanks for driving this @dvoytenko!

/cc @gmajoulet who's the best person to work through the technical details of the `amp-story-page` integration here.  Limiting the API to be per-page seems right to me.

**Comment by pbakaus** [comment]
all of the proposal makes sense to me. I'm wondering, are there classes of animations that you won't be able to do with just one amp-animation that triggers on visibility?

Also: Might be too early, but you should consider that page transitions will be a thing down the road, and think about how that would potentially look like - nothing to implement right now I guess, but worth to keep in mind (could be as simple as trigger="navigation").

**Comment by newmuis** [comment]
Also FYI that pages are sometimes visible on screen without being "active" (the page that the user is on).  For example, in the 3-panel desktop UI, the next and previous pages are also in the viewport.  Even in the full-bleed mobile UI, the next page is technically in the viewport (behind the current page, on the z-axis), as a performance optimization.

**Comment by pbakaus** [comment]
> Also FYI that pages are sometimes in the viewport without being "active" (the page that the user is on). For example, in the 3-panel desktop UI, the next and previous pages are also in the viewport. Even in the full-bleed mobile UI, the next page is technically in the viewport (behind the current page, on the z-axis), as a performance optimization.

good point, mabye calling it "activation" or "foreground" might be better than "visibility".

**Comment by dvoytenko** [comment]
IMHO, semantically, "visibility" is still ok. The visibility is defined by the story-page to be whatever it thinks it is.

**Comment by dvoytenko** [comment]
But if that seems too far, we can always call it `trigger=enter`.

**Comment by newmuis** [comment]
These all SGTM; my intent wasn't to bikeshed the name but make sure that the implementation takes that detail into account

**Comment by gmajoulet** [comment]
Thanks for getting together this I2I Dima!!
I'm also very excited about improving Stories animations.

One comment about the `amp-animation` controller: Stories already have some code that create some `amp-animation` compatible (Web Animations) code, and runs it with the `amp-animation` internal runners.
Rather than creating a new controller, it would be great if we could pipe the publisher provided `amp-animation` configuration into the existing "Animation Manager" that is already handled by each `amp-story-page`.

We have a lot of logic to play/pause/rewind/finish instantly animations based on different heuristic, and improving our existing Animation Manager to make it the new described controller would make things easier.
But that's mostly an implementation detail.

Happy to help with prototyping this, or with code pointers. :))

**Comment by alanorozco** [comment]
Update from a conversation with @dvoytenko and @gmajoulet.

### Implementation

- `<amp-animation>` will inspect the tree and bail out from building itself when inside an `<amp-story-page>`. Whatever `amp-animation` does that's necessary for this feature to work in `<amp-story>` will be refactored/exposed in the async [`WebAnimationService`](https://github.com/ampproject/amphtml/blob/b53a65af9ba8235a3a8881cc03e57e496ea41ede/extensions/amp-animation/0.1/web-animation-service.js#L20) that's already used.

- This allows the same one-way data flow from `amp-story` to `amp-animation` using the [`AnimationRunner`](https://github.com/ampproject/amphtml/blob/27b46b9c8c0fb3711a00376668d808f413d798ed/extensions/amp-story/1.0/animation.js#L74) like with [`animate-in` and friends](https://amp.dev/documentation/guides-and-tutorials/start/visual_story/animating_elements/).

- Story animation presets [are provided with calculated dimensions](https://github.com/ampproject/amphtml/blob/27b46b9c8c0fb3711a00376668d808f413d798ed/extensions/amp-story/1.0/animation.js#L159), which `amp-animation` will now consume:
  - `vw/vh` units will be relative to story page dimensions, like they already are in author-defined `amp-story` CSS.
  - [`width()/height()` extensions](https://amp.dev/documentation/components/amp-animation/#css-width()-and-height()-extensions) can already be used for element dimensions.
  - Element's `x` and `y` coords need to be exposed either via extensions or custom props.

- Elements from selectors in an `<amp-animation>` configuration need to be scoped per `<amp-story-page>`, for which the animation tools exposed from the former will be able to take a `scopeElement`.

### Current action items

- I'll implement a proof of concept for `amp-animation` inside an `amp-story-page` to figure out missing details, additional features for full support will come later.

- For sanity/consolidation: Use `width()/height()` extensions in [presets](https://github.com/ampproject/amphtml/blob/c4a663d0ba13d0488c6fe73c55dc8c971ac6ec0d/extensions/amp-story/1.0/animation-presets.js#L89).

### Open questions

- Problems can arise from supporting [`<style>` tags for keyframes like `amp-animation`](https://amp.dev/documentation/components/amp-animation/#keyframes-from-css). Postponing for now and only supporting JSON.

- Because of supported configuration combinatorics, it's up for debate whether the ideal API for this should be isolated somehow, like using a new `<amp-story-animation>` tag, or a different `trigger`. This is a different concern than implementation and its decision can be postponed (Personally I don't have a strong opinion 🙂)

**Comment by gmajoulet** [comment]
SGTM, thanks Alan! :)

> it's up for debate whether the ideal API for this should be isolated somehow, like using a new <amp-story-animation> tag, or a different trigger

What really matters is (1) your first bullet point "_amp-animation will inspect the tree and bail out from building itself when inside an amp-story-page_" and (2) the validation rules to ensure that it either works or is invalid.
Whatever allows you to optimize for these two sounds good to me 👍

**Comment by alanorozco** [comment]
@gmajoulet The [working implementation](https://github.com/ampproject/amphtml/pull/27597) doesn't even traverse since it assumes validation. In any case, we can define this as direct `amp-story-page` descendant, which is just a `parentNode` comparison.

Structurally, it seems to me like when the visibility concern is removed from `amp-animation` all it does is wrap configuration, so changing that to `amp-story-animation` or w/e is still basically free. TL;DR: idc

**Comment by dvoytenko** [comment]
From the chat today:

There's one more nuance that might be worth considering right away. It's the animation referencing.

We currently allow subanimations inside <amp-animation> to reference another <amp-animation> by ID. That works a bit like a function call. And could be generally very useful for repeating effects. I'm not sure if we want to now do amp-story-animation -> amp-story-animation. If we do, we'll need to block the one that's only used as a subanimation. Alternatively, we could expand our JSON slightly and allow a sub-animation to me declared there. Then, amp-animation builder would work like this:

includeSubAnimation(id):
 1. Look for a locally defined subanimation with the id in the `configJson.subanimations[id]`
 2. If not found, do `getElementById(id).configJson`

Not entirely clean, but not too bad, i think. This is described here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-animation/amp-animation.md#animation-composition

Not sure I'm very bothered yet by the `<amp-story-animation trigger="visible">` or `<amp-story-animation do-not-run>` sort of thing. But definitely something to keep in mind if we want to drop `trigger=visible` or make it more meaningful for stories, yet not lose the ability to reuse animation declarations.

**Comment by dvoytenko** [comment]
@alanorozco To clarify: are we all done here? Is it on the way to Beta/Stable as launched?

**Comment by gmajoulet** [comment]
@alanorozco do you have an update on the documentation conversation? Thanks!
