### ISSUE TITLE
Feature Request: `amp-table`

### ISSUE THREAD

**Issue by jamespacileo** [ampproject/amphtml#2745]
It would be ideal to have an AMP optimised table element.

Optimising tables for mobile is quite tricky and often the quickest solution is to eliminate these entirely from AMP pages.

**Comment by rudygalfi** [comment]
@jamespacileo Can you give some examples of optimizations you'd like to see in an `amp-table` component?

**Comment by ayrtoncz** [comment]
+1 for this feature from our team. We're now trying to put tables to amp-carousel and it's not optimal.

**Comment by rudygalfi** [comment]
Is the challenge with horizontally scrolling a table that needs more width than the viewport width?

cc @ericlindley-g

**Comment by jamespacileo** [comment]
That would definitely be a usecase 🙂 do you have something already for
this scenario?

**Comment by ayrtoncz** [comment]
@rudygalfi Yes, exactly. Today the only way to insert a table to AMP is to put it into amp-carousel and that's not optimal. You have to know the height of your table etc, which is a challenge in dynamically created content.

**Comment by ericlindley-g** [comment]
@jamespacileo @ayrtoncz 

I'm not aware of anything tailored for this case right now — do you have a non-AMP example you could link to, in order to have a concrete use-case (and an example of a good treatment on mobile) to work with?

**Comment by darobin** [comment]
Here is an example with both AMP and non-AMP versions. (The site is still experimental, please don't read _too_ much into the whole thing.) Our input is pretty arbitrary documents, and they often contain tables, some of which can be pretty large.

With the [non-AMP version](https://research.science.ai/on-the-marginal-cost-of-scholarly-communication), tables (you can find one right before the "Infrastructure Cost" section) will have horizontal scrolling without causing the page to scroll, and their caption will remain fixed as the table scrolls. (We plan on also adding shadows to indicate that there is table to be scrolled.)

With the [AMP version](https://research.science.ai/amp/on-the-marginal-cost-of-scholarly-communication), since we can't use `overflow: auto` the table is truncated. Alternatively we could degrade the whole experience by having the whole page scroll horizontally. Or we could look at hacks with `amp-carousel` or `amp-iframe`. None of that is really attractive.

**Comment by darobin** [comment]
So, having mulled this over I would be happy to take a stab at implementing this, but I'd like to make sure there's interest in the same functionality I'm interested in and hash out a few details first.

There is an [existing proposal for sortable tables](https://docs.google.com/document/d/11PGu3UO9kWPHYUKhI7PRdT73KR-J_1-A_hIqdmwkrMU/edit#heading=h.5wolfmbudvy3) but I think that's different. Sortable tables are regular (no colspan or rowspan, consistent types per column, typically vertical orientation, single-level headings, etc.) whereas arbitrary tables can have all of these. Trying to scale a sortable tables element to support any kind of crazy table would likely prove very counter-productive for everyone.

If we had `amp-table` it would wrap and _not_ replace HTML `table`. The HTML parsing rules for `table` and its content element (`"in table mode"`) are _very_ specific, so that if we wanted to replace `table` with `amp-table` we would likely also need to have `amp-tr`, `amp-td`, `amp-tbody`… None of that seems necessary or desirable.

The way I see this component working is basically that it would have a fixed height (being the "natural" height of the table it wraps — that ought never to change) and a width that is either fixed or fills the parent container. Then the table wrapped inside of it would be overflow-scrollable (from what I gather reading the carousel source, that is acceptable in the `amp-*` world, when it can't be avoided). Possibly we could add the nice touch of a scroll shadow (here is [one technique](http://lea.verou.me/2012/04/background-attachment-local/)).

This leads me to the conclusion that it is not so much an `amp-table` that is needed here but rather a more general `amp-horizontal-scroller`? Then again, it might be desirable to restrict to table content (because it's absolutely required there) to avoid abuse of the element.

WDYT? Happy to start hacking on this.

**Comment by ericlindley-g** [comment]
Thanks @darobin — at first glance that sounds good (and is very similar to what some folks on the core team have been thinking), but we should get more input from the team before committing. 

Some key voices for this one are away for winter holidays, but we can circle back next week to discuss. In the meantime, if you want to describe your solution in a bit more detail, you can open up an "Intent to Implement" for amp-horizontal-scroller.

**Comment by darobin** [comment]
@ericlindley-g I filed a PR directly (because the implementation is simple), do you reckon I need to also open an "Intent to Implement" issue? Or could this one be so labelled?

**Comment by rudygalfi** [comment]
@ericlindley-g Since you've been looking at this most recently, shifting this over to you.

**Comment by salcan** [comment]
Sorry, so what's the resolution here (if there was one)? Best practice would be to use amp carousel in place of a table?

**Comment by ericlindley-g** [comment]
My understanding is that the current best practice is to drop the table into an amp-carousel type=carousel to support scrolling sideways. The drawback is that the height has to be specified explicitly. Would that work for your use cases?  (if not, there's a feature request out to support container layout for amp-carousel, which would make it possible not to specify height explicitly in carousels—let us know if you would need that)

Long term there's a project underway (referred to as "layers") that will solve some of the resource management issues that come with side-scrollable elements, and I believe will support overflow-x scrolling when it's finished ( @jridgewell , is that the case, or do I have some of this wrong?)

/cc @aghassemi and @camelburrito in case there are additional details or other options here

**Comment by jridgewell** [comment]
Layers will indeed support side scrolling with any element.

**Comment by salcan** [comment]
@ericlindley-g Thanks. That's exactly what I did. Specifying height wasn't an issue in this situation but might be an issue down the road. I'm not at the point yet though. 

Is there any reading I can do on layers yet, or is it still too early?

**Comment by ericlindley-g** [comment]
Great! Glad you got it working — I'll defer to @jridgewell for details on layers

**Comment by mitchellkrogza** [comment]
I stumbled across this after just activating AMP on one of my sites today. Unfortunately one of my most popular posts which uses a table does not display the images in the AMP version of the page. Can anyone assist me in rectifying this? The non AMP page is: https://www.environment.co.za/weeds-invaders-alien-vegetation/alien-invasive-plants-list-for-south-africa.html and I use a plugin called TablePress to generate the table.

**Comment by salcan** [comment]
@mitchellkrogza Sounds like you might have a TablePress problem, not an AMP problem? I checked out [the page](https://www.environment.co.za/weeds-invaders-alien-vegetation/alien-invasive-plants-list-for-south-africa.html/amp) and it looks ok, just doesn't scale too well. 

I have a test carousel table setup here on this [Coffee Scale](https://coffee-scale.com/index.amp.html) page. Might be worth a shot?

**Comment by mitchellkrogza** [comment]
Thanks @salcan I’ll check that out in the morning :+1:

**Comment by rbeckstead** [comment]
Has there been a viable solution for the situation with AMP tables or carousels?

**Comment by ericlindley-g** [comment]
Nothing new since the last update. unless @jridgewell has an update on the layers work, which should solve the problem without the need for a workaround. if not, I believe the current route is to drop tables into amp-carousel type=carousel, with the requirement that height has to be explicitly defined (can use media queries to change behavior based on viewport width).

**Comment by brandonmcconnell** [comment]
This styling could be added to the amp-custom css block. However, the AMP team locally resolves this issue building upon the lightweight CSS framework Basscss which natively supports this functionality using their overflow-scroll class. Hope this helps!
**Basscss:** http://basscss.com/
**Basscss tables:** http://basscss.com/v7/docs/base-tables/

**Comment by ericlindley-g** [comment]
Thanks @brandonmcconnell !   I should caveat that: my experience is that left-right scrolling is intercepted by AMP viewers (for example, the AMP viewer when viewing an AMP document from Google Search). This means that containers scrolling on the x-axis can't be scrolled by the user. Have you tested in this context?

**Comment by aghassemi** [comment]
Thanks for sharing @paulrobillard!

**Comment by michaelprflores** [comment]
@paulrobillard this is quite wonderful. Thank you!

**Comment by ilkxeren** [comment]
+1 on this! Much needed. (necessary) tables on mobile are the worst.

**Comment by rrjanbiah** [comment]
@aghassemi @darkbluewalrus

As @paulrobillard account is currently not available, his comment is not available here. Do you remember his solution and possibly share them again? TIA
