### ISSUE TITLE
amp-link-rewriter : Add PAGE_VIEW_ID and CLIENT_ID(AMP_ECID_GOOGLE,,_ga)

### ISSUE THREAD

**Issue by peraltaf** [ampproject/amphtml#27548]
We use a concatenated value of CLIENT_ID(AMP_ECID_GOOGLE,,_ga) and PAGE_VIEW_ID to tie page traffic and ad impressions in both amp-analytics and amp-ads respectively. We want to utilize this concatenated value inside amp-link-rewriter so we can view downstream traffic from our merchant links but CLIENT_ID(AMP_ECID_GOOGLE,,_ga) and PAGE_VIEW_ID are not available in amp-link-rewriter. This is a request to add CLIENT_ID(AMP_ECID_GOOGLE,,_ga) and PAGE_VIEW_ID macros to amp-link-rewriter.

**Comment by zhouyx** [comment]
Hello @peraltaf, Can you please explain your use case a bit more. 
`<amp-link-rewriter>` is designed for affiliate links, that's why we don't allow passing user ids like clientId and pageViewId.
If you want to pass ids to your own site, `<amp-analytics>` linker may be the better option. 
https://amp.dev/documentation/components/amp-analytics/#linkers

**Comment by peraltaf** [comment]
We do use amp-analytics and amp-ads to pass the concatenated value of CLIENT_ID(AMP_ECID_GOOGLE,,_ga) and PAGE_VIEW_ID currently. We use this concatenated value as a unique value to tie the page and ads together for analysis. We have affiliate links on our AMP pages and we're working with a vendor to pass this as a variable for them to capture. Our goal is to provide a complete view of our commerce funnel, including the origin and merchant funnel. Without CLIENT_ID(AMP_ECID_GOOGLE,,_ga) and PAGE_VIEW_ID in amp-link-rewriter we can't get at that analysis since we won't know where a purchase may have originated from.

**Comment by zhouyx** [comment]
Thank you @peraltaf 
I'm still not convinced that we should pass user id to affiliate links because it's passing user id to third party sites. 

When you say: "since we won't know where a purchase may have originated from",
you're referring to the site where the user make the purchase? Do you own the merchandise site as well? If so then analytics linker is definitely the feature to use.

**Comment by peraltaf** [comment]
We don't own the merchant sites so analytics linker is out of the picture. It may help to jump on a call to hash through this but here's our entire workflow on Desktop and Mobile Web (non-AMP) that we're trying to recreate on AMP:

- We have a variable that we call view GUID that is captured on our analytics and ad calls. This view GUID is unique to each page view so we can tell which specific ads were displayed to each individual page view. 

- We've partnered with a vendor that allows us to view the purchase funnel once a user clicks out of our site from a merchant link. 

- This vendor allows custom variables to be passed to them so we pass the view GUID on each click out from these merchant links.

- The vendor keeps track of that view GUID throughout the purchase funnel.

- With this setup we now have a visibility on the complete purchase funnel from initial impression, to the click, to the lifecycle of the purchase on the merchant site.

On AMP we use the CLIENT_ID(AMP_ECID_GOOGLE,,_ga) concatenated with PAGE_VIEW_ID using a | as a proxy for view GUID. Similar to our Desktop implementation we pass this proxy view GUID to both our analytics and ad calls. We have merchant links on our amp pages and we want to pass this proxy view GUID to the merchant links in amp-link-rewriter.

Like I mentioned, we're happy to jump on a call to hash this out since it is a blocker for us internally.

**Comment by zhouyx** [comment]
Thank you for the detailed workflow. I prefer using analytics linker because you're passing the id to the vendor, not to the merchant site. And I'm trying to avoid adding `CLIENT_ID` to `<amp-linker-rewriter>` because it's not required in the generic affiliate link usage.   

One thing to clarify: analytics linker allows you to define the allowed destinationDomain, so it is still possible pass the value to the merchant site. https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/linker-id-forwarding.md#format

Another option is to use the `data-amp-addparams` to append CLIENT_ID and PAGE_VIEW_ID to the outgoing urls. 

Would any of the above options work?

**Comment by peraltaf** [comment]
Sorry for the delay. I gave both options to the team and they've been working on trying to implement analytics linker however it's not working. Below is from our internal ticket system:


here's what the code looks like for analytics call 
```
{
  "requests": {
      "omniturePageview":"https:\/\/trackingserver.com\/b\/ss\/reportsuiteid\/0\/amp-1.0\/s${random}?v24=CLIENT_ID(AMP_ECID_GOOGLE,,_ga)|PAGE_VIEW_ID&…",
  }
}
```
That outputs a guid like: "amp-OAt4rCnQUfUtQAtQa_ujPA|5965".

Here's the linkers code:
```
"linkers" : {
    "guid": {
        "ids" : {
            "client_id": "CLIENT_ID(AMP_ECID_GOOGLE,,_ga)",
            "page_view_id": "PAGE_VIEW_ID"
        },
        "destinationDomains": ['*'],
        "proxyOnly" : false,
        "enabled": true
    }
}
```

That outputs a guid like: "?guid=1*1oov1f0*client_id*YW1wLU9BdDRyQ25RVWZVdFFBdFFhX3VqUEE.*page_view_id*NTk2NQ.."
 
Also, I'm not seeing the value being converted when I try passing the guid via data-amp-addparams
```
<a href="https://amp.trackonomics.net" data-amp-addparams="guid=CLIENT_ID(AMP_ECID_GOOGLE,,_ga)|PAGE_VIEW_ID">amp.trackonomics.net</a>
```
It just creates a url like this: https://amp.trackonomics.net/?guid=CLIENT_ID(AMP_ECID_GOOGLE%2C%2C_ga)%7CPAGE_VIEW_ID.

**Comment by peraltaf** [comment]
@zhouyx Any suggestions?

**Comment by zhouyx** [comment]
Apology for the late response. 

Linker
That's expected, AMP doesn't append the raw user id to the query param, instead the value is encoded. Please refer to the doc [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/linker-id-receiving.md) to decode it on the receiving side. 

data-amp-addparams
A variable need to be specifically allowed to be passed as params. Please add `data-amp-replace="CLIENT_ID"` attribute as well. 

Thanks
