### ISSUE TITLE
Design Review 2020-04-08 20:00 UTC (Connatix Story Player, AMP testing & release quality, wg-performance)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#27599]
Time: [2020-04-08 20:00 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2020&month=04&day=08&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20200408T200000Z/20200408T210000Z&details=https%3A%2F%2Fbit.ly%2Famp-dr))
Location: [Video conference via Google Meet](https://bit.ly/amp-dr)

The AMP community holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc or issue by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by rares-mihai-preda** [comment]
This would be a good time to review I2I #26593 for AMP Connatix Story Player Extension which is accompanied by PR #26592

Also the readme file is here: https://github.com/ampproject/amphtml/pull/26592/files#diff-1b12adef7d797a93b20c711c800d388a

/cc @alanorozco

**Comment by rsimha** [comment]
I'd like to use ~30 mins to discuss AMP testing and release quality. Instead of being accompanied by an I2I issue, this will be an open conversation about ways in which we can drive improvements.

**Comment by kristoferbaxter** [comment]
cc @ampproject/wg-ui-and-a11y for "Connectix Story Player Extension"

**Comment by mrjoro** [comment]
The Performance Working Group will be presenting their periodic updates at this Design Review (10-15 minutes).

/cc @ampproject/wg-performance @kristoferbaxter

**Comment by rsimha** [comment]
### Connatix Story Player - Led by @rares-mihai-preda

@dvoytenko Why can't this be an iframe?
- Extension relies on communication between what's inside and outside the iframe. Eg: changing aspect ratio. Not sure this can be done with an existing AMP component.

@kristoferbaxter This looks like we're adding a new extension that can be an iframe. What if there were a way to create such a component with just an iframe. Would that suffice?
- We don't use anything special other than a way to close the component, so this may be okay.

@cramforce We don't want to miss the branding part of this I2I, so it is worth considering creating a mechanism to support branded content via a custom element. We may already have such a mechanism.

@kristoferbaxter We shouldn't have to create a custom element for each kind of content, or else it will become unweildy to maintain this code, tests, etc. We've noticed that several extensions don't have authorship after a while, which increases the maintenance burden. Therefore, we should make this a generic solution instead of a one-off extension.

@cramforce Video players are supposed to have the same interface, so we can do things like hide / show controls, etc. There is a generic video player component which may be usable for this case.
- This is not a video player, but is a "story player", which shows rich interactive content (and not just videos).

**Action items:**
- @kristoferbaxter and @alanorozco to investigate a way to create this via existing generic AMP components, figure out what is missing, and consider adding it. This way, we can support a branded component name without the burden of a whole new component implementation.

**Comment by kevinkimball** [comment]
# Discussion: AMP Testing and Release Quality 
* Wanted to share thoughts about how the AMP dev team has been thinking about this topic with the community
* Ship to four channels a week
## Overview of test coverage today
* Integration tests: doesn’t cover different real-world serving modes 
* E2E tests: do cover real-world serving modes (but slow) 
* Visual diff:  disadvantage is that it doesn’t cover animations, jank
* Cross-browser is covered by integration and visual diff tests 
* Code coverage percentage is informational only 
* Manual QA has been covered for about 18 months 
## What works  (see slides) 
## What doesn’t work 
* No systematic way of enforcing coverage for new features 
* Only one test for IE11 even though we have infra and publishers are making money from users on that browser 
* Manual test matrix is hard to update to reflect new components/ interactions 
* Lots of cherry-picks happening = failure of existing testing 
## Ideas on how to improve 
* Compilation checks could also benefit bundle size
* One-time push could be advantageous but over time revert to the mean 
* Code coverage should not get worse (add blocking checks to coverage) 
* Test engineer may not be feasible 
* Better instructions/documentation for contributors (do we want E2E for all new features?) 
* Different tiers of coverage (internal/external?) to maximize use of CI resources 
* Convert manual tests to E2E tests (leveraging Storybook)
* Manual test plan a requirement for shipping a feature (could be converted to E2E later) 
* Add “death dates” attached to specific functions to enforce deprecations (cannot submit code using the function after that date) 
* Challenge:  we want tests to use Closure compiler-minified code that we serve to end users, so we run the tests outside the process and load the minified bundle. How to do code coverage on this? Unique challenge 
* Some kind of check would be helpful. Could leverage work into the bundle size checker to establish levels. 
* Too many exceptions to the existing checks, could be topic for a fix it 
* Could test strategy be contracted out to a vendor? 
  * Storybook could make this simpler. 
  * Expertise vs. resources deficiency. Could hire a vendor to train the team on the skills needed also. 
  * Drawback could be still no one is looking at this full time. Would benefit from full-time view 
* Can we collect coverage percentage from unminified code while testing with minified code? 
  * To rephrase the question: If an HTML page serves JS, is there a way to determine how many lines of JS run on that page? 
  * V8 code coverage tools could enable

**Comment by mrjoro** [comment]
@kristoferbaxter can you provide a link here to the wg-performance update, and add it to the [WG updates page](https://github.com/ampproject/meta/wiki/Working-Group-Updates)?
