### ISSUE TITLE
WP: SSO in comment box stuck at "Connecting to <provider>" after sign-in

### ISSUE THREAD

**Issue by TinusLorvalds** [ampproject/amphtml#27645]
**Please only file reports about bugs in AMP here.**

- If you have questions about how to use AMP or other general questions about AMP please ask them on Stack Overflow under the AMP HTML tag instead of filing an issue here: http://stackoverflow.com/questions/tagged/amp-html
- If you have questions/issues related to Google Search please ask them in Google's AMP forum instead of filing an issue here: https://goo.gl/utQ1KZ

If you have a bug for AMP please fill in the following template. Delete everything except the headers (including this text).

## What's the issue?

When I am trying to login on iOS to add a comment using Google or Twitter I am stuck at the Connecting to … screen after I logged in at Google or Twitter and allowed the connection.

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Go to any post site on paulreno.de using iOS Safari and try to add a comment
2. Sign in using Google or Twitter
3. Wait until forever at the Connecting to … screen

## What browsers are affected?

Safari on iOS

## Which AMP version is affected?

AMP Version 1.5.2

**Comment by Ichigo3d** [comment]
Hi, this bug is reproducible.
Title:
Infinite logging to Google or Twitter account for posting of comment on website www.paulereno.de (Safari IOS)
Preconditions:
verify that you on production 

Steps to reproduce:
1) Got to site www.paulreno.de
2) Open any article
3) scroll down until comment text box
4) Tap on icon Google or Twitter
5) Login to the account Google or Twitter
6) Observe result
Expected result: Login is should finished fast and redirect user to comment page
Actual result: Login to Google or Twitter account got stuck in infinite loading. 
Environment:
Safari IOS ver. 12+
IOS ver.12+
Attachments:
![IMG_3879](https://user-images.githubusercontent.com/37351864/79003020-8fc08300-7b06-11ea-8834-63880fdb311e.jpg)

**Comment by choumx** [comment]
@westonruter Is there a process for forwarding WP plugin issues other than tagging you? :)

**Comment by westonruter** [comment]
You could transfer the issue to https://github.com/ampproject/amp-wp perhaps.

But I believe this is actually an issue with Jetpack's comments module and not AMP or the AMP plugin. The AMP plugin has no such functionality to post comments via authentication with some provider. I suggest opening the issue on Jetpack's support forum: https://github.com/Automattic/jetpack

**Comment by choumx** [comment]
Thanks Weston.
