### ISSUE TITLE
Add Sourcemap "golden" tests

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#27681]
## Describe the new feature or change to an existing feature you'd like to see

Unfortunately, we're getting frequent breaks in our Sourcemap pipeline. Either the source locations are incorrect because we forget to propagate, or a part of the pipeline destroys the information.

@choumx suggested maybe we could create golden tests for our sourcemap pipeline. Meaning, we'd use our latest code in `build-system/` to compile a known commit of AMP (eg, `c106206e169d3ce14a83faaa0a29b92e6dd00c76`). That way, if any change in our build process causes a change in the sourcemaps, we'll be alerted.

**Comment by choumx** [comment]
Could also do the same thing for select JS binaries as a regression test for our increasingly complex transform/compile pipeline.

/cc @ampproject/wg-infra

**Comment by rsimha** [comment]
> Meaning, we'd use our latest code in `build-system/` to compile a known commit of AMP (eg, `c106206e169d3ce14a83faaa0a29b92e6dd00c76`). That way, if any change in our build process causes a change in the sourcemaps, we'll be alerted.

This is technically possible today via a new `gulp` task that rolls `amp.js` back to a known commit, runs `gulp dist --core_runtime_only`, and diffs the resulting `v0.js` and `v0.map` files against their golden file equivalents.

However, my concern is that this will require constant manual updating of the golden file versions as new versions of closure compiler get released, and new babel transforms are added. (Today, closure updates are tested by renovate, and can be trivially merged if all tests pass. This will require us to update the golden version each time.)

@choumx @jridgewell Your thoughts?

**Comment by rsimha** [comment]
I tried comparing https://github.com/ampproject/amphtml/commit/c106206e169d3ce14a83faaa0a29b92e6dd00c76 and `master` (https://github.com/ampproject/amphtml/commit/c083d2c6120a251dcc9b0beb33c0336c7d3ca5a8) and found numerous diffs in the minified output for the core runtime, making it hard to tell which ones are undesirable.

![image](https://user-images.githubusercontent.com/26553114/79275842-ea464000-7e74-11ea-9041-d988c371f3ed.png)

Instead of checking out a known commit of AMP (which will require re-running `yarn` before compilation tasks can be invoked, what if we create a `sourcemaps-test.js` file on which we run the outermost layer of our compilation toolchain?

**Comment by jridgewell** [comment]
> However, my concern is that this will require constant manual updating of the golden files as new versions of closure compiler get released, and new babel transforms are added.

This is intentional, since any of these changes could cause an issue with sourcemaps.

> I tried comparing c106206 and master (c083d2c) and found numerous diffs in the minified output for the core runtime, making it hard to tell which ones are undesirable.

We only care about the map output here, and that [comparison](https://github.com/ampproject/amphtml/compare/c106206e169d3ce14a83faaa0a29b92e6dd00c76...c083d2c6120a251dcc9b0beb33c0336c7d3ca5a8) includes my sourcemap path fixes.

> Instead of checking out a known commit of AMP (which will require re-running yarn before compilation tasks can be invoked

I don't think this will yarn will be required for the most part. We should be able to do `rm -rf src; git checkout KNOWN_SHA -- src/` and get a fully working source directory at a known commit. Then, run though `gulp dist --core_runtime_only`, and we can verify the current `build-system/`'s compilation correctly generates the sourcemaps.

> what if we create a sourcemaps-test.js file on which we run the outermost layer of our compilation toolchain?

Unless it runs through every part of the compilation, I'm not sure this is enough. Is needs to be significant enough that it hits multiple babel-plugins (pre and post), and through closure.

**Comment by cramforce** [comment]
I proposed in the other thread to simply check if a sentinel string in the input source can be mapped to the correct source info on the output source. I think that should provide decent coverage and would not be subject to stable compilation.

**Comment by rsimha** [comment]
> This is intentional, since any of these changes could cause an issue with sourcemaps.

I'm fine with developers having to update the golden file for deliberate changes to babel transforms. However, I am against adding an additional step for every closure compiler update, since it will add a manual step to what is mostly an automatic process.

@jridgewell If https://github.com/ampproject/amphtml/issues/27681#issuecomment-613712669 is indeed sufficient, we can do so without a golden file as follows:
- Add a new `gulp check-sourcemaps-url` task that does the following
- Determine the tag of the latest stable release `LATEST_STABLE` by inspecting https://github.com/ampproject/amphtml/releases/latest
- Invoke `gulp dist --core_runtime_only --full_sourcemaps --version_override=LATEST_STABLE` (this tests `build-system/` code from `HEAD`, but is expected to point to a known-good sourcemaps URL)
- Ensure that `v0.js.map` ends with `"sourceRoot":"https://raw.githubusercontent.com/ampproject/amphtml/LATEST_STABLE/"`
- Ensure that this URL resolves correctly: https://raw.githubusercontent.com/ampproject/amphtml/LATEST_STABLE/src/amp.js

Would this work?

**Comment by rsimha** [comment]
I took a stab at writing up a simple sourcemaps content check by extracting source code from `v0.js.map` and comparing the contents of the extracted `amp.js` with `src/amp.js`. WIP branch is [here](https://github.com/ampproject/amphtml/compare/master...rsimha:2020-04-14-CheckSourcemaps). Right now, there are a few whitespace / const string changes, but the files are otherwise the same. Let me know if this approach is worth pursuing for a sourcemap content check.

![image](https://user-images.githubusercontent.com/26553114/79293109-cdbffd00-7ea0-11ea-8099-8d2a68b4229b.png)

**Comment by jridgewell** [comment]
We could parse the original and parse the output. If the AST trees match, then they're equivalent.

We also need to do basic assertions on the `sources` array in the map, but I think this is a good direction.

**Comment by rsimha** [comment]
> We could parse the original and parse the output. If the AST trees match, then they're equivalent.
> 
> We also need to do basic assertions on the `sources` array in the map, but I think this is a good direction.

SGTM. I've added a rudimentary AST comparison to #27795 and marked it as ready for review. There still are diffs between the ASTs that should show up in the Travis logs. Let's continue this discussion in the PR comments.

**Comment by rsimha** [comment]
Update: The AST comparison was found to be insufficient because it was based on extracting the `sourcesContent` field from `v0.js.map`, and not the `mappings` field. Back to the drawing board for this.

Meanwhile, I've reduced #27795 to just a sourcemap URL check, which has some non-zero value.

**Comment by rsimha** [comment]
I found a way to implement the suggestion in https://github.com/ampproject/amphtml/issues/27681#issuecomment-613712669.
