### ISSUE TITLE
404 error on browser back button

### ISSUE THREAD

**Issue by abeak** [ampproject/amphtml#27691]
## What's the issue?

When I go back to the AMP page by pressing the back button on the browser, the 404 error page sometimes comes up.

![Image from iOS (1)](https://user-images.githubusercontent.com/23374791/78960731-e1c6d000-7b29-11ea-93ff-b70a34034015.png)

## How do we reproduce the issue?

1. Open the AMP page
2. Press the link in the AMP page
3. Press the browser's back button

The issue occurs when I repeat steps 2 and 3.

It has been confirmed that it occurs on multiple sites.
One of the pages in which the issue occurs is as follows.

https://www.google.co.jp/amp/s/restaurant.ikyu.com/sd/101876/amp/

![新しいタブ-Google-Chrome-2020-04-15-10-57-56](https://user-images.githubusercontent.com/23374791/79291021-7f464900-7f08-11ea-8f08-de386734aa6b.gif)

## What browsers are affected?

It did not occur in iPhone Chrome, but it occured in browsers such as Safari.

## Which AMP version is affected?

Version 2004030010070

**Comment by uskay** [comment]
Very interesting case. These are the additional debug materials I received in another thread:
- Additional resources: [HAR file](https://cdn.glitch.com/98449704-33d8-49b2-88f2-aa6d2aeba5d3%2Fwww.google.com.har?v=1586939203922)
- Additional information: the repro GIF above is using `81.0.4044.92(Official Build) (64-bit)`

Unfortunately, I was not able to reproduce the issue but by looking at the HAR file,
1. The viewer, www.google.com, is loading the `<iframe>` below to load AMP from cache
```
<iframe class="u2quVpIWVr0__amp-doc v2FKFf" allow="autoplay" allowfullscreen="true" allowpaymentrequest="true" loading="eager" name="https://restaurant.ikyu.com/sd/101876/amp/" src="https://restaurant-ikyu-com.cdn.ampproject.org/v/s/restaurant.ikyu.com/sd/101876/amp/?usqp=mq331AQFKAGwASA%3D&amp;amp_js_v=0.1#origin=https://www.google.com&amp;cid=1&amp;prerenderSize=1&amp;visibilityState=visible&amp;paddingTop=32&amp;history=1&amp;p2r=0&amp;horizontalScrolling=0&amp;csi=1&amp;storage=1&amp;viewerUrl=https://www.google.com/amp/s/restaurant.ikyu.com/sd/101876/amp/&amp;cap=iframeScroll,navigateTo,fragment,handshakepoll,cid,replaceUrl,fullReplaceHistory"></iframe>
```
![iframe](https://cdn.glitch.com/98449704-33d8-49b2-88f2-aa6d2aeba5d3%2FScreen%20Shot%202020-04-15%20at%2017.30.26.png?v=1586939460989)

2. But some how the HTTP request is sent w/o any parameters e.g. `usqp` and `amp_js` which would result in 404
![request](https://cdn.glitch.com/98449704-33d8-49b2-88f2-aa6d2aeba5d3%2FScreen%20Shot%202020-04-15%20at%2017.40.57.png?v=1586940071060)

3. I'm not sure why this request is sent with `sec-fetch-site: same-origin` while it should be `cross-site` since it's an cross origin request i.e. www.google.com vs *.ampproject.org

**Comment by coreyching** [comment]
@morsssss 

Here are the steps I am seeing that is repeating the issue:

Steps to reproduce. 
1. Open Google (in ios safari)
2. Type "Niel Patel AMP"
3. Click on "Why AMP & Facebook Instant Can Be Bad for ... - Neil Patel" result.
4. Click on "neilpatel logo" in the orange bar
5. Click back
6. Links no longer work.


Similar complaints on the web:

https://support.google.com/webmasters/thread/16526831?hl=en&dark=0
https://stackoverflow.com/questions/60809468/amp-page-if-you-use-a-browser-back-you-cant-click-any-other-links
https://wordpress.org/support/topic/amp-is-freezing-it-is-not-possible-to-click-on-links/
https://www.drupal.org/project/amp/issues/3105858

**Comment by coreyching** [comment]
@mauricengo-revolve

**Comment by uskay** [comment]
@coreyching , While both are related to browser back, I feel the issue you are mentioning here is more related to #30838 . I'll add a link to your comment there as well.

cc/ @nainar

**Comment by mauricengo-revolve** [comment]
Hi @uskay and @morsssss, we are occasionally seeing both issues occurring with the back button use case — the 404 and the not clickable links. We're waiting on both issues to be addressed before launching our AMP site. @coreyching has been assisting us. Thank you for looking into this.

**Comment by morsssss** [comment]
Thanks everyone! I'm pinging some people over here...

**Comment by morsssss** [comment]
Trying this with https://www.google.co.jp/amp/s/restaurant.ikyu.com/sd/101876/amp/ as described by @abeak above, in Chrome DevTools emulating an iPhone, I get this 404 as well. I don't get it in DevTools emulating an Android device.

![Screen Shot 2020-10-29 at 5 44 38 PM](https://user-images.githubusercontent.com/29419498/97635871-7f261a80-1a0e-11eb-9422-3c6cc957a893.png)

**Comment by mauricengo-revolve** [comment]
@morsssss Thanks for looking into this. Is there any update on these issues?

**Comment by morsssss** [comment]
Thanks for the ping. Let me check...

**Comment by flaviori** [comment]
This seems to be related to https://github.com/ampproject/amphtml/issues/25179 where the query and fragment parameters are stripped out from the iframe on back.

In particular, on back the iframe tries to load the following which is a 404
https://restaurant-ikyu-com.cdn.ampproject.org/v/s/restaurant.ikyu.com/sd/101876/amp/

Whereas the URL actually available on the AMP Cache is:
https://restaurant-ikyu-com.cdn.ampproject.org/v/s/restaurant.ikyu.com/sd/101876/amp/?usqp=mq331AQFKAGwASA%3D&amp_js_v=0.1#aoh=16046200428269&origin=https://www.google.co.jp&cid=1&prerenderSize=1&visibilityState=visible&paddingTop=32&history=1&p2r=0&csi=1&storage=1&viewerUrl=https://www.google.co.jp/amp/s/restaurant.ikyu.com/sd/101876/amp/&cap=iframeScroll,navigateTo,fragment,handshakepoll,cid,replaceUrl,fullReplaceHistory

Just adding the ?&amp_js_v=0.1 is enough for the page to load.
https://restaurant-ikyu-com.cdn.ampproject.org/v/s/restaurant.ikyu.com/sd/101876/amp/?&amp_js_v=0.1

This seems like an old issue however, has anything changed since then?
https://github.com/ampproject/amphtml/issues/25179

**Comment by flaviori** [comment]
@choumx @ericfs

**Comment by flaviori** [comment]
Worth noting that this only reproducible in the standalone viewer as far as I can see.
Whereas if you get to the same page from the viewer in Google Search, the bug won't occur.

**Comment by uskay** [comment]
Thanks @flaviori for looking into this. This thread is talking about two different issues as far as I can tell. 

1. The original issue this thread points out. Viewer results in 404 b/c of missing query parameters.
2. The issue @coreyching [points out](https://github.com/ampproject/amphtml/issues/27691#issuecomment-716868604) relates to #30838 where it does show the page on Safari browser back but disables all the links on the page.

I'll loop @flaviori , @choumx and @ericfs into #30838 just in case.

**Comment by ericfs** [comment]
I'm having trouble reproducing the 404. @choumx, Are the query and fragment only stripped in certain cases?

**Comment by choumx** [comment]
I can repro this too. Flavio is right that this is caused by #25179. 

Query params are stripped before navigation (on Safari 13+, in viewer) and restored either immediately (`target=_blank`) or when restoring page from back/forward cache (`target=_top`). 

Looks like the issue is the case where the page is not stored in bfcache and needs to do a cold load (need to investigate when this happens). In this case, the missing viewer query params (e.g. `&amp_js_v=0.1`) cause a 404.

Simplest fix would be to turn off this feature (it might even be stale now with recent ITP developments in Safari 14). @ericfs Is it possible for the viewer to avoid 404 by adding a fallback for required query params?

**Comment by choumx** [comment]
Poked around a little more.

- It appears the feature is still useful in Safari 14 for preserving document referrer
- I can only repro inconsistently on my MBP and iPhone

@abeak @uskay Do we have a sense of how many users are impacted by this?

@ampproject/wg-caching Is it possible to add a fallback for missing required query params for cache URLs? E.g. missing `amp_js_v=0.1` causes 404: https://restaurant-ikyu-com.cdn.ampproject.org/v/s/restaurant.ikyu.com/sd/101876/amp/

**Comment by Gregable** [comment]
@choumx Can you elaborate a little more on what the fallback should do here? I'm not sure I follow the whole issue well.

**Comment by ericfs** [comment]
I think @seanjallen may have had a proposal about how to simplify `amp_js_v` usage, which could help here. I'll need to dig to find the proposal.

**Comment by choumx** [comment]
> Can you elaborate a little more on what the fallback should do here?

I believe the `?amp_js_v` param controls the version of `amp-viewer-integration-X.Y.js` script that's injected into the page. If it's missing, we could fallback to a default version (currently 0.1) instead of 404'ing. 

However, this is not a complete recovery since the iframe fragment would still be missing. This means paddingTop is not set (viewer header occlusion) and no viewer capabilities (swiping between articles). So maybe this isn't the best idea.

OTOH, manually refreshing the page containing the 404'ed iframe is a workaround with a complete recovery.

**Comment by uskay** [comment]
> @abeak @uskay Do we have a sense of how many users are impacted by this?

@choumx This would be related to #30838 as well but for this particular service @abeak and @tanakayuki are working on, they have around 60% of their users using iOS out of over 400K users, and 90% of those are using iOS 13, so pretty impactful.

**Comment by ericfs** [comment]
Will made a suggestion for a Google Viewer side fix. Filed b/173034823

**Comment by morsssss** [comment]
(for those who are curious, that refers to an internal Google bug-tracking system.)
(if you're looking for further news, please comment on this issue.)

**Comment by mauricengo-revolve** [comment]
Thanks @morsssss.  Is there any idea when this would be resolved?

**Comment by morsssss** [comment]
This fix would be on the Google side, not from folks who work on AMP - so I'm not sure.

@ericfs might know more, but he might not either. I'll see if we can get something going or at least learn more.

**Comment by ericfs** [comment]
Thanks for the nudge. Checking with the rest of the team on prioritization. Many are out this week so I probably won't have an update immediately.

**Comment by flaviori** [comment]
Quick update, while I don't have an ETA yet, we are now working on prioritizing this, and we'll share updates as soon as have any!

**Comment by flaviori** [comment]
FYI this is actively being worked on with a fix/workaround on the viewer side.
I would say 1-2 weeks for the fix to be submitted + another week of release, so hopefully fixed by EoM.

Proposed solution:
1) The cache returns an error page when the page is served without the amp_js_v parameter.
2) The error page sends a message to the viewer.
3) The viewer reloads the AMP page in the iframe with the full set of parameters.

This will be platform agnostic and work as in-depth defense against other cases where a page is loaded in the viewer without the corresponding amp_js_v param.

We are not moving forward with the rollback in #31614 assuming this is sufficient.

**Comment by seanjallen** [comment]
Update: This was fixed with an AMP cache side update back in February.

google.com should now load the publisher's version of the AMP page in response to a load failed message from the cache when this happens. You might see a brief 404 flash from the cache during this process. We might make this more robust on the google.com viewer side in the future, but for now the main user facing error of not being able to see a page after clicking back should be fixed (or at least ameliorated).

Any other viewer that uses the Google AMP cache should be able to behave the same way in response to the same load failed message if they want.
