### ISSUE TITLE
Restart button non-functional on single-page stories

### ISSUE THREAD

**Issue by wassgha** [ampproject/amphtml#27742]
## What's the issue?

See https://github.com/google/web-stories-wp/issues/1175

Pressing the restart button should restart a one-page story (in particular those with video elements), but the restart button is currently non-functional on one-page stories.

## How do we reproduce the issue?

Use the codepen at https://codepen.io/gharbiw/pen/rNOOWzG

1. The video should play automatically
2. Press the restart button
3. The video does not restart and continues playing with no effect

## What browsers are affected?

All browsers

## Which AMP version is affected?

All versions

/cc @gmajoulet

**Comment by gmajoulet** [comment]
Thanks for the bug report.

There are two different solutions for this bug:
1) Since there is only one page, we could hide the "restart" button
2) We could make the restart button rewind the current page

I think we should go with the 2nd solution, which works better when there are videos on the page. Some videos could not have a `loop` attribute, and this button would offer a way to play the media again.

cc @ampproject/wg-stories
