### ISSUE TITLE
amp-subscriptions: Allow for conditionally visible content on free pages

### ISSUE THREAD

**Issue by ChrisAntaki** [ampproject/amphtml#27754]
## Describe the new feature or change to an existing feature you'd like to see

Now that `granted` is always true on free pages, this breaks some existing pages
https://github.com/ampproject/amphtml/issues/27300#issuecomment-613561556

What's the best way we could allow for conditionally visible content on free pages?

**Comment by ChrisAntaki** [comment]
Hey @juanmadurand! Could you tell us more about Pagina's use case?

**Comment by jpettitt** [comment]
Some thoughts:

In the contribution use case we want to get the "entitlement" for two reasons

1. To be able to pingback the the users state for analytics purposes
2. To control display of the contribution request message

However the content is free so marking it as paid, while a valid short term solution, is not ideal.    We could add a flag to the swg config `alwayFetchIContributionState`, however we'd need to understand how that would interact with the news app.

Other thoughts?

**Comment by juanmadurand** [comment]
Hi guys, just my use case on this issue:
We need fetching entitlements on every page to display conditional UI depending on the status of the user (logged in, contributor, anonymous). 
On pagina12.com.ar, where all articles are free, we have a "Contribute with Google" button on AMP, that we want to show only for non-contributors users. That's why we need entitlements info always.

Beware that there's existing [documentation](https://developers.google.com/news/subscribe/guides/configure-amp?hl=en#implement-amp-access) about the conditional display, and should be updated in case you don't include by default the entitlements on free pages.

In our case, we tested that setting the `isAccessibleForFree` to `false` fixes the issue. But I understand it's a hack.

Thank you!

**Comment by jpettitt** [comment]
How about we add an `alwayAuthFreeContent` flag to the config and if it's present treat `isAccessibleForFree` as false.  That's lets us preserve the structured data semantics and still get the auth data.  It would then let the page render optional content to non-contributors (eg calls to action).  Setting this flag and the `alwaysGrant` flag at the same time should log a warningr and `alwaysGrant` should win.

The target use case would be contributions authough it would still operate on subscription content (since we don't actually know which is which at runtime)

**Comment by ChrisAntaki** [comment]
Sounds good to me! What do you think, @juanmadurand ?

**Comment by kliuless** [comment]
@jpettitt We are having the same issue, in that `AUTHDATA` fields aren't being populated on free pages. I believe your suggestion will work.

When you say "treat `isAccessibleForFree` as false", I assume this is only for the purposes of deciding whether to call `authorize` & providing access to the result via `AUTHDATA`. I'm not familiar with all the effects of `isAccessibleForFree` which is why I'm wondering about possible side effects.

**Comment by jpettitt** [comment]
@kliuless The original though was for contributions content where the main body of the article is free but there is some call to action that should only be displayed to non members.  What is your use case?

**Comment by kliuless** [comment]
@jpettitt Our case sounds very similar. We have both premium & free content. We have two buttons, "login" and "subscribe", and they were hidden/shown based on what our `authorize` function returned (whether the user is logged in, and whether they are a subscriber). We also perform an analytics call.

This was working well on amp-access, but after switching to amp-subscriptions the buttons always show and the analytics call is missing information.

I'm already in communication with someone at Google about this issue; he asked me to comment here to confirm that your solution would work for us.

**Comment by jpettitt** [comment]
Yep - I asked them to point you to this issue.  So I think what we need is for `alwayAuthFreeContent` combined with `isAccessibleForFree: true` to internally generate an entitlement that unlocks the page but continue with the auth request and subsequent render so the `data` fields are respected.

We have a "fixit" week coming up June 8th I'll add this to the list for both amp-access and amp-subscriptions
