### ISSUE TITLE
amp-animation & friends use incorrect keyframe easings on Safari 13.1

### ISSUE THREAD

**Issue by Ichigo3d** [ampproject/amphtml#27762]
Description: 
Drop-in ads story animation works slow in Safari browser 

Steps:
1) launch local server on version 2004071640410
2) open link http://localhost:8000/examples/amp-story-auto-ads.amp.html
3) swipe to left until Drop-in story ads
4) observe result.

Actual result: drop-in story ads animation works slow.

Expected result:  drop-in story ads animation works  should works fast.

**Comment by alanorozco** [comment]
This is only in Safari 13.1 since [the WebAnimation API is now native](https://webkit.org/blog/10266/web-animations-in-safari-13-1/)

The discrepancy with other platforms is that Safari won't interpret [`easing` in individual keyframes.](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API/Keyframe_Formats#Attributes)

[This test case](https://reminiscent-lopsided-army.glitch.me/easing.html) should do a stepped jump and then ease to the initial position. In Safari, this is a linear animation instead.

```html
    <div class="animated"></div>
    <script>
      document.querySelector(".animated").animate(
        [
          {
            offset: 0,
            transform: `translateY(0px)`,
            easing: "step-start"
          },
          {
            offset: 0.8,
            transform: "translateY(200px)",
            easing: "ease-in"
          },
          {
            offset: 1,
            transform: "translateY(0px)",
            easing: "ease-in"
          }
        ],
        {
          fill: "forwards",
          duration: 2000
        }
      );
    </script>
```

Same problem with the `amp-story` drop animation described in this issue, [case reproduced and isolated here](https://reminiscent-lopsided-army.glitch.me/drop.html).

We can rewrite `amp-story` preset keyframes so they don't use individual easings, but this would still be a problem with any `<amp-animation>` that uses this feature.

I'm working on finding a web platform test to provide a bug to WebKit. From the AMP's side, we either force the polyfill or wait for this to be resolved.

**Comment by alanorozco** [comment]
Filed WebKit bug https://bugs.webkit.org/show_bug.cgi?id=210526
Force polyfill as workaround in #27773
