### ISSUE TITLE
<amp-list>: support rendering outside of viewport

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#27910]
**summary**

I recently learned of a use case where someone would like to display an `<amp-list>` within a sidebar. The sidebar starts out closed. Ideally the amp-list could fetch and render while not in the closed sidebar for both SEO and performance reasons.

cc  @wassgha  @nainar @ampproject/wg-runtime

**Comment by choumx** [comment]
Maybe there's more context but it's not obvious to me that this is desirable behavior.

Developers can add placeholder content for crawlers (which are not guaranteed to run JS). And lazy loading is WAI.

**Comment by AndrewKGuan** [comment]
Hi,
in an AMP-only setup (no canonical), these hidden dynamic contents are crucial for crawling / indexing.  Developers will hesitate to use this AMP-only setup because of fear of losing out in search traffic due to this incapability.
For non-AMP pages, fetching dynamic contents can be controlled by developers and done post-rendering.  It is not doable with amp-list because they don't have control over when amp-list will populate.
Placeholders are not really an option in many cases.  If the contents can be rendered into placeholders, there probably won't be a need to use amp-list at the first place.

**Comment by choumx** [comment]
Another workaround is to use an amp-list to render structured data (JSON+LD) outside of an amp-sidebar.

**Comment by AndrewKGuan** [comment]
Would an amp-list attribute for non-performance blocking post-load rendering feasible?  
For example: 
<amp-list **_eagerRender=true_**> 
to give developers a bit more control?

**Comment by choumx** [comment]
I'm not a fan personally. Part of AMP's usefulness is that it can make decisions like "how far from viewport should we render elements" on behalf of the user.

**Comment by AndrewKGuan** [comment]
Not even post-hydration when the page is ready? =). amp-script is allowed to do that.

**Comment by jaygray0919** [comment]
@choumx 
>Another workaround is to use an amp-list to render structured data (JSON+LD) outside of an amp-sidebar.

this does not work, per earlier shared examples.
we **would like** it to work, but GSDTT, for example, will not acknowledge `JSON-LD` rendered from `amp-list`
