### ISSUE TITLE
Deprecate "owners" system

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#28042]
Follow-up to #25428.

Once resource scheduling with IntersectionObserver is stable, we should be able to simplify/remove `owners-interface.js`/`owners-impl.js`, and usages in extension code.

Should have a minor performance benefit. Curious how much of a binary size code reduction we'd get from ripping it out.

Also, there are probably other codepaths that can eventually be removed as well, e.g. `hidden-observer-impl.js`.

**Comment by newmuis** [comment]
What happens for cases where extensions need ownership that's not based on viewport intersection?

**Comment by choumx** [comment]
Hm, can you share details of these?

/cc @ampproject/wg-runtime

**Comment by newmuis** [comment]
I think we might (or, perhaps, should) have both:

(a) Elements that _are_ on the screen but we want to artificially delay their layout (e.g. to mitigate race conditions between components)
(b) Elements that are _not_ on the screen but we want to force into their lifecycle early (e.g. to do custom preloading that is not managed by the runtime)

It's good for us to have semantic control over this rather than having to "trick" the runtime into loading things by figuring out the "right" coordinates for something, even when those coordinates don't actually make sense for display.

/cc @ampproject/wg-stories

**Comment by choumx** [comment]
I think a configuration API to tweak the eagerness/laziness of resource loading could make sense. Please share any concrete use cases you have in mind.

**Comment by gmajoulet** [comment]
Most of our use cases would be fixed by the new intersection observer methods (nested scrollboxes).
There is one cause where we use the owners system to pause an AMP component as we navigate to the next page. We could apply a `display: none;` and wait for the runtime to automatically pause it, but having a way to control this programmatically makes more sense.

This falls into the same category that Jon described:
> It's good for us to have semantic control over this rather than having to trick the runtime into loading things by figuring out the "right" coordinates

**Comment by choumx** [comment]
I actually think pause/resume is unaffected by owners (there's just an extra API for it in owners-interface.js), so we should be ok. 

First-class support for "pausing videos beyond viewport distance X" would be possible with IntersectionObserver and seems better than status quo. :)
