### ISSUE TITLE
<amp-video muted is deprecated (according to search console) but still appears in WordPress plugin 

### ISSUE THREAD

**Issue by joshm33333** [ampproject/amphtml#28041]
Got an email notification of an amp issue on my site from google search console. muted is deprecated, use autoplay instead. checked my page in wordpress and found the muted toggle in the gutenberg editor.

I have the official amp plugin. Should it not strip the muted tag automatically? Should I post this as a bug in the Gutenberg bugs forum?

**Comment by westonruter** [comment]
The “Muted” toggle is part of the WordPress core block editor (Gutenberg) and is distinct from the “Autoplay” toggle:

> ![image](https://user-images.githubusercontent.com/134745/80526226-47e38d80-8947-11ea-95b5-49183d7a0454.png)

It's not clear to me how the AMP plugin should convert such videos into `amp-video`, since the block editor allows for non-muted autoplayed videos. I understand that `amp-video` always makes autoplayed videos muted, so is the idea that the “Muted” toggle should he removed when “Autoplay“ is toggled on?

Another issue is that last I checked, the block editor makes it difficult to remove these core toggles.

**Comment by joshm33333** [comment]
Original poster here
Just an idea, why not just strip the muted tag if the user turns on both autoplay and muted? No need to confuse the user with more rules to remember

**Comment by westonruter** [comment]
@wassgha is this the correct understanding of `amp-video` and `muted`? Does `autoplay` indeed imply `muted`? If so, then we could indeed omit the `muted` attribute when the `autoplay` toggle is on. The only problem then is what to do in the case of a video having `autoplay` _on_ and `muted` _off_. Should we force `muted` to be enabled in the UI (if we can't hide the toggle or disable it altogether)? Otherwise, if we don't do anything with the `muted` toggle then the user needs to be informed that it won't have any effect when `autoplay` is enabled, perhaps via some notice.

**Comment by wassgha** [comment]
@alanorozco  do you have the context for why we deprectated `muted`?

**Comment by alanorozco** [comment]
`autoplay` indeed implies `muted`. Explicit `muted` [was deprecated](https://amp.dev/documentation/components/amp-video/#attributes) because we wish to enforce for all autoplay videos (and avoid unmuted ones!).

If you set `muted` on an `amp-video` it will have no effect. The Wordpress UI should handle this if possible in some of the ways @westonruter mentioned.

We can additionally trigger a user-level warning from an `<amp-video>` when using `muted`. I'm unsure about the value of this approach since this would show only at runtime, and these warnings in general might be stripped out from some builds in the future.

**Comment by westonruter** [comment]
Where is the current `muted` deprecation warning from GSC coming from? I don't see it in the validator anywhere.

**Comment by westonruter** [comment]
I've filed an issue for the plugin to better handle the Autoplay and Muted toggles: https://github.com/ampproject/amp-wp/issues/4635

**Comment by alanorozco** [comment]
@westonruter I'm also unsure about the origin of the GSC warnings. If I understand correctly, they should go away as long as the Wordpress plugin removes `muted` from all `<amp-video>` tags?
