### ISSUE TITLE
I2I: Permutive component for dynamic ad targeting

### ISSUE THREAD

**Issue by joshfg** [ampproject/amphtml#28095]
## Summary

Permutive is a Data Management Platform (DMP) for publishers. We have a strong focus on privacy and first-party data: enabling publishers to use their data to power advertising and personalization in real-time, across every device, browser and environment, while respecting user privacy.

One of the essential capabilities we provide publishers is the ability to dynamically target their ads, based on a user's behaviour. We want to provide publishers with this capability in AMP, to the same standard as we do on standard Web pages. This proposal describes an AMP component that achieves this.

## Motivation

Many publishers have asked us to integrate with their AMP pages and provide the same benefits in the AMP environment that we've been able to provide on their standard Web pages.

We believe we can offer publishers the same benefits they have seen on standard Web in AMP, by building a custom `amp-permutive` component. This component would allow publishers to target dynamically, without reliance on [AMP RTC](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/rtc-documentation.md). We believe this approach has significant benefits for publishers and end-users:

- By avoiding reliance on a third-party cookie, we can provide dynamic ad targeting across every browser, in every environment.
- By avoiding AMP RTC calls, the publisher can avoid a blocking network request prior to the ad-request - leading to a better end-user experience and reduced competition for network resources on the user's device.
- We believe long-term, there are significant privacy benefits from processing and decisioning on data on-device, rather than in the cloud. Behavioral data can be processed without ever leaving the user's device. In this world, only the result (e.g. a list of audience segment IDs) needs to leave the user's device. We believe this is the most privacy-compliant approach to audience targeting, which is good for publishers and end-users.

## Design Document

Please find our proposal and the reasoning behind these design choices, here:

[https://docs.google.com/document/d/1IHCjfuQCGcDmptJZFXWA9qNj8A0hdmsciDi7P7hBgjo](https://docs.google.com/document/d/1IHCjfuQCGcDmptJZFXWA9qNj8A0hdmsciDi7P7hBgjo)

/cc @ampproject/wg-approvers
/cc @ampproject/wg-ads

**Comment by mrjoro** [comment]
@lannka is out until next week; @jeffjose can you take an initial look?

**Comment by powerivq** [comment]
@joshfg Thanks for making this proposal. It is well written. I have left some comments on your google doc. In general, on-device handling of targeting information makes a lot of sense, but let's resolve these technical questions.

**Comment by joshfg** [comment]
Thanks for the comments @powerivq ! I have left some replies in the google doc.

**Comment by samouri** [comment]
Instead of building an `<amp-permutive>` component, we've decided we can solve the same use case more generically via a set of 3 I2Is:

1. https://github.com/ampproject/amphtml/issues/30193: allow amp-script to run 3p scripts without a CSP via extra sandboxing.
2. https://github.com/ampproject/amphtml/issues/33580: teach amp-analytics to send events to the amp-script 
3. https://github.com/ampproject/amphtml/issues/33581: teach amp-ad to request configuration from amp-script

With all of those in place, a publisher can deploy an `<amp-script ...>`  on their page to load the Permutive script from their CDN (cross-origin src). All `amp-analytics` events can be configured to send data to the `<amp-script>` and then the `amp-ad` can request targeting data from the `amp-script`.
