### ISSUE TITLE
Design Review 2020-05-20 20:00 UTC (additional ads creatives support, amp-consent UI for TCFv2, wg-access-subscriptions update)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#28108]
Time: [2020-05-20 20:00 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2020&month=05&day=20&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20200520T200000Z/20200520T210000Z&details=https%3A%2F%2Fbit.ly%2Famp-dr))
Location: [Video conference via Google Meet](https://bit.ly/amp-dr)

The AMP community holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc or issue by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by mrjoro** [comment]
The Access & Subscriptions Working Group will be presenting their [periodic update](https://github.com/ampproject/meta/wiki/Working-Group-Updates) at this Design Review (10-15 minutes).

/cc @ampproject/wg-access-subscriptions @jpettitt

**Comment by powerivq** [comment]
The Ads WG will be presenting https://github.com/ampproject/amphtml/issues/28386 and https://github.com/ampproject/amphtml/issues/28428 for expanding types of creatives being supported on AMP.

**Comment by micajuine-ho** [comment]
The Analytics WG would like present our ideas for improving the amp-consent UI for 3P iframes to be better display disclosures TCFv2 (15 minutes).

/cc @ampproject/wg-analytics

**Comment by calebcordry** [comment]
Notes:

@powerivq

- Would like to expand kinds of creatives being supported especially for reservation
- demo.kargo.com/ad/3023316
- These kinds of creatives are not supported on amp pages only sticky ad
- These are in high demand from pubs

Allow sticky ads in amp-ad component

- We can think of this as a type of sticky ad with an animation
- Proposing to have amp ads tag support these kinds of creatives directly rather than changing sticky ad
- The size of this kind of ad can be dynamic and does not need to be configured by pub, it is declared by the creative
- There are some size constraints, but we expand the available inventory
- The proposal is to set area limit based on percentage of viewport size
- Able to support transparent backgrounds (might introduce user confusion with mis-clicks etc)
  - For loading failures we will destroy the ad component after timeout
  - Advertisers should not have an incentive to capture mis-clicks because they want people actually interesed in the ad
  - Still will have control of X button

Questions

- Alan: Does the transparent layer cover the entire viewport?
  - we will not allow the layer to cover the entire viewport. Ad will postMessage us the size and determine if it is too large - including transparent layer
  - should not prevent scrolling. If cursor is on top, CSS should allow scroll.
- Yuxuan: right now size is limited to 100px height, does this mean an ad could be skinny and be the whole height of viewport? Does this affect scrolling if I scroll this area taken by the ad?
  - we should probably have more contraints, maybe overall height limit but should be a rare use case. I don't want a limit on the width, but height sounds reasonable
- Naina: my concern with no width is we can make width 100% and a larger height than sticky ad currently allows
  - sticky ad has fixed height limit, maybe 100px is too restrictive is something like 15-20% ok?
  - Naina: depends on the use case, I would rather explicit width and height to prevent abuse
  - Alan: we could also do a aspect ratio in combination with %
  - Hongfei: we can discuss the limits in doc
- Zewen: is the transparent background clickable?
- lets discuss second proposal and that should give some clarification

- We want to move sticky ad to amp-ad

Make SafeFrame API available for all amp-ad networks

- ad will call register before any container is created or ad is shown
- this is where we will check size
- if this check passes, then we will create the transparent container using the CSS pointer event so that you can not click on the transparent ad container just yet
- there are some side effects, hyperlinks behind this layer will be unclickable
- Hongfei: is that true? Seems like its not a problem
- We wait until ad is loaded and animation is finished, at which point the ad sends a postMessage to say it is clickable
- We also have a time limit if we never receive this signal eg the ad fails to load
- we will also add an X button and remove the CSS pointer so that ad is fully interactive

Questions

- Justin: If we allow transparent background, and the ad itself is transparent, what's to prevent me from making the ad the full 20% and only "showing" the oatmeal in a small corner? Won't that give me a large interactable box for accidental clicks.
  - the advertisers should not have incentive to do that, as reservation advertisers usually have to pay by click
  - if they do this, they will be paying for invalid clicks, usually pubs have the incentive to increase clicks
  - Hongfei: remember that this is reservation ad where pubs & advertisers have an offline deal (direct sold) pubs have a lot of contol and mutual trust
  - Alan: is there a technical guarantee that this is direct sold
  - Hongfei: we need to communicate this to pubs that there are potential abuse vectors
- Yuxuan: why not hide the ad before it's ready?
  - we want to show animation before it is clickable
- Zewen: one idea is to limit surface area rather than height alone
  - yes this is one idea we are working out the details
- Justin: can we just add a blurred background? This would let it become obvious if ad is nefarious.
  - Yuxuan: this wouldn't work for the example?
  - Naina: this should be enforced for odd sizes
  - Justin: we should make it super obvious to user where the click area is
  - Naina: we can allow them to customize background?
  - Justin: we use same technique for blurry img placeholder
  - we can try it and see what it looks like, and see what stakeholders think. Only after animation is finished
- Devin: to reduce clicks could we have it scroll in, rather than animate?
  - this is similar to a different type of creative, and would that be better? Maybe its just a different experience
- Yuxuan: our default post prompt design relies on solid background and would likely need a redesign
  - probably fine if blurred background, but if transparent it will be weird
- Hongfei: lets give time, still a lot of UX questions that we should follow up offline

@micajuine-ho

AMP Consent UI TCFv2

- Currently we allow CMPs to display prompt in a fixed height with other constraints
- with tcfv2 many CMPs need to show more information and we get requests to take the whole screen so that users do not have to scroll down to accept
- its not a legal requirement to change this, scrolling down is allowed, but may not be great UX, and would likely lead to less accepts
- one solution is to take the current dialog box and expand it to the whole screen
  - if we cover the whole screen it might be confusing for user to not see any of the content
- another solution is to wait for CMP to return the whole dialog, and show a lightbox
  - this would be similar to blocking the page
  - this would not be all the way fullscreen, with space at top, but should satisfy CMP
  - users would see the content behind lightbox
  - lose prerendering benefits
- display lightbox when content is loaded
  - has margins around it, blocks scroll.
  - has a minimum delay so that it doesn't take over immediately
  - pretty common UX outside of AMP
- leaning towards final option as we think it has the best UX while keeping CMPs happy
- this is a big change
- Zewen: can we put accept/decline as sticky at bottom
  - users must scroll before accepting
  - you can show the button but only allow click after scroll
- CMP: can we add both options?
  - we would like to keep existing v1 flow if possible
  - pubs will still need to retag to use this new feature?
  - yes that seems to be a case
- is there a big difference between space at top and around?
  - Zewen: opt 2 is only showing top, but opt 3 showing top, bottom, left, right should be a better indication to users that the real content is behind
  - this is aligned with pubs interest
    Yuxuan: to clarify, this is an interstitial without user interaction, are we ok with this?
- Naina: its not ideal, but this is important.

**Comment by jeffkaufman** [comment]
@calebcordry excellent notes!

With `it is declared by the creative`, does the publisher or ad network need to opt in?  I'm worried about publishers seeing different ads than they thought they had signed up for

**Comment by powerivq** [comment]
@jeffkaufman Let's move the discussion to the respective Github issue. https://github.com/ampproject/amphtml/issues/28428

**Comment by mrjoro** [comment]
@jpettitt please update this issue with the Access & Subscriptions update when it's available.

/cc @ampproject/wg-access-subscriptions
