### ISSUE TITLE
Google OneTap support for AMP

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/amphtml#28120]
[OneTap](https://developers.google.com/identity/one-tap/web) enables super quick login flow for users.  It would be nice to have it also available on AMP as well.

**Comment by jonluca** [comment]
Plus one on this - this would be a great feature!

**Comment by nainar** [comment]
This has landed here: https://github.com/ampproject/amphtml/pull/29247/

**Comment by jonluca** [comment]
Nice! This is great @nainar - we have this component built out and ready to test, but it looks like it is still failing AMP validation on https://validator.ampproject.org/. It doesn't look like it's in beta anymore, though - do we know when it will be able to be considered valid amp?

**Comment by nainar** [comment]
We are looking to push this live in the next week or so 🤞

**Comment by andreylipattsev** [comment]
Hi @nainar any news here?

**Comment by nainar** [comment]
Landed here: https://github.com/ampproject/amphtml/tree/master/extensions/amp-onetap-google

**Comment by kdnanmaga** [comment]
@nainar 

I tried implementing amp-onetap-google and got the following error on the browser console:
`Refused to display 'https://accounts.google.com/o/oauth2/auth?client_id=99199563698-renu0s9sdukir1ijij853r3eovj5fre3.apps.googleusercontent.com&redirect_uri=http://localhost:8000/google-oauth2/complete/google-oauth2/&state=qn3mfmfBf5I3ejWMNmI21XMdsQdpUlqI&response_type=code&scope=https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/userinfo.profile' in a frame because it set 'X-Frame-Options' to 'deny'.`

Please let me know if there is something to fix on my end or there is an issue with accounts.google.com that has to be fixed by them. I tried setting "content-security-policy: frame-ancestors 'self' accounts.google.com" http header for the page but that did not work too.
