### ISSUE TITLE
Codecov reporting total-repo coverage

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#28212]
## What's the issue?

Codecov is reporting the wrong coverage change, and is red on PRs. The current [coverage over the entire repository](https://amp-project-metrics.appspot.com/) is 76.9%. Every PR that runs the Codecov check fails that check, saying 77% is below the 80% threshold. The coverage threshold should apply to the changed files/lines, not the total repo coverage.

## How do we reproduce the issue?

See #28190 #28185 

/tryassign @rsimha

**Comment by rsimha** [comment]
It turns out that the `base: auto` automatic baseline selection for codecov causes it to select the baseline commit for a PR, which is the branch point. This is inaccurate since there could've been several new commits to `master`, which Travis includes in its build.

See https://github.com/ampproject/amphtml/pull/28185#issuecomment-624285176 for more details.

E.g.: https://travis-ci.org/github/ampproject/amphtml/jobs/683465296

![image](https://user-images.githubusercontent.com/26553114/81112196-489e9580-8eec-11ea-838a-fb0e07e42df7.png)

I'll try explicitly setting the baseline commit while uploading coverage reports for PRs.

**Comment by rsimha** [comment]
Seems like explicitly selecting the baseline commit is an open FR for `codecov`: https://github.com/codecov/codecov-bash/issues/83#issuecomment-606674059

Unfortunately, this means that coverage numbers for older PR branches can be affected by newer commits to `master`. Investigating alternatives / workarounds.

**Comment by rsimha** [comment]
A few months later, this is still an open FR with Codecov. An available workaround is to rebase a PR branch to pull more accurate coverage numbers. (This should be rare, and should only be necessary for very old branches.)

I'm inclined to resolve this as infeasible. WDYT @rcebulko?

**Comment by rcebulko** [comment]
The issue w.r.t. using the merge-base isn't what I had in my mind as the primary issue here. AFAICT, the "compare commit", whatever that is, is used to look up the "baseline" _global coverage_, and then that is compared to the _global coverage_ at the PR head. My intuition is that this isn't how we want to be thresholding changes.

Rather, we only want to be assessing the % coverage of added/altered lines. Ie,  if the repo has 70% global coverage, then a PR adds a single 20-line function which is fully tested, the coverage of those added lines is ~100% even though the global coverage may still be only 70%. I'm not sure if codecov is providing that data at all.

**Comment by rsimha** [comment]
Oh I see. In that case, the fix is within our control. We can simply eliminate the status for project-level coverage.

https://github.com/ampproject/amphtml/blob/d77ff9cf28e3e95cdd9834fb2c0e2075dedd1ede/.codecov.yml#L23-L29

We will still get a separate status for patch-level coverage.

https://github.com/ampproject/amphtml/blob/d77ff9cf28e3e95cdd9834fb2c0e2075dedd1ede/.codecov.yml#L30-L36

**Comment by rcebulko** [comment]
@rsimha That looks like what we want!
