### ISSUE TITLE
amp-owners-bot unsubscribes reviewers from notifications

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#28253]
## What's the issue?

The `amp-owners-bot` unsubscribes a reviewer it notified as they submit a review.

## How do we reproduce the issue?

1. Someone sends a PR and the `amp-owners-bot` notifies you (in my example, it did not add me as a reviewer), which subscribes you from notifications
2. You submit a review for the PR
3. You get unsubscribed from notifications and don't get emails as the PR's author responds to your review

Before the review, subscribed:
![image](https://user-images.githubusercontent.com/1492044/81329251-45321800-906c-11ea-8173-11cbdbbef435.png)

After the review, unsubscribed:
![image](https://user-images.githubusercontent.com/1492044/81329270-4b27f900-906c-11ea-89ce-3967bcac5264.png)

cc @ampproject/wg-infra

**Comment by gmajoulet** [comment]
Friendly ping @rcebulko 

This happens to me almost daily and has been creating confusion in our review process. Is there any way we can help getting a fix?

**Comment by rcebulko** [comment]
Hi @gmajoulet , sorry for not getting to this sooner. I poked at this last week but realized I couldn't trigger it for myself and it fell behind other work.

Initial investigation suggests this is a result of the PR changing, and the bot editing the comment to remove reviewers on the PR. When that happens, even if you've left a review, GitHub's Activity/Notifications logic appears to be "since the current notification reason is a mention, and that mention is gone, you must no longer need to be notified at all"

The cleanest fix to me is to just allow notification comments to include reviewers. It won't add too much to the comment and shouldn't cause any additional notifications, since the user would already have been added to the thread.

**Comment by gmajoulet** [comment]
Thank you for the update Ryan! Let me know when/if you need any help to repro or test a fix :))

**Comment by rcebulko** [comment]
This fix will likely come at the expense of https://github.com/ampproject/amp-github-apps/issues/473, which was the initial FR to remove reviewers from the comment. Doing so while accounting for the order of events on the thread in such a way as to ensure notifications aren't impacted would introduce a significant degree of complexity (the current approach only requires the current state of the PR, not the full conversation thread). If it becomes a bother we can re-address that duplication separately
