### ISSUE TITLE
Intent to implement: Add WhatsApp to amp-social-share

### ISSUE THREAD

**Issue by chrisloftus** [ampproject/amphtml#2831]
Hey,

I saw that someone suggested adding WhatsApp to amp-social-share in #2794. I thought this would be cool to add, so I've done some of the work - https://github.com/chrisloftus/amphtml/commit/6ccf3a1b8af9b7a5691ba39c8efd08311da94b5e

However, WhatsApp URL [scheme](https://www.whatsapp.com/faq/en/iphone/23559013) doesn't have a `url` parameter, only `text`. So I think we should append the url to the end of the text. But I'm not sure what the best way to implement this in `amp-social-share-config.js` would be - if anyone could give me a pointer that would be great.

**Comment by mkhatib** [comment]
Hey @chrisjlee 

You're right, the current setup is very limiting because this expects the endpoint to want parameters. We're working on redesigning the `amp-social-share` implementation, so this might change to allow more extendability.

In the meanwhile, with your current setup you probably can drop the url parameter from whatsapp config and just append the URL to the text field in the configuration.

```
<amp-social-share type="whatsapp" width="60" height="44">
   <script type="application/json">
     {
       "text": "The AMP Project - https://example.com/artilce/1234",
       "attribution": "amphtml"
     }
   </script>
</amp-social-share>
``` 

This will then be up to the publisher what to include in the "text" configuration.

One of the things we're looking into is allowing [var substitution](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md) in amp-social-share. Another is to allow extending `amp-social-share` to more providers without the need to going through the process of configuring new providers on AMP itself.

**Comment by chrisloftus** [comment]
@mkhatib Thanks for the reply, really appreciate it.

I thought about not having a url parameter and then I thought that users wouldn't be able to specify a url different from the current page. If that's okay for now, I'll remove the param and maybe it could be mentioned in the docs (appending the url to the text).
