### ISSUE TITLE
amp-script "terminated due to illegal mutation" glitches the chrome profiler

### ISSUE THREAD

**Issue by dgilman** [ampproject/amphtml#28361]
## What's the issue?

I have an amp-script that is doing an excessive amount of DOM mutations, some possibly illegal, and the amp-script runtime wants to kill it after some time. Here are the console log messages:

```
[amp-script] Blocked 929 attempts to modify DOM element attributes or styles. For variable-sized <amp-script> containers, a user action has to happen first.
[amp-script] Blocked 29333 attempts to modify DOM element children, innerHTML, or the like. For variable-sized <amp-script> containers, a user action has to happen first.
[amp-script] amp-script[src="/static/simple-datatables.js"].js was terminated due to illegal mutation.
```

I didn't write the amp-script code that's running inside the web worker, so I decided to break out Chrome's JS profiler to try and see what it was doing wrong.

The bug is that the amp-script web worker is unable to be profiled via dev tools and any attempt to get any sort of trace out of the thing has failed. This may be a bug in Chrome itself, I am not sure, but I thought I'd start here.

I've tried starting the profiler and letting amp-script kill the web worker. The trace starts successfully but Chrome isn't stopping the trace when the worker dies resulting in a glitchy profile that can't be stopped or viewed.  I've also tried starting the profiler and attempting to stop it before amp-script gets a chance to kill the web worker and I still get the unkillable profile problem.

## How do we reproduce the issue?

https://dgilman.xen.prgmr.com/webworker/

Click on a header a few times to trigger the amp-script and wait 10+ seconds for the web worker to be terminated

## What browsers are affected?

Latest stable chrome 81

## Which AMP version is affected?

2005050322001

**Comment by samouri** [comment]
Hi @dgilman,

The error you are seeing regarding illegal mutations are not referring to any restraint that regular [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Worker) have.  AMP in general attempts to remove any possible [layout shift](https://web.dev/cls/) that could occur on a webpage. 

In order to minimize cls, we place a restriction on `<amp-script>` that mutations may only occur if the element has a fixed size or if it were immediately preceded by a user gesture. 

You can see the full explanation in the [amp-script](https://amp.dev/documentation/components/amp-script/#user-gestures) docs. The page you've linked to has an `amp-script` with a container layout (not fixed size) and therefore mutations are not allowed unless preceded by a gesture.

I hope that helps!

**Comment by dgilman** [comment]
I really think that error message is slightly misleading.  I gave you the link above that triggers the errors reliably.  However, I have other pages whose amp-script markup (including the same amp-script container layout) is much smaller (fewer rows in the table) and the whole thing works perfectly, no errors in the console, the javascript works well, the table gets mutated.

I have a feeling something is up with the performance and timeout of the web worker and that's triggering the misleading error messages in the console above.  Partially because it works on small tables but fails on large ones, but also because the underlying code includes this [beautiful, artisanal implementation of bubblesort](https://github.com/fiduswriter/Simple-DataTables/blob/master/src/helpers.js#L68).  That's why I'm interested in profiling it to see exactly what's going on in that web worker.

**Comment by dgilman** [comment]
And if this action should be denied because of amp-script rules I guess the working examples are a bug of their own.

**Comment by samouri** [comment]
>And if this action should be denied because of amp-script rules I guess the working examples are a bug of their own.

I haven't read up on the linked data-tables library, but assuming it performs dom mutations on initialization then this is indeed intended behavior.

Which working examples are a bug? Can you include a link to one?

**Comment by dgilman** [comment]
https://dgilman.xen.prgmr.com/webworker_small/

That's the same code as the earlier example but with 90% of the `<tr>`s removed. You can click the headers there and it'll sort correctly and amp-script won't try to block anything.  If it was doing illegal operations you're not catching it and if they aren't you're giving a misleading warning.

**Comment by samouri** [comment]
Seeing the two behaviors side by side, you are right that it is related to performance. I added `#development=1` to the url so that I could see the logging statements from `worker-dom`.

Seems like the bigger version takes a _long_ time to calculate the necessary mutations. After a user gesture there is a 5s window of time where you may create dom mutations, after which they are deemed "illegal" by amp-script.  Since it takes longer than 5s, it kills the worker.

Another way to confirm this is by setting `layout=fixed height="10000px" width="600px"` on the `<amp-script>` element. It won't terminate the worker, but performance will still stink.

**Comment by samouri** [comment]
@dgilman, do you think theres any further action to take here? If not, I'll close this issue

**Comment by dgilman** [comment]
It may be nice to do a console.log() when the five second timeout is hit.

There was still my original issue with being unable to profile the web worker. If your code is using the web worker API correctly I'd appreciate your help navigating the bug tracking system to get the issue over to the Chrome people in the right place.

**Comment by samouri** [comment]
That would mean firing a console.log 5s after every user interaction, which would not be useful. We have no way of knowing which mutations were a direct result of which user actions,.

As for the profiling a web worker, its actually possible to do that right now in the performance pane.  Instead of looking at "main thread" you have to look at "Worker", see this screenshot:
<img width="1501" alt="Screen Shot 2020-05-27 at 1 50 30 PM" src="https://user-images.githubusercontent.com/4656974/83055142-737a9600-a021-11ea-9a6e-48c6c1400787.png">

**Comment by dgilman** [comment]
Looks good to me
