### ISSUE TITLE
Story not getting a touchend event as users swipe in a player

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#28425]
As users swipe away from a Story in a viewer, the Story is paused on touchstart. In certain viewers (cf b/), it seems that the story does not get a touchend, and does not resume the playback/show the system UI again.
We should force show the system UI on `visibilitystate` change to `visible`.

cc @ampproject/wg-stories 

Video at b/156537752

**Comment by mszylkowski** [comment]
Stories do not only hide the system UI but also get paused since the touchEnd usually cancels. Will send PR soon

**Comment by gmajoulet** [comment]
Paused is fine as in this specific case, the story is hidden by the viewer.

**Comment by mszylkowski** [comment]
Yeah, I meant that swiping away pauses the story but (from my tests) when coming back to a story it does not unpause from that "long press" that never gets touchended. Since we want to resolve the long press, I used touchend from resume_() instead of just changing the visibilityState (as explained in the PR) because there's some state management that needs to stay consistent. Check PR for more details!
