### ISSUE TITLE
Design Review 2020-07-01 20:00 UTC (AMP.goBack)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#28469]
Time: [2020-07-01 20:00 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2020&month=07&day=01&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20200701T200000Z/20200701T210000Z&details=https%3A%2F%2Fbit.ly%2Famp-dr))
Location: [Video conference via Google Meet](https://bit.ly/amp-dr)

The AMP community holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc or issue by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by mrjoro** [comment]
The Infrastructure and Outreach Working Groups will be presenting their [periodic update](https://github.com/ampproject/meta/wiki/Working-Group-Updates) at this Design Review (10-15 minutes).

/cc @ampproject/wg-infra @rsimha 
/cc @ampproject/wg-outreach @sebastianbenz

**Comment by samouri** [comment]
I'd love to discuss a proposal to enable `AMP.goBack` to perform cross-document navigation: https://github.com/ampproject/amphtml/issues/28751

**Comment by lannka** [comment]
Notes for AMP.goBack

Justin:
- Origin page it's ok to have this. 
- What about Viewer case? what the behavior will be? is it going to close the iframe?
- Jake will do some more research to make sure it works in Viewer

Will:
- remember that the Viewer case was the reason it got stalled. because Viewer manipulate the history stack in its own way
- probably fine to do though, check with Dima about history manipulation in iframe
- more concern about changing the default behavor of AMP.goBack. standard procedure will be not to change the existing public API especially that it's not versioned. New action is preferred


@rsimha @sebastianbenz please update this thread once you have your updates ready.

Happy independence day!

**Comment by samouri** [comment]
Thank you for taking notes @lannka!

**Comment by mrjoro** [comment]
@rsimha @sebastianbenz please update this issue with links to the WG updates when they are ready.

**Comment by mrjoro** [comment]
@rsimha @sebastianbenz please update this issue and the [Working Group wiki](https://github.com/ampproject/meta/wiki/Working-Group-Updates) with links to your updates.
