### ISSUE TITLE
Validate .renovaterc.json when changed

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#28473]
The `renovate` package ships with [`bin/config-validator.js`](https://github.com/JamieMagee/renovate/blob/master/bin/config-validator.js), which does exactly what you'd expect. It turns out, we've had some configuration settings (`dependencies: { enabled: true }`) that did nothing; as well as recent PRs which updated the configuration and broke renovate bot. We should incorporate this config validation as a new build target to double-check any changes to the renovate config.

/cc @rsimha

**Comment by rsimha** [comment]
Agree that this check will be useful.

Context: The [config setting](https://github.com/ampproject/amphtml/blob/6a26555d8d72c53de754e6b2dab29bbd14a91965/.renovaterc.json#L8-L10) that disabled `dependencies` was valid as of last year. Since then, it appears to have changed. [Then](https://github.com/renovatebot/renovate/blob/50e9a85961fca834d171f9ae222facd84e0f38b2/website/docs/configuration-options.md#enabled). [Now](https://github.com/renovatebot/renovate/blob/bb85f46b635af91d4512df7686b1655754c49b05/docs/usage/configuration-options.md#enabled).
