### ISSUE TITLE
Design Review 2020-07-15 15:30 UTC (cross origin iframe, wg-caching)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#28471]
Time: [2020-07-15 15:30 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2020&month=07&day=15&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20200715T153000Z/20200715T163000Z&details=https%3A%2F%2Fbit.ly%2Famp-dr))
Location: [Video conference via Google Meet](https://bit.ly/amp-dr)

The AMP community holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc or issue by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by mrjoro** [comment]
The Validation & Caching Working Group will be presenting their [periodic update](https://github.com/ampproject/meta/wiki/Working-Group-Updates) at this Design Review (10-15 minutes).

/cc @ampproject/wg-caching @Gregable

**Comment by zhouyx** [comment]
I'd like to discuss cross origin iframe usage in AMP.

**Comment by twifkak** [comment]
> Devin (was that Devin?): amp-script already has all the security is already (meta tag SHA check)

Yes, it was me. I was noting the required [script hash](https://amp.dev/documentation/components/amp-script/#security-features) for cross-origin amp-script (added in #23691). If talking about making components use amp-script as a backend, then it seems like the spiritual analogue here would be hard-coding the script hash into the amphtml repo. This means any updates to the script would have to be at a new URL, followed by a commit of the new URL and hash to the amphtml repo. This eliminates the need to unobfuscate the code, but doesn't allow for faster release cycles than AMP. But maybe my spiritual analogue is incorrect.

**Comment by zhouyx** [comment]
Thanks all. 

I looked at the script hash requirement for cross-origin amp-script, based on https://github.com/ampproject/amphtml/pull/23691#issue-304415301 that's added to mitigate use of amp-script as a script gadget. 
Personally I think the fact that the script source is fixed based on the extension or the publisher's source origin already mitigate such concern a bit. Because one cannot use the component to load their own script. 
@joshfg what do you think about the script hash requirement and the release cycle restriction?

@dvoytenko I did some research regarding running iframe in separate thread, the closet thing I can find is Chrome's [site isolation](http://www.chromium.org/Home/chromium-security/site-isolation) project, which push iframe from different domains to new processor. From what I learnt, the feature was introduced for security reason, and is only partially enabled to Android Chrome due to memory usage concerns.

**Comment by joshfg** [comment]
> @joshfg what do you think about the script hash requirement and the release cycle restriction?

Unfortunately I don't think either of these would work for our use case.

Just to give some background for anyone else reading: we have [an open design proposal](https://docs.google.com/document/d/1IHCjfuQCGcDmptJZFXWA9qNj8A0hdmsciDi7P7hBgjo/edit?ts=5ed00973#heading=h.9urrv8a4mxx2) for an AMP component, which we've been discussing with Yuxuan. We think that it would be an option for us to open source most of our JS SDK in an AMP component, however there is a dynamic part of our script which we build for each publisher. This means that when a publisher deploys our component, they'd need to pass their Permutive publisher ID as configuration, and our component would load the dynamic part from our CDN (e.g. from `https://cdn.permutive.com/<publisher_id>.js`). This dynamic part is an important aspect of our product: it enables us to decision using data on-device which is better for speed, privacy and reducing the amount of data that needs to be sent into the cloud.

For our use case, I see two problems with the script hash requirement & release cycle restriction:
1. The dynamic part of our script is per publisher, it would be infeasible for us to maintain a complete list of script hashes (for every publisher who is a customer) in our component in the AMP repo.
2. This publisher specific script is highly dynamic. We rebuild it for the publisher, whenever the publisher changes their configuration in our dashboard. This can happen very frequently (e.g. daily, or more). We need these changes to go live quickly for our product to be effective, so waiting 1-2 weeks for the next AMP release wouldn't work here.

What are these security measures intending to achieve? If we were to have our own AMP component loading this script, the origin would be fixed in the component itself (to `cdn.permutive.com`) so it should not be possible to load a script from another origin.

**Comment by twifkak** [comment]
Thanks for clarifying the use-case. It's possible that, as @zhouyx says, the [script gadget](https://github.com/google/security-research-pocs/tree/master/script-gadgets) concerns are mitigated elsewise; I haven't read up on the details yet (nor should my saying "yes this seems secure" be considered authoritative as I'm not an expert in this area -- cue the old saying about proof of absence vs absence of proof). I just wanted to point out something worth considering.

**Comment by dvoytenko** [comment]
@zhouyx 

> I did some research regarding running iframe in separate thread, the closet thing I can find is Chrome's site isolation project, which push iframe from different domains to new processor. From what I learnt, the feature was introduced for security reason, and is only partially enabled to Android Chrome due to memory usage concerns.

Yes. That's the one I meant. Do you see any reference on how one can achieve a separate thread for site isolation for a `about:blank` iframe when the `sandbox="allow-same-origin"` is NOT configured?

And, what about a worker with a `importScripts('https://3p.net/some-script.js')`? That's a guaranteed thread with some isolation that we should have already some experience with, I believe.

**Comment by zhouyx** [comment]
> Do you see any reference on how one can achieve a separate thread for site isolation for a about:blank iframe when the sandbox="allow-same-origin" is NOT configured?

I couldn't find anything about `about:blank` iframe. And site isolation seems to only care about pushing site to different process not separate thread. Here's what I read

"To support a site-per-process policy in a multi-process web browser, we need to identify the smallest unit that cannot be split into multiple processes.  This is not actually a single page, but rather a group of documents from the same web site that have references to each other.  Such documents have full script access to each other's content, and they must run on a single thread, not concurrently.  This group may span multiple frames or tabs, and they may come from multiple sub-domains of the same site."
"In addition, top-level documents may contain iframes from different web sites.  These iframes have their own security context and must be rendered in a process based on their own site, not the site of their parent frame."

>And, what about a worker with a importScripts('https://3p.net/some-script.js')? That's a guaranteed thread with some isolation that we should have already some experience with, I believe.

I believe the worker when created runs in a separate thread. But scripts imported by `importScripts` runs in the same thread as the worker, Loading 3p scripts leads to security concerns, and `importScripts` is blocked in worker dom.

**Comment by dvoytenko** [comment]
But worker dom still uses a cross-origin script, no? The method of fetching it might be different, but isn't the end result still similar?

**Comment by zhouyx** [comment]
True. 
Here's my understanding of how worker runs cross-origin scripts in AMP today. `<amp-script>` fetch the cross-origin script, verify the script hash is the same as the one provided in meta. (This is the meta tag SHA check mentioned above) and then run cross-origin script in a sandboxed web worker.
And yes that's a guaranteed thread with some isolation, mostly due to the sandboxing strategy. We can definitely leverage that to run 3P vendor scripts if we could get rid of the [script hash](https://amp.dev/documentation/components/amp-script/#security-features) safely.

**Comment by dvoytenko** [comment]
I see. It looks like this hash is used more for integrity than security? I.e. no one on the serving stack validates the cache, do they? Assuming the integrity is less critical with a 3p service, what other security nuances do we need to validate for a worker?

I think to sum it up, we could explore two options:

1. A worker with all 3p scripts. A guaranteed single separate thread for all related vendors. But security parameters might be unsatisfactory.
2. A x-origin thread. It could be an iframe running on `getDefaultBootstrapBaseUrl`. Or maybe even it could be a `srcdoc` iframe without `sandbox=allow-same-origin`. It should check off security boxes. But it might be hard to guarantee thread isolation.

**Comment by dvoytenko** [comment]
And the nice part here, potentially, is that the API to both a worker and thread would probably be exactly the same.

**Comment by zhouyx** [comment]
Based on https://github.com/ampproject/amphtml/pull/23691#issue-304415301, the hash is added to mitigate use of amp-script as a [script gadget](https://github.com/google/security-research-pocs/tree/master/script-gadgets).

In the case of multiple 3P scripts, are you suggesting running them in one worker/iframe? Or the AMP runtime will queue them and run each one in a new worker/iframe.

>And the nice part here, potentially, is that the API to both a worker and thread would probably be exactly the same.

That'd be nice. The API should remained the same regardless of the underlying design.

**Comment by dvoytenko** [comment]
> That'd be nice. The API should remained the same regardless of the underlying design.

I meant mostly that it's just `postMessage/onMessage` in both cases.

> In the case of multiple 3P scripts, are you suggesting running them in one worker/iframe? Or the AMP runtime will queue them and run each one in a new worker/iframe.

Yes to former. One worker/iframe - all 3p scripts for the analytics use cases. It's basically a way to give the 3p scripts a restricted singular access to the doc but in a separate thread.

> Based on #23691 (comment), the hash is added to mitigate use of amp-script as a script gadget.

Can't say that I understand it all. But in our case the scripts will not be allowed to contribute any DOM and the cross-origin API is strictly `postMessage`.

**Comment by zhouyx** [comment]
Re: The running 3p scripts in workers discussion. We proposed an I2I #30193. Feedback is welcome!

Let us know if the proposal will help with your use case in AMP given that iframe in the background is not allowed.
