### ISSUE TITLE
Make sure cherry-picks to beta channel on Mon/Tues are included in the next beta channel release

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#28480]
Follow-up to https://github.com/ampproject/amphtml/issues/28307#issuecomment-629338702.

> The problem is cherry-picks to RC on Monday or Tuesday won't be included in canary (which is "cut" on previous Friday).
> 
> So AFAICT we need two things:
> 1. New guidance for release cops -- either use a later nightly or cherry-pick immediately into the new canary
> 2. An automated check that cherry-pick commits to release N are included in release N+1

**Comment by rsimha** [comment]
> The problem is cherry-picks to RC on Monday or Tuesday won't be included in canary (which is "cut" on previous Friday).

Drive-by comment with terminology update for posterity:
- The rc (release candidate) channel is now called beta channel
- The manual step of cutting the `canary` branch has been replaced by the automated step of cutting the `nightly` branch

That aside, +1 to both your suggestions 😃

**Comment by danielrozenberg** [comment]
I prefer to modify the cherry-picking instructions instead of instructing to use a later nightly - since nightly builds are cut at ~midnight (PT) there's still going to be a small skew, so this wouldn't solve the problem for when a fix to some P0 issue is merged between midnight and Tuesday morning

As for the automated check for cherry-picks, I'd rather block this for now on @estherkim's planned work on automating cherry-picks - once that exist, we can tack-on the related check based on machine-parsable metadata that the automation provides

For now, we'll just have to be careful.

@estherkim - where are we on cherry-pick automation?

**Comment by estherkim** [comment]
I'm writing up / thinking through the design right now. Solving this is one of its goals. Design review coming soon!

**Comment by danielrozenberg** [comment]
@estherkim you started working on this, correct?

**Comment by estherkim** [comment]
Yup! Underway.

**Comment by estherkim** [comment]
Forgot to update this - it's fixed via cherry-pick automation 👍
