### ISSUE TITLE
Virtual keyboard pops up when opening an amp-lightbox with an amp-date-picker

### ISSUE THREAD

**Issue by Sitanderkumar** [ampproject/amphtml#28607]
URL: https://m.cheapoair.com/flights/amp?preview=1

When a user inputs a depart or return date into the fullscreen amp-date-picker, the keyboard pops up and covers the calendar:

![image](https://user-images.githubusercontent.com/36926473/83135567-a09f7500-a103-11ea-821d-bcb25268dd80.png)

(Note: it can only be replicate  on physical device) 

@mdiblasio @niallkennedy @cvializ

**Comment by alanorozco** [comment]
Thanks for reporting this, @Sitanderkumar.

I've spent some time debugging this and can provide more information and an okay-ish workaround, but not a fix yet.

A reduced case for this is [like our provided example for using `[fullscreen]`](https://go.amp.dev/c/amp-date-picker/#fullscreen), composing the datepicker inside an `<amp-lightbox>` which is triggered when one of the reference fields is tapped:

https://github.com/ampproject/amphtml/blob/716397173873600f1ead42883843f25f42a2f623/extensions/amp-date-picker/amp-date-picker.md#L504-L520

The virtual keyboard pops up because the field gains focus, but the field is visibly covered by the opened lightbox.

## Publisher workaround

You can insert an `[autofocus]` element in the lightbox to trap focus away from the field:

```html
<amp-lightbox ...>
  <button autofocus></button>
</amp-lightbox>
```

Couple of caveats:

- The keyboard will pop up and pop back in briefly on the first focus. This allows the component to properly fill the screen, but the transition may be jarring.

- This is weird on screenreaders if the button is empty. You could make this button functional and label, like a `[ Today ]` button or a way to close the lightbox.

## Component fix

When using `[mode=overlay]`, the component already works around this problem by flipping `[readonly]` on the input field ([`addTouchReadonly_`](https://github.com/ampproject/amphtml/blob/b6313e372fdd1298928e2417dcc616b03288e051/extensions/amp-date-picker/0.1/amp-date-picker.js#L1011)). This can be employed for this use case, with a few caveats:

- The component needs to detect it's inside a lightbox that's opened when one of the attached fields is tapped. We can't use `mode=overlay` as a signal here since it's forbidden when using `[fullscreen]` (it's overall a different experience).

- Events need to be attached before the element is laid out, possibly on `buildCallback`. (This is because the element is laid out after the lightbox is opened, so there's a race here for flipping `[readonly]`).

Realizing that events are not attached until this occurs, I have a couple of open questions for UX:

- The datepicker updates with the input date when it's edited. The calendar pops up on tap, but _not_ on focus, which could be gained by tabbing in a parent form and editing the field. We should probably allow this to be edited like it does with `[mode=overlay]`, just by attaching events on build time rather than layout time.

- I'm not sure how focus should be trapped/returned for good a11y. If @caroqliu can chime in here I'd appreciate it!

**Comment by caroqliu** [comment]
Played around with this with the VoiceOver feature -- from what I can tell the a11y user flow isn't great but also isn't worsened by the proposed fix. The status quo for the lightbox feature of datepicker is that on opening the lightbox, the user is not notified but the dates are focusable and selectable after opening the lightbox. Closing the lightbox is not ergonomic since the `Esc` key is the only way to do it, we could either modify amp-date-picker to provide an a11y only close button in this view or rely on amp-lightbox to create it (along with blur-to-close) with #27114.

**Comment by alanorozco** [comment]
Awesome, thanks for your input @caroqliu!

> Closing the lightbox is not ergonomic since the Esc key is the only way to do it, we could either modify amp-date-picker to provide an a11y only close button in this view.

Since this approach maintains status quo, let's consider this an additional a11y improvement.
