### ISSUE TITLE
Expose full version string to ads

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2874]
I think right now ads only see the build-version, but are missing experiments.

Lets thread through the full string, so that they can log by experiment as well.

**Comment by ericlindley-g** [comment]
@cramforce , @erwinmombay — setting this for the next milestone, given the high priority, but feel free to re-slot as appropriate

**Comment by erwinmombay** [comment]
@cramforce qq, should this be a new field on https://github.com/ampproject/amphtml/blob/master/src/3p-frame.js#L76 or can we add it to the object returned by getMode(), also instead of querying the script tag would it be better if we added "version" and "fullVersion" to the AMP_CONFIG object during build/dist time?

**Comment by cramforce** [comment]
I was thinking about `getMode` and I suppose that is reasonable.

For the script tag: I suppose we need that anyway for @zhouyx's work, but it would definitely be better to put into into the `AMP_CONFIG` since that also works for "unversioned" delivery.
