### ISSUE TITLE
I2I: amp-nexxtv-player API change and rename to amp-3qnexx-player

### ISSUE THREAD

**Issue by neko-fire** [ampproject/amphtml#28903]
Update for extension amp-nexxtv-player.

Attribute changes:
- remove data-origin
- remove playlist-masked as streamtype
- remove data-seek-to
- add new attribute data-exit-mode: This Element determines what to show to the user after a Video has ended.

The company nexxtv was aquired by 3Q (https://3q.video/en/) and we want to rename the extension/add new extension as amp-3qnexx-player. 
Is this possible to have both extensions (new amp-3qnexx-player & existing amp-nexxtv-player) included for approx. 6 months in order not to break anything and make users/clients a smooth migration? Or is there an other way to achieve this?

/cc @ampproject/wg-approvers

**Comment by alanorozco** [comment]
Hi @neko-fire. Thanks for filing this issue.

> - remove data-origin
> - remove playlist-masked as streamtype
> - remove data-seek-to
> - add new attribute data-exit-mode: This Element determines what to show to the user after a Video has ended.

If I understand correctly, `playlist-masked` is a possible value for `data-streamtype`?

Since these are all `data-` attributes this should be fine to do. Go ahead with this change unless one of these attributes is required by validation.

Rename/migration should be fine since component usage is under the [deprecation threshold](https://github.com/ampproject/amphtml/blob/master/spec/amp-versioning-policy.md).

**Comment by neko-fire** [comment]
Hi @alanorozco,

correct `playlist-masked` is a possible value for `data-streamtype`. 
In addition I forgot to list `data-client` is replaced by `data-domainid`, which is a required value and needs validation.

If I understood the process correctly, I'll just rename the extension amp-nexxtv-player to amp-3qnexx-player and if amp-nexxtv-player is needed it can be used in an older release? 

many thanks!
