### ISSUE TITLE
Swiping back to a story should restart its active page

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#28927]
When a user swipes to go to the next story, the previous one gets paused. If they swipe back to this story, the active page should be restarted so it plays from the beginning, just like on a regular story page navigation.
Today this causes bugs where navigation is triggered instantly as a user goes back to a previous story.

cc @ampproject/wg-stories

**Comment by cramforce** [comment]
We should definitely rewind the last slide. But also consider not to auto-advance in this case.

**Comment by mszylkowski** [comment]
Would a sufficient check be "started a swipe but never finished, and then the story became active" (if that happens, restart the page)? That's what I'm thinking of doing but not sure how to test it otherwise

**Comment by cramforce** [comment]
I think this could be problematic for folks who swipe by accident and want to get back. We should consider fixing the auto-advance in this case instead. Or only reset when the navigation occurred on the very last slide.

**Comment by mszylkowski** [comment]
In my testing, currently when the auto-advancement from the last page of a story navigates to the next story and then the user swipes back, the last page gets automatically restarted properly. That's what's intended right?

The reason why I suggested the "started a swipe" check is because the way we can detect the user went to the next story with a swipe is that there's a call to touchStart but not Touchend, so in the case where we receive a touchStart, then page becomes inactive, then page becomes active again (without receiving a touchend), then it means the user swiped back to the current story. And in that case, we can restart the advancement for the current page (and the media elements).

**Comment by gmajoulet** [comment]
> In my testing, currently when the auto-advancement from the last page of a story navigates to the next story and then the user swipes back, the last page gets automatically restarted properly. That's what's intended right?

I don't see the page being restarted right now, this is what we should fix.

**Comment by gmajoulet** [comment]
Changed to P1
