### ISSUE TITLE
Document how to get started with writing HTML components

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#2896]
Looks like the [many extensions contributed so far](https://github.com/ampproject/amphtml/tree/master/extensions) have been developed by copy/paste/modify, since the [components spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-components.md) doesn't point to a getting started guide, there's no guide in the [spec directory](https://github.com/ampproject/amphtml/tree/master/spec) and the [DEVELOPING](https://github.com/ampproject/amphtml/blob/master/DEVELOPING.md) doc doesn't touch on developing components.

Would be great to have a guide explaining the build process, the API calls such as `AMP.registerElement`, imports, the `validator-amp-*.protoascii files`, [integration with tests/examples](https://github.com/ampproject/amphtml/pull/2017#issuecomment-184412965) etc.. Thanks!

**Comment by bpaduch** [comment]
I feel like this is well-covered in the [Eng Docs](https://github.com/ampproject/amphtml/blob/master/DEVELOPING.md#eng-docs) that are referenced, particularly: 

- [Life of an AMP](https://docs.google.com/document/d/1WdNj3qNFDmtI--c2PqyRYrPrxSg2a-93z5iX0SzoQS0/edit#)
- [Building an AMP Extension](https://docs.google.com/document/d/19o7eDta6oqPGF4RQ17LvZ9CHVQN53whN-mCIeIMM8Qk/edit#)


If you feel otherwise, please re-open the bug.
