### ISSUE TITLE
Source Map URL's are relative and generate unnecessary requests

### ISSUE THREAD

**Issue by aneeshd16** [ampproject/amphtml#29101]
## What's the issue?

The generated source map URLs are relative, and the browser attempts to load the source map from our server. For example https://cdn.ampproject.org/rtv/012006112352003/ww.js has this at the end of the file:
```
//# sourceMappingURL=ww.js.map
```

The browser attemps to load the source map from `https://<our domain>/ww.js.map` which results in unnecessary 404 requests on our server.

## How do we reproduce the issue?

1. Open the amp-analytics playground - https://playground.amp.dev/?url=https://preview.amp.dev/documentation/examples/components/amp-analytics
1. Open the browser console.
1. Chrome shows this warning - `DevTools failed to load SourceMap: Could not load content for https://playground.amp.dev/ww.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`.
On Safari it shows these **errors**:
```
[Error] Not allowed to load local resource: blob://nullhttps//playground.amp.dev/ww.js.map
[Error] Not allowed to request resource
[Error] Cannot load blob://nullhttps//playground.amp.dev/ww.js.map due to access control checks.
```

## What browsers are affected?

Chrome, Safari, probably all browsers.

## Which AMP version is affected?

Seen in  Version 2006112352003.

**Comment by jridgewell** [comment]
Ahh, this is because we're using  a `Blob` to construct the source code manually. Usually, sourcemaps are relative to their JS's source location (meaning, `cdn.ampproject.org`'s domain). But the `Blob` file is relative your origin, not the location we fetch the blob's text.

We'd need to find/replace the web worker's `sourceMappingURL` and combine it with the fetch location.

Would you be interested in fixing? It just requires a change in https://github.com/ampproject/amphtml/blob/eaaa44e21a281ebf853a3637f885f258f391af52/src/web-worker/amp-worker.js#L107-L109.

**Comment by aneeshd16** [comment]
Hi @jridgewell and thanks for your response! I have opened a PR (https://github.com/ampproject/amphtml/pull/29123) for this. I haven't been able to test this, it would be great if you could help with that.
