### ISSUE TITLE
I2I: Session Id Support in AMP Analytics

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#29324]
## Summary

Analytics vendors use a client-size session id to track an active session. Today AMP provides the `PAGE_VIEW_ID` and the high entropy `PAGE_VIEW_ID_64` that stays the same for a given site during what the AMP viewer defines as a session. The PAGE_VIEW_ID is persisted in RAM. 

The proposal is to support a session id that stays the same for a given site during a time period (e.g. 30 mins). Such session information will be stored in localStorage. 

See #1612 for more context.

#### Macro
`SESSION_ID(opt_expirationTime)`

The above macro will be added to `<amp-analytics>`. 

`opt_expirationTime` is an optional duration in seconds. 1800 (30 minutes) will be used as default value if it is not provided. The expirationTime needs to be in the range of [30, 86400] (30 seconds to one day) due to performance and privacy concerns. 

The returned value will be a random base64 string with a high 128 bit entropy. For example `U6XEpUs3yaeQyR2DKATQH1pTZ6kg140fvuLbtl5nynb`

When retrieved, the stored value will be returned if its set timestamp is within the expiration time, its timestamp will also be updated to the current time. 
If a stored value doesn't exist, or has expired. A new random session id will be generated and stored along with the current timestamp. 

#### Storage

The session id will be stored under localStorage entry `amp-analytics:session-id`. The reason AMP doesn’t allow storageKey customization is to prevent multiple sessions from being created under different names. 

The [localStorage API](https://github.com/ampproject/amphtml/blob/master/spec/amp-localstorage.md) between the AMP page and the AMP viewer will keep unchanged. It’s up to the `<amp-analytics>` service to remove stored value after expiration time.

`opt_expirationTime` is only used when the storage value is read. Since get/set storage value is asynchronous in AMP. We need to make sure that multiple calls to `SESSION_ID` are handled in order. 

#### Multiple Vendors
Since there will be only one session id stored. In the case where multiple vendors are using the `SESSION_ID`, the same id with the same duration will need to be shared. 

## Launch tracker

/cc @ampproject/wg-approvers on adding the storage entry
@ampproject/wg-analytics on the macro design

**Comment by cramforce** [comment]
Is the only difference from the client id that it has an expiration time?

**Comment by zhouyx** [comment]
True. other minor differences include: `CLIENT_ID` supports cid scope, and allows opt-out.

**Comment by cramforce** [comment]
Would this not be subject to `amp-consent`?

**Comment by zhouyx** [comment]
The proposed `SESSION_ID` is no different from `PAGE_VIEW_ID` in terms of opt-out. 
One can choose to use `<amp-consent>` to block `<amp-analytics>` entirely. If that's not the case, the `SESSION_ID` will always be generated and sent. It's then up to the analytics vendors to drop the requests on the server side based on consent information.

**Comment by cramforce** [comment]
Makes sense.

**Comment by zhouyx** [comment]
Cool! I'll take that as one approval : )

**Comment by cramforce** [comment]
No, sorry, I'd like this to be reviewed in design review first. Don't block on me.

**Comment by zhouyx** [comment]
lol agreed. we should review this in design review! 
@mattwelke @querymetrics @msukmanowsky Let us know your feedback on the design. And welcome to join our design review next week. #29260

**Comment by mattwelke** [comment]
In an interesting twist of fate, we ended up going with a 100% at query time implementation for session tracking where we don't even need to store a session ID at all. We're no longer in need of this feature.

But I appreciate it being added and I can see myself using it in the future. It's a nice alternative to worrying about analytical functions and windowing in SQL and you're okay with a fixed session size.

**Comment by adamsilverstein** [comment]
> Actually, we ended up going with a 100% at query time implementation for session tracking where we don't even need to store a session ID at all. We're no longer in need of this feature.

Hey @mattwelke - I'm curious if you could explain the approach you used here a bit more? Are you passing around query variables? Is the code open source?

**Comment by mattwelke** [comment]
@adamsilverstein  I can't share our code, but I can describe the approach.

At the end of the day, what we do with the data collected is worth it in rows in SQL where each row is a session, with a session representing a period of activity by one person where there is no more than 30 minutes of inactivity between events. We accomplished this before using client side cookies that expire in 30 minutes and are continuously renewed. AMP beacons don't support this, so we ultimately changed what we do on the back end to change how we produce these session rows in SQL. Instead of grouping on a "session ID" column in the table containing event rows, we use analytical functions to group by the difference in event time comparing one row to the next. We end up with the same result, except it's all based on event time in the event row only, not the session ID that used to be added to each event row too.

What I meant by what I said above was that I still like the idea of not forcing people to use advanced SQL techniques to accomplish their use case. They make lack the SQL expertise or their use case might not even work well with calculating sessions based on event time in batch to begin with. They may prefer the ability for the client to be the source of truth for a session ID. Implementing this would be useful for them. :+1:

**Comment by emmett9001** [comment]
I'm taking over Parsely's response to this issue for @msukmanowsky, and I'm really excited to see movement on this feature!

The semantics of the session ID macro match pretty well with how Parsely tracks sessions, so in that sense this implementation would fit our use case.

> My main concerns would be the value being propagated to non-AMP pages the same way that CLIENT_ID can.

I'd like to echo this concern from @mattwelke. Parsely's client-side analytics SDK understands both its own native client ID cookie format and the format written by the `CLIENT_ID` macro when a `cid-scope-cookie-fallback-name` is passed to it as documented [here](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/configure-analytics/analytics_basics/). With this approach, the Parsely SDK and the Google AMP component both see the same pool of client ID values instead of each having its own pool, which can lead to duplication in unique client counting. I'm not certain, but I suspect that this fallback cookie approach is what's meant by "supports cid scope" [above](https://github.com/ampproject/amphtml/issues/29324#issuecomment-659733208).

Without the ability to pass a fallback cookie name to the `SESSION_ID` macro, Parsely would have to figure out another way to consolidate session IDs generated by our own client-side SDK and the AMP component. My understanding is that there might be a way to hack together this behavior using the [AMP Linker](https://blog.amp.dev/2018/09/17/measuring-user-journeys-across-the-amp-cache-and-your-website/), but I'm unsure of the implementation details. Certainly, a fallback cookie argument to the `SESSION_ID` macro would make this much simpler for Parsely to adopt.

The other concern we have is around the scope of the `amp-analytics:session-id` localStorage key. From the design document, it seems that a site with multiple AMP analytics integrations (with, for example, Parsely and Chartbeat) would have session IDs shared between these analytics providers. Naive use of this field seems like it might run afoul of privacy regulations like GDPR, though again I'm unsure of the details.

**Comment by mattwelke** [comment]
> The other concern we have is around the scope of the `amp-analytics:session-id` localStorage key. From the design document, it seems that a site with multiple AMP analytics integrations (with, for example, Parsely and Chartbeat) would have session IDs shared between these analytics providers.

This is a good point. Different analytics vendors (and different session tracking use cases within a single analytics vendor) will want different IDs tracked to account for factors like different session lengths. It makes sense that however the session ID is stored, it is namespaced appropriately, like how the fallback cookie name for CLIENT_ID is allowed to be specified so that it won't clash with other cookies.

**Comment by zhouyx** [comment]
Thanks for the feedback! Really good points

> My main concerns would be the value being propagated to non-AMP pages the same way that CLIENT_ID can

AMP Linker can be used to propagate the value during navigation. This will work on non AMP landing page, since it can read the query param and store it however it like. But if the landing page is also AMP, there's currently no way to instruct AMP to write data to the localStorage. I can see a few ways to fix this. 
1. Introduce addition `opt_defaultValue` to `SESSION_ID`, AMP will use the provided default value as the session_id if it can't find one from storage. Here it would be `SESSION_ID(1800, QUERY_PARAM(sid))`
2. Utilize the existing `cookies` feature to write the session_id to cookie on the landing page, then provide an additional `opt_cookieValueOnOrigin`. If provided, AMP will first look for the provided cookie value if the document is served from the origin. Caveat here is this creates different code paths for cache versus origin. 

>The other concern we have is around the scope of the amp-analytics:session-id localStorage key. From the design document, it seems that a site with multiple AMP analytics integrations (with, for example, Parsely and Chartbeat) would have session IDs shared between these analytics providers. Naive use of this field seems like it might run afoul of privacy regulations like GDPR, though again I'm unsure of the details.

I think a good question here is if we find `SESSION_ID` a special version of `CLIENT_ID` or `PAGEVIEW_ID`. 
`CLIENT_ID` is persisted per user per domain and per vendors, `PAGEVIEW_ID` is persisted per user per domain per session (session defined by the AMP viewer). 
`CLIENT_ID` can be used to identify a user, so we introduced scope to separate the id across different third parties. While `PAGEVIEW_ID` is a unique pageview, and that's shared across all third parties. 
My understanding to the `SESSION_ID` is that it should never be used to identify user, and its usage is closer to the `PAGEVIEW_ID`. To mitigate privacy concern, we could reduce the maximum session time from 1 day to a few hours.

**Comment by zhouyx** [comment]
Feedback from the design review

1.  No personal identifiable information would be allowed to be stored via the storageAPI. There's privacy concern with storing the high entropy data, and we need to get privacy review before proceed.
2. Once we get approval from privacy review, we could enlarge the number of session id entries to more than one to satisfy the requirements of multiple vendors. 

The privacy review won't be needed if there's a way to bypass the storage API. Is using sessionStorage an option here? It can't cover cases where the tab is closed, but still provide some session coverage.

**Comment by zhouyx** [comment]
ping @mattwelke @emmett9001 on thoughts of using sessionStorage as a backup option? 
I understand sessionStorage has its limit, but myself as a user don't close tabs that often : )

Another question: Does a lower entropy session id work here? (e.g. 0-10000)

**Comment by emmett9001** [comment]
`sessionStorage` provides slightly different lifecycle guarantees than Parsely's current 30-minute session cookies. In particular, `sessionStorage` of AMP session data would miss the long tail of 30-minute browsing sessions that span multiple tabs on the same website. I don't have hard numbers comparing the prevalence of this type of session to ones that live entirely within a single browser tab, but I suspect that the vast majority of sessions don't span tabs or browser restarts. Thus, I think Parsely could make use of an AMP session implementation based on `sessionStorage`.

Parsely's session IDs have very low entropy, so I don't see a reason that AMP session IDs also having low entropy would cause us any problems.

**Comment by zhouyx** [comment]
Thanks for the feedback! Sounds like `sessionStorage` is not a preferred but somehow acceptable solution : )

I have another idea. The privacy concern is around the AMP's storage API. We could however use the localStorage without this storage API. When the cached AMP is served from within an iframe, the localStorage value set within the iframe can't be persisted and act like sessionStorage. But when the AMP doc is served from the origin (I think that's most likely the case when the user complete a purchase), the localStorage will be used. 
However this will still require special handling when the cached AMP docs generate multiple session ids, while the origin AMP doc stick to one session.  

I'll start the privacy review process with low entropy session id in the meanwhile. It would still be great if we can bypass the storage API and skip the process entirely : )

**Comment by dvoytenko** [comment]
I don't see a lot of issues with using `localStorage` directly, as long as it's a responsible use.

**Comment by emmett9001** [comment]
Any updates on the privacy review?

**Comment by zhouyx** [comment]
Hi @emmett9001 Thanks for reaching out. The decision was to use `localStorage` and not the Storage API. Because no value will be stored to the AMP viewer, we didn't request a privacy review.

**Comment by emmett9001** [comment]
Thanks for the update @zhouyx. Where can I find information about when this functionality will be available? Maybe https://github.com/ampproject/amphtml/issues/1612?

**Comment by emmett9001** [comment]
Any updates @zhouyx?

**Comment by zhouyx** [comment]
Thanks for the reminder. @rebeccanthomas will work on this soon.

**Comment by emmett9001** [comment]
What's the latest, @rebeccanthomas?

**Comment by emmett9001** [comment]
@zhouyx @rebeccanthomas is session_id available in AMP yet? when might we expect it to be if not?

**Comment by jridgewell** [comment]
Yuxuan moved to Youtube. Pinging @lannka to triage.

**Comment by micajuine-ho** [comment]
The @ampproject/wg-components will be taking over this work. @rebeccanthomas Let's figure out when to prioritize this in our next sprint planning meeting.

**Comment by mattwelke** [comment]
Hey folks, I won't be available to provide more feedback because we ended up implementing this server side instead so that we wouldn't be reliant on this feature existing in any web browser framework.

**Comment by colmsnowplow** [comment]
+1 interest in this feature. Excited to see it moving along! :)

**Comment by rebeccanthomas** [comment]
I am posting an update to our initial design which tries to capture all the decisions we have made through our discussions. 

##Summary
Analytics vendors use a client based session Id to track an active session. Currently AMP only provides the `PAGE_VIEW_ID` and `PAGE_VIEW_ID_64` which persist for what the AMP viewer defines as a ‘session’. 

This proposal is for AMP to support a session id which persists on a given site for the length of a given time period (ex. 30 minutes). 

##Session ID Macro
This change would add the a `SESSION_ID(opt_expirationTime)` macro to `amp-analytic`. 

The parameter `opt_expirationTime` is the duration of the session in seconds. If none is provided 1800 seconds (30 minutes) will be used as the default value. This value must be within the range of [30, 86400] (from 30 seconds to one full day).

The session ID value will be a random base64 string with 128 bit entropy. Ex. `U6XEpUs3yaeQyR2DKATQH1pTZ6kg140fvuLbtl5nynb`. 

This value will be returned if the timestamp associated with it is within the expiration time. When returned this timestamp will be updated to the current time. However, if this value does not exist or has expired a new value will be generated and stored. 

This macro will be acting as a special case of the `PAGEVIEW_ID` which is persisted per user per domain per session (as defined by the AMP viewer). 

In this case `SESSION_ID` will be persisted using the defined time period for the session. 

##Storing this Macro
The session ID will be stored using the localStorage API with the key `amp-analytics:session-id`. In order to prevent multiple sessions being created with different names we will not allow customization of this storage key. 

##Multiple Vendors
We will only be storing one session id per user per domain per session, so multiple vendors will need to share the same generated session id. 

##Limitations
The limitations of this implementation is that when a user leaves the site in the viewer and navigates to the site on the origin, if the user does not navigate directly using a link in the viewer, then `SESSION_ID` will not be persisted across these two instances. 

However, if the user does navigate directly we will use a similar method to resolve the `SESSION_ID` between the two as is currently being used for `CLIENT_ID`. 

##Privacy
In order to manage privacy concerns we have decided to store the `SESSION_ID` in `localStorage` and not use AMP’s Storage API which has limitations on what type of data is permitted to be stored. 

##Alternatives Considered
We considered using the Storage API and Session storage instead of the localStorage API however in order to manage the privacy requirements for this functionality.

**Comment by colmsnowplow** [comment]
> We will only be storing one session id per user per domain per session, so multiple vendors will need to share the same generated session id.

How does this relate to `opt_expirationTime` then? Could one vendor's analytics configuration change the behaviour of another vendor's extension?

**Comment by rebeccanthomas** [comment]
With our current design `opt_expirationTime` would be set by the first vendor and the other vendors would simply receive a sessionId based on that. However this is definitely not an ideal circumstance and I am currently rethinking aspects of the design to accommodate this. 

Additionally I wanted to share the outcomes of our design review last week: 
1. In order to avoid storing a full 128 bit string in localStorage we could potentially only store the expiration time and then use a hash of the `CLIENT_ID` as the `SESSION_ID` value. 
    * The tradeoff to this would be a potential delay in outbound navigation
    * In this case the when the `CLIENT_ID` is reset then we would also reset the `SESSION_ID` (need to discuss with vendors)
    * Using linker to connect the viewer and origin pages might cause a performance issue if we attempt to set the localStorage on outbound navigation. 
2. If possible we should use the linker to connect these two on inbound navigation
3. We should hash the sessionId per vendor so that no two vendors have the same ID
