### ISSUE TITLE
How user uploaded images will work with AMP

### ISSUE THREAD

**Issue by jitendravyas** [ampproject/amphtml#2939]
In AMP, it's mandatory to add `width` and `height` attribute of the image as HTML attributes, right? Other its validation give error and AMP version of new articles from the site won't be displayed in the search result.

If we specify width and height attributes on the markup, it's not possible to deliver different resolution images to different devices (unless we use srcset). We use https://www.imgix.com/  and we add this a suffix to the image URL `?auto=format&rect=0,16,1536,512&q=35&w=1280&fm=pjpg` Dynamically, to specify the width and height of the image. I don't know how to make this work with AMP

Also, we use cms to add content to the website. Image's width and height are not always same, so we can't add it in advance. 

Does anyone have any idea, what to do in this condition?

**Comment by dvoytenko** [comment]
@jitendravyas Width and height are not always required and when they do, they do not necessarily mean exact width/height, but could be relative. This depends on the value of the `layout` attribute as documented in the [amp-html-layout.md](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-layout.md), but in short here's what you can do:

1. You can use `layout=responsive` + `width` + `height` - this is the layout that uses width and height to calculate aspect ratio and then sizes the image based on the available width and height. If you know the aspect ratio - this might be the best option. The actual image could be selected from `srcset` depending on the actual width and the device's resolution (DPR). In addition `sizes` attribute can use media queries to refine the actual width.
2. You can use `layout=fill` and put the image in the container that will define width/height in CSS. Then you'll likely have to use `object-fit` CSS. This method is a bit worse since it looses aspect-ratio information. But it's ok in some applications. Just as above, `srcset` can be used to specify the best image for the actual width and resolution.

In both cases, `srcset` is used. Currently we do not provide protocol for dynamic URL generation as it looks like imgix.com is doing.

**Comment by ericlindley-g** [comment]
Closing as answered, but feel free to re-open with bugs or feature requests (General questions can be directed to [stack overflow](http://stackoverflow.com/questions/tagged/amp-html))
