### ISSUE TITLE
[Story video] Limit the number of downgraded videos at a given time

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#29500]
To avoid a "storm of preloads" on all of a Story videos when detecting a rebuffer, we should limit the downgrading to the videos on the next 1 or 2 pages.

This could be done by either:
- passing the `distance` information to the video element, so the bitrate manager can make a decision
- Story media pool could set the `preload` attribute to `none` or `auto` depending whether it wants the sources preloaded

cc @ampproject/wg-stories

**Comment by mszylkowski** [comment]
There is a chance that this happens automatically since the mediapool doesn't load videos that are more than 2 pages away, so they will never call the `resetOnDomChange`. And hopefully, videos managed that are on previous pages are already loaded so the PR in #32600 will prevent them from loading.

Still, let's keep this PR open so we track this as the changes get merged and we can test this.

**Comment by mszylkowski** [comment]
@gmajoulet this doesn't seem to be a problem any more (as I explained in the previous comment). Closing this as there's no necessary work for this to function (as it's already indirectly implemented), but we can reopen if the mediapool implementation changes.
