### ISSUE TITLE
Misleading "The tag 'script' is disallowed except in specific forms." error for JSON+LD script element

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#2966]
If the JSON+LD `<script>` element is placed in the `<body>` vs. `<head>`, the resulting error is:

"The tag 'script' is disallowed except in specific forms."

This has confused a partner today. Here's a small sample reproducing the error:

```html
<!doctype html>
<html AMP lang="en">
  <head>
    <meta charset="utf-8">
    <title>Lorem Ipsum</title>
    <link rel="canonical" href="http://example.ampproject.org/recipe-metadata.html" />
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no,minimal-ui">
    <!-- this style tag is required -->
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style>
  <noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    <script async src="https://cdn.ampproject.org/v0.js"></script>
  </head>
  <body>
    
  <script type="application/ld+json">
      {
        "@context": "http://schema.org/",
        "@type": "Recipe",
        "mainEntityOfPage": "http://example.ampproject.org/recipe-metadata.html",
        "name": "Grandma's Holiday Apple Pie",
        "image": {
          "@type": "ImageObject",
          "url": "http://cdn.ampproject.org/leader.jpg",
          "height": 200,
          "width": 200
        },
      }
    </script>
      ...
  </body>
</html>
```

**Comment by erwinmombay** [comment]
assigning to @powdercloud for review. feel free to reassign

**Comment by powdercloud** [comment]
@Gregable @honeybadgerdontcare - I think we could improve this by having a specUrl for this type of error (GENERAL_DISALLOWED_TAG) - we currently don't. This could point to documentation listing the specific forms. There's https://www.ampproject.org/docs/reference/spec.html#html-tags for instance which would be an improvement over nothing, especially if we clarified which ones need to appear in the head or linked to the more detailed specification.

**Comment by Gregable** [comment]
I think the easy solution in this specific case might be to relax the requirement that the schema.org json blob must be in the `<head>`. The [structured data testing tool](https://developers.google.com/structured-data/testing-tool/) doesn't seem to think that placing this in the `<body>` is a problem, so we should probably allow it too.

In general, generating the correct error message for these is tricky since there are a wide variety of allowable script tags all with very specific, somewhat overlapping rules. We probably reported the errors for this better in the past, but we made a change to be less specific intentionally as most of the errors reported about script tags were confusing custom javascript with an error on one of these more specific variants.

**Comment by Gregable** [comment]
This is now fixed by allowing the SD in the `<body>`.

**Comment by gagadada11** [comment]
There are some reason for these errors:
 1. Plugin contain script --> Just deactive all of plugin step by step to find the plugin issue
 2. Theme wordpress contain script --> just deactive theme wordpress step by step to find the theme wordpress issue
 3. You inserted some javascript on your wordpress --> just check and remove theme
 4. Check Kaspersky Anti-virus on your laptop. Do you install any virus SW like Kaspersky? Because it will auto insert the tag script on your website.
 --> Just check it by view page source. if you see the tag script, then just uninstall the Kaspersky. then can fix the issue.

If you want more detail, can refer to my website ([](https://quanglepro.com/cach-sua-loi-tag-script-is-disallowed-google-amp)/)

--> But i write in Vietnamese, so you can change it into English by google stranslation. Hope it can help you.
