### ISSUE TITLE
Ability to implement "flying carpet"  within AMP-AD component

### ISSUE THREAD

**Issue by damjan25** [ampproject/amphtml#29710]
@lannka I need exactly what is described in this [issue](https://github.com/ampproject/amphtml/issues/15216). I need solution(or workaround) asap. 
What I want to do:
- I want to place parallax  ad into AMP-AD tag (if this would work with fyling-carpet component, that would be perfect
- I want to place the parallax ad(flying-carpet) into amp-ad component because then I can use 1 ad slot for both ad types(parallax ad, normal display ad or video ad) based on config, and then publisher can decide which one he wants to use.

Something like:
```html
<amp-ad width="300" height="250" type="foo">
  <amp-fx-flying-carpet height="300px">
    <amp-img
      src="fullscreen.png"
      width="300"
      height="500"
      layout="responsive"
      ></amp-img>
  </amp-fx-flying-carpet>
</amp-ad>

```

I know that currently that does not work with fyling-carpet but is there a way to make it work with vanilla JS ? 

I tried to implement normal parallax ad inside AMP-AD component but then there is a problem, because you wrap ads inside IFRAME and then that IFRAME does not have access to window scroll position. Do you think it is possible to make it work somehow  with window.postmessage()?

**Comment by lannka** [comment]
Thanks for filing.

> I tried to implement normal parallax ad inside AMP-AD component but then there is a problem, because you wrap ads inside IFRAME and then that IFRAME does not have access to window scroll position. Do you think it is possible to make it work somehow with window.postmessage()?

What ad serving infra are you relying on? Are you open to use AMPHTML ads, which can achieve the parallax effect using amp-position-observer + amp-animation extension? Note that the key restriction of AMPHTML ads is no custom JS allowed in it, e.g. moat.js or things like that.

**Comment by damjan25** [comment]
yeah then AMPHTML ads are no go for me, I need custom JS. 🤔

**Comment by damjan25** [comment]
@lannka do you think it would be possible to use normal parallax ad (made with just using css) inside `<amp-ad>` tag and somehow provide scroll information from parent into the ads iframe ? 🤔

**Comment by lannka** [comment]
The concern is performance.

If the ad itself is AMP, we make sure it doesn't do any CPU heavy thing on scroll events. But for ads in a cross-origin iframe that AMP has no control, there is no such a guarantee.

Currently, there is a postMessage based API named "context.observeIntersection" in the ad iframe that is designed for viewability measurement. The implementation of that API is scroll events based. So theoretically, you can already use that API to calculate the scroll in the ad iframe. However, due to the above performance concern, AMP intentionally delay all scroll events for 36ms  and then group them in a requestAnimationFrame. That latency is OK for viewability measurement, but might not be acceptable for animation.

That's there we stuck.

@ampproject/wg-ui-and-a11y  @dvoytenko for advices

**Comment by damjan25** [comment]
Ok awesome :smile: Do you have any examples/snippets of code for this ? So I could try it and see how the animation looks. If not I will try to build something tomorrow and see if 36ms delay is good enough for animation to look smooth :) Thanks for help, really appreciate it.
