### ISSUE TITLE
[Story Player] Hide close button when tweet is expanded

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#29718]
Web Player close button is hidden when a page attachment is visible, but should also be hidden when a tweet is expanded.

cc @ampproject/wg-stories

**Comment by newmuis** [comment]
I feel like we should expose a state about whether the system layer buttons should be hidden, rather than the player learning all of the intricacies of the format.

e.g. if we introduce a new feature that covers the close button, it's that feature's responsibility to mark that the button should be hidden, rather than every player learning about this new feature and updating accordingly.

WDYT? @gmajoulet @Enriqe @connielei

**Comment by Enriqe** [comment]
Thanks for filing @gmajoulet, it's an edge case I hadn't thought of. 

And yea, I think I agree with @newmuis' thoughts here.

**Comment by gmajoulet** [comment]
Adding this to the sprint project. Nothing urgent but we should get to it soon-ish (next sprint?) as other players expressed interest in it.

**Comment by gmajoulet** [comment]
Clarifying: interest in what @newmuis described of having a unified event :))

**Comment by mszylkowski** [comment]
Somewhat independent of that, I'm making a prototype of expanding interactive components in the same way twits are being expanded. Did we think of another way of closing this screen, such as dragging down?

**Comment by Enriqe** [comment]
> Did we think of another way of closing this screen, such as dragging down?

Yep, being tracked here https://github.com/ampproject/amphtml/issues/28397

**Comment by Enriqe** [comment]
This should be addressed in #30031

**Comment by Enriqe** [comment]
Closed by #30031
