### ISSUE TITLE
Overrides to amp-geo for local testing are broken

### ISSUE THREAD

**Issue by mxdvl** [ampproject/amphtml#29717]
## What's the issue?

The [amp-geo override][amp-geo] is not working, despite being on the AMP [experimental channel][].

[amp-geo]: https://amp.dev/documentation/components/amp-geo/#debugging
[experimental channel]: https://amp-theguardian-com.cdn.ampproject.org/experiments.html

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Enable the [experimental channel] for amp.theguardian.com
2. Navigate to https://amp.theguardian.com/artanddesign/2020/jul/07/excluded-black-architects-southwark-architecture-london#amp-geo=yt (change `#amp-geo=yt` to somewhere else if you're in Mayotte)
3. The `body` class does **not** have `amp-iso-country-yt`. 😲 

## What browsers are affected?

Tested in Chrome 84

## Which AMP version is affected?

First seen in AMP version `2007242032001`.
It was working fine two weeks ago.

cc. @jeteve for visibility.

**Comment by jeteve** [comment]
@mxdvl 

The following URL seems to have the right class against the body?

https://amp-theguardian-com.cdn.ampproject.org/c/s/amp.theguardian.com/artanddesign/2020/jul/07/excluded-black-architects-southwark-architecture-london#amp-geo=yt

**Comment by jridgewell** [comment]
Hi @mxdvl,

There's a bit of a misunderstanding about the canary opt-in process. The URL you've linked to (https://amp-theguardian-com.cdn.ampproject.org/experiments.html) would enable canary when the HTML is hosted by `https://amp-theguardian-com.cdn.ampproject.org`.

But, you're trying to enable for `https://amp.theguardian.com`. To do so, you need to go to https://cdn.ampproject.org/experiments.html.

This is caused by the `__Host` cookie we use to do the opt-in. When you use https://amp-theguardian-com.cdn.ampproject.org/experiments.html, we're setting the cookie for the `https://amp-theguardian-com.cdn.ampproject.org` domain only. But on your HTML page, you're making a request to `https://cdn.ampproject.org` for the `v0.js` file. So, the `__Host` cookie won't be sent. Using https://cdn.ampproject.org/experiments.html sets the cookie for `https://cdn.ampproject.org`.

**Comment by mxdvl** [comment]
Thanks @jridgewell for the clarification. This seems a little at odds with the information on the [experiments.html][] page

> Experiments can no longer be enabled on the top-level cdn.ampproject.org/experiments.html. They must be toggled on the specific subdomain e.g. www-example-com.cdn.ampproject.org/experiments.html.

As it looks like the `__Host` header is not respected on `https://cdn.ampproject.org`. What helped me debug locally was adding the [`optin=experimental` query parameter][optin] has been the easiest, see code below. I guess it would also have been possible to serve these files locally, so if I get around doing that I'll add details here for future travellers.

[experiments.html]: https://cdn.ampproject.org/experiments.html
[optin]: https://github.com/ampproject/amphtml/blob/master/contributing/DEVELOPING.md#opting-in-to-pre-release-channels

### Locally working code example
 
``` html
<script async custom-element="amp-geo" src="https://cdn.ampproject.org/v0/amp-geo-0.1.js?optin=experimental"></script>
```
