### ISSUE TITLE
[Animation presets] Desktop panels mode, start animations after page transition

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#29753]
Animations currently play while the desktop panel is transitioning. 
They should start after the page is done transitioning.

cc @ampproject/wg-stories @hongwei1990

**Comment by gmajoulet** [comment]
It's a bit tricky because we do want videos to start playing as soon as the transition starts, otherwise you get gaps in playback/audio.
The animation could potentially be synchronized with the videos, and they'd get out of sync if we delay them.

It's a bigger conversation, but because of this and other multi-page animations issues, I think we should start considering killing the desktop panels carousel animation.

**Comment by processprocess** [comment]
There might be a different kind of transition that still gives the user a hint that the page moved and where it came from 
but doesn't require the entire movement.

**Comment by gmajoulet** [comment]
Ooooh that's extremely interesting! What do you have in mind?

**Comment by processprocess** [comment]
Something that involves not animating the active page but subtly animating the inactive pages, hinting that they used to be in the active state.
I think the tricky part will be to not draw attention to the inactive pages when they animate.

**Comment by samitron7** [comment]
What about just capturing the page position (ie center of viewport) and play animation only when the page is located in center of viewport. So the video can still start as soon as the page transition starts but animation only plays when the page is in the center (unless I'm not seeing any other video considerations).

**Comment by processprocess** [comment]
This has been resolved as part of #35267
