### ISSUE TITLE
Flaky test: amp-carousel type=carousel with single image 

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#29783]
![image](https://user-images.githubusercontent.com/6694512/89926950-99044e00-dbd3-11ea-95ba-3b0060364fc4.png)

Following up with skip PR. @ampproject/wg-ui-and-a11y can you please take a peek at this?

**Comment by krdwan** [comment]
FYI @caroqliu 

Looks like there's a flaky test in amp-carousel which we're skipping over.

**Comment by caroqliu** [comment]
@krdwan Thanks for the heads up! Can you take point and debug this?

**Comment by rcebulko** [comment]
Related: https://github.com/ampproject/amphtml/issues/30661

**Comment by samouri** [comment]
@rcebulko: I believe I fixed this in https://github.com/ampproject/amphtml/pull/30933. Do you know if there is a way to see test runs for a specific test over time in Travis so that we can close both this and https://github.com/ampproject/amphtml/issues/30661?

If not, then I vote lets close them pre-emptively and reopen if people notice they are failing again.

**Comment by samouri** [comment]
Ryan just pointed me [here](http://amp-test-cases.appspot.com/test-results/history/e773cd70eb0181c8806f6b2d742dd92f). Closing 🎉

**Comment by krdwan** [comment]
> Ryan just pointed me [here](http://amp-test-cases.appspot.com/test-results/history/e773cd70eb0181c8806f6b2d742dd92f). Closing 🎉

Awesome thanks @samouri !!!
