### ISSUE TITLE
amp-autocomplete: suggestions not available on `lightboxOpen` despite focus

### ISSUE THREAD

**Issue by askmeoffers** [ampproject/amphtml#29894]
We are using amp autocomplete inside the amplightbox. we are using lighboxOpen to make a default focus to the search box, that is working fine but we have another code that loads the default data when we have a focus on the searchbox and when there is no input to the search field. which also works fine when we click on the search box and give it a focus.

The issue is that the combination of amplightbox open focus to the ampautocomplete field is not triggering the json data fetch based on the empty value of the input box which it should do.

manually focusing on the searchbox triggers the default search whereas focus made by lightboxOpen.searchbox.focus is not invoking the same behaviour of default search. 

\\code snippet for the above 

<amp-lightbox id="my-lightbox"
  layout="nodisplay" on="lightboxOpen:searchtopbox.focus">
  <div class="lightbox"
  tabindex="0"> 	  <a href="#" class="close" on="tap:my-lightbox.close"
    role="button" > X</a>
    <div class="cntr">
		
	<amp-state id="dynamicsrc"><script type="application/json">"0"</script></amp-state>   
  <amp-autocomplete
					
					
    on="select:AMP.setState({valinp:''}),AMP.navigateTo(url=event.value,target='_top');"
			
         filter-value="serdata"
         min-characters="0"
         filter="none" 
			class="sr-r-h -auto"		
         src="<?php echo site_url().'/?action=get_search_def'; ?>"
         query="searchtopbox" 
         [src]="(dynamicsrc == '1')?'<?php echo site_url().'/?action=get_search_list'; ?>':'<?php echo site_url().'/?action=get_search_def'; ?>'"> 
      <input type="text" on="input-debounced:AMP.setState({ dynamicsrc: event.value.length == 0 ? 
          '0' : '1'});input-throttled:AMP.setState({vali: event.value})" [value]="valinp"
         name="queryInput" id="searchtopbox" class="form-control srpin"
         placeholder="Search For Stores, Coupons, &amp; Offers…"
			>
	  <template type="amp-mustache"> {{#is_trend}}
                      {{#f}}<div data-value="{{link}}" class="df-h tnh">trending now <svg class="trndicn"><use xlink:href="#trndicn"></use></svg></div>{{/f}}

                      {{^f}}<div data-value="{{link}}" class="tnl"> <a>{{name}}</a> </div>{{/f}}                      
                      {{/is_trend}}
                      {{#is_hostest}}
                      {{#f}}<div data-value="{{link}}" class="df-h -htl hide-mobile">HOTTEST NOW <svg class="htnwicn"><use xlink:href="#htnwicn"></use></svg></div>{{/f}}
                      {{^f}}<div data-value="{{link}}" class="htlsbi hide-mobile"> {{#expires_date}}<div class="rbn endsn">Valid Till {{expires_date}}</div>{{/expires_date}}
                                                            {{#img}}<amp-img width="143" height="59" class="hnwi" on="tap:AMP.navigateTo(url='{{link}}');" role="button" tabindex="0" src="{{img}}" alt="{{storenm}} coupon code" title="{{storenm}} coupon code" layout="responsive" data-amp-auto-lightbox-disable=""></amp-img>{{/img}}
                              {{^img}}<svg class="-sconoim"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#noimg"></use></svg>{{/img}}
                                                            {{text}}
                               {{^text}}<p class="p-mt">{{title}}</p>{{/text}}
                               {{#text}}<p>{{title}}</p>{{/text}} <a class="seallbtn">See All {{name}} Offers</a> </div>{{/f}}
                    {{/is_hostest}}
                    {{#is_feractu}}
                      {{#f}}<div data-value="{{link}}" class="df-h hide-mobile">featured deals <svg class="htnwicn"><use xlink:href="#fdlicn"></use></svg></div>{{/f}}
                      {{^f}}<div data-value="{{link}}" class="ftrdlbx hide-mobile"> {{#cimg}}<amp-img width="1" height="1" class="fdim" on="tap:AMP.navigateTo(url='{{slink}}');" role="button" tabindex="0" src="{{cimg}}" title="{{ctitle}}" alt="{{ctitle}}" layout="responsive" data-amp-auto-lightbox-disable=""></amp-img>{{/cimg}} <div tabindex="0" role="button" on="tap:AMP.navigateTo(url='{{slink}}');" class="fdc"> {{#img}}<amp-img width="143" height="59" src="{{img}}" title="{{name}} coupon code" alt="{{name}} coupon code" layout="responsive" data-amp-auto-lightbox-disable=""></amp-img>{{/img}}
                                {{^img}}<svg class="-sconoim"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#noimg"></use></svg>{{/img}}{{text}}<p>{{title}}</p></div> </div>{{/f}}  
                    {{/is_feractu}}  
                                        {{#is_str}}    
                      {{#fs}}<div data-value="/all-stores/" class="df-h">"{{ser}}" IN STORES ({{count}}) <span class="trndicn m-l-5"></span> <a class="vwsb">View All Stores</a></div>{{/fs}}

                             {{#fsn}}<div class="-ser-st" data-value="{{link}}"> <a class="stli-b psri">{{#image}}<amp-img width="143" height="59" src="{{image}}" title="{{title}}" alt="{{title}}" layout="responsive" data-amp-auto-lightbox-disable=""></amp-img>{{/image}}{{^image}}<svg class="-sconoim hide-mobile"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#noimg"></use></svg>{{/image}}{{title}}<div class="stcp">{{count}} Coupons</div> </a> </div>{{/fsn}}                      

                    {{/is_str}}  

                    {{#is_cat}}
                      {{#fs}}<div data-value="/coupon-categories/" class="df-h">"{{ser}}" IN CATEGORIES ({{count}}) <span class="trndicn m-l-5"></span> <a class="vwsb">View All Categories</a></div>{{/fs}}

                      {{#fsn}}<div class="r-t-sc" data-value="{{link}}"><a class="stli-b">{{title}}</a></div>{{/fsn}}
                     
                    {{/is_cat}} </template>
  </amp-autocomplete>
		  <div class="indtx">What do you want to search today?</div>
			
	
	  </div>
  </div>
		</amp-lightbox>

**Comment by caroqliu** [comment]
@askmeoffers Let me clarify, the fix is required to be performed as a PR in AMPHTML, not as a workaround when using AMP. One workaround that you _can_ do for now is call `AMP.setState` before you focus on the autocomplete input. This is because AMP actions will wait for `setState()` or `pushState()` to complete before invoking the `focus` action, so `amp-autocomplete` will likely have been laid out by then. This is definitely a creative workaround and possibly also a race condition, so the better course of action of course would be to fix the bug in AMP. 

[Here is the working version of the sample above to hopefully unblock you for now.](https://playground.amp.dev/?format=websites&_gl=1*kel4z8*_ga*YW1wLTVrcDR1bGNQYlJRZ0VkTHVaT2JiRUE.#share=PCEtLQogICMjIEludHJvZHVjdGlvbgoKICBBbiBhdXRvY29tcGxldGUtZW5hYmxlZCBpbnB1dCBmaWVsZCBzdWdnZXN0cyBjb21wbGV0ZWQgcmVzdWx0cyBjb3JyZXNwb25kaW5nIHRvIHRoZSB1c2VyIGlucHV0IGFzIHRoZXkgdHlwZSBpbnRvIHRoZSBpbnB1dCBmaWVsZC4gCiAgVGhpcyBmZWF0dXJlIGNhbiBoZWxwIHRoZSB1c2VyIHRvIGNhcnJ5IG91dCB0aGVpciB0YXNrIG1vcmUgcXVpY2tseS4KICBEYXRhIGNhbiBlaXRoZXIgYmUgZmV0Y2hlZCBmcm9tIGEgSlNPTiBlbmRwb2ludCBvciBsb2NhbGx5IGZyb20gYW1wLXN0YXRlLgotLT48IS0tIC0tPgo8IWRvY3R5cGUgaHRtbD4KPGh0bWwg4pqhPgo8aGVhZD4KPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDxsaW5rIHJlbD0iY2Fub25pY2FsIiBocmVmPSJodHRwczovL2FtcC5kZXYvZG9jdW1lbnRhdGlvbi9leGFtcGxlcy9jb21wb25lbnRzL2FtcC1hdXRvY29tcGxldGUvaW5kZXguaHRtbCI+CiAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCxtaW5pbXVtLXNjYWxlPTEsaW5pdGlhbC1zY2FsZT0xIj4KICA8c2NyaXB0IGFzeW5jIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAuanMiPjwvc2NyaXB0PgogIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1saWdodGJveCIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtbGlnaHRib3gtMC4xLmpzIj48L3NjcmlwdD4KICA8dGl0bGU+YW1wLWF1dG9jb21wbGV0ZTwvdGl0bGU+CiAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLWF1dG9jb21wbGV0ZSIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtYXV0b2NvbXBsZXRlLTAuMS5qcyI+PC9zY3JpcHQ+CiAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLWZvcm0iIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAvYW1wLWZvcm0tMC4xLmpzIj48L3NjcmlwdD4KICA8c2NyaXB0IGFzeW5jIGN1c3RvbS1lbGVtZW50PSJhbXAtYmluZCIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtYmluZC0wLjEuanMiPjwvc2NyaXB0PgogIDxzdHlsZSBhbXAtY3VzdG9tPgogIDpyb290IHsKICAgIC0tc3BhY2UtMTogLjVyZW07ICAvKiA4cHggKi8KICAgIC0tc3BhY2UtMjogMXJlbTsgICAvKiAxNnB4ICovCiAgICAtLXNwYWNlLTM6IDEuNXJlbTsgLyogMjRweCAqLwogICAgLS1zcGFjZS00OiAycmVtOyAgIC8qIDMycHggKi8KCiAgICAtLWNvbG9yLXRleHQtbGlnaHQ6ICNmZmY7CiAgICAtLWNvbG9yLXByaW1hcnk6ICMwMDVBRjA7CiAgICAtLWJveC1zaGFkb3ctMTogMCAxcHggMXB4IDAgcmdiYSgwLDAsMCwuMTQpLCAwIDFweCAxcHggLTFweCByZ2JhKDAsMCwwLC4xNCksIDAgMXB4IDVweCAwIHJnYmEoMCwwLDAsLjEyKTsKICB9CiAgICBib2R5IHsKICAgICAgcGFkZGluZzogMTVweDsKICAgIH0KICAgIGJ1dHRvbiB7CiAgICAgIG1hcmdpbjogMTBweCAwcHg7CiAgICB9CiAgICAubGlnaHRib3ggewogICAgICBiYWNrZ3JvdW5kOiByZ2JhKDAsMCwwLDAuOCk7CiAgICAgIHdpZHRoOiAxMDAlOwogICAgICBoZWlnaHQ6IDEwMCU7CiAgICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTsKICAgICAgZGlzcGxheTogZmxleDsKICAgICAgYWxpZ24taXRlbXM6IGNlbnRlcjsKICAgICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7CiAgICB9CiAgICAubGlnaHRib3ggcCB7CiAgICAgIGNvbG9yOiB3aGl0ZTsKICAgIH0KICA8L3N0eWxlPgoKICA8c3R5bGUgYW1wLWJvaWxlcnBsYXRlPmJvZHl7LXdlYmtpdC1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbW96LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tcy1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDthbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aH1ALXdlYmtpdC1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tb3ota2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbXMta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtby1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QGtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX08L3N0eWxlPjxub3NjcmlwdD48c3R5bGUgYW1wLWJvaWxlcnBsYXRlPmJvZHl7LXdlYmtpdC1hbmltYXRpb246bm9uZTstbW96LWFuaW1hdGlvbjpub25lOy1tcy1hbmltYXRpb246bm9uZTthbmltYXRpb246bm9uZX08L3N0eWxlPjwvbm9zY3JpcHQ+CjwvaGVhZD4KPGJvZHk+CiAgPGgyPmF1dG9jb21wbGV0ZSB3aXRoIGxpZ2h0Ym94PC9oMj4KICA8YnV0dG9uIG9uPSJ0YXA6bXktaW5wdXQtb3V0c2lkZS5mb2N1cyI+CiAgICBmb2N1cyBvbiBhdXRvY29tcGxldGUKICA8L2J1dHRvbj4KICA8Zm9ybSBjbGFzcz0ic2FtcGxlLWZvcm0iIG1ldGhvZD0icG9zdCIgYWN0aW9uLXhocj0iaHR0cHM6Ly9hbXAuZGV2L2RvY3VtZW50YXRpb24vZXhhbXBsZXMvYXBpL2VjaG8iIHRhcmdldD0iX3RvcCI+CiAgICA8YW1wLWF1dG9jb21wbGV0ZSBmaWx0ZXI9InN1YnN0cmluZyIgbWluLWNoYXJhY3RlcnM9IjAiIHNyYz0iL3N0YXRpYy9zYW1wbGVzL2pzb24vYW1wLWF1dG9jb21wbGV0ZS1jaXRpZXMuanNvbiI+CiAgICAgIDxpbnB1dCBpZD0ibXktaW5wdXQtb3V0c2lkZSI+CiAgICA8L2FtcC1hdXRvY29tcGxldGU+CiAgPC9mb3JtPgogIDxkaXY+CiAgICA8YW1wLWxpZ2h0Ym94IGlkPSJteS1saWdodGJveCIgbGF5b3V0PSJub2Rpc3BsYXkiIG9uPSJsaWdodGJveE9wZW46QU1QLnNldFN0YXRlKHtmb286ICdiYXInfSksbXktaW5wdXQtaW5zaWRlLmZvY3VzIj4KICAgICAgPGRpdiBjbGFzcz0ibGlnaHRib3giIHJvbGU9ImJ1dHRvbiIgdGFiaW5kZXg9IjAiPgogICAgICAgIDxkaXY+CiAgICAgICAgICA8YnV0dG9uIG9uPSJ0YXA6bXktaW5wdXQtaW5zaWRlLmZvY3VzIj4KICAgICAgICAgICAgZm9jdXMgb24gYXV0b2NvbXBsZXRlCiAgICAgICAgICA8L2J1dHRvbj4KICAgICAgICAgIDxmb3JtIGNsYXNzPSJzYW1wbGUtZm9ybSIgbWV0aG9kPSJwb3N0IiBhY3Rpb24teGhyPSJodHRwczovL2FtcC5kZXYvZG9jdW1lbnRhdGlvbi9leGFtcGxlcy9hcGkvZWNobyIgdGFyZ2V0PSJfdG9wIj4KICAgICAgICAgICAgPGFtcC1hdXRvY29tcGxldGUgZmlsdGVyPSJzdWJzdHJpbmciIG1pbi1jaGFyYWN0ZXJzPSIwIiBzcmM9Ii9zdGF0aWMvc2FtcGxlcy9qc29uL2FtcC1hdXRvY29tcGxldGUtY2l0aWVzLmpzb24iPgogICAgICAgICAgICAgIDxpbnB1dCBpZD0ibXktaW5wdXQtaW5zaWRlIj4KICAgICAgICAgICAgPC9hbXAtYXV0b2NvbXBsZXRlPgogICAgICAgICAgPC9mb3JtPgogICAgICAgICAgPGJ1dHRvbiBvbj0idGFwOm15LWxpZ2h0Ym94LmNsb3NlIj4KICAgICAgICAgICAgQ2xvc2UgbGlnaHRib3gKICAgICAgICAgIDwvYnV0dG9uPgogICAgICAgIDwvZGl2PgogICAgICA8L2Rpdj4KICAgIDwvYW1wLWxpZ2h0Ym94PgogICAgPGJ1dHRvbiBvbj0idGFwOm15LWxpZ2h0Ym94Ij4KICAgICAgT3BlbiBsaWdodGJveAogICAgPC9idXR0b24+CiAgPC9kaXY+CjwvYm9keT48L2h0bWw+)

**Comment by askmeoffers** [comment]
@caroqliu Thanks for providing workarounds. 

For now, as our development is still under progress so we will wait for the final fix.

Request you humbly to prioritize this fix and push it to the public repository directly avoiding the long life cycle of issue closure/release.

Thanks 
Team - https://askmeoffers.com/
