### ISSUE TITLE
Disable no-unused-vars linter for interfaces

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#29902]
## Describe the new feature or change to an existing feature you'd like to see

The "no-unsued-vars" linter is essentially a false-positive for interfaces. It's unnecessary and misleading. The recommended workarounds, such as adding "unused" prefix are generally wrong.

Is it possible to automatically disable this rule for interfaces?

Some ideas:
 1. Can we discover `@interface` in the jsdoc? This would be the most automatic option.
 2. Can we disable this rule for children of a class declaration suffixed with `Interface`?
 2. Can we skip this rule entirely for completely empty method declarations? E.g. `doX(arg1, arg2) {}`.
 3. Disable this rule for `*-interface.js` files, but also limit what can go to those files only to type declarations such as `@typedef` and `@interface`.

**Comment by rsimha** [comment]
_[Infra triage]_ The `no-unused-vars` lint rule is configured to not complain about interfaces (ending in `Interface`) or typedefs (ending in `Def`).

https://github.com/ampproject/amphtml/blob/3a4f018bea2e3aac973bf07fa906ac6f2c910efc/.eslintrc.js#L208-L214

Looking at the `no-unused-vars` [rule details](https://eslint.org/docs/rules/no-unused-vars#rule-details) in the `eslint` documentation, there doesn't appear to be any other special way to ignore this rule when the JSDoc uses an `@interface` tag for example.

@jridgewell @samouri @dvoytenko Do you think the existing mechanism is good enough? Or do you think we should add a check to force developers to use the `Interface` or `Def` suffix instead of adding an `eslint-disable-line no-unused-vars` annotation?

**Comment by samouri** [comment]
I'm personally ok with our current mechanism

**Comment by rsimha** [comment]
I suppose one thing we can do is to clean up existing interfaces that don't end in `Interface` and typedefs that don't end in `Def`. (There are [~20 instances](https://github.com/ampproject/amphtml/search?q=eslint-disable-line+no-unused-vars&type=code) in code right now.) This can be done organically as code is maintained / refactored.
