### ISSUE TITLE
Integration tests on Safari run in parallel instead of in series 

### ISSUE THREAD

**Issue by estherkim** [ampproject/amphtml#29930]
This is a bug because every test's iframe is created in a single Karma window. It affects common assertions like element position, and fails to ensure silo'ed environments per test.

Note that this is seen in Safari only, and not Firefox or Chrome.

Thanks @zhouyx for the find!

**Comment by rsimha** [comment]
Just did a little investigating. The reason we had to stop using `karma-safari-launcher` was because of https://github.com/karma-runner/karma-safari-launcher/issues/29. With current versions of Safari, opening a local HTML file (as Karma does) causes Safari to pop up a modal dialog that interrupts the test runner. 

The issue comments suggest workarounds like `karma-safarinative-launcher`, `karma-safari-private-launcher`, and `karma-safari-applescript-launcher`. I can try the others to see which one works best.

**Comment by rsimha** [comment]
Figured out the problem. There is code in `_init_tests.js` to clean up iframes between tests, but this was disabled for Safari because it didn't work well with the old `karma-safari-launcher`. I enabled it with the current `karma-safarinative-launcher` and noticed that all tests' iframes were at 0,0. Will send out a PR shortly.
