### ISSUE TITLE
AMP Caches Transform Valid CSS to Invalid CSS

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/amphtml#29959]
## What's the issue?

The Google AMP Cache specifically transforms some content inside CSS to invalid representations.

**Before**
![image](https://user-images.githubusercontent.com/61764/91197777-95cb9080-e6b0-11ea-9cff-f398b855b075.png)
**After**
![image](https://user-images.githubusercontent.com/61764/91197719-86e4de00-e6b0-11ea-86af-e5d6feb6cb7e.png)

**Before**
![image](https://user-images.githubusercontent.com/61764/91197847-ac71e780-e6b0-11ea-8ad1-fe8996fbc0f9.png)
**After**
![image](https://user-images.githubusercontent.com/61764/91197745-8ea48280-e6b0-11ea-8117-9c52cb53494a.png)

## How do we reproduce the issue?

Here's an example on the Google AMP Cache: https://www-nytimes-com.cdn.ampproject.org/v/s/www.nytimes.com/interactive/2020/us/new-york-coronavirus-cases.amp.html?usqp=mq331AQFKAGwASA%3D&amp_js_v=0.1#origin=https://www.google.com&cid=1&prerenderSize=1&visibilityState=visible&paddingTop=32&history=1&p2r=0&csi=1&storage=1&viewerUrl=https://www.google.com/amp/s/www.nytimes.com/interactive/2020/us/new-mexico-coronavirus-cases.amp.html

Origin Document: https://www.nytimes.com/interactive/2020/us/new-york-coronavirus-cases.html

Root cause seems to be conversion of entities inside CSS. https://twitter.com/Rich_Harris/status/1298279831713579010?s=20

```css
.css-ztxa74 span > *:last-of-type::after {
    content: '›';
    position: relative;
    bottom: -2px;
    margin-left: 4px;
    font-size: 23px;
    font-weight: 500;
}
```

## What browsers are affected?

All browsers, the issue is due to conversion of entities inside CSS.

## Which AMP version is affected?

Unknown which version of the AMP Cache transformers introduced this issue.

**Comment by tholman** [comment]
Have had the same problem here for a wile now https://github.com/ampproject/amphtml/issues/29540

**Comment by Gregable** [comment]
This issue is tracked internally as part of Google's AMP Cache as 166295722.

@tholman , I think #29540 is an independent issue.

**Comment by twifkak** [comment]
The fix for this has been deployed. Please reopen if you see otherwise.

**Comment by Gregable** [comment]
Adding a little more detail, though this is definitely resolved. 

The issue affected utf8 codepoints that have a `\x80` byte in a position other than the first byte position (2nd, 3rd, or 4th). This specific case (the bullet character) had such a byte in the 2nd position (`\xE2\x80\xA2`). A bug in the cache's UTF8 processing was introduced which couldn't recognize this character and replaced it with the UTF8 replacement character (\xFF\xFD).

The only place where this bug would have manifested in the AMP Cache was in `<style amp-custom>`. Stylesheets typically have minimal multi-byte characters and combined with the fact that this bug only affected a small number of multi-byte characters caused the issue to be missed in pre-release tests.

The change went live early last week and the fix was pushed into production on Aug 26. Documents already in the cache may have persisted in this state until they were next refreshed. For most documents, that's <12h, however it can be longer if the cache had trouble fetching a new copy from the origin server. It's likely there are very few, if any, affected documents still live on the cache.
