### ISSUE TITLE
AMP Story Player: When doing story navigation it resets the first page

### ISSUE THREAD

**Issue by rnkimani** [ampproject/amphtml#30178]
## What's the issue?
- While using the story navigation with multiple stories, clicking using `go` resets the story page and on click it shows where the page was left off. 

## How do we reproduce the issue?
- Implement the next and previous using `go`
- Click on a navigation and click through the pages of a story. 
- If you go back to one of the first stories it shows the first page instead of where it left off. 

### Context
- [Example](https://tappable-sdk.web.app/)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/45009681/92694063-28299080-f34f-11ea-8fd7-19ce22ef471c.gif)
- The first story has the active page to be 3 but when going back it resets to the first page and then on click it resumes where it left off. 

## What browsers are affected?
- All

## Which AMP version is affected?
- Latest
- Ref [#28416](https://github.com/ampproject/amphtml/issues/28416)

cc @Enriqe

**Comment by newmuis** [comment]
I'm sure it's because we dispose the iframe, but I'm surprised the state isn't restored from history.

**Comment by Enriqe** [comment]
I believe this is caused because internally, `go()` uses `show()`. And there's a bug in `show()` that shows the story in pre-rendered mode in some scenarios, which is causing this behavior. This will be addressed in https://github.com/ampproject/amphtml/issues/28987 which has a PR out and should be merged soon!
