### ISSUE TITLE
Allow amp-date-countdown to show time elapsed since

### ISSUE THREAD

**Issue by Bartor** [ampproject/amphtml#30197]
Currently, when feeding a past timestamp into the amp-date-countdown, it works by displaying correct values with a minus sign in front. It'd be nice to have a parameter which could switch things around and allow us to use the amp-date-countdown as a "time to" as well as "time elapsed since".

**Comment by nainar** [comment]
Could amp-date-display be more useful here? https://amp.dev/documentation/examples/components/amp-date-display/

**Comment by Bartor** [comment]
It'd communicate a similar kind of information for sure, but doesn't quite allow for what I described.

**Comment by krdwan** [comment]
@Bartor We just added a new attribute on the component `data-count-up`.  Including this will make the component count upwards instead of downwards.  (essentially time-elapsed since a particular date).  This should be in the main code base in a few weeks so keep an eye out here: https://amp.dev/documentation/components/amp-date-countdown/?format=websites which will be updated with documentation when the new feature is out.  Thanks!
