### ISSUE TITLE
Regression[?] in amp-story video pre-rendering

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#30207]
See https://www-usatoday-com.cdn.ampproject.org/c/s/www.usatoday.com/web-stories/jeanette-epps-first-black-woman-to-live-on-the-lss/#visibilityState=hidden

The following CSS rule `amp-story-page[active]:not(.i-amphtml-layout) amp-video.i-amphtml-poolbound {display: none !important}` completely hides the video.

The video element doesn't have a poster assigned although it could have (The amp-video element does have one).

**Comment by cramforce** [comment]
This is really worth digging deep. We never attempt to layout the video element and `amp-story-render` always times out.

**Comment by cramforce** [comment]
@jridgewell Could you quickly check why we don't layout these elements?

**Comment by jridgewell** [comment]
Looking into this now.

**Comment by jridgewell** [comment]
@cramforce: How did you get this URL? Specifically the `#visibilityState=hidden` portion.

After a ton of debugging, I narrowed down the issue to the fact that `layoutCallback` is never called on the `amp-story`. This is because we're in the `hidden` visState, which is reserved specifically for when the viewer has swiped to a new document and left this one. For viewer pre-rendering (which is what I think you're thinking of), visState should be `prerender`. When I go to https://www-usatoday-com.cdn.ampproject.org/c/s/www.usatoday.com/web-stories/jeanette-epps-first-black-woman-to-live-on-the-lss/#visibilityState=prerender, everything works as I'd expect.

Is this just user error, or do I need to keep digging?

**Comment by cramforce** [comment]
OMG, I apologize. I did not realize there was this distinction!!

The behavior matched what I saw happening in the player, but this must have been a red herring.

Sorry for wasting your time!
