### ISSUE TITLE
amp-youtube tracking play triggers when hitting replay button

### ISSUE THREAD

**Issue by MegKrish** [ampproject/amphtml#30216]
**Please only file reports about bugs in AMP here.**

## What's the issue?

The video-play currently fires events as expected when the play button is hit. However, after the video has reached the end and the user hits the refresh button the video-play button event fires again.
Briefly describe the bug.

## How do we reproduce the issue?

1) hit the play button on amp-youtube video component 
2) Let video complete playing and wait until the replay button appear
3) Hit the replay button on the video once it appears. You will see that tracking is firing the play-button event
Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

## What browsers are affected?

Chrome, Firefox, Safari

**Comment by micajuine-ho** [comment]
We recently changed the mapping of `VideoEvents` emitted by each amp-video implementation (youtube, vimeo, etc...) from interpreting `VideoEvents.PLAYING` as the analytics playing signal to `VideoEvents.Play` as the analytics playing signal. 

It looks like amp-youtube and amp-vimeo don't send the `VideoEvents.Play` signal, and so the video-manager never gets that event:

https://github.com/ampproject/amphtml/blob/43c953fa466cf4624bfe0b8aa410b49edb2067c5/src/service/video-manager-impl.js#L523-L526

Leading to the playing signal getting sent multiple times:
https://github.com/ampproject/amphtml/blob/43c953fa466cf4624bfe0b8aa410b49edb2067c5/src/service/video-manager-impl.js#L696-L698

This probably isn't the intended behavior. 
- One fix could be to alter the implementation of amp-youtube/amp-vimeo to have them send the `VideoEvents.Play` event once.
- Other fix could be to set the `this.hasSeenPlayEvent_`  to true after sending the `VideoAnalyticsEvents.PLAY` event from the `VideoEvents.Playing` event.

/cc @zhouyx thoughts on this?

**Comment by zhouyx** [comment]
This is working as expected based on the `video-play` [definition](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-video-analytics.md#video-play-trigger-on-video-play). The event is designed to fire when the video begins playing.  Which means it will fire after a pause or replay.  
@MegKrish What is your desired behavior?

The `VideoAnalyticsEvents.PLAY` is introduced later to replace `VideoAnalyticsEvents.PLAYING`. Because `playing` events can be emitted multiple times when playing was interrupted by network issue. The idea is that a `play` event should always happen before `playing` event. So if we see a `VideoAnalyticsEvents.PLAY` we'll set `hasSeenPlayEvent_` to `true`, and discard all following `VideoAnalyticsEvents.PLAYING` events for analytics purposes.

**Comment by MegKrish** [comment]
@zhouyx 

I'm trying to find a way that would allow for the play, pause, and replay button events to be identified separately. Currently, all three actions are tied to the play event which does not does identify the action separately

**Comment by zhouyx** [comment]
I think the is possible on the server side. By identifying `play` events right after `pause` event. 
However, I'm not sure if there's a native support for `replay` event. @alanorozco Any thoughts? Thanks

**Comment by MegKrish** [comment]
@zhouyx and @alanorozco checking in if there were any last min thoughts on this?

**Comment by micajuine-ho** [comment]
@MegKrish I think your best bet would be to try to figure this out server-side by following @zhouyx's suggestions. If it doesn't work well, we can reopen this issue and look into alternative solutions.
