### ISSUE TITLE
Intent to implement: Collect resource timing metrics in amp-analytics

### ISSUE THREAD

**Issue by querymetrics** [ampproject/amphtml#3022]
SOASTA mPulse on standard web pages collects resource timing for use in RUM analytics.
There are 2 sets of metrics collected client side by mPulse,
first is a set of basic statistics about the page, notably:
- # of resources referenced by the page
- # of different domains referenced by the page
- # of DOM nodes on the page
- byte size of rendered page
- # of image nodes on the page
- # of image nodes on the page that reference an external domain
- # of script nodes on the page
- # of script nodes on the page that reference an external domain

These could be collected with little JS and not be CPU intensive.

secondly, if ResourceTiming is available all the entries are compressed client side and beaconed.
The resource timing compression used is an OSS library, https://github.com/nicjansma/resourcetiming-compression.js.

Would the AMP Project be open to support resource usage metric collection in `amp-analytics`?

**Comment by avimehta** [comment]
personally i am fine with this if there is value in providing this. This will be something that gets added to platform and not to amp-analytics(although I am not sure about that).  resource-compression.js is around 4.5kb. @dvoytenko are you guys okay with that? It is MIT license so that part is fine. 

Other than that, I wish the compression was a little more general purpose so that we could use the same algorithm to compress scroll data as required by #1797. (scroll data is a series of numbers so same compression techniques can be applied but the way the code is currently structured, i don't think it can be reused.)

@querymetrics I presume you will be implementing this. correct?

**Comment by querymetrics** [comment]
@avimehta , yes, we can implement it.

We use similar compression techniques for sending back JS errors (will be open sourced soon) and UserTiming data (see https://github.com/nicjansma/usertiming-compression.js). The domain specific algorithms make the compression more efficient but there is certainly refactoring we could do to be able to compress other types of data as well.

**Comment by cramforce** [comment]
I think this would be great to have, but I am a bit concerned about the size.

Maybe we should make `amp-analytics-resourcetiming` where including the extension contributes new variables.

**Comment by adelinamart** [comment]
What is the latest status here? Thanks.

**Comment by rudygalfi** [comment]
I'm going to close this out. It looks like #3022 covered most or all of this.

**Comment by MiCHiLU** [comment]
@rudygalfi This is #3022. Are you mistaking closed an issue?

**Comment by rudygalfi** [comment]
Oops - meant #3593 seemed to address most of this
