### ISSUE TITLE
amp-link-rewriter just doesn't work

### ISSUE THREAD

**Issue by Bartor** [ampproject/amphtml#30314]
## What's the issue?
The `amp-link rewriter` component doesn't work. It throws no error, it just doesn't rewrite any URLs.

## How do we reproduce the issue?

1. Clone the [example file](https://github.com/ampproject/amphtml/blob/master/examples/amp-link-rewriter.html)
2. Host it/open it in the browser
3. The link does not change

## What browsers are affected?

All.

## Which AMP version is affected?

2009040024003

**Comment by micajuine-ho** [comment]
Hi @Bartor, the amp-link-rewriter does not change the current page's URL. It writes the URL on page navigation.

https://github.com/ampproject/amphtml/blob/master/extensions/amp-link-rewriter/amp-link-rewriter.md#json-configuration

In the example, when the <a> tag is clicked, instead of going to amazon.com, the amp-link-rewriter will rewrite the link and the user will be directed to `https://visit.foo.net?eid=231&cid=12345`.

Please let me know if you need anymore explanation.
