### ISSUE TITLE
amp-story-player: "Expand to fullscreen" button

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#30377]
## Describe the new feature or change to an existing feature you'd like to see

Add a new "expand to fullscreen" button in the amp-story toolbar (similar to expand button commonly seen on videos). 

Button is only displayed when embedded in amp-story-player.

## Describe alternatives you've considered

Every surface that uses amp-story-player that wants "expand to fullscreen" functionality would implement their own button to do so.

## Additional context

The Web Stories plugin for WordPress recently shipped and this would greatly improve consumption UX.

/cc @ampproject/wg-stories

**Comment by gmajoulet** [comment]
@Enriqe is your new API to customize and add Player buttons tracked publicly?

**Comment by Enriqe** [comment]
Yeah, tracked here https://github.com/ampproject/amphtml/issues/30031. The API is not final though, I'm still working on polishing the final details.

**Comment by jaygray0919** [comment]
Not sure I understand this issue. We use a Web Story (nee AMP Story) template developed at the SF Chronicle.
It supports desktop and mobile. WaPo also has a similar template.
So my question here is:
     does "Expand to full screen" stretch a conventional mobile window to a desktop landscape/portrait window
     or
     does it mean 'switch CSS (@media) to a desktop landscape/portrait monitor window'

In our experience, the SF Chronicle template works well and could be formalized for this use case

**Comment by swissspidy** [comment]
@jaygray0919 Neither. This issue is about the [`amp-story-player`](https://github.com/ampproject/amphtml/blob/master/spec/amp-story-player.md) component. It should be possible to use that component to embed a story on a page, and have a button on it that allows expanding the story to cover the full screen.

**Comment by jaygray0919** [comment]
ahhh! never mind ...

**Comment by swissspidy** [comment]
Looks like #30031 has been progressing nicely!

@Enriqe is there any update / preliminary docs on the API so that we could explore this?

**Comment by Enriqe** [comment]
We are still prepping the material which we will share very shortly. What I can say is that in this first iteration we will not include support for custom buttons, since we still need to clarify a few items from the product / UX side. We will have discussions early next week to unblock this, though.

**Comment by Enriqe** [comment]
I was able to squeeze it in #30914. The docs will be merged in #30988. Keep in mind there is a release freeze, but you could start reading the docs / opting-in to nightly to try it out.
