### ISSUE TITLE
frame-ancestors directive support in CSP on cdn.ampproject.org to protect from ClickJacking attack

### ISSUE THREAD

**Issue by oxdef** [ampproject/amphtml#30409]
Currently in Google search results page AMP powered page is displayed inside iframe with source like `https://foo-com.cdn.ampproject.org/c/s/foo.com/amp_document.html.`. This source is for AMP cache. But this page also could be displayed in every other site inside such iframe (from AMP cache like `cdn.ampproject.org`), including malicious one. So there could be attack called [Clickjacking](https://portswigger.net/web-security/clickjacking).

Classic way to prevent such attack is to use `X-Frame-Options: SAMEORIGIN` HTTP response header in the web app. But AMP cache removes it because this iframe should be displayed from google.com (and it is not "same origin"). Another approach is to specify `frame-ancestors` directive in Content Security Policy. [CSP is already added by Google AMP](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/secure-pages/) cache but without this directive. Also this directive could not be used in CSP specified via meta tag.

1. What do you think about this security risk?
2. Is it possible to add `frame-ancestors` into CSP policy of AMP cache with values for Google and Bing domains?

**Comment by Gregable** [comment]
I'm not sure I understand what the security risk is here. Can you provide a specific example?

**Comment by oxdef** [comment]
@Gregable The risk is about Clickjacking attack (please, see the link above). Consider e-commerce website and button "Add to cart". If this functionality is also supported in AMP-version of this website attacker could make iframe (with URL of AMP-version page for specific product) of this page on attacker's site and force to navigate user on it. Then in case of Clickjacking attack specific product  will be added in the cart of the victim. This attack is about framing target website on attacker's one.

**Comment by Gregable** [comment]
Hi @oxdef , I'm not sure I understand the specific attack you have in mind. Having clarity on that would help to understand the usefulness of this change. Feel free to respond on [slack](http://amphtml.slack.com/) or other more private channels if you have specifics you don't want to share publicly.

Typically, my understanding of a clickjacking attack would be something like: `https://bank.example/` has a predictable URL that displays a one-click "pay the attacker $100 from your logged-in account" button. `https://attacker.example/` then iframes this `https://bank.example/transfer?amount=100&acct=attacker` page showing only the "send" button, and tricks the user into clicking it. The user's own cookie credentials are used and money is transferred.

I don't see how this could happen on the `cdn.ampproject.org`'s pages. These pages are all 100% credential-less / cookie-less already. They never set cookies, javascript can never set cookies, etc. So a user click on these pages has no browser-sent credentials.

You might be thinking of the AMP Client ID identifier which can be shared between publisher origin `https://bank.example` and AMP Cache page `https://bank-example.cdn.ampproject.org`. In the case of `cdn.ampproject.org`, the cookie which backs the AMP Client Id is actually stored on the `https://google.com` (or `.co.uk`, `.de`, etc) origin. This is already necessary because in some browsers cookies are only available when they match the top-frame origin. The AMP Client ID is actually generated in the outer frame (`https://www.google.com/amp/s/bank.example/`) and passed to the inner document via `window.postmessage()`. Without the outer frame, this credential is unavailable.

All that said, it might not be a bad defense in depth to add `frame-ancestors`. The tradeoff is that we would need to enumerate all Google origins which legitimately frame the document. This is a pretty long list, since we have every google TLD (`.co.uk`, `.de`, etc) to worry about. Given the increase in byte size before the first byte of the document arrives on the network, we prefer to limit the CSP length as much as reasonably possible and this long list would run counter to that goal.

**Comment by oxdef** [comment]
@Gregable 

> I don't see how this could happen on the cdn.ampproject.org's pages. These pages are all 100% credential-less / cookie-less already. They never set cookies, javascript can never set cookies, etc. So a user click on these pages has no browser-sent credentials.

There are at least 2 scenario to make it possible:

1. CORS (https://amp.dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests/) with cookies. Simple example is "Like" button (https://amp.dev/documentation/examples/interactivity-dynamic-content/favorite_button/?format=websites) 
> Most AMP components that use CORS requests either automatically set the credentials mode or allow the author to optionally enable it. For example, the amp-list component fetches dynamic content from a CORS JSON endpoint, and allows the author to set the credential mode through the credentials attribute.
![Image from CORS AMP docs](https://amp.dev/static/img/docs/CORS_with_Cache.png)

2. Redirect
Many of e-commerce sites with AMP enabled use "redirect button" to provide "Add to cart" functionality. And it is uses especially for AMP.  Something like "https://www.e-commerce.example/basket/add/product/1234/" without user confirmation because of usability and conversion rate.

> All that said, it might not be a bad defense in depth to add frame-ancestors. The tradeoff is that we would need to enumerate all Google origins which legitimately frame the document. This is a pretty long list, since we have every google TLD (.co.uk, .de, etc) to worry about. 

TLD could be dynamically set based on various parameters from HTTP request. So you don't need to specify all google TLD in static CSP policy.

**Comment by Gregable** [comment]
@oxdef Thanks for the details. It seems like the attack requires some form of credentials transfer via the CORS response to `amp-list` or similar components. This was not an angle I had considered. 

I'm reviewing this with some security folks to better understand the attack surface. Since there is a security issue here, it's considered P1 and will remain so unless we determine the risk is otherwise low.

**Comment by oxdef** [comment]
I've made special URL for diagnostic:
```
$ http --headers "https://moon.oxdef.info/index.amp.html"
HTTP/1.1 200 OK
Accept-Ranges: bytes
Connection: keep-alive
Content-Length: 1562
Content-Security-Policy: frame-ancestors 'self' google.com google.ru
Content-Type: text/html
Date: Thu, 22 Oct 2020 07:23:15 GMT
ETag: "5f8fdd99-61a"
Last-Modified: Wed, 21 Oct 2020 07:04:57 GMT
Server: nginx/1.18.0
Strict-Transport-Security: max-age=15768000; includeSubdomains
X-Content-Type-Options: nosniff
```
And from the AMP Cache:
```
$ http --headers "https://moon-oxdef-info.cdn.ampproject.org/c/s/moon.oxdef.info/index.amp.html"
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: https://moon.oxdef.info
Alt-Svc: h3-Q050=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private, max-age=120
Content-Length: 11229
Content-Security-Policy: default-src * blob: data:; script-src 'sha256-5CxqAdDXlHviOy7zxeRpMobzRK/JNpLvkS+k8Zj3L3A=' 'sha256-FIBGC/wl1Qfnh2Fb5NPFHmRty7BHJdDpWW1FZ8egppI=' 'sha256-dKn2nAtwgzaaXC8ZM58hhldxNyeuu4qrzW4H9//9YMA=' blob: https://cdn.ampproject.org/esm/ https://cdn.ampproject.org/lts/ https://cdn.ampproject.org/mp/ https://cdn.ampproject.org/rtv/ https://cdn.ampproject.org/sp/ https://cdn.ampproject.org/sw/ https://cdn.ampproject.org/v0.js https://cdn.ampproject.org/v0.mjs https://cdn.ampproject.org/v0/ https://cdn.ampproject.org/viewer/; object-src 'none'; style-src 'unsafe-inline' https://cdn.ampproject.org/rtv/ https://cdn.materialdesignicons.com https://cloud.typography.com https://fast.fonts.net https://fonts.googleapis.com https://maxcdn.bootstrapcdn.com https://p.typekit.net https://pro.fontawesome.com https://use.fontawesome.com https://use.typekit.net; report-uri https://csp.withgoogle.com/csp/amp
Content-Type: text/html
Date: Thu, 22 Oct 2020 07:25:31 GMT
Expires: Thu, 22 Oct 2020 07:25:31 GMT
Last-Modified: Thu, 22 Oct 2020 07:05:20 GMT
NEL: {"report_to":"nel","max_age":604800,"success_fraction":0.05}
Origin-Trial: Am+6sz9r0IqtWb9SobKTqHA67MO+9PoMJTQ/Q+eubnkDYkCTxvnAPyt/HDOgBxz0pp2M4ijIadNkPVgnZiBy3AoAAABveyJvcmlnaW4iOiJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZzo0NDMiLCJmZWF0dXJlIjoiQmVmb3JlTWF0Y2hFdmVudCIsImV4cGlyeSI6MTYwNjMxMTkwOSwiaXNTdWJkb21haW4iOnRydWV9
Report-To: {"group":"nel","max_age":604800,"endpoints":[{"url":"https://beacons.gcp.gvt2.com/nel/upload-nel"},{"url":"https://beacons.gvt2.com/nel/upload-nel"}]}
Server: sffe
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Page-Speed: 0.9.10.99-9999
X-XSS-Protection: 0
link: <https://cdn.ampproject.org/rtv/012010132225002/v0.js>; rel=preload; as=script
```
By the way, you can decrease size for existing default CSP policy to something like (of course after consulting with  security folks):
```
Content-Security-Policy: default-src * blob: data:; script-src 'sha256-5CxqAdDXlHviOy7zxeRpMobzRK/JNpLvkS+k8Zj3L3A=' 'sha256-FIBGC/wl1Qfnh2Fb5NPFHmRty7BHJdDpWW1FZ8egppI=' 'sha256-dKn2nAtwgzaaXC8ZM58hhldxNyeuu4qrzW4H9//9YMA=' blob: cdn.ampproject.org; object-src 'none'; style-src 'unsafe-inline' cdn.ampproject.org cdn.materialdesignicons.com cloud.typography.com fast.fonts.net fonts.googleapis.com maxcdn.bootstrapcdn.com p.typekit.net pro.fontawesome.com use.fontawesome.com use.typekit.net; report-uri https://csp.withgoogle.com/csp/amp
```

**Comment by Gregable** [comment]
Since this doesn't affect any existing usage, reducing the priority slightly.

**Comment by Gregable** [comment]
As a workaround, it may be possible for the publisher origin to use the referrer header to verify that the XHR was made from within a frame that was on a google origin. This appears to work.

I don't think that this is a good long term solution. Referrer isn't always available and shouldn't really be used as a security feature. It also doesn't make sense to require publishers to maintain an allow list of Google search origins.

On the AMP cache end, we plan to have the cdn.ampproject.org response return a frame-ancestors header for exactly one domain at a time. In order to do that, the cdn.ampproject.org request needs to include information about what domain is requesting it. Referrer is a candidate here as well but doesn't work because of the cases where referrer is missing. In those case, the response can either disallow frames altogether (breaks legitimate usage) or allow all frames (rendering the security constraints useless). The publisher XHR origin may have more nuanced response options available to handle the empty referrer case. cdn.ampproject.org does not.

Instead, the plan is to modify the AMP viewer (the legitimate frame ancestor) to pass the viewer's origin to the document in the request headers. The response headers will echo that origin back in the frame-ancestors header, iff it matches an allow list of expected frames. The implementation here will require coordination and several release cycles.

**Comment by oxdef** [comment]
> As a workaround, it may be possible for the publisher origin to use the referrer header to verify that the XHR was made from within a frame that was on a google origin. This appears to work.

@Gregable As for Referrer header, yes, it's not good solution for Clickjacking attack protection for **publisher**, especially in case of AMP cache:

- Attacker can hide Referrer information with Referrer policy
- Publisher can check Referrer only in JavaScript code because browser gets cached version of the page from AMP cache CDN
- Attacker can disable JavaScript code in frame with `sandbox` feature. Also take into account that this JavaScript code is executed in AMP version of page and cache side.
- And, yes, AMP cache should "know better" about search engines then publisher. So it is better to solve the problem on the side (of AMP cache) who disable publishers' current protection with `X-Frame-Options`. 

> On the AMP cache end, we plan to have the cdn.ampproject.org response return a frame-ancestors header for exactly one domain at a time

Good news! :+1:
