### ISSUE TITLE
Webmaster tool reporting " Required tag missing" Error

### ISSUE THREAD

**Issue by gkteck** [ampproject/amphtml#3042]
The page is successfully validated by checking with #development=1.

But the Webmaster tool reporting " Required tag missing" Error

Here is the page URL

`goo.gl/XYDBwr`

**Comment by powdercloud** [comment]
I looked at this page, and the current version of it (as of Mon May  2 13:23:19 PDT 2016) is valid. It could be that the report in the webmaster console is based on an earlier version. If not, please feel free to reopen - thank you!

**Comment by gkteck** [comment]
The Webmaster tool is still showing error for this page.
The error detail message is 
"The mandatory tag 'body' is missing or incorrect."

**Comment by powdercloud** [comment]
@gkteck I'm quite confident this is a stale message. This is because it takes some time to recrawl the page. I've verified that the validator that we have in production considers the page as valid. You can do so here, since this doesn't give an error it means it's valid (and it agrees with the validator you could run in the browser with #development=1, the way it should):
https://cdn.ampproject.org/c/s/www.indiglamour.com/gallery/Tamil/Actor/Bala/404828-ipad.html

I'm not entirely sure about this part, but if you're concerned that it's not treated as valid AMP in Google's index, it may help to resubmit the page: https://support.google.com/webmasters/answer/6065812?hl=en. I think if you do nothing, it should fix itself as well, eventually.

PS: closing this once again, but again please feel free to reopen if this does not satisfy you. Thank you for the report!
