### ISSUE TITLE
Increase in AMP Traffic in Google Analytics tracking as DIRECT channel instead Organic

### ISSUE THREAD

**Issue by Kundanchy** [ampproject/amphtml#30515]
From past few days, I'm seeing an increase of AMP traffic on the Direct channel of many websites I'm working on.

The increase is follow the decrease on the normal organic tracking channel of my AMP pages (organic search). I'm trying to figure this out, but, I'm not able to find a decent response or solution. 

Seems like, all my Chrome Users from Mobile are directly typing AMP URLs. (Which is ideally not possible)

Any idea on how to deal with that ? Is there any bug in Chrome or how can i fix this? 
What might be the reason ??

Thanks.

**Comment by zhouyx** [comment]
@Kundanchy Thanks for reporting. I agree that all users directly typing AMP URLs is very unlikely. Could you please give me a more clear timeline? When did this start to happen, so I can look into our release timeline to see if this is an AMP issue first. 

Is this only affecting Chrome users in Google Analytics?. Is it possible to get a url for me to test with? Thanks

cc @zikas

**Comment by zhouyx** [comment]
I took a quick look on the amp.dev traffic. I'm not seeing the same regression there. @Kundanchy more details would be very useful.

**Comment by Kundanchy** [comment]
@zhouyx Thanks for your reply !
We started to see sudden increase from 1st-2nd Oct'2020. 
Yes this is happening for chrome users from Mobile devices (We have maximum traffic on Mobile).
Sharing few sample URLs where we have huge direct traffic:
https://hindi.asianetnews.com/amp/gallery/career/ias-interview-questions-for-upsc-aspirants-in-hindi-civil-service-upsc-tricky-questions-kpt-qhtelx
https://hindi.asianetnews.com/amp/gallery/weird-news/earn-10-lakh-rupees-for-single-5-and-10-coins-with-mata-vaishno-devi-photo-kph-qhs124
https://newsable.asianetnews.com/amp/gallery/cricket-sports/from-tamannaah-bhatia-to-anushka-sharma-six-beautiful-divas-virat-kohli-dated-in-his-bachelor-life-shl-qhsj06
https://newsable.asianetnews.com/amp/gallery/entertainment/ranbir-kapoor-alia-bhatt-marriage-will-katrina-kaif-attend-exboyfriend-wedding-qd4za5
Please look into this and help me to fix this.

Thanks,
CC @zikas

**Comment by zhouyx** [comment]
I verified that we had one release 2009190410000 promoted to Stable channel at September 29, 2020, 10:27:48 AM GMT-7, 
(Release 2009190410002 created with cherry picks #30452, #30453 doesn't seem related.) I don't think the time matches even with time zone differences included. 

I also checked Chrome's release history, the closet one was the Chrome for iOS Update at September 30, which doesn't seem to be related to the issue here. 

Is there any recent change to your GA account setting? I tested the urls you sent me, and was able to see the document referral set to `google.com` in the requests sent to Google Analytics.

@zikas your thoughts would be helpful! Thanks!

**Comment by Kundanchy** [comment]
@zhouyx Thanks for your time and effort !

We did not change anything in our GA account setting. 
This is not happening with us only, I have noticed that lot of people having same conversation on Twitter. Sharing screenshot from twitter for your reference:
![image](https://user-images.githubusercontent.com/72391302/95542817-75635580-0a14-11eb-9606-b3720d4e5a3e.png)

 Please dig a little deeper to get this resolved.

@zikas Please help !

Thanks,

**Comment by zhouyx** [comment]
@Kundanchy I noticed you're also using comscore to collect data. Are you seeing the similar issue there? or only with GoogleAnalytics? Thanks

**Comment by Kundanchy** [comment]
@zhouyx , No we are facing this issue with GA only.

**Comment by zhouyx** [comment]
@Kundanchy Thanks for confirming. 

@zikas and I investigated the issue offline. What we found is that the document.referrer information was sent correctly from AMP documents.

Since the timeline didn't match, and you indicate the issue is GA specific. We assume the issue is not on the client side. The best way to proceed is to file a support ticket directly to GA. Please include information from this thread in the ticket. Thank you!

**Comment by zhouyx** [comment]
Close as this is tracked on the GA side.
