### ISSUE TITLE
interaction between tests and experiments

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#30522]
**summary**
Currently unit tests do not pay any attention to experiments unless they are specifically turned on within the test themselves. This is an issue because when an experiment is turned up to 100% in production, I'd also want all of the related code to pass its unit tests (which is not enforced today).

In an ideal world, we could run every unit test under each possible combination of possible experiments. That would be incredibly impractical though, and so I propose that at a minimum we insure that any experiment set to >= 0.5 in production should be turned on automatically within tests.

**why this is important**
1. will discover real bugs
2. will make sure we do the work at the right time, instead of finding out about broken tests during experiment cleanup.

**Comment by rsimha** [comment]
This is the code in `src/experiments.js` that determines the status of an experiment:

https://github.com/ampproject/amphtml/blob/8f057734b56c5a3106e71193fbd5eba33123f594/src/experiments.js#L122-L185

For unit tests, would it make sense to initialize all experiments with the values found in `build-system/global-configs/prod-config.json`, so that if there are no test-level overrides, we default to the production config values?

**Comment by rsimha** [comment]
Side note: This issue may obviate the need for #25720. (We fixed the integration test use case, but did not do so for unit tests.)

**Comment by samouri** [comment]
Closing now that https://github.com/ampproject/amphtml/pull/30535 was merged. If we start detecting flakes due to the test randomness, we may want a followup PR to use `Math.round` on experiment values.
