### ISSUE TITLE
Font Awesome CDN Outdated

### ISSUE THREAD

**Issue by esng25** [ampproject/amphtml#30546]
While the whitelisted Font Awesome CDN still exists (https://fontawesome.com/account/cdn) but is being deprecated from further support as the Font Awesome team is pushing the use of kit.fontawesome.com. Please consider whitelisting this sub-domain so we can access the latest icons and features from Font Awesome.

**Comment by Gregable** [comment]
@dvoytenko for opinions on the addition.

Can you suggest a regular expression for matching the new URLs?

**Comment by kristoferbaxter** [comment]
I agree with adding this in too, would `*.fontawesome.com` be acceptable, or should we allow-list `kit` etc as one offs?

**Comment by honeybadgerdontcare** [comment]
Our [allowed list](https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L328) has been fairly specific, is there a reason to become that generic? It seems we could add `kit` to the `(use|pro)` subdomain expression as `(kit|use|pro)`. @esng25 Are there additional requirements that these URLs will have from the existing `use` and `pro` ones?

**Comment by esng25** [comment]
@honeybadgerdontcare - I can't think of any strong reason for a wildcard as long as the FontAwesome team doesn't keep changing sub-domains. That would be the only reason I can think of. 

Either way, I just wish we can access the latest features and support however you decide to implement it.

**Comment by honeybadgerdontcare** [comment]
@esng25 I am not personally familiar with Font Awesome and it's implementation. AMP has allowed `.css` files from subdomains `use` and `pro`, however from the [example](https://fontawesome.com/how-to-use/customizing-wordpress/snippets/setup-kit) I see it wants to request a `.js` file. That may require additional approvals since AMP is restrictive with including javascript. Are you asking to include `.css` files or also the `.js` files for kit?

**Comment by Gregable** [comment]
This has been resolved to add `kit`.
