### ISSUE TITLE
[amp-img][amp-bind] data-amp-bind-src Is Adding Itself to the <img> Tag

### ISSUE THREAD

**Issue by isaac-tru** [ampproject/amphtml#30547]
## What's the issue?

I am using react and am unable to use [src] on an <amp-img> tag, so I am using the fallback attribute data-amp-bind-src. However, this does not seem to validate reports the error: "img.i-amphtml-fill-content.i-amphtml-replaced-content.i-amphtml-error.i-amphtml-element-error: Binding to [%s] on <%s> is not allowed. amp-bind src IMG​​​"

## How do we reproduce the issue?

Instead of [src] on amp-img, use attribute data-amp-bind-src and see how it will show up on the <img> tag and produce an error.
[https://jsfiddle.net/qewc68zu/](https://jsfiddle.net/qewc68zu/)

## What browsers are affected?

Chrome 85.0.4183.121

## Which AMP version is affected?

Current.

**Comment by jridgewell** [comment]
Thanks for the issue @isaac-tru! While it's a bit annoying to receive the error message, it's safe to ignore and it won't affect your page.

This is caused by https://github.com/ampproject/amphtml/blob/65dae0deb7c53388b5069789281de42d1f1ee25a/builtins/amp-img.js#L102 copying the data attributes on the `<img>` tag, on which we don't allow data bindings. But when the `<amp-img>` changes its `src`, we'll propagate that new `src` onto the `<img>`. I think we just need to stop propagating the `data-amp-bind-*` attrs.

/cc @samouri and @kevinkimball

**Comment by isaac-tru** [comment]
Thank you for responding and finding that so fast. However, I am using @ampproject/toolbox-optimizer which does not use the boilerplate and includes the runtime css: 

`.i-amphtml-element-error {
    background: red!important;
    color: #fff!important;
    position: relative!important;
}`

Which makes the image not be able to be seen and I cannot overwrite that without breaking other css rules. So this may affect others using an optimizer too.

**Comment by isaac-tru** [comment]
Thank you very much. I will close this out and await the PR getting approved.
