### ISSUE TITLE
amp-script terminates worker on inactive document

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#30548]
1. Go to https://amp.dev/page-experience in a new tab
2. Type in any test URL, i.e. axios.com
3. Leave the tab and wait 2 min (Well over the time the fetch returns + amp-script source attempts to modify DOM)
4. Return to tab and see the amp-script portion of the page is disabled (greyed out) 
![image](https://user-images.githubusercontent.com/10456171/95337744-28e71100-0880-11eb-8834-8dd212f0279c.png)
with the following console message:
![image](https://user-images.githubusercontent.com/10456171/95337684-1c62b880-0880-11eb-9ab3-83c9ffdd22ff.png)

I understand we may no longer go through with #27948 which would have solved this issue.

**Comment by samouri** [comment]
> I understand we may no longer go through with #27948 which would have solved this issue.

One of the reasons I don't think we're going through with #27948 is actually because it wouldn't solve most issues. The worker wouldn't have been terminated, but we'd still block mutations. worker-dom also wouldn't notice any failures and have an incorrect vdom.

**Comment by samouri** [comment]
I haven't been able to reproduce the error locally since I can't get most of the checks to run on my machine (do I need API Keys etc.)?

Something I did notice is that the failure is entirely dependent on if you switch tabs before the linter api returns.
If you switch beforehand, then it'll lose track of the activation. If you switch tabs afterwards, namely once the following network requests are initiated, then it'll succeed.

A potential temporary fix (not recommended) would be to greedily start the 3 later fetches early. 
Will attempt to debug again at a later date / with the right keys

**Comment by caroqliu** [comment]
We try to hold off on pinging the other APIs until we've heard from the linter -- this tells us whether or not a page is AMP at all, and we don't want to waste resources if it's not. 

Let me look into the keys for you.

**Comment by samouri** [comment]
An alternative to getting special API key for me, would be ensuring that page experience works even when accessed via the amphtml gulp local proxy

**Comment by patrickkettner** [comment]
per [this comment](https://github.com/ampproject/amp.dev/issues/4879#issuecomment-735911846_), reopening as the current version on amp.dev is 2011252111002 and the issue is still occuring

**Comment by samouri** [comment]
Fix is ready!

**Comment by samouri** [comment]
Just tested it and I was not able to repro this error today.
Please reopen in case you can!
