### ISSUE TITLE
Expand on TRUSTED_VIEWER_HOSTS comment

### ISSUE THREAD

**Issue by ejcx** [ampproject/amphtml#3063]
[The comment](https://github.com/ampproject/amphtml/blob/master/src/service/viewer-impl.js#L110) references the setting of the referrer.

It's unclear if this is a security related change or not. How do I go about evaluating if I'd like to make a pull request to add my site to the regex? 

[This page 
](https://www.ampproject.org/docs/reference/extended/amp-dynamic-css-classes.html) also mentions the referrer but it's unclear what the purpose of adding these classes to amp page is? Branding?

**Comment by dvoytenko** [comment]
@ejcx 

> It's unclear if this is a security related change or not. How do I go about evaluating if I'd like to make a pull request to add my site to the regex?

What's your site? And could you please explain why do you need it in this whitelist? Currently, this whitelist is only used to allow a page that embeds an AMP document to override referrer for the purposes of access. This is because access decisions are often made based (in part) on referrer and thus the referrer-based vectors are common. This is not a very usual thing to modify.

>  the referrer but it's unclear what the purpose of adding these classes to amp page is? Branding?

This allows (ideally minor) customizations to the page based on the referrer. For instance, a publisher may choose to make "pin" buttons more prominent if the user has navigated from Pinterest. This is not a security-sensitive customization and thus it does NOT require referrer confirmation via trusted viewers whitelist.

**Comment by ejcx** [comment]
Thanks @dvoytenko. The thing I'm wondering is the security implications of adding something to this list. Right now it's unclear in the docs what adding sites or removing sites actually has an effect on.

If I changed isTrustedViewerOrigin_ to the function below, what security risks exist?

```
function isTrustedViewerOrigin_(url) { return true; }
```

**Comment by rudygalfi** [comment]
@ejcx With such a change, the referrer variable passed by a viewer would always be trusted. Some features, like Access, make use of referrer information to make decisions. A trusted viewer is able to help step in and make the referrer information more accurate (overriding what would get provided by default, which is document.win.referrer) so that Access works more as a user might expect.

**Comment by ejcx** [comment]
Thank you @rudygalfi. That's helpful for me.

**Comment by ejcx** [comment]
Final question @rudygalfi .

> Some features, like Access, make use of referrer information to make decisions.

Which features? Is this mostly to support first-click free ?

**Comment by rudygalfi** [comment]
I'm actually not super familiar with publishers' Access implementations, but I suspect Google's first click free policy is one of the places where referrer information comes in. There may be others.

**Comment by ejcx** [comment]
So it sounds like becoming "trusted" only gives you the ability to modify the referrer, which is to provide publishers/ad-networks with additional and more accurate information.
