### ISSUE TITLE
amp-script fails for incognito Chrome users in Google Search results

### ISSUE THREAD

**Issue by jerimiahwelch** [ampproject/amphtml#30691]
## amp-script fails for incognito Chrome users in Google Search results

amp-script fails for incognito Chrome users in Google Search results or any other iframe amp-viewer. This appears to be because localStorage is not available. All amp-script components on the page fail to initialize, render, or handle interactions.

## How do we reproduce the issue?

1. Load this demo page in both a regular Chrome browser window and an incognito Chrome browser window.
https://amp-test-viewer-51000.web.app/#https://wompme.blob.core.windows.net/7865/ampScriptDemo.html?_=1

2. Observe the "localStorage not supported" message and failed amp-script components.
![Screen Shot 2020-10-15 at 1 56 16 PM](https://user-images.githubusercontent.com/1224514/96186247-0001f400-0ef0-11eb-9dda-e75f9f6191ec.png)

## What browsers are affected?

Chrome 86 +

## Which AMP version is affected?

Version 2010010034001 - We just discovered that this is impacting ~ 3 million of our AMP pages currently in production.

**Comment by kristoferbaxter** [comment]
In `amp-script.js`, storage is retrieved, but isn't passed as null in this case to WorkerDOM.

```javascript
/**
   * @param {!StorageLocation} location
   * @return {?Storage}
   * @private
   */
  storageFor_(location) {
    if (location === StorageLocation.LOCAL) {
      return this.win_.localStorage;
    } else if (location === StorageLocation.SESSION) {
      return this.win_.sessionStorage;
    }
    return null;
  }
```

**Comment by samouri** [comment]
There are two AIs we can pursue to stop the bleeding:
1. worker-dom can guard for an error in its sanitizer `setStorage` call
2. amp-script can check for storage support before attempting any calls.

While either of these (or both) would keep worker-dom and amp-script running, if a page relies on storage for its flows as opposed to just as a progressive enhancement, then the page will break no matter what. 

This is due to the default Chrome setting for blocking 3p cookies in incognito mode:
<img width="683" alt="Screen Shot 2020-10-16 at 12 19 00 PM" src="https://user-images.githubusercontent.com/4656974/96283316-0654a680-0faa-11eb-80ca-62719570715a.png">

**Comment by kristoferbaxter** [comment]
If we move to make `worker-dom` behave more like the standard API when `localStorage` is unavailable, this would keep the contract the same as traditional web applications. 

Is likely a bit more work though.

**Comment by jerimiahwelch** [comment]
Any updates on an eta for a solution for this? Even some kind of error would be helpful. Since the amp-script doesn't run, we currently have no way to notify the user what is wrong.

**Comment by samouri** [comment]
@jerimiahwelch: I plan on prioritizing this for next week

**Comment by samouri** [comment]
The fix landed in worker-dom. Should make it to the stable channel in a couple of weeks
