### ISSUE TITLE
I2I: Add analytics vendor Tail DMP

### ISSUE THREAD

**Issue by babadopulos** [ampproject/amphtml#30815]
Hi!

We'd like to add Tail DMP to the amp-analytics vendors list to help our customers integrating our services in their amp pages.

cc @ampproject/wg-approvers
cc @ampproject/wg-analytics

**Comment by micajuine-ho** [comment]
Hi @babadopulos , thanks for your issue. You can follow the instructions here https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/integrating-analytics.md on how to integrate Tail DMP into the amp-analytics vendor list. Please feel free to reach out if you need any assistance. Additionally, once you have your PR out, please tag me so that I can help you merge your changes.

**Comment by micajuine-ho** [comment]
Closed via #30823
