### ISSUE TITLE
Unit test: compilation error leads to hang.

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#30907]
**summary**
When I forget to annotate a test function with `async` when using await, the test runner freezes and I can only escape by creating a new terminal and `kill`ing it.

![Screen Shot 2020-10-29 at 12 18 09 PM](https://user-images.githubusercontent.com/4656974/97601724-dca37280-19e0-11eb-80e6-89cb4f62217d.png)

cc @rsimha to triage

**Comment by rsimha** [comment]
This is a perfect use case for our [Ctrl+C handler](https://github.com/ampproject/amphtml/blob/master/build-system/common/ctrlcHandler.js), which starts a child process that listens for Ctrl+C and bails immediately, even when an async task causes the main process to be unresponsive.

Looking at the code, we're already using it during unit and integration tests (line 240):

https://github.com/ampproject/amphtml/blob/698171e8d9f298e3ca9e02313580c07ecfb85d76/build-system/tasks/runtime-test/runtime-test-base.js#L232-L243

I can think of two reasons why this isn't working as expected:

1. The process stalled before the handler process was created (in which case line 240 should be at the top of the function)
2. The handler process is broken on Windows because we're creating the child process incorrectly (I know there's a bug where the handler process silently fails to be created, but I've never been able to fix it because I don't develop on Windows).

**Comment by samouri** [comment]
1. I've confirmed that the createCtrlcHandler is running. Moving it higher up did not help :(
2. I'm back to using a Mac ever since the new byod policies took place this week.
3. Handler process is exiting properly, not sure whats still going on in the main process.

You should be able to repro very simply! Just remove an `async` from a unit test.

**Comment by rsimha** [comment]
To further clarify item 3, my suspicion is that the `teardown()` function is exiting the Ctrl+C handler, and is then getting stuck in `async` code with no way for the user to exit out. Here is the function:

https://github.com/ampproject/amphtml/blob/698171e8d9f298e3ca9e02313580c07ecfb85d76/build-system/tasks/runtime-test/runtime-test-base.js#L250-L262

A simple check for this is to comment out line 252 and see if you can then Ctrl+C out of the task.

A more long-term fix would be to add a lint rule to make sure that `await` can only be used on an `async` function or a function that returns a Promise.

**Comment by samouri** [comment]
I am very excited you managed to track this down :)
