### ISSUE TITLE
Performance impact of web player embeds

### ISSUE THREAD

**Issue by shishirm** [ampproject/amphtml#30990]
## What's the issue?

Embedding the we player on a page has an impact to performance, specifically the interactivity and the visual completeness of the page.

## How do we reproduce the issue?

1. URL with web player embedded below the fold -> https://travisj.dev/2020/10/07/32-ideas-for-jumpropes-for-september-2020/
2. URL with web player embedded above the fold -> https://travisj.dev/2020/10/07/above-the-fold-web-player/
3. URL with no web players embedded -> https://travisj.dev/2020/10/07/32-ideas-for-jumpropes-for-september-2020-no-players/

In the first two cases, when testing against Page Speed Insights, the TTI is about 35-36s, TBT is about 3s, Speed Index is 12s-17s
In the third case, when testing against Page Speed Insights, the TTI is about 5.3s, TBT is about 180ms, Speed Index is 4.3s

This indicates that the page takes a lot longer to get to visually complete owing to the player embedded (both above the fold and below the fold) and that the page also takes a lot longer to be fully interactive.

While embedding content will see some performance implication, the expectation is that the pages should still stay performant.

## What browsers are affected?

Tested primarily on page speed insights.

## Which AMP version is affected?

Related specifically to the web player.

**Comment by gmajoulet** [comment]
Thank you for filing this Shishir, we're starting to look into this and https://github.com/ampproject/amphtml/issues/30557 at the same time.

cc @ampproject/wg-stories

**Comment by gmajoulet** [comment]
cc @Enriqe can you double check if your last improvement to optimize the LCP fixed this, and close if everything is now working? Ty!

**Comment by Enriqe** [comment]
Just tested with the recent improvements and the results seem promising.

Taken the following tests:
1. No player (control) https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Ftemp-player.web.app%2Fexamples%2Famp-story%2Fplayer-no-player.html (speed score 100)
2. Player below fold https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Ftemp-player.web.app%2Fexamples%2Famp-story%2Fplayer-below-fold.html (speed score 100)
3. Player above the fold https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Ftemp-player.web.app%2Fexamples%2Famp-story%2Fplayer-above-fold.html (speed score 67)

We can see that the player below the fold case has improved significantly, matching the scenario with no player. The only differences are small increases in TTI and TBT, which naturally come from the added (unminified and uncached in this case) JS & CSS.

The third case involves loading the story and `amp-story.js` runtime, which in itself has its own performance implications. Since we have proven that having the player (while taking the amp-story.js out of the equation) doesn't have a significant performance hit, we can consider this issue closed.

What we can take from this is that we should improve scenario (3) the best we can. We could initially NOT load the story (even if the player is above the fold), and only show the poster image or some other UX treatment. Once the user clicks on it, then we would start loading the story. This would greatly improve scenario (3). I've filed a separate issue for this: #32594
