### ISSUE TITLE
AMP page showing invalid when visiting with Chrome despite showing valid when checking with validator

### ISSUE THREAD

**Issue by chopinesque** [ampproject/amphtml#31063]
## What's the issue?
https://stackoverflow.com/questions/64757682/amp-page-showing-invalid-when-visiting-with-chrome-despite-showing-valid-when-ch

AMP page showing invalid when visiting via Chrome following a Google search, despite showing valid when checking with amp validators.

## How do we reproduce the issue?
To replicate the issue, use Chrome from a phone and run a Google search for **pre-owned translatum**, it will bring up an amp page from translatum.gr. Click on that and see what happens. Please see a screen recording of the process here: https://www.translatum.gr/downloads/mobile.mp4

## What browsers are affected?
Chrome (mobile/desktop), Firefox (mobile/desktop)

## Which AMP version is affected?
amp-version="2010132225003"

**Comment by honeybadgerdontcare** [comment]
@chopinesque I see that the page you linked from Stack Exchange is valid both from validator.amp.dev and the Chrome Extension. I also see when setting Region Selection to Greece and searching for `pre-owned translatum` that there is a result for that domain and when clicking on that result it states it is not valid AMP.

Looking at the URL in the search result, it has a URL with parts of the query string escaped.

Original URL:
`https://www.translatum.gr/forum/index.php?action=amp;topic=987010`

URL in Search:
`https://www.translatum.gr/forum/index.php?action=amp%3Btopic%3D985701`

Using that escaped URL with both validator.amp.dev and the Chrome Extension it shows that the returned HTML is not valid AMP and is not declared as AMP.

There are two potential solutions for you, though this is outside of the scope of AMP itself.
 - Use `&` instead of `;` for different query params.
 - Update the server for this domain to handle escaped query params for `%3B` (which is `;`).

**Comment by chopinesque** [comment]
Thank you for the great reply.
Not sure how to update the server to handle these parameters. If you have any idea, I would be grateful.

**Comment by honeybadgerdontcare** [comment]
Do you have control of generating the URLs? I'd suggest trying to use `&` instead of `;`.
Otherwise, I'd suggest trying Stack Overflow or whomever is hosting your server.

**Comment by chopinesque** [comment]
Yes, but the = sign seems to cause trouble too which is not an issue with the canonical URL which also has it.
