### ISSUE TITLE
amp-sidebar should add class to body

### ISSUE THREAD

**Issue by massa84** [ampproject/amphtml#3106]
For our website we would like to 'slide' the content of the article to the right simultaneously with the sidebar opening animation, but, to do so, it would be extremely useful if the amp-sidebar adds some configurable class to the body.
Otherwise we should rely on possibly complicated sibling selectors to achieve the same result  but would make everyone life a bit harder.

Would it be possible to add this feature ?

**Comment by sriramkrish85** [comment]
@massa84 - we did consider that initially , this version of sidebar was built mainly for the mobile web. We did consider adding a state class to the body and then later rule it out due to implementation complexities and also to avoid excessive spamming of classes on the body.

However , we would definitely consider implementing this as a feature (may be like - adding an attribute would trigger this and hopefully will be configurable)

CC - @ericlindley-g - to help prioritize this into a milestone as appropriate.

**Comment by ericlindley-g** [comment]
@massa84 I've spun off a feature request for the specific animation behavior you describe in #3170—I've made some assumptions about the behavior, so feel free to correct or elaborate on that issue. 

@sriramkrish85 — closing the request in this issue to add state classes to the body, due to the concerns you mention above. Please correct/re-open if this is possible without those risks, somehow
