### ISSUE TITLE
https://news.androidlista.it/2020/10/14/novita-di-whatsapp-adesso-e-possibile-silenziare-gruppi-e-chat-per-sempre/?amp

### ISSUE THREAD

**Issue by Geracas** [ampproject/amphtml#31119]
Details
---

| Metric                  | Field data  | Lab data    |
|-------------------------|-------------|-------------|
| LCP                     | <pass/fail> | <pass/fail> |
| FID                     | <pass/fail> | <pass/fail> |
| CLS                     | <pass/fail> | <pass/fail> |
| HTTPS                   | <pass/fail> | <pass/fail> |
| Safe browsing           | <pass/fail> | <pass/fail> |
| Mobile-friendliness     | <pass/fail> | <pass/fail> |
| Intrusive Interstitials | <pass/fail> | <pass/fail> |

Notes
---

Components in use: 

/cc @ampproject/wg-performance

**Comment by kristoferbaxter** [comment]
Hi there,

I ran this page thru the [Page Experience tool](https://amp.dev/page-experience) and it seems to be passing Core Web Vitals.

<img width="1152" alt="Screen Shot 2020-11-12 at 6 38 01 AM" src="https://user-images.githubusercontent.com/61764/98953678-d4a00400-24b1-11eb-9b6d-14533d06d5b7.png">

There are some opportunities for improvement, from the report.

Since it seems to be passing and there are listed opportunities, I'm going to close this issue. Feel free to comment if there are additional questions.
