### ISSUE TITLE
ability to hide "big play button" in amp-ima-video

### ISSUE THREAD

**Issue by spormeon** [ampproject/amphtml#31214]
as in the title really,  if using autoplay and when not,  the big play button should be hidden and/ or have the ability to hide the big play button, with something like nobigbutton  , similar to the "noloading" to hide the loading spinner

![amp-ima-video_-_AMP_Playground_🔊](https://user-images.githubusercontent.com/8503167/99420449-20f5a480-28f5-11eb-9358-7dd0a76c2864.png)

**Comment by alanorozco** [comment]
Thank you for your request! Here's my proposal.

### Render full control bar in unstarted state

Provide an option, like `<amp-ima-video controls="static" ...>` so that the full control bar is rendered before video is played, instead of the Big Play Button. By full control bar, we mean the following that's displayed when the video is already playing:

<img width=375 src=https://user-images.githubusercontent.com/254946/99433207-14a42400-28c2-11eb-872f-eb5dd30a9cf8.png>

However, I'm not sure if this is doable for cases when you have preroll ads. It's possible we need to selectively toggle/disable specific controls. **I'm interested in discussing this further with @ampproject/wg-components**, and possibly get a UX review on this.

---

@spormeon: This may take a few cycles to get done on `amp-ima-video`.

**If you'd like to draw your own controls**, you may alternatively [use `amp-video-iframe`](https://amp.dev/documentation/components/amp-video-iframe/#integration-inside-the-frame). This allows you to use your own document inside the player's `<iframe>`, where you can render and manipulate any IMA implementation, like [one provided for VideoJS.](https://github.com/googleads/videojs-ima).

**Comment by spormeon** [comment]
just to chip in.  If using autoplay, I think they should be hidden at start and appear on float over, with just the "equaliser" icon bouncing away like does now?

**Comment by alanorozco** [comment]
> @spormeon: If using autoplay, I think they should be hidden at start and appear on float over, with just the "equaliser" icon bouncing away like does now?

The autoplay behavior is similar to that, except the controls only appear on click.

[You may try it out yourself here.](https://playground.amp.dev/#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CjxtZXRhIGNoYXJzZXQ9InV0Zi04Ij4KICA8dGl0bGU+YW1wLWltYS12aWRlbzwvdGl0bGU+CiAgPGxpbmsgcmVsPSJjYW5vbmljYWwiIGhyZWY9Imh0dHBzOi8vYW1wLmRldi9kb2N1bWVudGF0aW9uL2V4YW1wbGVzL2NvbXBvbmVudHMvYW1wLWltYS12aWRlby9pbmRleC5odG1sIj4KICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLG1pbmltdW0tc2NhbGU9MSxpbml0aWFsLXNjYWxlPTEiPgogIDxzY3JpcHQgYXN5bmMgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC5qcyI+PC9zY3JpcHQ+CiAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLWltYS12aWRlbyIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtaW1hLXZpZGVvLTAuMS5qcyI+PC9zY3JpcHQ+CiAgPHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1vei1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbXMtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7YW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGh9QC13ZWJraXQta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbW96LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1zLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW8ta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUBrZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19PC9zdHlsZT48bm9zY3JpcHQ+PHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOm5vbmU7LW1vei1hbmltYXRpb246bm9uZTstbXMtYW5pbWF0aW9uOm5vbmU7YW5pbWF0aW9uOm5vbmV9PC9zdHlsZT48L25vc2NyaXB0Pgo8L2hlYWQ+Cjxib2R5PgogIDxhbXAtaW1hLXZpZGVvIGlkPSJteVZpZGVvMyIgd2lkdGg9IjY0MCIgaGVpZ2h0PSIzNjAiIGxheW91dD0icmVzcG9uc2l2ZSIgZGF0YS10YWc9Imh0dHBzOi8vcHViYWRzLmcuZG91YmxlY2xpY2submV0L2dhbXBhZC9hZHM/c3o9NjQweDQ4MCZpdT0vMTI0MzE5MDk2L2V4dGVybmFsL2FkX3J1bGVfc2FtcGxlcyZjaXVfc3pzPTMwMHgyNTAmYWRfcnVsZT0xJmltcGw9cyZnZGZwX3JlcT0xJmVudj12cCZvdXRwdXQ9dm1hcCZ1bnZpZXdlZF9wb3NpdGlvbl9zdGFydD0xJmN1c3RfcGFyYW1zPWRlcGxveW1lbnQlM0RkZXZzaXRlJTI2c2FtcGxlX2FyJTNEcHJlb25seWJ1bXBlciZjbXNpZD00OTYmdmlkPXNob3J0X29uZWN1ZSZjb3JyZWxhdG9yPSIgZGF0YS1zcmM9Imh0dHBzOi8vY29tbW9uZGF0YXN0b3JhZ2UuZ29vZ2xlYXBpcy5jb20vZ3R2LXZpZGVvcy1idWNrZXQvc2FtcGxlL0JpZ0J1Y2tCdW5ueS5tcDQiIGRhdGEtZGVsYXktYWQtcmVxdWVzdD0idHJ1ZSIgYXV0b3BsYXk+CiAgPC9hbXAtaW1hLXZpZGVvPgo8L2JvZHk+PC9odG1sPg==) There's an unrelated bug in which the controls appear for a brief moment on initial play, but I believe @micajuine-ho is tracking that problem elsewhere.

**Comment by micajuine-ho** [comment]
The issues is being tracked here: #31223
