### ISSUE TITLE
Amp-ima-video skips mid-rolls etc if Click time line of video near end

### ISSUE THREAD

**Issue by spormeon** [ampproject/amphtml#31263]
with amp-ima-video  , if you have pre, mid and post rolls and forward skip to the end of the video by click the time line near end, is it supposed to “skip” the mid-rolls ( as it does), in eg videojs it stops and plays the mid rolls, then comes back to the video at the point you choose in the timeline

**Comment by alanorozco** [comment]
I'm not entirely sure that the midroll actually gets skipped in every case. It might be due to publisher-specific IMA configuration? [See this sample, the midroll is displayed on video seek.](https://playground.amp.dev/#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5wcmUsIG1pZCBhbmQgcG9zdHJvbGw8L3RpdGxlPgogIDxsaW5rIHJlbD0iY2Fub25pY2FsIiBocmVmPSJzZWxmLmh0bWwiIC8+CiAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCxtaW5pbXVtLXNjYWxlPTEsaW5pdGlhbC1zY2FsZT0xIj4KICA8c3R5bGUgYW1wLWJvaWxlcnBsYXRlPmJvZHl7LXdlYmtpdC1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbW96LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tcy1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDthbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aH1ALXdlYmtpdC1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tb3ota2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbXMta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtby1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QGtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX08L3N0eWxlPjxub3NjcmlwdD48c3R5bGUgYW1wLWJvaWxlcnBsYXRlPmJvZHl7LXdlYmtpdC1hbmltYXRpb246bm9uZTstbW96LWFuaW1hdGlvbjpub25lOy1tcy1hbmltYXRpb246bm9uZTthbmltYXRpb246bm9uZX08L3N0eWxlPjwvbm9zY3JpcHQ+CiAgPHNjcmlwdCBhc3luYyBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwLmpzIj48L3NjcmlwdD4KICA8c2NyaXB0IGFzeW5jIGN1c3RvbS1lbGVtZW50PSJhbXAtaW1hLXZpZGVvIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1pbWEtdmlkZW8tMC4xLmpzIj48L3NjcmlwdD4KICA8c3R5bGUgYW1wLWN1c3RvbT4KICAgIGgxIHsKICAgICAgbWFyZ2luOiAxcmVtOwogICAgfQogIDwvc3R5bGU+CjwvaGVhZD4KPGJvZHk+CiAgPGg0PnByZSwgbWlkIGFuZCBwb3N0cm9sbDwvaDQ+CiAgPGFtcC1pbWEtdmlkZW8KICAgIGlkPSJWaWRlbzMiCiAgICB3aWR0aD0iNjQwIgogICAgaGVpZ2h0PSIzNjAiCiAgICBsYXlvdXQ9InJlc3BvbnNpdmUiCiAgICBkYXRhLXRhZz0iaHR0cHM6Ly9wdWJhZHMuZy5kb3VibGVjbGljay5uZXQvZ2FtcGFkL2Fkcz9zej02NDB4NDgwJml1PS8xMjQzMTkwOTYvZXh0ZXJuYWwvYWRfcnVsZV9zYW1wbGVzJmNpdV9zenM9MzAweDI1MCZhZF9ydWxlPTEmaW1wbD1zJmdkZnBfcmVxPTEmZW52PXZwJm91dHB1dD12bWFwJnVudmlld2VkX3Bvc2l0aW9uX3N0YXJ0PTEmY3VzdF9wYXJhbXM9ZGVwbG95bWVudCUzRGRldnNpdGUlMjZzYW1wbGVfYXIlM0RwcmVtaWRwb3N0JmNtc2lkPTQ5NiZ2aWQ9c2hvcnRfb25lY3VlJmNvcnJlbGF0b3I9IgogICAgZGF0YS1wb3N0ZXI9Ii9leGFtcGxlcy9pbWcvaW1hLXBvc3Rlci5wbmciCiAgPgogICAgPHNvdXJjZQogICAgICBzcmM9Imh0dHBzOi8vY29tbW9uZGF0YXN0b3JhZ2UuZ29vZ2xlYXBpcy5jb20vZ3R2LXZpZGVvcy1idWNrZXQvc2FtcGxlL0JpZ0J1Y2tCdW5ueS5tcDQiCiAgICAgIHR5cGU9InZpZGVvL21wNCIKICAgIC8+CiAgPC9hbXAtaW1hLXZpZGVvPgo8L2JvZHk+CQo8L2h0bWw+Cg==)

![midroll](https://user-images.githubusercontent.com/254946/100138970-9f959900-2e43-11eb-85a0-ad5178736d3e.gif)

**Comment by spormeon** [comment]
try it with this tag, it only plays 1 of the set of 5 midrolls, or is that expected behaviour, to only play the 1 set of 5 that is nearest the vmap midroll times?
https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostlongpod&cmsid=496&vid=short_tencue&correlator=

**Comment by alanorozco** [comment]
[I'm seeing all 5 midrolls play consecutively.](https://playground.amp.dev/#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5wcmUsIG1pZCBhbmQgcG9zdHJvbGw8L3RpdGxlPgogIDxsaW5rIHJlbD0iY2Fub25pY2FsIiBocmVmPSJzZWxmLmh0bWwiIC8+CiAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCxtaW5pbXVtLXNjYWxlPTEsaW5pdGlhbC1zY2FsZT0xIj4KICA8c3R5bGUgYW1wLWJvaWxlcnBsYXRlPmJvZHl7LXdlYmtpdC1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbW96LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tcy1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDthbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aH1ALXdlYmtpdC1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tb3ota2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbXMta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtby1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QGtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX08L3N0eWxlPjxub3NjcmlwdD48c3R5bGUgYW1wLWJvaWxlcnBsYXRlPmJvZHl7LXdlYmtpdC1hbmltYXRpb246bm9uZTstbW96LWFuaW1hdGlvbjpub25lOy1tcy1hbmltYXRpb246bm9uZTthbmltYXRpb246bm9uZX08L3N0eWxlPjwvbm9zY3JpcHQ+CiAgPHNjcmlwdCBhc3luYyBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwLmpzIj48L3NjcmlwdD4KICA8c2NyaXB0IGFzeW5jIGN1c3RvbS1lbGVtZW50PSJhbXAtaW1hLXZpZGVvIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1pbWEtdmlkZW8tMC4xLmpzIj48L3NjcmlwdD4KPC9oZWFkPgo8Ym9keT4KICA8aDQ+cHJlLCBtaWQgYW5kIHBvc3Ryb2xsPC9oND4KICA8YW1wLWltYS12aWRlbwogICAgaWQ9IlZpZGVvMyIKICAgIHdpZHRoPSI2NDAiCiAgICBoZWlnaHQ9IjM2MCIKICAgIGxheW91dD0icmVzcG9uc2l2ZSIKICAgIGRhdGEtdGFnPSJodHRwczovL3B1YmFkcy5nLmRvdWJsZWNsaWNrLm5ldC9nYW1wYWQvYWRzP3N6PTY0MHg0ODAmaXU9LzEyNDMxOTA5Ni9leHRlcm5hbC9hZF9ydWxlX3NhbXBsZXMmY2l1X3N6cz0zMDB4MjUwJmFkX3J1bGU9MSZpbXBsPXMmZ2RmcF9yZXE9MSZlbnY9dnAmb3V0cHV0PXZtYXAmdW52aWV3ZWRfcG9zaXRpb25fc3RhcnQ9MSZjdXN0X3BhcmFtcz1kZXBsb3ltZW50JTNEZGV2c2l0ZSUyNnNhbXBsZV9hciUzRHByZW1pZHBvc3Rsb25ncG9kJmNtc2lkPTQ5NiZ2aWQ9c2hvcnRfdGVuY3VlJmNvcnJlbGF0b3I9IgogICAgZGF0YS1wb3N0ZXI9Ii9leGFtcGxlcy9pbWcvaW1hLXBvc3Rlci5wbmciCiAgPgogICAgPHNvdXJjZQogICAgICBzcmM9Imh0dHBzOi8vY29tbW9uZGF0YXN0b3JhZ2UuZ29vZ2xlYXBpcy5jb20vZ3R2LXZpZGVvcy1idWNrZXQvc2FtcGxlL0JpZ0J1Y2tCdW5ueS5tcDQiCiAgICAgIHR5cGU9InZpZGVvL21wNCIKICAgIC8+CiAgPC9hbXAtaW1hLXZpZGVvPgo8L2JvZHk+CQo8L2h0bWw+Cg==) Sped up:

![midroll-set](https://user-images.githubusercontent.com/254946/100145573-5f3b1880-2e4d-11eb-9bac-6045367ef936.gif)

**Comment by spormeon** [comment]
ye but there is a bunch of them, like 5-6 sets of 5?

**Comment by micajuine-ho** [comment]
Hi, I can confirm that the behavior of playing only 1 set of mid-roll ads instead of all 10 (when user skips to the end), is not occurring from our client side player (as we only listen for signals from the SDK to play/pause the content video and alter UI).

I cannot find anything specifically on this topic within the [SDK documentation](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side), however it might be worth it to file an issue in their repo: https://github.com/googleads/googleads-ima-html5/issues
