### ISSUE TITLE
Bad loading experience in Story: Flash of white between video poster and video playback

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#31358]
To repro 

1. Load this URL https://www.lonelyplanet.com/stories/8-unusual-animal-migrations/ with a fast but not ultra fast connection
2. Observe that some kind of poster loads quickly
3. Then there is a white flash (page background color)
4. And then the video loads.

## What browsers are affected?

Chrome Android

## Which AMP version is affected?

Tested with current stable

**Comment by gmajoulet** [comment]
Additional note: this might behave different on iOS and Android. Android has some custom code within `amp-video` to handle poster images.

https://github.com/ampproject/amphtml/blob/2f33bbeb343a7307ddfa9bd8b9bd41014675e48d/extensions/amp-video/0.1/amp-video.js#L666-L692

cc @ampproject/wg-stories

**Comment by mszylkowski** [comment]
So far what I've found:

The amp-videos on Android (may also happen on iOS, don't have a device to test) remove the poster before displaying the first frame of the video. Was able to reproduce on a regular video element, so it's a problem related to the way the `video` element works. Only happens on videos with posters.

Also, the `firstLayoutCompleted`method from `amp-video` doesn't get called when the video starts playing, it gets called when the `loadedmetadata` event is first triggered, which happens fractions of a second before the video starts playing. Therefore, it hides the poster before it should, and the background flashes.

From all HTMLMediaElement events, `timeupdate` is the only one that guarantees that a frame is playing, so we can listen to that event after the video is swapped in order to know when to hide the placeholder. All `play` or `playing` or `loaded...` events don't guarantee the video is actually playing, which is weird and the source of this bug. This fix works perfectly on Android (haven't tested on iOS)! It hides the poster image right when the video starts playing. Would have to check other implementations

I tried to dig into the `video` implementation specs on [HTML Spec](https://html.spec.whatwg.org/multipage/media.html) and couldn't find the reason why there's a delay between the `playing` event and the first frame, but it doesn't happen on desktop so my assumption is that it doesn't have to do with the specs but with the specific implementation details...
