### ISSUE TITLE
AMP story player: story is misaligned in page

### ISSUE THREAD

**Issue by rnkimani** [ampproject/amphtml#31360]
## What's the issue?
- The amp story player is misaligned in a page. 

## How do we reproduce the issue?
- It only happens in a few sites, [example](http://caretobeauty_com_marketing-demo.tappable.co/). Click on the bubble to load the story. 
<img width="442" alt="Screen Shot 2020-12-01 at 10 12 44" src="https://user-images.githubusercontent.com/45009681/100708673-cca2f800-33bd-11eb-8a70-a543db2e5837.png">

- I removed the position absolute and it worked. 
<img width="625" alt="Screen Shot 2020-12-01 at 10 11 23" src="https://user-images.githubusercontent.com/45009681/100708615-b006c000-33bd-11eb-8140-f81dd8ffdbb9.png">

## What browsers are affected?
- all

## Which AMP version is affected?
- latest

cc @Enriqe

**Comment by Enriqe** [comment]
Turns out the `text-align: center;` from the parent page was bleeding into the shadow DOM of the player, causing the iframe to have undesired alignment rules. I just sent out a PR to reset all styles coming from the parent document inside the iframe.

**Comment by Enriqe** [comment]
By the way, I notice in your example you are using both `exit-control` and the JSON configuration to specify a `close` button. I suggest you delete the `exit-control` attribute and just use the JSON configuration under the player since it's the new and preferred of displaying a close button. Having both may cause some undesired behavior.
