### ISSUE TITLE
[amp-story-player] Add events for page changes when using player APIs

### ISSUE THREAD

**Issue by pshihn** [ampproject/amphtml#31391]
## Describe the new feature or change to an existing feature you'd like to see

The amp-story-player lacks the capability to tell it to go to a specific page in a story through API. 
As a related feature, it should also fire events when the page changes.

**Comment by newmuis** [comment]
This is actually already supported.

/cc @Enriqe to provide the details (and also, do you know why docs don't list this?)

**Comment by Beethoven** [comment]
player.show(storyUrl, pageId)

https://github.com/ampproject/amphtml/pull/31198

**Comment by pshihn** [comment]
https://github.com/ampproject/amphtml/pull/31198 adds the method but no events though. Would be super useful to have events on page change as well.

Side note: Is the latest player available on CDN anywhere or do we just build it from this codebase?

**Comment by Enriqe** [comment]
That's right, the ability to tell the player to go to a specific page in a story is already supported. This hasn't made it to the docs because we were waiting the changes to hit production. Given that the release freeze is now over I will go ahead an update the [docs](https://github.com/ampproject/amphtml/blob/master/spec/amp-story-player.md#go).

For now, you can use either the [`go()` or `show()` methods](https://github.com/ampproject/amphtml/blob/master/spec/amp-story-player.md#go) to accomplish this.

* Use the second parameter in `go(storyDelta, pageDelta)` to change the page in the current or target story. e.g. `go(0, 1)` will move the page 1 page forward in the current story. `go(-2,3)` will move 2 stories backwards and then 3 pages forward on that story.
* Use the second parameter in `show(storyUrl, pageId)` to change the page in the current or target story. e.g. `show(null, 'targetPageId')` will change the current story to the `targetPageId` page. `show('story2.html', 'targetPageId')` will move to `story2.html and navigate to its `targetPageId`.

As for the event, we don't dispatch the `navigation` event when these APIs are used, but I think we should add support for this. I'll use this issue as a FR for that.

> Side note: Is the latest player available on CDN anywhere or do we just build it from this codebase?

Yes, it's available on the AMP cache, please refer to the [docs](https://github.com/ampproject/amphtml/blob/master/spec/amp-story-player.md#-amp-story-player) for the required scripts and the most recent [README](https://github.com/ampproject/amphtml/blob/master/src/amp-story-player/README.md) for more examples / usages. 

Hope this helps! :)

**Comment by pshihn** [comment]
@Enriqe According to docs `navigation` events are only fired when the story changes not when the page inside a story changes. (https://github.com/ampproject/amphtml/blob/master/spec/amp-story-player.md#custom-events) Are the docs missing this?

I don't think you need to fire events when API is called. Usually events are fired from user action or automatic transition, not through API calls. The user actions would be tapping to go to next/prev page, or when page changes automatically after the video plays.

**Comment by Enriqe** [comment]
Oh, my bad. There's another event (that we also hadn't added to the docs yet), called `storyNavigation`. It will fire whenever a user taps on next/previous page of the story. It includes `pageId` and `progress`, which will correspond to the page that was navigated to in the story and the progress (from 0 to 1).

**Comment by pshihn** [comment]
> Yes, it's available on the AMP cache, please refer to the [docs](https://github.com/ampproject/amphtml/blob/master/spec/amp-story-player.md#-amp-story-player) for the required scripts and the most recent [README](https://github.com/ampproject/amphtml/blob/master/src/amp-story-player/README.md) for more examples / usages.

I don't see the reference to cdn url for the the latest player. Everything points to https://cdn.ampproject.org/amp-story-player-v0.js

Also, `show(storyUrl, pageId)` is a good one, but it requires me to parse to story markup to get the page id. It would be much better to have an option where I can give the pageIndex instead. Not pageId or pageDelta.

**Comment by Enriqe** [comment]
> I don't see the reference to cdn url for the the latest player. Everything points to https://cdn.ampproject.org/amp-story-player-v0.js

Sorry, I'm not sure I understand what you need. That binary contains the latest player runtime.

> Also, show(storyUrl, pageId) is a good one, but it requires me to parse to story markup to get the page id. It would be much better to have an option where I can give the pageIndex instead. Not pageId or pageDelta.

Could you share a bit more of your use case? We can file that as a separate FR.

**Comment by pshihn** [comment]
i could not find the binary I guess only the 'amp-story-player-v0.js' which is the v0 version. I am perhaps missing the link to the binaries :/  or are you saying  'amp-story-player-v0.js' is the one with this feature? Sorry maybe I am missing something obvious. 

Regarding the feature, here's one use case: When you have multiple stories in a player and you want to go from one to the other, it remembers what page you were on in that story - so it goes to that page. I want to always start from the first page. I want to say `show(url, 0)`

**Comment by Enriqe** [comment]
>  is the one with this feature? 

Yes that is the latest runtime. You will always get the latest changes in production unless you are opted-in to beta or other channels.

> I want to always start from the first page. I want to say show(url, 0)

If you want the stories inside of the player to ignore the local storage and always start at the beginning, you can add a fragment parameter `#ignoreLocalStorageHistory=true` at the end of your story URL.  e.g. `mystory.html#ignoreLocalStorageHistory=true`.

An alternative is to call `go(0, -99999)` whenever the player switches from one story to the other to reset it to the first page.

**Comment by pshihn** [comment]
How do I opt into beta?

**Comment by Enriqe** [comment]
> How do I opt into beta?

Please refer to these docs https://github.com/ampproject/amphtml/blob/master/src/amp-story-player/README.md#i-want-the-bleeding-edge-and-latest-features-how-can-i-get-them

**Comment by pshihn** [comment]
> If you want the stories inside of the player to ignore the local storage and always start at the beginning, you can add a fragment parameter `#ignoreLocalStorageHistory=true` at the end of your story URL. e.g. `mystory.html#ignoreLocalStorageHistory=true`

This does not work. Created an issue with a live example: https://github.com/ampproject/amphtml/issues/31423

**Comment by Enriqe** [comment]
My bad, the fragment parameter is for a very specific use case that some player use when the iframe evicts the story and then places it in the iframe, resetting it to the first page.

Since it's a very particular use case, I would not recommend doing that and instead using the `go(0,-9999)` method I recommended earlier https://github.com/ampproject/amphtml/issues/31391#issuecomment-738281505.

**Comment by pshihn** [comment]
Yes. `go(0,-9999)`  does not work either: https://github.com/ampproject/amphtml/issues/31424 See the linked fiddle.
