### ISSUE TITLE
Can CSS break amp-state?

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#31532]
Here is a baseline AMP document using CSS, standard HTML elements and text. [1-amp-state-no](https://afdsi.com/amp-test/1-amp-state-no.html)

A valid document; no issues.

Here is a "no CSS" version of `1-amp-state-no` but which uses `amp-state`, `amp-list` and `amp-mustache`. [2-amp-state-yes-css-no](https://afdsi.com/amp-test/2-amp-state-yes-css-no.html)

A valid document; no issues.

Here is a version that combines the CSS from `1-amp-state-no` with the substitution structure of `2-amp-state-yes-css-no` [3-amp-state-yes-css-yes](https://afdsi.com/amp-test/3-amp-state-yes-css-yes.html)

A valid document; but CSS appears to break the application of `amp-state`, `amp-list` and `amp-mustache`.

Any thoughts about what's going on here, or what's wrong with `3-amp-state-yes-css-yes`?

**Comment by samouri** [comment]
The `<amp-list>` and `<amp-state>` is structured in a pretty confusing way that just happens to look like it works in the second example and breaks as I'd expect in the third.

The way its designed, each element in the `items` array ends up rendering the entire template. The way you're using it, you'd like the template to only render a single time but with all of the variables present.

In order to do that, you'll need to modify the data to be only a single item.  E.g. from :
```js
{ items: [ { { term1: "ex1" }, {term2: "ex2"} } ]
```

To:
```js
{ items: [ { term1: "ex1", term2: "ex2"} ] }
```

Note that you can also take advantage of [single-item](https://amp.dev/documentation/components/amp-list/#single-item) in this case.

I've modified your third example to demonstrate. You can see the result here: https://live-amp-bugs.glitch.me/issues/31532.html

**Comment by jaygray0919** [comment]
brilliant - thank you.
