### ISSUE TITLE
amp-iframe in amp-carousel disappears on slide change

### ISSUE THREAD

**Issue by dritter** [ampproject/amphtml#31583]
Hi there,

We found a Bug with iframes not being loaded in an amp-carousel. If you advance one slide, and go back to the iframe slide, you will see the placeholder forever (iframe is not loaded). But if you advance two or more slides and go back, the iframe is correctly loaded.

This happens with `amp-carousel v0.2`, but not with `v0.1`. 

See [reproducer in playground](https://playground.amp.dev/#share=PCFET0NUWVBFIGh0bWw+CjxodG1sIOKaoT4KICA8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04IiAvPgogICAgPHRpdGxlPk15IEFNUCBQYWdlPC90aXRsZT4KICAgIDxsaW5rIHJlbD0iY2Fub25pY2FsIiBocmVmPSJzZWxmLmh0bWwiIC8+CiAgICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoIiAvPgogICAgPHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1vei1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbXMtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7YW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGh9QC13ZWJraXQta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbW96LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1zLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW8ta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUBrZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19PC9zdHlsZT48bm9zY3JpcHQ+PHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOm5vbmU7LW1vei1hbmltYXRpb246bm9uZTstbXMtYW5pbWF0aW9uOm5vbmU7YW5pbWF0aW9uOm5vbmV9PC9zdHlsZT48L25vc2NyaXB0PgogICAgPHNjcmlwdCBhc3luYyBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwLmpzIj48L3NjcmlwdD4KICAgIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1pZnJhbWUiIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAvYW1wLWlmcmFtZS0wLjEuanMiPjwvc2NyaXB0PgogICAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLWNhcm91c2VsIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1jYXJvdXNlbC0wLjIuanMiPjwvc2NyaXB0PgogICAgPHN0eWxlIGFtcC1jdXN0b20+CiAgICAgIGgxIHsKICAgICAgICBtYXJnaW46IDFyZW07CiAgICAgIH0KICAgIDwvc3R5bGU+CiAgPC9oZWFkPgogIDxib2R5PgogICAgPGgxPkhlbGxvIEFNUEhUTUwgV29ybGQhPC9oMT4KICAgIDxhbXAtY2Fyb3VzZWwgbGF5b3V0PSJmaXhlZCIgd2lkdGg9MzgwIGhlaWdodD0yODAgdHlwZT0ic2xpZGVzIiBsb29wPgogICAgICA8YW1wLWlmcmFtZQogICAgICAgIHdpZHRoPSIyMDAiCiAgICAgICAgaGVpZ2h0PSIxMDAiCiAgICAgICAgc2FuZGJveD0iYWxsb3ctc2NyaXB0cyBhbGxvdy1zYW1lLW9yaWdpbiIKICAgICAgICBsYXlvdXQ9InJlc3BvbnNpdmUiCiAgICAgICAgZnJhbWVib3JkZXI9IjAiCiAgICAgICAgc3JjPSJodHRwczovL3d3dy5nb29nbGUuY29tL21hcHMvZW1iZWQvdjEvcGxhY2U/a2V5PUFJemFTeUF5QVM1OTlBMkdHUEtUbXROcjlDcHRENjFMRTRnTjZvUSZxPWljZWxhbmQiCiAgICAgID4KICAgICAgICA8ZGl2IHBsYWNlaG9sZGVyPgogICAgICAgICAgTG9hZGluZy4uLgogICAgICAgIDwvZGl2PgoJICA8L2FtcC1pZnJhbWU+CiAgICAgIDxhbXAtaW1nIHNyYz0iaHR0cHM6Ly9waWNzdW0ucGhvdG9zLzM4MC8yODAiIGxheW91dD0iZml4ZWQiIHdpZHRoPTQwMCBoZWlnaHQ9MzAwPjwvYW1wLWltZz4KICAgICAgPGFtcC1pbWcgc3JjPSJodHRwczovL3BpY3N1bS5waG90b3MvMzgwLzI4MSIgbGF5b3V0PSJmaXhlZCIgd2lkdGg9NDAwIGhlaWdodD0zMDA+PC9hbXAtaW1nPgogICAgICA8YW1wLWltZyBzcmM9Imh0dHBzOi8vcGljc3VtLnBob3Rvcy8zODAvMjgyIiBsYXlvdXQ9ImZpeGVkIiB3aWR0aD00MDAgaGVpZ2h0PTMwMD48L2FtcC1pbWc+CiAgICAgIDxhbXAtaW1nIHNyYz0iaHR0cHM6Ly9waWNzdW0ucGhvdG9zLzM4MC8yODMiIGxheW91dD0iZml4ZWQiIHdpZHRoPTQwMCBoZWlnaHQ9MzAwPjwvYW1wLWltZz4KICAgICAgPGFtcC1pbWcgc3JjPSJodHRwczovL3BpY3N1bS5waG90b3MvMzgwLzI4NCIgbGF5b3V0PSJmaXhlZCIgd2lkdGg9NDAwIGhlaWdodD0zMDA+PC9hbXAtaW1nPgogICAgPC9hbXAtY2Fyb3VzZWw+CiAgPC9ib2R5Pgo8L2h0bWw+Cg==).

Screen recording:
![amp-iframe-in-carousel](https://user-images.githubusercontent.com/1544760/102056917-6bcbe480-3ded-11eb-8653-97aefe0d8e4a.gif)

The AMP Version is at least `2011252111002`.

**Comment by micajuine-ho** [comment]
Hi @dritter, thanks for your bug report!

AMP carousel handles the scheduling of resources for its children elements (in order to optimize for performance), which includes scheduling their layouts, unlayouts, pausing, and resuming. 

Specifically for `<amp-iframes>`, when their owner pauses them (due to them exiting the viewport), the `pauseCallback()` is not implemented, but they still get unlaid-out due to having `unlayoutOnPause()`:
https://github.com/ampproject/amphtml/blob/f874e89ca8cbba68fec093666e8e908c32990ee1/extensions/amp-iframe/0.1/amp-iframe.js#L607-L610
https://github.com/ampproject/amphtml/blob/f874e89ca8cbba68fec093666e8e908c32990ee1/src/service/resource.js#L1090-L1098

When the `<amp-iframe>` returns to the viewport immediately, without having its layout scheduled (aka when you go forward only 1 slide),  the owner calls the `resumeCallback()`, but it's not implemented, and thus the placeholder remains.

2 possible fixes:
- Implement `resumeCallback()` for amp-iframe, that lays-outs the element again
- Create some `layoutOnUnpause()` method that will default to `false` but return `true`, for amp-iframe, causing it to be relaid-out when the owner tries to resume.

@samouri Do you have any thoughts on this?

**Comment by samouri** [comment]
Nice find and writeup @micajuine-ho!
Do we know how widespread this issue is? Is this affecting each and every component that has `unlayoutOnPause` enabled and doesn't implement a `resumeCallback`?

If this is indeed affecting all of them, we could add logic to the `resume()` fn of resources.js to automatically layout components that were laid out due to `unlayoutOnPause`

**Comment by samouri** [comment]
Reading the docs on [destroying heavyweight resources](https://github.com/ampproject/amphtml/blob/master/contributing/building-an-amp-extension.md#destroying-heavyweight-resources)

> Note if your element unlayoutCallback destroys the resources, it probably wants to return true in order to signal to AMP the need to call layoutCallback again once the document is active. Otherwise your element will never be re-laid out.

`<amp-iframe>` currently returns true from `unlayoutCallback`, so maybe something else is at play?

https://github.com/ampproject/amphtml/blob/d619dac38b7465bfb9fd616c72b1e179196bb03f/extensions/amp-iframe/0.1/amp-iframe.js#L635-L637

**Comment by micajuine-ho** [comment]
@samouri Thanks for the reply!

> Reading the docs on destroying heavyweight resources

Thanks for including this, didn't know we had a doc describing this!

From my understanding, returning `true` in `unlayoutCallback()` will mark the element as eligible for relayout in the future.  

https://github.com/ampproject/amphtml/blob/1e0e5bb46a445e13d4f1d9a0371b12d2203b33e6/src/service/resource.js#L1067-L1078

However, I think the problem here is that when the `paused` <amp-iframe> becomes visible, <amp-carousel> only tries to schedule it to resume (i.e. amp-iframe#resumeCallback() which doesn't exist) and not to layout. 

Does that sound correct?

**Comment by dritter** [comment]
This seems to be fixed with the release of `2101230412006`. I suspect that it got fixed along with https://github.com/ampproject/amphtml/issues/32449 .
Only a small Issue remains: The IFrame gets reloaded completly on switching one slide, but not if I switch multiple slides. IMHO the full reload is unnecessary.

**Comment by samouri** [comment]
FYI @dvoytenko

**Comment by dvoytenko** [comment]
Correct, #32449 should fix this. The full reload, I believe, has always existed in that case b/c there's no safe way to pause an iframe otherwise and it could be a problem with the playback going on where a user might not be able to find where it's coming from.

**Comment by dritter** [comment]
Thanks for the explanation @dvoytenko .
I am not sure what I saw. It looked to like there is a difference how the IFrame is brought back to life depending on how many slides I change. But I cannot reproduce this behavior. So, I close this issue as works as expected.
