### ISSUE TITLE
Issue when submitting AMP-Form from Gmail context

### ISSUE THREAD

**Issue by davecook88** [ampproject/amphtml#31612]
**Please only file reports about bugs in AMP here.**

- If you have questions about how to use AMP or other general questions about AMP please ask them on Stack Overflow under the AMP HTML tag instead of filing an issue here: http://stackoverflow.com/questions/tagged/amp-html
- If you have questions/issues related to Google Search please ask them in Google's AMP forum instead of filing an issue here: https://goo.gl/utQ1KZ

If you have a bug for AMP please fill in the following template. Delete everything except the headers (including this text).

## What's the issue?

The issue is that on amp-form submissions from the Gmail inbox context are failing, despite working from the AMP playground and AMP Gmail playground. This error is displayed:

```
Uncaught (in promise) Error: Class$obf_1009: [https://dynamicmail-pa.googleapis.com/v2/xhrs:proxy?alt=protojson] Cg: Unsupported HTTP status: 400: Class$obf_1011: [object Object]

log.js:258 [amp-form] Form submission failed: Error: Request viewerRenderTemplate failed: Error: Class$obf_1009: [https://dynamicmail-pa.googleapis.com/v2/xhrs:proxy?alt=protojson] Cg: Unsupported HTTP status: 400: Class$obf_1011: [object Object]
```

This is occurring from a server/email configuration which previously was successfully able to post from the Gmail context.

## How do we reproduce the issue?

Here is a simplified version of the email form being used.

https://gist.github.com/davecook88/0ec9217aac511c879f626f9476792fa2

Here is a link to a simplified version of my Firebase configuration: https://github.com/davecook88/firebase-minimal

The AMP email retrieves data relating to a specific task in Firestore. In order to create a task, here is the CURL command:

```
curl --request POST \
  --url [BASE_URL]/app/api/task \
  --header 'Content-Type: application/json' \
  --header 'origin: https://playground.amp.dev' \
  --data '{
	"name":"task name",
	"author": "Dave",
	"checklist":[
		{"title":"item 1", "checked":false},
		{"title":"item 2", "checked":false},
		{"title":"item 3", "checked":false}
	]
}'

In the body of the email posted in my original question, the urls in lines 40 and 45 will need to be modified to query this specific task.

Clicking a checkbox in the email should trigger a form post to the server but instead it throws an error
````

## What browsers are affected?

All browsers? Some specific browser? What device type?

## Which AMP version is affected?

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)

This was working until around 2 weeks ago. I have reverted my configuration to a known working version and the same issue arises.

**Comment by davecook88** [comment]
Is it fair to say that this is an issue with AMP. Since posting this, I have continued to search for an answer to this issue but without success.

I can confirm that the [AMP toolbox library](https://github.com/ampproject/amp-toolbox), which is recommended on the official AMP documentation, causes the same issue.

I have also replicated the CORS code listed on the AMP documentation in NodeJS. I'll copy this below:

```
app.use((req, res, next) => {
    res.set("Access-Control-Allow-Credentials", true);
    let senderEmail;
    console.log("request received");
    console.log("headers", req.headers);
    if (req.headers["AMP-Email-Sender"]) {
        console.log("request received");
        senderEmail = req.headers["AMP-Email-Sender"];
        if (isAllowedEmail(senderEmail)) {
            res.set("AMP-Email-Allow-Sender", senderEmail);
        }
    } else if (req.headers["origin"]) {
        const reqOrigin = req.headers["origin"];
        if (!req.query.__amp_source_origin) {
            return next(new Error("Not allowed by CORS"));
        } else {
            senderEmail = req.query.__amp_source_origin;
            if (!isAllowedEmail(senderEmail)) {
                return next(new Error("Not allowed by CORS"));
            }
        }
        console.log("reqOrigin", reqOrigin);
        console.log("senderEmail", senderEmail);
        res.set("Access-Control-Allow-Origin", reqOrigin);
        res.set(
            "Access-Control-Expose-Headers",
            "AMP-Access-Control-Allow-Source-Origin"
        );
        res.set("AMP-Access-Control-Allow-Source-Origin", senderEmail);
        return next();
    }
});
```

**Comment by pankajanand18** [comment]
We are facing the same issue. 
```javascript
Uncaught (in promise) Error: Class$obf_1010: [https://dynamicmail-pa.googleapis.com/v2/xhrs:proxy?alt=protojson] Cg: Unsupported HTTP status: 400: Class$obf_1016: [object Object]
    at T2m (m=rn4kU,yWJZbc,PaBahd,MMhUM,cs,zm225,o2ajQe,kRtote,Av2a7c,kbPIy,igbF5,Trl7bc,cv,dFpypf,MigGy,jVZ0pe,rMQdJc,Sz7W7c,CTcde,NVcOs,PZhDZb,Aihl6c,J03Die:118)
    at U2m (m=rn4kU,yWJZbc,PaBahd,MMhUM,cs,zm225,o2ajQe,kRtote,Av2a7c,kbPIy,igbF5,Trl7bc,cv,dFpypf,MigGy,jVZ0pe,rMQdJc,Sz7W7c,CTcde,NVcOs,PZhDZb,Aihl6c,J03Die:118)
    at m=cm,RGIyZe,WQKEXd,Yns7ze,Xg6p3c,DjaFmc,e,be,blMNCd,J0c0De,p59Uie,zPd59e:3265
    at Object.AQa.wa (m=b:504)
    at m=b:1723
    at Object.Vnb.Aa (m=b:1713)
    at Object.j_a.Aa (m=b:828)
    at m=b:2912
    at Object.OMa.Aa (m=b:367)
    at Yoc (m=b:2927)
```


The exact response from the API call  to `dynamicmail` is below:
```

--batch_N7ZM4-keNf7_f20ClhUOtCxePixT0GgN
Content-Type: application/http
Content-ID: <response-batch360949235667429450+gapiRequest@googleapis.com>

HTTP/1.1 400 Bad Request
Vary: Origin
Vary: X-Origin
Vary: Referer
Content-Type: application/json+protobuf; charset=UTF-8

{"1":3,"2":"Request contains an invalid argument."}
--batch_N7ZM4-keNf7_f20ClhUOtCxePixT0GgN--
```

**Comment by davecook88** [comment]
@pankajanand18 I've received an answer from someone at Google about this. 

There's a bug with AMP forms submitting with `enctype=3D"application/x-www-form-urlencoded"` which has been submitted for resolution. 

I'll update this thread when I have an update on the ticket.

**Comment by pankajanand18** [comment]
Thanks for the response @davecook88 . Really appreciate it. 🙏
 Looking forward to get another update.

**Comment by zhangsu** [comment]
Just an FYI: for that exact issue Dave mentioned at https://github.com/ampproject/amphtml/issues/31612#issuecomment-752297123, the workaround is to remove the `enctype` attribute from `<form>` so that it defaults to `multipart/form-data`. Gmail currently converts form data to `application/x-www-form-urlencoded` behind the scene, so it should virtually have the same behavior whether `enctype` is specified.

**Comment by pankajanand18** [comment]
@zhangsu  that worked liked charm for our case. thanks a ton.

**Comment by M-J-Robbins** [comment]
I just hit this same issue, came here to report it but good to see it's already logged.  

Adding a note that where Gmail and [Gmail playground](https://amp.gmail.dev/playground/) will convert to `application/x-www-form-urlencoded` the [AMP playground](https://playground.amp.dev/?runtime=amp4email), the [mail.ru playground](https://postmaster.mail.ru/amp/playground.html) and Mail.ru will all still submit as `multipart/form-data`.

So there may be some inconsistencies in the data received from Gmail users compared to mail.ru users (I've not tested Yahoo! yet).

**Comment by c10r** [comment]
+1 I just his this bug as well. Would love to hear if there's an ETA on a fix anytime soon?

**Comment by princesslafayette** [comment]
Hi there, I'd just like some clarification since the issue is fixed: is it expected behaviour that Gmail converts forms of type `multipart/form-data` to `application/x-www-form-urlencoded`? And if so is there a way to allow Gmail to enforce using `multipart/form-data`?

**Comment by zhangsu** [comment]
> Hi there @zhangsu , I'd just like some clarification since the issue is fixed: is it expected behaviour that Gmail converts forms of type `multipart/form-data` to `application/x-www-form-urlencoded`? And if so is there a way to allow Gmail to enforce using `multipart/form-data`?

Hey @princesslafayette! This issue here is about the Gmail proxy responding with an error when `enctype="application/x-www-form-urlencoded`, and that has been fixed. The issue you mentioned (Gmail converting `multipart/form-data` to `application/x-www-form-urlencoded`) is separate. Unfortunately, there's currently no workaround for the conversion. The Gmail proxy doesn't support the `multipart/form-data` serialization on the server side.

In practice, the difference between `multipart/form-data` and `application/x-www-form-urlencoded` should rarely matter for AMP for Email because
1. the spec doesn't allow sending binary data (otherwise, `multipart/form-data` would be more efficient in encoding binary data)
2. virtually all modern web servers should be able to handle both types of encodings and let application developers consume the form data in a unified way. Developers usually use a web server framework to handle deserialization of form data, so the differences are usually abstracted away by the framework.

Is there a particular reason why you want to specifically receive the form data encoded with `multipart/form-data`?

**Comment by zhangsu** [comment]
Hmm, that sounds like bug somewhere along the way. Reversed characters in a URL should be URL-encoded so that they are never ambiguous. `;` is indeed a reserved character in URL, so the Gmail proxy should URL-encode it. For the expected form data you mentioned, I would expect the Gmail proxy to pass you `selection=3&comment=hello%59hi` so that it will be parsed correctly by the Go server. If you can come up with a minimal repro for this issue, I can take a look and see where the bug is.

**Comment by zhangsu** [comment]
@samouri do you mind closing this issue since it's fixed in Gmail?

**Comment by samouri** [comment]
@zhangsu: I'm no longer an active contributor to AMP (and don't have permissions).

/to @jridgewell
