### ISSUE TITLE
amp-youtube/amp-video not pausing on subsequent plays

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3169]
Both `amp-youtube` and `amp-video` seems to have troubles pausing specially on subsequent plays and pauses.

## How do we reproduce the issue?
1. Open the [viewer example](http://amp-mk-1.herokuapp.com/examples.build/viewer.html).
2. Scroll down to the YouTube video and click to play it
3. Switch the viewer to Tab "Two" to make "One" go into visibityState=hidden
4. Notice the youtube video is paused correctly
5. Go back to One and confirm YouTube player is in fact paused.
6. Resume playing the video.
7. Switch to Two again.
8. Notice the YouTube player does not pause this time! 

## What browsers are affected?
Tested on Chrome Version 50.0.2661.94 (64-bit) Desktop.

Same thing seems to happen with `amp-video`.

I haven't tried reproducing this on production in the Google Carousel, but it could be happening there as well.

cc / @muxin

**Comment by mkhatib** [comment]
Was able to reproduce this on news.google.com carousel on __emulated__ Safari iOS with `amp-youtube` video not pausing when swiping away.

**Comment by mkhatib** [comment]
This is reproducable also on production in the video lightbox on https://www.ampproject.org/ - open the dialog, wait for the video to load, play it, close the lightbox, will pause first time but open the dialog again play and close and it won't pause!

**Comment by rudygalfi** [comment]
@mkhatib Any updates on this? If not a priority, can you change milestone?

**Comment by mkhatib** [comment]
@muxin have you made any progress on this?

**Comment by aghassemi** [comment]
Chatted with @muxin, I will take the issue.

**Comment by aghassemi** [comment]
This is due to a bug in resource and affects multiple components that do manual pause scheduling (`amp-sidebar`, `amp-lightbox` and `amp-carousel`) so a video inside all of those components will suffer from the same bug.

The issue is trivial to fix but wondering what you think about the two possible approaches. The issue is that manual calls to `schedulePause` put a component in a permanent* paused mode, two options for a fix:
1. Introduce a `scheduleResume` that components that do manual calls to `schedulePause` must call when appropriate. (e.g. lightbox `close()` calls `schedulePause` and lightbox `open()` calls `scheduleResume`). `scheduleResume` won't do anything for component's that are not paused already.
2. Runtime automatically calls `resume` for paused elements after the layout call is finished. (this assumes there is never a case where you want to do layout without resuming, which might be totally false)

I like option 1, it is explicits but it is easier to miss than option 2.

*Not completely permanent, the only way to get out of it is if the whole document goes to pause and back to resume again. (e.g. document swipe)

cc: @cramforce @dvoytenko @jridgewell

**Comment by dvoytenko** [comment]
I think only option (1) would work at this time. Subsequent layouts will not be called second time, e.g. when a carousel is swiped back again.
