### ISSUE TITLE
Allow <section> / <blockquote> / maybe other tags on mustache triple brace syntax

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#32039]
- `section` is fine ([friends](https://github.com/ampproject/amphtml/issues/32039#issuecomment-763030874) are also probably fine)
- `blockquote` is fine.
- `pre` is probably fine.
- we likely need to go through a standard tag list so that we don't need to include tags piecemeal again.

https://github.com/ampproject/amphtml/blob/0827b5bee99e121d88a76f5e03ea026c6cac4afc/src/purifier/sanitation.js#L113-L124

/cc @ampproject/wg-components 
/cc @caroqliu 
/cc @jaygray0919

**Comment by dvoytenko** [comment]
I certainly don't see a problem whitelisting `<section>` and `blockquote`. A bit surprised they are not whitelisted already. I thought our purify dictionaries should be up-to-date?

**Comment by caroqliu** [comment]
I don't have the context for why we have as limited of a set of allowed tags as we do, and support proactively expanding this set. It would be nice if this was up to date so folks who need disallowed tags don't have to go through the 2-week release cycle to get it, especially if we don't have a good reason why it is disallowed in the first place.

Since sanitization is involved, maybe @ampproject/wg-security-privacy could advise here as well?

**Comment by alanorozco** [comment]
@dvoytenko I think we just missed all the "semantic elements" that act like `<div>`. If `<section>` is fine, then maybe so are all of these:

- `<article>`
- `<aside>`
- `<details>`
- `<figcaption>`
- `<figure>`
- `<footer>`
- `<header>`
- `<main>`
- ~~`<mark>`~~ (included)
- `<nav>`
- `<section>`
- `<summary>`
- `<time>`

**Comment by jaygray0919** [comment]
One last request here: `<pre>`. We have this statement that, currently, is ineligible for triple braces: `<pre class="line-numbers language-html">` (which, in JSON, of course would be: `<pre class='line-numbers language-html'>`). As you might expect, that element + class formats code with line numbers. Currently, the statement is inline HTML. We would like to include it in JSON (with the balance of the related content.

**Comment by jaygray0919** [comment]
@alanorozco can we depend on the above changes to be made in the near future? We're at a point where we can edit several triple brace documents and would like to move the target elements into JSON. We're OK if the pages fail the validator since the pages won't be in production until February 2021. The important elements for us (at this time) are `<section>` `<blockquote>` and `<pre>`.

**Comment by alanorozco** [comment]
@jaygray0919 

@dmanek will be making this change soon. The change should be in production within what's typically two weeks after merging.

**Comment by jaygray0919** [comment]
Thank you. Will reduce complexity.

**Comment by honeybadgerdontcare** [comment]
> I don't have the context for why we have as limited of a set of allowed tags as we do, and support proactively expanding this set. It would be nice if this was up to date so folks who need disallowed tags don't have to go through the 2-week release cycle to get it, especially if we don't have a good reason why it is disallowed in the first place.
> 
> Since sanitization is involved, maybe @ampproject/wg-security-privacy could advise here as well?

We prefer an allowedlist if there is ever a situation where a disallowed list may be needed in the future. Also in favor of expanding the list as requests come in. A 2-week cycle seems an okay trade off with having to do an emergency sanitization.

**Comment by zhangsu** [comment]
This allowlist of triple Mustache tags is shared with the email format, so we should've consulted @ampproject/wg-amp4email before modifying this list. triple-mustache is a pretty security sensitive feature in the email format, and adding non-formatting tags like amp-img to the allowlist requires a security review.

This is still okay-ish for now, since for some email clients (like Gmail) the Mustache is actually rendered on the server side, and the server uses a different triple-mustache allowlist. However, for consistency with email clients who don't server-side render the template we should keep the client-side sanitization consistent. I think the best path forward here to prevent this from happening in the future is to use a separate list for email so we don't accidentally modify the email format when there are requests to add new tags for the website format. We can still add to the email allowlist on a case-by-case basis.

/cc @samouri
