### ISSUE TITLE
Script cdn.ampproject.org/v0/amp-ad-0.1.js is identified as Potentially Suspecious file by "https://scanner.pcrisk.com/"

### ISSUE THREAD

**Issue by kakinada9** [ampproject/amphtml#32092]
I tried to scan my websit "https://www.kakinada9.com" for any suspecious Phishing/Malware detection using the online scanner "https://scanner.pcrisk.com/" in the end report I got a result  show that my website has a Potentially suspecious  File and the file is "cdn.ampproject.org/v0/amp-ad-0.1.js" Could you help me in this regard, why this file might be Suspecious. Is this the problem with my website or scanner or the script..

This the screenshot of the scan result
https://prnt.sc/xbxajx

**Comment by kristoferbaxter** [comment]
This appears to be an issue with the scanning software, not the Open Source library. Using `JSON.parse` instead of inlining a large Object literal is a preferred approach. 

<img width="1090" alt="Screen Shot 2021-01-21 at 11 47 45 AM" src="https://user-images.githubusercontent.com/61764/105404163-8197ab00-5bde-11eb-8108-673a62805e58.png">

Additional information is available here: https://www.youtube.com/watch?v=ff4fgQxPaO0
