### ISSUE TITLE
Add support for Text Fragments in AMP

### ISSUE THREAD

**Issue by sebsg** [ampproject/amphtml#32139]
## Describe the new feature or change to an existing feature you'd like to see

Chrome has implemented this new [W3C draft spec about Text Fragments](https://wicg.github.io/scroll-to-text-fragment/) that allows linking to specific parts of a web page. Upon opening the link the browser will scroll-to and highlight the specified section.

While this works on most sites, one big issue with the feature currently is that it doesn't work on AMP pages. For example, the text fragment anchor part of the URL seems stripped from most AMP pages when loaded. From my understanding of AMP, there might be other issues even if the fragment was not stripped.

Some examples:

- https://www.google.com/amp/ampexamples.com/amp-html-1410.html#:~:text=Recently%20the%20AMP%20project%20becomes%20more%20and%20more%20popular,%20especially%20considering%20it's%20being%20powered
- https://amp-reddit-com.cdn.ampproject.org/v/s/amp.reddit.com/r/OutOfTheLoop/comments/53ztlp/what_is_ampredditcom/?amp_js_v=a6&amp_gsa=1&usqp=mq331AQHKAFQArABIA%3D%3D#:~:text=some-,Reddit,-threads

There seems to be a way to make this work since some pages loaded from a search results page work (e.g. search for "when is ios 14.3 coming out")

Would it be possible to add support for scroll-to text fragments?

**Comment by bokand** [comment]
Since the fragment directive (everything including and after `:~:`) is hidden from the page, it isn't the AMP page somehow interfering with it. A page writing to the `location.hash` will cause it to clear the text fragment from the omnibox but that's a small UI glitch, it shouldn't affect behavior.

I believe the AMP viewer displays the content in an iframe? If so, that's the reason we don't get text highlighting, to enforce [origin isolation](https://wicg.github.io/scroll-to-text-fragment/#example-4d0b486d:~:text=the%20malicious%20page%20can%20determine%20if,blur%20event%20in%20its%20own%20document), text fragments only work in the main frame.

I think the most promising solution would be to expose information about the text fragment to the page (see https://github.com/WICG/scroll-to-text-fragment/issues/128) and have the root AMP page pass through the data to the iframe'd content.

IIRC, AMP actually had an implementation of scroll-to prior to text-fragment support in the browser, that could be reused (though the matching algorithm may need to be updated to support the text-fragment semantics). Alternatively, there is an open source implementation of the text-fragment spec (see https://github.com/WICG/scroll-to-text-fragment/issues/135) that we could probably pull in.

Could someone on the AMP side comment on the feasibility of this approach (+confirm my assumptions above)?

**Comment by dmanek** [comment]
@bokand I haven't had a chance to look into this in depth. Plan to start looking next week and will comment when I have something.

**Comment by eligrey** [comment]
@bokand fragment directives are still accessible, albeit in a slightly-convoluted manner. See https://github.com/WICG/scroll-to-text-fragment/issues/128#issuecomment-831546941 for some utils that can help web devs interoperate with these directives.

**Comment by dmanek** [comment]
Closing this issue as it is now verified using Chrome >= 93.
