### ISSUE TITLE
Allow target blank for amp-story-page-attachment Links

### ISSUE THREAD

**Issue by ghelapratik** [ampproject/amphtml#32171]
Currently, while linking the page attachment to an external URL opens the URL in the same window. This behavior is taking away people from the story and the flow is broken and confusing. A good alternative to this will be to open the external URLs in a new tab. So, allowing target="_blank" in the <amp-story-page-attachment> tag will be really helpful.

**Comment by Enriqe** [comment]
/cc @gmajoulet @newmuis @raovs for product decision on opening it in the same window.

@ampproject/wg-stories

**Comment by gmajoulet** [comment]
This is technically infeasible because of browser limitations. Opening a link in a new tab requires a trusted event gesture, and iOS Safari doesn't consider a "swipe" gesture as such. Ie: on swipe, you can only open a link in the same window.

If you want to open a link in a new tab you have to use something that can only be clicked (regular link), not swiped (page attachment).
