### ISSUE TITLE
[amp-next-page] AMP Client ID changes when scrolling through to amp-next-page in AMP Viewer

### ISSUE THREAD

**Issue by Cauchon** [ampproject/amphtml#32305]
## What's the issue?

The [AMP Client ID](https://webcache.googleusercontent.com/search?q=cache%3AVRskkkr1q5IJ%3Ahttps%3A%2F%2Fdevelopers.google.com%2Fanalytics%2Fdevguides%2Fcollection%2Famp-analytics%2Fclient-id%20&cd=1&hl=en&ct=clnk&gl=us) (used in amp-analytics) is changing on scrolling into amp-next-page in an amp viewer (but not on publisher origin).

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Go to https://www.google.com/amp/s/www.cnet.com/google-amp/news/nasa-curiosity-rover-snaps-dramatic-mars-selfie-at-scenic-mont-mercou/ in mobile emulator with network tab open in Devtools.
2. Scroll through and into the second article.
3. Search for "v56=&AQE=1" in the network tab. You should see two records. Compare the vid query params for each of them. They are distinct even though they are for the same session. (If you open another tab and go to, for example, https://www.google.com/amp/s/www.cnet.com/google-amp/news/nasa-curiosity-rover-snaps-dramatic-mars-selfie-at-scenic-mont-mercou/ and scroll through, you will see that the client id of the first article will correspond to that of the first article of the previous stream you looked at, but the second article won't)

## What browsers are affected?

Viewer only. Chrome

## Which AMP version is affected?

2101211748002

(cc @dmanek)

**Comment by micajuine-ho** [comment]
cc @dmanek Maybe we should take a look at this during fixit week :)

**Comment by micajuine-ho** [comment]
To recap the situation:

Publisher Origin:
- Parent pages loads and creates or retrieves CID per its ampdoc
- Parent page loads the 'next page' as an iframe
- The 'next page' iframe retrieves CID per its ampdoc (the same as the parent amp doc) 
- The CIDs are the same 

Viewer: 
- Parent iframe loads and creates or retrieves CID per its amp doc 
- Parent iframe loads the "next page" as an iframe 
- The "next page" iframe retrieves CID per its amp doc, which is different from the parent amp doc 
- The CIDs are not the same 

Possible Solutions 
- Check in CID if we are in next page context, then grab parent CID (Extra work for all docs)
- Preset CID in the iframe before we load the page, within next page service (feasibility?)
- Use linker to pass CID (does not guarantee load)
- In analytics override default client ID to check for top level amp doc (probably won't work because of FIE)

**Comment by anooplath** [comment]
Was this resolved ? I am having same issue for amp-next articles.
