### ISSUE TITLE
Intent to implement: Apester unit embed

### ISSUE THREAD

**Issue by benbakhar** [ampproject/amphtml#3233]
This proposed `<amp-apester>` component would embed a responsive Apester unit in an iframe. 
This single component would support publishers using Apester CMS and enable them easy embed in AMP articles.

Exmaple:

```
<amp-apester
    data-interaction="573a302aeac5f7343b74dae1"
    height=“390”>
</amp-apester>

```

This markup exmaple will create an iframe with src [https://preview.qmerce.com/interaction/573a302aeac5f7343b74dae1](https://renderer.qmerce.com/interaction/573a302aeac5f7343b74dae1)

The data-\* attributes are basic configuration options for the units, for example the interaction attribute which determines the id for a specific embed unit.

BB.

**Comment by cramforce** [comment]
This looks good. You will likely need a `layout` attribute. Should the value be `fixed-height` or `responsive`?

**Comment by dvoytenko** [comment]
@benbakhar Thanks a lot. This sounds great. Two quick questions to start this off:

1. Sizing: how predictable is the sizing of your widgets? AMP is pretty opinionated as far as initial layout concerned to avoid disruptions due to unexpected resizes. We provide a few models to accommodate typical layout needs and hopefully these widgets would fit into that well.

2. E.g. with polls, do you currently do some work to ensure a one-person-one-vote?

**Comment by benbakhar** [comment]
Hey guys thanks for answering,

@cramforce i guess we will use the `fixed-height` property as our units indeed have fixed height per unit across all platforms.

@dvoytenko to ensure one person one vote we are using local storage api if supported on client. about our unit's sizes, we are using fixed height with fluid width layout supporting `max-width` of 700px

**Comment by cramforce** [comment]
LGTM

**Comment by cramforce** [comment]
Would `amp-poll-apester` make sense here?

We're trying to make the names a bit more useful :)

**Comment by OksanaSemenov** [comment]
@cramforce regarding the name: 
amp-apester 
or 
amp-apester-media 

thanks!

**Comment by cramforce** [comment]
The name should encode what it is for. It is used for more than polls?

**Comment by dvoytenko** [comment]
@benbakhar Thanks for the responses! And what do you store in the local storage? I'm asking because AMP requires a greater document embed-ability and there are some notable restrictions for use of local storage in iframes, especially in Safari. E.g. see https://github.com/ampproject/amphtml/issues/2970#issuecomment-214530415

**Comment by Adirbe** [comment]
@OksanaSemenov @cramforce Apester is used for all storytelling purpose, so publishers can use polls, quizzes, Journey, video and more - so not just polls :)

We would love to get amp-apester-media or amp-apester-stroytelling

Thank you!

**Comment by cramforce** [comment]
SGTM 
Would there be a type attribute that makes it semantically visible what type of embed is being shown?

**Comment by Adirbe** [comment]
@cramforce Sure! for each engine there is a other logo.

**Comment by benbakhar** [comment]
@cramforce currently we are no using any data attribute like so.

**Comment by ericlindley-g** [comment]
@cramforce Is this ready for a PR, or are there any outstanding questions beforehand?

**Comment by cramforce** [comment]
Can definitely move into a PR!

**Comment by mrsufgi** [comment]
Hey all :) 
we submitted a PR for <amp-apester-media> 
https://github.com/ampproject/amphtml/pull/4291

@cramforce @benbakhar @OksanaSemenov  👍

**Comment by dvoytenko** [comment]
@mrsufgi Thanks again! I've update the PR to clarify the necessary steps for loader, but the current PR is pretty close.

RE: resize changes

The exception to use `changeSize` is possible, but we'd like to understand how you'd go about recommending initial size for static layout? The goal is for users to be able to specify a fairly close initial size to avoid jarring jumps and relayouts.

**Comment by mrsufgi** [comment]
regarding https://github.com/ampproject/amphtml/pull/4755: resize changes.

apester-media unit flow is starts with presenting the user with a loader and later we display the actual content. The preloader have a static size (based on the 'height' property.  Once the content is available and we get the size again (in most of the cases is the same as for pre-loader), in the rare cases the editor have changed the content, this affected the size and will force us to resize the unit. We want to display it with the new size without a button. In terms of user experience, since the loader is replaced with the content the user should not experience any visible resizing happening. 

On this page you can see an illustration of our complete flow  http://www.pcwelt.de/news/Achtung-Fake-Whatsapp-Kettenbrief-droht-Nutzern-10041831.html

In our editor, we calculate the exact height of the unit, then, we provide the editor with the exact snippet. Embedding the snippet as is won't trigger any resizing events.
When an editor updated a media, we recalculate the height and generate a new snippet with the updated values. Since we want the end users to have the best experience (no jarring jumps and resizing events) in every platform we encourage the editor to re-embed the unit in the website, or update the value.
This 'warning' will persist until the editor decide to remove it. In this stage, the editor is well informed of the consequences of not re-embedding the unit and most likely corrected the unit size parameters. 

We also want to log a warning in console when the sizes mismatch, which will also push editors and webmaster to fix the parameters.  

The ChangeHeight call is here to cover the gap between 'initial embed' and 'updated embed'.

In playlist mode, it's a little tricky. we plan to update the API endpoint to receive an optional 'height' property obtained from the html element itself. Then, return the media with the closest height in this playlist. we are open for better ideas on how to support unknown height (we know it only after the queryMedia xhr-promise request to display-service.

**Comment by dvoytenko** [comment]
@mrsufgi Thanks! Could you remind me if it's easy to tell apart playlist mode from normal units in `amp-apester-media.js`. If so, we can go ahead and use `changeSize` for the normal units and we'll discuss playlists in a bit more detail.

**Comment by mrsufgi** [comment]
@dvoytenko it is indeed easy differentiate normal from playlist, 
normal attribute: data-apester-media-id 
playlist attribute: data-apester-channel-token
I'll get right to it. Thank you

**Comment by mrsufgi** [comment]
@dvoytenko long time no see, had to put my resources elsewhere but I'm back on track with our plugin, I'll push a commit with changeHeight for normal medias soon.

**Comment by mrsufgi** [comment]
In addition, how do we request changing apester-media from experimental to stable?

**Comment by dvoytenko** [comment]
@mrsufgi We can take it out of experimental when you are ready and validator has been updated. 

/cc @Gregable could you please confirm that these validator changes have been rolled out? https://github.com/ampproject/amphtml/blob/master/extensions/amp-apester-media/0.1/validator-amp-apester-media.protoascii

**Comment by adelinamart** [comment]
Is this finalized?

**Comment by adelinamart** [comment]
@Gregable any updates here? Thanks

**Comment by adelinamart** [comment]
@mrsufgi @dvoytenko can we take this out of experiment?

**Comment by dvoytenko** [comment]
Yes. This issue can be closed I believe.

**Comment by mrsufgi** [comment]
Thanks everyone for helping us with this effort ! Much obliged :) happy holidays

**Comment by dvoytenko** [comment]
@mrsufgi Thanks a lot for the contribution!
