### ISSUE TITLE
Only some images rendering on sites served from AMP cache - no issues with AMP origin

### ISSUE THREAD

**Issue by jamesozzie** [ampproject/amphtml#32427]
[One user in the WordPress support forums](https://wordpress.org/support/topic/images-not-showing-on-amp-page/#post-14002451) is encountering AMP Cache issues, with some images not appearing in AMP cache, yet they all appear in AMP origin.  

Looking at the image markup in their non AMP URLs I don't see [any differences](https://www.diffchecker.com/N8oahVqn) that could impact this behaviour. The problematic images in AMP cache are 404 errors. The user is using Cloudflare.

If you have a bug for AMP please fill in the following template. Delete everything except the headers (including this text).

Additional context:
- [AMP Cache URL](https://www-gistfocus-com.cdn.ampproject.org/c/s/www.gistfocus.com/hairstyles-for-nigerian-ladies/?amp) with issue evident
- [AMP Origin URL](https://www.gistfocus.com/hairstyles-for-nigerian-ladies/?amp) - no issue
- [Search query](https://www.google.com/search?q=site%3Awww.gistfocus.com+nigerian+hairstyles&oq=site%3Awww.gistfocus.com+nigerian+hairstyles&aqs=chrome.0.69i59j69i58.459j0j9&sourceid=chrome&ie=UTF-8) to locate site from organic search: site:www.gistfocus.com nigerian hairstyles
- This is not realted to a WordPress plugin
- User does have Cloudflare active for this site
- Valid AMP URL, and this occurs on other URLs on the same site
- [Video demonstrating the issue](https://we.tl/t-NAlamWFLMn)
- [Non AMP image markup](https://www.diffchecker.com/7a14OlvG) (left code snippet not appearing in AMP cache, no issues with right code snippet)
- [Users full Site Health information](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit?urlBuilderDomain=get10up.com&gxids=7628#response=ACYDBNixlAlxKJ-I9uJLQ30cCrrAR3niv5apuIrB73mmVj_ry2rYEjwpvSnco13PDLTnTbI)
- Images all jpegs, all valid dimensions
- Doesn't occur with featured images
- All absolute URLs

**Comment by honeybadgerdontcare** [comment]
@jamesozzie Thank you for the report. We're looking into it.

**Comment by honeybadgerdontcare** [comment]
It appears that these images may not be being served correctly. Reproduce by:

1. Open a new and unused icognito window
2. Go to URL: https://www.gistfocus.com/wp-content/uploads/2020/11/beautiful-hairstyles-marley-twist-559x600.jpg
3. Note that this returns a 404
4. Go to URL: https://www.gistfocus.com/hairstyles-for-nigerian-ladies/?amp
5. Note that this returns the image
6. Go to URL: https://www.gistfocus.com/wp-content/uploads/2020/11/beautiful-hairstyles-marley-twist-559x600.jpg
7. Note this returns the image

It returns in 6/7 because it's in the cache from 4.

My guess is there is some setting that is preventing the image from being served without having a certain referral.

Internally we checked that we also receive a 404 for that image when trying to crawl it.

Please let the domain owner they should look at their settings to ensure search engines can crawl their images.

**Comment by jamesozzie** [comment]
@honeybadgerdontcare Thanks for checking, I'll follow up with the user.
