### ISSUE TITLE
[amp-base-carousel]swipe on touch devices doesn't respect advance-count attribute

### ISSUE THREAD

**Issue by Notebit** [ampproject/amphtml#32486]
You can check the issue in this playground example 
[example on amp playground](https://playground.amp.dev/?format=websites#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5hbXAtaW5saW5lLWdhbGxlcnkgLSBFeGFtcGxlIDE8L3RpdGxlPgogIDxzY3JpcHQgYXN5bmMgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC5qcyI+PC9zY3JpcHQ+CiAgPHNjcmlwdCBjdXN0b20tZWxlbWVudD0iYW1wLWlubGluZS1nYWxsZXJ5IiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1pbmxpbmUtZ2FsbGVyeS0wLjEuanMiIGFzeW5jPjwvc2NyaXB0PgogIDxzY3JpcHQgY3VzdG9tLWVsZW1lbnQ9ImFtcC1iYXNlLWNhcm91c2VsIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1iYXNlLWNhcm91c2VsLTAuMS5qcyIgYXN5bmM+PC9zY3JpcHQ+CiAgPHNjcmlwdCBjdXN0b20tZWxlbWVudD0iYW1wLWxpZ2h0Ym94LWdhbGxlcnkiIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAvYW1wLWxpZ2h0Ym94LWdhbGxlcnktMC4xLmpzIiBhc3luYz48L3NjcmlwdD4KICA8bGluayByZWw9ImNhbm9uaWNhbCIgaHJlZj0iaHR0cHM6Ly9wcmV2aWV3LmFtcC5kZXYvZG9jdW1lbnRhdGlvbi9jb21wb25lbnRzL2FtcC1pbmxpbmUtZ2FsbGVyeS5leGFtcGxlLjEuaHRtbCI+CiAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCI+CiAgPHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1vei1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbXMtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7YW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGh9QC13ZWJraXQta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbW96LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1zLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW8ta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUBrZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19PC9zdHlsZT48bm9zY3JpcHQ+PHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOm5vbmU7LW1vei1hbmltYXRpb246bm9uZTstbXMtYW5pbWF0aW9uOm5vbmU7YW5pbWF0aW9uOm5vbmV9PC9zdHlsZT48L25vc2NyaXB0Pgo8L2hlYWQ+Cjxib2R5PgoKPGFtcC1pbmxpbmUtZ2FsbGVyeSBsYXlvdXQ9ImNvbnRhaW5lciI+CiAgPGFtcC1iYXNlLWNhcm91c2VsCiAgICBjbGFzcz0iZ2FsbGVyeSIKICAgIGxheW91dD0icmVzcG9uc2l2ZSIKICAgIHdpZHRoPSIzLjYiCiAgICBoZWlnaHQ9IjIiCiAgICBzbmFwLWFsaWduPSJzdGFydCIKICAgIGxvb3A9InRydWUiCiAgICB2aXNpYmxlLWNvdW50PSIyIgogICAgICAgICAgICAgICAgICAgICBhZHZhbmNlLWNvdW50PSIyIgogICAgbGlnaHRib3gKICA+CiAgICA8YW1wLWltZwogICAgICBzcmM9Ii9zdGF0aWMvaW5saW5lLWV4YW1wbGVzL2ltYWdlcy9pbWFnZTEuanBnIgogICAgICBsYXlvdXQ9InJlc3BvbnNpdmUiCiAgICAgIHdpZHRoPSI0NTAiCiAgICAgIGhlaWdodD0iMzAwIgogICAgPjwvYW1wLWltZz4KICAgICA8YW1wLWltZwogICAgICBzcmM9Ii9zdGF0aWMvaW5saW5lLWV4YW1wbGVzL2ltYWdlcy9pbWFnZTEuanBnIgogICAgICBsYXlvdXQ9InJlc3BvbnNpdmUiCiAgICAgIHdpZHRoPSI0NTAiCiAgICAgIGhlaWdodD0iMzAwIgogICAgPjwvYW1wLWltZz4KICAgIDxhbXAtaW1nCiAgICAgIHNyYz0iL3N0YXRpYy9pbmxpbmUtZXhhbXBsZXMvaW1hZ2VzL2ltYWdlMi5qcGciCiAgICAgIGxheW91dD0icmVzcG9uc2l2ZSIKICAgICAgd2lkdGg9IjQ1MCIKICAgICAgaGVpZ2h0PSIzMDAiCiAgICA+PC9hbXAtaW1nPgogICAgCiAgICA8YW1wLWltZwogICAgICBzcmM9Ii9zdGF0aWMvaW5saW5lLWV4YW1wbGVzL2ltYWdlcy9pbWFnZTIuanBnIgogICAgICBsYXlvdXQ9InJlc3BvbnNpdmUiCiAgICAgIHdpZHRoPSI0NTAiCiAgICAgIGhlaWdodD0iMzAwIgogICAgPjwvYW1wLWltZz4KICAgIDxhbXAtaW1nCiAgICAgIHNyYz0iL3N0YXRpYy9pbmxpbmUtZXhhbXBsZXMvaW1hZ2VzL2ltYWdlMy5qcGciCiAgICAgIGxheW91dD0icmVzcG9uc2l2ZSIKICAgICAgd2lkdGg9IjQ1MCIKICAgICAgaGVpZ2h0PSIzMDAiCiAgICA+PC9hbXAtaW1nPgogICAgPGFtcC1pbWcKICAgICAgc3JjPSIvc3RhdGljL2lubGluZS1leGFtcGxlcy9pbWFnZXMvaW1hZ2UzLmpwZyIKICAgICAgbGF5b3V0PSJyZXNwb25zaXZlIgogICAgICB3aWR0aD0iNDUwIgogICAgICBoZWlnaHQ9IjMwMCIKICAgID48L2FtcC1pbWc+CiAgPC9hbXAtYmFzZS1jYXJvdXNlbD4KICA8YW1wLWlubGluZS1nYWxsZXJ5LXBhZ2luYXRpb24gbGF5b3V0PSJub2Rpc3BsYXkiIGluc2V0PgogIDwvYW1wLWlubGluZS1nYWxsZXJ5LXBhZ2luYXRpb24+CjwvYW1wLWlubGluZS1nYWxsZXJ5Pgo8L2JvZHk+CjwvaHRtbD4=)

Description of the issue.
amp-base-carousel supports an advance-count attribute (in the example I set it to "2") but if you scroll the carousel using swipes instead of buttons, like you would do on touch devices, then it ignores the advance-count directive and advances slides 1 by 1. You can open the example link with a touch enabled device like a smartphone, or from desktop you can enable Responsive Mode from Inspect element for having the touch gestures support

What I would expect.
I would expect the amp-base-carousel to move between slides using the advance-count amount in any situation, if the user uses next and previous buttons, but also if the user uses the swipe for going previous and next

**Comment by caroqliu** [comment]
Hi @Notebit, thanks for filing this issue! 

The `advance-count` attribute configures exactly what you described: it determines the number of slides that advance when using the previous and next buttons. 

When scrolling freeform, the number of slides you transition by is a function of the momentum on your scroll and the snapping configuration on the carousel. By default, we allow the carousel to snap ([`snap="true"`](https://amp.dev/documentation/components/amp-base-carousel/?format=websites#snap))—meaning it is not possible to stop partially through a slide if at least 1 is visible—and snap on every 1 slide ([`snap-by="1"`](https://amp.dev/documentation/components/amp-base-carousel/?format=websites#snap-by)). If you want the scrolling gestures to correspond to the arrow advances, I'd suggest setting `advance-count` and `snap-by` to the same amount.

Note that one function of snapping is to align the carousel with the "closest" slide, so if the user doesn't scroll by >50% of the `snap-by` amount, the carousel will snap to the prior edge rather than the next edge of the current set.

This should resolve the issue you're describing to create the experience you want. Perhaps one consideration can be to default `snap-by` to the same as `advance-count` rather than a value of `1`, but seeing as what you're describing is available in the current feature set, I'm going to close this issue as WAI for now.

**Comment by Notebit** [comment]
Hi @caroqliu 
sorry my fault, I didn't notice the snap-by attribute. I added it, it also supports media queries as advance-count, so now anything looks fine and i have the swipe by touch and next/previous moving with the same pace.
thanks again
