### ISSUE TITLE
Amp-ad extension missing or incorrect (Top Warnings)

### ISSUE THREAD

**Issue by mrcferri** [ampproject/amphtml#32688]
I've just received the following message:

_Search Console has identified that your site is affected by 1 AMP issues:
Top Warnings
.....
The tag 'amp-ad extension .js script' is missing or incorrect, but required by 'amp-ad'. This will soon be an error.
We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search._

No URLs of example pages having this issue were provided, as it usually happens. Totally new it's the "Top Warnings" line, something I never saw before.

Despite an in-depth check, I didn't find any page with the above mentioned problem: when there was am amp-ad tag, there was also the corresponding extension script.

In the past I had that same issue, but it was promptly solved and pages were successfully validated. Then I got this message, even though the pages weren't modified since then...

Another strange thing I've just noticed in Search Console, it's that the number of AMP pages detected  is now very low compared to about a week ago.

Any idea? Thanks,

Marco

**Comment by alanorozco** [comment]
cc @ampproject/wg-caching 

@mrcferri Would you mind sharing an affected URL?

**Comment by Gregable** [comment]
The author mentioned that they couldn't find any specific URL, just a site-level warning.

I don't know that amp project can help much without an URL to debug. You probably want to reach out to Search Console support for more details first. 

I will say that this has been a warning for years now and we will likely not make it into an error without significant outreach due to the large number of documents that it would break. So, while it would be good to fix if you can find it, it shouldn't have any affect on AMP page's validity or treatment in search any time soon.
