### ISSUE TITLE
Menu in mobile phone

### ISSUE THREAD

**Issue by dlugoreality** [ampproject/amphtml#32777]
## What's the issue?
The menu on the mobile phone does not work. 
The menu icon on the mobile is displayed, but it cannot be clicked and the menu does not open.

## How do we reproduce the issue?
https://www.listinskylubos.sk/

## What browsers are affected?
chrome in mobile phone

All browsers? Some specific browser? What device type?

## Which AMP version is affected?
Verzia 2.0.10 | Od AMP Project Contributors, I recently installed an amp for the first time. I see the problem now.
![Screenshot_20210221-201704](https://user-images.githubusercontent.com/79246602/108635845-e9f9d680-7481-11eb-8c90-1e251d1e0e1a.png)

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)

**Comment by caroqliu** [comment]
Hi @dlugoreality, thanks for filing this issue! I see this is the markup for the toggle button: 
```html
<button id="primary-toggle-button" data-toggle-target=".main-menu-modal" 
  data-toggle-body-class="showing-main-menu-modal" 
  aria-expanded="false" data-set-focus=".close-main-nav-toggle">
  <span></span>
  <span></span>
  <span></span>
</button>
```

It looks like the button is trying to do three things:
1. Toggle the visibility of the `.main-menu-modal` element
2. Toggle the `showing-main-menu-modal` class on the `body` element
3. Focus on the `.close-main-nav-toggle` element, which appears to be inside the `.main-menu-modal` element.

To accomplish all of the above in AMP, you want to use the AMP actions and events system via the [`on` attribute](https://amp.dev/documentation/guides-and-tutorials/learn/amp-actions-and-events/) instead of the `data-toggle-target`, `data-toggle-body-class`, and `data-set-focus` attributes.

Note in particular that you target elements by their `id`, not any selector, so the `.main-menu-modal`, `body`, and `.close-main-nav-toggle` elements will all have to have `id` attributes as well. For the following example, let's assume they have `id="main-menu-modal"`, `id="landing-page"`, and `id="close-main-nav-toggle"`, respectively. To achieve what you had specified using the `on` attribute, it should look something like this:

```html
<button id="primary-toggle-button" 
  on="tap:main-menu-modal.toggleVisibility,landing-page.toggleClass(class='showing-main-menu-modal'),close-main-nav-toggle.focus">
  <span></span>
  <span></span>
  <span></span>
</button>
```

Please note that if the button is truly toggling the elements, as in you can click it to both open and close your main menu modal, then it may not make sense to `focus` on the `close-main-nav-toggle` everytime. Alternatively, if this button only opens the modal and does not close it, I would recommend using `show` and `toggleClass(class, force="true")`:
```html
<button id="primary-toggle-button" 
  on="tap:main-menu-modal.show,landing-page.toggleClass(class='showing-main-menu-modal',force=true),close-main-nav-toggle.focus">
```

One last unrelated note on your toggle button - I see it has `aria-expanded="false"`. Since the button is not actually collapsible or expandable, I recommend placing this attribute on your modal instead of on your button.

I'm going to close this issue for now as it is not a problem within AMP itself.
