### ISSUE TITLE
[amp-story-player] Creating a player dynamically builds container twice, pushing down story

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#32826]
Sample https://codesandbox.io/s/react-amp-story-player-forked-ygjdv?file=/src/App.js:138-157

Creating a player dynamically (using `load()`) on a player that is already connected to the DOM is building two shadow root containers and pushing down the displayed story:
![image](https://user-images.githubusercontent.com/5449100/108880509-5c78cc80-75d0-11eb-8f6e-c08d310a5ab6.png)

The problem is that the window variable `AmpStoryPlayer` calling `load()` and the player script `amp-story-player-v0.js` are both building the player and appending a shadow root.

Since they are using two different `AmpStoryPlayer` instances with the same `<amp-story-player>` element, the `this.isBuilt_` won't prevent them from building a container on the element.

Normally if the player is connected to the DOM, the script is responsible for building the player. But when it's not, `AmpStoryPlayer.load()` should be used. The interesting part about this React sample is that both are able build it.

One solution that comes to mind is to move the `isBuilt` check to the element level (not instance), so that a single `<amp-story-player>` element can't get built twice.

@ampproject/wg-stories

**Comment by gmajoulet** [comment]
For the record, what Enrique and I discussed offline:

1. An error should be thrown when trying to instantiate a player on a DOM element that already has one
2. Calling `new AmpStoryPlayer(...)` should return the player DOM element instead of the class instance, so we have consistency between doing `querySelector('amp-story-player')` on a Player that was in the initial HTML, and calling `new AmpStoryPlayer(...)`
3. Revise our documentation examples to show that

There's no breaking change to these updates.
