### ISSUE TITLE
Add possibility to disable navigation in amp-story-player

### ISSUE THREAD

**Issue by nterol** [ampproject/amphtml#33320]
## Describe the new feature or change to an existing feature you'd like to see

Currently, swiping left or right will make the player navigate to the next story. 
But if one adds a carousel in an `amp-story-page-attachment, for instance, swiping in the carousel will actually make the player swipe to the next story, which make the interface unusable.
Temporarily disabling the player's navigation would greatly improve the experience.

## Describe alternatives you've considered

At the moment I'm just trying to override the style applied to the story `iframe`

## Additional context

https://user-images.githubusercontent.com/24438131/111496646-c6ecda80-8740-11eb-9eb7-8cbb87240d9c.mov

**Comment by Enriqe** [comment]
Thanks for the feature request!

/cc @ampproject/wg-stories 

I think we could introduce a programmatic API that toggles between story navigation (e.g. `player.enable/disableNavigation()`) and/or a JSON configuration similar to `pageScroll` but for navigation. But currently dynamically updating the player JSON configuration is not supported, so we would need to add support for that first.

**Comment by mszylkowski** [comment]
@Enriqe this seems to be an expected behavior in most story platforms, so we could implement this without any special configuration, or have a flag that enables this instead of having to subscribe to events and execute custom logic from the website. The default behavior of the player could be "if there's a page attachment open, disable navigation", which would solve this FR and make the player more predictable and inline with all other story experiences.

**Comment by Enriqe** [comment]
Yep, you're right. I'm unsure if <<page attachment is open>> is the right heuristic though, we might still want to enable navigation when it's open, just not when there's horizontal scrolling.

Similar to how regular HTML <div>s work: The inner element should horizontally scroll until it reaches the end, then the parent element should be able to receive the scroll events after that.

**Comment by newmuis** [comment]
> we could implement this without any special configuration

Agreed, that we shouldn't add a new publisher-facing API for this.  We should have one consistent way of handling it.

> Yep, you're right. I'm unsure if "page attachment is open" is the right heuristic though, we might still want to enable navigation when it's open, just not when there's horizontal scrolling.

Also agreed, this is a very good UX question.  Since it's a UX question, cc @hongcatlover and @processprocess to help us here.

We have two options:

(a) People should be able to swipe to the next story while in a page attachment.  If there's horizontally-scrollable content like a carousel, swiping to the next story should only happen when they overscroll on the horizontally-scrollable section.
(b) People should not be able to swipe to the next story while in a page attachment.  In this case, they'd have to close the page attachment first, then swipe to the next story.

Thoughts/opinions?

**Comment by nterol** [comment]
It seems that listening to `touchstart` and `touchmove` events from the page attachment and stopping the propagation in the callbacks prevents the player from swipping to the next story when swipping in the page attachment while still being possible from the rest of the story.
So my own problem is solved, but I do agree with @Enriqe when you say: 
>  I'm unsure if "page attachment is open" is the right heuristic though, we might still want to enable navigation when it's open, just not when there's horizontal scrolling.

It could still be useful to block the player navigation, and not only if page attachment is open.
