### ISSUE TITLE
1 `background-audio` file to continue to play story-to-story

### ISSUE THREAD

**Issue by scottmathson** [ampproject/amphtml#33337]
Continuing to play `background-audio` story-to-story would be amazing!

Ex: story/page 1 introduces the audio and has `auto-advance-after="15s"` set. Then page 2 continues playing this same `background-audio` file from the 15s mark. 

And/or if the user advances to the next slide prior to auto advance set, then the audio file continues to play from that timestamp, on through the duration of `amp-story-page` or until declared to somehow stop (or audio ends), otherwise.

Alternatively, if this isn't going to happen, I'll like go down some version of dynamic audio file splitting route. Any file splitting resources (JS/API-based preferred) and recommendations are welcome! :-)

Thanks for considering this! /cc @pbakaus 

---

Semi-related/adjacent issues:
- https://github.com/ampproject/amphtml/pull/30023
- https://github.com/ampproject/amphtml/issues/29623

**Comment by pbakaus** [comment]
Just wanted to add my voice here - I wanted this for a long time, and I think this could really make Web Stories feel significantly more immersive. /cc @raovs @newmuis

**Comment by newmuis** [comment]
Within the same story, you can continuously play one audio file throughout the entire story using the [`background-audio` attribute on the `<amp-story>` tag](https://amp.dev/documentation/components/amp-story/#background-audio-(optional)).

This doesn't work for two cases, and I'm not sure from reading this which one(s), if any, you care about:

1. Playing audio across multiple pages of a single story, but not the entire story
2. Playing audio across multiple stories

For (1), I haven't forgotten your gapless audio request @pbakaus 😉   I think there might be a technical path forward, but it's potentially quite difficult/risky due to all the other media playback black magic we do.  I still think it's worth experimenting with and proving out the concept, but thus far we've just been building towards it gradually.

For (2), I think this is pretty unlikely in the current architecture, given that they're completely different HTML documents.  If they're played in the same player, I would recommend listening for navigation signals with the `amp-story-player` and having the host document play the audio.

**Comment by pbakaus** [comment]
Ah got it, I must have forgotten about the `background-audio` attribute! That's helpful, and maybe what Scott has been looking for (if so, feel free to close this issue).

But yes, gapless playback of audio across multiple pages would still be amazing :)

**Comment by scottmathson** [comment]
You know what? Doing so at the `<amp-story>` level versus per-`<amp-story-page>` may very well be a good workaround here, thanks! Going to explore more.

Speaking to the first scenario (1) you outlined above, though (_and apologies if initial request was confusing_) **gapless playback between pages is the ideal scenario** that I'm after, here! Thanks for chiming in, how feasible do you see implementing that as being?
