### ISSUE TITLE
amp-story-player completely broken ‼❗

### ISSUE THREAD

**Issue by brianpetro** [ampproject/amphtml#33546]
## What's the issue?

amp-story-player is failing to render everywhere I have checked.

## How do we reproduce the issue?

Check the examples in the documentation here: https://amp.dev/documentation/guides-and-tutorials/integrate/embed-stories/

Page is downloaded and seems to render but the placeholder never disappears.

## What browsers are affected?

Tested Chrome and Firefox on Windows. Tested Chrome and Webkit on Pixel. 

## Which AMP version is affected?

Seems to be a new issue as of today, was working last night.

**Comment by brianpetro** [comment]
@swissspidy this seems serious, are you able to confirm this bug?

**Comment by newmuis** [comment]
Also looks to be the case to me.  Investigating.

**Comment by newmuis** [comment]
Looks to be working in `2103122145004`, but not `2103240330000`.  Will try to see if we can roll back the release to fix.

**Comment by newmuis** [comment]
So, I'm definitely able to find several player instances that work, but also several player instances that don't work.  We're trying to understand what the pattern is so that we can understand the scope.

**Comment by newmuis** [comment]
Looks like stories embedded in non-AMP pages are working, but stories embedded in AMP pages are not (which makes sense, as the loader that the original report mentions is rendered only for AMP elements).

**Comment by newmuis** [comment]
We are rolling back to the `2103122145004` release to mitigate this issue, but will still need to cherrypick fixes so that this doesn't perpetually block the AMP release.

@ampproject/wg-components do you understand why the loader might be shown for the `amp-story-player` element in `2103240330000` but not `2103122145004`?

@ampproject/wg-stories is it intended that the `amp-story-player` use the loader at all?  The non-AMP version is not using the loader (as it does not exist), so is it expected that the player can function with a good user experience without the use of AMP's loader?
