### ISSUE TITLE
analytics: play event config throws an error if the selected element is not on the page

### ISSUE THREAD

**Issue by lluerich** [ampproject/amphtml#33556]
## What's the issue?

If using a selector to track the analytics event ```audio-play``` fired by the ```amp-audio``` component, the console will throw an error, if the selected element is not present on the current page.

## How do we reproduce the issue?

Basically add a valid ```amp-analytics``` configuration (as seen [here](https://amp.dev/documentation/components/amp-audio/?format=websites#analytics) which must contain a valid CSS selector. If the element is not in the DOM of the current page an error is printed to the console.

![Bildschirmfoto 2021-03-31 um 12 55 55](https://user-images.githubusercontent.com/15678151/113133879-771e1100-9220-11eb-8374-9678925c261d.png)

Example:
https://codepen.io/lurchi/pen/eYggONa?editors=1001

1. open the link
2. check the console

## What browsers are affected?

All browsers

## Which AMP version is affected?

2103122145004

**Comment by alanorozco** [comment]
Hi @lluerich 

I initially tagged this as `P1`, but after looking deeper I'm not sure that this is an issue at all.

This error is meant to be displayed to the author of the page. We use the `user()` convention to log messages that are meant to denote misuse.

https://github.com/ampproject/amphtml/blob/e928bfd376e18c0660baf396f1edb1093dc7b572/extensions/amp-analytics/0.1/analytics-root.js#L211-L214

This is meant to alert the author so that they **exclude** unnecessary rules from their analytics config. If an element is not present, its rule shouldn't be either.

I would like to understand more about why you require including rules for inexistent elements.

(@micajuine-ho may have more input on the matter.)

**Comment by micajuine-ho** [comment]
@alanorozco is correct. The `#audio1` selector will listen for events to be fired on an element with an id of `audio1` (which is currently not the case in the example provided).

**Comment by lluerich** [comment]
This may be my bad then, since I found the experienced behaviour misleading. I expected the ```amp-analytics``` component to not try to track an element, that is not on the current page. Basically I was expecting the same behaviour that is shown with ```click```-events for example.

**Comment by alanorozco** [comment]
>  I expected the amp-analytics component to not try to track an element, that is not on the current page. 

Surely, but an unused rule still affects performance in payload size and execution by scanning the missed selectors.

>  Basically I was expecting the same behaviour that is shown with click-events for example.

Could you please show an example of a click rule for an unused selector? We may need to consolidate the behavior if this is the case.

**Comment by lluerich** [comment]
Valid point. Thanks for clarifying. 👍🏻 

While the behaviour does not occur on events such as ```visible```- or ```carousel-change```-, it occurs on ```click```-events. You can find an updated example [here](https://codepen.io/lurchi/pen/YzNLWWe).

**Comment by micajuine-ho** [comment]
@lluerich This occurs because `click` trigger requires a `selector`. The other triggers you mentioned do not need a selector (i.e. `visible` will work fire on page load not just an element if no selector is defined, and `carousel-change` will fire whenever any carousel on the page is changed). Thus it only makes sense that the `click` trigger guards against selectors that are not found.

**Comment by lluerich** [comment]
@micajuine-ho Thanks for pointing that out to me.
I believe this can be closed then as the 'bug' that I found was not really a bug but intentional design.
