### ISSUE TITLE
[amp-script] console errors are not being surfaced

### ISSUE THREAD

**Issue by dmanek** [ampproject/amphtml#33566]
## What's the issue?

When using amp-script without the `nodom` attribute, no console errors are surfaced.

## How do we reproduce the issue?
 
See https://iris-deeply-berry.glitch.me/ - amp-script is missing the `nodom` attribute, however there are no console errors.

## What browsers are affected?

All

**Comment by andrei0x309** [comment]
I don't know if this helps you, but I don't think it's a bug, an invisible `amp-script` without the `nodom` will not execute at all, that why no console message is logged.

 I visited the link you provided and saw no worker dom thread created.

If you put the `amp-list` inside the `amp-script` your example works: [https://suave-fallacious-pufferfish.glitch.me/](https://suave-fallacious-pufferfish.glitch.me/).

You can trigger execution if you give `amp-script` a fixed layout of 1x1px, you can even make it take no space using CSS absolute and will still work.

But you have to be careful with these kinds of invisible scripts because for example if you have a page where you can scroll a lot and you scroll down and reload sometimes when the page jumps to the last point(remembered point) and the script won't enter the view and will not execute.

I think the script is designed to only start executing when it enters the view, so a script can execute later as you scroll down, but I don't recommend using these small 1x1 fixed invisible scripts, as from what I've tested they don't execute reliably and most time execute but sometimes skip execution especially if you reload-jump scroll and if you scroll up they start to execute as an `amp-script` with layout container will do reliably do.

**Comment by samouri** [comment]
@dmanek: how could the `<amp-script>` component know that the element _should_ have nodom?
There should at least be a warning that the script is not undergoing initialization. I believe the current warning mistakenly checked for zero height and width instead of zero height or width.

Fix in https://github.com/ampproject/amphtml/pull/37747

**Comment by samouri** [comment]
Closing as the warning was added in https://github.com/ampproject/amphtml/pull/37747. @dmanek please reopen if you believe there are further action items.
