### ISSUE TITLE
Intent-to-Implement: oewa web analytics

### ISSUE THREAD

**Issue by oewaoffice** [ampproject/amphtml#3379]
We're trying to add support for ÖWA analytics. 

The following variables must be defined:
in "vars"-section:
•	s: offer
•	cp: categorypath
in "requests"-section:
•	url: HTTPS location of amp-analytics-oewa.html

Call should look like this:

```
<amp-analytics type="oewa">
<script type="application/json">
{
  "vars": {
    "s": "offer",
    "cp": "contentpath"
  },
  "requests": {
    "url": "https://subdomain.domain.example/amp-analytics-oewa.html"
  }
}
</script>
</amp-analytics>
```

A copy of amp-analytics-oewa.html via HTTPS is required on a subdomain (because we require our script to be run in an unmodified version):

```
<html>
  <head>
    <script src=https://dispatcher.oewabox.at/oewa.js></script>
  </head>
  <body>
    <script>
      var match,
          pl     = /\+/g,
          search = /([^&=]+)=?([^&]*)/g,
          decode = function (s) { return decodeURIComponent(s.replace(pl, " ")); },
          query  = window.location.search.substring(1);
      var OEWA = {};
      while (match = search.exec(query)) { OEWA[decode(match[1])] = decode(match[2]); }
      oewa.ns = true;
      oewa.c({}, OEWA, 2);
    </script>
  </body>
</html>
```

**Comment by andreban** [comment]
@dvoytenko

**Comment by cramforce** [comment]
HI @oewaoffice, your implementation includes a usage of the `iframePing` mechanism which we highly discourage and only allow when it comes together with an implementation plan and timeframe when it would be removed.

From a quick glance it should be pretty simple to implement https://dispatcher.oewabox.at/oewa.js in terms of the standard `amp-analytics` capabilities. It appears you are using localStorage. This would not work reliably in AMP, because your iframe would be a third party iframe. The CLIENT_ID mechanism in AMP probably is a great substitute.

Please go down that route. Thanks!
