### ISSUE TITLE
Google Tag Manager examples

### ISSUE THREAD

**Issue by slivorezka** [ampproject/amphtml#3380]
Hi to all!
I don't found how to use GTM directly via `amp-analytics`.

Maybe make sense add this description to [Use Case](https://www.ampproject.org/docs/guides/analytics/use_cases.html) documentation like amp-analytics - googleanalytics?

Thanks!

**Comment by avimehta** [comment]
Hi @slivorezka GTM does not support AMP yet. I know that the team is looking into it. Look for announcements from them for amp support.

**Comment by wjouet** [comment]
Hi all,

The <amp-gtm> tag is a must-have feature for us, since we use Google Tag Manager for all our tracking tags on a dozen sites. Using a specific <amp-analytics> tag would make us work twice when adding a new tag to one of our sites.

Google team told us at the AMP conference that <amp-gtm> tag was already in the roadmap, and that we could use <amp-iframe> tag instead until <amp-gtm> is released, but unfortunately iframes are really buggy and don't fire correctly ..

So, when do you plan to release <amp-gtm> tag? :)

Thanks!

**Comment by Wadekone** [comment]
Hi Guys, 
Found this article dated October 24, 2016: 
https://analytics.googleblog.com/2016/10/google-tag-manager-giving-mobile.html

That should be it right?

**Comment by wjouet** [comment]
Hi @Wadekone,

Indeed that's a great news, we saw that a few weeks ago!
The only drawback with this solution is that we can't use the same tag for multiple GTM containers, which forces us to duplicate all our tags in GTM ... but I'm even not sure this feature will be possible one day!
