### ISSUE TITLE
[Page attachments] [Inline] Add closable affordance for screen readers

### ISSUE THREAD

**Issue by raxsha** [ampproject/amphtml#33820]
Added a close badge when we have shorter attachment for better A11y. See mock:

<img width="227" alt="Screen Shot 2021-04-13 at 9 31 32 PM" src="https://user-images.githubusercontent.com/10503669/114641197-a2344600-9c9f-11eb-85dd-b86fad5adf46.png">

@ampproject/wg-stories

**Comment by processprocess** [comment]
This branches our UX and introduces new UI.
We could favor a pattern of selection rather than dismissal and have the entire area be focusable to return to the story.

There are a couple benefits to this:
1. Keeps UI/UX consistent.
2. Solves the same problem that exists when open to 80%.

<img width="311" alt="Screen Shot 2021-04-14 at 9 56 48 AM" src="https://user-images.githubusercontent.com/3860311/114722714-07bc1d00-9d08-11eb-9a19-5e6f89a8bea4.png">

I commented on the Figma file and will follow up with @hongcatlover

**Comment by processprocess** [comment]
@hongcatlover approved closing via highlighting the story in the background. 
let's go that route for this.
