### ISSUE TITLE
Amp-lightbox-gallery - Thumbnails showing the wrong image when clicked.

### ISSUE THREAD

**Issue by SimonHogstromRonbol** [ampproject/amphtml#34556]
### Description

I've come across a bug when making an amp-image-gallery with thumbnails, connected to the action on the thumbnail itself. The 2rd time the gallery is opened, the image that shows up in the lightbox, is the one prior to the image the thumbnail depicts.

Note: this issue only comes up when using thumbnails, and everything works fine if you just use full-size images with the lightbox attribute instead of thumbnails.

@sebastianbenz on slack advised that I filed this as a bug,

### Reproduction Steps

https://codepen.io/sunturion/pen/eYvRxKY

- Click a thumbnail image to open the lightbox.
- Close the gallery.
- Click a different thumbnail.
- The image should now be the one prior to the one clicked, order wise.

### Browser(s) Affected

Chrome, Firefox, Edge

**Comment by nickFalcone** [comment]
I made an [example](https://github.com/nickFalcone/amphtml/blob/bc9ce8ab9f61d8e2f4ad2457c2e50bcfbec4a890/examples/lightbox-gallery-linked.amp.html) on my fork and can reproduce the issue.  Setting a breakpoint on [enter_()](https://github.com/ampproject/amphtml/blob/65a6e3a3c0fd6837858a5600f0ee62a22ba4ee68/extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js#L1030) reveals the expected `sourceElement` but the prior image gets displayed.

I get the following error when opening any image:

```
log.js:255 [Resource] Error: layoutComplete race
```
This error was mentioned in [#30426](https://github.com/ampproject/amphtml/pull/30426). 

Resizing the viewport before clicking an image produces the expected behavior.
