### ISSUE TITLE
Add option to keep the linker for exact domain matches

### ISSUE THREAD

**Issue by claudiucelfilip** [ampproject/amphtml#34666]
### Description

The [Don't append linker for exact domain match PR](https://github.com/ampproject/amphtml/pull/32100) can affect tracking in situations where more platforms use the same domain. The request is to provide a way to opt-out of this behaviour.

Ex:  In the case of WordPress.com, the linker is used to transition from the AMP Landing Pages to Calypso; which are 2 platforms with the same domain. After the linker removal for exact domain match, this transition is broken.

### Alternatives Considered

Having a `noInternalLinking` would allow us to opt-out of the changes from the [PR](https://github.com/ampproject/amphtml/pull/32100) and go back to the previous behaviour.

### Additional Context

The `noInternalLinking` solution has been brought up in other discussions as well:
https://github.com/ampproject/amphtml/pull/32100#issuecomment-772901579
https://github.com/ampproject/amphtml/issues/30176#issuecomment-765730810

**Comment by micajuine-ho** [comment]
Hi @claudiucelfilip , thank you for your issue report. 

Since we went with #32100 as default behavior, would it be acceptable to have this be an opt-in feature: `allowInternalLinking`?

**Comment by ekatysheva** [comment]
Hello @micajuine-ho , we have the same issue on our website, we use next.js and have a lot of AMP pages on the same domain meanwhile using google analytics and amplitude for tracking. Previously we used internal linking to pass params everywhere and keep session unbroken between non-AMP and AMP pages, but currently I cannot find how to do it.
`allowInternalLinking` would help I believe 🙏

**Comment by claudiucelfilip** [comment]
> Hi @claudiucelfilip , thank you for your issue report.
> 
> Since we went with #32100 as default behavior, would it be acceptable to have this be an opt-in feature: `allowInternalLinking`?

Sounds good to me.

**Comment by micajuine-ho** [comment]
Hi @claudiucelfilip @ekatysheva, I'd like to understand a little more about what you need the linker for? Are you trying to get the CLIENT_ID when a user navigates from an AMP page to a non-AMP page (on the same domain)? 

/cc @kristoferbaxter

**Comment by ekatysheva** [comment]
I think so. I don't deeply undestand what is going on when linking is working (though I've tried to read docs many times), but e.g. this portion of configuration
```
 "linkers": {
   "enabled": true,
   "proxyOnly": false,
   "destinationDomains": ["*.ourdomain.com"] // we have several subdomains for staging/prod
 },
```
helped me to link sessions between AMP and non-AMP pages with google analytics. It was done quite some time ago and I found out just today that this behaviour is broken when tried to do so with amplitude.

**Comment by micajuine-ho** [comment]
I'm sorry that the change occurred so abruptly (we were not aware of these use cases, additionally, we decided that linkers should only be different domain, since you should have access to both pages and be able to access the information via AMP or non-AMP).

Were there any parts in particular with the documentation that you found confusing? If so we can look to improve it.

> helped me to link sessions between AMP and non-AMP pages with google analytics

My thought here is that GA Is using CLIENT_ID as an identifier per user per domain. This CID is stored in cookies on that domain, so I believe it should be accessible on the non-AMP page either via server side changes or client side. 

Server side would be the best option here since it should be conducive of a better UX. Does this approach sound do able?

**Comment by claudiucelfilip** [comment]
>  Are you trying to get the CLIENT_ID when a user navigates from an AMP page to a non-AMP page (on the same domain)?
That's correct, the problem is that the AMP pages (ie. WordPress) are on one platform and the non-AMP pages (ex. signup) are on another (ie. Calypso). 
Both platforms, however, are on the same domain and the CLIENT_ID is processed on the 2nd platform. Therefore, If a user lands on the non-cached version of the AMP Landing Page, and transitions to signup, then there's no CLIENT_ID passed.

**Comment by micajuine-ho** [comment]
So landing page is AMP and then signup page is Calypso? 

> Therefore, If a user lands on the non-cached version of the AMP Landing Page, and transitions to signup, then there's no CLIENT_ID passed.

CLIENT_ID can still be generated on the non-cached AMP page, and stored in cookies, which should be accessible on your Calypso signup page. Is that not the case?

**Comment by claudiucelfilip** [comment]
> CLIENT_ID can still be generated on the non-cached AMP page, and stored in cookies, which should be accessible on your Calypso signup page. Is that not the case?

That is the case, and this was something we looked into initially. Since Calypso signup is not the only affected platform/flow, we felt this approach would cause extra overhead, and went with another direction. 
However, being able to go back, to the previous behaviour would save us from this work-around and it'd ensure us we haven't missed anything.

**Comment by micajuine-ho** [comment]
Hi @claudiucelfilip, looking at our documentation, I don't think we explicitly wanted to support same domain linking, (even though it was allowed). 

However, I understand that this can be a headache, so why don't we bring discussion to design review to get feedback from the broader AMP team. 

My general concerns are around maintaining this feature long-term, when it was not supposed to be used this way, along with supporting and new quicklinks feature. 

I will sign up for design review. Please feel free to join so that we can get some more context around this problem.

**Comment by micajuine-ho** [comment]
@claudiucelfilip Took this question to Design review yesterday. The team agreed that we can support this. I will work on making the changes with a new opt in API.

**Comment by claudiucelfilip** [comment]
> @claudiucelfilip Took this question to Design review yesterday. The team agreed that we can support this. I will work on making the changes with a new opt in API.

That's excellent news. Thank you!

**Comment by hugojay** [comment]
@micajuine-ho Hi, we use linkers for our e-commerce site tracking conversions from ad to transactions. This change break our conversion report recently since our amp page no longer pass params through linkers to non-amp shopping cart page. We look forward to https://github.com/ampproject/amphtml/pull/34821 that should bring our tracking code back by `sameDomainEnab`. 🙏 

btw, you shall also update [readme document for linker-id-forwarding](https://github.com/ampproject/amphtml/blob/aee80a6e9d15304000391a0787ef30c8c771430c/extensions/amp-analytics/linker-id-forwarding.md#format). Thank you!
