### ISSUE TITLE
docs: make update mechanism clearer for amp-live-list

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#3468]

**Comment by kul3r4** [comment]
Hi,
I think we could make it clearer that, if you don't specify data-update-time and there are no insertions in the document, the amp-live-list will not show any changes. I added in the bold my suggestions.

In the section "Update behaviour and user experience"
....
If a replace or tombstone operation is found but no insert (no new items) is found on a poll request, the replace and the tombstone operation will occur without the need for a reader's action **if data-update-time is specified.**

...

In the section "Attributes on items":

data-update-time (Optional)

Timestamp when the entry was last updated. **Use this attribute for showing updates on existing items**. We recommend using Unix time (the number of seconds that have elapsed since Thursday, 1 January 1970).
