### ISSUE TITLE
amp-carousel when we are using this with selector after clicking on next slide the next image was not showing facing issue still

### ISSUE THREAD

**Issue by naveen-iiit** [ampproject/amphtml#34700]
### Description

The problem occurring in all browsers we have specifically checked for chrome.

we are using amp-carousel along with amp-selector for showing an indicator below the slider but unfortunately we are not able to go to next slider after 2.
Carousel:
<amp-carousel id="carouselWithPreview" type="slides" layout="responsive" width="350" height="197" autoplay on="slideChange:
              carouselWithPreviewSelector.toggle(index=event.index, value=true),
          carouselPreview.goToSlide(index=event.index)">
              
<amp-selector id="carouselWithPreviewSelector" on="select:carouselWithPreview.goToSlide(index=event.targetOption)" layout="container">

Issue:
[Action] Target "carouselPreview" not found for action [slideChange:
              carouselWithPreviewSelector.toggle(index=event.index, value=true),
          carouselPreview.goToSlide(index=event.index)].

### Reproduction Steps

Just click on next slide you will get

### Relevant Logs

```shell
[Action] Target "carouselPreview" not found for action [slideChange:
              carouselWithPreviewSelector.toggle(index=event.index, value=true),
          carouselPreview.goToSlide(index=event.index)].
```

### Browser(s) Affected

Chrome

**Comment by caroqliu** [comment]
Thanks for filing @naveen-iiit! Do you have sample markup I can look at to reproduce/investigate?

**Comment by naveen-iiit** [comment]
Yes caroqliu 

You can check the same at  [](https://amp.indiaherald.com/)

with mobile view

**Comment by naveen-iiit** [comment]
https://amp.indiaherald.com/

**Comment by caroqliu** [comment]
It looks like the error is due to the fact that there is no element with the id `carouselPreview` on the page. Do you perhaps mean to use `carouselWithPreview`? If so, that should be unnecessary to do given it is in response to the carousel `slideChange` event (meaning, i.e. if the carousel transitions to slide `2` and fires the event, this action would then `goToSlide` of index `2` in response, which would be noop since that is already the current slide state). You should be able to remove the `carouselPreview.goToSlide(index=event.index)` line and the error will go away.

**Comment by naveen-iiit** [comment]
The issue was not resolved even after removing that.

the error showing in console was gone but the actual issue was still there.

check the video for more clarity

forward was not working but backward is.

https://user-images.githubusercontent.com/48469343/121477749-dc8f3a80-c9e5-11eb-9a77-65e2e61774ba.mp4

**Comment by caroqliu** [comment]
Yes, I see what you mean from the video. I'm not able to reproduce on mobile view on Chrome on the given page myself, but it looks like the slides are updating to the incorrect index after a slide change completes. Can you see if updating to version `0.2` of `amp-carousel` will make a difference?

**Comment by naveen-iiit** [comment]
Hi caroqliu

Thanks for your response as you have said I have updated the latest version to 0.2 it's working fine but another issue was raised.

As you see in the video once  I have moved to next slide by drag auto play was stopped.

can you check that once.

https://user-images.githubusercontent.com/48469343/121644662-ea5dc200-cab0-11eb-844f-1a5c0ad6fe73.mp4

**Comment by caroqliu** [comment]
> As you see in the video once I have moved to next slide by drag auto play was stopped.

This is working as intended because after a user engages with the carousel, they could be engaging with the content. Therefore if autoplay resumes, it would potentially disrupt the interaction. 

From the [component documentation](https://amp.dev/documentation/components/amp-carousel-v0.2/?format=websites#autoplay-(optional)):
> Regularly advances to the next slide without user interaction. If the user manually changes slides, then autoplay is stopped.
