### ISSUE TITLE
`amp-yotpo` with `data-widget-type="ReviewsTab"` displays nothing

### ISSUE THREAD

**Issue by praditha-hidayat** [ampproject/amphtml#34859]
### Expected Result
On the AMP page, I should see the Review tabs and SEO page like what I see on the HTML version.
Here is the working version on the HTML version: https://www.backpackerdeals.com/reviews

### Current Behavior
I don't see any generated content on our AMP page to display the Review tabs and SEO page like what we have in HTML version.

Here is how I do the implementation based on the following article:
https://support.yotpo.com/en/article/accelerated-mobile-pages-amp-widgets
```
<!doctype html>
<html ⚡ lang="en">
<head>
<meta charset="utf-8">
    <title>amp-yotpo</title>
    <script async src="https://cdn.ampproject.org/v0.js"></script>

    <!-- ## Setup -->
    <!-- Import the amp-yotpo component -->
    <script async custom-element="amp-yotpo" src="https://cdn.ampproject.org/v0/amp-yotpo-0.1.js"></script>
    
    <link rel="canonical" href="https://amp.dev/documentation/examples">
    <meta name="viewport" content="width=device-width">
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  </head>
  <body>

	<!-- ## Basic usage -->
    	<amp-yotpo
	    width="550"
	    height="100"
	    data-app-key="3L1oF2nFye8y4SexpVc02tJACGjk6wnetqONiyM3"
	    data-widget-type="ReviewsTab">
	</amp-yotpo>
  </body>
</html>
```

### Reproduction Steps

- Set the AMP HTML page
- Load the amp project javascript
- Load the amp-yotpo component
- Load the amp-yopo widget for Review based on this documentation: https://support.yotpo.com/en/article/accelerated-mobile-pages-amp-widgets#reviews-tab-seo-page
- Load it on browser, and I see nothing

### Browser(s) Affected

Chrome, Firefox

### AMP Version Affected

2106030132000

**Comment by caroqliu** [comment]
Hi @praditha-hidayat, thanks for filing this issue! I am able to reproduce on Chrome that the component displays nothing after loading. I'm going to mark this P1 instead of P0 because this issue does not appear to be a regression—I'm able to reproduce on current LTS as well as multiple prior LTS RTVs. 

I'll continue investigating and update here with updates. It's worth noting that the amp.dev example uses a `data-app-key` value which yields a 404 from the requested vendor script, which is unrelated from the "display nothing" issue.

**Comment by caroqliu** [comment]
It looks like only `data-widget-type="ReviewsTab"` is affected, and nothing is rendered due to this line: 
https://github.com/ampproject/amphtml/blob/1f2308befa3015c84f0c8839357884dff36880d2/3p/yotpo.js#L28

We should be able to expect a "Reviews tab" to be rendered, but given that the above line has been with the component since its inception, I'm not sure we have ever been able to expect this feature to work.

**Comment by praditha-hidayat** [comment]
Hi @caroqliu 

Thanks for the fixes. Is there anything I should change for now?
Or I must wait for the next release?

Thanks

**Comment by caroqliu** [comment]
> Hi @caroqliu
> 
> Thanks for the fixes. Is there anything I should change for now?
> Or I must wait for the next release?
> 
> Thanks

It will be available in the next release.
