### ISSUE TITLE
[amp-story-page-attachment]: Link text placed at extreme left or right does not behave as clickable inside of page

### ISSUE THREAD

**Issue by kamblenavnath** [ampproject/amphtml#34949]
I tried adding a link on page in page attachment. But found that when that specific link is right/ left aligned (approx within gap of 30px from right or left), it remains idle even though if you click on it. It does not redirect to given URL site. It works only when it's somewhere at center.

Here is an amp story, I am sharing. Please check and let us know how can we resolve? Or if it is a bug, then let us know.
- Story link with issue: [Amp_Story_Sample_1](https://vs-subdomain-appsites.azurewebsites.net/myampstories.visualstories.com/test-page-attachment-with-an-link-text-inside)
- Story link applied padding to right and left to make it work: [Amp_Story_Sample_2](https://myampstories.visualstories.com/test-page-attachment-with-an-link-text-inside)

**Comment by sebastianbenz** [comment]
//cc @ampproject/wg-stories

**Comment by processprocess** [comment]
Thanks for filing this @kamblenavnath and tagging us @sebastianbenz 

This appears to be a regression in the page attachment due to the work in #31320.

Suggested fix, Don't run [this method](https://github.com/ampproject/amphtml/pull/31320/files#diff-2978d455c7ebcad28c69459ca8ad11d05a6ce6af1f68c55b5d23a3bd970ee96eR576) when the attachment is open.

Screenshot:
<img width="436" alt="Screen Shot 2021-06-22 at 10 51 23 AM" src="https://user-images.githubusercontent.com/3860311/122947077-e0a54b80-d347-11eb-9117-32edd7054175.png">

**Comment by processprocess** [comment]
Another idea would be to check if the clicked element is inside a page-attachment.

**Comment by kamblenavnath** [comment]
@processprocess Hey any updates? Is it yet to resolve?

**Comment by processprocess** [comment]
Thanks for following up @kamblenavnath I'm pinging my team for review on #34958 :)
