### ISSUE TITLE
I wonder if we should add a second CSS query as a fallback, e.g. `[template=fill] img, amp-story-grid-layer img`

### ISSUE THREAD

**Issue by wayneglicc** [ampproject/amphtml#35126]
I wonder if we should add a second CSS query as a fallback, e.g. `[template=fill] img, amp-story-grid-layer img`
If there's a template=fill it's obv a better pick, but if it's not found whatever img we can find might be good?
Some stories don't have a `template=fill`, like https://wp.stories.google/stories/web-stories-sharing-on-social-media/

_Originally posted by @gmajoulet in https://github.com/ampproject/amphtml/pull/34974#discussion_r657466486_

**Comment by processprocess** [comment]
Hi @wayneglicc, thanks for reading the PR and commenting on this!

It currently does what you describe by [selecting all images within a grid layer and finding the largest](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story/1.0/background-blur.js#L125-L128).

We are looking into including videos in the selector. #35131 is filed to track that.

I'm going to close this since it's working as you describe but please feel free to follow up with any questions!
