### ISSUE TITLE
Migrating from Closure for compilation/type-checking --> esbuild/babel/terser for compilation and tsc for type-checking

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#35264]
# Closure --> esbuild/babel/terser/tsc

This I2I is to spark the discussion on whether we'd like to migrate off of Closure for production builds, as well as move off of its type system. While technically both the compilation and type checking aspects of this I2I could be pursued separately, I don't believe it would make sense to do that. For example, using TS types while compiling with Closure means that as time goes on Closure will slowly become less and less efficient as it understands less of our typing.

POCs for the migration
- https://github.com/ampproject/amphtml/pull/35201
- https://github.com/ampproject/amphtml/pull/35243

Related I2I on using TS in AMP: https://github.com/ampproject/amphtml/issues/13791

### Motivation

DevEx:
- We can significantly reduce build times for prod builds. For example, in my current PR prod builds goes from 12m --> 7.5m (with further low hanging fruit).
- We can take advantage of the _much_ more powerful (and pleasant to use) TS type system in new code.
- We could seamlessly start writing Bento components with TS markup.

Community alignment:
- Most OSS projects do not use Closure -- and instead choose alternatives. Using its API is not easy, and we've written thousands of LOC to make it work.

Cons:
- Bundle size: Currently, even with prop mangling turned on, the `terser` output is still ~2kb larger for `v0.mjs`. Hopefully we can further close the gap, but a bigger bundle size is directly at odds with our project policy of prioritizing end user over developer.
- Project stability: We are confident in Closure's stability and staying power (Google is heavily invested in it). We can't be sure of this with a new project like `esbuild` maintained by an individual.

### Alternative Solutions

Do nothing.

### Notifications

/cc @ampproject/wg-approvers @ampproject/wg-performance @ampproject/wg-infra

**Comment by rsimha** [comment]
Thanks for kicking off this discussion. Would love to see this brought to design review. Here are some preliminary questions:

**On type-checking:**
- Are there any classes of type errors that can be caught with closure (see [here](https://github.com/google/closure-compiler/wiki/Warnings#warnings-categories)) but not with TS?
- And conversely, are there any that can be caught with TS but not with closure?
- Based on these two, is the existing level of parity acceptable for AMP?

**On production builds:**
- Good point about Closure's stability. How does this weigh against the maintenance burden of [`amp-closure-compiler`](https://github.com/ampproject/amp-closure-compiler)?
- If in future, `esbuild` were to become unusable by AMP for some reason, are there alternatives outside of closure?

**Comment by alanorozco** [comment]
Regarding byte-size, one of the problems with the minified esbuild output is that static methods are not treated as standalone functions like Closure would. As a result, "getter classes" like `Services` are included as a whole:

```js
Wi = class {
  static accessServiceForDoc(t) {
    return ji(t, "access", "amp-access");
  }
  static accessServiceForDocOrNull(t) {
    return zi(t, "access", "amp-access");
  }
  static subscriptionsServiceForDoc(t) {
    return ji(t, "subscriptions", "amp-subscriptions");
  }
  // ...
}
```

Conversely, Closure would inline the used methods as function and thus DCE the rest of the class, like in this caller example (`"platform"`, `"performance"`):

```js
ud(self.document, function () {
  let a = Kl.getAmpDoc(self.document);
  K(self, "platform", Fi);
  K(self, "performance", Fl);
  let b = M(self, "performance");
  self.document.documentElement.hasAttribute("i-amphtml-no-boilerplate") &&
    b.addEnabledExperiment("no-boilerplate");
  b.addEnabledExperiment("esm");
  xe();
  b.tick("is");
  Jl(a, b);
});
```

There's an easy win to be made for `Services` specifically. We introduced this class in order to allow stubbing of the service getter themselves (#10128) like so:

```js
// impl
import Services from '(...)services';
Services.accessServiceForDoc(...);
```
```js
// test
import Services from '(...)services';
env.sandbox.stub(Services, 'accessServiceForDoc')
```

However, we can now stub module members directly. This would allow us to turn getters like `accessServiceForDoc` into standalone functions, which esbuild would then be able to inline and DCE piece-meal, thus reducing the size of the output. 

```js
// impl
import {accessServiceForDoc} from '(...)services';
accessServiceForDoc(...);
```
```js
// test
import * as Services from '(...)services';
env.sandbox.stub(Services, 'accessServiceForDoc')
```

**Comment by rcebulko** [comment]
> **On type-checking:**
> 
> * Are there any classes of type errors that can be caught with closure (see [here](https://github.com/google/closure-compiler/wiki/Warnings#warnings-categories)) but not with TS?

IIUC we rely on Closure for many of those warnings. Some (checking variables, missing returns, undefined vars) would be caught by TS; others (assigning to a const, violating `@private` or similar access restrictions, useless code, misplaced JSDoc annotations like combining `@extends` and `@implements`) probably would not be, though I haven't verified which exactly. The linter might fill some gaps, but certainly not all.

CC also warns about conformance violations, like using `String.prototype.includes` which isn't fully supported (well, until we deprecate IE). We do a lot of this ourselves with our `forbidden-terms` checks, but it's still valuable. There's a couple little validations like that.

> * And conversely, are there any that can be caught with TS but not with closure?

Likely many; TypeScript type-checking is much more strict than CC w.r.t. type-checking. Conversely, this means type-annotating existing JS will require additional work, as TS will require more detailed type annotations and definitions than we currently have.

> * Based on these two, is the existing level of parity acceptable for AMP?

I suspect the tradeoff would at minimum be neutral, as the benefits of strict TS checking would offset the minor checks CC adds. Some could be replaced with our own implementations, others we might use existing tooling out there (ex. does `esbuild` have a conformance violations check?)

> **On production builds:**
> 
> * If in future, `esbuild` were to become unusable by AMP for some reason, are there alternatives outside of closure?

I too am curious about this. I would imagine TS is/will remain pretty widely supported generally, but don't know much about the high-performance compiler/minifier ecosystem.

If we decide to do this migration, we'll want to transition in the reverse order that we initially enabled type-checking. That is, `core` should be last (alternately, if we first migrate things in `core`, everything that depends on them will will break CC type-checking and won't yet pass TS checking).

One significant blocker/unwieldy effect is that CC has comment annotation support for type assertions, which TS does not. For example, when you call `devAssertString(foobar)` in a function, CC knows that past that point, `foobar` is of type string because `devAssertString` is annotated with `@closurePrimitive {asserts.matchesReturn}`.

TS does not support this comment, but supports an alternate syntax along the lines of `function devAssertString(value: *) asserts value is string : string` (don't quote me on that syntax). Using this means our code is no longer truly JS, and is instead TS. It's possible that other tooling expecting ES6 code will break (I'm thinking linters, possibly some babel things, etc). The alternative is for every call-site to add an explicit type-cast comment `/** @type {string} */` after asserting the type, which is unwieldy, would require a lot of code to be updated, and generally feels code-smelly.

More generally, I think this transition will lead to us constantly hitting the question of "how much TS do we put in AMP?" as we try to leverage more features, interfaces, enums etc. that work cleanly in full TS but don't play as nicely in code pretending to be JS but compiled with `tsc`.

Apologies for the disorganized nature of this post, I'm a bit tired but have many disorganized thoughts and experiences with both CC and TS type-checking. TL;DR - TS is probably better in the long-run, but would require a not-insignificant investment to transition and may lead to actual TS taking over the repo.

**Comment by rileyajones** [comment]
From a DevEx perspective, this seems like a big win. The integration between TS and VSCode is very good and should allow developers to more easily catch and understand errors before even needing to compile.

**Comment by samouri** [comment]
Thank you all for the discussion. I'll try to address some of the points, and then also add a few ideas to the mix.

> Are there any classes of type errors that can be caught with closure (see here) but not with TS?

@rcebulko is correct re. Conformance Checks. I believe those are the only meaningful ones we would lose access to.

> And conversely, are there any that can be caught with TS but not with closure?

The type checking capabilities in terms of both errors it can discover and in terms of data modeling are far superior. Also its ability to discover errors without needing many passes is a huge DevEx win. For example, running CC right now on `src` will find 1000 errors. Once those 1000 are fixed, another 200 will be discovered, and so on. 

> Based on these two, is the existing level of parity acceptable for AMP?

I strongly believe **yes**. We can try to mitigate the loss of conformance with `eslint`.

---

> If in future, esbuild were to become unusable by AMP for some reason, are there alternatives outside of closure?

There is one similarly fast tool `swr`, and then some less-fast alternatives like `rollup`, `webpack`, and `swr`. Since basically all of our custom AMP logic lives within `babel` plugins, migrating between these tools should be relatively straightforward.

---

> One significant blocker/unwieldy effect is that CC has comment annotation support for type assertions, which TS does not.

TS does support [type predicates](https://github.com/Microsoft/TypeScript/issues/17212#issue-243123298) within JS Docs these days. It also supports [assertion functions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions) within jsdoc via [`@ returns {asserts param is type}`](https://github.com/microsoft/TypeScript/issues/45280#issuecomment-891120872).

> If we decide to do this migration, we'll want to transition in the reverse order that we initially enabled type-checking. That is, core should be last (alternately, if we first migrate things in core, everything that depends on them will will break CC type-checking and won't yet pass TS checking).

I actually believe the opposite -- specifically that we should start with `Bento` and `Core` (Bento makes heavy use of Core). Since it already passes CC types, it is the most straightforward to get passing `tsc`, as well as makes it feasible for `Bento` to migrate. The rest of AMP is undergoing significantly slower development and is therefore a much lower priority.

> More generally, I think this transition will lead to us constantly hitting the question of "how much TS do we put in AMP?" as we try to leverage more features, interfaces, enums etc. that work cleanly in full TS but don't play as nicely in code pretending to be JS but compiled with tsc

Importantly, we _do not_ want to compile with `tsc`, only type check. I believe we'd very likely want to use `TS` syntax, but then stay away from TS-only features (`enum`). This is an important question to bring up during design review.

---

We can pursue a more modest and incremental alternative to the above. Instead of Migrating completely to `tsc`/`esbuild` overnight, we could begin by switching building of only select bundles. One viable path I see:

- `v0.js` and all `0.1` components continue to be built and minified with `Closure`
- We begin using `tsc` for all of our type checking (Closure is currently only typechecking `Core`).
- We use `esbuild`/`terser` for bundling Bento (1.0) components

**Comment by samouri** [comment]
We've [optimized](https://github.com/ampproject/amphtml/issues/36453#issuecomment-982728510) the esbuild binaries to be within 2% of the output size of our closure builds. Requesting formal approval from folks in @ampproject/wg-approvers

**Comment by kristoferbaxter** [comment]
Approved.

**Comment by jridgewell** [comment]
Approved

**Comment by rsimha** [comment]
Enthusiastically approved.

**Comment by samouri** [comment]
Stable is now built with esbuild/babel/terser and we are actively removing Closure Compiler from the codebase. @rcebulko and I have been gradually adding `tsc` based typechecking.

🚀
