### ISSUE TITLE
Error: An AMP component 'amp-lightbox-gallery' is using an invalid version. Use a valid version of this AMP component.

### ISSUE THREAD

**Issue by merakmarey** [ampproject/amphtml#35505]
### Description

Google AMP Website validator reports error in page:
An AMP component 'amp-lightbox-gallery' is using an invalid version. Use a valid version of this AMP component.

### Reproduction Steps

https://lr.trapichero.com/c/monrovia/montserrado/buy-or-sell/shoes-and-clothes

**Comment by honeybadgerdontcare** [comment]
@merakmarey

I could not get the [URL](https://github.com/ampproject/amphtml/blob/main/extensions/amp-lightbox-gallery/validator-amp-lightbox-gallery.protoascii) you provided to load. It responded:

```
Database error :   
```

The only valid versions are `0.1`, `1.0`, and `latest`.

**Comment by merakmarey** [comment]
URl is back on now.
Preface: The extension is declared but not used.
Two separated issues. Google Search Console reports the original error. Invalid version.
Google Search Online validator report the "correct" issue, declared but not used.
https://search.google.com/test/amp?utm_source=gws&utm_medium=onebox&utm_campaign=suit&id=zo8z92WYeYzuyN7gBjrIxg

**Comment by merakmarey** [comment]
Main question...why is this invalid AMP?

**Comment by honeybadgerdontcare** [comment]
One tenet of AMP is that it is fast. Including unused javascript goes against that tenet. The validator does a check to see if an included extension is used. If it is not used then an error appears as it's wasted bytes sent to the client. Some extensions are exempted from this check but only because including that check now would be cumbersome and cause previously valid AMP documents to become invalid.

As to the Google Search Console issue, it may be best to follow up on Google Search Console help forums. The validator may report different errors but it is typically transient and you should see it normalizing over time. It's very rare to have different errors.
