### ISSUE TITLE
Cannot use loop as boolean attribute for amp-base-carousel

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amphtml#35555]
### Description

For components like `amp-video` or `amp-carousel` I can use the `loop` attribute without any value, i.e. `<amp-video loop .../>`.

Relevant spec:

https://github.com/ampproject/amphtml/blob/c491d6f3e767a6749b4e2c003d926111922784b8/extensions/amp-video/validator-amp-video.protoascii#L71-L74

https://github.com/ampproject/amphtml/blob/c491d6f3e767a6749b4e2c003d926111922784b8/extensions/amp-carousel/validator-amp-carousel.protoascii#L63-L66

Unfortunately, for `amp-base-carousel` I cannot do this as it causes a validation error. I have to specifically use `loop="true"` or `loop="false"` or `loop="(min-width: 800px) true, false"` (which btw is nowhere documented)

Spec:

https://github.com/ampproject/amphtml/blob/c491d6f3e767a6749b4e2c003d926111922784b8/extensions/amp-base-carousel/validator-amp-base-carousel.protoascii#L70-L74

### Reproduction Steps

Insert `<amp-carousel layout="responsive" width="4" height="1" loop></amp-carousel>` in AMP playground, see no validation error.

Insert `<amp-base-carousel layout="responsive" width="4" height="1" loop></amp-base-carousel>` in AMP playground, get validation error.

### Relevant Logs

```shell
The attribute 'loop' in tag 'amp-base-carousel' is set to the invalid value ''.
```

### AMP Version Affected

2107240354000

**Comment by westonruter** [comment]
Adding the Bento label as this directly impacts the ability of using the React/Preact version: https://github.com/swissspidy/gutenberg-bento/issues/1.

**Comment by caroqliu** [comment]
This appears to be a validation error rather than a functional error. Note from this [jsbin](https://jsbin.com/dopejojeli/edit?html,output) that using `loop` attribute without any value is equivalent to enabling it. I'll send a PR shortly to fix our allowed value regex for the validator here. 

In terms of the `loop="(min-width: 800px) true, false"` syntax, this should be documented for both versions (classic and Bento) under ["Media queries"](https://amp.dev/documentation/components/amp-base-carousel-v1.0/?format=websites#media-queries). The information on this can be found [here.](https://github.com/ampproject/amphtml/blob/main/docs/spec/amp-html-responsive-attributes.md) Note that this is specific to the custom element layer (AMP or Bento mode) as legacy compatibility with the 0.1 AMP layer.
