### ISSUE TITLE
Test out CSS containment

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3564]
Experiment with auto-applying CSS containment rules to elements with layout types that guarantee containment semantics (such as really most `layout` values).
https://developers.google.com/web/updates/2016/06/css-containment

**Comment by zhouyx** [comment]
Tested on `amp-iframe` and `amp-img` but didn't see major improvement,  I changed style by setting `element.style.left` to different values, and calculated time taken using chrome profiles tool. I suppose it is because browser already limit scope for us. Any suggestions on a style change that browser may fail on limiting scope automatically?

>The good news is that modern browsers are getting really smart about limiting the scope of styles, layout, and paint work automatically, meaning that things are getting faster without you having to do anything.

**Comment by ericlindley-g** [comment]
@muxin @zhouyx  Slotting in Current, as it sounds like you're working on this now, but feel free to correct/update the milestone as needed
