### ISSUE TITLE
AMP.printState no longer working with #development=1 hash

### ISSUE THREAD

**Issue by jerimiahwelch** [ampproject/amphtml#35655]
### Description

AMP.printState() no longer working with #development=1 hash

### Reproduction Steps

1. Go to https://www.bedbathandbeyond.com/amp#development=1
2. type AMP.printState() in the console

Expected behavior

1. AMP state will display in the console

Actual behavior
1. Undefined is displayed in the console

<img width="642" alt="Screen Shot 2021-08-12 at 3 29 00 PM" src="https://user-images.githubusercontent.com/1224514/129278235-8753e973-f5c4-4745-90c8-92ac49610dd9.png">

### Browser(s) Affected

Chrome

### AMP Version Affected

Evergreen version. old versions are not affected

**Comment by jerimiahwelch** [comment]
An additional Example:

https://amp.luckyvitamin.com/#development=1
<img width="660" alt="Screen Shot 2021-08-12 at 3 33 59 PM" src="https://user-images.githubusercontent.com/1224514/129278447-929f4c1f-835e-4eae-83a1-d72b8f6f5b3e.png">

**Comment by kristoferbaxter** [comment]
This is likely related to these sites using the mjs build which removes this feature to keep bundle sizes smaller.

A workaround would be to use a local development environment instead.

**Comment by MadisonMiner** [comment]
@kristoferbaxter, 

The above examples are using the standard `https://cdn.ampproject.org/v0.js`, and are not SSR'd. I do not see any .mjs files being downloaded. (I do see .mjs files on SSR'd pages BTW: https://www.bedbathandbeyond.com/amp/wm-optimized/#development=1)

Here is another example:
https://providence-gcnstage.ampify.wompmobile.com/our-services/urgent-care/expresscare-interstate#development=1

`AMP.printState()` no longer works, this just started this week. We are seeing this on many sites. 

If it is somehow related to the .mjs files, is it possible to opt-out? 

Any help is greatly appreciated. Losing `printState()` presents a challenge. 

Thank you,

**Comment by kristoferbaxter** [comment]
Interesting! Can take a look to see what happened here.

Am out today, so perhaps @samouri could look?

**Comment by samouri** [comment]
I've personally never seen `AMP.printState` work correctly, even going back a few years. I'll investigate

**Comment by samouri** [comment]
According to the provided timeline, the bug must have occurred between versions `2107240354000` and `2107302322000` ([commit log](https://github.com/ampproject/amphtml/compare/2107240354000...2107302322000)).

While this bug isn't reproducible in local development, I've isolated the bug to a faulty refactor in https://github.com/ampproject/amphtml/pull/35294. Instead of only transforming `.development` in esm mode, we transform it everywhere. This logic was removed:

https://github.com/samouri/amphtml/blob/c9f0dfb1948e09073a1711358a1c07e7d562a742/build-system/babel-plugins/babel-plugin-amp-mode-transformer/index.js#L31-L34


Fix incoming in: https://github.com/ampproject/amphtml/pull/35690

**Comment by jerimiahwelch** [comment]
Thank you for the quick Fix.

We are really glad to have this back.

**Comment by samouri** [comment]
Thank you @jerimiahwelch for reporting it!

**Comment by samouri** [comment]
FYI @jerimiahwelch: you should be able to temporarily work around the issue until the fix hits stable by entering `AMP.setLogLevel(5)` in the console

**Comment by jerimiahwelch** [comment]
Thanks @samouri , that is really helpful

**Comment by joblog** [comment]
Hi, I'm having the same issue with AMP.printstate returning undefined (in both Firefox and Chrome).
I've tried AMP.setLogLevel(5) with no effect.
It was working for me a couple of months ago. My pages are valid.

I am using the official AMP plugin for WordPress. I updated it two weeks ago to version 2.1.4

I don't see any mention of the issue here
https://github.com/ampproject/amp-wp/releases
Maybe it will be fixed in 2.2
In the meantime can you advise on how I can update/fix the issue so I can observe AMP.state
Thanks

**Comment by westonruter** [comment]
@joblog If the issue is that development logging only works for JS scripts and not MJS ones, then you can fix this by turning off ESM. Here's an example plugin to do that: https://gist.github.com/westonruter/279bcb54336449ce55d8887fb0fcf5b9

There's no mention of this in the AMP plugin's release notes because the AMP plugin does not bundle any of the AMP scripts. They get loaded from the CDN.

You may want to conditionally disable ESM when [`wp_get_environment_type()`](https://developer.wordpress.org/reference/functions/wp_get_environment_type/) is `local` or `development`.

**Comment by samouri** [comment]
> Hi, I'm having the same issue with AMP.printstate returning undefined (in both Firefox and Chrome).

I don't believe `AMP.printState` ever _returned_ anything (always was undefined AFAICT). It should be printing to the console though.

**Comment by joblog** [comment]
@samouri I didn't put that clearly: I am talking about what gets printed to the console.

@westonruter  Yes! That worked. I installed and activated the plugin - which  disabled ES modules by default - and now AMP.printstate() is printing the state to the console.

I obviously missed the warning that AMP.printstate only works for JS scripts and not MJS ones.

Thanks both of you.
