### ISSUE TITLE
AMP Sidebar: Use `toggle` style helper

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#3567]
Instead of the `setStyles(element, { display: 'none' })`.

**Comment by sriramkrish85** [comment]
Toggle can't be used here - since the APIs are specifically for open and close - calling open twice should not close the sidebar.

**Comment by jridgewell** [comment]
Pass the [second parameter](https://github.com/ampproject/amphtml/blob/master/src/style.js#L135) then.

**Comment by sriramkrish85** [comment]
@jridgewell 
i don't see a big difference between toggle and setStyle/Styles , also toggle does not explicitly set display to block (probably not a big deal now). Why is it a compulsion to use this?

**Comment by jridgewell** [comment]
Just because we have a dedicated function to do it instead of having two separate ways to `display: none` (even if they are trivial).

**Comment by dvoytenko** [comment]
Partially why `toggle` exists is because we kept repeating the same error, by setting explicit `display: block`. This is indeed sometimes necessary, but most of time this is incorrect and the most appropriate step is to simply remove `display:none`, otherwise `display:block` often overwrites the original definition of `display:flex` and so on.
