### ISSUE TITLE
extraUrlParams vendor's implementation not prefixed with &

### ISSUE THREAD

**Issue by BenDz** [ampproject/amphtml#3585]
Hi,

When using extraUrlParams with AT Internet analytics, the extra params are not prefixed by a "&".
In our (AT Internet) implementation, this cause issue since the first parameter name will be include to the previous parameter.
For vendors who don't use the extraUrlParams in their requests, they are added at the end of the request, and are prefixed by the "&".

Since this extraUrlParams are optional, I guess the addition of the prior "&" should be done on the extension side, and not in the vendor part, since it would cause a "&&" in the request in case it is not used.

What is your point of view on this?

## How do we reproduce the issue?

Example with a AT Internet vs Google Analytics integration: http://jsbin.com/defaxicuho/edit?html,output

1. Use extraUrlParams with AT Internet analytics type

## What browsers are affected?

All browsers, issue in the extension/vendor part

## Which AMP version is affected?

Version 1464987951323
Following implementation in AT Internet of the extraUrlParams (#3255), thanks to #3168 

Thanks!
Benjamin

**Comment by ericlindley-g** [comment]
@avimehta  Slotting in backlog, but feel free to correct/update the milestone as needed

**Comment by dvoytenko** [comment]
Upgrading to current. @avimehta PTAL.

**Comment by avimehta** [comment]
@BenDz Thanks for the bug report. I have mixed feelings about the bug described here. 

`extraUrlParams` can be inserted at the beginning, middle or the end of the URL. If it is at the beginning of the URL, the starting character should be `?` and not `&`. In the middle and end, it should be `&`.

Making the `extraUrlParams` aware of the position where the insertion happens makes the code complicated. 

Letting vendors decide what prefix to use causes the problem you described.

To keep things simple, I opted for the design that is currently implemented. I think the best way to solve this might be to accept that `&&` can exist in certain cases in the URL. Since that is not a invalid, I think it is okay. If you agree, I can send out a PR to update AT internet's config. 

Let me know...

**Comment by rudygalfi** [comment]
I agree. I think the value of extraUrlParams should be neither `?` nor `&`. The outer configuration should determine it based on where it's used.

@avimehta There's a "lazy" way to use extraUrlParams, though, which is to define the values but not specify a place in the hit request for the params to be ended. In this case, they are just tacked onto the end and must necessarily add `&`, right? (I'm going off of this documentation: https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#extra-url-params)

**Comment by BenDz** [comment]
@avimehta Yes, our processing will work correctly with `&&`. I mainly wanted to get your point of view on it, not sure if we had to consider it as a bug.
If it is okay for you to keep this design, I would greatly appreciate if you could push it on your side.
Thanks!

**Comment by BenDz** [comment]
@avimehta Have you been able to add this extra & to our integration?
Do you want me to add it?
A few customers are waiting for this improvement, the faster we can have it, the better it will be.
Thank you

**Comment by avimehta** [comment]
Hi @BenDz, sent out #3818
