### ISSUE TITLE
Appnexus Ads are broken

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3589]
App Nexus ads in amp seems to be broken since awhile with the following error:

```
Uncaught TypeError: Cannot read property 'anq' of undefined
```

![image](https://cloud.githubusercontent.com/assets/2647/16092402/94ed35f0-32ec-11e6-8fc8-190f31a6d297.png)

@mkendall07 any idea if you can take a look and see if you can fix this? You can reproduce this by running `gulp` and navigating to `ads.amp.max.html` example.

**Comment by mkendall07** [comment]
Thanks for letting me know. I'll take a look

**Comment by mkendall07** [comment]
This is just an issue with the `ads.amp.html` page and the 2 different ways that AppNexus ads are loaded. Because the "simple" ads are loaded first, our global context doesn't have a reference to the `apntag` object. Really these 2 different ad types should never be mixed. I can fix it by switching the order of the ads loading or just remove the first 2 ad spots...
