### ISSUE TITLE
✨ Create Bento Components for Advertisement

### ISSUE THREAD

**Issue by AnuragVasanwala** [ampproject/amphtml#35989]
### Summary

Bento component for `amp-ad` is necessary for non-AMP pages. This I2I proposes to create Bento component for `amp-ad`. Moreover, dependent components `amp-a4a`, `amp-ad-custom`, `amp-ad-exit` and Fast Fetching Network Advertisement (`amp-ad-network-*-impl`) may need to be port to Bento.

### Design Document

By default, `amp-ad` does not create advertisement itself. Instead, it check for the advertisement `type` and initialise the respected advertisement component (let's say it as "child advertisement component"). Then after, everything else will be take care by the child advertisement component.

Here, based on the `amp-ad:0.1`, it can load following `type` of advertisement:
1. `AmpAdCustom`
    - Primary Dependency: `amp-a4a` -> `AmpAdNetworkBase`
2. `AmpAd3PImpl`
3. Fast Fetching Network Ad (`amp-ad-network-*-impl`)
    - Primary Dependency: `amp-a4a` -> `AmpA4A`

Based on above advertisement `type`, to create Bento `amp-ad`, we may need to port dependent components, Fast Fetching Network components, `amp-ad-custom` and `amp-ad-exit`.

Here’s, my proposed step-by-step plan to port `amp-ad:0.1` to `amp-ad:1.0` with dependencies:
1. Initially, create Bento `amp-a4a`
2. Create Bento `amp-ad`
3. Create one-by-one Bento component for all `amp-ad-network-*-impl`
4. Create Bento `amp-ad-custom`
5. Create Bento `amp-ad-exit`

I would like to know feasibility of the proposed plan.
Please provide correction/suggestion wherever required.

### Motivation

Nowadays, advertisement are very common and source of many organisation. Porting `amp-ad` to Bento helps to optimise and improve non-AMP page-experience of end-user.

### Alternative Solutions

We can do nothing and use conventional way of using `iframe` as ads for non-AMP pages but which may compromise page-experience.

### Notifications

/cc @ampproject/wg-approvers

**Comment by pradeep910** [comment]
I have some questions related this amp-ad bento component. 

**What will be the ad revenue impact?**
Since this bento `amp-ad` component is to be used in the non-amp pages, I would like to know what impact this will have on ads revenue in comparison with regular ads implementation (i.e. with GPT JS or Adsense ad codes.) for non-amp.

**What about the current amp-ad multi size restrictions or warnings?**
There are some restrictions currently as we know for which sizes to use in AMP when we use multiple sizes. (_`data-multi-size="728x90,468x60,300x50"`_). The secondary sizes must comply basically with the amp-ad specs in order to make it work fine and therefore something like this _`data-multi-size="300x50,970x250,300x250"`_ will not work properly. 

Is there any part of this we could or plan to fix programmatically in terms of size warnings returned in console? See this for reference - https://github.com/ampproject/amphtml/blob/f564b7ee3cd59972fe86c4edc3052db70852c6f0/ads/google/utils.js#L88-L135 

cc @adamsilverstein

**Comment by caroqliu** [comment]
Can @ampproject/wg-monetization advise on this high level strategy and wider implications?

**Comment by powerivq** [comment]
@newmuis FYI

**Comment by AnuragVasanwala** [comment]
I have revisited implementation for this I2I because of the complexity involved in making `amp-ad` a bento Component. Instead, I have prepared a new I2I: [✨Bento Component for Google Publisher Tag (bento-gpt) #36685](#36685)

This new I2I (#36685) proposes a new Bento Advertisement Component for Google Publisher Tag.
