### ISSUE TITLE
Richer interactions in Web Stories not exist in web story WordPress 

### ISSUE THREAD

**Issue by alzhrani099** [ampproject/amphtml#36029]
### Description

hello there 

i have read this article 

https://blog.amp.dev/2021/08/26/richer-interactions-in-web-stories/?utm_source=pocket_mylist

Richer interactions in Web Stories not exist in WordPress , is there a way to add it in WordPress plugin ?

if still new , when we will see it in WordPress plugin?

best regards

### Alternatives Considered

not sure where i should find alternative

**Comment by newmuis** [comment]
Hi @alzhrani099!

This is actually an issue with the Web Stories WordPress plugin, rather than Web Stories itself, so I've migrated your issue to https://github.com/google/web-stories-wp/issues/9003.  I will close this one, but please feel free to reopen if there are Web Stories-specific issues we can help resolve!
