### ISSUE TITLE
Iframe resize height adjustment

### ISSUE THREAD

**Issue by pdufour** [ampproject/amphtml#3663]
## Short description of your issue:

I may be missing something, but I don't understand why there is a limit around making an iframe height smaller. I have a legitimate case where I have created a responsive ad that needs to adjust height at a couple of breakpoints.

Source: https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L757

## How do we reproduce the issue?
- Create an amp-ad
- Fire an event to make the amp ad smaller than it currently is

## What browsers are affected?

All browsers
## Which AMP version is affected?

v0

**Comment by dvoytenko** [comment]
That line of code comes after several other attempts. Generally resize will be allowed unless the ad is currently directly in the viewport and cannot be resized without disrupting the viewport. If breakpoints can be described via media queries - most of elements support `sizes` and `heights` attributes as described in https://github.com/ampproject/amphtml/blob/master/spec/amp-html-layout.md

I'll close this for now, but please chime in with more questions.

**Comment by pdufour** [comment]
So would a height adjustment while the amp ad is in view be considered under this rule?
>  cannot be resized without disrupting the viewport.

**Comment by dvoytenko** [comment]
@pdufour Correct, under this rule, the resize would be not be allowed. The embed should receive back `embed-size-denied` event. There are other rules under which it could still be allowed later, such as when resize event is triggered by the user action.

I'm not sure why you need to parse CSS. I understand that in many cases, ad description in a amp document would not be able to foresee why size variations it'd need. The only thing I can recommend in these cases is to center the ad as possible and assume that the size change request could be denied. Otherwise, AMP cannot wait for a undetermined time for ad to download, initialize and decide what size it needs to then shift around the rest of the document.

**Comment by jridgewell** [comment]
> The embed should receive back embed-size-denied event.

Not when you're making it [smaller](https://github.com/ampproject/amphtml/blob/90837fe/src/service/resources-impl.js#L759-L761), that'll only happen when making it [bigger](https://github.com/ampproject/amphtml/blob/90837fe/src/service/resources-impl.js#L762-L766). I think this is a legitimate bug (not that we deny it, but that we don't notify you that we denied it).

**Comment by dvoytenko** [comment]
@sriramkrish85 Let's make sure the iframe gets notified in either case when the size is denied.

**Comment by zhouyx** [comment]
+1

**Comment by zhouyx** [comment]
Closes this issue as we make `attemptChangeSize()` a promise, iframe can know the size is denied when the promise is rejected.  And in the case of amp-ad, we always send response.
