### ISSUE TITLE
amp-form xssi-prefix support reporting as invalid

### ISSUE THREAD

**Issue by AaronMLB** [ampproject/amphtml#36843]
### Description

According to the documentation for `amp-form`, the element should support the `xssi-prefix` stripping option:

https://amp.dev/documentation/components/amp-form/?format=websites#xssi-prefix

However, the AMP validator both in the browser console and Google's crawler is reporting this as invalid: 

> The attribute 'xssi-prefix' may not appear in tag 'form'. (see https://amp.dev/documentation/components/amp-form)

> Disallowed attribute or attribute value present in HTML tag.

Is the documentation wrong or is the validator? I pray it is the latter.

### Reproduction Steps

For example, see: https://www.comedy.co.uk/guide/sketch_show/#development=1

`<form method="post" action-xhr="ENDPOINT" class="list-filter" xssi-prefix=")]}\*" data-initialize-from-url>`

**Comment by honeybadgerdontcare** [comment]
Looking at the current validator rules, `xssi-prefix` is only allowed for the [AMP Email format](https://github.com/ampproject/amphtml/blob/main/validator/validator-main.protoascii#L2411), and not other formats such as AMP or AMP Ads.

I am unsure if this is an oversight or intentional. For now the documentation is wrong. I do not see a reason not to allow `xssi-prefix` for the other formats.

@ampproject/wg-components can we support `xssi-prefix` in AMP in addition to AMP Email?

**Comment by AaronMLB** [comment]
> Looking at the current validator rules, `xssi-prefix` is only allowed for the [AMP Email format](https://github.com/ampproject/amphtml/blob/main/validator/validator-main.protoascii#L2411), and not other formats such as AMP or AMP Ads.

How odd! It's throughout the AMP for Websites documentation on many XHRy components. Thanks for clarifying.

**Comment by samouri** [comment]
No reason we shouldn't enable it everywhere
