### ISSUE TITLE
Deprecate Firefox 60-63 Support

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#36908]
### Summary

Ongoing development won't try to solve issues for these versions, particularly polyfills. These are 3 year old browsers (FF 63 was released Oct 23, 2018), and likely are not common in the wild.

### Motivation

Removing support for these will allow us to remove the Custom Elements v1 Polyfill from our ESM builds, removing roughly 2% (~1.3kb) of our brotli compressed output.

### Impact on Existing Users

Expected to be minimal. Will provide numbers when I get query access.

### Alternative Implementation

Continuing to support Firefox.

### Notifications

/cc @ampproject/wg-approvers

**Comment by samouri** [comment]
We just recently dropped support for IE11: https://github.com/ampproject/amphtml/issues/34453.

I doubt FF is the only other browser whose latest support version we should update (AFAIK these have never been updated since AMP was started).

Could we expand this issue to also include bumping the lowest versions of Safari/Chrome/UC/etc?

**Comment by kristoferbaxter** [comment]
We spoke about this offline, but usage statistics would be great to demonstrate low usage.

Additionally, following the pattern of the IE 11 deprecation... should we also include console logging to inform developers?

**Comment by jridgewell** [comment]
This range of Firefox appears to make up 0.005% of our request traffic.

**Comment by kristoferbaxter** [comment]
That's great news! Let's bring this to design review and get some additional feedback.

**Comment by erwinmombay** [comment]
Approved.
