### ISSUE TITLE
Validator fails on cdn.ampproject.org

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#3697]
The both the Chrome AMP validator plugin and the built in #development=1 validator generates errors on  AMP pages served via cdn.ampproject.org

Example:
Valid https://dailydot.relaymedia.com/amp/lifestyle/where-is-marijuana-legal/
Invalid https://cdn.ampproject.org/c/s/dailydot.relaymedia.com/amp/lifestyle/where-is-marijuana-legal/

This it is confusing to non engineering users who have installed the AMP Validator as a "show me the amp version" tool.

Possible solutions:

1. Make the validator read from the original AMP url.
2. Make the validator treat cdn.ampproject.org as a non-amp page and show the link icon rather than trying to test it.

**Comment by erwinmombay** [comment]
routing to @Gregable @powdercloud

**Comment by Gregable** [comment]
This is largely working as intended since the AMP Cache makes some non-legal transformations. In particular: the usage of versioned runtime files.

I'd like to get a better feel for how confusing this is to folks. Whitelisting special behavior for amp caches could be somewhat difficult to maintain if other third-party transforming-caches are created later.

Another possibility would be stripping the amp attribute from the `<html amp>` tag on the page in the Cache, thereby disabling the validator.

**Comment by jpettitt** [comment]
@Gregable stripping the `<html amp>` sounds like a perfect solution as at that point the page is no longer valid amp.  

In terms of confusion our some of our non-technical customers have installed the validator plugin as a way of seeing their own AMP pages and as a way of seeing who else has pages that are AMP enabled.  If they see their own content on the cdn and it's doesn't validate engineering gets a call wondering why.

**Comment by ericlindley-g** [comment]
Adding this to the backlog milestone; please feel free to update/correct

**Comment by honeybadgerdontcare** [comment]
The [AMP Validator Chrome extension](https://chrome.google.com/webstore/detail/amp-validator/nmoffdblmcmgeicmolmhobpoocbbmknc) now identifies cdn.ampproject.org as a cache and uses @jpettitt advice to show a link icon instead of trying to validate. The [extension's code](https://github.com/ampproject/amphtml/tree/master/validator/chromeextension) is also now public.

**Comment by rudygalfi** [comment]
Nice! Landed on a page today I was hoping/expecting to be valid AMP but wasn't. Then I realized the cache was serving it and it was actually fine.

The new behavior is a much better UX.

**Comment by erwinmombay** [comment]
super happy to see the extension is now open source 👍
