### ISSUE TITLE
Validator considers "#" to be a valid amp-img url

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#3705]
The validator considers this valid

`<amp-img layout=responsive height=1 width=1 src="#" ></amp-img>`

The spec says

> The value must be a URL that points to a publicly-cacheable image file. 

"#"  is not a publicly-cacheable image file.  :-)

**Comment by dvoytenko** [comment]
@Gregable wdyt?

**Comment by Gregable** [comment]
The validator can't really enforce that the URL is a publicly-cacheable image file. It could be private cache or an html file or whatever. We might consider changing the spec since this is unenforceable anyway.

Technically "#" is a valid URL, and without fetching it we don't technically have any way of knowing that it's not an image. I don't think it's necessarily worth it to special case this one. @jpettitt, have you seen cases where this causes problems to allow?

**Comment by jpettitt** [comment]
Nothing in the wild.  I just noticed it while I was messing around with the web based validator.  I was surprised it didn't squawk about the url not being [http, https, data] given how picky other pars of AMP are about sources.

**Comment by Gregable** [comment]
`<amp-img>` allows relative URLs as well. We squawk more for URLs that the amp cache can't rewrite to itself. If the cache can rewrite, we can make the URLs https.
