### ISSUE TITLE
Mismatch in amp-video autoplay attribute between docs and validator

### ISSUE THREAD

**Issue by mjangda** [ampproject/amphtml#3715]
The `amp-video` docs state that:

> The autoplay attribute allows the author to specify when - if ever - the animated image will autoplay.
> 
> The presence of the attribute alone implies that the animated image will always autoplay. The author may specify values to limit when the animations will autoplay. Allowable values are desktop, tablet, or mobile, with multiple values separated by a space. The runtime makes a best-guess approximation to the device type to apply this value.

However, the validator complains if you set `autoplay="desktop"` or any of the variations noted above. Using just `autoplay` or `autoplay="autoplay"` or `autoplay=""` do validate.

There was some discussion on this in #2381. Do the docs need to be updated for this attribute or is still considered a bug?

**Comment by mkhatib** [comment]
Currently, the docs should be updated to reflect the validator. However, this might be still worth discussion, it seems one of the reasons we invalidate these values was the fact that there were no way we can support `autoplay=mobile` due to browsers limitations. 

This is quickly changing, [WebKit 10 is introducing some support for auto playing on mobile](https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html) though not entirely sure it's gonna be through the same attribute.

cc/ @dvoytenko @cramforce

**Comment by cramforce** [comment]
Hmmm, Chrome is also switching to the same policy as WebKit 10.

I think we should fix the docs. Those values don't make any sense. It should be just `autoplay` (and support for the values to make XHTML fanatics happy :)

**Comment by mkhatib** [comment]
Sounds good. @mjangda would you be able to send a PR to update the docs?
