### ISSUE TITLE
amp-story-player: previous and next story buttons not visible in Safari

### ISSUE THREAD

**Issue by fraserb99** [ampproject/amphtml#37211]
### Description

The buttons used for skipping between stories are not visible on Safari browsers. This includes macOS and iPadOS Safari.

### Reproduction Steps

1.  Navigate to https://000615502.deployed.codepen.website with a browser that isn't Safari and open a story from the carousel. The skip buttons are correctly shown on either side of the story.
![image](https://user-images.githubusercontent.com/44883743/145997698-98e00c99-32f4-44dd-85aa-d35ba93e27f8.png)

2.  Navigate to https://000615502.deployed.codepen.website with Safari. The buttons are not visible. They are functional and can be clicked, they are just invisible
![image](https://user-images.githubusercontent.com/44883743/145998264-be225bf0-b6f9-4d53-b82c-286108bed44c.png)

### Browser(s) Affected

Safari

**Comment by processprocess** [comment]
Hi Fraser. Thank you for filing this :) 

It appears to be an issue specific to how Safari determines z space which is pretty interesting. 
In Safari, translateZ will override z-index. Check out [this thread](https://stackoverflow.com/questions/40895387/z-index-not-working-on-safari-fine-on-firefox-and-chrome) on if you're curios.

[This line](https://github.com/ampproject/amphtml/blob/main/css/amp-story-player-shadow.css#L35) appears to be the culprit.

Possible solutions:
1. Remove the 1px translateZ on the active iframe, changing it to: `transform: translate3d(0, 0, 0)`. This should be safe since the other iframe panels do not have a translateZ value. 
2. Add a 2px translateZ on the buttons (not recommended since it's a patch)

**Comment by ychsieh** [comment]
Not reproducible
