### ISSUE TITLE
AmpStories - Texts on Safari bug using preset 2021-Foreground

### ISSUE THREAD

**Issue by llccrr** [ampproject/amphtml#37244]
### Description

Using a text inside an amp-story-grid-layer with the preset : `foreground-2021 `
The text should always take the same amount of line, but in Safari it seems to break, going from 1 to 2 lines or from 3 to 4 lines when resizing the window.

<img src="https://user-images.githubusercontent.com/15107671/146780533-c1a0bede-d819-44f6-b236-0377d29c27b0.png" width=49% height=50%> <img src="https://user-images.githubusercontent.com/15107671/146780596-d2f15e5f-f090-4b73-8284-accedf6e26a1.png" width=49% height=50%>
source: https://join-dev.my.join-stories.com/texts-wcb7GWj/?t=004

### Reproduction Steps

Open `https://join-dev.my.join-stories.com/texts-wcb7GWj/?t=004` in **Safari** and resize the window, you will notice the text ratio changing (line break do change)

### Browser(s) Affected

Safari

**Comment by processprocess** [comment]
cc @mszylkowski for additional context

**Comment by mszylkowski** [comment]
We've talked about it on Slack, and it seems like this is a Safari issue where it rounds up the font sizes to integer values, whereas all the other browsers use the non-rounded values (chrome uses up to one decimal place for example). This makes the font-size larger in some cases on Safari, which introduces line breaks when the text width fits perfectly the container. https://bugs.webkit.org/show_bug.cgi?id=46987.

There's a couple of solutions that tools can use:
- Introduce `<br>` on the places where they want line breaks, either [calculated on the tool](https://stackoverflow.com/questions/3738490/finding-line-wraps) or added whenver a newline is inserted by users.
- Make text font-sizes 10x larger and use `transform: scale(0.1)` to bring it back to the original size, allowing fractional font-sizes this way.
- Make the containers larger so that wounding up the font-size doesn't introduce different line breaks (this would require manual checking, so it's not ideal)

I hope these points are useful to fix the layouts, but I don't think there would be a way for the format to fix such things directly (so I'm closing this). Feel free to reply here or on Slack with any further concerns on this topic.
