### ISSUE TITLE
Infra: increase stability of bundle size bot

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#37264]
### Description

AMP has "bundle size bot" which runs on every PR. It measures how each PR affects binary size.
It compares the binary size in the PR branch against one on `main`.

This requires that the commit on `main` has a recorded bundle size. Unfortunately when the CI fails for `main` commit, the bot will hang for every dependent PR. This often confuses AMPGineers as most don't know about this dependency or how to fix it.

This FR encompasses two tasks:
1. CI on `main` should always report bundle size as long as the build succeeds, even if other jobs like e2e fail.
2. CI on `main` should retry a few times to account for flakey tests. 

This should account for the vast majority of bundle size bot flakiness.

**screenshot**
![image (2)](https://user-images.githubusercontent.com/4656974/147139378-19cbce5a-05c9-44ee-a086-03b2e9629abc.png)

/to @ampproject/wg-infra

**Comment by danielrozenberg** [comment]
While I would love to make the bundle-size bot more stable (and therefore never hear about it again), there's no easy way to fix this without doing a complete rewrite of its architecture:

> 1. CI on `main` should always report bundle size as long as the build succeeds, even if other jobs like e2e fail.

The bundle-size job isn't dependent on other test jobs, it only depends on the prod build jobs

![image](https://user-images.githubusercontent.com/1839738/148091783-59912740-5e7a-4dd1-86b3-271b9b7ad03a.png)

> 2. CI on `main` should retry a few times to account for flakey tests.

Retrying a build automatically is not a good solution, if `amp dist` fails on CircleCI we want to know about it, not just blindly retry ;)


Ideally the bundle-size bot can be rewritten to use event queues / Pub/Sub tasks, instead of an old-school optimistic job. Can't say that I have the bandwidth to work on this though (maybe a future intern project? 😅)

**Comment by samouri** [comment]
Great! So (1) is already done then!

> Retrying a build automatically is not a good solution, if amp dist fails on CircleCI we want to know about it, not just blindly retry ;)

AFAIK we don't have any alerting set up for this. Blindly retrying _once_ will remove the vast majority of flakes in `amp dist` without impacting our ability to resolve issues.

**Comment by danielrozenberg** [comment]
We do have alerting - failures on `main` get emailed to @-ampproject/build-on-duty
