### ISSUE TITLE
AMP Validator throws message with unknown results since last release

### ISSUE THREAD

**Issue by Sebastian-Fitzner** [ampproject/amphtml#37298]
### Description

With the release https://github.com/ampproject/amphtml/releases/tag/2112231523000 we now got an error in `development=1` mode. 
On the console we can see logs regarding validator issues: 

![image](https://user-images.githubusercontent.com/5232680/148183086-af531cbe-ee63-4f07-9948-2c3ebe7510c2.png)

### Reproduction Steps

We can reproduce it on any AMP page I have found. But you can use the following URL: 
https://amp.welt.de/politik/deutschland/article152274035/Wenn-Anwaelte-Mandanten-um-ihr-Geld-prellen.html#development=1

1. Open up the provided URL
2. Make sure to add the `development=1` hash to the URL to see the logs. 
3. Open up the developer tools

### AMP Version Affected

2112231523000

**Comment by Gregable** [comment]
Thanks for the catch. This interface is infrequently used enough that we are going to submit a fix forward this time. It should be out today, tomorrow at the latest.

**Comment by hrkhal** [comment]
@Gregable Worth noting that this is also causing the Chrome extension to also error:

<img width="791" alt="Screenshot 2022-01-06 at 09 13 50" src="https://user-images.githubusercontent.com/7547332/148358930-88996fa9-d42a-474a-984f-876628321518.png">

**Comment by Gregable** [comment]
The chrome extension issue was a separate bug, but the same release. It had already been fixed by the time I replied here. If you are still seeing it you may need to restart chrome to flush your cache.

There was another release yesterday, approx 16h ago, that should also have fixed the `#development=1`. If you have restarted your browser and are still seeing either error, please reopen this issue.
