### ISSUE TITLE
[Validator] [Question] Moving to upper case tags in validator necessary?

### ISSUE THREAD

**Issue by sidkshatriya** [ampproject/amphtml#3738]
I noticed that in the validator source code base and in the protoascii file you seemed to have moved to upper case for tag names i.e. `BODY` instead of `body`, `HEAD` instead of `head` etc. Most of html written nowadays has the tags in lowercase. So, moving from lowercase as default to upper case as default has led to a lot of case conversions in the code. Long term, I feel this could be a source of lot of source code "noise" and some possibly subtle bugs (if the developer forgot to make his tag upper case). In html5 the tags are in lower case anyways.

My request would be to go back to lowercase as before simply because lowercase tags seem more "right".  However, I'm not aware of the background behind change so please forgive if there were some valid reasons for this change.

**Comment by Gregable** [comment]
The change was made because `element.nodeName` in the DOM APIs of browsers return upper case tag names. This is a performance optimization, exploring the use of DOM APIs in some contexts.

We have sufficient tests in our release process to catch any tag names not being upper case in the rules file, so as to avoid actual bugs.

Error messages are still being emitted in lower-case form, unchanged.
