### ISSUE TITLE
Bento version of `amp-lightbox` does not respond to state-bound `open` attribute changes via `amp-bind`

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#37400]
### Description

When using `amp-lightbox` v1.0 (Bento), using `amp-bind` to manage the `open` attribute has no effect. Example code:

```html
<amp-state id="state">
  <script type="application/json">
  {"open": false}
  </script>
</amp-state>

<button on="tap:AMP.setState({'state':{'open': true }})">See Quote</button>
<amp-lightbox id="quote-lb" layout="nodisplay" data-amp-bind-open="state.open">
  <blockquote>
    "Don't talk to me about JavaScript fatigue" - Horse JS
  </blockquote>
  <button type="button" on="tap:AMP.setState({'state':{'open': false }})">Nice!</button>
</amp-lightbox>
```

See live examples comparing Bento and classic components with amp-bind for `amp-lightbox`, `amp-video`, and `amp-twitter`: https://bento-amp-with-amp-bind.glitch.me/

Note that only `amp-lightbox` appears to not work with `amp-bind`.

### Reproduction Steps

See https://bento-amp-with-amp-bind.glitch.me/

### Browser(s) Affected

Chrome

### AMP Version Affected

2112231523002

**Comment by westonruter** [comment]
cc @alanorozco

**Comment by samouri** [comment]
This is an oversight in the `R1` resources system. Since components are lazily built when displayed, beginning with `nodisplay` means the implementation isn't loaded when amp-bind tries to mutate it here: 

https://github.com/ampproject/amphtml/blob/a5b5ef12e2566a70b9675d7970e710ad27f86aae/src/custom-element.js#L1793-L1804

Solution will likely be a single line of code (`scheduleAsap`), brainstorming now to ensure it is the right thing to do.

**Comment by samouri** [comment]
Potential solution: https://github.com/ampproject/amphtml/pull/37619
