### ISSUE TITLE
2201071715000 release removed latestVersion attribute from bundles.config.extensions again

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#37415]
### Description

See https://raw.githubusercontent.com/ampproject/amphtml/2201071715000/build-system/compile/bundles.config.extensions.json

For more context see https://github.com/ampproject/amphtml/issues/37356

### Reproduction Steps

n/a

**Comment by samouri** [comment]
Since the break isn't in our binaries and is instead in the structure of the file needed in the `git tag`, I fixed this by "moving" the tag to the same commit but [with the fix](https://github.com/ampproject/amphtml/commit/a360182e5ca6fdd1140a61c3013d6762c820861b).

Steps followed:
- Checked out the current tag.
- Created a backup branch (`git checkout -b 2201071715000-backup`)
- Created a new branch (`git checkout -b 2201071715000-fix`)
- Moved the tag locally (`git tag -d 2201071715000`, `git tag 2201071715000`)
- Pushed the change upstream (`git push upstream :2201071715000`, `git push upstream 2201071715000`)
