### ISSUE TITLE
[amp-story] Unmute and share events not firing anymore

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#37446]
### Description

Both the  `{ "on": "story-open", "tagName": "amp-story-share-menu"}` and `{ "on": "story-audio-unmuted" }` story analytics events don't seem to fire anymore.

I have a suspicion this might be a regression due to the change in icons for both the share and unmute functionalities.

### Reproduction Steps

Open this story (https://stories.avrotros.nl/missie-1-capture), unmute the sound or tap the share button and notice there are no analytics events being sent through the network.

### Browser(s) Affected

Chrome, Firefox, Safari, Edge, UC Browser

### OS(s) Affected

All

### Device(s) Affected

All

**Comment by newmuis** [comment]
@processprocess @coreymasanto can you confirm whether this is related to #37444?

**Comment by coreymasanto** [comment]
This probably isn't related to #37444 because that issue started several months ago

**Comment by gmajoulet** [comment]
These two events come from the system layer, that we recently refactored (cc @mszylkowski).

**Comment by gmajoulet** [comment]
I do get the `unmute` ping, but not the `share` one.

**Comment by mszylkowski** [comment]
I see that the share configuration is not being sent, but it's calling `.triggerAnalyticsEvent` on it so I'm debugging why the event is not firing. Can confirm that there's a triggered analytics event `story-open` with the tag `AMP-STORY-SHARE-MENU` that's not reaching the end and sending the request

**Comment by mszylkowski** [comment]
@cpauwels The trigger works if you set `"tagName": "amp-story-share"` instead of `"tagName": "amp-story-share-menu" due to the previous implementation triggering with that tagName. I'm getting the "unmute" event as well, to confirm what Gabriel said.

I don't think we should change the tagName to use the new one because all the people using the previous tagName would stop getting the events, and I don't think we can add aliases to the events so many tagNames can be used for the same event. I'm closing this issue since it wouldn't make sense to change it, but we should definitely document the story trigger events, which I'll do at least with the `examples/amp-story/share.html` and `examples/amp-story/analytics.html` demos.

**Comment by gmajoulet** [comment]
We documented `amp-story-share-menu` here: https://github.com/ampproject/amphtml/blob/main/extensions/amp-story/amp-story-analytics.md#story-open-trigger-on-story-open

When did we change it to `amp-story-share`?

**Comment by mszylkowski** [comment]
Oh then `amp-story-share-menu` is the value we originally were triggering? I can change it back to use that

**Comment by mszylkowski** [comment]
https://github.com/ampproject/amphtml/pull/37209/files#diff-4fb3853112effea00e77e5ac52f42e027ca37664bcd96643c1911777eceff937L29 I see before the PR we had `amp-story-share-menu` and I changed it to `amp-story-share` as an oversight. I'll revert it to `amp-story-share-menu` in here: https://github.com/ampproject/amphtml/pull/37475

**Comment by gmajoulet** [comment]
To confirm, `amp-story-share-menu` (configuration in the original post of this issue) will be fixed in the next few hours.

**Comment by mszylkowski** [comment]
The changes were cherry picked to stable, so your story should now report the share clicks correctly.
