### ISSUE TITLE
Support `amp-story-captions` for `amp-audio`

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amphtml#37462]
### Description

In our Web Stories editor we want to leverage `amp-video` to play _audio_ files, so that we can display captions for them.

To achieve that, we basically use `amp-video` like this (simplified):

```html
<amp-video layout="nodisplay" autoplay captions-id="caption-el">
  <source src="https://example.com/audio.mp3" type="audio/mpeg" />
  <track src="https://example.com/track.vtt" />
</amp-video>
```

This works great and the audio plays fine and the captions are displayed correctly.

However, we do get a validator warning that the video requires a poster image:

```
The mandatory attribute 'poster' is missing in tag 'amp-video
```

I think in such a case — the video being hidden and only playing audio — the poster requirement could be lifted

### Alternatives Considered

Two alternatives I could think of:

1. Add `amp-story-captions` support to `amp-audio` and let AMP render a `<video>` for the audio element in the background
2. Just provide the URL to some dummy poster image (accessibility concerns?)

**Comment by newmuis** [comment]
1. The real answer is to use `<amp-audio>` and `<amp-story-captions>`, as you imply.  I'm a bit surprised that `<amp-story-captions>` does not support `<amp-audio>` already; @gmajoulet do you have a sense of what more is required to support it?
2. Given that you need to use `<amp-video>`, I think it may actually still be valid to require a poster in this case.  The `<amp-video>` tag will be visible to end users (so that the captions show up), and until the audio source and/or captions have loaded, end users will be looking at a blank HTML element.  If the component is meant to introduce visuals, we need some kind of placeholder content to show until that visual is ready to be displayed.  If the creator (or a tool, on behalf of the creator) can be certain that the visual is not needed, then I think your second workaround is probably best in the interim.

**Comment by swissspidy** [comment]
Using `amp-audio` + `amp-story-captions` would of course be the ideal solution. If it's relatively straightforward to implement, I'd be happy to submit a PR.

> If the component is meant to introduce visuals, we need some kind of placeholder content to show until that visual is ready to be displayed.

It isn't meant to introduce visuals, hence `layout="nodisplay"`

**Comment by swissspidy** [comment]
OK, I gave it a try at #37500 to support captions for `amp-audio` but it doesn't currently work at all. Any help appreciated, feel free to use it as a starting point otherwise.

**Comment by swissspidy** [comment]
@gmajoulet @newmuis Friendly ping 👋 

We'd really like to see amp-audio + amp-story-captions support on the WP editor side. It feels like it shouldn't be too big of a hassle, so I'd appreciate it if someone could take a look at it. #37500 might help.

**Comment by gmajoulet** [comment]
`amp-video` has a lot more features such as using the Google video caching, that will eventually (hopefully) provide auto generated captions. If the mandatory `poster` is your only concern, the attribute is mandatory but can be left empty.

**Comment by swissspidy** [comment]
Right, that makes sense. Although not sure if the video caching also works for audio files.

I could swear that `poster=""` doesn't work but it's indeed valid AMP.

Problem solved then for us!

**Comment by gmajoulet** [comment]
We're actually not 100% sure about video caching for audio files, but have been looking into it as of next week. If it doesn't work we'll fix it very soon.
