### ISSUE TITLE
Bento: Reorganizing

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#37536]
### Summary

I believe that over the past few years of development, we've developed some alignment/messaging/naming cruft. Here are some items I believe we should update with urgency:

1. amp-base-carousel --> amp-carousel, bento-base-carousel --> bento-carousel: (https://github.com/ampproject/amphtml/issues/37380)
2. publish packages to `@ampproject/bento-XYZ` instead of `@ampproject/amp-XYZ`
3. Stop publishing the AMP Binary to NPM. It isn't realistically usable outside of the AMP Cache.
3. Direct all consumers to use NPM Caches instead of the AMP Cache for all use cases (unpkg, cdnjs, etc). Do this by updating the bentojs documentation website.
4. Decouple Bento's versioning scheme from AMP versions. Bento can follow a more traditional semver model, whereas AMP can continue with its RTVs. This means removing the file-based versioning scheme.

### Notifications

/cc @ampproject/wg-bento

**Comment by kvchari** [comment]
> 2. publish packages to @ampproject/bento-XYZ instead of @ampproject/amp-XYZ

Bento components are currently published as @bentoproject/XYZ ([example](https://www.npmjs.com/package/@bentoproject/accordion))

**Comment by samouri** [comment]
> > 2. publish packages to @ampproject/bento-XYZ instead of @ampproject/amp-XYZ
> 
> Bento components are currently published as @bentoproject/XYZ ([example](https://www.npmjs.com/package/@bentoproject/accordion))

Fantastic! That item is already done then. IMO we can probably stop publishing the [ampproject version](https://www.npmjs.com/package/@ampproject/amp-accordion) then.

**Comment by samouri** [comment]
> I don't think we do anymore, it's been 4 months since that package was last published. I believe infra has a process for deprecating old NPM packages. @estherkim would know more

Awesome. Lets deprecate and have the README point to the Bento namespace'd package instead.

**Comment by sebastianbenz** [comment]
I think that's great, are there any negative performance implications?

**Comment by estherkim** [comment]
> Awesome. Lets deprecate and have the README point to the Bento namespace'd package instead.

Done, deprecation message points to the twin  `bentoproject/XYZ` package

**Comment by kvchari** [comment]
> Direct all consumers to use NPM Caches instead of the AMP Cache for all use cases (unpkg, cdnjs, etc). Do this by updating the bentojs documentation website.

One more wrinkle here: there is currently a (minor) difference between the CDN binaries and the NPM binaries. The NPM binaries simply export a `defineElement` function whereas the CDN binaries invoke the `defineElement()` function. See the ternary [here](https://github.com/ampproject/amphtml/blob/main/build-system/tasks/extension-helpers.js#L762). This is intentional ands lets consumers drop the CDN binary in a script tag without calling `defineElement()` themselves while NPM users. A solution here that we discussed previously is creating an npm entry point at `@bentoproject/XYZ/install` that import and invokes the `defineElement()` fn. Then CDN users can point their script src to that file.

**Comment by samouri** [comment]
> while NPM users can choose when to install

What is the use case for choosing when to install? I'd assume needing that choice is the edge case

**Comment by kvchari** [comment]
We also need to start deploying the "outer css" for extensions to NPM because it's necessary for some components (like the accordion which doesn't use jss/shadow css to style itself). I was planning on doing this as part of building/publishing @bentoproject/core


> What is the use case for choosing when to install? I'd assume needing that choice is the edge case

Bundlers, used by Bento consumers, can perform DCE optimizations if they know a package doesn't have side-effects. To declare that a package has sideEffects, we would have to add `sideEffects: false` configuration to each extension's package.json which will opt-out of those optimizations. To avoid that, we can provide a clean, non-side-effecting script for consumers using bundlers and an install script for browsers/simple users. @westonruter noted [here](https://github.com/ampproject/amphtml/issues/35554#issuecomment-933742411) that both could be useful in different scenarios. Whether this is an "edge" case really depends if most consumers are using bundlers or not, which is hard to tell.

**Comment by samouri** [comment]
> To declare that a package has sideEffects, we would have to add sideEffects: false

Do you mean to declare that a package _doesn't_ have side effects? The default is to assume that all packages have side effects. Also, AFAIK this entire concept is only important for CJS and barely relevant for ESM.

**Comment by kvchari** [comment]
Following-up on this after discussion yesterday:

> 5. Decouple Bento's versioning scheme from AMP versions. Bento can follow a more traditional semver model, whereas AMP can continue with its RTVs. This means removing the file-based versioning scheme

We're going to continue using AMP's versioning scheme (using RTVs) for Bento components because using a more traditional semver model would require bumping the major (since our minor is already so high). Bumping the major of all the extensions is disruptive and places additional maintenance burden on preserving the old versions (in source code or a release branch). 

> 4. Direct all consumers to use NPM Caches instead of the AMP Cache for all use cases (unpkg, cdnjs, etc). Do this by updating the bentojs documentation website.

When we begin directing consumers to use NPM caches, we'll also have to remember to direct them to either use [importmaps](https://github.com/WICG/import-maps), to remap `@bentoproject/core` (any any other dependencies of a particular component, e.g. `mustache`) to the corresponding CDN package [^example], or use a CDN that expands bare import specifiers (e.g [unpkg](https://unpkg.com/) See `?module` documentation in Query Parameters section)


importmaps example:
```html
<head>
  <script type="importmap">
  {
      "imports": {
        "@bentoproject/core": "https://unpkg.com/@bentoproject/core@<version>/dist/bento.core.module.js"
    }
  }
  </script>
  <script type="module" src="https://unpkg.com/@bentoproject/accordion@<version>/dist/web-component.module.js"></script>
</head>
```
