### ISSUE TITLE
[amp story shopping] handle empty attachment template during swipe up on load

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#37621]
### Description

If the user swipes up on a shopping page on load, the template isn't built so nothing is displayed.
The template builds on `PAGE_ATTACHMENT_STATE` which is only triggered after the user has released swipe.

Approaches:
a) Build PLP by default. Simplest solution but more up-front cpu load.
b) Build PLP on swipe start. Less CPU on load but may require hooking into [onSwipeY_](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story-page-attachment/0.1/amp-story-draggable-drawer.js#L407) in draggable drawer. 

https://user-images.githubusercontent.com/3860311/153246060-953c76c3-0c8a-4e61-ad99-2d76253743a7.mp4

**Comment by gmajoulet** [comment]
I'd say this is working as intended! If you build it before swiping it's just more CPU usage. If you build it as you're swiping up it's going to jank.
FWIW, other Story products also only load once you release the swipe (or swipe beyond a given threshold). This is actually how the page-attachment was built in the first place, it's only rendering before you swipe because of a bug (that we should fix).

**Comment by processprocess** [comment]
Closing this since it's working as intended.
building once swiping beyond a threshold makes sense to me though so that it doesn't look empty.
