### ISSUE TITLE
[Story shopping] Load fonts from layoutCallback

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#37684]
### Description

Shopping attachment fonts currently load from `buildCallback`. If we want to respect lazy loading practice where content only loads when the page gets close to the viewport (distance <= 2), it needs to be moved to `layoutCallback`.

https://github.com/ampproject/amphtml/blob/3356584ca168894d691afe409fd7132acf119df0/extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js#L68

@ampproject/wg-stories 

### Reproduction Steps

-

**Comment by mszylkowski** [comment]
I have 1 caveat against this (but otherwise it makes sense): if the shopping attachment is on the first page, `layoutCallback` will load later than `buildCallback`, and the late fonts can cause a higher CLS. Given that probably the extension will be used on non-first pages, it makes sense to move it to the `layoutCallback`. We should check interactive components also do this if we make this change.

**Comment by gmajoulet** [comment]
Resources should always be loaded from the `layoutCallback`.

- Loading them from the `buildCallback` leads to multiple edge cases, e.g. (1) breaking story page resources lazy loading, (2) overloading the network on initial page load, (3) if enabled, breaks privacy preserving prerendering
- The difference between `buildCallback` and `layoutCallback`, if any, is in milliseconds
- If we suspect any CLS or any other metric regression, it needs to be measured so we can understand the impact of it
