### ISSUE TITLE
[amp-story] Unmute using message API freezes video on ios

### ISSUE THREAD

**Issue by edoudou** [ampproject/amphtml#37745]
### Description

When you send a unmute request via messaging API, the video freeze on iphone.

### Reproduction Steps

Here is an exemple where you can try to

- play the video
- unmute and play
- play and unmute
- play, wait 5s, and unmute. 

https://vzwjou.csb.app

https://user-images.githubusercontent.com/4236706/155178333-6fb689e8-9f60-4789-8767-645083d52f50.mp4

https://user-images.githubusercontent.com/4236706/155178356-7a125392-b9b8-4e0f-adda-e09605ecc1a8.mp4

https://user-images.githubusercontent.com/4236706/155178369-09dbee09-88e7-45ca-adf6-7575765aa684.mp4

https://user-images.githubusercontent.com/4236706/155178379-deab2fb4-e04d-438f-8ec7-f680652a79ab.mp4

/

### Browser(s) Affected

Safari

### OS(s) Affected

iOS 15

### Device(s) Affected

Iphone SE

**Comment by newmuis** [comment]
As far as I know, the desired behavior is simply disallowed on the web on iOS.  You cannot use a user gesture to enable unmuted media playback in a different frame from where the user gesture occurred.  You would need the mute controls to be within the same frame (i.e. in the story), or to have a native implementation of the player, using iOS webviews.

/cc @gmajoulet to maybe fact check me here

**Comment by gmajoulet** [comment]
+1

Here are the autoplay policies for [Chrome](https://developer.chrome.com/blog/autoplay) and [WebKit](https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/).
If you see it working on Chrome it could be either because of the [Media Engagement Index](https://developer.chrome.com/blog/autoplay/#media-engagement-index) or the [iframe delegation](https://developer.chrome.com/blog/autoplay/#media-engagement-index) (that the Player enables by default).

I'm closing this ticket as there is no bug we could fix, but feel free to continue the conversation if you have additional questions/feedback.

**Comment by edoudou** [comment]
Yes, that was one of my supposition.
Maybe there should be a security to prevent this to happen as it makes the video freeze.

**Comment by edoudou** [comment]
Do you know if there could be any tricks ? Because right now it prevent a lot of workflow.
For example, if the user unmute a video in one story of our player, I would love to unmute every stories, and vice versa.

**Comment by newmuis** [comment]
I've been searching for tricks for years, and have considered some very terrible hacks to solve this problem (for very similar reasons to what you describe).  I've not yet found a way to do this that would work without making assumptions about the structure of the content.  Funnily enough, the hacks that I've tried seem like they would work, except they are _also_ not supported in iOS, for different reasons 🙄
