### ISSUE TITLE
[amp-story][analytics] story-page-visible event trigger when visibility is set to hidden (expected ??)

### ISSUE THREAD

**Issue by edoudou** [ampproject/amphtml#37756]
### Description

Change of page on a story with visibility state set to `hidden` triggers the event `story-page-visible`.

I don't know if this is intended, but it seems illogical to send this event when so story is not in visibility state `visible` (or maybe in `paused`, but not in `hidden`)

### Reproduction Steps

Use this link https://v08ph9.csb.app/

- Click on play, (set state to visible)
- go to page 2 or 3
- stop the story (set state to hidden)
- rewind

**Comment by edoudou** [comment]
Any update on this issue please ?

**Comment by edoudou** [comment]
Any news ?

**Comment by erwinmombay** [comment]
@ychsieh could you take a look at this when you get a chance?

**Comment by ychsieh** [comment]
How do you verify you are receiving `story-page-visible` event? From the URL you provided I checked the code at JoinStoryPlayer.js in `onPageNavigation_`, you log the message "page visible page {x}" without checking any events received? 

In addition, if the AMP doc is invisible, how do you change page on a story?

**Comment by edoudou** [comment]
I check the network traffic and see the event being fired. 

You can use the player programatique functions (or communicate with the iframe if you build your own player) to ask the story to change page.

**Comment by ychsieh** [comment]
Will take another look at it once I fixed the other bugs about Get Link button in player.

**Comment by edoudou** [comment]
@erwinmombay @ychsieh any news ?

**Comment by ychsieh** [comment]
Try #39274. 

I assume your player code would rewind the story after you switches to the other tab. However, when you switch back, the event would still be fired since it becomes visible again, even though it won't fire at all as long as you don't switch back to the tab.

In order to test it correctly, I think you can switch to the other tab and wait there for some time. And you come back to the tab to check if the event timestamp matches the time you switch back instead of the time you execute rewind.
