### ISSUE TITLE
[amp-story] When not coming from cache, you should be able to prerender assets without playing the story.

### ISSUE THREAD

**Issue by edoudou** [ampproject/amphtml#37785]
### Description

Right now, the only way to display an asset is to set the visibility state to `visible`. However, this play the story. You cannot render the story if you never played it before.

As discussed with @newmuis during the working group, this is to prevent security issues. This prevent tiers services from getting information on the user.

However, this prevent certain worklflow, where a story could be visible but should not play, as it is not the focus of attention.

Developers should have a way to display assets without playing the story, either using an additional visibility, or with an additional state.

### Reproduction Steps

On this sandbox, you can try to change the story visibilityState : https://z9ce0.csb.app/

**Comment by newmuis** [comment]
Adding in a few folks in hopes that one of them has the right context: @jridgewell @samouri @alanorozco @rsimha 

This is effectively a feature request for a modality where `PRERENDER` does _not_ preserve privacy.  Is there a precedent for this?

**Comment by samouri** [comment]
> where a story could be visible but should not play, as it is not the focus of attention

A hacky workaround could be to make it visible and then quickly pause. You can't currently skip straight to paused, because then resources won't have their build & layout callbacks invoked.

> Is there a precedent for this?

Not that I know of. The [new PREVIEW](https://github.com/ampproject/amphtml/issues/37129) state feels a bit similar in purpose. For off-cache use cases I don't think we have the same privacy-preserving concerns -- so this seems like a reasonable request to me.

**Comment by gmajoulet** [comment]
> A hacky workaround could be to make it visible and then quickly pause.

+1

I believe you can do this pretty easily from the open source Story Player :))

**Comment by jridgewell** [comment]
We cannot make changes to the privacy features of `PRERENDER` state. We could make it so that `PAUSED` state allows `buildCallback`.

**Comment by edoudou** [comment]
> A hacky workaround could be to make it visible and then quickly pause.

I did try, and I guess due to some race condition, I had the following bug.
- the card keep playing.
- the asset does not prerender (seen only with videos)

In general, I prefer to prevent using "hacky workarounds".

> We cannot make changes to the privacy features of PRERENDER state. We could make it so that PAUSED state allows buildCallback.

Yeah I figured out changing the `PRERENDER` state behaviour might not be a good idea. Being able to use the `PAUSED` state skipping the `VISIBLE` state might be a good option.

**Comment by edoudou** [comment]
> Not that I know of. The https://github.com/ampproject/amphtml/issues/37129 state feels a bit similar in purpose. For off-cache (or even just non-SERP) use cases I don't think we have the same privacy-preserving concerns -- so this seems like a reasonable request to me.
I just added the `PREVIEW` state to the code sandbox to test. It seems to be working perfectly for my use case, I just couldn't find it in the documentation / by browsing the code.

It's is just a documentation issue then.

**Comment by newmuis** [comment]
I think `VISIBLE` and `PREVIEW` both suffer from the fact that there is no way to indicate to the story that it should be paused, without encountering delays and/or race conditions.  

> Not that I know of. The new preview state feels a bit similar in purpose. For off-cache (or even just non-SERP) use cases I don't think we have the same privacy-preserving concerns -- so this seems like a reasonable request to me.

For the record, the new `PREVIEW` state will also preserve privacy in much the same way as `PRERENDER`.

**Comment by edoudou** [comment]
> For the record, the new PREVIEW state will also preserve privacy in much the same way as PRERENDER.

Oh, so I guess `PREVIEW` is not a viable solution for my case either ^^'

**Comment by samouri** [comment]
@edoudou + @newmuis: The privacy preserving characteristics of `PREVIEW` and `PRERENDER` modes depend on an AMP Optimizer rewriting subresource URLs to point to the cache. For example, redirecting all `<amp-img>` tag `src` attributes to point to a cache address instead of the original origin address. This concept doesn't apply off cache.

`PRERENDER` might work for your use case as long as all the components you care about have `prerenderAllowed` set to true.

**Comment by gmajoulet** [comment]
Thank you @samouri for bringing the conversation back on track! `visibilityState=prerender` will load all cached resources. You're only seeing the assets NOT being loaded because you're not using resources loaded from the AMP cache.

You have several options on how to move forward:

1. (Preferred) load AMP Cache URLs (cdn.ampproject.org)
2. Run your documents through the AMP optimizer

For (1) if you use the open source Stories Player, all it takes is adding this parameter that will rewrite your URLs: `<amp-story-player amp-cache="cdn.ampproject.org"` ([documentation](https://github.com/ampproject/amphtml/blob/main/docs/spec/amp-story-player.md#amp-cache)).
We're constantly improving performance for AMP Cache URLs, as we have more control over the scripts/css/assets.

If you do that, using `prerender` will load your first page assets.

**Comment by edoudou** [comment]
We try to always keep our stories compliant, but we have better control over the quality of the assets when not coming from amp cache, so we prefer to display the non cached story in our player.

**Comment by gmajoulet** [comment]
Just want to make sure you're aware of how much performance you're missing out on by not using the AMP Cache URLs.

Your story on the AMP Cache: https://www.webpagetest.org/result/220310_BiDc0X_C4C/?view=webvitals
Not on the AMP Cache: https://www.webpagetest.org/result/220310_AiDcP5_DAH/?view=webvitals

You load 2.5x more bytes, and fail both LCP and CLS. Higher quality assets doesn't necessarily mean better experience, you're losing a ton of traffic to load abandonments and much larger bounce rate.

**Comment by 12cew** [comment]
Should this issue be labeled as P2: Soon?

We are doing research about “Issue Priority Prediction". We have developed a tool to automatically label the priority of an issue. The basic idea is to employ Bert model to encode the textual and code descriptions of the issue, and incorporate the issue’s attributes in the model, then apply multi-task learning to facilitate other information boosting the prediction performance. 
 We have conducted experiments on four GitHub projects with 21700 issues, and results show that [79% accuracy]() can be achieved.

Our tool shows that this issue has a very large possibility to be labeled as P2: Soon 
Could you please tell us whether it should be labeled as P2: Soon?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.
