### ISSUE TITLE
[Story CWV] SSR system layer to slightly improve UX/CLS

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#37855]
### Description

Now that Stories are visible before the JavaScript is loaded, they're displayed without the system layer. We need to use [buildDom](https://github.com/ampproject/amphtml/blob/b70eebecdd6469148f2ae0f81b4918a3f851d6ec/src/compiler/README.md) to SSR the progress bar and system icons.

This will improve UX and potentially a bit of CLS.

cc @ampproject/wg-stories 

### Alternatives Considered

-

**Comment by mszylkowski** [comment]
Leaving this comment for my future self: Given that the system layer is embedded inside a shadow DOM we'd need the declarative shadow DOM logic to transform the shadow DOM once we load the JS. I can take a look to see if it'd work as expected with this overhead. Everything else should be smoother from my initial understanding.

**Comment by mszylkowski** [comment]
I think it wouldn't make sense to implement this change:

This will not improve the CLS at all, because the system layer would need to be rendered to the outer DOM and then moved to the shadow DOM where it currently is (HTML doesn't have a declarative shadow DOM), so we can't reander early the final version of the system layer; LCP wouldn't improve either. So no PX gains with this. UX could improve a bit, but if any user-stylesheet has a style that breaks the progress bar when not in a shadow dom, the progress bar would look awful and be bad for UX.

Moving sth from one DOM to another counts as separate items being removed or added to the page, but there's a chance that users can see it as a layout shift because of some user style that impacts the system layer inadvertently (eg: some weird border radius or transform they could have).

Another issue with this is that the system layer CSS would need to be added to `amp-story.css` as well as added inside the shadow dom CSS, which ends up being very messy.
