### ISSUE TITLE
[amp-story-shopping] Allow for a custom cta

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#38080]
### Description

Similarly to the `amp-story-attachment` and `amp-story-outlink`, allow for passing an optional `cta-text` attribute so that it is possible to override the "Shop Now" text.

Please also update the following:
- Documentation
- amp validation so that `cta-text` is a valid attribute

**Comment by processprocess** [comment]
Good idea :) I updated the description to include updating the documentation and validation.

**Comment by processprocess** [comment]
This needs to follow the API for `amp-story-page-attachment`
Reference the docs [here](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story-page-attachment/amp-story-page-attachment.md#cta-text-optional).

Steps to do this:
1. Allow a new attribute on `amp-story-shopping-attachment` called `cta-text`.
2. In buildcallback, if cta-text is defined, put it into the jsx template instead of the translated string.
