### ISSUE TITLE
Embed YouTube Videos In Web Stories

### ISSUE THREAD

**Issue by rdotsmith** [ampproject/amphtml#38103]
### Description

Seeking ability to embed YouTube videos in the story card itself. Normal AMP pages have <amp-youtube> but they're not valid in Web Stories. 
![image-20220323-093257](https://user-images.githubusercontent.com/103694929/163481508-e6e1de4e-493a-47b5-aec6-78f47248cbfd.png)

### Alternatives Considered

We can embed YouTube videos in attachments on a Web Stories card, but we want to embed YouTube videos on the card itself.

**Comment by cpauwels** [comment]
From what I know (amp stories team, feel free to correct if needed), YouTube videos can't be added to stories because they require interaction (tapping the play button), which conflicts with the tap to advance in the story.

The recommendation for adding a YouTube video in a story is to download it (youtube-dl for example) and host the video yourself, or to add the video to an amp-story-page-attachment component, where the amp-youtube component is allowed.

**Comment by ychsieh** [comment]
Correct. The UX philosophy for Web Stories is to allow auto-advancing the content. Closing this.
