### ISSUE TITLE
Expose AMP extension name when embedding amp-ad

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#3815]
amp-ad can be embedded within AMP extensions like amp-sticky-ad and amp-fx-flying-carpet. AMP should expose the extension housing the amp-ad, so ad networks can expose this information to bidders. Bidders can then use this information to price the ad requests appropriately. 
CC @cramforce @michaelkleber @kashyapnitin

**Comment by lannka** [comment]
Discussed with @jasti, just as how we normally pass `amp-ad` attributes into the 3P iframe via URL fragment, we can just pass this particular piece of data in the same way.

For example: `data-amp-container-element="amp-sticky-ad"`

We can maintain a list of ad container elements, so that only elements in the list will be passed through.

Once this data is available in the iframe, it's the 3P JS's responsibility to convert it to URL params that's meaningful to its ad server.

@michaelkleber can you give an example how doubleclick would like to use this piece of data? Is it something already supported on ad server?

**Comment by michaelkleber** [comment]
That sounds great in a 3p world.  In an a4a world (#3133), the ad request is constructed by contributed code and it would need access to the same information, but I presume that whatever utility function you use to populate the value of the `data-amp-container-element` property would be available for us to call in a4a JS.

The use case is that an ad network might want to adjust what ads it serves depending on where they will appear on the screen or how they will be displayed.

**Comment by lannka** [comment]
Probably the simplest way is to add this `data-amp-container-element="amp-sticky-ad"` to `amp-ad` element as a new attribute. So the current logic in both 3p and a4a just start to flow.

**Comment by michaelkleber** [comment]
SGTM!

**Comment by zhouyx** [comment]
Question I have about getting the container name for a given ad. 
Directly approach would be getting the closest parent element that is an ad container. Would we introduce more ad containers in future? If yes do we have a guideline for them. asking because I want the approach to work for all future ad container.

**Comment by jasti** [comment]
Is it easy to detect all parents? If so, I don't see any harm in passing an array/string of all parents.

**Comment by zhouyx** [comment]
It's easy, and we are doing that in `isPositionFixed` function now.  but if we only support an ad in single ad container (I think it's the case for for `amp-sticky-ad` and `amp-fx-flying-carpet`), would it be a waste to detect all parents then?

**Comment by jasti** [comment]
That's the status right now, but may have multiple containers in the future. I don't have a strong preference for how we approach it right now.

**Comment by lannka** [comment]
OK, I would say let's keep it simple for now (assuming one direct parent container for less computational cost). We can always extend later if necessary.

**Comment by jasti** [comment]
@zhouyx  With #4307 merged, is this already implemented? If so, is there documentation?

**Comment by zhouyx** [comment]
It's already implemented. not documented

**Comment by michaelkleber** [comment]
@zhouyx Looking at the DOM in the example page from #4862, I see the attribute `class="-amp-element -amp-layout-fixed -amp-layout-size-defined -amp-layout"` on the `amp-ad` element inside the `amp-sticky-ad` container.  That surprises me — I thought the point was for `amp-sticky-ad` to appear.

**Comment by zhouyx** [comment]
What the change here won't affect `class`. The change here is to pass `amp-sticky-ad` as through an HTML `amp-container-element` attribute. Ad server can access this piece of info from `data.container`

**Comment by michaelkleber** [comment]
@zhouyx Ah, thank you, I get it now!  And `window.context.data.container` is indeed `"AMP-STICKY-AD"`.  Much obliged.

**Comment by jasti** [comment]
@zhouyx Would you please document this change @ https://github.com/ampproject/amphtml/blob/master/ads/README.md#information-available-to-the-ad

Thanks!

**Comment by zhouyx** [comment]
@michaelkleber 
FYI: have an update here. with #4929 the container info is now in `window.context.container`. The change made to this week's canary and should be live in prod next week. So if you are using `window.context.data.container` please adapt to the new `window.context.container` by then. 
Sorry for any inconvenience.

Document updated.
