### ISSUE TITLE
Web Stories Videos Are Not Playing On Android 11 or Android 12

### ISSUE THREAD

**Issue by rdotsmith** [ampproject/amphtml#38201]
### Description

We just published a Web Story and noticed the videos on pages 6, 8, 10, and 12 do not play. They just load the first frame, then freeze. There's no sound or motion. 

This is also impacting a video animation we have on page 4 - but this page has no sound. You can see the animation just freezes on the first frame. 

URL: https://www.thinkwithgoogle.com/consumer-insights/consumer-trends/trending-visual-stories/viewer-choice-reshapes-content

Pages impacted: 4, 6, 8, 10, 12

Operating Systems Tested: Android 11 and Android 12

We can't reproduce this on Chrome Desktop, Safari Desktop, or iPhone Xr v15.4.1 - it's only happening on Android. 

### Reproduction Steps

Visit this URL in Android 11 or Android 12:

https://www.thinkwithgoogle.com/consumer-insights/consumer-trends/trending-visual-stories/viewer-choice-reshapes-content

Try to play the videos on pages 6,8,10,12. Also, try to play the animated "R" on page 4. It's supposed to move from left to right across the screen. You'll notice the first frame of the video loads, but the rest of the video never plays. 

### OS(s) Affected

Android 11, Android 12

### Device(s) Affected

Pixel 3, Pixel 6 Pro

**Comment by mszylkowski** [comment]
I'll get a bit technical here, I've already talked to some of you about this privately but wanted to document the error :)

We've looked into that story and the videos were using an unsupported video format ([HLS](https://www.dacast.com/blog/http-live-streaming/#:~:text=HLS%20format%20is%20an%20adaptive,widely%20used%20live%20video%20protocol.) / M3U8) on Android that browsers don't support natively and the HLS polyfill for JS is 200kB (so we'll likely never support HLS due to the size of the library needed to load these video formats).

**Are amp-videos ever going to support HLS?**
We only use browser codecs, so unless all browsers implement the decoding logic, HLS might not play in some browsers (note that HLS is just a holding format for pointing to multiple video or audio files, the video codec is actually different). We don't plan to add the HLS library to amp-video, and it's probably not a good idea to depend on a 200kB library to play a video, no matter how much better the encoding is on that format.

**Why does the video fail if you also specify an mp4 video as well?**
Because browsers don't always know what formats are supported (`canPlayType` returns `maybe`) we can't skip the HLS video automatically, we could only skip the video when it fails after it tries to load. However, automatic fallback of failed video sources is dangerous because the video takes a lot longer to load, so it's not clear whether silently failing to a fallback is better than loudly showing the error (which helps you debug the error more easily).

**What if I want streaming video files?**
Streaming videos is mostly useful for live videos (like Youtube live or Twitch), but on static stories the regular video formats work just as well (given that the video has a specific length). mp4 and other formats can currently support partial playback with sub-sections of the video downloaded as needed, so you don't get any benefits from HLS.

So, I'll close this bug, let me know if you need any further help! The recommendation is to use formats that are supported in all browsers.
