### ISSUE TITLE
Erro amp web-story on parsed in LightHouse

### ISSUE THREAD

**Issue by dougrhis** [ampproject/amphtml#38329]
### Description

Error in amp web-story when parsed by LightHouse

### Reproduction Steps

https://teste.comercomfartura.com.br/teste/?utm_content=123

![Captura de Tela 2022-07-04 às 12 14 51](https://user-images.githubusercontent.com/9891463/177182612-e464861a-5827-43dc-87be-460db38659e8.png)
![Captura de Tela 2022-07-04 às 12 13 44](https://user-images.githubusercontent.com/9891463/177182620-c27f3d46-bbc3-4350-af49-f8bf8d01aecd.png)
![Captura de Tela 2022-07-04 às 12 13 28](https://user-images.githubusercontent.com/9891463/177182621-4328c662-0fab-4c4a-9865-07d1925bb996.png)

**Comment by coreymasanto** [comment]
The `Links are not crawlable` indexing warning can be ignored because it's mainly pointing out that there is no `href` attribute, and we only include that attribute if the story is in a viewer/player that has an `'attribution' `parameter provided to it (more info [here](https://github.com/ampproject/amphtml/blob/34fbeda57c3cc9d01ab3c39cf9618342ec840187/docs/spec/amp-story-player.md#display-story-attribution)).

The `[user-scalable="no"] is used` accessibility warning can also be ignored because I believe that it is used to prevent users from using zoom-in and zoom-out gestures for stories.

**Comment by adamshwa** [comment]
Hi there @coreymasanto 

After following these instructions:
The data will come from the <amp-story>'s metadata attributes in the story's document, as described:
1. For the logo: the entity-logo-src attribute (if provided), otherwise the publisher-logo-src attribute.
2 .For the string of text: the entity attribute (if provided), otherwise the publisher attribute.
3. When the attribution is clicked, it will navigate the user to a URL. This will come from entity-url attribute if provided, otherwise it will use the story's canonical domain.

It failed to display both logo and text, can you please review if there is bug in the code?
I tried to debug this area, and it never manages to add anything to src attr, although something was config.
![Screen Shot 2022-08-25 at 17 38 43](https://user-images.githubusercontent.com/111682480/186695642-af84adfc-f1e6-43ab-8002-cbabc7b03ae2.png)
