### ISSUE TITLE
New domains not getting approved for AMP for Email

### ISSUE THREAD

**Issue by akshayadinesh** [ampproject/amphtml#38480]
### Description

Hey! We've been trying for the past 3 weeks to get new email addresses approved for AMP for Email in Gmail using this [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSdso95e7UDLk_R-bnpzsAmuUMDQEMUgTErcfGGItBDkghHU2A/viewform?gxids=7628), and we have not received any responses or approvals. Does this form no longer work for enabling new domains? What is the new process? This is pretty frustrating for brands urgently trying to send AMP emails.

### Reproduction Steps

Fill out the AMP for Email Sender Registration [form](https://docs.google.com/forms/d/e/1FAIpQLSdso95e7UDLk_R-bnpzsAmuUMDQEMUgTErcfGGItBDkghHU2A/viewform?gxids=7628) after sending a test email.

**Comment by newmuis** [comment]
Let me see if I can find out the process.

**Comment by newmuis** [comment]
As far as I'm aware, the requirement for usage is simply filling out the form that you've linked.  It does not necessarily indicate that you will receive a response.

Each email client may approve senders based on their own subjectivity and their own criteria.  Since you mentioned Gmail, specifically, Gmail has their own documentation [here](https://developers.google.com/gmail/ampemail/register).

However, this repository tracks issues with the open source AMP format itself; Google's usage of that format or approvals for senders is out of our control.

Please feel free to reopen this issue for any further discussion.

**Comment by danchar** [comment]
I'm having this issue as well. Newmuis, is there a contact to seek feedback or get a status where our registration is?
