### ISSUE TITLE
Web Stories “Get link” returns foreign language characters as encoded URL in story bookend

### ISSUE THREAD

**Issue by LuckynaSan** [ampproject/amphtml#38510]
### Description

The story bookend is displayed with HTML markup when the story title or permalink slug contains language special characters.

Example story URL: https://feignednorth.s4-tastewp.com/web-stories/%e0%b0%87%e0%b0%82%e0%b0%a1%e0%b0%bf%e0%b0%af%e0%b0%be-%e0%b0%b8%e0%b0%bf%e0%b0%ae%e0%b1%86%e0%b0%82%e0%b0%9f%e0%b1%8d%e0%b0%b8%e0%b1%8d-%e0%b0%aa%e0%b1%88%e0%b0%a8-%e0%b0%95%e0%b1%87%e0%b0%b8/

### Reproduction Steps

1. Create a new Web Story
2. Use “ఇండియా-సిమెంట్స్-పైన-కేస” as title
3. Publish the story. 
4. View story
5. Click Share icon > Get Link. Note URL copied contains HTML markup.

![image](https://user-images.githubusercontent.com/66372350/197801707-77aefd86-8fef-4ed6-900b-27c19616e772.png)

**Comment by newmuis** [comment]
I believe this is actually the correct behavior, as these characters are URL encoded to ensure compatibility across systems.  The only characters that are guaranteed not to require encoding in URLs are the [unreserved characters](https://en.m.wikipedia.org/wiki/Percent-encoding).  We rely on the end user's web browser to provide the URL encoding when copying the link.

These URLs are otherwise equivalent, and both should work.
