### ISSUE TITLE
AMP Not Working on Indonesia

### ISSUE THREAD

**Issue by srqwes** [ampproject/amphtml#38567]
### Description

AMP is not working on ios, and sometimes android on indonesia, i check other sites that have AMP version also not working in
Indonesia

### Reproduction Steps

googl.com/amp/ExampeSites.com/ not working

### OS(s) Affected

Android, Ios

### Device(s) Affected

All Ios and Android

### AMP Version Affected

Latest

**Comment by emrenogay** [comment]
I can help you for IOS write me on skype https://join.skype.com/invite/d5VbV1IRR1wD

**Comment by newmuis** [comment]
Google's AMP viewer is only used in contexts where they can detect browser support, but recent changes to webkit have made this no longer possible on iOS-based browsers.  This is not a breakage in AMP, though; the page should still function accordingly. It is just represented as a direct link to the AMP page on the publisher's site, rather than using Google's AMP viewer.
