### ISSUE TITLE
Return to the main page after Web Story has ended 

### ISSUE THREAD

**Issue by LuckynaSan** [ampproject/amphtml#38594]
### Description

A user would like to see a Web Story close out and return to the site page after the story has ended. 

Opening this feature request for the format to consider.

Web Stories support topic: https://wordpress.org/support/topic/automatic-redirect-to-the-main-page-of-the-site-after-viewing-the-last-slide/

### Alternatives Considered

n/a

**Comment by newmuis** [comment]
This should be a request for the player integration within the web stories Wordpress plugin.  The hooks from `amp-story-player` to implement such a thing should be available today.  @swissspidy do you know where the right place to track that feature request would be?

**Comment by swissspidy** [comment]
@newmuis I suggested opening a topic here because I understood this as a feature request for when viewing the canonical URL.

For amp-story-player we could handle this in the googleforcreators/web-stories-wp repo, though it would only apply when a story is viewed in a lightbox that uses the player

Context: Lucky is a support specialist for the WordPress plugin

**Comment by newmuis** [comment]
For the canonical URL, there is (intentionally) no intent to support this.  The correct way to architect this would be to use the `amp-story-player` to implement hierarchical navigation.

**Comment by newmuis** [comment]
Closing this issue, as this is not something that the web stories format plans to support.

If the web stories WordPress plugin (or any other consumer of the `amp-story-player` API) intends to support this, please file separate tracking issues accordingly.
