### ISSUE TITLE
Open Redirection 

### ISSUE THREAD

**Issue by Arrpiittt** [ampproject/amphtml#38980]
### Description

Open redirection vulnerabilities arise when an application incorporates user-controllable data into the target of a redirection in an unsafe way. An attacker can construct a URL within the application that causes a redirection to an arbitrary external domain. This behavior can be leveraged to facilitate phishing attacks against users of the application. The ability to use an authentic application URL, targeting the correct domain and with a valid SSL certificate (if SSL is used), lends credibility to the phishing attack because many users, even if they verify these features, will not notice the subsequent redirection to a different domain.

### Reproduction Steps

Step-1 : Go to any *.cdn.ampproject.org

Step-2: Let's take a example https://www-thefantasydoctors-com.cdn.ampproject.org/c/s/www.thefantasydoctors.com/spurs-forward-rudy-gay-to-miss-time-with-heel-issue-dr-parekh/amp/

Step-3: Now change the URL after the /c/s/ endpoint 

Step-4: https://www-thefantasydoctors-com.cdn.ampproject.org/c/s/www.bing.com you will redirect to bing.com

Step-5: Attacker can use this bug to initiate phishing complain.

**Comment by erwinmombay** [comment]
@banaag would you mind taking a look at this?

**Comment by banaag** [comment]
After doing research on this, the redirect happens not to www.bing.com initially but to (1) https://www-bing-com.cdn.ampproject.org/c/s/www.bing.com (and this appears to be by design). Only because www. bing.com is not in the amp cache, does it eventually redirect to www.bing.com.  I'm not sure we should be changing the initial behavior in (1) as this might have unexpected effects on existing to code that depends on that behavior. 

@erwinmombay WDYT?

**Comment by banaag** [comment]
Just to be clear, for this example, the sequence goes:
https://www-thefantasydoctors-com.cdn.ampproject.org/c/s/www.bing.com
redirects to:
https://www-bing-com.cdn.ampproject.org/c/s/www.bing.com
(which has matching domains, so no phishing)
which then eventually redirects to:
[www.bing.com](http://www.bing.com/) (since no entry in amp cache)

**Comment by erwinmombay** [comment]
Thanks for explaining further @banaag , the second step explains a lot.

closing this out as WAI. feel free to re-open if there are more concerns.

**Comment by symbol90** [comment]
You are right, but I was the first to report this vulnerability
