### ISSUE TITLE
Youtube cover image is sized incorrectly

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3909]
See first example in http://localhost:8000/examples.build/youtube.amp.max.html

I thought we used the `cover` display to make it work previously.

**Comment by cramforce** [comment]
Just realized we still use a direct `img` tag and that only instagram was converted. Any reason besides time?

**Comment by mkhatib** [comment]
For YouTube it's because of #3216 and the hack we use to fallback between `sddefault` and `hqdefault`. If we give up that hack we can convert to using `amp-img` and proper `createPlaceholderCallback` instead.

Not sure why the `cover` is not taking effect. I remember we originally waited a bit because there seem to  be a delay for the cover to be applied. Will look into it.

**Comment by cramforce** [comment]
@aghassemi please take a look!

**Comment by aghassemi** [comment]
@cramforce Fortunately this is not a bug with our `<amp-youtube>`. The first example in `youtube.amp.max.html` is using a custom `<amp-img>` as placeholder for the cover that points to `https://i.ytimg.com/vi/mGENRKrdoGY/hqdefault.jpg`. Now, the built-in cover image in `<amp-youtube>` uses `object-fit: cover` (same as youtube itself) for the cover image but the custom `<amp-img>` used in the example is not setting that CSS rule hence the visual difference. 

We can fix that by adding `    <style>
      amp-img[placeholder] img {
        object-fit: cover;
      }
    </style>` to `youtube.amp.max.html` but I think the whole example is misleading example, we should not encourage using `<amp-img>` pointing to the actual cover photo as palceholder (since we do that for you anyway). I am going to change that example.
