### ISSUE TITLE
Rendering with viewport limitations may have a bug

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3911]
To repro:

- Go to http://localhost:8000/examples.build/instagram.amp.max.html
- Fling down really fast to the bottom of the page
- See how it takes 5 seconds (until the next pass) to load the full instagram iframe.

This doesn't only happen for fast flings, but it is easier to repro this way.

Setting to critical right now, but please lower to high priority if this is rare in practice.

**Comment by cramforce** [comment]
@dvoytenko should also take a look.

**Comment by jridgewell** [comment]
I'm not able to get 5 second delays, the most I've seen is 700ms after I stop scrolling to start layout and 1300ms to finish (the first `<amp-instagram>` takes a similar amount of time to finish). About 600ms is waiting for the next pass, and I think this is due to the initial run of other JS though maybe it is due to [`Resources#calcTaskTimeout`](https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L1127-L1134).

**Comment by dvoytenko** [comment]
This sounds like the initial penalty we have in `calcTaskScore`.

**Comment by jridgewell** [comment]
Ok, I think I've found it:

 - `<amp-instagram>` will [not render outside the viewport](https://github.com/ampproject/amphtml/blob/master/extensions/amp-instagram/0.1/amp-instagram.js#L57-L59).
 - We queue things to layout/preload as [step 3](https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L934-L949) of the "discover work" phase.
 - We set whether an element is in the viewport as [step 4](https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L951-L965).

So because we set whether an element is in the viewport _after_ we schedule things to layout, the scrolled-into-view `<amp-instagram>` is not yet "in viewport". Since it won't render outside viewport, it won't be scheduled. After scheduling things that either were in viewport, or can render outside what was the viewport, we update whether elements are in viewport. So the next pass, the we'll schedule the scrolled-into-view `<amp-instragram>` since it now knows it's in the viewport.

The fix seems to be updating "in viewport" before trying to schedule things to layout/preload. PR incoming.
