### ISSUE TITLE
mParticle vendor availability on amp analytics cdn

### ISSUE THREAD

**Issue by annapareddy** [ampproject/amphtml#3921]
mParticle was recently added as vendor to amp analytics extension. The code has been reviewed and merged into master. 
In our documentation, to send data to mParticle from AMP pages, we are recommending developers to create script tag with src https://cdn.ampproject.org/v0/amp-analytics-0.1.js. 

I can't find mParticle in that file. Can someone please let me know what need to be done for mParticle to be included in that file on CDN ?

PR : #3774

**Comment by rudygalfi** [comment]
Code that's merged needs to be included into a release. It looks like you were included into the canary last week, so presumably in the production version this week, but as Avi noted, things may be a bit messed up due to US holidays (https://github.com/ampproject/amphtml/pull/3774#issuecomment-229507723).

If you opt into the AMP dev channel at https://cdn.ampproject.org/experiments.html, the version of https://cdn.ampproject.org/v0/amp-analytics-0.1.js served to you should include mParticle.

**Comment by annapareddy** [comment]
@rudygalfi Thank you.
