### ISSUE TITLE
Question about https requirement in AMP-VIDEO vs AMP-IMG

### ISSUE THREAD

**Issue by peternofelt** [ampproject/amphtml#3946]
Curious to know the need for HTTPS requirement for amp-video when amp-img does not have the same requirement. 

From a content perspective, both content formats are static resources (thought video is more recent day to day occurrence on the web). Genuinely curious to understand the HTTPS requirement for video and then not for image. Seems arbitrary. 

Thanks,
Pete

HTTPS reference requirement in amp-video.
https://github.com/ampproject/amphtml/blob/master/builtins/amp-video.md#attributes

**Comment by dvoytenko** [comment]
/cc @Gregable 

@peternofelt , this is because when https image is not available we can always proxy it via https via our CDN. But we cannot proxy videos.

(I'll close this issue for now, but please feel free to comment back to reopen)

**Comment by peternofelt** [comment]
@dvoytenko thank you for the reply. This very much makes sense from from the technical perspective of Google assisting with content proxying. I agree proxying video would come with a host of problems. 

As clarification: Google will proxy https videos if they are not available?

A Case For HTTP Video
Independent of Google (as AMP is open source and can be used by a variety of services/companies), might it be a valid to suggest that amp-video have the a parameter like 'proxy="http-skip"'. In this case amp-video can display video (actual video files like m3u8 or mpg4, not wrapped by a web player) without the https requirement.

Another reason for this is the mere fact that most smaller publishers (and even large organizations) want to host their own video but don't have the time/monetary bandwidth or technical resources to provide this video via HTTPS. To them images *just work* and as video becomes as ubiquitous a image media, there's the same expectation.

Thoughts?

**Comment by dvoytenko** [comment]
@peternofelt 

> Google will proxy https videos if they are not available?

No. We can't really proxy video streams - that would cause very big performance issues.

> proxy="http-skip"

The problem here is that AMP is always served via HTTPS. So, in some environments (strict mode) the http video simply won't play. In others - we'll be breaking https promise.

> but don't have the time/monetary bandwidth or technical resources to provide this video via HTTPS

We certainly try to be very conscious of this, hence we do proxy images when needed. However, I believe, at this point it's relatively easy to find very cheap or even free certificates. I don't have numbers off the top of my head, but bandwidth wise https should not consume much more than http (and likely less) and latency wise https wouldn't have any visible downside for videos.

/cc @cramforce

**Comment by cramforce** [comment]
We believe pretty strongly that very soon all content on the internet will be HTTPS and it is definitely a nice "feature" of AMP that it is pushing multiple ecosystems such as ads and video serving in that direction.

We do proxy HTTP images because it was easy to do, but we cannot proxy video and hence video must be HTTPS like all other non-proxied resources. This definitely makes adoption a bit harder, but it only moves it up by 6 months or so, since everything is moving to HTTPS anyway.
