### ISSUE TITLE
Investigate unit/integration test breakages starting with NodeJS 20

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#39510]
### Description

So far my investigation led me to find that https://github.com/nodejs/node/commit/fb2b80fca08fca9940e4fd1c2fa0fa7f7c33b056 is the commit that causes the breakage. That commit is itself a dependency update, which makes this one deep rabbit hole

### Reproduction Steps

To build Node locally, clone the repository (`git clone https://github.com/nodejs/node`), check out the commit you want to build, and run `make clean && make -jN` (where N is the number of CPU cores on your workstation). This is time consuming (e.g., for me it takes about 25-35 minutes on 6 cores)

You can then run AMP using that custom version of Node from the amphtml directory as `/path/to/node/repo/out/Release/node amp.js <command>`. To re-run the unit tests on my workstation I used `amp clean && ~/node/out/Release/node amp.js unit --headless` (this makes sure that the .babel-cache is cleared, in case the cache could interfere with the results)

**Comment by danielrozenberg** [comment]
Related: #39492

**Comment by erwinmombay** [comment]
@danielrozenberg i tried running `amp unit --headless` using node v18.18.0 installed by `nvm` and could not reproduce `ReferenceError: AMP is not defined`

then i downloaded the `node` repository then checked out the `v18.18.0` tag and ran `make clean && make -j6`. next i ran `/path/to/node/repo/out/Release/node amp.js unit --headless` and could not reproduce `ReferenceError: AMP is not defined`

I did get a bunch of failing errors (timeout, done() etc, failed to load img) but none of them seemed like the `ReferenceError` we are looking into. Am I doing anything wrong or are any of the flakes/timeout errors I get caused by the ReferenceError? (i have always had these flakes and timeout errors for whatever reason)

**Comment by danielrozenberg** [comment]
Hmm... I just sent out a test PR that un-pins the version on Node, and the tests pass

It's possible that I merged a renovatebot PR for a dep that was fixed in the meantime, or that Node v18.18.1 fixed whatever broke for us on v18.18.0

I'm going to test a few commits using v18.18.1 in between when I pinned Node to v18.17.1 (2e2cdc1) and now to see what's up - if I can find a spot where it breaks, and then when it doesn't break, it means that something was fixed upstream and we can pretty safely un-pin node

**Comment by erwinmombay** [comment]
@erwinmombay to take a look as well

**Comment by danielrozenberg** [comment]
Created #39613 to jumpstart your investigation - it reverts the v18 pinning and switches to LTS. See failures in that PR's CircleCI results - `amp unit` tests and `amp integration` tests both fail during the Babel phase. `amp dist` and `amp e2e` pass

**Comment by danielrozenberg** [comment]
Let's close this for now and cross our fingers that this doesn't come back 🤞
