### ISSUE TITLE
Allow custom script after first render when AMP page is top level context

### ISSUE THREAD

**Issue by triblondon** [ampproject/amphtml#4064]
Apologies for reassuming the role of boat rocker in chief.

Would it be feasible to allow custom script to run on an AMP page, in the following circumstances:
- Script URL is declared in a special link tag
- Page is the top level context, i.e. is not being displayed as part of the Google search carousel or in gmail or whatever.
- Custom script is loaded asynchronously by the amp runtime once rendering is complete

This would enable publishers to progressively enhance their full article experience on top of an amp page, rather than having to serve amp on a different URL.

This idea came out of a discussion we just had about PWAs with the Google Tokyo team.

**Comment by cramforce** [comment]
CC @dvoytenko 

I've been thinking about this, but slightly differently.

This is where we are now:

- AMP already supports SW installation (both same origin and from remote origin)
- #3742 is working towards an app shell model for same origin docs, where the PWA displays and enhances the AMPs.
- The SW based system would essentially allow free customization for the N > 1st page view (user lifetime, not seession), so users always get a fast experience.

Obviously, this has one important problem: It won't work in Safari (being the only browser that has not yet announced support).

So, given the above, I see script injection really only as a polyfill for ServiceWorkers in Safari and older browsers. They main issue with just allowing script injection, which I'm not fundamentally opposed to, is that AMP itself makes assumptions that can easily be broken if there are other scripts around. It'll be very easy to write programs that are broken and hard to fix in this environment, and I don't like propagating programming models that have this property. 

The work in #3742, however, provides for a clean mechanism through which containers like a PWA can extend a document (Through Shadow DOM slots). Any system we build only for Safari, should take advantage of as much of the same infrastructure, since we all kind of expect Safari to ship SWs next year.

I thus think, the right approach is to implement a type of super-partial-ServiceWorker-polyfill, where if SWs are not supported a script is loaded, but only executed if it comes from cache (e.g. loads faster than 100ms), and this script would then given the chance to upgrade the page in a similar fashion to what the SW would have done.

**Comment by triblondon** [comment]
Ok, so you're saying I request an article, and service worker instead responds with an app shell that makes a fetch for the article, and does some deconstruction of the AMP to create a view.

That's a very specific application architecture to support in the platform. Reminds me of app cache! What if that doesn't suit my application? What I'm suggesting leaves the architecture up to the developer, including registering a service worker if an app shell is the best solution for them.

**Comment by cramforce** [comment]
Well, it was just one example. As soon as you have a ServiceWorker you can do whatever you want.

**Comment by adewale** [comment]
@triblondon please also take a look at: https://ampbyexample.com/components/amp-install-serviceworker/ and https://ampbyexample.com/sw.js

Are those closer to achieving what you want?

/cc @sebastianbenz

**Comment by triblondon** [comment]
Thanks @adewale.

I hadn't considered the idea of the Serviceworker modifying the AMP page so that it's no longer AMP compliant, but that would achieve what I'm looking for, assuming that the browser viewing my AMP page supported serviceworker.  So this would enable pages to be fully AMP compliant when displayed on third party platforms like Google search carousel, and still use AMP components when displayed normally, without having to have an `amp.` subdomain or `?amp=1` mode.

**Comment by adelinamart** [comment]
@cramforce what's the latest status on this one?Thanks.
