### ISSUE TITLE
Do not allow ad-shaped iframes in fixed position

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#4122]
If `amp-iframe` instances match the existing code: https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/0.1/amp-iframe.js#L479 and also fulfill the conditions of https://github.com/ampproject/amphtml/blob/74f25ee3225229426a9d7c8ecbdec3e69acc00e4/extensions/amp-ad/0.1/amp-ad-3p-impl.js#L112 then do not render the iframe and emit an error to the console to use `amp-sticky-ad` plus `amp-ad` instead.

CC @lannka @jasti

**Comment by lannka** [comment]
Would that affect existing users?

**Comment by muxin** [comment]
Yeah. The idea is to let people use sticky-ad and amp-ad instead.

**Comment by jasti** [comment]
I doubt if many people use it already. @muxin are we throwing some sort of console message to ask users to use amp-sticky + amp-ad instead?

**Comment by muxin** [comment]
Yes, we are going to show error console message asking people to use amp-sticky-ad + amp-ad instead.

**Comment by cramforce** [comment]
This is obviously a non-backward compatible change, but we are willing to
take the breakage. I'm not aware of anyone actually doing this, though.

**Comment by muxin** [comment]
@cramforce I just want to clarify things a little bit. We are using https://github.com/ampproject/amphtml/blob/74f25ee3225229426a9d7c8ecbdec3e69acc00e4/extensions/amp-ad/0.1/amp-ad-3p-impl.js#L112 because we don't want the amp-iframe to be ad-like and its ancestor to be position: fixed, right? How about `amp-iframe` inside `amp-sticky-ad`, `amp-light-box` and `amp-fx-flying-carpet`? If the `amp-iframe`inside those element is position-fixed ad, do we allow it?

**Comment by dvoytenko** [comment]
I believe this is correct: if we think the iframe is ad-shaped - we want to apply the same restrictions to it as to an amp-ad.

**Comment by muxin** [comment]
I see, thanks @dvoytenko
