### ISSUE TITLE
Make AMP validator NPM module interface more idiomatic

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#4155]
I think we could still iterate on the JS API a bit to make it more idiomatic. Something like

``` JS
var validate = require('amphtml-validator').validate;
validate(html).then(allGood).catch(function(reason) {
  if (reason.validationErrors) {
    handleValidationErrors((error.validationErrors);
  } else {
    throw reason.error;
  }
});
```
- For promise chainability it makes sense to use rejection for all the bad cases and only resolve on the good ones.
- I think we should avoid exposing magic strings like 'PASS' and instead use booleans.

Also: I'd like to avoid using ES6 in the examples as long as that is not common practice on NPM.

**Comment by jridgewell** [comment]
> For promise chainability it makes sense to use rejection for all the bad cases and only resolve on the good ones.

👍. I suggested this as well.

> Also: I'd like to avoid using ES6 in the examples as long as that is not common practice on NPM.

Everything in the example is supported by the latest stable node.

**Comment by pietergreyling** [comment]
Wrt "I'd like to avoid using ES6 in the examples as long as that is not common practice on NPM."

Can we ensure that we couple compatibility to that of Google App Engine Node.js Flexible env docker image:
https://cloud.google.com/appengine/docs/flexible/nodejs/
https://cloud.google.com/appengine/docs/flexible/nodejs/release-notes
https://github.com/GoogleCloudPlatform/nodejs-docker

I have had to pin my dev env to stable node5 (5.11.1) after running into crashes on production caused when hitting some ES6 code (which had to be refactored) after pushing node6 images to GCE. Be particularly careful with promises support as well.

**Comment by powdercloud** [comment]
Perhaps to explain these eyesores a bit, the point of the promise is to hide that we are fetching the validator script (from cdn.ampproject.org by default). If the promise fails, then there was something wrong with that. Regardless of the language used, you would probably not want to lump this in with a validation failure. I could see something that is synchronous and static and hides the getInstance() call but I'm not sure how to do this (it'd crash the app if the script can't be fetched).
On the 'PASS' string, it's the enum value name from validator.proto. We copy this over so it's possible to make it a bool (sortof, except for expressing 'UNKNOWN' reasonably), but keeping the difference to the proto representation as small as possible is a plus.
So I think for both of these problems, one could make a wrapper which makes it slightly more convenient / idiomatic for Javascript. Question is, should this go into index.js? My bias is no, because it's good to keep the surface of the API smaller and people can do it for themselves. I think it would be better to provide this kind of thing as an example that one can copy/paste/modify as needed. I think the main contribution of the API is to provide reliable / stable / reasonably efficient access to the validator so that others can build upon it.
I'll make the example use var and old style loop. Hope this takes care of too much ES6. :-)

**Comment by cramforce** [comment]
@powdercloud I get all your points, but developer experience trumps stuff that is nice with some proto :)

Totally agree that all of this is just a wrapper around your API (can go into index.js or not). Basically just another layer of abstraction on top. I agree with the sentiment of having a low level base, but a lot of people will use this, so we should make it nice.

You also totally don't have to do this yourself. I'll find someone to write a quick wrapper if we agree  in principle

**Comment by powdercloud** [comment]
@cramforce Thank you! I'm very happy for someone to make a wrapper, especially if it's an optional thing that doesn't complicate index.js. :-)

As for the benefits of the .proto (https://github.com/ampproject/amphtml/blob/master/validator/validator.proto) - I believe the consistency between different languages / formats is useful to anyone, even Javascript developers. E.g. the command line tool supports json which uses the same field names and values and so on:
amphtml-validator --format=json https://www.google.com/
If someone wanted to write a Ruby script, they could look at some .json example output, maybe skim the .proto definition (or something we generate from it down the road) and get going, shelling out to our command line tool. They don't have to learn Javascript or read the index.js code.

Just saying though, whatever works is fine.

**Comment by adelinamart** [comment]
What's the latest status here? Thanks

**Comment by Gregable** [comment]
@cramforce , is this still an issue you think needs work, or are we in good shape?

**Comment by erwinmombay** [comment]
this should be good with the gulp adapter and everything imo
