### ISSUE TITLE
amphtml-validator CLI fails on Mac OS X

### ISSUE THREAD

**Issue by uncompiled** [ampproject/amphtml#4246]
When running amphtml-validator from the command line on Mac OS X, the following error occurs:

```
$ amphtml-validator https://www.ampproject.org/
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

## How do we reproduce the issue?

1. On a Mac, run `npm install -g amphtml-validator`
2. Run `amphtml-validator https://www.ampproject.org/`

readlink behaves differently on a Mac, so [index.sh](https://github.com/ampproject/amphtml/blob/master/validator/nodejs/index.sh#L11) fails.

A workaround is to `brew install coreutils` and use `greadlink` instead.

**Comment by ericlindley-g** [comment]
@powdercloud   — Slotting in "pending triage" for now. please update the milestone when you have a sense of when work will start. Thanks!

**Comment by powdercloud** [comment]
Thanks much for saying hi and reporting this. Sorry I've never used a Mac, that's why this happened.

We should to make this portable. Two ideas:
- Use this recipe to implement a readlink -f substitute shell function: http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
- Use the Node.js interpreter since it comes with a nice fs package, so it ought to be possible to make a one-liner for readlink -f.

I'm in the midst of something right now but will look into this in a while unless someone else posts a solution first.

**Comment by powdercloud** [comment]
I posted a PR which uses the second approach. Thanks in advance for any feedback. The action item that remains is to verify this fix works on a Mac.

https://github.com/ampproject/amphtml/pull/4269

**Comment by powdercloud** [comment]
Thanks for your help @uncompiled.
version 1.0.10 with the fix pushed to npmjs.com.
