### ISSUE TITLE
Allow ampproject.* in <amp-iframe>

### ISSUE THREAD

**Issue by pbakaus** [ampproject/amphtml#4339]
As irony has it, @cramforce can't have nice things because he [disallows](https://github.com/ampproject/amphtml/blame/master/extensions/amp-iframe/0.1/amp-iframe.js#L66) the ampproject.org origin categorically in all <amp-iframes>. 

Otherwise, of course, he'd see this fancy metrics page when he navigated to https://ampproject.org/metrics:

![screen shot 2016-08-02 at 8 18 04 pm](https://cloud.githubusercontent.com/assets/43004/17352762/4921bb1e-58ee-11e6-8a76-de572f5a409f.png)

A little help?

**Comment by jridgewell** [comment]
@dvoytenko, do you know why we have this restriction?

**Comment by dvoytenko** [comment]
I suppose it'd have been sufficient to always require `sandbox` w/o `same-origin` for these iframes. But generally, `ampproject.org` is a proxy and thus embedding self-proxied would open us to essentially circumvent our own AMP rules since they are on the same origin. And `sandbox` attribute is not yet supported everywhere we need.

**Comment by pbakaus** [comment]
Is there any workaround you can think of for our actual homepage? Maybe we can change the regex to explicitly catch cdn.ampproject.org instead?

**Comment by rudygalfi** [comment]
Would it make sense to host embedded resources like this off of ampproject.net?

**Comment by pbakaus** [comment]
I guess we could, but would need another deploy target, firebase app etc. Needlessly complicated imho.. I'd prefer the fix suggested.

**Comment by dvoytenko** [comment]
I'd wait on the @cramforce to decide. There might be other reasons as well.

**Comment by cramforce** [comment]
While not strictly necessary (can be circumvented with things like a URL shortener) I'd really like to avoid allowing this. Resources on our own origins should only be included through more direct mechanism, because we put special trust in them.
Don't we have the synthetic firebase domain (which we used during testing) we can use for this?

**Comment by pbakaus** [comment]
Didn't even think about the Firebase trick, sure, I'll use that. Whatever works :)
