### ISSUE TITLE
Allow nested `<svg>` elements

### ISSUE THREAD

**Issue by tigt** [ampproject/amphtml#4343]
It's unintuitive, but `<svg>` is both a root and container element. Its use as container element is essential for positioning and sizing graphics elements via percentages, since `<g>` can't take dimensional attributes and `transform`s can't use anything but coordinate-space units.

Example:

```xml
<svg>
  <g transform="translate(-50)">
    <svg x="100%">
      <path d="..."/>
    </svg>
  </g>
</svg>
```

This snippet anchors a `<path>` off the right side of the SVG viewport, then shimmies it back into view by 50 units. It's the only way to get this kind of positioning in SVG in browsers that don't support `<foreignObject>`.

[Currently the `<svg>` element has a `DISALLOWED_ANCESTOR` of `<svg>`](https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L1482). It would be enough to omit that line, but maybe you found a reason to avoid that?

**Comment by Gregable** [comment]
Unfortunately it requires a little more work than just changing that rule, but that only means it'll take a little longer. I'll work on it

Long explanation: The AMP Cache reserializes HTML to make sure that the result is uniform for all browser's quirks parsing engines. We have special code for handling `<svg>` sections, because tag parsing follows different rules inside an `<svg>` section. Specifically, self-closing tags (ie: `<foo />`) are parsed as both an open and close, which isn't the same in HTML5. There may also be some other rules I'm not aware of. The code assumes no nesting in a valid page, so I'll need to make some changes to the AMP cache before I can change the rules.

**Comment by ericlindley-g** [comment]
@Gregable Given the blocking tasks before being able to tackle this, it sounds like "backlog" is the right spot, but please update the milestone if work is planned in the short term

**Comment by Gregable** [comment]
Will do. I do want to implement this, but there are some more urgent things to tackle first.

**Comment by jridgewell** [comment]
Closed by https://github.com/ampproject/amphtml/pull/4638.

**Comment by jaygray0919** [comment]
@Gregable we would like to put a button in an SVG that opens an `amp-lightbox`. To do this we will need to use SVG  [foreignObject](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject). We would use the container structure described above by @tigt . My two questions: 
1. is `foreignObject` valid amp-svg?
2. can we link a `foreignObject` button to amp-lightbox?

Here is the use case:
we want to avoid using a mouse-over tool-tip because mouse-over is ineffective in mobile. For example, here is a draft of our  [mobile tool-tip](https://afdsi.org/test/_amp-list-tooltip-2/). It implements a design proposed by @sebastianbenz. We would like to use the same structure with an SVG (as above `amp-list` and `amp-mustache` supporting `amp-lightbox`).

Hence our questions 1 and 2. Thanks for advice here.

**Comment by jridgewell** [comment]
> can we use the nested structure

Yup

> is foreignObject valid amp-svg?

No, it's still forbidden.

> can we link a foreignObject button to amp-lightbox?

No, per above. Why can't the button be outside of svg?

**Comment by sebastianbenz** [comment]
@jaygray0919 AMP actions work inside svgs so you might not need a button: 

```
<rect ry="3" rx="3" height="72.5" width="72.5" y="0" x="954"
     tabindex="0" 
     role="button"
     on="tap:myLightbox"></rect>
```

See also https://amp.dev/documentation/examples/interactivity-dynamic-content/seatmap/preview/?referrer=ampbyexample.com

**Comment by jaygray0919** [comment]
@sebastianbenz perfect (why didn't i think of that ...). @jridgewell The 'action' (the button) cannot be outside the SVG because it performs the role of a tool-tip. The tool-tip needs to be adjacent to the SVG object that 'needs spailin' (needs additional information). Thank you @sebastianbenz
