### ISSUE TITLE
Intent-to-implement: Yandex.Metrica and amp-analytics integration

### ISSUE THREAD

**Issue by rifler** [ampproject/amphtml#4463]
Add new block to vendors.js, examples and readme.
Add new event with `timeout` type to fire request once after a specified number of seconds.

**Comment by rudygalfi** [comment]
cc @avimehta

**Comment by avimehta** [comment]
@rifler Does the [`timer`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#timer-trigger-on-timer) type not work for this? You can set the `interval` to number of seconds and `maxTimerLength` to `1 + interval`.

**Comment by rifler** [comment]
The problem is in immediate callback calling.
I can add new parameter to timerSpec (for example `immediate`, defaults to `true`), but i think it's some difficult for webmaster:
```
{
    "timerSpec": {
        "immediate": false,
        "interval": 15,
        "maxTimerLength": 16
    }
}
```
vs
```
{
    "timeoutSpec": {
        "delay": 15
    }
}
```

**Comment by rifler** [comment]
what do you think? we will accept any your decision

**Comment by rudygalfi** [comment]
@avimehta WDYT? I think either of these approaches seems good to me. I think I'm slightly preferring the `immediate` option just because it can be rolled into an existing concept and still makes sense that way. (In other words, it can solve the problem: what if I want a `timer` that doesn't trigger at time=0 but will trigger at many intervals after that?) I do like that `timeout` is semantically more straightforward.

**Comment by avimehta** [comment]
I agree, lets just implement immediate property in timerSpec.
