### ISSUE TITLE
Consider using 3p iframe for <amp-viz-vega>

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#4472]
Related to https://github.com/ampproject/amphtml/issues/3991 and https://github.com/ampproject/amphtml/pull/4461 

Two reasons:
1. d3 and vega scripts have side-effects (they add global vars and who knows what else they do.)
2. The giant 500kb third-party script for vega and d3 can be parallel parsed when in an iframe instead of blocking the main thread.

@dvoytenko @erwinmombay

**Comment by dvoytenko** [comment]
Yes. We can certainly do that. There are some negatives with iframes of course.

**Comment by cramforce** [comment]
The parallel parsing isn't really a thing with iframes. It definitely makes
sense to late load the JS, though, so we avoid compiling during
pre-rendering.

On Aug 12, 2016 1:45 AM, "Dima Voytenko" <notifications@github.com> wrote:

Yes. We can certainly do that. There are some negatives with iframes of
course.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ampproject/amphtml/issues/4472#issuecomment-239326549>,
or mute the thread

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please verify first whether the feature proposal is still relevant.

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
