### ISSUE TITLE
IMG tag attribute longdesc support datauri

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#4515]
IMG tag attribute longdesc support datauri in HTML5 spec

https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L1224

**Comment by Gregable** [comment]
No major modern browsers currently support `longdesc` as far as I can tell. It seems that it's only used for javascript to access and then display something. I could be wrong, this is just from some quick research. Please correct me otherwise.

Considering the `<IMG>`tag is only allowed inside `<noscript>`, it will have no effect.

Normally I'm fine with validating something that has no effect. In the `data:` url case though it's possible that a browser may implement some behavior down the line. It's unclear what behavior that would be since the encoded string is an HTML doc. In particular, I'm worried about javascript in that document.

I don't feel too strongly about this though, since it's all hypothetical. I'm going to close as working as intended, but feel free to ask to reopen.
