### ISSUE TITLE
Loading amp-experiment JS without a amp-experiment config blocks page rendering

### ISSUE THREAD

**Issue by georgecrawford** [ampproject/amphtml#4568]
I'm interested in using `amp-experiment`, however it seems to have some problems.

Using the demo at https://github.com/ampproject/amphtml/blob/master/examples/experiment.amp.html (saved to http://codepen.io/georgecrawford/full/BzbYrk/), I can see two issues:

- adding the `<script async custom-element="amp-experiment" src="https://cdn.ampproject.org/v0/amp-experiment-0.1.js"></script>` script seems to introduce a delay of ~4 seconds to the first render
- the `amp-x-...` classes aren't applied to the body as expected

If this extension is not yet ready for public consumption, perhaps we could get some guidance on what the remaining issues are?

AMP version: 1471018286527

**Comment by rudygalfi** [comment]
amp-experiment is still experimental (the status of extensions is listed on the documentation page in the top area).

I believe the delayed render is due to it being experimental and should go away once it's upgraded to stable status.

In addition, the `amp-x-...` classes not being applied may be due to not enabling the experiment, which you can do with the console, having appended `#development=1` to the page URL:

```
AMP.toggleExperiment('amp-experimental')
```

cc @lannka in case you discover any additional issues.

This extension has been delayed a bit due to another bug fix we're waiting to land. That should happen this week and we expect to move amp-experiment to stable early next week.

**Comment by rudygalfi** [comment]
Note: mistake in my previous console code snippet. Updated the previous post, but email updates may not reflect it.

**Comment by georgecrawford** [comment]
Thanks Rudy - I haven't realised that experimental meant that I needed to enable the experiment experiment! Also good news about the delayed render.

**Comment by rudygalfi** [comment]
That's right: https://github.com/ampproject/amphtml/blob/master/tools/experiments/README.md.

**Comment by jridgewell** [comment]
Note: The render delay is fixed in https://github.com/ampproject/amphtml/pull/4498.

**Comment by georgecrawford** [comment]
Hmm. I just tested this again, and a page with `<script async custom-element="amp-experiment" src="https://cdn.ampproject.org/v0/amp-experiment-0.1.js"></script>` in the head seems still to have the render delay (NB: no `<amp-experiment>` block is actually configured in my page). Is https://github.com/ampproject/amphtml/pull/4498 available in production yet?

**Comment by jridgewell** [comment]
@lannka ^. Not sure how we should handle this case.

**Comment by lannka** [comment]
@georgecrawford unfortunately right now loading the extension JS without really using it with a <amp-experiment> configuration is not a valid use case. Why do you want to do that?

Meantime, @jridgewell we can discuss how to improve this. Probably we should look at the <amp-experiment> rather than the JS when to block the rendering.

**Comment by georgecrawford** [comment]
Don't worry, I can work around it. Just trying to reduce the changes I need to make when actually putting an AB test live. No problem.

**Comment by jridgewell** [comment]
I would say listen for `docReady`. If it happens and there's no `<amp-experiment>`, there's never going to be an experiment, go ahead and resolve the `variant` promise.

**Comment by dvoytenko** [comment]
@jridgewell @lannka agree. i think it's important to allow scripts without uses at this time. We know that authors a lot of times just pad them all in. I think we have a request for AMP Caches to strip away scripts that are not really used when proxying, but that would only part of all impressions.
