### ISSUE TITLE
[Validator] Blacklist usage of __amp_source_origin from link/src/href/input/action

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#4636]
`__amp_source_origin` is used by the runtime to send publishers the source origin of requests the runtime makes.

We'd like to make sure this is never set by the user on attributes like `href`, `src`, `href`, `form.action`.

We'd also like to ban `input.name` value to be `__amp_source_origin`.

**Comment by mkhatib** [comment]
@Gregable let me know if this makes sense and can be done currently in the validator setup.

**Comment by powdercloud** [comment]
I think this is straight forward in the validator, since we have support for AttrSpec.blacklisted_value_regex, so we can blacklist values.  Grepping for value_url in the .protoascii files appears to be an ok way to figure out for which AttrSpecs this value should be blacklisted. Should this extend to urls inside CSS as well?

**Comment by Gregable** [comment]
This should be live everywhere in the validator now.
