### ISSUE TITLE
Support <amp-ad> in some fixed positioned <amp-xyz> elements

### ISSUE THREAD

**Issue by shimonenator** [ampproject/amphtml#4643]
Currently it is possible to include an ad between every few carousel slides, however if you want to give carousel full screen space (in lightbox style, `position: fixed`), the ads will not render. This is a different use case compared to a case where one would stick an ad to the top/bottom of the page to to make it always visible, since the scroll direction is scheduled horizontally in the fixed element.

I would like to request to allow ads in such a corner case.

**Comment by jridgewell** [comment]
This should work with

```html
<amp-lightbox>
  <amp-carousel>
    <amp-ad ...>
  </amp-carousel>
</amp-lightbox>
```

Are you trying to put a `position: fixed` style directly on the `<amp-carousel>`?

**Comment by shimonenator** [comment]
@jridgewell, no, but rather a CSS based lightbox of an always visible carousel. In other words I have a scrollable carousel, where on tap on an image it goes full screen and allows to view images in the larger size, continuing from the same image they tapped on. To prevent full screen version of carousel I need to use `position: fixed;`.

Then every so often there's an ad between the images...

**Comment by jridgewell** [comment]
Right, you need to implement your lightbox with `<amp-lightbox>` elements. You can't put `<amp-ad>`s under a non-[blessed](https://github.com/ampproject/amphtml/blob/master/src/ad-helper.js#L21-L25) fixed-position element.

**Comment by aghassemi** [comment]
@shimonenator, we are also working on a new Lightbox UX which is essentially a lightbox carousel. It allows users to continue to see other media after opening one in the lightbox and will give them a grid view to see thumbnails of other media as well. I think that's very much aligned with what you are trying to do here. It is in very early stages of development however so it could be a few months before it is ready for production. You can see an early prototype here: https://goo.gl/rW73Bw
Follow #4152 for progress on this feature.

**Comment by shimonenator** [comment]
@jridgewell this is exactly why I have requested to "bless" `<amp-carousel>`, since even the new <amp-lightbox> doesn't seem to solve the problem I need to solve. Simply because it solves a different problem with different use-cases. 

I have a few publicly available prototypes to display what I am trying to achieve, am I allowed to post branded content here?

**Comment by aghassemi** [comment]
@shimonenator Is http://goo.gl/ZoJT73 the expected UI you like to have? So if the new lightbox supported multiple slides in the view ( similar to amp-scrollable-carousel) would that fully cover your use-case? 
+ @ericlindley-g

**Comment by shimonenator** [comment]
@aghassemi - yes, that is correct.

I am not sure if I understand what you mean by "ightbox supported multiple slides in the view". Currently enabling lightbox on the gallery causes lightbox to attempt to take control over the gallery slides. I think what would work better in my case is the old lightbox, where the content is displayed in the lightbox, but no new functionality is introduced, and the gallery stays in control of the experience. That is also true for #4642

**Comment by ericlindley-g** [comment]
@shimonenator , could you describe what you mean by "take control" and "stays in control of the experience"? 

I think what @aghassemi meant by his question was this: The new lightbox is currently set up to display slides one at a time, like `<amp-carousel type="slides">`. If, instead, the new lightbox was able to display a continuous strip of slides, like `<amp-carousel type="carousel">` (you can see examples of both [here](https://ampbyexample.com/components/amp-carousel/)) would that address your use-case?

**Comment by shimonenator** [comment]
@ericlindley-g when you implement a gallery, it displays right and left arrows to navigate within the gallery. When you wrap gallery into the new lightbox, it displays its own arrows, and prevents gallery interaction. 

I think the only way in my case to address my use-case is to disable the concept of slides in the lightbox, and allow gallery to continue to be in charge of that. In other words, separate the concerns: lightbox takes care of creating a new context on the Z axis (i.e. a full screen overlay), and  gallery to adapt to the available space and continue the experience using CSS snap-points. Please see my examples linked above to describe the experience.

**Comment by ericlindley-g** [comment]
I think I see—your requirements are as follows:

If you have implemented an existing `<amp-carousel type="carousel">` on your page, you would like to support the following interaction:

* User tap on an individual item in the carousel should open a lightbox containing the items in that carousel

With the following requirements:

* Ads should be supported in this lightbox carousel (this will be supported by the work @aghassemi is doing)
* This lightbox carousel should adapt to the available space (such that the items take up either the full width or height of the lightbox) (this will be supported by the work @aghassemi is doing)
* The items in this lightbox should be scrollable, just like `<amp-carousel type="carousel">`, where swiping results in a continuous scroll, rather than advancing discrete, single-item slides with distinct snap-points.

Is the third bullet above right? [The link to your desired behavior](http://www.cbsnews.com/html/cbsnews/misc/amp/amp-gallery-carousel-2016-08-19.html#gallery__amp-gallery) does this, but your comment on using CSS snap-points makes me wonder if you want a behavior in the lightbox with snap-points for each item, like `<amp-carousel type="slides">`. (The discrete snapping behavior will be supported by the work @aghassemi is doing)

Is all of the above correct (aside from the snap-points clarification)? Are there any additional requests?


If not, the rest seems like an implementation detail. It sounds like you would like the implementation to look like an `<amp-carousel>` wrapped in `<amp-lightbox>`. Another option is for `<amp-lightbox>` to take on some of the responsibilities of `<amp-carousel>` in the lightbox environment, which is what @aghassemi is working on.

**Comment by adelinamart** [comment]
Do we still need to work on this one, or do we have another bug for this?

**Comment by aghassemi** [comment]
#4152 should cover these requirements.
