### ISSUE TITLE
Make available a pre-release version of the validator

### ISSUE THREAD

**Issue by jfsoul** [ampproject/amphtml#4663]
I think it might be beneficial to provide a way to access a pre-release version of the validator (in much the same way as the dev channel works currently).  This way developers can verify that their pages will continue to pass validation after the next release.

While deprecations are initially handled by warnings, these are not always heeded - being able to see when these and other changes will return validation errors ahead of a full release would be very helpful.  The validator command line tool and node module already provide a way to specify alternate validator.js as input - so this would integrate nicely with those.

I would also have thought that it would be good to provide a validator that matches the features currently in pre-release? That way developers can be sure their use of new features is valid - and amp developers can ensure their validation changes are working as expected for dev channel users.

I think I might be missing something and the issue is more complicated that it seems, but as far as I can see - it just makes sense.  Let me know your thoughts.

**Comment by erwinmombay** [comment]
@powdercloud is this possible?

**Comment by powdercloud** [comment]
It doesn't seem hard, the only reason against it is that it's extra work. Maybe the most practical way is to do a rolling release that is reasonably close to the validator sources in Github. So we wouldn't try to synchronize it with the AMP runtime pre-release, but in practice it would be close enough to get a sense of what's going to happen.

**Comment by ericlindley-g** [comment]
@powdercloud Putting "pending triage" for now, but please update the milestone when you have a sense of if and when this would be tackled. Thanks!

**Comment by Gregable** [comment]
We actually now release a canary validator to validator-canary.js which we can use for these kinds of things. When using #development=1, the canary will be loaded if you are opted into using canary runtime. We don't always release ahead of validator.js, but we can when something like this will happen.

Since the mechanism is in place, I'm going to go ahead and close.

**Comment by jfsoul** [comment]
@Gregable That sounds great, thank you.

I wasn't able to see it being used with #development=1 on canary or at https://cdn.ampproject.org/v0/validator-canary.js.  Is it not available yet or am I missing something?

**Comment by Gregable** [comment]
I'm not sure what you are asking. Currently the canary and prod releases are identical.

**Comment by jfsoul** [comment]
My assumption (because you mentioned validator-canary.js) was that in canary and #development=1 the network request for the validation would go to a different location. 

I'm guessing from the confusion that I got that wrong and the same endpoint is used regardless.

**Comment by powdercloud** [comment]
@jfsoul My understanding is that there is a cookie for the dev channel which makes it so that cdn.ampproject.org serves different content. See also here: https://www.ampproject.org/docs/reference/experimental
Like @Gregable mentioned at the moment there's no difference between the validator canary and non canary versions, so you wouldn't be able to tell.
https://cdn.ampproject.org/v0/validator-canary.js is a URL which lets you fetch the canary version even if the cookie isn't set - this can be handy in case you wanted to do a simple wget; but when the cookie is set, then you'll get that version via https://cdn.ampproject.org/v0/validator.js. Again hard to tell when they have the same content, like they do right now. Sorry 'bout the confusion.

**Comment by jfsoul** [comment]
@powdercloud Ok thanks for the clarification, I see my misunderstanding now.

I wasn't expecting 2 things: 

1. https://cdn.ampproject.org/v0/validator.js to potentially serve a different version based on the cookie.  This totally makes sense, I just jumped to the wrong conclusion when validator-canary.js was mentioned!
2. https://cdn.ampproject.org/v0/validator-canary.js to serve a 404 with AMP_CANARY=1 cookie.  I have now turned off the cookie and it works.  This is a bit confusing, can you replicate and is it intentional?

**Comment by Gregable** [comment]
@jfsoul , regarding point 2, I can replicate this. I'm unsure of the reason for this mechanism. @cramforce might know.

**Comment by cramforce** [comment]
@erwinmombay Can fix that :)

The way the diversion with the cookie works is using a glob that likely doesn't match the new file.

**Comment by jridgewell** [comment]
Created b/35325316 to track this internally.
