### ISSUE TITLE
Trying to change object after Object.freeze() 

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#4702]
https://github.com/ampproject/amphtml/blob/master/src/url.js#L121
https://github.com/ampproject/amphtml/blob/master/3p/integration.js#L454

`parentLocation` is from function `parseUrl()`, and we call `Object.freeze()` for it in test mode. But in the meantime we try to set the value for `parentLocation.originValidated`. If we want to freeze an object we shouldn't change it afterwards in our code. It's interesting because tests are passed because of another bug #4701, where we fail to get correct mode thus never freeze() `parentLocation`

Trying to add attributes after `freeze()` only throws error in strictly mode. Failing silently makes debugging super tricky. Is there a way to force it to throw error? If not should we consider returning a clone obj?

**Comment by lannka** [comment]
I will vote for an object clone. 
- so we remove the discrepancy between prod mode and test mode. (right now only test mode freeze the object)
- there is really no good reason why the URL object cannot be mutated. I believe freeze was introduced to protect the cache being modified in test to avoid any side effect caused by one test case to the other.

Before making the change, can you try to count how many times `parseUrl()` is called in our `everything.amp.html`? I think memory should not be a big issue, but better to have a rough idea about the impact.

**Comment by jridgewell** [comment]
I'd vote for leaving the freeze in the test code. It's specifically there to prevent us from screwing things up unintentionally. Instead, we can just clone the object in 3p.

**Comment by lannka** [comment]
@jridgewell changing the production code to work around such a side effect caused by a test helper doesn't sound right to me.

On the other hand, returning a clone without of "freeze" also can `prevent us from screwing things up unintentionally`.

**Comment by zhouyx** [comment]
@lannka  `parseUrl()` is being called around 30 times in `everything.amp.html`.

**Comment by lannka** [comment]
Thanks Yuxuan. 

@cramforce do you think it's a performance concern to clone the cached URL value?

Returning either an immutable or a clone seems both reasonable. Just keep the behavior the same on both prod and test. Returning an immutable saves some memory but is dangerous because it silently ignore any mutation.
