### ISSUE TITLE
amp-access - pingback endpoint is mandatory.  Should it be?

### ISSUE THREAD

**Issue by zygotic99** [ampproject/amphtml#4709]
When using the `amp-access` extension, providing both an `authorization` and a `pingback` endpoint are mandatory.  `login` is not.

We have used `amp-access` to show or hide ads as appropriate for a given user - which in practice means where in the world that user physically is.  This was quick to implement and looks to work really well - but we have had to provide both endpoints.  We don't currently provide a login flow, and if we do in future it isn't clear that login state would affect the presence or not of ads.  We don't need to do any metering.

For this use case, we're not interested in the `pingback` endpoint and don't need it.  We may well find some use for it in the future, though.

Does `pingback` need to be mandatory?  I see the purpose of two distinct endpoints, but given that the extension and runtime don't use the response to the call, surely it should be down to the individual publisher to decide whether to implement `pingback` and use its functionality?  

By needing to implement both we at least double the number of hits to an AA service underlying the use of `amp-access`.

Either way, the documentation in amp-access.md doesn't specify that authorization and pingback endpoints are required and that a login endpoint is not.

Cheers
Steve

**Comment by dvoytenko** [comment]
@zygotic99 You are right, the pingback mainly exists for metering of any kind: trial or product. It also serves to make it very clear that AMP reserves the right to call authorization endpoint before the actual impression, e.g. during prerendering. In other words, the real impression only happens when pingback is sent.

We do realize that in some access scenarios pingback is not really necessary and so it sounds like the case with your system. Could you, however, please confirm whether that's really the case for you?

**Comment by zygotic99** [comment]
Hi @dvoytenko 

Yes - can confirm.  We're happy to make the ad / no ad (amp-access visibility) decision during a prerendering phase (so long as it isn't server-side prerendering that would apply that decision to more than one reader - but pingback wouldn't let us avoid the implications of that anyway).

We need to serve no ads to UK readers to serve ads to users outside the UK, and occasionally need to override that on a per-article or global basis.  The authorization endpoint alone lets us do that.  The option to use pingback is nice, being required to implement it is less so.

Hopefully you could make the prerendering auth request does not denote an article view clear in the docs - perhaps in a preamble before the 'Solution' section and perhaps with a process diagram to illustrate what requests are sent and when?

**Comment by dvoytenko** [comment]
@zygotic99 No, it's client-side prerendering, not server-side. The spec states "This RPC may be called in the prerendering phase and thus it should not be used for meter countdown, since the Reader may never actually see the document.", but I'll see if we can improve on this.

Otherwise, yes, your request is valid and I will enable it.

**Comment by ericlindley-g** [comment]
@dvoytenko  Please update the milestone when you have a sense of when work will start—thanks!

**Comment by zygotic99** [comment]
👍 Thanks Dima, thanks Eric.
