### ISSUE TITLE
Optimize dev's assertEnumValue like assert

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#4731]
We should optimize away `dev().assertEnumValue()` just like we do with `dev().assert()`

**Comment by erwinmombay** [comment]
to not have to write new code the easiest way for me to do this is to change the signature of `assertEnumValue` from `enumObj, s, opt_enumName` to `s, enumObj, opt_enumName` since the current amp pass code just takes the first argument and preserves it to be used in any assignment passed into another call etc.

cc @dvoytenko

**Comment by dvoytenko** [comment]
Yeah, that does sound good.

**Comment by adelinamart** [comment]
@erwinmombay shall we consider closing this one? Thanks

**Comment by rsimha** [comment]
This was done
