### ISSUE TITLE
amp-iframe get resized in current viewport

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#4736]
Check [our nightly build](http://amphtml-nightly.herokuapp.com/test/manual/amp-iframe-resize.amp.html) to reproduce the issue.
Once page loaded, scroll down to the bottom within 2s.
You will see the yellow boxes (amp-iframes) get resized though they are already in viewport.

![ezgif-1792188890](https://cloud.githubusercontent.com/assets/8496897/18021043/a03662a2-6b99-11e6-90c0-cd3b38899508.gif)

**Comment by jridgewell** [comment]
Tracked it down to the [`iniBox` conditional](https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L823).

**Comment by jridgewell** [comment]
@dvoytenko: Why was [`iniBox`](https://github.com/ampproject/amphtml/commit/726bdac973bb7c77b14942dabe145e7e001b69da) added?

**Comment by dvoytenko** [comment]
@jridgewell The problem that this is trying to address is how to resize multiple elements. Say you have two `amp-list` at the bottom. When user scrolls to the bottom - both will trigger load and eventually resize. The order in which the load will complete is random since it depends on the HTTP response and thus the order of resizes is random. Depending which will resize first, the other may be denied - so which one resizes and which one is denied is also random. For this purpose, this code uses the initial measurements of the elements in the document. Notice also (and that's important) these coordinates are compared against the document length, NOT viewport height. I.e. we allow a little more for the elements at the bottom of the document (again, NOT viewport).

**Comment by cramforce** [comment]
Is this still an issue?

**Comment by adelinamart** [comment]
@jridgewell is this still an P0?

**Comment by jridgewell** [comment]
Still an "issue", but it's by design.
