### ISSUE TITLE
Render <amp-analytics> within <amp-ad> for A4A in the parent doc instead of the shadow dom/iframe

### ISSUE THREAD

**Issue by j-e-shaw** [ampproject/amphtml#4770]
## Short description of your issue:

When an A4A ad is returned, it's cut off from the parent doc either by using a shadow DOM or an iframe. This prevents <amp-analytics> tags from using <amp-ad> as the selector.

When rendering, the analytics tag should be separated from the ad content and written outside of the shadow DOM/iframe.
## How do we reproduce the issue?

Serve an A4A with an <amp-analytics> tag with:
      ...
      "visibilitySpec": {
        "selector": "amp-ad",
        "selectionMethod": "closest",
      ...
## What browsers are affected?

All browsers
## Which AMP version is affected?

All

**Comment by avimehta** [comment]
@dvoytenko Currently I use closestByTag to get the closest parent element with a particular tag name. The call does not work across shadowDOM boundary. For example, in a tree like the following, `<amp-ad-body>.__AMP__RESOURCE` is null so `amp-ad-body` can't be used as a selector and `<amp-ad>` is not never found by `element.closest()` call. 

```
<amp-ad>
  #shadowRoot
    <amp-ad-body>
      <amp-analytics>
```

I think the solution is to detect if the element is in shadowDOM and cross the boundary if needed. An alternative solution could be for amp-ad rendering to hoist amp-analytics outside the amp-ad and place it next to it. preference?

**Comment by keithwrightbos** [comment]
Could we not place the amp-analytics tag within the amp-ad element to ensure it knows which amp-ad is the proper one to which it should listen?  It should be able to co-exist with the shadowRoot.

**Comment by tdrl** [comment]
Not if the shadow root is on the `amp-ad` tag itself, as it currently is.  IIUC, shadow roots hide / suppress the DOM tree below their host element.  (Though, I guess I don't know for sure whether those tags would *execute* in their tree, even though it is suppressed for display and other DOM operations.)

**Comment by j-e-shaw** [comment]
Yes, I think it should be within the amp-ad element, either before or after the shadowRoot should be fine.

I'm currently seeing:

<amp-ad...>
  #shadow-root
    <style amp-runtime...
    <style amp-custom...
    <amp-ad-body...>
      ...
      <amp-analytics...>...
    </amp-ad-body>
</amp-ad>

**Comment by dvoytenko** [comment]
It's not that hard to go over the shadow root boundary. We were planning to always use open shadow roots (and even if we didn't, it's still easy enough). We just need to make sure that we don't do this by accident and start triggering wrong analytics requests. But if we keep `amp-analytics` inside the ad, that should not happen, I don't think.

**Comment by avimehta** [comment]
I personally agree with many of the comments in the thread. It would be preferable to cross shadow boundary instead of moving the tag itself. Moving the tag itself will cause confusion in terms of selectors to use. Also, if the ad itself comes with amp-analytics tag and is selecting something within the tag, moving the tag will break this. 

Will send out a PR to enable crossing of shadow boundary.

@tdrl To answer your question, amp-analytics allows people to select an element for viewability measurements. The selection happens using two properties:

```
'selector': <tag name or element Id>
'selectionMethod': <undefined or 'closest' or 'scope'>
```

when the `selectionMethod` is `closest`, the search is limited to the ancestors that satisfy the `selector` property. When the `selectionMethod` is 'scope', only elements within the parent are searched. When a `selectionMethod` is not provided, just the `selector` is used. More details about this are in extensions/amp-analytics/amp-analytics.md. Examples are in examples/analytics.amp.html.

**Comment by j-e-shaw** [comment]
Is shadow DOM supported in all browsers today? Or will the change also cross the friendly-iframe boundary?

**Comment by tdrl** [comment]
Shadow DOM is supported only in Chrome at the moment, AFAIK.  But Safari support is in the works and coming soon.  Right now, I'm seeing about an equal number of "with shadow DOM" and "without shadow DOM" queries from A4A.

And I should have clarified: it's not a _friendly_ iframe in the "render w/o shadow DOM" case.  We load the creative from cache via `<iframe src="original request URL">`, making it a cross-domain iframe.

**Comment by dvoytenko** [comment]
I think shadow dom/iframe is a good question. How does the same analytics tag would work in iframe case? Also, can someone provide a good example of the analytics tag in this case?

**Comment by j-e-shaw** [comment]
I'm having trouble getting a live rendering with Chrome caching but here's roughly how it would look.

```html
<amp-ad...>
  <iframe src="..">
    <html... >
      <head...>... </head>
      <body... >
        ..... <!-- ad content -->
        <amp-analytics>...</amp-analytics>
      </body>
    </html>
  </iframe>
</amp-ad>```

**Comment by ericlindley-g** [comment]
cc/ @rudygalfi

**Comment by dvoytenko** [comment]
@j-e-shaw Ok, the example looks good, but could you elaborate a bit on this and show the minimal `amp-analytics` setup that should go over the boundary to `amp-ad` tag? I'm still trying to get a very good idea, given that an Ad is essentially an independent document, what's the right expectations for event propagation here.

**Comment by j-e-shaw** [comment]
Here's a sample analytics block:

```html
<amp-analytics>
<script type="application/json">
{
  "transport": {"beacon": false, "xhrpost": false},
  "requests": {
    "visibility1": "..."
  },
  "triggers": {
    "continuousVisible": {
      "on": "visible",
      "request": "visibility1",
      "visibilitySpec": {
        "selector": "amp-ad",
        "selectionMethod": "closest",
        "visiblePercentageMin": 50,
        "continuousTimeMin": 1000
      }
    }
  }
}
</script>
</amp-analytics>
```

**Comment by tdrl** [comment]
So if I'm following right, the desire is that we *not* hoist the analytics tag out, regardless of whether the ad is rendered in shadow DOM or iframe, yes?  In that case, is there anything for A4A to do, or is this an AMP/AMP-Analytics wiring question entirely?

**Comment by dvoytenko** [comment]
Yes, I'd definitely like to avoid hoisting out and I'd say this is certainly b/w runtime and analytics and a4a just happens to be a first customer of something like this.

As for the format, I'm a bit concerned about configuring boundary traversal this way b/c:
 1. It invites mistakes where we'd look for the wrongly set selectors in the parent DOM.
 2. It potentially could go too far by trying to traverse even outside of `amp-ad` and getting possibly more information than we'd expect.
 3. I'd like to ensure that a4a documents stand on their own as much as possible as AMP documents, that only happen to be embedded normally.

What I'm wondering if we it'd be better to further borrow into CSS spec and support this use case either as `:root` or `:host` selector.

/cc @cramforce

**Comment by cramforce** [comment]
Is there any path around hoisting when we have to fallback to 3p iframes? I guess that might be out of scope (no pun intended) here.

Direct support for simple forms of `:host` seem like a good idea, but I'm not sure we can really avoid amp-analytics being aware of being inside of A4A and managing is specifically.

**Comment by dvoytenko** [comment]
I think the right thing here is for analytics package to be smart enough and look for 3p intersection events we pass in the `window.context` when `:host` selector is specified.

**Comment by j-e-shaw** [comment]
Is there any timeline on a resolution? Thanks

**Comment by avimehta** [comment]
@dvoytenko created the concept of friendly frames in https://github.com/ampproject/amphtml/pull/4916. I think We'll start using that and enable this.

**Comment by dvoytenko** [comment]
Please ping me for any questions on this. I'm still strongly in favor of a controlled definition that instructs that an analytics tag should work on the host element, such as `:host`.

**Comment by dvoytenko** [comment]
So, to confirm this for everyone, we are starting work on analytics for friendly iframes. The exact details will be confirmed through the implementation, but some important notes:

First: we'll NOT be hoisting analytics elements outside of the iframe's boundary. Instead, analytics service will understand and interpret boundary as we find appropriate. Thus, the overall DOM structure will look like:

```
<amp-ad...>
  <iframe srcdoc="..">
    <html... >
      <head...>... </head>
      <body... >
        ..... <!-- ad content -->
        <amp-analytics>
          {
             "selector": ":host",
             ...
          }
        </amp-analytics>
      </body>
    </html>
  </iframe>
</amp-ad>
```

Second: the boundary transition will most likely be restricted only to the host AMP element, e.g. `amp-ad` in the example above. Whether this will use `:host` selector or something similar is still subject to implementation. I prefer `:host` since it's (a) a CSS standard that's applicable to our case, and (b) it decouples the embed from the parent doc (e.g. it can be placed into `amp-embed` w/o changes).

Third: we will focus on friendly iframes right away. While all of these are applicable to Shadow DOM embeds, it's better to focus on iframe technology as a starting point.

Fourth: we still need to confirm var resolution. Current setup would expose the parent document's URL vars to the ad. For instance, `CANONICAL_URL` is the parent doc's canonical URL, `DOCUMENT_REFERRER` is the parent doc's referrer and `CLIENT_ID` is the parent doc's client ID. This could be totally fine or could be problematic - subject to the implementation: we may restrict access to some of these or completely override others.

**Comment by tdrl** [comment]
Just checking in on the status of this.  I know that the friendly iframe machinery is now in place and (?) solid.  What else needs to be done on this?

**Comment by avimehta** [comment]
Tracking all the items required for this in https://github.com/ampproject/amphtml/issues/5657.

**Comment by rudygalfi** [comment]
Any updates here?

**Comment by dvoytenko** [comment]
This is mostly complete. The remaining items are tracked by separate issues such as #6128 and #7452.
