### ISSUE TITLE
AMP HTML format specification requires schema:headline instead of schema:name

### ISSUE THREAD

**Issue by dbs** [ampproject/amphtml#483]
The AMP HTML format specification at https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md states:

    The following properties of CreativeWork must be present:
    * headline

Please use http://schema.org/name as the required property instead of http://schema.org/headline. schema:name better matches the broad categories of all CreativeWorks, versus the much more article-oriented schema:headline.

Similarly, `alternativeHeadline` is recommended. It would be better to recommend the broader http://schema.org/alternateName.

See also https://github.com/schemaorg/schemaorg/issues/205

**Comment by jvandriel** [comment]
+1

**Comment by danbri** [comment]
When AMP is being used for news articles, I think 'headline', 'alternativeHeadline' are fine. But I agree that for broader applicability the more generic properties would be more appropriate.

**Comment by Aaranged** [comment]
+1 to making "name" rather than "headline" a required property.  As the Dans have noted, "headline" is not appropriate for some content, but "name" is universally applicable to any CreativeWork.

For example it is not uncommon to see web pages (i.e. CreativeWork sub-type WebPage) without anything like an on-page "headline" at all, but any well-formed WebPage has a <title> tag, where that value for <title> is almost always appropriate for the "name" property.

**Comment by jmadler** [comment]
Related to #491

**Comment by jmadler** [comment]
Obsoleted as per #593
