### ISSUE TITLE
Use native srcset when available

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#4849]
We currently always use a srcset polyfill. Could we use native srcset where supported by the platform (widely supported, but the `w` form that AMP uses primarily is less so)?

Apparently the width descriptor is supported in Safari 9.

**Comment by cramforce** [comment]
@dvoytenko Could you explain why we use a polyfill everywhere?

**Comment by dvoytenko** [comment]
@cramforce We can create an experiment and try with native where supported. But there could be couple of differences:

1. Per spec, `w` srcset can only be used in conjunction with `sizes`. I dropped this requirement for a couple of reasons: (a) because we could always do that; (b) I used sizes for other elements and wanted it to be independent.
2. The code setup allows us to lower the DPR for lower networks, though this is not currently used.

**Comment by dvoytenko** [comment]
Let's close for now.
