### ISSUE TITLE
Timeout waiting for render-start/no-content

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#4864]
Now, amp-ad with `render-start` supported ad type only  resolve `layoutCallback` after receiving `render-start`/`no-content` message.  If the message is never received, `layoutCallback` promise will never resolve. We should introduce a timeout for case like this. 
Also with the timeout added, we will have better ideas when to add default fallback for amp-ad.

What should we do in the case of timeout?  Collapse/Display fallback? What if `render-start` message arrives after timeout, should we still try to display ad? 

How can we find out a proper timeout value? Should the value depends on ad type?

@lannka @cramforce @jasti Any thoughts on this?

**Comment by dvoytenko** [comment]
Hmm. I thought we already had a timeout for render-start/no-content? If neither arrives, we should wait until iframe is loaded and then give it another N seconds before resolving/rejecting loading.

**Comment by jasti** [comment]
@dvoytenko  Spoke to @zhouyx and @lannka offline. I'm actively working with UX on https://github.com/ampproject/amphtml/issues/3831 - once we have this, I'm less worried about being aggressive with a timeout since there will be some indication that an "ad is coming..". We decided to start with a sufficiently plenty timeout (8 seconds) before we show the fallback or collapse. Beyond 8 seconds, we will just ignore any responses from the server. More generally, the user is probably moved away by 8 seconds anyway.

**Comment by cramforce** [comment]
It may be surprising, but I think 8 seconds will prove to be not enough. I do, however, think it would be great to do so.

A more conservative approach would be to stop the loading indicator after N seconds, but still show the ad should it decide to come.

**Comment by jasti** [comment]
Okay, the thing we should certainly avoid is to not collapse/show fallback the slot when offscreen just because we think the ad may still be coming but in reality, for e.g., the ad was misconfigured. 

TBH, 8 was arbitrary. Why don't we start with 10 (!) but since @lannka is working on logging roundtrip ad load times, we can adjust as we get more data.

**Comment by zhouyx** [comment]
#4873
