### ISSUE TITLE
amp-analytics substitution variable for user agent

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#5050]
This is a request to provide a user agent substitution variable for amp-analytics.

**Comment by jridgewell** [comment]
Can't this be done with the `user-agent` Header in every request?

**Comment by rudygalfi** [comment]
Ah, yes. :) I had a feeling there was some reason we didn't pursue this, but couldn't remember the precise reason.

**Comment by bodinsamuel** [comment]
Hi,

Sorry to reply to this closed issue.
But I feel like this behaviour is not resolved at all.

At melty.fr, we have +500K amp pages, all of them are cached the more we can.
Meaning a user making a http request to our amp page, will never reached the backend
and thus never tell us its user_agent.
In our amp-analytics we would like to return user_agent, but because only json is allowed, 
this is not possible. 
Isn't is possible to create a substitution variable, mainly for this kind of scenario ?

Thanks a lot

**Comment by jridgewell** [comment]
`<amp-analytics>` simply pings whatever analytics provider you have. Part of that ping is the `User-Agent` HTTP header. There's no need for the variable.

**Comment by bodinsamuel** [comment]
This is not that simple, google analytics (for my case), does not register the full user agent event in the raw data.
And we are forced to store that dat, for each page view, by a third party that assess our analytics (you ll understand that we are not the only sites that will want that info in the future).
I think it does not interfer with the philosophy of amp and does not need cpu power nor complexe code, but I may be mistaken?

Best regards

**Comment by pbazerque** [comment]
I second this demand for the exact same reasons. 
I do see the Browser info in GoogleAnalytics reporting . However I m required to provide the Full UA string as part of our analytics assessment. This info is not provided in the BigQuery Google Analytics stream, which is why all my sites have a CustomDim to carry the UserAgent .

This cannot currently be replicated in AMP , which means lost stats if we switch our traffic to AMP. This is a major showstopper to go beyond pilots.

The closest variable I could find is https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#viewer , but our analytics auditor requires the actual UserAgent

**Comment by rudygalfi** [comment]
@jridgewell @avimehta If certain reporting situations require the UA to be sent explicitly as data rather than as part of the header, then I'm open to reconsidering this.

**Comment by cramforce** [comment]
While, indeed, not needed, this seems like a good case for an external contribution.

**Comment by adelinamart** [comment]
@rudygalfi is this a prioritized FR?

**Comment by rudygalfi** [comment]
#9722 is now covering this.
