### ISSUE TITLE
Dancing video player

### ISSUE THREAD

**Issue by sriramkrish85** [ampproject/amphtml#5137]
Go to abc news page (i searched for "trump") and touch and move the video player

Voila!!!
https://youtu.be/K9ut3xyykUo

**Comment by cramforce** [comment]
It appears ABC news is using an `amp-iframe` based video player, which makes it very unlikely that there is an AMP bug here.

**Comment by cramforce** [comment]
If this is caused by frameborder, maybe we can reach out to ABC to fix is. CC @ericlindley-g

**Comment by aghassemi** [comment]
@cramforce @ericlindley-g  See PR #5143 . It is caused by frameborder but the `box-sizing` change in PR #5143 will fix it. Also we are defaulting frameborder to 0 in PR #5143 (it is a common reset CSS fix since not setting frameborder will pick up the user agent's default CSS). So ABC doesn't need to do anything if merge this fix.

**Comment by cramforce** [comment]
@aghassemi But they can probably deploy CSS changes quicker than us.

**Comment by aghassemi** [comment]
true, meanwhile they can just add frameborder=0 to their video iframe. @ericlindley-g @cramforce

**Comment by ericlindley-g** [comment]
Thanks for flagging this—working on outreach now  cc/ @jmadler

**Comment by aghassemi** [comment]
Closed by #5143
