### ISSUE TITLE
Why is inline <style> required?

### ISSUE THREAD

**Issue by Dutch-Gert-Jan** [ampproject/amphtml#514]
The specification seems to require at least one style tag with inline styling.

From a security point of view, as incorporated in the Content Security Policy standard, including inline css introduces security risks.

Why not allow the opacity declaration to be specified in an external style sheet?

Similarly, why is it required to load the AMP library from cdn.ampproject.org. Again, from a performance point of view, I appreciate the high probability that the client has already cached the 38KB/138KB library, but from a security point of view, it is a liability.

**Comment by cramforce** [comment]
The inline style is not required (the boilerplate is but can easily use hashes in CSP). But external styles are not allowed.

Our CSP is very strict on JS, but does allow inline CSS. We currently assess the risk introduced by that as OK, because documents are also validated.

Requiring cdn.ampproject.org has 2 security sides: Yes, it is a liability, but it is also the only way to know what you get. I think decentralizing that might be an option in the future

**Comment by Meggin** [comment]
Should we add something more to docs on the security side of things?

**Comment by cramforce** [comment]
We should eventually document CSP requirements for embedding amp docs. But
the eng team needs to write those themselves. The audience is relatively
small.
