### ISSUE TITLE
Web Content Accessibility Guidelines (WCAG) 2.0 Level A/AA Compliant

### ISSUE THREAD

**Issue by rlee2015** [ampproject/amphtml#5247]
Is there any plan to meet Web Content Accessibility Guidelines (WCAG) 2.0 Level A/AA?

**Comment by rudygalfi** [comment]
@aghassemi Any sense of where we're at today on WCAG 2.0 Level A/AA compliance?

cc @ericlindley-g

**Comment by aghassemi** [comment]
@rudygalfi Without a careful audit against the WCAG AA spec, it is hard to tell. Aside from a few of our interactive widgets like carousel and sidebar, many of the WCAG rules falls on the page author to comply with. So we can't fully apply WCAG to a framework but certainly can apply it to ampstart.com templates!

Overall based on the A11Y testing I did a few month back, we are mostly in a good shape (minus couple of high priority amp-carousel a11y bugs like https://github.com/ampproject/amphtml/issues/5487)

Also worth considering that since our primary use is in mobile, https://www.w3.org/TR/mobile-accessibility-mapping/ (which clarifies how WCAG applies to mobile) is important to follow.

My approach to accessibility for the AMP core is less about formal compliance and more about meeting real-world a11y needs. Mobile screen-readers are beasts of their own and have their own quirks. So something may be fully compliant with WCAG and behave well on desktop with JAWS but be totally  unusable on iOS with VoiceOver but that's what really matters at the end of the day for most of our users.

**Comment by rudygalfi** [comment]
Thanks for the detailed reply @aghassemi!

I'm going to treat this like a question issue that's gotten an answer and go ahead and close it. However, if there are specific areas where we're falling short of WCAG AA support, then we should definitely track those as separate issues.
