### ISSUE TITLE
amp-mustache data attribute values are stripped

### ISSUE THREAD

**Issue by quarterto** [ampproject/amphtml#5281]
When a mustache is used in the value of a `data-*` attribute, the attribute value is stripped. It seems you're stripping unrecognised attributes, which is reasonable, but I don't think data attributes should come under this. This is preventing us using custom analytics vars in an `amp-list`.

## How do we reproduce the issue?

http://blog.153.io/amp-test-mustache/

Inspect element on the amp-list and observe that `data-vars-foo` has no value, when it should be `test`.

## What browsers are affected?
All browsers

## Which AMP version is affected?
Tested with version `1474310684773`.

**Comment by mkhatib** [comment]
Thanks for filing @quarterto - I don't see any problem with keeping `data-*` attributes. I am looping in some security folks just to make sure this is fine to do. If we get the clear we can then introduce this easily. 

I know other frameworks do something similar (for example Angular 1.X sanitizer) but the best answer I got for stripping out `data-` attributes was because of the use of a whitelist.

cc/ @molnarg and @dvoytenko

**Comment by Gregable** [comment]
The validator already allows the document to contain `data-*` attributes on any tag, so if the presence of these tags is a security risk, the sanitizer isn't the only place where the issue results. The AMP cache similarly does not strip these tags.

**Comment by georgecrawford** [comment]
Thanks @mkhatib and @Gregable. Are we now in a position to 'introduce this easily'? It's preventing us from tracking something quite important. Let us know if you'd like any further information. Thanks!

**Comment by mkhatib** [comment]
Unfortunately, we've found that there might be an issue with some of data attributes - that Mustache and AMP sanitizer treat a bit differently. I am working on figuring out if this pauses any security issues yet.
