### ISSUE TITLE
Refactor last instances of loadPromise import

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#5294]
`amp-analytics/transport.js` and `amp-ad-api-handler.js` both import `loadPromise` refactor this to avoid importing it.

`amp-ad-api-handler` constructor already gets an instance of the base element passed as a first argument.

**Comment by erwinmombay** [comment]
@adelinamart yes, but low priority. should help in reducing file size

**Comment by rsimha-amp** [comment]
I just picked up this bug, and am seeing the following imports of loadPromise in the code base. From reading the original comments in this bug from Sep 2016, it seems like we wanted amp-analytics/transport.js and amp-ad-api-handler.js to no longer import loadPromise, and instead, use the instance from amp-ad-api-handler. It looks like the imports have changed significantly since then, and / or the filenames have changed.

@mkhatib / @erwinmombay, could you take a look at the list below and comment on what is left to do here?


extensions/amp-analytics/0.1/transport.js:import {loadPromise} from '../../../src/event-helper';
extensions/amp-analytics/0.1/test/test-visibility-impl.js:import {loadPromise} from '../../../../src/event-helper';
extensions/amp-analytics/0.1/test/test-transport.js:import {loadPromise} from '../../../../src/event-helper';
extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js:import {loadPromise} from '../../../src/event-helper';
extensions/amp-a4a/0.1/test/test-a4a-integration.js:import {loadPromise} from '../../../../src/event-helper';
extensions/amp-install-serviceworker/0.1/test/test-amp-install-serviceworker.js:import {loadPromise} from '../../../../src/event-helper';
src/service/variable-source.js:import {loadPromise} from '../event-helper';
src/friendly-iframe-embed.js:import {loadPromise} from './event-helper';
src/base-element.js:import {loadPromise} from './event-helper';
test/integration/test-example-validation.js:import {loadPromise} from '../../src/event-helper';
test/functional/test-service.js:import {loadPromise} from '../../src/event-helper';
test/functional/test-3p-environment.js:import {loadPromise} from '../../src/event-helper';
test/functional/test-3p-frame.js:import {loadPromise} from '../../src/event-helper';
test/functional/test-viewport.js:import {loadPromise} from '../../src/event-helper';
test/functional/test-dom.js:import {loadPromise} from '../../src/event-helper';
test/functional/test-friendly-iframe-embed.js:import {loadPromise} from '../../src/event-helper';
test/functional/test-extensions.js:import {loadPromise} from '../../src/event-helper';

**Comment by erwinmombay** [comment]
@rsimha-amp sorry for delay, looking.

**Comment by rsimha-amp** [comment]
Ping.

**Comment by rsimha-amp** [comment]
Assigning to @erwinmombay until we have more context around what's left to do.

**Comment by rsimha-amp** [comment]
Let's write up a GFI based on this.

**Comment by erwinmombay** [comment]
Step by Step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.  (If you [join the AMP Project](https://goo.gl/forms/T65peVtfQfEoDWeD3) we'll be able to assign this issue to you after you've claimed it.)
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] [Sign the Contributor License Agreement](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributor-license-agreement) before creating a Pull Request.  (If you are contributing code on behalf of a corporation start this process as early as possible.)
- [ ] Edit the file [extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js)
- [ ] Change any call to `loadPromise` to `this.baseInstance_.loadPromise`
- [ ] Remove the import of `loadPromise` from the `event-helper` module and make sure there are no references to it anymore (running `gulp lint` should help check on this)
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `Closes Issue #5294` in the description and request a review from @erwinmombay, @rsimha-amp, @danielrozenberg . 
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

**Comment by erwinmombay** [comment]
extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js is the only file that can be optimized from what's left of the loadPromise use. we can only switch the non module call if there is any instance of AMP.BaseElement

**Comment by atl-love** [comment]
Hey, I'll look into this one.

**Comment by erwinmombay** [comment]
thanks @atl-love , please ping me directly if you need anything

**Comment by atl-love** [comment]
Thanks all for your help. Since PR #18396 has been merged and closed, how do I close this issue?

**Comment by adelinamart** [comment]
Thank you for solving this issue. I can close it for now. You can use the following keywords for your PR for closing issues: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by atl-love** [comment]
Will do and thanks!
