### ISSUE TITLE
Springboard Player Placeholder Mismatch Poster Image

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#5327]
Springboard Player dynamically calculated placeholder doesn't match the first poster image when the player loads. 

Typically we'd like the loaded placeholder image to match the first frame or poster of the video player (see youtube examples to see smooth transition between the placeholder image and the actual player). 

Currently there's a clear visual jump between the placeholder and the player. 

@Em-PredragMilosevic Can you investigate if there's a better placeholder image that can be calculated here?

**Comment by adelinamart** [comment]
What's the latest status here? Thanks

**Comment by mkhatib** [comment]
Haven't heard back from @Em-PredragMilosevic - closing this for now.

**Comment by Em-PredragMilosevic** [comment]
I'm sorry, somehow i didn't see this up to now.

On our video platform, placeholder is controled by users.
By default, placeholder is frame taken from the middle of a video, or it can be uploaded by user.
Placeholder used to match first frame, but we had a lot of complaints, because first frame is usually just black screen and users didn't like that.
