### ISSUE TITLE
Support required vars in AMP analytics

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#5386]
I recently saw a case where a Google Analytics user failed to correctly send their account id.

From reading the code, this is currently a silent failure which is very hard to debug.

I think we should introduce a concept of required vars where a trigger fails with a clear error message in the dev tools console if a variable that is absolutely required was not set.

CC @rudygalfi @avimehta

**Comment by rudygalfi** [comment]
Could this just be a vendor config feature? I don't think it makes sense in any other context because there's not an expectation of inherited behavior.

**Comment by cramforce** [comment]
Yeah, I think `vendors.js` would be a good place for this.

**Comment by avimehta** [comment]
ok, here are two possible solutions: 

1 Have a new array in the config that lists all the required variables and then Ensure that none of those are empty(-ish) when final url creation is being done. 

2 Create a variable called `REQUIRED` in url-replacements and set the default value for all required variables to `REQUIRED`. Whenever we try to expand this variable, we'll throw a user error and say that this is required. 

Both of them are easy enough to do. 1. is contained within mp-analytics package whereas 2 results in code changes in platform. 2 might be slightly simpler to read/understand.

**Comment by zhouyx** [comment]
Given we've already supported all the operator macros. We can also introduce a `REQUIRED` macro for this use case. However the error message itself won't be very specific because it can't relate to the original variable name. 

I would vote for approach #1 instead, where we can introduce a requestedVars field;
```
requiredVars: ['fake']
```
The con is that no error will occur if `${fake}` resolve to empty. But I don't expect that to be common.
