### ISSUE TITLE
amp-twitter breaks when amp-3p-iframe-src is defined

### ISSUE THREAD

**Issue by quarterto** [ampproject/amphtml#5400]
amp-twitter uses the base URL specified by the amp-3p-iframe-src meta tag, which I don't think is valid. There should be no reason not to use the Twitter URL for this frame.

**Comment by cramforce** [comment]
@quarterto there is definitely an argument for changing this. It definitely shouldn't "break" in this case, though. The default documented frame content should work just fine for Twitter (and facebook, etc.)

Do you maintain a site where this is actually broken?

**Comment by quarterto** [comment]
> Do you maintain a site where this is actually broken?

Yes, example article where it's broken: http://amp.ft.com/content/b1be7a87-0f52-3159-bf8e-1a72742bf8be (you'll probably get the paywall, but there are [ways around it](https://github.com/Financial-Times/google-amp/blob/master/app.js#L112)). We're using the meta tag to configure `amp-ad` so we can use our own targeting. I'm guessing we could go about that with `src` instead?

**Comment by cramforce** [comment]
@quarterto A few comments on that

- I'd recommend calling draw3p synchronously. You can just slightly rearrange things. Of course, you can still call `done` at the same time you do now.
- As the first line you want to look at `config.type` and only if the type is whatever ad network you use, go into the krux code path. Otherwise just call `done` without doing anything.
- Not all browsers that AMP supports have promises available and AMP does not ship a polyfill into the integration.js file.
- You currently fail to pass these additional args https://github.com/ampproject/amphtml/blob/master/3p/remote.html#L19 which are important security wise.

**Comment by quarterto** [comment]
Thanks for the pointers, I'll look into it. We're [including a polyfill](https://github.com/Financial-Times/google-amp/blob/master/views/ads-iframe.html#L7).

**Comment by cramforce** [comment]
You definitely want to put that polyfill script tag after the inline
script. Otherwise it blocks fetching AMP's iframe JS.
