### ISSUE TITLE
Slide resets when user pause movement midway of a swipe

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#5428]
Repro:
- Open [example on mobile](https://ampbyexample.com/samples_templates/news_article/preview/)
- Scroll down to the slideshow
- Swipe to next image on the carousel but don't finish the swipe and just pause your movement mid-way.
- Notice the slide jumps back to the initial position ignoring the user is still holding that slide.

cc/ @abeck000

**Comment by camelburrito** [comment]
This is a known compromise.

This is because - 
we identify scroll end with a timeout - and this scenario is actually ending scroll

This is technically not feasible for now because we rely on the scrolling and scrollEnd timer for slide switching - but here is what i am thinking we could do to improve

1) check if the current slide is not an embed and then look for touchEnd not being triggered after scroll timeout - this would tell us if the user is stalling in the middle . Also this would certainly make the logic a little more hackier - @mkhatib do you wanna give this a shot ?

**Comment by adelinamart** [comment]
@camelburrito shall we close this? Thanks

**Comment by aghassemi** [comment]
handled in carousel v2 because it uses native scroll-snap in all cases.
