### ISSUE TITLE
amp-audio and amp-video seem unnecessary

### ISSUE THREAD

**Issue by kevinmarks** [ampproject/amphtml#545]
The stated reason for having them is to get control over preloading media. However, the audio and video tags have the built-in ability to add preload=none to them, thereby giving you the control needed. 
Instead of making up new  tags, why not just require this attribute and the width,height ones you want?

**Comment by cramforce** [comment]
Its definitely worth considering. Question is whether we will implement pre-roll ads.

But I can totally see allowing video/audio with preload=none.

That is not really the right semantics, because we may choose to preload after all.

**Comment by kevinmarks** [comment]
You can still choose to preload in js; the point of the declarative version is to tell the browser what to do initially. You could still implement pre-roll ads in code, though if you do it to my videos without asking that is rather rude.

**Comment by cramforce** [comment]
We'd never do it to your videos. You'd do it to your videos :)

**Comment by kevinmarks** [comment]
Got it. This is where we need a playlist element in html

**Comment by dvoytenko** [comment]
A nice thing about custom elements is that we essentially never need to
separately scan DOM looking for them. That saves fair amount of cycles.
Also being able to create the common language for layout, placeholders and
fallback is a benefit. But definitely worth thinking about this.

**Comment by tantek** [comment]
I'd also like to see at least an attempt to "fix" or "improve" existing HTML <audio> and <video> elements (with proposed spec changes) that would allow browsers (or polyfills) to modify their behavior in the performance-enhancing ways that drove the development of amp-audio and amp-video. Optimistically I'd like to see such an attempt to fix or improve <img> as well though that has much more legacy and may be harder (we should still try).

**Comment by cramforce** [comment]
@tantek Lets AMP make potentially wrong decisions for a while before we change a browser!

**Comment by tantek** [comment]
That's a reasonable methodology for sure. Since creating amp-img, amp-audio, amp-video is a non-trivial amount of work, I'm presuming that the AMP team did run into non-trivial (even blocking) problems with working directly with img, audio, video.

I'm advocating for taking the first step - reporting those problems as issues to fix with img, audio, video, and allowing the broader set of smart folks working on browsers across numerous organizations a chance to see if they can come up with ways to fix them. 

We're pretty far from changing the browsers in any particular way for this, however if someone were to come up with a good solution along the lines of providing the more efficient behavior that's been designed into AMP, I believe the browsers have incentive to make those elements work better by default.
