### ISSUE TITLE
AMP JS runtime (v0.js) is no longer in the repo

### ISSUE THREAD

**Issue by JoeArizona** [ampproject/amphtml#5460]
The AMP JS runtime (v0.js) used to be in the repo, but is no longer. Can we get it back? We can grab it by browsing or CURLing to https://cdn.ampproject.org/v0.js, but it would be very helpful to be able to track official changes to the runtime in the repo.

**Comment by rudygalfi** [comment]
You can track release info here: https://github.com/ampproject/amphtml/releases

I'm not sure about the v0.js change. /to @erwinmombay @cramforce

**Comment by cramforce** [comment]
Nothing in this direction changed. As @rudygalfi pointed out one can follow the release page for changes. It certainly doesn't make sense to check the actual code into GitHub since it changes with every commit.

I assume https://github.com/ampproject/amphtml/releases is the right answer here :)

**Comment by erwinmombay** [comment]
our changelog's are slightly confusing right now since a "release" can be a union of multiple versions. I plan to make it so that the latest version will have the changelog of everything that hasn't been released yet this makes it so that you only need to look at 1 pre-release version instead of all pre-release versions.

https://github.com/ampproject/amphtml/issues/5293

**Comment by cramforce** [comment]
@erwinmombay Neat! Also consider adding `<summary>` and `<details>` to the notes :)

**Comment by erwinmombay** [comment]
@cramforce will do!
