### ISSUE TITLE
let amp-ad expose `isRenderStartImplemented` through attribute

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#5465]
we have different behaviors for ad who support `render-start` or not. This is not a problem for the ad itself since it has access to adConfig file. 
However it would be nice to expose this property to some ad containers (like sticky-ad) through attribute. One thing to note is that setting this attribute in `#layoutCallback` is too late, this need to be done no later than amp-ad `#buildCallback`. Since both 3P ad and A4A need this value, I am proposing to set the `isRenderStartImplemented` attribute during `amp-ad`  `#upgradeCallback`.

Ideas? 
@lannka @jridgewell 

part of #5432 blocks #5456

**Comment by lannka** [comment]
It sounds good to me.

But if possible, I would avoid these kind of hassle by not supporting such a requirement. I think external widgets should not behave differently depending on the implementation detail about the amp-ad (w/ or w/o render-start), although the external widget here is a parent that owning the amp-ad.

e.g., we can have a same ad loading experience no matter of w/ or w/o render-start implemented:
show a white background and close button when amp-ad has laid out.

* if render-start is implemented, the creative and white background will come together.
* if render-start is not implemented, the white background will be shown in 1s, no matter the creative is shown or not.

@jasti I know you and zhouyx@ had a related conversation, but what do you think about this? Does it worth the cost here?

**Comment by jasti** [comment]
@lannka As long as we don't show the the white background (and close button) before the creative itself for those networks that have render-start implemented, we are good. (Showing the placeholder before the ad increases perceived latency)
Implementation details up to y'all.

**Comment by zhouyx** [comment]
@lannka you mean get rid of transparent overlay in both cases?

**Comment by lannka** [comment]
@jasti there is no way we can prevent showing a white background before the displaying creative. even with the change zhouyx@ is working on.

I just wanted to point out that this is complicating the logic but making little impact since only a small amount of ad traffic doesn't have render-start implemented. We should probably just work on other stuff to move more ad networks to implement render-start API.

On the other hand, I'm not that convinced the different UI treatment is an improvement, it actually makes the UI inconsistent.

**Comment by jasti** [comment]
@lannka sorry, I misunderstood your original question. As part of #5432, the only change I'm suggesting is to remove the transparent overlay for those that have implemented render-start. According to @zhouyx  it's impossible to paint the close button the same time as the ad, for those that don't have render-start implemented. (Right @zhouyx ?)
For your second point - if > 80% of ad view benefit from the change, I think it's ok to be inconsistent for a tiny volume - especially if we are moving all ad networks towards implementing render-start.

**Comment by zhouyx** [comment]
@jasti right, it's impossible to do anything the "same time" as the ad, for those that don't have render-start implemented because we have no idea on that "same time" point. I think what @lannka is suggesting here is to get rid of the inconsistent for both cases. 

It would be super easy to just remove the transparent overlay, however to keep it for ads that don't support render-start while removing it for ads that support render-start is hard.  I also start to doubt whether it's worth it to complicate our logic for very few ads that don't support render-start.

**Comment by lannka** [comment]
@jasti I meant only < 20% of the ad view will be affected by the change. And the number is getting smaller as we're moving more ad networks to render-start. On the other hand, for those "<20%" ad view, I'm not sure the change is really an improvement, because it's inconsistent with the 80% (having such a animated transparent layer thing).

I know the loading experience isn't good for the 20%. But isn't it the reason and incentive we want to move them over to render-start? I don't really see the need to do such a patch that does not solve the problem but rather complicate things.

**Comment by jasti** [comment]
@lannka @zhouyx See your point. Let's remove the transparent overlay in both cases then.

**Comment by zhouyx** [comment]
Cool @jasti just to confirm. In order not to complicate things, we are also removing the 1 sec delay for ad that doesn't support `render-start`.

**Comment by jasti** [comment]
Yes, would love to see a QA implementation. Thanks!

**Comment by zhouyx** [comment]
PR is lgtmed. I will send you the testing url, and merge that pr after your approval @jasti

**Comment by zhouyx** [comment]
#5456 merged.

**Comment by zhouyx** [comment]
close this issue as we decide this feature is not needed any more
