### ISSUE TITLE
Docs: broken link in published docs vs. GitHub .md files

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#5555]
At https://www.ampproject.org/docs/reference/components/amp-iframe, the link under

> They are sandboxed by default. [Details](https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/#sandbox)

is broken. It points to https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/#sandbox rather than https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md#sandbox

While the fix would be trivial to implement, I wanted to create this issue in case the problem is more widespread for anchor links of this type.

**Comment by jridgewell** [comment]
A PR would be lovely. 😄

/to @braraujo.

**Comment by bpaduch** [comment]
Yes, it turns out this is a more widespread issue for any anchor links created with `#anchorname` (another example in [amp-analytics](https://www.ampproject.org/docs/reference/components/amp-analytics) for the ["analytics vendors"](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/#analytics-vendors) link).  This is related to how urls from relative github urls are created in [import_docs.js](https://github.com/ampproject/docs/blob/master/scripts/import_docs.js).  

I'm no expert on the script but I can try and play with the regex's unless @pbakaus can perform a fix?

**Comment by jridgewell** [comment]
Oo, thank you for pointing me to the right direction. https://github.com/ampproject/docs/pull/225

**Comment by jridgewell** [comment]
Fixed by https://github.com/ampproject/docs/pull/225.
