### ISSUE TITLE
Delayed rendering for AMP extensions. 

### ISSUE THREAD

**Issue by pranjal-jain** [ampproject/amphtml#5573]
These are the versions of [Housing's](https://housing.com) project details page (please emulate in mobile else you'll get 404).
[Normal Page](https://housing.com/in/buy/projects/page/57) 
[AMP with the amp-style boilerplate](https://housing.com/amp/projects/page/57) 
[AMP without amp-style boilerplate](https://housing.com/amp/projects/page/57?hidestyle=true)

We ran webpage tests on our normal page as well as our AMP page and we noticed that in our AMP page, the style-amp boilerplate is blocking the first paint altogether. 
Then we removed this boilerplate and ran the webpage tests. The reports of the test when tested from: Dulles, VA - Chrome - Emulated Nexus 5 - 3G:

[Normal Page](https://www.webpagetest.org/video/compare.php?tests=161012_ZB_3E5Y-r%3A1-c%3A0&thumbSize=200&ival=100&end=visual) (First Paint - 4.1s)
[AMP Page URL](https://www.webpagetest.org/video/compare.php?tests=161012_SM_3E8Y-r%3A1-c%3A0&thumbSize=200&ival=100&end=visual) (First Paint - 4.9s)
[AMP Page without amp-style boilerplate](https://www.webpagetest.org/video/compare.php?tests=161012_06_3E8Z-r%3A1-c%3A0&thumbSize=200&ival=100&end=visual) (First Paint - 3.8s)

**Comment by jridgewell** [comment]
No idea who to give this to, so @rudygalfi gets it. Maybe @cramforce?

**Comment by cramforce** [comment]
As you can see in your screenshots without the boilerplate, this results in a FOUC, because AMP didn't get to run yet.

One thing that is interesting (and that you might want to look into) is that your ServiceWorker starts pre-caching items right away. Maybe we should consider to wait a bit with the installation to get it out of the critical path.

On the good news

- when people come from Google search they always have AMP in cache (because it gets loaded during the Search load) and that makes the graph look very different
- for the Google AMP Cache we may be able to get rid of the boilerplate in the future.
- and then we might also provide a way to get rid of it for origin hosted AMP pages.

**Comment by rudygalfi** [comment]
@cramforce Can you update on status of this issue? Did #5573 solve this? Should this stay open?

**Comment by cramforce** [comment]
We have a project going that will remove the boilerplate for pages served from cache. I think we can close this.
