### ISSUE TITLE
Relax the requirement for loading amp-mustache with amp-form

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#5619]
I'm working on a [very simple `<amp-form>` sample](https://github.com/ampproject/amphtml/issues/5617#issuecomment-253914401) that [doesn't use Mustache templates at all](https://github.com/dandv/amp-by-example/blob/988b53be02215a36a3eb024779fa218baba8bfe7/src/30_Advanced/favorite.html#L91-L98).

However, when the form is submitted, I get this message in the console if I don't load `amp-mustache-0.1.js`:

> Error: Template must be declared for template as `<script custom-template=amp-mustache>`

(I've tried removing `type="amp-mustache"` but I get `Type must be specified: template​​​`)

**Comment by mkhatib** [comment]
Thanks for filing @dandv will look into getting this in soon

**Comment by mkhatib** [comment]
So thinking of this some more, you can already use non-template responses to show content using the classes we add on forms `.amp-form-submit-success`. 

Though doing it through the `[submit-success]` might provide a better accessible responses. Looking into allowing this.

**Comment by aghassemi** [comment]
Copying some comments from #8098:

"Currently `<div submit-success>` and `<div submit-error>` are required to have a template tag as thet child. This should become optional. There are cases where a static success or message is enough and there is no need to load amp-mustache for those cases."

**Comment by cvializ** [comment]
@aghassemi I agree that `amp-mustache` should be optional. However, I think that allowing AMP authors to put arbitrary DOM in place of a template might not be what we want, since that content will load on page-load, where a template's content does not (as mentioned in [this doc](https://docs.google.com/document/d/1q-5MPQHnOHLF_uL7lQsGZdzuBgrPTkCy2PdRP-YCbOw/edit#) linked from [template-impl.js](https://github.com/cvializ/amphtml/blob/master/src/service/template-impl.js#L25))

Are there downsides to adding a bare-bones `amp-literal` template class into core or `amp-form`? It would just render DOM as entered in the template tag. What do you think of that approach?

**Comment by aghassemi** [comment]
@cvializ I don't think it's worth increasing `v0.js` size (given we are constantly trying to reduce its size) for this. I don't really expect the size of "content" to be much more than the actual HTML code.

On a related note, we need to ensure that if they put an `amp-component` there, it will get layedout properly ( e.g. `amp-img` actually loads when the message is displayed )
