### ISSUE TITLE
Amp-accordion - Ability to tag a section as collapsed by default.

### ISSUE THREAD

**Issue by yavorm** [ampproject/amphtml#5734]
We'd like to use an amp-accordion for an expandable list of filtration options on top of a page which contains a list of items. Our accordion has a single section which does not have the `expanded` attribute.

The problem is that while clicking from one page to another, sometimes the accordion will be displayed expanded on page load (while other times it's collapsed).

Please add a `collapsed` attribute or alternative way to force a single-section accordion to default to the collapsed stage on page load.

**Comment by ericlindley-g** [comment]
Thanks for the request, @yavorm. Currently the accordion stores state, so that if you open it, then navigate to another page, then navigate back, the accordion will still be open. https://github.com/ampproject/amphtml/issues/3813 has a request to not store this state, so it is always either expanded (if you have included the `expanded` attribute) or collapsed (if not). Would this solve your problem, or could there be another bug?

**Comment by jridgewell** [comment]
This is due to local storage persisting, right?

**Comment by camelburrito** [comment]
session storage.

**Comment by yavorm** [comment]
Yes, that is correct

**Comment by yavorm** [comment]
Closing this bug, thank you for the explanation @ericlindley-g
