### ISSUE TITLE
First item in carousel does not finish loading

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#5803]
First item of carousel does not finish loading if carousel is not initially visible.
I have tried this with `<amp-youtube>` and `<amp-instagram>`. 

To repro:
- Go to: https://output.jsbin.com/fubuka/quiet
- Scroll down to see the carousel
- Note the instagram image in carousel still have the amp dot-dot-dot animation. It never goes away.
- Notethe instagram image outside of carousel load fine. 

Happens in  prod, canary and master.

/to @camelburrito

**Comment by camelburrito** [comment]
@jridgewell  - can you help take a look. I think layout callback is not being called for the iframe (instagram) the first time

![screen shot 2016-10-25 at 11 22 27 am](https://cloud.githubusercontent.com/assets/1037311/19698750/677d4206-9aa5-11e6-8f7a-37754144d9a5.png)

**Comment by camelburrito** [comment]
Here is what is going on - 

Layout callback for slides is being called even when it is outside the viewport (expected)

Which in turn calls the layout callback of its first slide - which happens to be instagram - but instagram says - do not render me outside the viewport.

Ideally run time should see if an element is owned and should layout regardless of the setting if the layoutCallback is being triggered by the element's owner

CC @dvoytenko

**Comment by dvoytenko** [comment]
I believe @jridgewell fixed this. No? We allow owned elements to override "outside viewport" restriction.

**Comment by jridgewell** [comment]
I only overrode the restriction for the x-axis (the element may be entirely to the left or right of the viewport). The y-axis restriction still applies.

This is being caused (I think, there's so many damn carousel classes I can't keep track) because:

- The carousel receives `#layoutCallback` when 3 viewports out of screen (normal)
  - The carousel tells the first item to preload
    - The first item checks if it should preload, says nope, I don't render outside the visible y-axis of the viewport
  - The carousel never tells the element to preload again when scrolled into view

The element does eventually load if you go to the next slide then go back.

**Comment by camelburrito** [comment]
yup :) isn't that what i wrote above :)

**Comment by jridgewell** [comment]
Also, this behavior probably never worked, even before my change in https://github.com/ampproject/amphtml/pull/5583. 😞

**Comment by camelburrito** [comment]
right now this happens only if the first slide is instagram or youtube hence this might not have been notice.

**Comment by jridgewell** [comment]
Ha, I didn't read yours. 😛

**Comment by jridgewell** [comment]
Ok, so I see two possible solutions:

- We ignore `#rendersOutsideViewport` for owned elements. The owner says to prerender, do it.
  - Easy
  - Expensive, since `<amp-instagram>` and `<amp-youtube>` are heavy elements.
  - Owner doesn't really know best here, it just doesn't get the signals that maybe you should try prerendering again.
- We send the owner a signal when we encounter an `NOT_LAID_OUT` element.
  - Harder
  - Allows the owner to try prerendering again if needed
  - Cheaper, since we won't render expensive elements unless they know they should

@dvoytenko?

**Comment by aghassemi** [comment]
Note that Carousel is already breaking the `rendersOutsideViewport` rules on the x-axis by always pre-rendeing (+/-) 1 slide ignoring the child's `rendersOutsideViewport`  value. (e.g. eventhough `<amp-instagram>` says never render me outside of viewport, it is getting rendered when it is invisible but next in line in the slides queue) so option 1 may not be too bad for now.

**Comment by jridgewell** [comment]
Fixed by #5814.
