### ISSUE TITLE
form action attribute is invalid for method=POST; uncaught console log error. log.js:248

### ISSUE THREAD

**Issue by shakaran** [ampproject/amphtml#5877]
My AMP page validates, but on load has an uncaught error in the JavaScript console saying:

```
Uncaught Error: form action attribute is invalid for method=POST: form#register​​​
    at xa.f.assert (https://cdn.ampproject.org/v0.js:11:342)
    at HTMLDocument.Hf (https://cdn.ampproject.org/v0.js:164:50)
```

I don't undertand the error since the forms action could be used in method=POST (as far I did for years in HTML)
## How do we reproduce the issue?

When visiting http://iberopistacho.com/registro this error should appear on load in the Javascript console.

I'm running ChromeOS Version 54.0.2840.59 (64-bit)
Powered by AMP ⚡ HTML – Version 1477334765771
and using https://cdn.ampproject.org/v0.js

**Comment by devSamuel** [comment]
same for me in safari and chrome version 2.0

**Comment by mkhatib** [comment]
Hey @shakaran the page should not validate, are you seeing the page passing validation on https://validator.ampproject.org ? or which tool?

This is working as intended. As [per the docs](https://github.com/ampproject/amphtml/blob/master/extensions/amp-form/amp-form.md#attributes), `action` is an invalid attribute for `POST`.  Read some more on [security considerations](https://github.com/ampproject/amphtml/blob/master/extensions/amp-form/amp-form.md#security-considerations).

This decision was made for security reasons, so we only allow xhr-POST that we can provide a gurantee of security if publishers follow the [AMP CORS spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md).

Please let me know which validation tool were you using where you saw this passing validation, it might be still being deployed.

**Comment by mkhatib** [comment]
btw, both https://validator.ampproject.org and #development=1 validation seem to throw a validation error for this. Are you using one of these or something else?

**Comment by shakaran** [comment]
@mkhatib well, validate or not, it doesn't should throw a exception and break totally my submit button form. I mean, why is not showing a normal error console instead a exception breaking all the javascript flow?

Also, if action is invalid attribute in a POST, how I should rewrite this, since it is not a XHR request?

And this is build using Symfony and twig template as:

    {{ form_start(form, { 'attr': {'class': 'form_settings form-horizontal col-xs-12', 'id': 'register'}}) }}

in PHP I have:

```
$form = $this->createForm(RegisterType::class, NULL, array(
    			'action' => $this->generateUrl('ibero_pistacho_register_es'),
    			'method' => 'POST',
    	)
    	);
```

So which I should edit? remove the action="/registro"? how I indicate another diferrent path to post since I cannot use the action?

**Comment by mkhatib** [comment]
I am not familiar with these frameworks. But non-xhr POST is invalid in AMP.  

You'd have to try to figure out a way to do this through XHR through `action-xhr` attribute. 

As for the exception vs error it might be possible to relax this, I don't see any reason why not.

**Comment by afiugud** [comment]
Hi there! I'm sorry about my english
Ok, I agree that more security is better, but, why needed to marking images or videos or wherever with special tags and not necesary for mark forms tag? I don't want to match my forms tag so why AMP manage it? Last days I'm changing my entire projects with xhr-post forms and only because all post methods break submit events. I'm using AMP on third party CMS and not only on SPA projects. I think this rule are broken the modularity of project. Sincerely I think is not a good idea. Other way making a simple submit with JS are broken your reason of security and does not matter form tag have post method or xhr-action or whatever.
I'm sorry about my horrible english >_<
En español: Me parece bien las razones de seguridad, pero ¿por qué la necesidad de marcar imágenes o vídeos o lo que sea con etiquetado especial y no hacerlo con los formularios? Porque no quiero incluir ese marcado en mis formularios así que, ¿por qué AMP me obliga a hacerlo? Los últimos días me ha tocado realizar cambios en todos los proyectos para que los envíos fuesen por AJAX porque el evento "submit" rompía el código. Uso AMP en CMS y aplicaciones de terceros, no sólo en aplicaciones SPA. Creo que esta regla rompe la modularidad del proyecto y sinceramente creo que no es una idea muy acertada. De cualquier modo, un simple línea de código en javascript realizando el submit del formulario se carga toda esa idea de seguridad (cosa que se puede conseguir desde la consola del navegador, es absurdo) y da igual si el formulario tiene o no el atriburo xhr-action si es por método post o si tiene target o no...
Remato mi alegato con un pensamiento: mucha gente igual quiere usar AMP de forma parcial, tal y cómo creo que se concibió este proyecto, pero ahora nos damos cuenta de que no es tan parcial y que perdemos el control de cómo queremos gestionar la seguridad de nuestra aplicación (sea buena, moderada o mala). Yo ni siquiera he incluido la librería para formularios tal y cómo viene en la documentación, pero aún así, entra en log.js y "peta" estrepitosamente. Un saludo y suerte con el proyecto, pero creo que yo me bajo.

**Comment by shakaran** [comment]
@mkhatib sorry, but force that all our forms would be XHR is a bad idea, as suggested by @afiugud a simple way to skip this is from console or via JS submit.

I have that website more than 4 days break it, any client could register because this error, so that means losses to my client. I will have to remove fully AMP, since if it is forcing me to rewrite all the forms, it is not a good deal to me.

For me it is urgent that you don't throw that exception and only you show a error, that would be a easy fix of 1-2 lines of code and release to production, but I cannot wait weeks until you fix that, so I am removing fully AMP from my sites, at least until you relax this condition

**Comment by AdamDurzynski** [comment]
I still have the same problem with 1 of my 4 wordpress blogs.

In error console is red info:

ncaught Error: form action attribute is invalid for method=POST: form#commentform​​​
    at ia.f.assert (https://cdn.ampproject.org/v0.js:6:342)
    at HTMLDocument.Gf (https://cdn.ampproject.org/v0.js:166:50)f.assert @ log.js:243Gf @ document-submit.js:73

It is strange, bacause on 3 others wordpress blog with Your plugin everythigs works fine.

**Comment by nragan34** [comment]
I am reproducing the same error 

log.js:251 [form] action attribute is invalid for method=POST: form.wrapper.i-amphtml-form.amp-form-dirty


Using Flask
