### ISSUE TITLE
[question] Governance model for new features like new third-party content or ads?

### ISSUE THREAD

**Issue by soulgalore** [ampproject/amphtml#589]
One thing I think is lacking is documenting the governance model for new features. It me mostly guessing how it would work, but I think it would be great to have documented steps what needs to be done for getting new features included.

Best
Peter

**Comment by jmadler** [comment]
There's kind of two things here:  the minimum requirements a service must meet in order to contribute an extension to AMP, and the governance model for the AMP project itself.

I want the broader governance model conversation to happen on the AMP mailing list (which is yet to be created) so that a broader group of people can be involved in its decision making.

As for minimum notability requirements, I think ultimately that should be decided in that same way, but I am ok with developing a tentative guideline for now to allow third-party services to integrate with AMP.

So let's start that conversation off:  I was thinking that the [notability guidelines](https://en.wikipedia.org/wiki/Wikipedia:Notability) of the English Wikipedia could be a good litmus test.

**Comment by soulgalore** [comment]
> I want the broader governance model conversation to happen on the AMP mailing list (which is yet to be created) so that a broader group of people can be involved in its decision making.

cool! would it be possible to say something about it, how you think? thinking about tomorrow and http://velocityconf.com/devops-web-performance-ny-2015/public/schedule/detail/46967

**Comment by cramforce** [comment]
For features in general, we roughly follow the Chromium team's rules:

Usually after some less formal discussion, you create an "Intent to implement" bug like https://github.com/ampproject/amphtml/issues/571

This requires 2 LGTMs from project committers at which point patches with the implementation can be accepted.

As @jmadler points out there are more specific requirements on things like new embeds in terms of notability. Since in this case there is always `amp-iframe` as a fallback urgency isn't very high to have first class support for every last thing on the internet.

Did you read https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md and have specific questions regarding it. We know it isn't sufficient yet, but I was just wondering if you had specific questions.
