### ISSUE TITLE
[amp-ad] Shifted amp-ad on Android 4.2.2 system browsers

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#5958]
Same error has been seen on desktop Safari 7 as well. 

![screenshot_20161101-154454](https://cloud.githubusercontent.com/assets/8496897/19910444/3d7e8302-a04a-11e6-882c-1cb4fcaf1d3a.png)

**Comment by lannka** [comment]
It only happens to doubleclick ads.

@tdrl @keithwrightbos can it caused by the centering doubleclick is doing? 

![screenshot_20161101-161611](https://cloud.githubusercontent.com/assets/8496897/19911090/8a0cfcea-a04e-11e6-9513-461054222998.png)

**Comment by tdrl** [comment]
Do you have an AMP version number and repro page for this?  (Looks like you could repro on the a4a.amp.html example page?)

**Comment by tdrl** [comment]
@glevitzky -- Trying to assign you to this Issue, but the assignment box isn't allowing me to. :-P

**Comment by glevitzky** [comment]
Are there any more details on how to reproduce this? I'm not seeing anything unusual in a4a.amp.html.

**Comment by glevitzky** [comment]
Okay, I was able to reproduce using my personal phone's default browser. Now to figure out a way how to debug this...

**Comment by lannka** [comment]
Reproducible on `ads.amp.html`. You should be able to see it on desktop Safari 6 and 7 as well. We used [Saucelabs](https://saucelabs.com/) to have older version of Safari (remember to turn on developer option in Safari preference).

For Android 4.2.2 system browser, I honestly don't know how to debug :-(. Chrome cannot attach to it.

@cramforce do we need to whitelist @glevitzky so that we can assign bug to him?

**Comment by cramforce** [comment]
@lannka I invited them.

**Comment by lannka** [comment]
@glevitzky not sure if you need to accept any invitation. i still can't assign to you yet.

**Comment by glevitzky** [comment]
Is this something I would get via email or github? I don't see anything in either.

**Comment by jridgewell** [comment]
You would have to join the [ampproject](https://github.com/ampproject). Go there, you should see a notification at the top of the page.

**Comment by glevitzky** [comment]
Ah, thanks! Invitation accepted.

**Comment by glevitzky** [comment]
Alright, after spending most of the day rewiring things so that I can test my local code changes in a locally running instance of Android, I can confirm that the issue is in fact the ad centering code that was added as part of the multi-size feature.

As for the solution, should we do some sort of carve out by user agent? I.e., if we detect that the user is on an Android system browser, don't center the ad? And likewise for desktop Safari 7? I'm not really sure what else could be done.

**Comment by lannka** [comment]
So it's this piece of code? Do you know which one is badly supported?

```
  const container = global.document.querySelector('#c');
  container.style.top = '50%';
  container.style.left = '50%';
  container.style.bottom = '';
  container.style.right = '';
  container.style.transform = 'translate(-50%, -50%)';
```

BTW, can you teach me how did you get to the browser console of such an Android system browser. :-)

**Comment by cramforce** [comment]
I'm sure our CSS experts can get the desired result to work on older
Androids.

**Comment by glevitzky** [comment]
@lannka That's the right piece of code. I don't have a comprehensive list of systems where this is broken, as I only tested on Android.

To test my changes I ran an Android instance through: /google/data/ro/teams/mobile_eng_prod/crow/crow.par

I also had to make some modifications for how script source URLs are generated, which you can find on my test branch here: https://github.com/google/amphtml/tree/ad-shift. Afterward I could use my machine's FQDN to hit my local gulp server through the Android instance.

@cramforce I will try to fix the CSS for Android, but if someone more knowledgeable in CSS wants to give me some pointers, that would be great.

**Comment by glevitzky** [comment]
Someone with more experience with CSS please correct me if I'm wrong. 

It seems like the issue is that CSS 'transform' property is not supported for Chrome versions 31 and below (the Android system web browser is apparently built on top of Chrome 30 according to useragent data), nor is it supported by Safari version 8 or below. Source: http://www.w3schools.com/cssref/css3_pr_transform.asp. 

If that's the case, then the best bet is to find some alternative CSS that is supported in those versions, or, failing that, to carve out those older browser versions. For the latter, the worst case scenario would be creatives not being centered within multi-size ads, which currently are a very small fraction of total ads.

**Comment by lannka** [comment]
Great investigation.

It sounds reasonable to fail for older browser if no good CSS alternative available.

**Comment by cramforce** [comment]
So, just add
`container.style.transform = container.style.webkitTransform = 'translate(-50%, -50%)';`
?

**Comment by glevitzky** [comment]
That appears to work, at least for Android. Will confirm and put out a PR shortly.

**Comment by jridgewell** [comment]
There's going to be other places affected by this. We should make a `centerInParent` helper function.

**Comment by glevitzky** [comment]
Any suggestion as to where that function should live?

**Comment by jridgewell** [comment]
Probably the `style.js` module.

**Comment by jridgewell** [comment]
Or, or we could use the `getVendorJsPropertyName` in there to get the right name.

**Comment by cramforce** [comment]
Yes, much better!

**Comment by cramforce** [comment]
Just use setStyle (better anyway) and it magically starts working.
