### ISSUE TITLE
Fixed layer appears on top of sidebar in google viewer

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#6045]
AMP page https://cdn.relaymedia.com/amp/www.civilbeat.org/2016/11/chang-raises-spends-3-times-more-than-slom-in-senate-race/

Should look like this when `amp-sidebar` is open

![image](https://cloud.githubusercontent.com/assets/524856/20033574/b731b4ee-a360-11e6-8d4e-424ec3df0449.png)

However in the Google search results viewer it looks like this

![image](https://cloud.githubusercontent.com/assets/524856/20033579/cc5b32a0-a360-11e6-8190-654ea3b5e487.png)

With the header bar on top of the `amp-sidebar` - the offending code seems to be element level css on the header and only happens on iPhone (Chrome and Safari including emulation)

```
element.style {
    pointer-events: initial;
    z-index: 10999;
    top: calc(54px);
}
```

**Comment by camelburrito** [comment]
since sidebar gets added to the fixed layer via the component, the fixed layer does not prefix its z-index with 10* - hence this issue. @dvoytenko , I think we would need to provide max-z-index guidelines for the page or some how scan through all possible z-index on the components and determine the prefix based on that. (or make the prefix 100 or make sidebar's z-index 999 instead of 9999)

@jpettitt - thanks for filing! - temporary work around is to make the z-index: 99 on the element , this should solve this for now (in fact since it is already position:fixed you might not have to do a z-index - though i'm not sure if you have other pages that might need the z-index.)

**Comment by wouter2203** [comment]
@camelburrito Could you explain the temporary work around? Since `99 + 10000 = 10099` which means the element will still be higher than the side bar with a `z-index` of `9999`.

**Comment by camelburrito** [comment]
@wouter2203 - you are correct - i thought fixed layer was just prefixing a 10 to the z-index. 

@dvoytenko i think we might have to make sidebar always "physically" be on the fixed layer to avoid this.

**Comment by ericlindley-g** [comment]
@camelburrito  — can this be closed?
