### ISSUE TITLE
Is the AMP project committed to promoting web standards?

### ISSUE THREAD

**Issue by Download** [ampproject/amphtml#6086]
If so, then why does the 'spec' mandate the use of vendor prefixes?

> AMP HTML documents MUST:
>
> ...
> Contain the following in their <head> tag: <style amp-boilerplate>body{**-webkit**-animation:-amp-start ...

Wouldn't it be better to stick to W3C specs?

**Comment by cramforce** [comment]
@Download We are, but also practical in that things need to work and the `-webkit-` addition is crucial for some Safari and Android browser support. That same sample you showed has the standard `animation` property in it, just a bit further down.

**Comment by Download** [comment]
@cramforce  Thanks for your response!

But why enforce support for old browsers is what I mean? 
It's just that the wording MUST is so strong for something that is so... opiniated as which browser (versions) to support. 

Wouldn't it be better if the standard boilerplate only contained standard HTML and CSS? People that want to support old browsers can then add an extra snippet of css for those. But now AMP forces everyone to support old/legacy browses. 

It seems weird to have this strong requirement for it. Or is it maybe allowed to leave the -webkit stuff out if you don't care about those older browsers?

**Comment by cramforce** [comment]
@Download This is a very special case, because we require this literal CSS to be present in each page. There was some discussion about this (and we may soon switch to a shorter recommended version), but agreement is to leave the check literal without allowing any modifications. This is just because it is easier to copy paste the snippet than doing any type of fuzzy matching on it (which would then require good error messages).

**Comment by Download** [comment]
@cramforce Thanks for explaining I am looking forward to seeing the legacy stuff dropped in a future version of AMP  👍
