### ISSUE TITLE
Enhance a4a format spec to allow blank src attributes

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#6127]
This is to make sure ad servers can easily handle optional elements, especially when A4A creation time has some optional macros which might validate fine but request time validation might fail because of blank src attributes if the asset uploader doesn't set the optional element.

CC @ampproject/a4a

**Comment by jasti** [comment]
@tdrl, please feel free to re-assign.

**Comment by tdrl** [comment]
Will do.  To clarify, is this blank `src` attributes on _any_ AMP element or only on the `amp-ad` itself?  The use case here is an `amp-pixel`, right?  So this meant to apply to any element?

**Comment by michaelkleber** [comment]
Seems to me like amp-pixel and amp-analytics are the most relevant use cases.

**Comment by Gregable** [comment]
We don't allow `src` to be empty in the validation rules for tags like `<amp-pixel>`, should we be making updates to validation as well?

**Comment by michaelkleber** [comment]
Yes, I think the whole point of this issue is to allow an empty src string to be valid throughout the stack: pass validation, be a no-op instead of an error at render time, and update the spec to indicate that it's considered acceptable.

**Comment by tdrl** [comment]
Fair enough.  For the record, the [A4A Spec](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/amp-a4a-format.md) doesn't actually mention `src`, so any prohibition on an empty `src` attribute is inherited from the master AMP spec.  Would it be helpful to add an explicit "empty `src` is allowed" in the A4A spec, or is it better to remain silent and address it purely in the AMP spec?  (I vote for the latter, and not just because I'm lazy ;-) but because it makes a clearer single-source-of-truth.)

While we're at it, are there any other attributes that should get special treatment?

**Comment by Gregable** [comment]
Disabling src= validation might make it harder for a developer to debug/notice issues. My preference would be to continue to require these for this reason, and to instead fix whatever is causing the blank src= tags, but I can see the practicality of the other approach.

It's more OK for elements which have no user consequences if broken, such such as amp-pixel and amp-analytics, but I think we should draw the line for other tags that do have consequences (ie: an `<amp-img src=>` would be something we would want to remain invalid).

I'd also recommend making the change to AMP rather than just A4A, just to keep the mental overhead lower for developers working on both.

**Comment by michaelkleber** [comment]
I think allowing the empty string is quite reasonable -- this isn't disabling validation, just adding one new valid value :-).  Realistically, since there are serving systems which support templating in an optional URL but don't support removal of an entire block of HTML when that optional URL is absent, making AMP a little permissive here seems like the right move.

**Comment by Gregable** [comment]
Something like `<amp-img src="" width=400 height=400></amp-img>` results in a very broken user experience though, with a big blank gray box on the page. 

Of course, a developer could cause the same problem in other ways which aren't detectable by a validation pass.

**Comment by michaelkleber** [comment]
Yes, I agree, amp-pixel and amp-analytics are the use cases where I think make sense to allow the url to be null (at which point they become no-ops).

**Comment by jasti** [comment]
@Gregable is this accepted for a validator change?

**Comment by Gregable** [comment]
Yes, I'll implement empty `src` for `amp-pixel` and `amp-analytics`. @dvoytenko in case there is anything the runtime needs to do to handle.

**Comment by Gregable** [comment]
Actually `amp-analytics` has no `src` attribute (https://www.ampproject.org/docs/reference/components/amp-analytics), only `amp-pixel`.

**Comment by dvoytenko** [comment]
I assume `amp-analytics` refers to `config=""` attribute? If so, empty value is supported here.

Not the case for `amp-pixel.src` however. Normally we resolve all URLs against the base or against the source. And normally, an empty `src` is resolved as well. Are we sure that it's a good idea to walk away from these rules in this case?

**Comment by jasti** [comment]
For `amp-analytics`, I think Michael was referring to making event and pageview URLs to be optional. 
For pixel, there are two use cases to validate from the requestor's perspective: 
1. optional attributes 
2. ability to validate with macros

Since both of these actually don't lead to visually broken content, I'd recommend we allow it. Or we should consider building a proper templating mechanism into our validator.

**Comment by jasti** [comment]
Re-reading it, 2. is not relevant to this conversation. Still think we should allow empty URLs and remove references during reserialization, if possible.

**Comment by Gregable** [comment]
@jasti, the validator does not do anything with the JSON contents, so those fields (event and pageview) can be empty or even cat emojis. @dvoytenko, good catch, I missed that part of the spec. I'll also allow `config` to be empty.

If you don't want me to allow those two fields to be empty, speak now.

**Comment by dvoytenko** [comment]
@jasti Do you have an example of such a document with empty fields? I'd like to be 100% confident what we'll allow.

**Comment by honeybadgerdontcare** [comment]
Addressed in #7590 for both amp-pixel.src and amp-analytics.config
