### ISSUE TITLE
Allow configuring of additional "trusted destination hosts" for variable substitution in href of <a> tags

### ISSUE THREAD

**Issue by smeder** [ampproject/amphtml#6141]
This is a follow on request to #4078. We need to be able to white-list a set of non-origin destinations for which we want to enable variable substitution. The use case for this is around variable substitution in deeplinking service urls such as Branch.io or Firebase, where the variables substituted would enable downstream analytics.

**Comment by rudygalfi** [comment]
@cramforce Any updates on this or does this need any further discussion?

**Comment by cramforce** [comment]
CC @rudygalfi 

Yeah, we probably should do this.

**Comment by smeder** [comment]
Any updates on this? It is preventing us from running effective experiments on AMP. If this is blocked by privacy concerns we could also consider just allowing substitution of the current triggered experiments.

**Comment by rudygalfi** [comment]
#4078 is not yet rolled out. We're prioritizing getting that out (hopefully next 2 weeks or so) and then can take a look at expanding the set of origins that can be used (this issue).

**Comment by cpapazian** [comment]
I'm working with @smeder on a possible patch for this. It looks like it should be pretty easy to add specified domains to the origin check that is already being done in `maybeExpandLink`.

Looking at https://github.com/ampproject/amphtml/issues/4078 @cramforce mentions using a meta tag with the site and white listed variables. Does that work, or would a JSON structure be better? The meta tag looks simpler to me, and we can probably drop the white listed variables, since  `data-amp-replace` already contains that whitelist per link. I was thinking something like ... 
```
<meta name='amp-link-variable-allowed-origin' content='www.somesite.com'>
<meta name='amp-link-variable-allowed-origin' content='www.othersite.org'>
```
I've hacked together something locally that seems to be working, so if this looks good, I should be able to turn around a patch pretty quickly.

**Comment by cramforce** [comment]
@cpapazian That looks good. I'm wondering, should we use a `data-amp-allowed-origin` on the individual `a` tag instead of the global meta tag?

**Comment by smeder** [comment]
In our case we will have a whole bunch of these links on a page (just looked at a sample page with ~600), so placing this on each individual anchor tag feels like it would bloat the DOM.

**Comment by cramforce** [comment]
K, lets use full origins like `<meta name='amp-link-variable-allowed-origin' content='https://www.othersite.org'>` and lets use more idiomatic space separation `<meta name='amp-link-variable-allowed-origin' content='https://www.othersite.org https://www.yetanothersite.com'>`

**Comment by cramforce** [comment]
@cpapazian's change is ready to be merged. Just need a quick go ahead from @rudygalfi 

I'm also realizing this whole topic is in need of docs :)
