### ISSUE TITLE
amp-font does not work in Microsoft Edge

### ISSUE THREAD

**Issue by eike-hass** [ampproject/amphtml#6219]
We are having trouble loading webfonts with the <amp-font> component. We threw together a quick example. Are we doing something wrong? We see some errors in the console, might be related.

## How do we reproduce the issue?

1. Open the Edge browser
2. Navigate to https://output.jsbin.com/tofusinehe/
3. See that "fancy font" is not properly styled 

## What browsers are affected?

Edge 38.14393.0.0

## Which AMP version is affected?

AMP 1478301221318
I don't think this is a new issue.

**Comment by eike-hass** [comment]
This also seems to be a issue on OSX Safari: Version 9.1.2 and Version 8.0.6

**Comment by camelburrito** [comment]
@eike-hass - works on 8.0.8 safari.

The fonts are not guaranteed to be loaded successfully all the time. The loader tries its best to try and load the font before the timeout. 

On IE Edge i see this is broken, I'm debugging that.

**Comment by eike-hass** [comment]
@camelburrito thank you for looking into this!
Weird thing is that the "direct embed" displays the font way before the timeout of the font-loader. Shouldn't the font loader pick up the font-load "event" roughly at the same time? Our use case would be to display a fallback font while loading, but displaying the correct font on the first request is definitely the desired result.

**Comment by camelburrito** [comment]
@eike-hass direct embed is render blocking and hence could display before the font-loader, the font-loader will (should) trigger font loads without blocking rendering. The browser (most of them) would trigger the load when they actually start rendering an element that needs this font and will block rendering till the download finishes. amp-font will trigger the download  when the extension is loaded meanwhile the body continue rendering and it will enable the font via the css classes. 

Chrome, Safari 10 and FF have native support for FonFaceSet.load/check methods and hence we can rely on the browser to load the font and tell us when it has finished loading. 

Rest of the browsers (IE and lower versions of Safari) do not support this API and we have to rely on the polyfill, where we repeatedly keep trying to detect if a font loaded and this could time out sometimes. 

It is weird that the polyfill works on IE and not on edge.  Will keep you posted on the progress.

**Comment by eike-hass** [comment]
It seems the font-loading stopped working on IE11. Can you reporduce this issue?

**Comment by ericlindley-g** [comment]
Re-opening this issue
/cc @camelburrito

**Comment by camelburrito** [comment]
@eike-hass just tried your bin on IE 11 seems to work fine for me, is there another page you want me to take a look at? 

Closing this for now (feel free to re-open)

**Comment by eike-hass** [comment]
@camelburrito I can reproduce this on https://ampbyexample.com/components/amp-font/ This is what it looks like on my machine: 
![image](https://cloud.githubusercontent.com/assets/3441319/23212440/0e136720-f907-11e6-9ac8-8171fc642161.png)

**Comment by eike-hass** [comment]
could this issue be reproduced?

**Comment by jridgewell** [comment]
I think @cvializ was looking into it, but got delayed by AMP Conf.

**Comment by camelburrito** [comment]
@cvializ - find me when you need help :)

**Comment by cvializ** [comment]
will do!

**Comment by cvializ** [comment]
I have noticed a few things:

1. Current versions of Chrome, Safari and Firefox behave as expected when I attempt to reproduce with [an amp demo page](https://github.com/ampproject/amphtml/blob/master/examples/font.amp.html).

2. Some fonts fail in IE11 with an error `CSS3114: @font-face failed OpenType embedding permission Check. Permission must be Installable.` Specifically, the `Tangerine_Regular.ttf` font on the [ampbyexample.com amp-font demo](https://ampbyexample.com/components/amp-font/) shows this behavior. This error doesn't appear in Edge. This is due to a permission flag that IE enforces, but other browsers don't. I found a short explanation in the CSS3114 section here: http://marinbezhanov.com/how-to-embed-webfonts-properly-and-how-to-solve-the-ambiguous-css3111-font-face-encountered-unknown-error/.

3. For missing fonts or for fonts with the above error, amp-font fails to add the `on-error-add-class=""` class to the root node in IE11 and Edge.

We should work to fix the `on-error-add-class` not getting added, but the font permission issue seems to be a font-file-specific issue outside the scope of `amp-font`
