### ISSUE TITLE
AMP Page Show's Error in Google Chrome Extension Validation Check , but It's Clear in AMP Validator ?

### ISSUE THREAD

**Issue by alurijayaprakash** [ampproject/amphtml#6353]
AMP Validation Error 

iam using Wordpress **[AMP Plugin](https://wordpress.org/plugins/amp/)** and if i validate My **[Website AMP page](https://goo.gl/olX4Ui)**  with **[Google Chrome AMP Validator Extension](https://chrome.google.com/webstore/detail/amp-validator/nmoffdblmcmgeicmolmhobpoocbbmknc?hl=en)** : it show's one error . but if i validate the same AMP page at **[AMP Validator](https://validator.ampproject.org)**  it Completely Clear ie. Passed . i Think there is issue in either **[AMP Validator](https://validator.ampproject.org)** or [Chrome AMP validator Extension ](https://chrome.google.com/webstore/detail/amp-validator/nmoffdblmcmgeicmolmhobpoocbbmknc?hl=en)

Wordpress AMP plugin Version : 0.4.2
Browser : Google Chrome

Please consider this issue , Reply Me back.
![111](https://cloud.githubusercontent.com/assets/22980471/20659008/db410502-b566-11e6-972c-5fffb24029f0.PNG)
![222](https://cloud.githubusercontent.com/assets/22980471/20659009/db43de9e-b566-11e6-93d7-20200bea500e.PNG)

**Comment by Gregable** [comment]
I can't reproduce, both show your page as passing for me. Can you try restarting your browser to make sure that the extension picks up the new validator rules and try again?

**Comment by Gregable** [comment]
Another possible theory is that a `<script>` tag is being injected into the page when you view it in your browser. Either due to some difference in the response being returned by the server, something on your network modifying the response before it reaches your browser, or maybe even a browser plugin. You can try viewing the source of the page in your browser to see what's actually at line 6.
