### ISSUE TITLE
Consolidate canary-config.json and prod-config.json

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#6359]
@dvoytenko had brought up that the current usage of canary-config.json is actually a bad idea as what this really does is leak the experiment into production (which is 1%). We should be instead setting a good probably value for the experiment to occur like 1% and not using it as an on/off switch like we are currently using the flags.

Action Items:
- remove canary-config.json and only prod-config.json will be used for both canary and prod versions served.
- canary: 1/0 should still be set correctly. 
- ~~If an experiment is ON in canary and not in production, carry it over to prod-config.json and set a .01 value.~~

@ampproject/a4a @cramforce

**Comment by dvoytenko** [comment]
@erwinmombay All good except the last one. We don't need to set the canary experiment to `.01` value. It should be as PROD explicitly configured.

**Comment by tdrl** [comment]
I'm not sure I understand the issue here. The `{prod,canary}-config.json` gets concatenated onto the front of their respective traffic fractions, right?  So ~1% of AMP page loads get the `canary-config.json` and the rest get `prod-config.json`?  If you eliminate the `canary-config.json`, how do you ensure that some things run only in canary?  Just by checking the `AMP_CONFIG.canary` value?  Then how do partial traffic experiments (like A4A) adjust their fraction within those slices?

**Comment by dvoytenko** [comment]
I do think that running some things in canary specifically is convenient and a useful use case. Alternative approach would be to re-assemble 1% PROD binary from Canary with PROD config. That would preserve all use cases correctly, I believe.

**Comment by erwinmombay** [comment]
after a few more discussions with @dvoytenko + @tdrl 's input we decided to just leave current set up as is. closing this

**Comment by dvoytenko** [comment]
Let's add md file next the config with quick points on how they are to be used.
