### ISSUE TITLE
Problem with comments

### ISSUE THREAD

**Issue by AdamDurzynski** [ampproject/amphtml#6410]
I can add a comment under post. Button “add commnet” not working. Under browser console i see such error:
Uncaught Error: form action attribute is invalid for method=POST: form#commentform​​​
at ia.f.assert (https://cdn.ampproject.org/v0.js:6:342)
at HTMLDocument.If (https://cdn.ampproject.org/v0.js:166:50)

**Comment by mkhatib** [comment]
Hey @AdamDurzynski yes, we don't allow non-XHR POST requests hence the invalid `action` attribute for `method=POST` error for security reasons, [please see docs here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-form/amp-form.md#protecting-against-xsrf).

You'd need to use `action-xhr` in order to implement this functionality. Your endpoints need to implement [AMP CORS spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md).

Closing this as this is expected behavior. Feel free to ask more questions if this doesn't answer your questions.

**Comment by AdamDurzynski** [comment]
Thx.
