### ISSUE TITLE
Analytics zero "Avg. Time on Page" param

### ISSUE THREAD

**Issue by dmitrymotorin** [ampproject/amphtml#6434]
Is there some issue with amp-analytics? We have 20-85 "pageviews" on some the pages but "avg. time on page" is zero for all 20-85 "pageviews". As you can see on the provided screenshot from our "Google Analytics" account, the other pages have more than 1:00 minute "av. time on page" param.
**Pages with issue from the screenshot:**
http://womenosophy.com/reasons-have-older-sister/amp
http://womenosophy.com/pros-cons-getting-hair-permed/amp
http://womenosophy.com/traits-make-open-minded-people-special/amp
http://womenosophy.com/ultimate-signs-man-crazy/amp
Screenshot from "Google Analytics":
<img width="1401" alt="analytics-zerotime-rows" src="https://cloud.githubusercontent.com/assets/6582420/20787385/317f7c1a-b7b4-11e6-8cb5-2162f3088c67.png">

**Comment by mkhatib** [comment]
Thanks for filing @dmitrymotorin 

How recent are these analytics results? 

Just trying to figure out if a recent change I made might have caused this. If you are able to figure when did the 0-time on page started to happen it might help us pinpoint if there's a problem.

**Comment by dmitrymotorin** [comment]
@mkhatib results from last week.

**Comment by avimehta** [comment]
This is a known drawback of Google Analytics. GA's calculations for time on page are a little weird because they use the time between visit to first page and second page to calculate time on page/time on site. This calculation messes up when there is only one page in the visit/session. We are looking at solving this issue but don't have anything to share for now.
