### ISSUE TITLE
Sticky ads should never resize the ad container to be bigger than initial size

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#6464]
- [ ] Ensure that the returned ad can never resize the ad container (or overflow) to larger than the primary amp-ad width and height
- [ ] Disallow multi-size attributes when placed as sticky ads
- [ ] Update AMP validator to show errors when embedding amp-ad with multi-size attributes when placed as sticky ads

Example: 
![sticky](https://cloud.githubusercontent.com/assets/2366341/20848000/4896370a-b89e-11e6-9596-34d91e0ce18a.jpg)

Sample code:
`
<amp-sticky-ad layout="nodisplay">
<amp-ad width="320" height="50" data-multi-size="300x50,1x1" data-multi-size-validation="false" type="doubleclick" data-slot="/7175/fdcmobile/amp/article" json="{&quot;targeting&quot;:{&quot;displaysection&quot;:&quot;businessinthebeltwayblog&quot;,&quot;amp&quot;:&quot;true&quot;,&quot;pos&quot;:&quot;mobile&quot;,&quot;fl&quot;:&quot;&quot;,&quot;channel&quot;:&quot;business,investing&quot;,&quot;swimlane&quot;:&quot;&quot;,&quot;specialslot&quot;:&quot;&quot;,&quot;section&quot;:&quot;business:washington,investing:taxes&quot;,&quot;id&quot;:&quot;blogAndPostId/blog/post/12-41931&quot;,&quot;brand&quot;:&quot;&quot;,&quot;displaychannel&quot;:&quot;business&quot;}}"></amp-ad>
</amp-sticky-ad>
`
Test page: http://www.forbes.com/sites/beltway/2016/11/30/trumps-treasury-pick-describes-a-very-different-tax-plan-than-his-boss-campaigned-on/amp/

CC @zhouyx @cramforce

**Comment by zhouyx** [comment]
@jasti As we figured this specific example's bug is not related to sticky-ad. Do we still want to limit sticky-ad resizing now? If so, do we want to disallow all kinds of resizing or do we want to introduce some restrictions here?

**Comment by cramforce** [comment]
I'd be in favor of a defense in depth.

**Comment by jasti** [comment]
@zhouyx yes, let's go ahead with restricting resize on sticky ads.

**Comment by zhouyx** [comment]
Working on this. 
> Disallow multi-size attributes when placed as sticky ads
Update AMP validator to show errors when embedding amp-ad with multi-size attributes when placed as sticky ads

@jasti This is not very practical as as AmpAd we don't provide multi-size attributes. Those multi-size attributes are from third party ad networks, and they can name it to whatever they like. The best we can do here is to disallow resizing sticky ads to a larger dimension. Or As I would propose, do not allow sticky ads to resize at all. Because if they resize to a very small size or even to height 0px, it would still be a bad user experience. WDYT

**Comment by jasti** [comment]
Not permitting resize on sticky ads makes sense. Thanks.

**Comment by jasti** [comment]
Fixed in another PR
