### ISSUE TITLE
Anchor scrolling not working correctly

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#6512]
If the sidebar content is small, the anchor URL works perfectly. If the sidebar is long, the anchor seems to be pushed to the bottom of the page.

Here's two long pages with 5000px height and a `<div id=middle>` in its middle. The first page has a small sidebar. The #middle anchor scrolls the page to its middle, which is correct:

https://cdn.ampproject.org/c/s/mmm6.fastcommerce.com.br/lojas/00010554/htm/anchor-ok.html#middle

The second page has a long sidebar. The #middle anchor incorrectly scrolls the page to its end:

https://cdn.ampproject.org/c/s/mmm6.fastcommerce.com.br/lojas/00010554/htm/anchor-not-ok.html#middle

**Comment by camelburrito** [comment]
@rudygalfi - the links do not work :(

**Comment by camelburrito** [comment]
@mkhatib - this might also have something to do with the issue i showed you today morning.

**Comment by ericlindley-g** [comment]
Here's what I think is a [working example](https://www.ampproject.org/docs/reference/components/amp-analytics#transport)

**Comment by mkhatib** [comment]
@rudygalfi I am not sure I understand, is this related to page load or actually clicking a specific anchor inside `amp-sidebar`?

Also, which platform you're seeing this on?

**Comment by mkhatib** [comment]
@camelburrito what was the URL for the page you showed me?

**Comment by rudygalfi** [comment]
@ericlindley-g Can you clarify how to repro using your example. For instance, I'm not sure if you're referring to mobile emulation mode or which anchor tags to click on.

@mkhatib If memory serves, this was reported on the mailing list. I believe the cases were:

- amp-sidebar does NOT extend the full height of viewport. In the middle of a very long page (~5,000px) there's a div with id="middle" which is positioned roughly in the middle of the page. If you click on this from within a link in the amp-sidebar, scrolling works as expected.

- amp-sidebar extends beyond the full height of viewport. In the middle of a very long page (~5,000px) there's a div with id="middle" which is positioned roughly in the middle of the page. If you click on this from within a link in the amp-sidebar, scrolling does NOT work as expected.

**Comment by ericlindley-g** [comment]
Apologies — my example might be related to the issue, but isn't the same use case.

To repro on mobile emulator or desktop (works fine on iPhone 6/Chrome):

1. Click on this [example](https://www.ampproject.org/docs/reference/components/amp-analytics#transport)

expected: Page opens, scrolled such that heading[id="transport"] is at the top of the viewport

actual: Page opens, scrolled to the bottom of the page

**Comment by aghassemi** [comment]
@ericlindley-g @rudygalfi I created a test page: http://s.codepen.io/aghassemi/debug/peOVMw (since the other links are all broken) but have not been able to repo. (tried Desktop: Chrome/Safari, iOS: Safari, Android: Chrome). They all seem to be working fine. Is my test page correct? Do you know of any other live examples that have this issue?

**Comment by ericlindley-g** [comment]
Strange—I'm having trouble repro-ing this exact case as well. The general case may have been fixed by some other work, somehow.

I'd be okay closing for now.

Possibly related but tracked for the [AMP Start website](https://github.com/ampproject/ampstart/issues/260): on iOS Chrome, at  https://ampstart.com/components, tapping on the hamburger icon in the "navigation" examples causes the viewport to scroll to the bottom of the page.

**Comment by rudygalfi** [comment]
I'm good with closing. The original pages that showed this seem to be gone.
