### ISSUE TITLE
Please, add extension for TidioChat

### ISSUE THREAD

**Issue by ghost** [ampproject/amphtml#6553]
Hi there,
sorry if I write this request here, may be it's not the right place, but I need an AMP extension for TidioChat https://www.tidiochat.com/ so I can migrate my website to AMP

In this moment AMP suffers from the lack of an extension for livechat.

This extension if easy to create, just give a public key as parameter and it should add a script to the DOM such as:

<script async src="https://code.tidio.co/{publickey}.js"></script>

Thanks,
Marco

**Comment by marcofortina** [comment]
Here a sample of my code but I don't know very well how to contibute to AMP and how to make it more robust:

`import {isExperimentOn} from '../../../src/experiments';
import {dev, user} from '../../../src/log';

/** @const */
const TAG = 'amp-tidio-chat';

/** @type {number}  */
let trackingTidioChatCount = 0;

class AmpTidioChat extends AMP.BaseElement {


  /** @param {!AmpElement} element */
  constructor(element) {
    super(element);
    // declare instance variables with type annotations.
  }


  /** @override */
  buildCallback() {
    // get attributes, assertions of values, assign instance variables.
    // build lightweight dom and append to this.element.
    dev().assert(this.element.getAttribute('publickey'), 'Required attribute publickey');
    this.publickey_ = this.element.getAttribute('publickey');

    trackingTidioChatCount++;
    if (trackingTidioChatCount > 1) {
      console/*OK*/.error('Only 1 TidioChat script allowed per page.');
    }

    const script = this.win.createElement('script');
    script.src = 'https://code.tidio.co/' + this.publickey_ + '.js'; 

    this.element.appendChild(script);
  }

}

AMP.registerElement('amp-tidio-chat', AmpTidioChat, CSS);
`

**Comment by marcofortina** [comment]
Ok I found all I need for contributing. Please authorize me for creating pull requests, Thanks

**Comment by jridgewell** [comment]
We generally reach out to someone from their company to implement the extension.

/to @ericlindley-g.

**Comment by marcofortina** [comment]
Yes I understand it, but as you can see it's an easy implementation. My extension just add the required script to use the tidiochat.
Thanks,
Marco

**Comment by jridgewell** [comment]
We explicitly forbid outside javascript from being injected into the page. This would have to inject a cross-origin iframe (or similar) that then runs the widget.

**Comment by marcofortina** [comment]
I see... I tried this method using as example other extensions like "amp-facebook" and "amp-viz-vega". How could this widget be included? If you have any advice I'd love to, because for me it is vital to have a chat customer support on AMP websites. Let me know so I could collaborate on this new extension.
Thanks

**Comment by jridgewell** [comment]
Facebook works by injecting an iframe, and we security reviewed Vega's code so we could directly include it (it's open source).

Generally, these are best left to the company to implement, because we rely on them to keep the extension up to date with their code. Can you contact them for support, and ask them to get in touch with us to get an implementation?

**Comment by marcofortina** [comment]
Hi there!
TidioChat script inject an iframe and few lines of css style and create a Listener for changing the parrent style of the injected iframe during the interaction with the widget.

I can try to ask TidioChat team if they can do that :+1: anyway because as I said before I use this widget for my business I'm glad to collaborate with the implementation and of course to keep it up to date and I have all ready for forking on AMP, commit my extension and create a pull request.

Can we anyway proceed?
Marco

**Comment by jridgewell** [comment]
> TidioChat script inject an iframe and few lines of css style and create a Listener for changing the parrent style of the injected iframe during the interaction with the widget

That would have to written into an AMP extension, we can't load an outside script at all.

/cc @ericlindley-g or @rudygalfi

**Comment by ericlindley-g** [comment]
Hi @marcofortina  — just wanted to check in to see if you had any luck contacting TidioChat

**Comment by marcofortina** [comment]
Hi @ericlindley-g I wrote to them and proposed to implement it also because if they do it, they could be the 1st with a livechat on amp ;) but at the moment no answers.

I wrote an extension but because I can not modify their js, I just can inject their js as posted before.

**Comment by marcofortina** [comment]
anyway I inform you that I moved all my website on AMP ;) if you like to take a look and give me some feedback I would be grateful
[Discoteche Roma](https://www.discotecheroma24.it/)

**Comment by ericlindley-g** [comment]
Nice! It's great to see a fully AMP'd canonical site like this :)

W/r/t the TidioChat extension, if there's no way to implement as a third-party without directly injecting the js, then we'll have to wait for TidioChat to implement, themselves. Thanks anyway!

**Comment by marcofortina** [comment]
Thanks to you. At the moment I'm a little bit busy with the New Year Eve Party here in Rome, but on January I would like to contribute with the AMP project creating extension for some missing feature like a "full responsive menu" (not only sidebar) and all that I see could be useful

**Comment by ericlindley-g** [comment]
That sounds great — when you are ready to start, you can open an issue as an "Intent to implement", to briefly describe the feature, including the user-facing behavior, developer markup to use the feature, and the implementation for the library itself. There you can discuss the approach with the team, before submitting a pull request with the implementation.

**Comment by heiwen** [comment]
@ericlindley-g There are quite a few other customer messaging platforms around, take Intercom or Zendesk just to name a few examples. I understand that the AMP team has been working very closely with ad portals and audio/video services to get them on-board, is there any similar initiative planned in the Help Desk segment?

**Comment by ericlindley-g** [comment]
Hi @heiwen  — It's true that integrations for features like ad/audio/video embeds tend to work best when the organization responsible for the original feature is directly involved. Though I'm not aware of any direct outreach by the AMP team for help desk features.  ( /cc @rudygalfi in case he's aware of any effort along these lines)

One thing that would help is for help chat providers to hear directly from their customers about their need to have their feature in AMP (the need is most clear when it's coming from their actual customers, rather than someone on the AMP team)

**Comment by aghassemi** [comment]
Unlikely AMP Core team will add these. Intent to Implement/OR from these vendors would be welcome.
