### ISSUE TITLE
AMP Google Analytics not working

### ISSUE THREAD

**Issue by ankurp** [ampproject/amphtml#6740]
Please walk through the following steps for reporting an issue about AMP:

- Please ask general questions about AMP over on stackoverflow under the AMP HTML tag: http://stackoverflow.com/questions/tagged/amp-html
- Please ask/post questions/problems related to Google Search in Google's AMP forum: https://goo.gl/utQ1KZ

## Short description of your issue:

Google analytics used to work with `<amp-analytics>` tag and has stopped working for about a month.

## How do we reproduce the issue?

USA Today which uses Google Analytics does not trigger a Google analytics call https://cdn.ampproject.org/v/amp.usatoday.com/story/95582484/?amp_js_v=6

1. Open the link above in browser
2. Open Network tab and look for `collect` call which never fires for the site
3. Confirm by viewing the source that the `<amp-analytics>` tag for Google analytics is there in the source of the HTML.

## What browsers are affected?

Tested only in Chrome but should not matter

## Which AMP version is affected?

Using v0 of AMP

**Comment by jridgewell** [comment]
I don't see a `<amp-analytics type="googleanalytics">` anywhere on the page? Only a `type="comscore"`, and a custom which defines its own requests to `https://srepdata.usatoday.com`.

**Comment by ankurp** [comment]
@jridgewell If you look at the source you will see the following but I see they don't specify `type="googleanalytics"`

```
<amp-analytics id=analytics1>
	<script type="application/json">
	{
		"transport": {"xhrpost": false, "beacon": true},
		"requests": {
			"base": "https://${trackingServer}/b/ss/${accounts}/1/AMP-0.1/sRANDOM",
			"pageView": "${base}?AQB=1&vid=CLIENT_ID(amp_id)&pageName=${pageName}&j=amp&ref=${ref}&c4=${c4}&c7=${c7}&c16=${c16}&c17=${c17}&c18=${c18}&c19=${c19}&c25=${c25}&c42=${c42}&AQE=1"
		},
		"vars": {
			"trackingServer": "srepdata.usatoday.com",
			"accounts": "globaldesktopmobilesite",
			"pageName": "usat :/story/news/politics/onpolitics/2016/12/18/donald-trump-reince-priebus-electoral-college--russia-hacking/95582484/",
			"c4": "AMPmobileweb",
			"c7": "AMPmobileweb",
			"c16": "article",
			"c17": "news",
			"c18": "politics",
			"c19": "onpolitics",
			"c25": "gpapermobileapp",
			"c42": "95582484",
			"ref": "DOCUMENT_REFERRER"
		},
		"triggers": {
			"pageLoad": {
				"on": "visible",
				"request": "pageView"
			}
		}
	}
	</script>
</amp-analytics>
```

But this is an issue with another website which does specify `<amp-analytics type="googleanalytics">` If you view the source of this site you will see the markup is there and set correctly but google analytics does not fire https://cdn.ampproject.org/v/s/www.bloomberg.com/gadfly/amp/articles/2016-11-15/human-bond-pickers-find-redemption-against-indexing?amp_js_v=6

**Comment by jridgewell** [comment]
/to @avimehta 

@lannka, maybe you could help?

**Comment by jpettitt** [comment]
We are seeing the analytics tag firing at a doubleclick address instead of the normal GA one and it's not including our extra vars.  This is only pageview events - our visibility events are still hitting www.google-analutoics.com/collect

https://stats.g.doubleclick.net/r/collect?v=1&aip=1&t=dc&_r=3&tid=UA-73338518-2&cid=amp-fHZgKWzWlyzNG9qJZynjfnZuFZw-7y-8TvyZokMMAd8x95daLFPrGlvFV6IKFu2L&jid=0.3412224567191007&_v=a1&z=0.09046188048244419

**Comment by jpettitt** [comment]
See also https://github.com/ampproject/amphtml/issues/6714

**Comment by jridgewell** [comment]
Cross posting https://github.com/ampproject/amphtml/issues/6714#issuecomment-268112606:

This is due to Chrome not showing redirected XHR requests in the Network DevTools. Testing in Firefox, I see two XHRs:

1. POST to www.google-analytics.com
   - Includes extra params
   - Returns 302 redirect to stats.g.doubleclick.net
2. GET to https://stats.g.doubleclick.net
   - No extra params

Is your data being logged incorrectly in doubleclick.net?

**Comment by jpettitt** [comment]
Chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=675789

**Comment by cramforce** [comment]
Can we close this?

**Comment by ankurp** [comment]
@cramforce  This can be closed if `302` is the correct status code and response for Google analytics call that has extra parameters.

**Comment by cramforce** [comment]
You should be able to verify with Safari or Firefox devtools.
