### ISSUE TITLE
Please allow users to opt out AMP

### ISSUE THREAD

**Issue by chunhualiao** [ampproject/amphtml#6817]
Tons of complaints online about this horrible AMP  entrenched in google news and google search and forced into throats of users.  I am not sure if the AMP tried to read them at all.

Two biggest issues are
1. A singe vertical slide can easily be wrongfully  recogonized as a horizontal swipe, triggering disappearing of the article being read. Horrible user experience.

2. Search results return coated amp links. Forcing users to deal with the bug mentioned above. Totally unusable.

I already had enough and ditched google news. I am changing my search engine to bing now.

**Comment by chunhualiao** [comment]
The link for user complaints

https://productforums.google.com/forum/m/#!topic/webmasters/8ogdv04Cm-k

**Comment by ericlindley-g** [comment]
Thanks for the feedback @chunhualiao. The [product forum](https://productforums.google.com/forum/?utm_source=footer#!msg/webmasters/8ogdv04Cm-k/fcSe61u2DgAJ) in your link is the right place to provide this feedback, since the AMP open-source library doesn't directly cause the issues you describe (this GitHub repo is specifically for the open-source library). Instead, distribution platforms like Google Search or Google News & Weather have in certain conditions chosen to return AMP documents that web publishers have created themselves (Google does not create these AMP documents), and define the interactions to navigate between those documents (swiping, etc).

That said, folks at Google working on distribution platforms are listening to this feedback and working on improving the experience. Also, folks working on the AMP open-source project are thinking through what we can do to help (for instance, providing web publishers with more tools to create good-looking, fully-featured AMPs quickly and easily).

(closing this issue, since it's already covered in the Google forums)
