### ISSUE TITLE
Add support for container layout to amp-carousel

### ISSUE THREAD

**Issue by darobin** [ampproject/amphtml#6906]
Content that features items that cannot be reduced to fitting inside a limited width (eg. tables) are currently difficult-to-impossible to use in AMP. This has been discussed in issue https://github.com/ampproject/amphtml/issues/2745 and further in PR https://github.com/ampproject/amphtml/pull/6842 where @camelburrito suggested it would be simpler to address this by having `amp-carousel` support container layouts.

It is arguable that a carousel is likely not the best long-term option here, but without an ETA on ways to support horizontal scrolling it might be the best bet we have.

## How do we reproduce the issue?

This is a deliberate limitation of `amp-carousel` that could be lifted.

## What browsers are affected?

All.

## Which AMP version is affected?

All.

**Comment by techjoshua** [comment]
Personally, I'd like the `amp-carousel` component to support `type="carousel" layout="responsive"`.
I've been trying to figure out how I can make a carousel full of square child elements to be as wide as the viewport, and have its height adjust so I can choose to fully show 2, 3, or 4 carousel items based on the viewport dimensions.

I've hacked together something that works, but of course it doesn't validate.  I've had to style the `amp-carousel` element and its children with media queries and drop the width, height, and layout attributes which the validator complains about.

The funny thing is that it works... even though the validator isn't happy I can get the page to work as desired.  And in theory it doesn't violate the principles on which AMP is based, as the dimensions are deterministic.  My CSS  (which I could ditch if `layout="responsive"` was supported with `heights=""`):
```
amp-carousel {
	height: 50vw;
	width: 100vw;
	position: relative;
}
			
amp-carousel .slide {
	display: inline-block;
	width: 50vw;
	height: 100%;
}
			
@media (min-width: 767px) {
	amp-carousel {
		height: 33.333vw;
	}
	amp-carousel .slide {
		width: 33.333vw;
		height: 33.333vw;
	}
}
			
@media (min-width: 991px) {
	amp-carousel {
		height: 25vw;
	}
	amp-carousel .slide {
		width: 25vw;
		height: 25vw;
	}
}
```

**Comment by camelburrito** [comment]
@aghassemi - Are we planning on addressing this in the near future?

**Comment by aghassemi** [comment]
It is in the short-term backlog, but may very well become obsolete if `layers` work ends up allowing horizontal scrolling on any element.

**Comment by ericlindley-g** [comment]
Should we close this as a duplicate of [layers](https://github.com/ampproject/amphtml/issues/3434)? (sounds like we're pretty sure Layers will cover this case)

/cc @aghassemi @camelburrito @jridgewell

**Comment by sparhami** [comment]
It seems like `layout="container"` does not make much sense for carousel, because layout container means the carousel should size to the contents, but the carousel must have some overflow for it to scroll. I would assume that container would be used with some CSS to constrain the width, thus making the carousel take the height of its content, but still scroll.

Layers seems to satisfy the original use case, as long as you do not need looping. There may be other situations where the behavior is useful.

There are two new layouts that appear to make sense here:  a fixed width and a fill width. In both cases, the children of the carousel would need to have a height set (a layout of fixed, fixed-height, responsive or intrinsic). Othewise, a newly loaded slide could change the height of the carousel.

One possible use case is to allow page authors to specify a carousel (e.g. via a templating system) without knowing the height of their children.

Carousel v2 should work with these layouts, so the only work to be done is to add the new layout models (if it makes sense). I'm not sure how useful this might be in practice.
