### ISSUE TITLE
Feature request: amp-list to support layout 'container'

### ISSUE THREAD

**Issue by stonezhong** [ampproject/amphtml#7000]
## How do we reproduce the issue?
We expect the code below to work: (however, currently amp-list does not support layout container)
```
    <amp-list
        layout=container
        src="/mylist.php">

        <template type="amp-mustache">
        <div>
            <a href={{url}}>{{title}}</a>
        </div>
        </template>
    </amp-list>
```

The expectation is:
- it produces a div for the entire list
- for each item, the html from template gets inserted
- the total height of the list depend on the number of items returned.

## What browsers are affected?

All browsers? Some specific browser? What device type?
All browsers

## Which AMP version is affected?
1.0

**Comment by zhouyx** [comment]
7000! 🎉

**Comment by dvoytenko** [comment]
@stonezhong `layout=container` is currently disabled in `amp-list` because we do not allow disruptive resizes. The rules are generally the same for all elements, not just `amp-list`. Some situations where we allow resize are:
 1. When the element (e.g. `amp-list`) is not currently visible in viewport (e.g. below the fold and the resize would not disrupt the user reading). This is especially true when the element is at the bottom of the document.
 2. When the resize happens due to the user action. This is not really relevant to `amp-list`.

If we were to allow the `layout=container`, we'd have to preserve the same resize rules here and this is not usually expected. Hence it's disabled to avoid confusion.

**Comment by stonezhong** [comment]
@dvoytenko, thanks for explaining this, now I understand why 'layout=container' is not supported.

So if I have a container and the content is based on the JSON response (and bind to specified template), in such case, you have to be able to tell the size of the container before the AJAX call, otherwise, if after the AJAX call and it changes the container's size then it is considered as `disruptive resizes` so it is not supported.

I agree `disruptive resizes` is not good, but some `disruptive resizes` is local (aka, it does not push around element around it), maybe it can be considered less `disruptive` in that case.

**Comment by dvoytenko** [comment]
@stonezhong Do you have an example? We do allow resizes in very many cases and in practice we've seen resizes on `amp-list`s to be mostly allowed.

**Comment by adelinamart** [comment]
@stonezhong this was not updated in a while. If you still have any open questions, feel free to reopen this issue. Thanks!

**Comment by seomaz** [comment]
@dvoytenko for example

I create a amp-list based on json response with "show more" featured using amp-form, amp-bind.. like this: https://ampbyexample.com/advanced/show_more_button/

I can calculate the height of a fixed amount of elements (example 24 items * 300px), but when the json response was 4 items the amp-list height is too much...

Im using amp-bind to recalculate the height when click on "show more" button but i need to recalculate on amp-list first load.

thanks
