### ISSUE TITLE
Implement a build promise that resolve when an element builds

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#7032]
As a follow up for #6951 we need a way to know when an element has been built.

This is because waiting for an extension to download still allows for a small chance of a race condition where we execute submission after the extension has installed but before elements have been built.

**Comment by jridgewell** [comment]
We've been using services to do this: 

 - https://github.com/ampproject/amphtml/blob/master/extensions/amp-experiment/0.1/amp-experiment.js#L50
 - https://github.com/ampproject/amphtml/blob/master/extensions/amp-share-tracking/0.1/amp-share-tracking.js#L91

**Comment by mkhatib** [comment]
Not sure if this would work for the dependency between `amp-selector` and `amp-form`. Basically `amp-form` needs to wait until `amp-selector` has finished downloading and building. 

It's not clear to me how `getService` can be used here? Will `amp-selector` basically be required to define a service at the end of its `buildCallback` that `amp-form` would wait for?

**Comment by jridgewell** [comment]
> Will amp-selector basically be required to define a service at the end of its buildCallback that amp-form would wait for?

Basically. Is this something that needs to be done for every `<amp-selector>`, or just once for all?

**Comment by mkhatib** [comment]
That's a good question. I think if the upgrade and build cycle happens for all `amp-selector`s synchronously once the extension is installed then once should be enough - otherwise we'll have to wait for each separate `amp-selector` to build.

What do you think? 

@dvoytenko should we be using this method or would we still want to introduce a build promise?

**Comment by dvoytenko** [comment]
@mkhatib @jridgewell This particular feature, looks like, needs per-element build promise, since `amp-form` relies on the state of each particular `amp-selector`. Obviously, most of time, the upgrade will force near-immediate build of all elements of the same type. However, we cannot rely on this being true 100% of the time - thus doing so would create a risk condition. So, I think we should consider adding a *very lazy* build promise to custom element.
