### ISSUE TITLE
amp element/result does not loading on submit, but loads on shaking the browser window

### ISSUE THREAD

**Issue by dignustech** [ampproject/amphtml#7046]
I am working on a project where i am using the POLL widgets. It is currently working with combination of api and data is loading inside amp-list tag. When I submit the result via selecting any option the result does not show up, but when i zoom-in/zoom out the browser window, the result loads.

Does anyone experience the same problem with amp or have any solution and suggestions? 

![widget-screenshot](https://cloud.githubusercontent.com/assets/25145346/21979669/f68b8a24-dc05-11e6-9c68-38ff4054e93e.png)

![widget-result-loads-on-browser-when-zoom-in](https://cloud.githubusercontent.com/assets/25145346/21979681/0795c29e-dc06-11e6-91b5-1cff6fe18525.png)

**Comment by dvoytenko** [comment]
@dignustech Do you have a sample link? The most likely explanation is that the list is not allowed to be resized initially, but later allowed due to user action. The resizes are restricted based on whether runtime believes the resize will be disruptive - i.e. will jump UI while it's in the viewport. This can be dealt with by giving a good initial estimate of the size using `layout/width/height` attributes or by providing an `oveflow` element. But the sample link would help me to give a more definitive answer.

**Comment by mkhatib** [comment]
Thanks for filing @dignustech! Please provide a link or code samples so we can test this out and see if we can reproduce.

**Comment by dignustech** [comment]
Here is the url - https://beta.clubcall.com/  (amp/amp)

There is POLL widget on the page. When you submit the option and zoom in/out the page using (ctrl -) then the result loads.

Please review. Thanks.

**Comment by mkhatib** [comment]
Unfortunately @dignustech. I am unable to reproduce this. Can you give more details on where you're seeing this - browser? OS? versions?

**Comment by dignustech** [comment]
Hi guys, I resolved it myself with a fix. Have used the `div submit-success` to get the result instead of `amp-list` used earlier. 
Have another issue, will post in separate thread. Thanks!
