### ISSUE TITLE
Widespread Chrome console warning about preloading resources for nothing

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#7076]
I see the following warning in Chrome's console on various AMP sites:

> The resource [...] was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.

Example sites include CNN, WaPo etc.:

* https://amp.cnn.com/cnn/2017/01/17/politics/chelsea-manning-sentence-commuted/index.html
* http://www.refinery29.com/amp/2017/01/136511/president-obama-commute-sentence-chelsea-manning
* https://www.tripadvisor.com.au/Restaurants-g294265-zfx1-Singapore.html
* https://www.washingtonpost.com/amphtml/world/national-security/obama-largely-commutes-sentence-of-chelsea-manning-us-soldier-convicted-for-leaking-classified-information/2017/01/17/f3205a1a-dcf8-11e6-ad42-f3375f271c9c_story.html

## What browsers are affected?

Chrome 55 on Linux (Version 55.0.2883.87 (64-bit)) and Mac OS (Version 55.0.2883.95 (64-bit)); possibly other browsers.

## Which AMP version is affected?

1484259764365

## Potentially related Chromium issue

https://bugs.chromium.org/p/chromium/issues/detail?id=655698

**Comment by cramforce** [comment]
@dandv Unfortunately there is nothing we can do, except give feedback to the Chrome team that they are annoying.

There is a tradeoff here:

- These warnings can really help in the general case, because people preload stuff they don't use.
- We, unless, we have a major bug, preload the exact URLs, but we lazily load them for real, so we trigger the heuristic.

I think we will have to live with the warnings unfortunately.

**Comment by cramforce** [comment]
Closing, but feel free to open again!
