### ISSUE TITLE
"title" attribute not added to <img> tag

### ISSUE THREAD

**Issue by wisc** [ampproject/amphtml#7151]
When using amp-img the alt attribute is added, but not the title attribute, which leads to a different UX on mobile, where holding the image pressed shows the title if present, otherwise the alt. By definition the title attribute does not have the same purpose as alt, so both should be present imo.

## How do we reproduce the issue?

I have an example here: https://consolia-comic.com/

The main image (comic) has the alt & title in <amp-img>, however it only shows the alt attribute in the resulting <img> tag.

Steps:

1. Add <amp-img> tag with alt & title attributes to an amp document
2. Inspect the generated <img> tag

## What browsers are affected?

I tested this on my desktop with chrome (52) & firefox (48), on my phone it's chrome 53 on android 5.0.0.

## Which AMP version is affected?

AMP version 1484769855829. I just implemented AMP, so i don't know how long this has been an issue.

Thanks!

**Comment by jridgewell** [comment]
Thanks for the bug! Do you want to do the fix for it (it's super easy, just adding `title` to the [list](https://github.com/ampproject/amphtml/blob/49f80f9/builtins/amp-img.js#L27-L28) and [test](https://github.com/ampproject/amphtml/blob/49f80f9aba42fd2e5891b9bf11b5fac328c38bd4/test/functional/test-amp-img.js#L53-L68))
