### ISSUE TITLE
Whitelist SVG's <foreignObject>

### ISSUE THREAD

**Issue by tigt** [ampproject/amphtml#717]
If I want to use SVG with raster images, I'm fine with using `<amp-img>` to do so. But in order for that, the `<foreignObject>` tag is required.

Is its flaky IE support problematic, or is AMP more future-facing than that? Edge supports it.

**Comment by dvoytenko** [comment]
Ok. Makes sense. For some reason I convinced myself that it was deprecated. I will send along to validator.

**Comment by powdercloud** [comment]
http://www.w3.org/TR/SVG/extend.html#ForeignObjectElement:
[...] The ‘foreignObject’ element allows for inclusion of a foreign namespace which has its graphical content drawn by a different user agent. The included foreign graphical content is subject to SVG transformations and compositing.
The contents of ‘foreignObject’ are assumed to be from a different namespace. [...]
==
Will it actually work to embed things inside it, since we're using HTML syntax not XHTML and this talks a lot about namespaces etc? Has anyone tried?
Sure, adding the tag is easy, just trying to avoid that we need to back pedal later.

**Comment by Tigt** [comment]
Yeah, inline HTML5 SVG comes with its own set of rules. Whenever you open an SVG `<title>`, `<desc>`, or `<foreignObject>`, it auto-switches to HTML, regardless of any `xmlns` you have on them.

**Comment by Gregable** [comment]
We now support `<foreignObject>`. @dvoytenko, please close when you have a chance.
