### ISSUE TITLE
amp-bind carousel and default selected thumbnail preview

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#7201]
I was looking at [carousel and amp-bind integration](https://github.com/ampproject/amphtml/pull/6797) while trying to add a border to a carousel image thumbnail every time the image from a carousel is shown.

When a page containing a carousel loads, the first image of the carousel will be shown and it should be possible to highlight the corresponding thumbnail.
From the pull request sample, by using:
`on="goToSlide:AMP.setState(selectedSlide=event.index)"` 
and
`    <amp-img src="https://ampbyexample.com/img/image1.jpg" width=100 height=75
        [class]="selectedSlide == 0 ? 'selected' : ''" on="tap:AMP.setState(selectedSlide=0)"></amp-img>` for the thumbnail preview, the selectedSlide variable will only be updated when scrolling the carousel. As a result, when landing on the page, no thumbnails will be highlighted.

@choumx  Is it possible to give a default value to selectedSlide or check of selectedSlide has not been defined?

**Comment by choumx** [comment]
Good question! 

So generally speaking, initial values can be set via `<amp-state>` component. However, during initial page load we deliberately do *not* evaluate expressions with those initial values. This is because we want to avoid changing the page after initial load without any user action (which can be strange and janky). For example, imagine an AMP page's contents dramatically changing ~1 second after it loads.

For initial values, you can directly set the text/css class/attribute on the element itself. In the above example: `<amp-img class="selected">`

To handle the cases where a variable isn't defined, you can use the `||` operator to define an initial value, e.g. `someVariable || 'defaultValue'`. A better way is to use `<amp-state>` as mentioned above. I'll update the examples to show this in action.

Related to #6199.

/cc @ericlindley-g

**Comment by kul3r4** [comment]
Updating the sample will work for me, let me know once it's updated.

**Comment by choumx** [comment]
Closing in favor of #7399.
