### ISSUE TITLE
Harmless bug in validator.js cdata blacklisted regexp

### ISSUE THREAD

**Issue by cgorbit** [ampproject/amphtml#7246]
https://github.com/ampproject/amphtml/blob/master/validator/engine/validator.js#L1643

```javascript
var blacklistedCdataRegexStr = '';
if (tagSpec.cdata !== null) {
    for (const blacklist of tagSpec.cdata.blacklistedCdataRegex) {
        blacklistedCdataRegexStr += blacklist + '|';
    }
}
```

blacklistedCdataRegexStr will contain something like this:
"[object Object]|[object Object]|[object Object]|"

Consider last vertical bar!

**Comment by Gregable** [comment]
Fixed as commited (https://github.com/ampproject/amphtml/blob/master/validator/engine/validator.js#L1619). Will be deployed later.

**Comment by cgorbit** [comment]
```javascript
blacklistedCdataRegexStr = tagSpec.cdata.blacklistedCdataRegex
    .map(function(b) { return b.regex })
    .join('|');
```

**Comment by Gregable** [comment]
Hm, I thought I had tests that confirmed this was working. Investigating now.

**Comment by Gregable** [comment]
OK, so we had a test that should have been catching this: [incorrect-custom-style](https://github.com/ampproject/amphtml/blob/master/validator/testdata/feature_tests/incorrect_custom_style.out), but we were not outputting any error for the violating line containing !important. This was why the issue hadn't been noticed before. No error was being generated because we were hiding them if the cdata already had an error, which we should no longer do.

I'll fix all of this up in an upcoming PR, and include your join changes.

Thanks for noticing this!
