### ISSUE TITLE
Web Validator uses different UA on redirect

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#7325]
This fails on CDN https://www-suara-com.cdn.ampproject.org/c/www.suara.com/amp/news/2017/02/03/095115/istana-meragukan-klaim-sby-yang-merasa-disadap

It passes validator https://validator.ampproject.org/#url=http%3A%2F%2Fwww.suara.com%2Famp%2Fnews%2F2017%2F02%2F03%2F095115%2Fistana-meragukan-klaim-sby-yang-merasa-disadap

In the background this is because the first request redirects from www. --> m.

The second request to m.suara.com/amp/news/2017/02/03/095115/istana-meragukan-klaim-sby-yang-merasa-disadap adds an img if you don't use a mobile browser.  

`"GET /redirect HTTP/1.1" 301 184 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MTC19V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.81 Mobile Safari/537.36 (compatible; validator.ampproject.org) AppEngine-Google; (+http://code.google.com/appengine; appid: s~amp-validator)"`

`"GET /second_request HTTP/1.1" 200 464 "http://www.daneknecht.com/redirect" "AppEngine-Google; (+http://code.google.com/appengine; appid: s~amp-validator)"`

**Comment by powdercloud** [comment]
@dknecht Sorry this took so long. Today, I was able to reproduce what you're reporting here, as in, in cdn.ammproject.org, the first link you provided produced an error page with validation errors. Upon checking out the debug link there, however, the validator.ampproject.org would verify this with PASS.
Getting a bit confused I thought it's the validator.ampproject.org's fault, that it fails to set the user-agent correctly. After looking through the code some (specifically, how http.Client in Go copies over headers including the user-agent ... https://golang.org/src/net/http/client.go), I don't think this is the case, however, and it wouldn't be consistent with what you're reporting anyway, since it's passing in validator.ampproject.org, so the user-agent upon redirect must have been all right.
So I audited the code for cdn.ampproject.org a bit. As one would expect it's not completely trivial but it appeared that there, too, do the headers get copied. So I scratched my head once more.
Interestingly, now I can't reproduce the problem any more - the first URL works fine now.
I suspect what happened is that some time in the past we may have had a problem with copying such headers in cdn.ampproject.org, but that the problem is fixed, so by visiting this URL I caused this page to get updated. It's either that, or the webserver for www.suara.com stopped inserting the extra image.
Anyway I have a hunch this is fixed, so unless I hear otherwise I will assume we're good for now. Thanks a lot for looking into it and for your report.
