### ISSUE TITLE
null is not an object (evaluating 'c.sentinel')

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#7402]
http_user_agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) GSA/22.0.141836113 Mobile/14C92 Safari/600.1.4"      
   }

exception: "b@https://cdn.ampproject.org/rtv/001486166232176/v0/amp-iframe-0.1.js:5:269"    

sample page: https://cdn.ampproject.org/c/www.cbssports.com/nfl/news/watch-patriots-victory-parade-with-live-tv-updates-pictures-from-wild-celebration/amp/

**Comment by erwinmombay** [comment]
@bradfrizzell you familiar with this?

**Comment by dvoytenko** [comment]
@bradfrizzell It looks like this is originating from your code. Here's what I found so far.

The error is when accessing [`data.sentinel`](https://github.com/ampproject/amphtml/blob/6a97771cd66ad7706bafe4aaf777d4ee8a5372ea/src/iframe-helper.js#L205)

The reason is that `data` can be null. It's incorrectly force-casted to non-nullable value in [here](https://github.com/ampproject/amphtml/blob/6a97771cd66ad7706bafe4aaf777d4ee8a5372ea/src/iframe-helper.js#L399). You can see just two lines above, `deserializeMessage` is called which returns a possibly nullable result.

Further, `deserializeMessage` appears to fail while parsing messages such as "amp-macro-task". I'm not sure if this is a valid message and what it means exactly. This could be a false positive, i.e. an unwitting code sending a message that looks like ours. In this case, perhaps, we can make `isAmpMessage` to check not just for "amp-", but for "amp-{".

In the end, however, the code above should probably still change to do `if (!data || !data.sentinel) {return}`

**Comment by dvoytenko** [comment]
@bradfrizzell  I believe the merged #7440 is the right fix. But please confirm.

**Comment by bradfrizzell** [comment]
This looks good to me. Sorry about the slow response. Thank you all for taking care of this bug while we've been on an offsite.

**Comment by dvoytenko** [comment]
NP. I will close this for now. The logs confirm that the error appears to be gone.
