### ISSUE TITLE
Robots Meta Name set to noindex

### ISSUE THREAD

**Issue by akshatmalikcoc** [ampproject/amphtml#7459]
Hi

By default all url's show a "index,follow" under meta name=robots, however, when loading from cdn.ampproject.com/example.com/?amp=1 the view source of the page reveals: `<meta name=robots content=noindex>`

Can you please help understand if the cdn pages are supposed to contain this?

AMP Version: 1486153081489

**Comment by akshatmalikcoc** [comment]
@rudygalfi - Awaiting your Response. Thanks!

**Comment by rudygalfi** [comment]
@akshatmalikcoc I think there's something missing after "view source of the page reveals". Can you clarify your question?

**Comment by akshatmalikcoc** [comment]
@rudygalfi I guess it got hidden. My complete content once again below:

By default all url's show a "index,follow" under meta name=robots, however, when loading from cdn.ampproject.com/example.com/?amp=1 the view source of the page reveals: <meta name=robots content=noindex>

I have my newly indexed url's in search results containing "A description for this result is not available because of this site's robots.txt" - I fear this might be attributed to the noindex.

I tried to search for documentation which would explain the above but could not find anything.
Please help understand as to why does CDN.apm URL have "noindex".

**Comment by akshatmalikcoc** [comment]
@rudygalfi : Awaiting your revert please

**Comment by rudygalfi** [comment]
Apologies for the delay. Pages served from the Google AMP Cache (cdn.ampproject.org URLs) are not meant to be indexed by any search engine since they are just proxies of pages hosted elsewhere. This is why the page contains an instruction not to index. You can see this also being done via the cache's robots file: https://cdn.ampproject.org/robots.txt.

So long as, according to your example, the originally hosted page at example.com/?amp=1 is getting indexed, then everything is working as expected.
