### ISSUE TITLE
FR: dynamically fetch, cache, and populate multiple pieces of content on load

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#7463]
Tracking a recent brainstorm ( @erwinmombay, @cramforce, please jump in and correct anything I've gotten wrong :)

High-level functionality:
On load, a call is sent from the client to the origin server to fetch content for the page, which it will use to populate via template (like amp-list)

Unlike amp-list, content from the server response is cached by the runtime, and used to populate multiple sections of the page as they near the viewport, rather than just populating a single section on load

Potentially useful for highly dynamic data (ex. prices, quantities, etc), or personalization (e.g. geo-specific currencies)

Step 1 is a proposal in the form of a design doc

**Comment by cramforce** [comment]
Might be a good one for @cvializ to start with.
CC @mrjoro

**Comment by cvializ** [comment]
I'll take a look!

**Comment by cramforce** [comment]
Great. Ping me tomorrow and I can give a quick overview.

**Comment by cramforce** [comment]
I filed #7194. From that bug:

@mkhatib and I were discussing a scheme like that, which may be useful in more places:

1. Change fetch/XHR service to support fragment URLs on JSON GET requests. In particular `https://example.com/service.json#key.subkey` fetches the URL, but then returns `actualJSON.key.subKey` to the caller.
2. Cache (using a TBD strategy) the return value for `https://example.com/service.json` (ignoring the fragment), so that multiple things on the page can be backed by the same JSON request.

- Does this make sense?
- What should the caching strategy be? Options: Cache GET responses for page life time (would sometimes be a memory leak), cache N responses, cache requests with fragment, don't cache, but coalesce requests started within N milliseconds.

Will close the other one.

**Comment by jridgewell** [comment]
We're getting several of these fetch-once-and-cache stores:

- [Call tracking](https://github.com/ampproject/amphtml/pull/7493)
- [amp-custom-ad](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/0.1/amp-ad-custom.js#L33)

They could all use this de-dupe fragment logic (fragment isn't sent to the server), and there are likely other extensions that could take advantage of this. Time to extract?

**Comment by cramforce** [comment]
Good hint. And yes, that is basically the idea of this to make it accessible to most XHR consumers.

**Comment by jpettitt** [comment]
So in theory I could build a fully templated and entirely JSON driven page? With every element populated this way?  I ask becasue several of our sites have JSON api's with full content and assets.

**Comment by cramforce** [comment]
@jpettitt This FR does not add any new capabilities to AMP. Instead it allows to use a single JSON data request as a data source for multiple consumers on an AMP page.
