### ISSUE TITLE
Implement SPF Youtube

### ISSUE THREAD

**Issue by rever1992** [ampproject/amphtml#7472]
Hi Team AMP!.

Are you going to implement the youtube SPF in the future?.

Greetings.

**Comment by aghassemi** [comment]
@rever1992 Do you need something like YT SPF to enable amp-to-amp navigation or need it for partial page updates based on user actions/fresh data availability?

We are working on amp-to-amp navigation and considering AMP is already fast to load, partial replacement on navigation is not something we are considering at the moment.

If you need it for partial rendering, there are a few components that may help you do that:

`amp-form` allows partial rendering after submission using Mustache templates. https://www.ampproject.org/docs/reference/components/amp-form

`amp-live-list` can be used to to do partial rendering based on polling for fresh data. Similar to SPF, server can respond with partial HTML instead of the full page ( https://github.com/ampproject/amphtml/blob/master/extensions/amp-live-list/amp-live-list-server-side-filtering.md ). Although the response format is not JSON based like YT SPF.

Hopefully this helps. I am still interested in hearing what you had in mind for youtube SPF though.

**Comment by aghassemi** [comment]
@rever1992 Closing as we don't have any plans to support the SPF framework. Please see the comment above.
