### ISSUE TITLE
No Favicon

### ISSUE THREAD

**Issue by aashishpahwa** [ampproject/amphtml#7550]
Hi

My amp pages show blank favicon. Is it because of any contradicting plugin or the problem is at the developers end?

**Comment by jridgewell** [comment]
This is due to your server. For example, both NY Times on the [cdn](https://cdn.ampproject.org/c/s/mobile.nytimes.com/2017/02/14/us/politics/flynn-russia-trump-resignation.amp.html) and their [own domain](https://mobile.nytimes.com/2017/02/14/us/politics/flynn-russia-trump-resignation.html?referer=) display a favicon.
