### ISSUE TITLE
Provide a generic action to focus/reveal elements

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#7626]
Make it possible to focus/reveal specific elements via action. Here are three scenarios in which this would be very helpful:

1. **Scroll to element after form submit success**: A form adds elements to a list, on successful submit the new element should be revealed (even if it requires scrolling the page). This is necessary in case the form input field is on a different position on the page than the results.

       <form ... on="submit-success:last-element-in-result-list.focus" ...>
</form>

1. **Show last element in a sub view**:  amp-bind makes it possible to implement master/detail views. This would work even better if once could reveal specific elements on the detail view:

       <button on="tap:AMP.setState(showProduct=1234),product-1234.focus" ..>

3. **Focus form input fields in lightbox:** lightboxes are great for form inputs, make it possible to set focus to a specific form input field once the lightbox opens:

       <button on="tap:enter-details.showLightbox,form-details-name.focus" ..>

//cc @ericlindley-g

**Comment by aghassemi** [comment]
@ericlindley-g this aligns nicely with some of the FR @alanorozco is doing this sprint (#7027, #649) so I suggest `Prioritized FR` milestone.

**Comment by ericlindley-g** [comment]
+1 This would be great — particularly if we could smoothly animate the scrolling into view (as opposed to a "jump cut")

**Comment by alanorozco** [comment]
This is a great idea and it seems like it's almost a requisite to make the amp-bind story really useful.

One small caveat re: our current implementation of actions. Since originally only one action per event was supported, chaining actions wouldn't be a problem. Currently, action results can potentially be asynchronous so certain user expectations would not be matched since the action sequence is executed synchronously.

This needs more thought to answer whether we're ok with this. If we're not, then a more robust promise-chaining mechanism is needed.

**Comment by aghassemi** [comment]
Relevant: https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/zz7AqKAfVTY/N9YQ9BSiDQAJ

**Comment by aghassemi** [comment]
@spacedino UX might be needed for the animation curve of the smooth scrolling. Chrome is also adding this feature, We might be able to just borrow the curve from their implementation.

**Comment by aghassemi** [comment]
@sebastianbenz @ericlindley-g FYI, feature merged today, will be in Canary this week.
