### ISSUE TITLE
getMajorVersion in Chrome IOS doesn't work

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#7653]
When [creating viewport binding](https://github.com/ampproject/amphtml/blob/master/src/service/viewport-impl.js#L1732), the `getMajorVersion` return `0` in chrome ios 10, which leads to creating the wrong viewport binding.

The condition for checking ios environment version should be fixed.

**Comment by aghassemi** [comment]
@ericlindley-g @muxin @dvoytenko I recommend P1 as `ios-embed-wrapper` has already launched. I assume we need to re-test `ios-embed-wrapper` after fixing this since previous test runs were not getting the `ViewportBindingIosEmbedWrapper_` on iOS 10 as expected due to this bug.

**Comment by dvoytenko** [comment]
To clarify the exact reasoning:
 1. `getMajorVersion` for Chrome iOS returns `0` incorrectly. However, it's a tangent bug. It should instead return a real Chrome version, e.g. `56`. This should be fixed, but fixing it will not correctly address this bug, since Chrome 56 could be deployed to iOS 10 or iOS 8.
 2. Thus, the real fix would be to look at the iOS version or Safari-compatible version. Both are available in the user agent string and need to be properly parsed. 

Otherwise, I agree. This is a P1.
