### ISSUE TITLE
Bind enhancements

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#7825]
- [ ] 1. Expose amp-accordion "expanded" attribute to bind
- [x] 2. Expose amp-sidebar expanded/collapsed state to bind

/cc @camelburrito for above two items

- [x] 3. Expose "src" attribute for video players (youtube and brightcove to start)

**Comment by choumx** [comment]
An update:
1. Binding to `expanded` mostly works. Getting it to 100% (ARIA attribute and saving state to sessionStorage) is tricky since the `amp-accordion` isn't informed when `amp-bind` mutates its children directly. `MutationObserver` would work but maybe there's a better pattern for these cases -- needs more thought.
2. Binding to `amp-sidebar` currently doesn't work since it's moved to the viewport fixed layer at build. Feasible but not trivial, and IMO of questionable user value to begin with.
3. In progress.

Once (3) is in, I'm inclined to drop this to P3 and bump to backlog since they're not the "quick wins" we originally assumed. @ericlindley-g Thoughts?

**Comment by ericlindley-g** [comment]
Thanks for the breakdown—that plan sounds good to me

As a side note: part of the value of binding to amp-sidebar is that developers can customize the button that triggers the sidebar to look different whether the sidebar is closed (e.g. hamburger menu icon) or open (e.g. "X" button).  That's possible today by using CSS sibling selectors (so it's fine to be a P3), but binding would make it possible for the page layout to be more semantic in the future.

**Comment by choumx** [comment]
(2) is now done with #16130. Closing since (1) works modulo session storage.
