### ISSUE TITLE
Support polling a specified endpoint in amp-live-list

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#7848]
Tracking a feature request in https://github.com/ampproject/amphtml/issues/2762 for `<amp-live-list>` to poll to an endpoint other than the host doc. Could be a valid AMP doc, could be a JSON endpoint

Could be specified as an additional attribute

Complexity: content needs to be valid AMP. Potentially could only allow AMP cache URLs, or do some validation on the fly (and simply not slot in new content that doesn't validate).

/cc @erwinmombay

**Comment by erwinmombay** [comment]
the json endpoint one is a bit tricky. definitely needs more discussion on that

**Comment by jgsojo** [comment]
Hi @alanorozco, this is the issue I told you about this monday at our meeting at Madrid. 

PD: I'm the front-end developer from El Confidencial.

**Comment by alanorozco** [comment]
To add more context on this:

This issue describes two different features:

- configurable endpoint 
- JSON endpoints 

@jgsogo is interested in the latter. 

The reason why the endpoint needs to deliver HTML is because it can then be cached. This relieves the origin server from a little bit of the load caused by polling. 

In order to support JSON, we would ideally ping the server only when needed instead of polling with a constant frequency. For this, a long-polling connection (e.g. websockets) that notifies the client when there is new content available would be necessary. Haven't really thought out the complexity of this in the context of AMP, but it might be worth looking into if authors require support.
