### ISSUE TITLE
Construct metric for some reasonably definitive measure of AMP performance?

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#7927]
Even though we expose a number of performance metrics in amp-analytics, these may still fall short of providing a definitive and consistent metric for AMP's page loading performance.

With the `ini-load` trigger recently launched, this can provide a ground truth for when AMP considers the page to have all the content in the first viewport loaded. However, it's just a trigger. It doesn't have an associated start time to construct a performance metric.

This issue is to discuss:
* Should we make some updates to calculate load time in combination with `ini-load`?
* Are there paths to deriving this metric via other amp-analytics variables? For instance, consider the following ping that fires on `ini-load`:

```
https://example.com/ping?ts=${timestamp}&ns=${navTiming(navigationStart)}
```

Do we have a reasonable metric by doing the calculation: `ts - ns`?

**Comment by rudygalfi** [comment]
cc @cramforce @dvoytenko @smeder @paul-matthews who were involved in an off-GitHub discussion that inspired this.

**Comment by dvoytenko** [comment]
One nuance is that `ts` is also a bit of a moving target. We currently calculate `ini-load` only when requested. As such, it's normally very very close to the real `ini-load` event, but could be somewhat deferred by (a) analytics package being loaded, and (b) priority delays for analytics initialization. Again, delta is typically near zero. So, this depends on desired fidelity. By comparison, `performance.timing` metrics are near 100% fidelity since they are done by the browser itself.

**Comment by smeder** [comment]
I was wondering about the accuracy of the timestamp. Any sense for the level of fidelity? Order of 10ms?

**Comment by dvoytenko** [comment]
All `performance.timing` timestamps have high fidelity independent of script loading times. I'd expect a +/-10ms fidelity on all of those for sure.

**Comment by dknecht** [comment]
@ampproject/cloudflare FYI

**Comment by rudygalfi** [comment]
Not seeing any further traffic on this, I'll close this out since it doesn't seem essential. Feel free to re-open if there's interest in proceeding with this.
