### ISSUE TITLE
Chrome extension reports errors on valid page

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#8007]
How to reproduce:

1. Load <https://www.gaslightstl.com/single-post/2017/01/27/Why-is-the-obvious-not-obvious-somemosttimes#development=1> using a mobile UA in Chrome, with the [AMP Validator](https://chrome.google.com/webstore/detail/amp-validator/nmoffdblmcmgeicmolmhobpoocbbmknc?hl=en) extension installed.

Expected:

The extension does not report any errors.

Actual:

The extension reports multiple errors, even though the document is valid AMP.

![screen shot 2017-03-07 at 12 46 31 pm](https://cloud.githubusercontent.com/assets/51244/23669993/309875e2-0334-11e7-9b5c-f760836a02e1.png)

Copy-and-pasting the HTML content into <https://validator.ampproject.org/> also reports that the page is valid AMP.

**Comment by honeybadgerdontcare** [comment]
This is most likely due to how the extension grabs the HTML. Since the AMP Runtime has already transformed the HTML in the browser, grabbing the source directly from that fetch in Chrome isn't possible. The extension instead makes an [XMLHttpRequest](https://github.com/ampproject/amphtml/blob/master/validator/chromeextension/background.js#L242) to get the non-transformed HTML.

I speculate that Chrome is not sending the mobile user agent along with it from devtools and is instead getting the non-AMP version of the page.

**Comment by ithinkihaveacat** [comment]
Ah, that makes sense, although the problem might be with the Chrome extension mechanism not propagating the (spoofed) user agent, rather than devtools. (A `fetch("/")` in the console uses the correct UA, though I didn't dig any deeper.)

**Comment by Gregable** [comment]
Closing the issue. Feel free to reopen if I misunderstood.

I'm entertained that this issue is a thread between two usernames of `ithinkihaveacat` and `honeybadgerdontcare`.
