### ISSUE TITLE
[Feature Request] Whitelist date related functions on amp-bind

### ISSUE THREAD

**Issue by plegner** [ampproject/amphtml#8040]
On a shop or restaurant website, you might want to indicate if it is currently open or closed, or feature different content at different times of day (e.g. breakfast/lunch/dinner).
On a shopping or auction website you might want to have different styling based on how much long an item/sale is available.

This could be achieved by whitelisting/providing certain date related functions in amp-bind:

```
<amp-date id="myState" name="today" value="now"></amp-date>
<p [class]="myState.today.getUTCHours() > 10 || myState.today.getUTCHours() < 19 ? 'visible' : 'hidden'">We're open!</p>
```

These expressions could even be evaluated continuously, to allow real time changes to the page.

**Comment by ericlindley-g** [comment]
Thanks for the feature request, @plegner ! 

Would be interesting to have some kind of date/time component to show the specific, current time (or elapsed time * since * a certain time). Might also be interesting to specify ranges of dates to display text, rather than date ("Just now" for items updated in the last 30 seconds, for instance).

One complication would be getting the formats and actual time right across all geos.

Would also be interesting to hide/show items conditional on a time range with this component. Since bindings don't affect the page at load time, though, I'm not sure if it would be possible to use bind in the way you've described for these particular use-cases. Another approach would be to allow evaluation of date/time to affect the contents of a div with a static size, so hiding/showing its contents wouldn't re-size the element.

/cc @choumx @aghassemi

**Comment by mcmd** [comment]
Hi, resurrecting this FR.

The time-elapsed-since-a-given-date is now covered by amp-date-countdown, but conditional format based on date is still a valid use case. This for instance:

A restaurant offer only active during dinner times on weekdays
A "Call us" button only enabled during the times the call center is open

In a non AMP page, doing this in the client side is trivial. In AMP, you would have to either use amp-list (which would require you to expose a new endpoint for this, with the complexity that may represent for some developers) or, potentially, amp-script.

Is amp-script going to be the recommended way of doing this client side? If not, could this FR be retriaged?

**Comment by conwaydev** [comment]
This would be real helpful right now, https://github.com/ampproject/amphtml/issues/13797 was closed in favor of a server-side work around but I'd love to be able to (client-side) create an amp-bind-macro that converts a string (think 3pm CST) based off the user's chosen timezone, but I can't accomplish this with https://amp.dev/documentation/components/amp-bind/#allowed-listed-functions

**Comment by choumx** [comment]
@conwaydev Do you need to display this data on page load? If so, you probably want to try `amp-script`.
