### ISSUE TITLE
Bind performance guarantees

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#8057]
Determine & test:

- [x] Limit # of bindings per AMP documents (determine what N is)
- [x] Limit to complexity of individual expressions (Metric could be # of nodes in abstract syntax tree expression)
- [x] Limits on amp-state (maybe file size, maybe # of characters?) — may not need this, but could be worth testing

**Comment by choumx** [comment]
`amp-state` parses its JSON in `buildCallback` which currently can (though shouldn't) impact render latency. Another option is to use `requestIdleCallback` or run the parsing in a worker.

Parsing 100KB of JSON takes 10-20ms which seems like a reasonable cap. Ideally we'd enforce this in the validator rather than at runtime.
