### ISSUE TITLE
All layouts reported us unsupported for amp-ad

### ISSUE THREAD

**Issue by tlong2** [ampproject/amphtml#8218]
The isLayoutSupported function was removed from `<amp-ad>` in https://github.com/ampproject/amphtml/commit/980e7ca38269b695def57bf99e7a8abd58630b21. isLayoutSupported is apparently called before the element is upgraded meaning it falls back to the BaseElement version which is:
`
  isLayoutSupported(layout) {
    return layout == Layout.NODISPLAY;
  }
`
Thus every type of `<amp-ad>` layout is considered invalid.

Was able to see this on http://amp.autoplaced.com.

**Comment by jridgewell** [comment]
Marking as a high priority for now. Having elements call `#isLayoutSupported` without first being upgraded feels like a potential catastrophe waiting to happen.

**Comment by jridgewell** [comment]
Now I know why this feels so wrong to me, I had already opened an [issue](https://github.com/ampproject/amphtml/issues/5980) about it!

**Comment by jridgewell** [comment]
Looking into this further:

This isn't widespread, because most of the time the implementation is still the [`ElementStub`](https://github.com/ampproject/amphtml/blob/16e555b4ea0454877a0da824f91be213d6aa1888/src/element-stub.js), which allows any layout type. I'm not entirely sure when the element get's upgraded from `ElementStub` to the correct (still not entirely upgraded) BaseElement implementation. Whenever we're in this state we have a real issue. Once it gets fully upgraded, we're back to normal behavior.

**Comment by dvoytenko** [comment]
@jridgewell Not yet exactly sure where this risk condition happens. But as a quick fix let's allow layouts ASAP.

**Comment by aghassemi** [comment]
@tlong2 production was also patched by this fix. http://amp.autoplaced.com no longer produces those errors.
