### ISSUE TITLE
amp-live-list: feature request: support ajax pagination

### ISSUE THREAD

**Issue by rowangray** [ampproject/amphtml#8314]
Currently amp-live-list uses a simple href pagination system which requires a page refresh to switch pages.

We're trying to use the live-list component to display an updating comment feed, so would rather not have the entire page refresh to get additional comments or paginate the comments

Allowing the update poll to include a query string or having a separate pagination function that accepts one or more variables would be useful, this will give a lot more control over the amp-live-list content items that the server can return.

**Comment by erwinmombay** [comment]
cc @ericlindley-g I think this is a really interesting request that might be doable. Only concern is the unknown size of the amp-live-list at that point. 

cc @dvoytenko for input on sizing and layout concerns.

**Comment by ericlindley-g** [comment]
@erwinmombay  — might be worth sync'ing with @aghassemi and @choumx for the work they're doing on filtering/sorting. I wonder if the same mechanic can be re-used for both?

**Comment by westonruter** [comment]
One thing to note here is that in pagination there would need to be a standard way to hide/omit the previous link, since the next link would only ever be clicked to load more. The previous link would never be clicked so it should never be shown.

Also, in relation to #4524 for updating list without user interaction, `amp-live-list` could also be used to implement infinite scroll.

**Comment by aghassemi** [comment]
(Additional comments regarding this FR on can be found https://github.com/ampproject/amphtml/issues/9423#issuecomment-372471242)
