### ISSUE TITLE
Support referrer-policy for amp-pixel and amp-analytics

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#8372]
We should be able to support this for image requests, and possibly other transports.

Modern browsers support `referrerPolicy` directly, but we need to implement a fallback based on iframes with anonymous origins as a fallback. That means we can likely only support the value `none`.

**Comment by lannka** [comment]
We will be introducing an optional `referrerPolicy` attribute to `amp-pixel`. 
```html
<amp-pixel src="https://abc.com/pixel" referrerPolicy="no-referrer">
```

For browsers with support, the new attribute will be directly carried over to the `<img>` element.
Otherwise, a iframe based polyfill will be used to scrub referrer if and only if `referrerPolicy="no-referrer"`.

@cramforce let me know if it sounds right.

**Comment by cramforce** [comment]
The attribute name is `referrerpolicy` (lowercase p) :)

The Safari that launched last week support `fetch` with `referrerpolicy`, so we can use that as an intermediate polyfill if we want to. Overall, however, we need to be conscious about `amp-pixel` size since this is a core extension.
