### ISSUE TITLE
[Feature Request] Allow shorter SW Iframe delay

### ISSUE THREAD

**Issue by zackargyle** [ampproject/amphtml#8376]
## Feature Request
Currently the iframe for a service worker install is loaded after a 20 second delay. This is pretty worthless, to be quite frank. The reason I want to use the iframe rather than the static `src` property is cookies. I want to be able to run experiments with the service worker I install via the AMP page to see what works best for precaching. With a 20 second delay, I'm not gonna get a big sample size :(

**What I would love:** an attribute allowing a shorter delay (minimum 3-5 seconds probably to still not choke up the network and rendering).

**Comment by cramforce** [comment]
I was wondering why nobody asked. Super happy to reduce this. I think we should go down to 10 seconds.

I don't understand the "The reason I want to use the iframe rather than the static src property is cookies" sentence. It isn't either or. The iframe is available when running on an AMP cache, while the SW is loaded when already on the origin.

**Comment by zackargyle** [comment]
Hey @cramforce. So our `/sw.js` path is actually a handler rather than a static file. Then we bucket you into an experiment group and serve you a service worker based on what group you're in. For the bucketing we need your pinterest.com cookies. Maybe I misunderstood how the `amp-install-serviceworker` was working, but it looked like if I wanted the cookies I needed the iframe to our `sw.html` installer.

**Comment by cramforce** [comment]
Cookies should definitely work on you `/sw.js`. I just researched that the other day.
