### ISSUE TITLE
Tracking scrolling using amp-analytics: add a selector

### ISSUE THREAD

**Issue by javierparis** [ampproject/amphtml#8403]
## Description ##
Currently, the scroll event is based on the page dimensions. It would be very interesting to be able to track a subsection of the page, given a selector.
For instance, imagine an article (or a specific piece of information) in a page. And imagine that the article is what you most care regarding tracking the user scroll. 
The article would start and end in a specific height within the page container. We could wrap that article and give it an id, and use a selector property in the analytics event, for tracking the scroll percentage based on that html element id.

**Comment by aghassemi** [comment]
/to @dvoytenko 
@zhouyx Is this at all related to what you have been working on recently for scoping analytics?

**Comment by zhouyx** [comment]
Scope does sounds like a possible solution to me in this case. @dvoytenko WDYT?

**Comment by dvoytenko** [comment]
@javierparis Would this be solved by the visibility triggers? I.e. some sections in the doc will trigger visibility. That trigger is pretty robust with time conditions and percent visibility. And %/time of visibility would seem to be easier to normalize/understand vs scroll positions that are very sensitive to device size.

If that would work in principal, visibility has an issue that only AMP elements can be tracked. We can expand that to all other DOM elements. See #4449.

Otherwise, this is not about ads, is it? If so, I'm not sure how scoping would help here.

**Comment by rudygalfi** [comment]
I think this could be solved by visibility triggers, but it also makes a great deal of sense as a spec attached to the `scroll` trigger. For instance, we could defined a `scrollSpec` that has a field called `selector`.

**Comment by zhouyx** [comment]
So this is not to track the scroll within one element, but the scroll of part of the document. 
If we are going to track scroll of a certain area of the document, I agree that visibility trigger may be a better feature to use. 
Closing the issue for now. Feel free to reopen if we still see the requirement. Thank you

**Comment by tom-essp** [comment]
Hi, we were trying to add a selector to scroll percentage trigger to our content publishing website. We only want to measure this on the article part and not rest of the page. It would be really great if we can get that feature added
