### ISSUE TITLE
ABE lightbox samples broken in iOS when in the viewer

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#8504]
## Repro
- on iOS (I have tested with 10.3 and 10.2), search for `amp by example lightbox`
- view the result link (opens in SRP AMP viewer)
- tap OPEN LIGHTBOX
- notice it does not work. (it actually opens but is invisible)
- Does NOT happen when not viewed in the viewer

## Issue
With a bit of debugging, `-webkit-overflow-scrolling: touch` that comes from `#i-amphtml-wrapper` seems to cause this. Disabling that rule fixes the issue (also explains why it only happens in the viewer)

Please also **note: lightbox is _NOT_ broken on iOS everywhere** (e.g. search for "shoes ebay" and those pages are fine). Issue seems to be specific to ABE. Probably a certain CSS from ABE in combination with `-webkit-overflow-scrolling: touch` is causing this.

/to @dvoytenko Would be nice to figure out if there is a solution for this in AMP instead of ABE.
/cc @sebastianbenz

**Comment by dvoytenko** [comment]
@sebastianbenz Do you know what might be causing this?

**Comment by muxin** [comment]
@sebastianbenz When I'm inspecting the page https://www.google.com/amp/s/ampbyexample.com/components/amp-lightbox/ on safari ios, the `<amp-lightbox id="my-lightbox">` is inside a <div class="abe-preview">, and if I disable the `overflow: auto` in `abe-preview`'s css properties the problem is gone. What's the reason for class `abe-preview` to have `overflow: auto`? Also, I wonder why the code `<amp-lightbox id="my-lightbox">` is not along with the `OPEN LIGHTBOX` button section.

**Comment by sebastianbenz** [comment]
Thanks @muxin for looking into this. The `overflow: auto` was in place if the preview is larger than the available space, but I don't think that this happens so far.

**Comment by sebastianbenz** [comment]
Fixed for ABE now: https://www.google.com/amp/s/ampbyexample.com/components/amp-lightbox/

**Comment by aghassemi** [comment]
verified fixed
