### ISSUE TITLE
Google Analytics not working

### ISSUE THREAD

**Issue by Shreerang** [ampproject/amphtml#8527]
## Short description of your issue:

Google Analytics does not seem to be working on AMP based sites.

## How do we reproduce the issue?

I am using the chrome Tag Assistant extension to check this and the on AMP based sites the result always is "Tags not found". Even on ampproject.org, we have the same situation. 

## What browsers are affected?

All browsers I guess.

## Which AMP version is affected?
1490899213109

**Comment by 1987yama3** [comment]
me too.

I did try it at ampstart project(clone).

when don't change(default trackingID), it is not send to Google Analytics. but it send to ```https://stats.g.doubleclick.net/r/collect```. 
when change tracking ID to mine, it is send to Google Analytics. and it has no problem.

following is send to doubleclick.net request URL.

```
https://stats.g.doubleclick.net/r/collect?v=1&aip=1&t=dc&_r=3&tid=UA-67833617-1&cid=amp-jnXOtCdz-zhYVHvfCT6i5nK4NkKfKOHtokre9EVqwKY_mklva63OZ4ZvsemkqVSp&jid=0.24394279072841485&_v=a1&z=0.30742841110087626
```

**Comment by rudygalfi** [comment]
All analytics integrations in AMP use amp-analytics, which doesn't run any of the analytics vendors' specific JavaScript like Google Analytics' analytics.js. This means that the [Chrome extension you mentioned](https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk) is likely unaware of it and won't detect it.

When I look at the network traffic on ampproject.org, I do see Google Analytics collection occurring. For example:

```
https://www.google-analytics.com/collect?v=1&_v=a1&ds=AMP&aip=true&_s=4&dt=Accelerated%20Mobile%20Pages%20Project%20%E2%80%93%20Accelerated%20Mobile%20Pages%20Project&sr=412x732&_utmht=1490938606281&cid=amp-5FNWwm0r2p-QrACTqOcrSWhGchu8jCWyxFjqaWCO2VOIhf6i07e-2j-dr8bGfx0T&tid=UA-67833617-1&dl=https%3A%2F%2Fwww.ampproject.org%2F&dr=&sd=24&ul=en-us&de=UTF-8&t=event&jid=&ec=visible&ea=hero-image%20visible&el=totalTimeMin%3A%205000&ev=5004&a=6336&z=0.8044003500321852
```

Have you observed any impact on data reported in Google Analytics, or is the concern just due to the extension reporting "No tags found"? If it's the latter, then the above explanation should cover the reason why.

**Comment by 1987yama3** [comment]
Please see following...

![capture_20170331_1500](https://cloud.githubusercontent.com/assets/29188/24538228/da39eb98-1622-11e7-9c16-d6d3e29a46bc.png)

**Comment by rudygalfi** [comment]
I'm not reproducing. Are you using anything on the client side that might block requests like an ad blocker?

**Comment by Shreerang** [comment]
My site is akshataphotography.com and I see the same thing that @1987yama3 is seeing on his!
<img width="1436" alt="screen shot 2017-03-31 at 1 44 44 pm" src="https://cloud.githubusercontent.com/assets/3829231/24568834/5f229784-1618-11e7-9427-92de87b4d28f.png">

**Comment by rudygalfi** [comment]
Thanks for the link. It looks like the page-level visibility isn't firing. We're taking a look.

**Comment by rudygalfi** [comment]
We think this is working as intended. But it looks broken because of how the Chrome console is showing the network traffic. The pageview request is getting 302'd to a doubleclick.net URL. It's actually being sent as expected. In Chrome, however, the original request isn't shown sometimes.

To check this, you can open up Firefox, and you'll see:
<img width="1631" alt="screen shot 2017-03-31 at 15 15 53" src="https://cloud.githubusercontent.com/assets/3888212/24571329/4870204e-1625-11e7-86df-bfbef1191c64.png">
