### ISSUE TITLE
Unacceptable, forced to use CDN instead of self hosting.

### ISSUE THREAD

**Issue by jsmad** [ampproject/amphtml#8568]
I find it **unacceptable** that we are forced to use a foreign server for loading the amp scripts.

This is a security risk (admittedly a minor one) but more importantly it is an **information leak**. I am not interested to share information about my users with google or whoever runs the CDN, including referrer, browser and other user information.

Thus, we should be able to host the scripts on our own, without "white listing" domains/urls in the script tag and without errors when testing with "#development=1".

Thank you.

**Comment by bjalford** [comment]
On the flipside, doesn't it come with the benefit that a user knows it's the 'true' AMP files being executed and not manipulated, with all their inbuilt validation etc? Also, couldn't there also be a speed improvement if those files are distributed so that they could be cached when navigating between AMP sites?

**Comment by cramforce** [comment]
I started the discussion here.
https://medium.com/@cramforce/decentralized-hosting-of-amps-javascript-npm-for-the-web-75ed698a4d64

This is definitely something that can be addressed if people feel strongly about it.

You do, however, overestimate the value of the information sharing since the resources themselves are cached and hence only a small subset of page views actually trigger requests.

**Comment by jsmad** [comment]
@bjalford, I am not sure what a 'fake' AMP js file could be about, but I'm open to it. Most libraries use Subresource Integrity to help mitigate fake scripts. About caching, I prefer to do my own caching and not depend on 3rd parties, so a public cdn is a negative for me.

@cramforce, well written, thank you for taking the time to analyse the issue. I do feel strongly about information leakage and even a single IP & referrer hit is a problem. By opening this ticket, I did not imply that the AMP script should only be served by self hosting, my suggestion is to at least allow the admin/developer to choose between a public CDN and self hosting.

Thank you.

**Comment by adelinamart** [comment]
@cramforce any updates here? Thanks
