### ISSUE TITLE
ITI: read position progress bar 

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#8658]
Would like to implement a scroll bar to to indicate read position of AMP document.

Similar to this kind of thing:  http://www.cssscript.com/demo/tiny-reading-progress-indicator-pure-javascript-rpbar-js/

Would anyone else find this useful? Any feedback before we start looking into coding?

**Comment by aghassemi** [comment]
@bjalford I think this UI will be useful in general. Instead of a dedicated component however, we could add support for such scroll-bound effect to https://github.com/ampproject/amphtml/issues/8411. 

Currently #8411's design assumes one viewport scroll as duration of an effect, simply allowing users to pick "1 page scroll" instead of "1 viewport scroll" as duration can enable this and more.

#8411 is currently in progress, I recommend waiting until enough of scroll-bound animation work is in place and then evaluating whether this makes sense as a separate component or extending scroll-bound animation to support "1 page scroll" instead.

**Comment by bjalford** [comment]
Thanks. Makes sense.

**Comment by niutech** [comment]
Another solution is to use a [pure CSS scroll depth indicator](https://www.cssscript.com/demo/pure-css-scroll-depth-indicator/).

**Comment by tobiasfrenkler** [comment]
Very useful feature, especially for longer articles. I would love to see it implemented. Is it still under consideration?

**Comment by aghassemi** [comment]
@tobiasfrenkler a component for this is not prioritized but this is doable in AMP using `amp-position-observer`, here is an example: https://codepen.io/aghassemi/pen/MxQxZR?editors=1111

**Comment by aghassemi** [comment]
deduping with same request on #19193
