### ISSUE TITLE
Add support for multiple custom elements in a single extension

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#8727]
Conceptually, custom elements and extensions are different, but we currently require a 1:1 mapping between them.  We should lift this requirement and allow extensions that specify multiple custom elements (but not a single custom element split across multiple extensions).

**Comment by choumx** [comment]
Is this not already possible with multiple `AMP.registerElement` calls in the extension's entry point, (e.g. `amp-ad.js`)?

**Comment by dvoytenko** [comment]
Registration is definitely possible. But this system works two ways:

1. An extension when loaded registers elements. This already works. As soon as elements are registered, they have static layout applied (if not applied yet) and processed otherwise.
2. All extension elements are initially preregistered _before_ extension is even downloaded. This is done by searching for `<script custom-element="amp-xyz">` and stubbing these elements. This allows us to perform static layout immediately without waiting for the extension to be downloaded. It's an important part of avoiding FOUC. When extension later arrives, the elements go through upgrade.

**Comment by adelinamart** [comment]
@newmuis any updates here? Thanks.

**Comment by cramforce** [comment]
Should we close this or #9143 or are they different?

**Comment by newmuis** [comment]
This sounds like a duplicate of #9143, which has more context around a possible solution.
