### ISSUE TITLE
Validator should flag missing script tags

### ISSUE THREAD

**Issue by cantrell** [ampproject/amphtml#875]
I've run into a couple of cases where I've used AMP HTML tags without their corresponding `script` "imports," but the validator doesn't catch it. For example, in you insert an animated GIF using amp-anim (without the corresponding amp-amin JavaScript tag), the placeholder will be rendered (presumably since the amp-img implementation is in AMP core), but the validator doesn't flag the missing JavaScript tag.

**Comment by cramforce** [comment]
Yes! We were tracking this already, but I can't find the issue.

**Comment by eddhannay** [comment]
@cramforce Is there any estimate for when the validator will be open sourced?

**Comment by cramforce** [comment]
No, but before Christmas :) Maybe in a few days.

**Comment by Gregable** [comment]
Follow up question on this issue. Is there a good reason to flag the opposite relationship: a `<script>` import without a corresponding tag that requires it? 

This represents a small performance hit, but is otherwise not a big deal? I would imagine requiring it would break some pages where the site owner includes the superset of all imports needed by any page on the site into a reused template, so my initial thought is that this would be a bad idea to make bidirectional.

**Comment by Gregable** [comment]
The validator now flags these missing script tags. Let me know if you see any issues with it.
