### ISSUE TITLE
amp-video placeholder behaviour

### ISSUE THREAD

**Issue by quarterto** [ampproject/amphtml#8896]
According to the [`amp-video` documentation](https://www.ampproject.org/docs/reference/components/media/amp-video):

> One or zero immediate child nodes can have the `placeholder` attribute. If present, this node and its children form a placeholder that will display instead of the video. A click or tap anywhere inside of the `amp-video` container will replace the placeholder with the video itself.

However, in practice, it's behaving as just the default `placeholder` from `BaseElement`, i.e. the placeholder is removed as soon as the element gets layout. I see nothing in `amp-video.js` or `video-manager-impl.js` that suggests the tap-to-play behaviour.

Is this a bug in the implementation? Or are the docs out of date (some holdover for the `amp-iframe` click to play thing #571 #1361 #1386 perhaps)?

**Comment by ericlindley-g** [comment]
@quarterto , I think your guess of this being the result of out-of-date documentation is correct. Is that right, @aghassemi ? Can we just remove the "click or tap" language in this section?

**Comment by quarterto** [comment]
@ericlindley-g it's a shame if that's the case, I was hoping to be able to use our [standard video placeholder](https://www.ft.com/__origami/service/build/v2/demos/o-video@2.5.0/placeholder). How about if I opened a PR implementing the documented behaviour?

**Comment by jridgewell** [comment]
I think this is referring to the `poster` attribute, right?

**Comment by aghassemi** [comment]
@quarterto @ericlindley-g Documentation is wrong in this case, definitely not how `placeholder` works. Given the `poster` support, `placeholder` does not make much sense for `amp-video`. (and I rather leave the behaviour of `placeholder` consistent across components instead of special casing it here). I will update the documentation.

Good news is click-to-play custom overlay is already possible using standard AMP actions. Here is a working, responsive and valid sample: https://codepen.io/aghassemi/pen/QvGgbr . (Important part of that code is `on="tap:myVideo.play, myOverlay.hide"` rest is just layout and styling)

I will update amp-by-example with this sample for future reference.

Hope this resolves your issue @quarterto.
