### ISSUE TITLE
amp-youtube: Cannot read property 'contentWindow' of null

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#9036]
```
TypeError: Cannot read property 'contentWindow' of null
    at W.push.f.k.A (https://cdn.ampproject.org/rtv/011493142602549/v0/amp-youtube-0.1.js:18:73)
    at https://cdn.ampproject.org/rtv/011493142602549/v0/amp-youtube-0.1.js:15:352
```

Seems we're getting a message before the iframe has been laid out. We should probably check all those other message handlers in the other players.

Also, we're registering the youtube message listener twice. WTF?

**Comment by aghassemi** [comment]
We _were_ listening to messages twice, https://github.com/ampproject/amphtml/pull/8981 fixed that.

We couldn't be getting messages before it was laid out, but we were still receiving messages after it was unlaid out (because of the double listen). Should not happen anymore after https://github.com/ampproject/amphtml/pull/8981 since the only listener is also removed same time as `this.iframe_` = null
