### ISSUE TITLE
amp-bind does not honor 'autoplay' in code example

### ISSUE THREAD

**Issue by richardrabbat** [ampproject/amphtml#9084]
**Please only file bugs/feature requests for AMP here.**

## What's the issue?

autoplay of the amp-video element is not honored.

## How do we reproduce the issue?

1. Go to:
https://ampbyexample.com/components/amp-bind/#binding-attribute-values

2. set to enable experiment

3. Use a large monitor to make sure the video of the dogs is showing, along with the "Set to Cat" button.

4. Click "Set to Cat"

Result:

The source of the video changes as expected BUT
The video does not start playback, even though it's set to autoplay

(note that if the amp-video tag had added the autoplay attribute to <video>, that would have worked)
 
## What browsers are affected?

Tested on Chrome and Safari

## Which AMP version is affected?

Experimental version with amp-bind support

**Comment by choumx** [comment]
Thanks for the bug report! Kevin, can you take a look please?

/to @kmh287 /cc @aghassemi

**Comment by aghassemi** [comment]
@kmh287 The issue is when `src` changes, video reloads but `video-manager` which handles `autoplay` has not idea this happened.

I suggest:
- [ ] Add a new `RELOAD` event to `VideoEvents` in `video-interface.js`
- [ ] Have `amp-video` dispatch the RELOAD event when `src` is changed with `bind`
- [ ] Have `video-manager-impl` react to the RELOAD event by adding:
```
    listen(entry.video.element, VideoEvents.RELOAD, () => {
      entry.updateVisibility();
    });
```
to `maybeInstallVisibilityObserver_()`
