### ISSUE TITLE
Using VARIANTS can cause silent failures

### ISSUE THREAD

**Issue by pdufour** [ampproject/amphtml#9108]
## What's the issue?

Using the `VARIANTS` variable in a `amp-analytics` block with:
`amp-experiment` JS file included but
**no** `amp-experiment` block added
causes the amp-analytics requests to never fire without logging any errors.

If you have:
**no** `amp-experiment` JS file
**no** `amp-experiment` block added causes the requests to never fire 

This triggers the error `runner-3.41.10.min.js:1 To use variable  VARIANTS , amp-experiment should be configured`. This error should be shown in the first case as well if it's going to fail. Instead it causes a silent failure.

## How do we reproduce the issue?

http://jsbin.com/kihexutidu/1/edit?html,output

1. Include `VARIANTS` somewhere in a `amp-analytics` block
3. Include the `amp-experiment` JS file in your head.
3. See that no network request to your configured URL is made.

## Expected behavior
- This should throw the error `To use variable  VARIANTS , amp-experiment should be configured`

**Comment by lannka** [comment]
@pdufour thanks for reporting. This is a publisher mis-configuration. Unfortunately it's hard for AMP runtime to detect the 1st error case because the config block can just be very late parsed by the browser, that we can't know its existence early enough.

One thing we could possibly try is check such an error when documentReady event is received. However, I felt this might be out of scope of AMP runtime. 

@honeybadgerdontcare do you think this is something that validator should enforce?

**Comment by honeybadgerdontcare** [comment]
@Gregable thoughts?

**Comment by jridgewell** [comment]
I'm more worried about the second report. First one should be handled by validator.

**Comment by lannka** [comment]
@jridgewell we already print errors for the 2nd case.

**Comment by jridgewell** [comment]
From the report, we the analytics never fire. That's a problem, it should error and report with the un-replaced URL.
