### ISSUE TITLE
Scrollable carousel: make it easier to customize margin

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#9226]
### First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

### What you will need to know
- CSS
- Javascript

### Background
Amp carousel type="carousel" (See [doc](https://www.ampproject.org/docs/reference/components/amp-carousel) and [example](https://ampbyexample.com/components/amp-carousel/)) is an AMP component used to display a list of images as a continuous strip. Developers using this component can customize the styles by applying to specific css selectors. We have a default margin set for each scrollable carousel slide as follows:
```
.i-amphtml-scrollable-carousel-container .amp-carousel-slide {
  margin-left: 8px;
}

.i-amphtml-scrollable-carousel-container .amp-carousel-slide:first-child {
  margin-left: 0px;
}
```
Developers can customize the margin by using the following css:
```
.i-amphtml-scrollable-carousel-container .amp-carousel-slide {
  margin-left: 10px;
}
```

### Motivation
In order to make it easier to customize, we could reduce the css selector to one class so that developers can write css like the following:
```
.amp-scrollable-carousel-slide {
  margin-left: 10px;
}
```

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] Locate [`buildCarousel`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/0.1/scrollable-carousel.js#L55) method in `scrollable-carousel.js`
- [ ] When adding cell/slide to `this.container_`
```
    this.cells_.forEach(cell => {
      this.setAsOwner(cell);
      cell.classList.add('amp-carousel-slide');
      this.container_.appendChild(cell);
    });
```
Add another css class `amp-scrollable-carousel-slide` to each cell/slide, so that the css selector is more specific (`amp-carousel-slide` is used for both amp-carousel `type=carousel` and `type=slides` thus is not specific enough by itself).
- [ ] Open [`amp-carousel.css`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/0.1/amp-carousel.css#L184) and change the default styles for scrollable carousel slide to be the`amp-scrollable-carousel-slide` we just added. 
- [ ] After the code change, to test the default style is still working, checkout http://localhost:8000/examples/carousel.amp.html
- [ ] Test that customizing the margin can be done using the class `amp-scrollable-carousel-slide` by modifying [`examples/carousel.amp.html`](https://github.com/ampproject/amphtml/blob/master/examples/carousel.amp.html#L9) file. But the example file changes don't need to be committed.
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review) and request a code review from me (@muxin).  Mention `Fixes #9226` in the description.
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by muxin** [comment]
### First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

### What you will need to know
- CSS
- Javascript

### Background
Amp carousel type="carousel" (See [doc](https://www.ampproject.org/docs/reference/components/amp-carousel) and [example](https://ampbyexample.com/components/amp-carousel/)) is an AMP component used to display a list of images as a continuous strip. Developers using this component can customize the styles by applying to specific css selectors. We have a default margin set for each scrollable carousel slide as follows:
```
.i-amphtml-scrollable-carousel-container .amp-carousel-slide {
  margin-left: 8px;
}

.i-amphtml-scrollable-carousel-container .amp-carousel-slide:first-child {
  margin-left: 0px;
}
```
Developers can customize the margin by using the following css:
```
.i-amphtml-scrollable-carousel-container .amp-carousel-slide {
  margin-left: 10px;
}
```

### Motivation
In order to make it easier to customize, we could reduce the css selector to one class so that developers can write css like the following:
```
.amp-scrollable-carousel-slide {
  margin-left: 10px;
}
```

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] Locate [`buildCarousel`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/0.1/scrollable-carousel.js#L55) method in `scrollable-carousel.js`
- [ ] When adding cell/slide to `this.container_`
```
    this.cells_.forEach(cell => {
      this.setAsOwner(cell);
      cell.classList.add('amp-carousel-slide');
      this.container_.appendChild(cell);
    });
```
Add another css class `amp-scrollable-carousel-slide` to each cell/slide, so that the css selector is more specific (`amp-carousel-slide` is used for both amp-carousel `type=carousel` and `type=slides` thus is not specific enough by itself).
- [ ] Open [`amp-carousel.css`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/0.1/amp-carousel.css#L184) and change the default styles for scrollable carousel slide to be the`amp-scrollable-carousel-slide` we just added. 
- [ ] After the code change, to test the default style is still working, checkout http://localhost:8000/examples/carousel.amp.html
- [ ] Test that customizing the margin can be done using the class `amp-scrollable-carousel-slide` by modifying [`examples/carousel.amp.html`](https://github.com/ampproject/amphtml/blob/master/examples/carousel.amp.html#L9) file. But the example file changes don't need to be committed.
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review) and request a code review from me (@muxin).  Mention `Fixes #9226` in the description.
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by jaycribas** [comment]
Hey there, first time contributor, I'd love to work on this today.

**Comment by jridgewell** [comment]
Awesome, go for it @jaycribas!

**Comment by jaycribas** [comment]
Hello @muxin - submitted a pull request for ya!
