### ISSUE TITLE
Feature Request: No way to check AMP Validation State using Vanilla HTML+JS

### ISSUE THREAD

**Issue by johnnyshankman** [ampproject/amphtml#9371]
## What's the issue?

_**Feature request:**_

_Gherkin:_
As a developer writing end to end tests
When I go to an AMP page with `#development=1` appended to the URL
I expect that I can check the validation state of the current page using a single line of synchronous JS in the console

_More info_
I think it makes the most sense for there to be a data attribute appended to the `<html amp>` element in this fashion `<html amp amp-valid>` and for failure `<html amp amp-invalid>`, but **only** when in development mode.

That way the developer can reliably check that attribute in order to assert the validation state of the AMP page without any GET requests to third parties, XHR, or Node. 

I envision using something like
`return document.documentElement.hasAttribute('amp-valid')` in my Ghost Inspector tests or in my Selenium/Capybara feature tests. I'd just have to account for the 1-2 seconds it takes for the validator to run before asserting.

## How do we reproduce the issue?

N/A

## What browsers are affected?

N/A

## Which AMP version is affected?

Latest 1494446565961

**Comment by jridgewell** [comment]
Why aren't you just using the [validator](https://www.npmjs.com/package/amphtml-validator)?

**Comment by johnnyshankman** [comment]
@jridgewell not possible from something like Ghost Inspector or Ruby based feature testing a la Cucumber.

**Comment by jridgewell** [comment]
Can you use Cloudflare's validation API?

**Comment by johnnyshankman** [comment]
@jridgewell Yes, I could write a separate test suite that solely hits Cloudflare's validation API endpoint and then parses the JSON to check for validity. This just seems like a redundant/unnecessary step  to me since I'm already running E2E feature tests against fully-rendered AMP pages in Selenium/Capybara (or alternatively Ghost Inspector).

Wouldn't it be more efficient to take my same E2E tests  _but_ do them against pages in `#development=1` mode _and then_ as the very last step run Capybara's `evaluate_script` to assert something like `window.AMP.pageIsValid` becoming true?

That way I get clean E2E feature tests which test for correct content _and_ amp-validity without having to do any asynchronous API calls to 3rd party services.

[Here's the Capybara method](http://www.rubydoc.info/github/jnicklas/capybara/master/Capybara/Selenium/Driver#evaluate_script-instance_method) I'm hoping to leverage in this scenario and [here's a similar Ghost Inspector feature](https://ghostinspector.com/docs/executing-javascript/#assert) that would also do the job.

**Comment by johnnyshankman** [comment]
Another reason why using Cloudflare isn't a perfect solution: 

We host our CI/pre-prod builds on a private server requiring username+password credentials. We'd have to expose our credentials into the URL using `name:pwd@url.com` syntax in order to let Cloudflare through our authentication when validating against new builds and looking for smoke before going to production. Not ideal.

**Comment by jridgewell** [comment]
/to @powdercloud. Ideally, the validator included with `#development=1` would have just have a `validate` that works like the NPM module.

**Comment by powdercloud** [comment]
I looked into it for a bit. The status quo is that when #development=1 is appended, this code runs:
https://github.com/ampproject/amphtml/blob/master/src/validator-integration.js
Specifically, there's a call to amp.validator.validateUrlAndLog.
And it looks like once this is all done and I'm in the browser's console (I use Chrome), I can put 
amp.validator.validateUrlAndLog(window.location.href);
to trigger it again. The method validateUrlAndLog itself is in here:
https://github.com/ampproject/amphtml/blob/master/validator/engine/validator-in-browser.js
The main thing that may surprise at first is that it does a HTTP get request to fetch the page a second time. This is necessary because the DOM from which it was loaded is heavily modified by the AMP runtime once the validator is there, so we really need to get the string again.

If amp.validator.validateUrlAndLog were to also store a result object, would this be sufficient?
Then you could access this with amp.validator.validationResult. It would have all the information, like the status, the errors, parameters for the errors, etc.

The way to graft this together is for amp.validator.validateUrlAndLog to return this object, and for the runtime to store it in this variable. It's a slight bit hacky but makes it so we don't have to add this global variable to engine.js.

Opinions on this most welcome. I'm not familiar with Ghost Inspector etc. Note that with the solution outlined here you'd still end up with an extra HTTP fetch per document you're checking - that's just how @development=1 works.

**Comment by johnnyshankman** [comment]
@powdercloud I noticed the same method and found the same confusion, why is there no function to revalidate the current page and return the state synchronously?

`validateUrlAndLog` is okay, but not nearly as useful because it's async/promise-based (due to the underlying GET request).

Storing the return value in a global variable would be better than the current implementation because our front end tests can always sleep and then check that variable. 

What would be most ideal is `validateCurrentDocumentAndLog`. It would validate the current page and synchronously return `true` or `false`.

**Comment by powdercloud** [comment]
This might be a way.
1) Load the AMP page. E.g. load this one, with development=1 so that the validator gets loaded:
https://www.ampproject.org/docs/tutorials/login_requiring#development=1
2) In the console, run this:
`var request = new XMLHttpRequest(); request.open('GET', location.href, false); request.send(null); var validationResult = amp.validator.validateString(request.responseText);`
validationResult has the status field (in this case 'PASS') and also the errors if there are any. 
Also:
- On my (pretty big) screen this fits into one line ...
- Chrome prints a deprecation warning for making a synchronous request (the last parameter, false, to request.open). Also documented here: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests
- It would be worthwhile checking the other fields of request as well, e.g. request.status and make sure it's 200 before proceeding.
- This scheme fetches the page three times. But perhaps for testing this is a non-issue. If it bothers you, you could make a server side handler on your end which script includes the validator.js and then has a <script> block which runs the code above to invoke it. The server side handler could take the URL / page as a parameter e.g. it could be /amp-validate?doc=path/to/amp.html or similar and if you're making server side stuff anyway this should be easy to do.

**Comment by johnnyshankman** [comment]
@powdercloud that works great with one minor addition.
```
var request = new XMLHttpRequest(); 
request.open('GET', location.href, false); 
request.send(null); 
var validationResult = amp.validator.validateString(request.responseText);
var valid = validationResult.status === "PASS";
```

You are right that it is inefficient but this gets the job done for now, assuming the underlying implementation of the validator doesn't change suddenly. If it does, my tests will start failing and I'll have to refactor or remove the step.

**Comment by powdercloud** [comment]
amp.validator.validateString(inputText) isn't going to change, and neither is the status field of the return value; if we make changes they'll be backwards compatible by necessity because the runtime, the npm library, the chrome extension, etc. depends on this. I also don't see why the behavior of loading this for #development=1 would change.
@johnnyshankman It looks like we're both happy so I'll take the liberty and close this bug. Please feel free to reopen or make another bug as you see fit. Thank you.

**Comment by praharshjain** [comment]
As of October 13, 2018 AMP validation can be checked using - 
window.AMPErrors.length === 0
(supported in https://cdn.ampproject.org/v0.js)

**Comment by johnnyshankman** [comment]
Not true, just checked a page with errors and `window.AMPErrors` was `[]`. I think that's used internally for something else @praharshjain

**Comment by Ladi-Harish** [comment]
I think you will get some solution to using this website [AMP Validator](https://www.ampvalidator.com/).

 By using this website you can test multiple numbers of URLs in a short time. And this site is secure, accurate, fast and easy to use. The most interesting thing is you will get the proper beautified email report.
