### ISSUE TITLE
Clean up unit tests and move all integration tests to integration/

### ISSUE THREAD

**Issue by rsimha-amp** [ampproject/amphtml#9404]
Some integration tests live in the unit tests directory. Discovered via issue #9387

**Comment by lannka** [comment]
@choumx could you take a look the [failed tests](https://travis-ci.org/ampproject/amphtml/jobs/233463856) in test-bind-impl.js ?

It fails locally as well if you do 
```bash
gulp clean
gulp build
gulp test --nobuild --files=extensions/amp-bind/0.1/test/test-bind-impl.js
```

**Comment by lannka** [comment]
And it passes if you do
```bash
gulp clean
gulp dist --fortesting 
gulp test --nobuild --files=extensions/amp-bind/0.1/test/test-bind-impl.js
```

Ideally for unit test we should have no dependency with build at all, i.e., we should be able to do:
```bash
gulp clean && gulp test --nobuild --files=extensions/amp-bind/0.1/test/test-bind-impl.js
```

**Comment by bradfrizzell** [comment]
Currently when running `gulp test` at head, I am seeing 35 test failures. All are related to amp-bind as far as I can tell. @jonkeller reproduced.

**Comment by choumx** [comment]
Thanks for raising this.

Failures are due to 404s because we always fetch the compiled `ww.js` instead of `ww.max.js`. Also, most tests in `test-bind-impl.js` are not really unit tests since they require web worker.

TODO:
- Move `test-bind-integration.js` to `test/integration`.
- Add support for fetching non-compiled URLs in `extension-location#calculateEntryPointScriptUrl`.
- Either move `test-bind-impl.js` to `test/integration` or stub worker dependency.

**Comment by choumx** [comment]
/to @kmh287 Can you work on this? 😃

**Comment by choumx** [comment]
FYI, `amp-bind` unit tests no longer require `gulp dist` which should speed up PR builds. 

In fact, `gulp build --css-only` suffices since it still appears to build web worker.

**Comment by rsimha-amp** [comment]
@choumx, good to hear. I've sent out #9626, which eliminates `gulp dist` from PR runs.

**Comment by rsimha-amp** [comment]
attn: @erwinmombay

**Comment by choumx** [comment]
Closing since `amp-bind` is no longer the bottleneck. I'll follow up with a new issue for removing the `gulp build --css-only` dependency when we're ready for it.
