### ISSUE TITLE
FR: Infinite scroll

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#9423]
Thinking through this, but first idea is allowing scroll events to trigger `amp-list[src]` update if a) w/in certain distance of bottom of document and b) target amp-list element is last child of `<body>`

Though there may be a better approach (e.g. w/ an entirely custom element)

**Comment by jpettitt** [comment]
I think a dedicated element would be the way to go, ideally we'd be able to bring in a section of another amp page and have it display the part we want and bring in any needed amp extensions that were not on the page already.   

We also want the new page to be able to refresh the config so that we could specify the next page dynamically.

Might need to start trimming stuff at the top of the page to save memory ...

**Comment by leonalicious** [comment]
hi, I need this solution too, any workaround approach for this please ?

**Comment by haroon8iconglobal** [comment]
Brother when you will complete this task my company is wait for  trigger !

**Comment by cpapazian** [comment]
if an amp-position-observer component could trigger setState actions, we could implement an amp-list with infinite scroll without additional components. is it possible to loosen this restriction in some situations?

**Comment by haroon8iconglobal** [comment]
I think in scroll event at a time shows only 5 itmes as per screen,
so if someone scroll down upward items should remove or if respectively
scroll up ward so at top most blow items must remove so at the time as per
mentioned item should be only shows

**Comment by ericlindley-g** [comment]
@cpapazian — that's a good point, though creating a new infinite scroll component in order to manage that use case offers the ability to manage other aspects of the UX and make performance optimizations with this use case in mind.  It also means that bind stays simpler (and doesn't need to risk cases where forms submit without explicit user intent).

**Comment by choumx** [comment]
@ericlindley-g @aghassemi @lswang1618 @sebastianbenz Flagging a possibility to have both client-side filtering with infinite scroll if we bundle this into `amp-list` and `amp-bind`. Mostly useful for the e-commerce use case.

Combining a metaprogramming idea from another thread:

```html
<amp-list 
    filter="item.color == 'red' && item.inStock"
    [filter]="condition1 + operator + condition2"
    auto-fetch-on-scroll="page">
```

- `filter` contains an amp-bind expression
- `[filter]` allows you to configure `filter` to change filter conditions
- `auto-fetch-on-scroll` enables infinite scroll feature and is the name of a query param that is automatically added to the URL e.g. `?page=3` for the third fetch

**Comment by sebastianbenz** [comment]
@choumx how would the filter attribute work in amp-list's single-item mode? Sometimes you're forced to use single-item mode even for lists (e.g. when combining amp-list with amp-carousel).

**Comment by choumx** [comment]
Filtering would still work -- the item will either be filtered or won't be. The amp-list could render zero items. Prototype here: #13028

**Comment by sebastianbenz** [comment]
@choumx I'm taking about a different use case:

```
<amp-carousel ...>
<amp-list singleitem items="."  ...>
<template>
{{#slides}}
<div>Slide 1</div>.   <= slides needs to be filtered
{{/slides}}
</template>
</amp-list>
</amp-carousel>
```

**Comment by cpapazian** [comment]
> auto-fetch-on-scroll enables infinite scroll feature and is the name of a query param that is automatically added to the URL e.g. ?page=3 for the third fetch

something like this, combined with https://github.com/ampproject/amphtml/issues/12540, could work for us. are you envisioning the fetch triggering when the user scrolls to the end of the result set?

one small nit: instead of an incrementing page count, could the value reference a field in the previous set of results? we keep a "bookmark" for the results, which is included in a result and passed to the next result. so, a possible `amp-list` result could be: 
```
{
  items: [ ... ],
  bookmark: 'placeholder'
}
```
where items are appended to the list of items and a bookmark field is overwritten with the latest value. then, the request for the next page would get `&bookmark=placeholder` appended to its query string.

i have some non-infinite scrolling prototypes that i'm working on that use this mechanism (though  https://github.com/ampproject/amphtml/issues/11881 blocks us from testing in production).

**Comment by westonruter** [comment]
> first idea is allowing scroll events to trigger amp-list[src] update

Using `amp-list` would not be feasible for a lot of content which we may want to infinite-scroll. Since `amp-list` renders via mustache templates, and since mustache templates restrict the markup to just basic formatting, it would prevent infinite scroll from including images, videos, and any other arbitrary rich content that would be required. Extending an `amp-live-list` to support infinite scroll would be viable, however, since arbitrary AMP markup is allowed. See #8314.

**Comment by aghassemi** [comment]
@westonruter `templates` in `amp-list` support pretty much everything supported at document level including `amp-image`, `amp-iframe`, `amp-video`, etc.. Is there a particular component you could not use in `amp-list`? If so, please file an issue for us and we can look into fixing it.

**Comment by westonruter** [comment]
@aghassemi I'm referring to:

> `Output arbitrary HTML using {{{unescaped}}}. The output of "triple-mustache" is sanitized to only allow formatting tags such as <b>, <i>, and so on.`

https://www.ampproject.org/docs/reference/components/amp-mustache#restrictions

So specifically content output via triple-mustache. For example, a use case is:

```html
<amp-list src="https://example.com/wp-json/wp/v2/posts">
  <template type="amp-mustache">
    <article>
      <h1><a href="{{link}}">{{{title.rendered}}}</a></h1>
      {{{content.rendered}}}
    </article>
  </template>
</amp-list>
```

Where `content.rendered` includes arbitrary amphtml.

**Comment by aghassemi** [comment]
@westonruter Oh I see, yeah that's by design since without having static template, we can't validate the end result would be valid AMP. `amp-live-list` won't have that issue since updates are done in the AMP page itself.

@ericlindley-g Looks like we may need a separate infinite scroll solution for `amp-live-list` (FR #8314) as not all cases can be handled with `amp-list`.

@westonruter What are some of the use-cases you have in mind, if you don't mind sharing? We are also building a separate infinite scroll component that allows loading whole new AMP documents when user reaches end of one. (see https://github.com/ampproject/amphtml/issues/12945)

**Comment by westonruter** [comment]
> What are some of the use-cases you have in mind, if you don't mind sharing?

I'm not sure what else there is to elaborate on. The use case is to list the most recent posts or comments from a REST API endpoint, where the data returned can include amphtml markup which needs to be rendered in an AMP document.

**Comment by aghassemi** [comment]
Thanks @westonruter, just wanted to make sure your use-case is different than infinite scrolling for whole AMP documents which is getting its own component. Infinite scroll for rich comments is definitely a compelling use-case.

**Comment by cathyxz** [comment]
I'm going to close this issue in favor of https://github.com/ampproject/amphtml/issues/14060, which is effectively the same thing.
