### ISSUE TITLE
Tasks queued up in Travis 

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#9500]
![screenshot from 2017-05-23 11 03 00](https://cloud.githubusercontent.com/assets/8496897/26368910/ed3d79e0-3fa7-11e7-9366-80df23208864.png)

anyway to increase the throughput?

**Comment by rsimha-amp** [comment]
There are three potential reasons for this:

1. The setting for auto-cancelling multiple (duplicate) test runs for consecutive commits on one branch had been turned off. I've turned it back on, and this should de-dupe PRs.
2. Now that we're sharding unit tests and integration tests, we're building twice, once on each shard. This will be fixed with #9404 
3. Now that steps are sharded, if a run were to fail early prior to builds, the unrelated shards will still be run. This is a case of a shorter wait in the best case, but a potentially longer wait in the worst case. I'm investigating a way to cancel all jobs for a run if one job fails.

**Comment by choumx** [comment]
Addendum to #2 above, we should skip building the runtime since integration tests are skipped on PR builds anyways.

**Comment by taymonbeal** [comment]
Is there any instrumentation or profiling that tells us how long is spent on each step of the CI pipeline?

**Comment by rsimha-amp** [comment]
@taymonbeal, all the build and test tasks kicked off by pr-check.js are instrumented. Open the logs for each shard to see how long they took.

**Comment by taymonbeal** [comment]
Do you need `sudo: required`? Removing it means Travis doesn't have to spin up VMs. And there's no reason in principle why it shouldn't be possible to install Chrome without root, is there?

**Comment by rsimha-amp** [comment]
/cc @erwinmombay to comment on why we needed sudo, and whether we still do.

From  http://docs.travis-ci.com/user/trusty-ci-environment/, there is now beta support for trusty without sudo, although, as you point out, it doesn't spin up VMs, and therefore, doesn't offer the same kind of no isolation between consecutive test runs since there might be state that persists between builds.

**Comment by taymonbeal** [comment]
It still offers full isolation. It's just that isolation is achieved through Docker containers, not through VMs, so it's faster. That's why I'm suggesting that it be used.

**Comment by rsimha-amp** [comment]
While Docker appears to offer full isolation when it comes to persistent state (you're right), I don't believe it reserves resources like VMs do, and this may affect some of our tests. I'll spin this off into its own issue for further discussion, and if it turns out that we can do without full VMs, I'm open to making the change.

**Comment by rsimha-amp** [comment]
Update: The PR build time (including a `gulp build` and a full unit test run) is now down to around 15 minutes, with a total CPU time consumption of less than 20 minutes. With this, we can close out this issue.
