### ISSUE TITLE
amp-form: Support id submit-success & submit-error template resolution

### ISSUE THREAD

**Issue by Philbob** [ampproject/amphtml#9609]
## What's the issue?

At the moment amp-form will only allow the use of submit-success & submit-error templates, if those templates are nested inside the amp-form element itself.  I have been looking at a use case that would require me to be able to post an XHR and on success load the template in another part of the form.

Looking through the documentation suggests that it up to the individual component to determine how it's going to handle template resolution.  Are there any plans to extend amp-form to be able to look for success & error templates by id, or has it been implemented this way for a particular reason, if not can amp-form be extended for this scenario.

**Comment by aghassemi** [comment]
This has come up couple of times. Allowing `id` to optionally specify the template target is a reasonable request and I can't think of reasons not to support it.
/to @cvializ

**Comment by cvializ** [comment]
I'll have to check if there was an intentional reason for the current form template API, but I agree, this could be useful. Until that time, you might be able to use [the experimental `amp-bind`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-bind/amp-bind.md) extension to meet your needs. To use it in production you need to sign up for the origin trial, but it can help fill the gaps in some features.

There's [a similar request on StackOverflow](https://stackoverflow.com/questions/43918898/amp-form-show-same-html-after-form-submit-with-the-some-additional-elements/43922797#43922797) that I provide a sample workaround for. Maybe this could help your use-case for now

**Comment by Philbob** [comment]
excellent, thanks

**Comment by aghassemi** [comment]
Closing in favour of an earlier feature request for this: https://github.com/ampproject/amphtml/issues/7118
