### ISSUE TITLE
Explore the feasibility of using Docker containers instead of full VMs on Travis

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#9651]
From looking at .travis.yml, ampproject/amphtml enables `sudo: required` and uses full VMs with the trusty environment. While these are slow, they guarantee isolation between test instances, and resources allocated for each VM.

It appears that we currently use sudo in one place: to install chrome. If we can do away with the sudo requirement and use Docker containers, we may see a significant speed up in how PR jobs start up on Travis.

The purpose of this issue is to track the feasibility of using Docker containers over full VMs, and if so, to track the work required to make it so.

For reference, see [this](https://github.com/ampproject/amphtml/issues/9500#issuecomment-305324097) discussion in #9500

**Comment by cramforce** [comment]
Definitely worth researching with we can get rid of the `sudo` for Chrome.

**Comment by rsimha-amp** [comment]
For posterity, here is the documentation from Travis:

Blog post: https://blog.travis-ci.com/2016-11-08-trusty-container-public-beta
Documentation: https://docs.travis-ci.com/user/trusty-ci-environment/

**Comment by rsimha-amp** [comment]
It turns out that while using Docker containers instead of VMs on Travis reduces VM startup time, it has significantly increased build and test time, increasing the overall PR check round trip from < 20 mins to > 30 mins.

Compare https://travis-ci.org/ampproject/amphtml/jobs/238464404 (with this change) against https://travis-ci.org/ampproject/amphtml/jobs/238462066 (without this change).

**Comment by rsimha** [comment]
Reopening this old issue to revisit docker images, now that we don't use `sudo` since we use the `chrome` addon on Travis instead of installing it ourselves.
