### ISSUE TITLE
dvoytenko ooo

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#9681]
@amphtml-team @ampproject/a4a 

Hi All! I'll be out on vacation June 5th through June 28th. See you all soon and happy hacking!

**Comment by trodrigues** [comment]
I might submit that PR to remove the experimental flag from amp-access-laterpay sometime next week. Will anyone be able to merge that, or is there someone I should tag/mention? Would be nice to not leave it hanging around until you come back 😁

Also have a nice vacation!

**Comment by trodrigues** [comment]
I've created a PR for this at https://github.com/ampproject/amphtml/pull/9685

We still need to deploy production changes for one of our backend components related to this (happening early next week) but I've actually thought that it should be ok to remove the flag already, because this is only relevant to our customers and any of our customers that would use this would eventually be in contact with us anyway.

**Comment by dvoytenko** [comment]
@trodrigues Just assign mention @rudygalfi and he'll forward it along to the best person to review.
