### ISSUE TITLE
Support additional semantics for buttons on amp-user-notification

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#9694]
amp-user-notification currently supports [`dismiss` semantics](https://github.com/ampproject/amphtml/blob/master/extensions/amp-user-notification/amp-user-notification.md#usage). Depending on the message conveyed by the user notification, it may be desired to be able to capture additional kinds of user responses to the notification.

This FR proposes supporting the following *additional* semantics:
- `accept`
- `reject`

These should support `data-*-href` URLs that are requested upon the corresponding action and the `on="tap"` events. There should also be a storage story, but possibly we can just store that any interaction took place, which is already supported with `dismiss` today. This will need further discussion.

If we do this, we need to think though how this will impact additional areas of AMP like features that gate client ID issuance on amp-user-notification.

**Comment by cramforce** [comment]
My thoughts: We need to define semantics. Because the opt-out will be global and not per scope (while it is currently possible to have multiple notifications and accept scope.

Opt out should

- Store opt-out bit in Storage API
- Notify viewer about opt-out if present
- Optionally call opt-out endpoint on pub side.

Question: What should CID Service do? Suggestion: We reject the user notification promise, but CID Service produces the empty string instead of an error.

**Comment by aghassemi** [comment]
#9810 took over this issue for a more targeted solution. Still keeping this as a FR in the backlong

**Comment by aghassemi** [comment]
P3 as #9810 has partially addressed this.

**Comment by aghassemi** [comment]
Closing this as the main use-case is handled by `amp-consent`
