### ISSUE TITLE
Discover if (maybeBoolean) in linter

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#9740]
I'm not sure this may be possible in eslint due to lack of type info, but maybe we can find a way to opt out of the lint where it it OK:

Rule

`if (maybeBoolean)` 

should be a lint error if `maybeBoolean` is not actually always of `boolean` type (has value `false` or `true`), because if people really want to check whether it is null or an object they should write `if (maybeNull != null)` for much better performance.

Maybe we could require `!!boolean` or comparison like `!= null` inside of the if conditional.

**Comment by erwinmombay** [comment]
it's kind of possible, we can look up the variables raw type but this breaks down with any indirection (where we assign the value to another var declaration)

lmk if you think its still worth it

see: 
![hey](https://user-images.githubusercontent.com/354746/26842787-d8795154-4aa2-11e7-88d4-adf9388dca93.png)

**Comment by jridgewell** [comment]
I think this is [dubious](https://jsperf.com/if-falsey-vs-nullish).

**Comment by cramforce** [comment]
I think I was misunderstood. I only want to transform `if (object)` to `if (object != null)`. Nothing else.

**Comment by jridgewell** [comment]
Those are the last 4 cases in the jsperf.

**Comment by cramforce** [comment]
The relevant test would use `{}` instead of `true`. Unfortunately test editing is broken for me right now.

**Comment by cramforce** [comment]
The slowdown (if any) comes from having to call `valueOf()` method on the object to find out whether it is falsy.

**Comment by erwinmombay** [comment]
also maybe writing a custom conformance rule would be better for this task

**Comment by jridgewell** [comment]
jsperf's gone downhill. Here's an [updated one](https://jsperf.com/if-falsey-vs-nullish-2).

**Comment by cramforce** [comment]
Cool. Lets close this until @bmeurer convinces me otherwise :)

**Comment by bmeurer** [comment]
I'd argue that you should use `o === null` to check whether something is `null`, because `o == null` also yields true if `o` is `undefined` or `document.all` (thank you Internet Explorer!). If you want to check for `null` or `undefined`, write `o === null || o === undefined`. The performance difference can be noticeable compared to using *ToBoolean* (up to 15% faster on average for simple examples as outlined [here](http://benediktmeurer.de/2017/04/03/v8-behind-the-scenes-march-edition/)). Usually that 15% doesn't matter though. But what I learned from @trueadm and @developit is that avoiding the *ToBoolean* conversion can reduce the number of unnecessary deopts during startup; which mostly affected Crankshaft since at this point Ignition doesn't collect feedback for `ToBoolean` bytecodes (because TurboFan doesn't consume any feedback for this), but this will change over time, and then the deopt problem will be back again.

**Comment by cramforce** [comment]
This just reminds me that we need to do some investigations with respect to deopts in AMP's startup sequence.
