### ISSUE TITLE
Amp shadow - ShadowDOM v1 slots not supported 

### ISSUE THREAD

**Issue by rowangray** [ampproject/amphtml#9761]
ShadowDom V1 slots are not supported by firefox or safari < 10. And don't seem to be working with the polyfills that come with AmpShadow

I would usually polyfill these, but it seems that the shadyDom and ShadowDom polyfill are incompatible with AmpShadow.

**Comment by dvoytenko** [comment]
@rowangray Thanks for the report. These should be polyfilled already. Let me check where/why this might not be the case.

**Comment by dvoytenko** [comment]
@rowangray Correct. Slots were not polyfilled. For some reason I thought that they were. Could you point me to the slot polyfill that you'd normally do? I'll see what it'd take to integrate it on our end...

**Comment by dvoytenko** [comment]
@rowangray Thanks!

**Comment by jridgewell** [comment]
Validator support tracking issue: #10345.

**Comment by dvoytenko** [comment]
@rowangray I sent #10359 change that would, at least, hide the undistributed content. This way, the fallback story is available. I'm looking into the distribution itself as well.

However, my other question to you, since you have experience of using shadyDOM and other polyfills, what would happen if you were to pre-setup Shadow DOM polyfill before executing Shadow AMP? From what I can tell, it should work correctly with proper polyfill. Though some inconsistencies are possible, which would probably be easy enough to fix.

Do you have a minimalistic example running somewhere where ShadyDOM or other polyfills are used so I can test against them? One nuance: CSS isolation is relatively important for our use cases. So, hopefully, that'd be part of the polyfill.

**Comment by edhollinghurst** [comment]
Hi @dvoytenko, I've created a demo of the shadow-slot issue we're seeing:

https://www.edhollinghurst.com/amp-shadow-slot/amp-shadow-slot.html
(You'll need to refresh the page to get the PWA)

You'll see that in Chrome the AMP logo appears and is slotted in the correct place. However this does not happen in Firefox.

I did try using the Shadow DOM polyfill to see if this helped but unfortunately didn't have any luck with this.

Any advice with to get this working would be appreciated. Many thanks!

**Comment by dvoytenko** [comment]
@rowangray Thanks a lot! @torch2424 is looking into how to adopt shadow AMP on top of Shady DOM and similar polyfills.

**Comment by dvoytenko** [comment]
@rowangray We've made our Shadow API compatible with WebComponents.js (and it work with other polyfills). See docs [here](https://github.com/ampproject/amphtml/blob/master/spec/amp-shadow-doc.md#shadow-dom-api-and-polyfills). This should enable all other major features, including slots.

The pattern that the docs recommend should be the fastest. Using that pattern, platforms that already support SD will be unblocked immediately, while others will wait for polyfill install.

PTAL
