### ISSUE TITLE
Lightbox 2.0: image zoom/pan functionality

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#9977]
- [ ] pinch zoom
- [ ] double tap zoom
- [ ] pan
- [ ] vertical swipe to dismiss

**Comment by cathyxz** [comment]
FYI @spacedino, this is the demo URL I'm pushing to: https://amp-cathyxz.herokuapp.com/test/manual/amp-lightbox-viewer-optin.amp.html. It's a work in progress, but feel free to play around with it before our session tomorrow. 

It may be stale but hopefully not broken. I've refactored the code slightly so that the Lightbox Gallery (aka `amp-lightbox-viewer`) has the zoom/pan functionality from `amp-image-lightbox`.

**Comment by cathyxz** [comment]
So far we have WIP: 
- double-tap zoom
- panning
These things need to get fixed: 
- swiping doesn't work when swiping over the image, need to disable swiping while zoomed in and reenable swiping when zoomed out. 
- code cleanup

TODO:
- pinch zoom
- vertical swipe to dismiss (refactor: this should probably be handled by the lightbox-viewer, and not the ImageViewer).

**Comment by aghassemi** [comment]
*UX Review Notes*
- Demo requirements @cathyxz to provide (will eventually move to ABE)
  - picsum.photos image assets 
  - inline carousel
  - some with no desc, short desc, normal desc, some with ridiculously long descriptions
  - different image ratios (landscape and portrait) and one that fills the viewport.
  - a video
  - an ad
  - a tweet
- We may need to change the animation timing for `amp-carousel` - @spacedino to provide new timing
- We need proper icon - @spacedino to provide
- We need to default thumbnails for lightboxable types ( video, twitter, instagram, etc.. ) for cases we cannnot we find an image thumbnail and author has not provided one. - @spacedino to provide. 
- Question: Should we or author provide a entry point for lightboxable items? (even images?) Needs more discussions with @ericlindley-g. 
- Grid view: for thumbnails, do we keep ratio or square? (Square for now)
- Grid View: how many columns? should be responsive between 3-6? 
- Zoom and Pan: let's try double tap to zoom in and out and single tap for description.

**Comment by ericlindley-g** [comment]
Excellent notes!  Do you have more context on the question of entry points for lightboxable items, or should we just sync in real-time when I'm back?

**Comment by aghassemi** [comment]
We can chat later in details. Context is whether AMP should overlay any UI on top of elements that can go into lightbox mode. For now decision was not having AMP overlay anything but have the action API for authors to do so.

**Comment by ericlindley-g** [comment]
Gotcha — sounds good to chat later. I lean toward a default UI that can be customized or opted out of, rather than having nothing by default, since I think there's a lot of value in providing an affordance to users (more likelihood of engagement; higher probability of *good* UI, assuming that we provide a "good" affordance:)

But I'm sure there was some good discussion about this, so looking forward to getting caught up.

**Comment by aghassemi** [comment]
@ericlindley-g, @spacedino also thought the same regarding the value a default affordance would add. It sounds good to me as well.

@spacedino could you create some mocks with the UI you have in mind for a few common cases (image, video, tweet, ad?) before we discuss this in details?

**Comment by cathyxz** [comment]
This should be closed by these PRs: 
https://github.com/ampproject/amphtml/pull/12284
https://github.com/ampproject/amphtml/pull/12219
https://github.com/ampproject/amphtml/pull/12092
