### ISSUE TITLE
[amp-sidebar 1.0][Toolbar] Create Manual tests

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#9985]
Evaluate Scenarios to be supported and create manual tests for all possible scenarios

- [ ] Sidebar with no toolbar
- [ ] Sidebar with one toolbar - min media, min & max media, max media, min 0px, no media (this scenario should not build the toolbar.)
- [ ] Sidebar with multiple toolbars on different media
- [ ] Sidebar with Multiple toolbars on same media (users could position on top or bottom)
- [ ] Sidebar with Multiple toolbars on same media and same layout (This will look ugly you should discuss with UX/Product on how to handle this)
- [ ] Sidebar with only toolbar content - needs ux / product decisions - we don't want to show empty sidebar if the sidebar only has toolbar contents

**Comment by torch2424** [comment]
We decided the following in required UX meetings.

Multiple toolbars will not be supported. The default will be `position: fixed; top: 0;` for all default toolbars. If the user would like multiple toolbars, they should be using the [target](https://github.com/ampproject/amphtml/issues/9982) attribute.

Sidebar with only toolbar content decided we shall [not handle this edge case](https://github.com/ampproject/amphtml/issues/9984).

This has been partially fixed by: https://github.com/ampproject/amphtml/pull/10084

And will be completely fixed by: https://github.com/torch2424/amphtml/pull/8
